### ISSUE TITLE
Just a little more documentation

### ISSUE THREAD

**Issue by welcoMattic** [spatie/laravel-medialibrary#10]
Hi!

Thanks for your nice work to manage medias with models, it's really cool!

But, is it planned to write more documentation, I'm a little lost with only README file ... 
Or maybe some live examples?

Thanks a lot!

**Comment by freekmurze** [comment]
Thanks for you pr. Of which functionality would you like to see some more examples?

**Comment by welcoMattic** [comment]
Basically, examples with a real Model and an use case in a Controller. May I will write it later if you want?

**Comment by freekmurze** [comment]
Sure, I'll gladly accept pull requests that makes the documentation better.

**Comment by freekmurze** [comment]
We're currently rewriting the package and we'll rework the documentation as well.

**Comment by welcoMattic** [comment]
Ok, thank you.

**Comment by elieandraos** [comment]
@welcoMattic here is an example of implementation within a controller 
https://github.com/elieandraos/gaia-news/blob/master/src/Gaia/News/NewsController.php 

I inject a service class to handle the upload 
https://github.com/elieandraos/gaia-news/blob/master/src/PSR4/Gaia/Services/NewsService.php 

just follow the store() method inside the controller
