### ISSUE TITLE
Event system?

### ISSUE THREAD

**Issue by cviebrock** [spatie/laravel-medialibrary#100]
I was trying to write some functionality to add custom properties to a Media object after it has been attached to my models (figuring out average colour, in my case).

I can't use `Model::created(...)` because in FileAdder.php we have:

```php
        ...
        $this->subject->media()->save($media);

        $this->fileSystem->add($this->pathToFile, $media, $this->fileName);
        ...
```

The actual file doesn't get saved to the filesystem until _after_ the Eloquent model is created.  And, there don't seem to be any other Eloquent events fired after that initial save().

Any suggestions on how I can achieve this (without necessarily queuing a job to be processed later)?

**Comment by freekmurze** [comment]
The original file will have been added to the medialibrary after `toCollectionOnDisk` has done its work. The converted files will be created later (if they are queued).

You could use a custom Media model. Let your custom one extend the Media class provided by this package. Then override the `toCollectionOnDisk`-method. Add your own logic after calling the parent method.

Thoughts?

**Comment by cviebrock** [comment]
I was hoping not to extend the model (mostly to keep things simple).  What about adding a package-specific event, e.g.:

```php
$this->fireModelEvent('media.stored', false);
```

after the file is added?  Then I can hook into that event in my own code.

**Comment by freekmurze** [comment]
I'm ok with events being added to the package. On first thought, I think these would be handy to have:
- MediaHasBeenStored(Media)
- ConversionHasFinished(Media, conversionName)
- MediaHasBeenDeleted(mediaId)
- CollectionHasBeenCleared(Media, collectionname)

I'll try to add these to the package soon, but if you need this quick, I'd welcome a PR that adds this.

**Comment by cviebrock** [comment]
MediaHasBeenDeleted(mediaId) could just be handled using the built-in `eloquent.deleted` event on the Media model, I'd think.  But I have a PR almost ready for the other events ... as soon as I can figure out how to write tests for them.  :)

**Comment by freekmurze** [comment]
`CollectionClearedEvent`, `ConverionCompleteEvent`, `MediaAddedEvent` are available in v3.10.0

**Comment by ziming** [comment]
Do you mean ConversionCompleteEvent instead? @freekmurze

**Comment by freekmurze** [comment]
Yeah you're right, that was a typo.

Seeing that made me think about the names of all events. I renamed them all in v3.10.1 to make them more readable:  `CollectionHasBeenCleared`, `ConversionHasBeenCompleted`, `MediaHasBeenAdded`

Normally this would be a breaking change, but as not many people will have starting using these events, I'm treating it as a bugfix release.
