### ISSUE TITLE
How to use laravel-medialibrary and ctf0/Laravel-Media-Manager both at a time

### ISSUE THREAD

**Issue by harryprasath** [spatie/laravel-medialibrary#1000]
Im not able to use laravel-medialibrary and ctf0/Laravel-Media-Manager both at a time because of the zipstream version..
laravel-medialibrary requries zipstream 0.4.1 and ctf0/Laravel-Media-Manager requries 0.5.0.
So can you please look into this. Please find the screenshot attached.

![image](https://user-images.githubusercontent.com/8749419/38031082-07b643de-32b8-11e8-84df-c230a1728413.png)

**Comment by freekmurze** [comment]
I had troubles with getting the `0.5.0` version to work, so I specifically targetted the `0.4.1` version.

I'll try to look into this soon.

**Comment by harryprasath** [comment]
Thanks for your reply please look in to this soon

**Comment by freekmurze** [comment]
0.5.* still gives problems... Closing this for now.

**Comment by harryprasath** [comment]
But its not fixed yet.. Can we close it once its fixed?

**Comment by pankajsanam** [comment]
I am having the same problem. Hopefully you guys figure something out.

**Comment by estaticfear** [comment]
i'm having the same problem :(
