### ISSUE TITLE
(Question) How to broadcast ConversionHasBeenCompleted event to Pusher?

### ISSUE THREAD

**Issue by kingsloi** [spatie/laravel-medialibrary#1001]
I have a Vue.js SPA. In my app, the admin user uploads an image (drag & drop) for an item in the same spot the images are listed. 

Currently, the user uploads an image, and have I have a 5 second reload timer which triggers after an image is uploaded (5 seconds to account for upload -> conversion -> upload to s3) to display the thumbnail in the list.

The whole upload & conversion process takes roughly 1 second, so rather than wait an additional 4 seconds per upload, I want to use Pusher to update my view when the thumbnail conversion has triggered, rather than wait. 

I've rarely needed to override a composer package class, let alone an event. I'm just wondering what you guys can recommend?

**Comment by freekmurze** [comment]
Right now the events by this package are not broadcasted.

The easiest way to achieve broadcasting events right now is to listen for the events of the package and then broadcast your own events. You should listen for those own events clientside.
