### ISSUE TITLE
Modifying the file_name when media-conversions are missing leaves file in inconsistent state

### ISSUE THREAD

**Issue by tomlankhorst** [spatie/laravel-medialibrary#1006]
When renaming a file with media-conversions, both the file and its conversions are renamed by the `Filesystem` through an Event observer. 
When an expected conversion does not exist this throws an exception, canceling the `save` action. 
Now, the `file_name` attribute is not changed but the original file name is already changed, leaving the file in an inconsistent state. 
I think that we should not assume that conversions exist, for the following reasons:

- Conversions might be defined later than when the media item was added
- Conversions might still be generating
- Conversions might fail (thumbnail generation, failing binaries, optimizers, etc.)

So, I suggest checking whether a conversion exists, before trying to rename it. 

_When the original file does not exist, it throws and fails to save as well, but at least it did not rename any files and this is an actual unexpected situation._

**Comment by freekmurze** [comment]
We'll continue the conversations in #1007
