### ISSUE TITLE
Bug in documentation.

### ISSUE THREAD

**Issue by Tjoosten** [spatie/laravel-medialibrary#1012]
Hi, 

I was wondering and trying to install media-library. But i think i found a error in the documentation. 
https://docs.spatie.be/laravel-medialibrary/v7/converting-images/defining-conversions. The docs says that i need to include. 

`Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia`

But when i do that just like the other things in the docs i get my issue. 

`PHP Fatal error:  Interface 'Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia' not found in D:\kern\app\Article.php on line 22
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in D:\kern\vendor\laravel\framework\src\Illuminate\Container\Container.php:918`

Tried to tinker with it and it looks that i needed `Spatie\MediaLibrary\HasMedia\HasMedia`
not `Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia`

Bdw thanks for the work on the package and happy easter

**Comment by freekmurze** [comment]
Feel free to send a PR to the docs, there's an `edit` button on every page. 👍

**Comment by Tjoosten** [comment]
Alright will love to it in my free time!


2018-04-03 11:58 GMT+02:00 Freek Van der Herten <notifications@github.com>:
