### ISSUE TITLE
custom path folder title ?

### ISSUE THREAD

**Issue by laravelish** [spatie/laravel-medialibrary#1015]
Hello i made a custom path generator like this

```php
<?php

namespace App\Helpers;

use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\PathGenerator\PathGenerator;

class CustomPathGenerator implements PathGenerator
{
    /**
     * Get the path for the given media, relative to the root storage path.
     *
     * @param \Spatie\MediaLibrary\Media $media
     *
     * @return string
     */
    public function getPath(Media $media): string
    {
        $model = class_basename($media->model_type);
        
        return $model . '/' . $media->getTypeFromMime() . '/' . date("Y-m-d") . '/' . md5($media->name);
    }

   ....
   .....
   .......
}
```

but is it possible to replace the `date("Y-m-d")` with my `App\Post slug` ?

**Comment by laravelish** [comment]
this fixed my issue [https://docs.spatie.be/laravel-medialibrary/v7/api/adding-files#usingname](https://docs.spatie.be/laravel-medialibrary/v7/api/adding-files#usingname)

now i can use `str_slug($model->name)`

Thanks for this amazing package.

**Comment by laravelish** [comment]
hmm but it creates a folder inside `str_slug($media->name) ` like this folder structure
Folder_title
         -- fa3a8a3eab2e05db2fed915333a2f00c
  -- fa3a8a3eab2e05db2fed915333a2f00c512.jpg

![screenshot_2](https://user-images.githubusercontent.com/1642161/38167316-8cc6e100-3533-11e8-82a7-2869b4114070.png)

why is that ?

**Comment by TVke** [comment]
Hey @laravelish 

I think it is because of the `md5(...)`. 
The `getPath` method creates the path (the name not included).

Hope this helps.

**Comment by laravelish** [comment]
ok
