### ISSUE TITLE
Placeholder when image has not been generated

### ISSUE THREAD

**Issue by nycooookie** [spatie/laravel-medialibrary#1017]
Is there a way to display something like a placeholder / dummy image, when the actual image has not been generated yet (when using queues)?

----

Scenario: There's a page to edit the user profile (including image). After saving, the user is redirected to an overview page, where the updated image is displayed. `hasMedia()` returns `true`, but the image has not necessarily been generated yet when using queues. Instead of displaying a broken (nonexistent) image, I'd like to show a placeholder instead (e.g. image with text "image is being generated").

Is there some way to do that, or how would you handle such situation? I would think this is not an uncommon case.

(However awesome package! 🙌)

**Comment by freekmurze** [comment]
In case the image hasn't been generated yet, `getUrl` and `getPath` methods will return `null`. 

You could do add a method like this to your model that handles the `null` case:

```php
public function avatar() {
   $pathToPlaceholder = '...';

   return $this->getFirstMediaUrl('avatar', 'thumb') ?? $pathToPlaceholder;
}
```

**Comment by nycooookie** [comment]
Ahh easier than I thought 😅
Thank you!

**Comment by chris-faulkner** [comment]
I just tried this and couldn't get it to work. I set queue to Database and uploaded an image (which has 2 conversions). I am not running the queue to process the images but it still returns the url for the conversion which doesn't exist:
`dd($this->getFirstMediaUrl('images', 'thumb'));`
This is what it dumps out as the url:
![screenshot 2018-05-07 23 46 36](https://user-images.githubusercontent.com/25483015/39728948-4c117a2c-5251-11e8-8078-46a6d2241249.png)
So it's trying to load the conversion but it won't exist until the queue processes it.

I'm probably doing this wrong, but if you could spare a moment to correct me it would be very helpful.
Perhaps I need to check if the file exists separately?

Thanks for the great package!
