### ISSUE TITLE
How to set public visibility to each file for digitalocean spaces ? (s3 driver)

### ISSUE THREAD

**Issue by netanelwebninja** [spatie/laravel-medialibrary#1018]
Hey,

I have Laravel 5.6 app, Im using digitalocean spaces for filesystem driver (its like s3, using same s3 driver for laravel).

I installed the laravel-medialibrary package, and upload files, works like a charm.

The problem is that all the files that uploaded to Digitalocean spaces are private, normally when I use laravel Storage facade I fix it using Storage:: setVisibility but I didnt found a way to do it with medialibrary.

I just want all the uploaded files to be visibility = public

Thanks

**Comment by thisiskaden** [comment]
Add visibility header in config file.

```
config/medialibrary.php

    'remote' => [
        /*
         * Any extra headers that should be included when uploading media to
         * a remote disk. Even though supported headers may vary between
         * different drivers, a sensible default has been provided.
         *
         * Supported by S3: CacheControl, Expires, StorageClass,
         * ServerSideEncryption, Metadata, ACL, ContentEncoding
         */
        'extra_headers' => [
            'CacheControl' => 'max-age=604800',
            'visibility' => 'public',
        ],
    ],
```

**Comment by netanelwebninja** [comment]
@thisiskaden Thanks !

**Comment by dominikager** [comment]
Hi, i just migrated from S3 to Digitalocean. Now i have the problem that every asset is private.
Doest anybody has a solution?

**Comment by johnpuddephatt** [comment]
@dominikager I think you can set `'visibility' => 'public'` in the config for your DO filesystem driver

**Comment by petsoukos** [comment]
> Add visibility header in config file.
> 
> ```
> config/medialibrary.php
> 
>     'remote' => [
>         /*
>          * Any extra headers that should be included when uploading media to
>          * a remote disk. Even though supported headers may vary between
>          * different drivers, a sensible default has been provided.
>          *
>          * Supported by S3: CacheControl, Expires, StorageClass,
>          * ServerSideEncryption, Metadata, ACL, ContentEncoding
>          */
>         'extra_headers' => [
>             'CacheControl' => 'max-age=604800',
>             'visibility' => 'public',
>         ],
>     ],
> ```

Is there a way to set this per upload and not globally ?

**Comment by johnpuddephatt** [comment]
I haven't tested it but I think you need to add 'public' as a third parameter, as shown below: 

```
$path = Storage::disk('s3')->put('directory_name/'.$user->id, $request->file('file_name'), 'public');
```

**Comment by petsoukos** [comment]
> I haven't tested it but I think you need to add 'public' as a third parameter, as shown below:
> 
> ```
> $path = Storage::disk('s3')->put('directory_name/'.$user->id, $request->file('file_name'), 'public');
> ```

But this doesn't use media library or I'm not getting it.

**Comment by johnpuddephatt** [comment]
Sorry I forgot this was in spatie/laravel-medialibrary, I ended up here because I was looking for a general Laravel solution.

Try this: https://github.com/spatie/laravel-medialibrary/issues/241#issuecomment-349455094 <https://github.com/spatie/laravel-medialibrary/issues/241#issuecomment-349455094>

**Comment by chonchol-alzaf** [comment]
> Add visibility header in config file.
> 
> ```
> config/medialibrary.php
> 
>     'remote' => [
>         /*
>          * Any extra headers that should be included when uploading media to
>          * a remote disk. Even though supported headers may vary between
>          * different drivers, a sensible default has been provided.
>          *
>          * Supported by S3: CacheControl, Expires, StorageClass,
>          * ServerSideEncryption, Metadata, ACL, ContentEncoding
>          */
>         'extra_headers' => [
>             'CacheControl' => 'max-age=604800',
>             'visibility' => 'public',
>         ],
>     ],
> ```

thanks. its worked
