### ISSUE TITLE
Problema no pacote laravel-medialibrary

### ISSUE THREAD

**Issue by jhonny11melo** [spatie/laravel-medialibrary#1023]
Call to a member function getUrl() on null (View: C:\xampp\htdocs\blog-vuejs2\resources\views\layouts\app.blade.php) (View: C:\xampp\htdocs\blog-vuejs2\resources\views\layouts\app.blade.php)

**Comment by brendt** [comment]
Please refer to the [documentation](https://docs.spatie.be/laravel-medialibrary/v7/introduction) to learn about how to use the media library.
