### ISSUE TITLE
Medialibrary is converting the thumb image into JPG

### ISSUE THREAD

**Issue by clementbirkle** [spatie/laravel-medialibrary#1024]
Hello,

 I am using Medialibrary V.5

When I upload a PNG image, the Medialibrary is converting the thumb image into JPG in bad quality. How can I resolve this problem and keep it in PNG? 

Precision:
- the orignal image in PNG is in good quality + large resolution
- I use imagick

Thank you in advance

**Comment by clementbirkle** [comment]
Finally, I found a partial solution with the method: ->keepOriginalImageFormat()
But with this, the SVG file wasn't converted to JPG anymore. I don't want this way. So I think I need to edit Conversion::getResultExtension() method... is it the best solution ? If yes, how can I override properly this method ?

Thank you in advance

**Comment by brendt** [comment]
I'm afraid that if you're using v5 of the medialibrary, I won't be able to help you solve this. There have been numerous bugfixes in v6 and v7, though updating means you'll have to do some manual work. You can read the upgrading guide here: https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md

Unfortunately, while you can override the model class via config, there's no way to override the conversion class.
