### ISSUE TITLE
Imagick driver does not work

### ISSUE THREAD

**Issue by taliptako** [spatie/laravel-medialibrary#1028]
There is a option for image driver you can use imagick or gd but in any case gd driver used.If you set image driver to imagick and delete gd extension for php you will see the error about gd extansion missing ..

**Comment by brendt** [comment]
Could you share the error you're getting? I've got GD bundled in my compiled PHP installation and have no easy way to disable it. I'm sure Imagick is used to render images, but maybe GD is used somewhere behind the scenes still, causing the error. If you can provide a stack trace, it might clarify where the error is happening.

**Comment by taliptako** [comment]
Here is the stack trace [](https://kopy.io/J9iil#UbuiI9rPGhLeL8)
I'm sure that i set my image driver to imagick but as you said probably gd is still used somewhere behind scene.

**Comment by brendt** [comment]
Thanks for the input! I was able to pin this problem down. It was in `spatie/image`, when the width or height of an image was requested.

This commit fixed it: https://github.com/spatie/image/commit/9b7a027b618943c5fd6136285f0ead28c4f75c1e

This is the tag: https://github.com/spatie/image/releases/tag/1.4.2

You should be able to just run `composer update` if you're on the newest medialibrary version, and `spatie/image` should update automatically.

**Comment by taliptako** [comment]
@brendt Unfortunately still same ..

**Comment by brendt** [comment]
Is it a different error?

**Comment by taliptako** [comment]
@brendt I think we should add a method for configuring image driver globally in medialibrary package and it should set driver for spatie/image only one time
 and then we dont need to add ->useImageDriver(config('medialibrary.image_driver')) method when we use Image::load() because in some places you guys didnt use ->useImageDriver(config('medialibrary.image_driver')) so this causing an error.
I just search in this package for usages of Image::load() and add all of them ->useImageDriver(config('medialibrary.image_driver')) method and its works now. But instead of doing this i think we should have one method for setting image driver.

**Comment by brendt** [comment]
Hi @taliptako 

This should now be fixed everywhere with 7.1.5 (https://github.com/spatie/laravel-medialibrary/releases/tag/7.1.5).
