### ISSUE TITLE
Breaking change in minor release

### ISSUE THREAD

**Issue by Numline1** [spatie/laravel-medialibrary#1029]
Hello,

the update from 7.0.* to 7.1.* caused an issue where all of our media conversions suddenly experienced a 404 error. I've noticed the code handling file naming for our thumbnails got changed and the package started returning an incorrect route (/conversions/thumbnail500.jpg got changed into /conversions/prefix_thumbnail500.jpg). This resulted in us having to regenerate all the images on all the servers (which took a while).

I was under the impression that this package follows semver, yet, breaking change made it into a minor version update.

**Comment by brendt** [comment]
Hi @Numline1 

The conversion name change happened in 7.0: 

> all converted files should now start with the name of the original file.

https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md#from-v6-to-v7

**Comment by freekmurze** [comment]
To my knowledge the functionality we mentioned was introduced in 7.0. Which commit are you referring to?

**Comment by Numline1** [comment]
Hi, the way we've discovered this issue was an upgrade to Laravel 5.6 (we were on 5.3 previously). This also came with medialibrary upgrade. All of these changes went through a regular lifecycle, meaning being deployed on dev and test environments first. Composer.json and composer.lock were already updated at this point, the package was working fine (with all the changes to conversions made in model classes). The day we deployed to production, everything was fine as well (This was 7.0.0, the version was only restrained to stay within the same major release), until someone hit "composer update" accidentally. This updated medialibrary to 7.1.3, which somehow started the issue with conversions / renamed thumbnails. This was a huge messup (mostly on our side, but the thumbnail issue took us by surprise).

The commits I was referring to were:

https://github.com/spatie/laravel-medialibrary/commit/f9e1f015607d6dbfe42db4c14b5d37f091f5541a
and the release message saying "Fix for renaming files when not all conversions are present" (I'm not sure what this refers to exactly).

Just to sum up, I'm not blaming anyone (especially not Spatie guys), but something went wrong and I'm trying to figure out what and why (why was 7.0 working fine). Thanks for any feedback.

**Comment by freekmurze** [comment]
That commit is unrelated to the work that has been done around putting the original file name somewhere in the filename of a conversion.

Are you 100% sure that you used 7.0 at some point on your production server?

I'm pretty certain that if 7.1 does not work because of changed conversion names, 7.0 will also not work for you.

**Comment by Numline1** [comment]
Hi, I'll check our commit history and respective composer.jsons and composer.locks to see what went wrong. I'm sure it was an issue on our side, just gotta find how it happened. Thanks for the help, I'll post an update if I find something that could explain this.
