### ISSUE TITLE
get directory path to file ?

### ISSUE THREAD

**Issue by laravelish** [spatie/laravel-medialibrary#1031]
Hello

how can i get the directory path to the file ?

because if i use `$media->getFirstMediaPath();`
i returns `/home/admin/web/sddsd.com/public_html/storage/app/public/Post/video/video-01-04-2018/1-4-2018__75618.mp4`

but i need to return it like this

`/home/admin/web/sddsd.com/public_html/storage/app/public/Post/video/video-01-04-2018/`

**Comment by brendt** [comment]
You can use PHP's `pathinfo` function: http://php.net/manual/en/function.pathinfo.php

```php
pathinfo($media->getFirstMediaPath(), PATHINFO_DIRNAME);
```
