### ISSUE TITLE
registerMediaConversions error with Custom Model

### ISSUE THREAD

**Issue by woodgates** [spatie/laravel-medialibrary#1032]
Hi.
I'm creating a custom Media Model and I'm receiving and error message. 

This is my custom Model (empty to test):
```
namespace App\Models;
use Spatie\MediaLibrary\Models\Media as BaseMedia;

class WgtMedia extends BaseMedia
{

}
```

This is my medialibrary.php:
 ` 'media_model' => App\Models\WgtMedia::class,`

This is my AbstractComponent Class:
```

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Image\Manipulations;
//use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

abstract class AbstractComponent extends Model implements HasMedia
{
  use HasMediaTrait;
  public function registerMediaConversions(WgtMedia $media = null)
{
    $this->addMediaConversion('square')
          ->fit(Manipulations::FIT_CROP, 320, 320)
          ->sharpen(10);

    $this->addMediaConversion('thumb')
          ->height(320)
          ->sharpen(10);

    $this->addMediaConversion('mini')
          ->height(150)
          ->sharpen(10);
}
```

This is the error I'm getting in my AbstractComponent class:

> 
"Declaration of App\Models\AbstractComponent::registerMediaConversions(?App\Models\WgtMedia $media = NULL) must be compatible with Spatie\MediaLibrary\HasMedia\HasMedia::registerMediaConversions(?Spatie\MediaLibrary\Models\Media $media = NULL) ◀"

What I'm missing?

**Comment by TVke** [comment]
Hi @woodgates 

I just copied your code in an empty project with a clean install of the medialibrary and it works perfectly.
Maybe a composer update would fix it.

Here is the code I used (that works):

``` php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Image\Manipulations;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

abstract class AbstractComponent extends Model implements HasMedia
{
    use HasMediaTrait;

    public function registerMediaConversions(WgtMedia $media = null)
    {
        $this->addMediaConversion('square')
            ->fit(Manipulations::FIT_CROP, 320, 320)
            ->sharpen(10);

        $this->addMediaConversion('thumb')
            ->height(320)
            ->sharpen(10);

        $this->addMediaConversion('mini')
            ->height(150)
            ->sharpen(10);
    }
}
```

And the model:

``` php
namespace App\Models;

use Spatie\MediaLibrary\Models\Media as BaseMedia;

class WgtMedia extends BaseMedia
{

}
```

Hope this helps.

greetings
Thomas

**Comment by woodgates** [comment]
Hi @TVke 

I updated composer and I still get the same error. I'm using Laravel 5.6 and "spatie/laravel-medialibrary": "^7.0.0"

Did you changed the medialibrary .php? If so, how?

**Comment by TVke** [comment]
Hi @woodgates 

I changed my medialibrary config file like this:

`'media_model' => \App\Models\WgtMedia::class,`

**Comment by woodgates** [comment]
Hi @TVke 

Can it be related with the access level of the Classes, or the folder permissions?

**Comment by TVke** [comment]
Hi @woodgates 

It is possible, but it is probably something that calls the `registerMediaConversions ` method that generates the error. Maybe delete your vendor directory and then `composer install` again.

**Comment by brendt** [comment]
PHP doesn't allow the following:

```php
class A 
{
    public function test(A $a) {}
}

class B extends A 
{
    public function test(B $b) {}
}

$b = new B();
```

Allowing subclasses of typehints would break [LSP](https://en.wikipedia.org/wiki/Liskov_substitution_principle). There's a lot of theory on the why and how, if you're interested you should lookup "variance and contra variance".

Anyways the fix here is to still use `Media` as type hint, and not your own implementation, you will be able to use your implementation, but you're not able to type hint it.

```php
public function registerMediaConversions(Media $media = null) {}
```

**Comment by woodgates** [comment]
@brendt 
Thanks Brendt, I'll try to make it work that way.

Just one last comment: In this case, as my model is named WgtMedia laravel is looking for the "wgt_table". Maybe it can be mentioned in the Docs that your table name should be according to the custom Model Name.

My Best.
