### ISSUE TITLE
Incorrect doc block for interface

### ISSUE THREAD

**Issue by afraca** [spatie/laravel-medialibrary#1034]
I noticed how the interface specifies a different return type for `getMedia` as the trait, see return types here:
https://github.com/spatie/laravel-medialibrary/blob/7.1.4/src/HasMedia/HasMedia.php#L50
https://github.com/spatie/laravel-medialibrary/blob/7.1.4/src/HasMedia/HasMediaTrait.php#L217

**Comment by freekmurze** [comment]
Fixed
