### ISSUE TITLE
Can't Remove This Package

### ISSUE THREAD

**Issue by b3smith13** [spatie/laravel-medialibrary#1042]
I'm a little new to working with packages but as far as I can tell I've deleted all files relevant to this package from my laravel site but every time I run a php artisan command it reinserts itself into my /bootstrap/cache/packages.php file. Can anyone help me get this removed once and for all? Thanks in advance!

**Comment by marksparrish** [comment]
You need to delete it from your composer.json file.

**Comment by marksparrish** [comment]
I found this on laracast.com

https://laracasts.com/discuss/channels/laravel/how-properly-remove-package-with-auto-discover?page=1
