### ISSUE TITLE
Media::$model Member has protected access

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-medialibrary#1043]
Since some time I get `Member has protected access` in PhpStorm as error-message when I access the `model` property of the `Media` model.

It looks like it's cause by the eloquent query builder:
https://github.com/illuminate/database/blob/6c2e190d30b53e61851f76e23854c627306a0214/Eloquent/Builder.php#L29-L34

So far I see it this doesn't produce a real error, in my implementation, but it doesn't look nice. 
Do you have an idea how to solve this - without renaming the columns and causing BC.

Even if I would say that something like `parent`, `subject` or whatever would be better - but this isn't my goal.

**Comment by freekmurze** [comment]
I'm going to leave things as they are for now, but I'll consider renaming the relation when creating a new major version of the package.

**Comment by Gummibeer** [comment]
@freekmurze Ok, but you also have no idea how to solve this without renaming?

**Comment by freekmurze** [comment]
I'm currently creating the next major version on the `v8` branch. I'm not seeing the message you're describing, so I'm inclined to just leave it as is (maybe this has been solved in PhpStorm?).

Feel free to submit a PR to the `v8` branch, should you think this still needs to be changed.
