### ISSUE TITLE
Quality of converted images

### ISSUE THREAD

**Issue by gerciljunio** [spatie/laravel-medialibrary#1045]
I've already installed all the necessary packages and described in the [documentation](https://docs.spatie.be/laravel-medialibrary/v6/installation-setup#optimization-tools)

I [have an image](https://s3.amazonaws.com/toaberto/media_dev/b53b3a3d6ab90ce0268229151c9bde11/c/small.jpg), 260x260px, with the following conversion:

```
$this->addMediaConversion('large')
 ->width(1000)
 ->height(1000)
 ->optimize()
 ->nonQueued();
```

the image converted to 1000x1000px [is this](https://s3.amazonaws.com/toaberto/media_dev/b53b3a3d6ab90ce0268229151c9bde11/c/large.jpg)

and also has a conversion to 600px

```
$this->addMediaConversion('medium')
 ->width(600)
 ->height(600)
 ->optimize()
 ->nonQueued();
```

the image converted to 600x600px [is this](https://s3.amazonaws.com/toaberto/media_dev/b53b3a3d6ab90ce0268229151c9bde11/c/medium.jpg)

and also has a conversion to 1000px

```
$this->addMediaConversion('large')
 ->width(1000)
 ->height(1000)
 ->optimize()
 ->nonQueued();
```

the image converted to 1000x1000px [is this](https://s3.amazonaws.com/toaberto/media_dev/b53b3a3d6ab90ce0268229151c9bde11/c/large.jpg)

Is this the expected result and am I demanding too much for the small size of the image or should the package improve the quality even if an image is small?

thanks!

**Comment by freekmurze** [comment]
I guess it is normal, your original image is just too small.
