### ISSUE TITLE
eager loading not working(Model::with('media'))

### ISSUE THREAD

**Issue by JinalSomaiya** [spatie/laravel-medialibrary#1047]
using Version "spatie/laravel-medialibrary": "^6.0.0"

I am trying to fetch images of Listing Model and display it using foreach loop.
also used eager loading 'with' method with Listing Model.
So. How to avoid multiple database requests?

My Code is:
Controller File:
           $listing = Listing::with('media')->findOrFail($listingId);
           return view('dealer.inventory.inventory-other-details', compact('listing'));

View Blade File:
                  @foreach($listing->getMedia('damage_photos') as $image)
                            var file = {
                                    name: '{{ $image->file_name }}',
                                    size: '{{ $image->size }}',
                                    url: '{{ $image->url }}'
                                };
                            myDropzone.options.addedfile.call(myDropzone, file);
                            myDropzone.options.thumbnail.call(myDropzone, file, file.url);
                            myDropzone.emit("complete", file);
                            myDropzone.files.push(file);
                            file.previewElement.id = file.name;
                        @endforeach

and also used @foreach($listing->media as $image)

All works, but it turns out a lot of queries to the database, please tell me how to avoid this

Thank you.

**Comment by freekmurze** [comment]
`getMedia` will perform it's own queries to lookup the right data. 

If you perform `YourModel::with('media')` the media will have all media loaded. If you go that route, you should take care of filtering the `$yourModel->media` collection yourself.

**Comment by JinalSomaiya** [comment]
I also tried with using $yourModel->media but same queries used.
no difference showed me.
why?

**Comment by kamalkhan** [comment]
You may simply add a custom relationship method to your model that you can use to eager load all media collections or even a specific media collection.

```php
    // 'attachments' media collection
    public function attachments()
    {
        return $this->media()->where(function ($query) {
            $query->where('collection_name', 'attachments');
        });
    }
```

Now, to eager load, you have the following abilities:

- `\App\Listing::with('attachments')->get()`
- `$listing->load('attachments')`

**Comment by EricBusch** [comment]
> You may simply add a custom relationship method to your model that you can use to eager load all media collections or even a specific media collection.

@kamalkhan This results in an N+1 problem... at least it did for me.

To properly eager load media models from a single Media Library Collection, you should do something like this:

```php
use Illuminate\Database\Eloquent\Relations\MorphMany;

$listings = \App\Listing::with([
    'media' => function (MorphMany $query) {
        $query->where('collection_name', 'attachments');
    }
])->get();
```

This will eager load all of your attachments for each model without eager loading other collections. This can be useful if you have lots of collections for a single model and those collections have a lot of records but you only want to return Media for a specific collection.

## EXAMPLE

I have 4 Models (`\App\Resource`) and each Model contains 2 single media collections: `thumbnail` and `preview`.

Let's take a look at 2 queries...

**QUERY 1**

```php
$resources = Resource::with(['media'])->get();
```

This query results in: 
- Total queries: 2 
- Total Media models hydrated: **8**

**QUERY 2**

```php
use Illuminate\Database\Eloquent\Relations\MorphMany;

$resources = Resource::with([
    'media' => function (MorphMany $query) {
        $query->where('collection_name', 'thumbnail');
    }
])->get();
```

This query results in: 
- Total queries: 2 
- Total Media models hydrated: **4**

The 2nd query reduces the number of hydrated Media models by half. Reducing the number of hydrated models reduces the amount of memory usage of your page.

Hope this helps!

**Comment by kamalkhan** [comment]
@EricBusch I don't think that's entirely true.

Your **first query** is collecting both the `thumbnail` and the `preview` media collections which results in 8 hydrations (4 thumbnail and 4 preview collections)

Whereas, your **second query** is only accessing the thumbnail collection, hence only 4 hydrations (only 4 thumbnail collections).

But as far as collecting both the collections, your second query will have 2 queries as opposed to your first query which i think will have 4 queries. But still, your first query isn't using the relationship I suggested.

**Comment by bhulsman** [comment]
@EricBusch That gave me a good start and I came up with the following. Imagine a product list...

```
<?php

class Product extends Model implements HasMedia
{
    use InteractsWithMedia;

    public function featuredImage(): MorphOne
    {
        return $this->morphOne(Media::class, 'model')->where('collection_name', '=', 'featured');
    }
}
```

^ A product has one featured image, which is shown in de product list for every product.

```
<?php

$products = Product::query()->with(['featuredImage'])->get();
```

^ To eager load the featured images, in a controller for example.

```
@if($featuredImage = $product->featuredImage)
    <img src="{{ $featuredImage->getUrl() }}" alt="" />
@endif
```

^ Check if there is a featured image and display it.

This avoids eager loading other image collections for the product and should have decent performance!
