### ISSUE TITLE
SoftDeletes trait on parent class

### ISSUE THREAD

**Issue by dwhite-nep** [spatie/laravel-medialibrary#1049]
https://github.com/spatie/laravel-medialibrary/blob/3683133d8c6a585225e7473d2a37c843de181e35/src/HasMedia/HasMediaTrait.php#L44

This soft deletes check does not currently work on classes that inherit the SoftDeletes trait.  I was able to get it to work in my code by moving the SoftDeletes trait to the child classes but it seems like it would work if `trait_uses_recursive` was changed to `class_uses_recursive` which would return all inherited traits.

**Comment by freekmurze** [comment]
Thanks you for your research. Please PR this.
