### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by rafailml** [spatie/laravel-medialibrary#1052]
Hi guys, and thanks for great package. I have few questions about using media library.

1. How to make getUrl() to return https:// based url. Now it returns http:// 

2. Is it posible to get all model records with their first images? Something like Manufacturer::get(). Now I'm looping over all records and calling getFirstMediaUrl for each record which does not look elegant.

Thanks for your help.

**Comment by TVke** [comment]
Hi @rafailml 

1. the base url is retrieved from the `filesystems.php` config file (if you have not touched it, it will take the url set in the `.env` file at `APP_URL`)

2. There is no helper function to list the first images. If you want a cleaner way, you can always place the logic in your model in a static function or maken a scope to clean up the query

Hope this helps

greetings
Thomas
