### ISSUE TITLE
Custom path not working correctly

### ISSUE THREAD

**Issue by SamuelNitsche** [spatie/laravel-medialibrary#1053]
I want to store my files in a folder named like the model to which they belong. In my case, the model is called "Serie". I have created a custom path generator and in the getPath method I return the attribute "model_id". For "Serie" I created a media collection called "image" which contains a single file. Therefore, existing files are overwritten during upload. When uploading for the first time, everything works as expected. With the second upload the old file is deleted but the new file is not saved.
Have I missed something in the configuration or is this a bug?
Thanks for your help!

**Comment by SamuelNitsche** [comment]
Thanks for your help!

My path generator looks like this. 

```
<?php

namespace App\Generators\CustomPathGenerator;

use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\PathGenerator\PathGenerator;

class CustomPathGenerator implements PathGenerator
{
    public function getPath(Media $media) : string
    {
        return $media->model_id.'/';
    }
    public function getPathForConversions(Media $media) : string
    {
        return $this->getPath($media).'conversions/';
    }
    public function getPathForResponsiveImages(Media $media): string
    {
        return $this->getPath($media).'responsives/';
    }
}
```

I noticed that an existing record for a media is deleted when uploading and overwriting. Is there possibly a timing problem here?

**Comment by TVke** [comment]
Hi @SamuelNitsche 

I have not tested it yet but I see that you did not start with the `->getBasePath()` method in `getPath` maybe this causes the problem.

greetings
Thomas

**Comment by SamuelNitsche** [comment]
Hm, didn't see this. At the moment I cannot test this, but I will give it a try. I think this should be documented.
Anyways, thank you very much! I will give you feedback.

**Comment by brendt** [comment]
Hi @SamuelNitsche 

Am I correct in assuming you want to save your media files in a sub-folder of the model they are attached to?

So instead of

```
media/
  1/
    file.jpg
    conversions/
      small.jpg
      medium.jpg
      big.jpg
  2/
    file.jpg
    conversions/
      small.jpg
      medium.jpg
      big.jpg
```

You want

```
media/
  model_id_1/
    1/
      file.jpg
      conversions/
        small.jpg
        medium.jpg
        big.jpg
  model_id_2/
    2/
      file.jpg
      conversions/
        small.jpg
        medium.jpg
        big.jpg
```

If that is so, there's a bug in your implementation:

```php
public function getPath(Media $media) : string
{
    return $media->model_id.'/';
}
```

You should return the path for the media item to save, not the folder where all media items for that model should be stored. Like so.

```php
public function getPath(Media $media) : string
{
    return $media->model_id . '/' . media->id . '/';
}
```

**Comment by SamuelNitsche** [comment]
Sorry for not responding quite a while. I actually don't know if that was a bug that is fixed now or if I failed with my implementation. Whatever, I tried implementing this again and everything works like expected.

**Comment by robincp1991** [comment]
same issue.........
