### ISSUE TITLE
EPS Thumbnail?

### ISSUE THREAD

**Issue by ingageco** [spatie/laravel-medialibrary#1057]
Is there any possibility of getting eps-to-thumbnail support?

**Comment by freekmurze** [comment]
The medialibrary doesn't support that image type out of the box. However you can easily create your own image generator. Here's some more info: https://docs.spatie.be/laravel-medialibrary/v7/converting-other-file-types/creating-a-custom-image-generator

**Comment by ingageco** [comment]
Great! I missed that in the docs.

**Comment by joshuadegier** [comment]
I case anybody encounters this issue, here are the steps to generate EPS thumbnails. I've created an EPS.php class in `App\Services\Media\ImageGenerators`:

```
<?php

namespace App\Services\Media\ImageGenerators;

use Imagick;
use ImagickPixel;
use Illuminate\Support\Collection;
use Spatie\MediaLibrary\Conversion\Conversion;
use Spatie\MediaLibrary\ImageGenerators\BaseGenerator;

class EPS extends BaseGenerator
{
    public function convert(string $file, Conversion $conversion = null): string
    {
        $imageFile = pathinfo($file, PATHINFO_DIRNAME).'/'.pathinfo($file, PATHINFO_FILENAME).'.jpg';

        $image = new Imagick();
        $image->readImage($file);
        $image->setBackgroundColor(new ImagickPixel('none'));
        $image->setImageFormat('jpg');

        file_put_contents($imageFile, $image);

        return $imageFile;
    }

    public function requirementsAreInstalled(): bool
    {
        return class_exists('Imagick');
    }

    public function supportedExtensions(): Collection
    {
        return collect('eps');
    }

    public function supportedMimeTypes(): Collection
    {
        return collect('application/postscript');
    }
}
```

After that, edit your medialibrary.php config file and add the generator to the list:

```
    /*
     * These generators will be used to create an image of media files.
     */
    'image_generators' => [
        ...
        \App\Services\Media\ImageGenerators\EPS::class,
    ],
```

That's it. Generating thumbnails should now work for EPS files.

One thing I don't understand is why the library is capable of generating previews for AI files out of the box without any modifications? It doesn't same to have any ImageGenerators for that filetype and based on the mime it's basically the same as EPS.
