### ISSUE TITLE
Change tablename 'media' to something else

### ISSUE THREAD

**Issue by Pixelairport** [spatie/laravel-medialibrary#1061]
I use laravel together with cartalyst platform. There is already a package which has a table in database with the name 'media'. Is it enough to change the migration file of spatie and do the following line in the model:

protected $table = 'spatie_media';

or will there be other problems if i do this? Maybe somewhere is used DB::table('media') ... Or should i use another package?

**Comment by brendt** [comment]
Hi @Pixelairport 

Besides changing the migration, you also have to use your own model: https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-your-own-model
