### ISSUE TITLE
Downloads questions

### ISSUE THREAD

**Issue by ingageco** [spatie/laravel-medialibrary#1064]
Hey guys - I have a few questions about the download function - both single and multiple. 

1. Does generating a zip file for download require the media to be downloaded to the system disk (from s3) before it's generation?
2. Is there a possibility of a timeout with this if the images are large and there are many of them?
3. When I try to download a single image using the code in the documentation (from S3), I get "the file "http://s3/file.jpg" does not exist" - all of the files are public-read. What am I doing wrong?

Thank you for your help!

**Comment by freekmurze** [comment]
1. No, behind the scenes we don't create a zip file on your disk. All content is streamed from all filesystems (even remote ones like S3) to the client.
2. I don't think so.
3. Please check if you specified a `domain` value in the `s3` part of the config file.
