### ISSUE TITLE
Old issue regression? keepOriginalImageFormat

### ISSUE THREAD

**Issue by virtruvio** [spatie/laravel-medialibrary#1066]
Encountering a bug when using registered keepOriginalImageFormat() method while converting .MP4 video.  Registered conversion (e.g. "thumbnail") is properly executed by conversions classes (resulting in a JPEG frame grab for a converted image), but, post-conversion, media->getUrl('thumbnail') returns original extension of .mp4.  The result is that the proper 'thumbnail' registered conversion is done and the file in place in the filesystem, but -getUrl() returns for instance.  ... thumbnail.... .mp4 instead of ... thumbnail... .jpg

**Comment by freekmurze** [comment]
I'd accept a PR with tests that fixes this.
