### ISSUE TITLE
Question re. custom path generator

### ISSUE THREAD

**Issue by dambridge** [spatie/laravel-medialibrary#107]
Just to make sure I'm not missing anything: regardless of what I do to customize the path, when I remove any media the entire path is removed from what I can see? For instance, there's no place I can configure a {tenant_id} 'root' folder on S3, below which the path generator would create all the assets. If there's a trick or something I could do to make this happen, could you let me know?

**Comment by freekmurze** [comment]
You could use the id of the `media` objects to make sure every media gets it's own unique directory.
