### ISSUE TITLE
How to get id when uploading a media

### ISSUE THREAD

**Issue by emrade** [spatie/laravel-medialibrary#1070]
Hello, this is my first time using spatie media library. I was wondering if there was a way i could get the id of the media i am uploading and save that id to the field of another table. I looked through the documentation but i could not find it. Thanks.

**Comment by freekmurze** [comment]
`addMedia` will return an instance of the `Media` model. 

```php
$media = $this->yourModel->addMedia(...);

$media->id; // returns the id of the added media
```
