### ISSUE TITLE
Conversions not completing when moving between models

### ISSUE THREAD

**Issue by mradamwood** [spatie/laravel-medialibrary#1075]
I'm struggling to get conversions to run when moving images between models.

I've tested that conversions are working on the original model with local and s3 and they are.

I've checked to see if the conversion function kicks in when moving models and it seems to be but the conversions don't save. I'm not seeing any errors. 

Any pointers for debugging?

**Comment by freekmurze** [comment]
By default the conversions are queued. Is your queue running? Alternatively set the queue driver to sync.

**Comment by mradamwood** [comment]
Found the problem in case anyone else runs into it.

I'm basically using the move example from the docs

```php
$mediaItem = $model->getMedia()->first();

$movedMediaItem = $mediaItem->move($anotherModel);
```

However looking at the src move() takes a collection as an optional second parameter and defaults to 'default'. I've updated my move to set the collection again and this kicks in the conversion (my conversions are restricted by collection)

```php
$movedMediaItem = $mediaItem->move($anotherModel,'product');
```

**Comment by freekmurze** [comment]
Thanks for posting your solution 👍
