### ISSUE TITLE
Updated event handler always does createDerivedFiles

### ISSUE THREAD

**Issue by afraca** [spatie/laravel-medialibrary#1076]
This is to keep track of an issue previously discussed in a closed PR (missing tests):
https://github.com/spatie/laravel-medialibrary/pull/965/files

The problem: 
The MediaObserver registers a callback for the `updated` event, which checks the `manipulations` property on the media object, and if it was changed it will make sure all conversions are there with the `createDerivedFiles` from `FileManipulator` , done here:
https://github.com/spatie/laravel-medialibrary/blob/7.3.0/src/MediaObserver.php#L29

The manipulations will always be an array (cast like that in the model I think from top of my head), so the comparison will ALWAYS fail as the second parameter to `json_decode` misses.

**Comment by brendt** [comment]
This bug will be fixed in v7.3.2, give it half an hour for Travis to finish and I'll tag the release.

**Comment by brendt** [comment]
Released: https://github.com/spatie/laravel-medialibrary/releases/tag/7.3.2
