### ISSUE TITLE
Use DIRECTORY_SEPARATOR for windows compability (tests only?)

### ISSUE THREAD

**Issue by afraca** [spatie/laravel-medialibrary#1077]
I was trying to make a PR for https://github.com/spatie/laravel-medialibrary/issues/1076 , but due to circumstances had to do so on Windows.. PhpUnit will crash currently because of this:

https://github.com/spatie/laravel-medialibrary/blob/7.3.0/src/UrlGenerator/LocalUrlGenerator.php#L55
The call to `getStoragePath` is problematic. Exactly how I can't remember but it will use a value from this function:
https://github.com/spatie/laravel-medialibrary/blob/7.3.0/tests/TestCase.php#L149
that uses hardcoded directory separators. Then the comparison in the LocalUrlGenerator will fail **on windows** (as one path has a backslash in it and one does not) and an exception will be thrown. (And it's in some __toString() so php is NOT happy with that)

I have worked around this (so it seems...) by just using `realpath` around the return value from https://github.com/spatie/laravel-medialibrary/blob/7.3.0/tests/TestCase.php#L149 , that might be helpful for someone looking into this.

edit: Maybe a bit confusing that I talk about two solutions
- use realpath
- use DirectorySeparator

I'm currently not at my Windows pc to test whether the DS solution works, but it should and I think it's the best of the two, though not sure why.

**Comment by freekmurze** [comment]
We'll continue the conversation in #1080
