### ISSUE TITLE
Missing php extension in require-dev for Windows

### ISSUE THREAD

**Issue by afraca** [spatie/laravel-medialibrary#1078]
As noted in my other issue (https://github.com/spatie/laravel-medialibrary/issues/1077) I had to run the package tests on Windows...  By default the Windows distribution of php does not have the `php_pdo_sqlite` extension enabled, so I think "we" should include it in the composer.json. I'll open a PR soon.

**Comment by brendt** [comment]
Released as of 7.3.3: https://github.com/spatie/laravel-medialibrary/releases/tag/7.3.3
