### ISSUE TITLE
Photo gallery suggestion

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#108]
Any idea, concept on how I could let users create galleries? I mean what could be the approach with the media library?

**Comment by freekmurze** [comment]
There are multiple ways of achieving this. It all comes down on preference.I suggest you take a look at [the excellent Project Flyer series on Laracasts](https://laracasts.com/series/build-project-flyer-with-me). Replace the upload and thumbnail generation code but the functions provided by this package.

**Comment by kickthemooon** [comment]
could I use collections for the purpose of galleries?

**Comment by freekmurze** [comment]
It all depends on what you want to build.

**Comment by kickthemooon** [comment]
its a travel booking app.
Now I need the travel offer to have a gallery? :)
