### ISSUE TITLE
How to return image URL via an API

### ISSUE THREAD

**Issue by emrade** [spatie/laravel-medialibrary#1082]
Hello, all the example i have seen which used this Laravel package used it with Laravel blade views. I was wondering if it is possible to return an image url as a relationship like the way it is below. 
`return Product::with("product_image")->get()`

**Comment by bhulsman** [comment]
Add `$with = ['media'];` to the Product model and create your own Media model (extending the default media model) and add `$appends = ['url']` with a `getUrlAttribute` method.

Docs:
- https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-your-own-model
- https://laravel.com/docs/5.6/eloquent-mutators#defining-an-accessor

**Comment by rachid804** [comment]
An other option is to use [API Resource](https://laravel.com/docs/5.6/eloquent-resources) or laravel fractal, for API resource I will something like:

```php
//app/Http/Resources/ProductResource.php

class ProductResource extends Resource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request $request
     * @return array
     */
    public function toArray($request)
    {
        return [
           'image' => $this->media->getFullUrl(),
           ...
    }
}
```

And in your controller:

```php
$product = Product::with("product_image")->get();
return new ProductResource($product);
```

**Comment by freekmurze** [comment]
Thanks for explaining two excellent options @bhulsman and @rachid804 👍

**Comment by EbenezerOyenuga** [comment]
> Thanks for explaining two excellent options @bhulsman and @rachid804

I am facing the same issue please I still do not understand what to do. Can you please help break it down in more simpler terms as I am new to API resources and all. Thanks

**Comment by aishahsam2213** [comment]
Noted sir
