### ISSUE TITLE
How to deal with custom properties (alt text) for responsive images?

### ISSUE THREAD

**Issue by rjsworking** [spatie/laravel-medialibrary#1087]
Hi
I add a custom property 'alt' to each media model but can't figure out how to deal with it with responsive images.
For a non responsive images I do something like this and it works as expected but it loads always the same image.
```
<img alt="{{ $item->getFirstMedia()->getCustomProperty('alt') }}" 
src="{{ $item->getFirstMediaUrl() }}">
```
In my blade template file I have ```{{ $item->getFirstMedia() }}``` which generates the whole img srcset tag without the "alt" tag and don't know how to add the custom property.

Thanks in advance

**Comment by freekmurze** [comment]
If you want to customise how responsive images are rendered you'll need to publish the `responsiveImage` view and make your modifications in the published view.

https://github.com/spatie/laravel-medialibrary/blob/master/resources/views/responsiveImage.blade.php

**Comment by rjsworking** [comment]
Hi @freekmurze. 
Thank you very much. So simple. Sorry for the inconvenience.

Cheers

**Comment by jeff-h** [comment]
For future visitors, this may be helpful: https://github.com/spatie/laravel-medialibrary/issues/1348#issuecomment-559865188
