### ISSUE TITLE
Media record is added to the database even when resizing fails with a 500 error

### ISSUE THREAD

**Issue by techdaddies-kevin** [spatie/laravel-medialibrary#1088]
Our upload limit is set to 10MB and this works fine. The problem comes when someone uploads a small (by filesize) image that is huge in resolution. In these cases, the resizing process hits the server's memory limit, which causes a 500 error. This is expected behavior, and fine. The issue though is that the DB record is still created in these cases even though the media wasn't actually saved to disk properly. I'm not sure how to deal with this situation. I feel like medialibrary should throw an exception in these cases and rollback the database insertion.

**Comment by brendt** [comment]
We're going to solve this by throwing an exception when a conversion has failed. This exception will contain the `Media` model. Handling the exception should be done in your project code, this means you'll probably want to add functionality to the ExceptionHandler. 

A quick tip regarding memory issues: are you using `gd` or `imagick` as the image driver? `imagick` has a significant smaller memory footprint. Nevertheless, we'll add this exception functionality.

**Comment by brendt** [comment]
Scratch the above, it's a fatal error that's uncatchable. I'm afraid the only solution will be in monitoring the job status. If it fails because of a memory exception, your application should manually handle the cleanup based on the failed job logs (in your database).

One more tip: there's an event called `Spatie\MediaLibrary\Events\ConversionWillStart` which you could hook into, to maybe prevent the generation from starting altogether based on your own logic. Maybe this can be of help.

**Comment by brendt** [comment]
And another tip I just thought of, there's a method `hasGeneratedConversion` as of 7.3.0 on the `Media` model. You can use this to verify whether the conversion actually has been generated or not. Beware that this feature only works for media items generated after 7.3.0, please refer to the UPGRADING guide for more information: https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md#730

**Comment by techdaddies-kevin** [comment]
Thanks so much for all of your advice. We are currently using GD but I will switch over to Imagick today and add a few checks to hopefully catch this on our end after the fact!

**Comment by brendt** [comment]
Best of luck!
