### ISSUE TITLE
You are trying to access a protected property

### ISSUE THREAD

**Issue by FabienLucini** [spatie/laravel-medialibrary#1089]
https://github.com/spatie/laravel-medialibrary/blob/46ef12d51b2f45745940e2fd751fcb939cbd5c9b/src/MediaObserver.php#L37

Hi, this property is protected, you must use the method isForceDeleting() instead ;)

**Comment by brendt** [comment]
Thanks for the heads-up, I've made a bugfix. When Travis is done I'll tag a release.

**Comment by brendt** [comment]
This is fixed as of 7.3.4: https://github.com/spatie/laravel-medialibrary/releases/tag/7.3.4

**Comment by FabienLucini** [comment]
Forget one, the same issue here:
https://github.com/spatie/laravel-medialibrary/blob/master/src/HasMedia/HasMediaTrait.php#L45
