### ISSUE TITLE
Method Illuminate\Database\Query\Builder::getUrl does not exist

### ISSUE THREAD

**Issue by polashmahmud** [spatie/laravel-medialibrary#1091]
My Model
`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Company extends Model implements HasMedia
{
    use HasMediaTrait;

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('logo')
            ->width(150)
            ->height(150)
            ->sharpen(10);
    }
}`

when i foreach data it's how Method Illuminate\Database\Query\Builder::getUrl does not exist error.

`@foreach($companys as $company)
          <td>{{ $company->getUrl() }}</td>
 @endforeach`

image insert option is working fine. please sausage me why can i solved this error.

**Comment by bhulsman** [comment]
Company is model from which you have to fetch the media first. Calling `getUrl()` only works on an instance of Media.

Use `$company->getFirstMediaUrl()` and see https://docs.spatie.be/laravel-medialibrary/v7/basic-usage/retrieving-media for more information.

**Comment by polashmahmud** [comment]
@bhulsman Thank you vary much :+1:
