### ISSUE TITLE
Placeholder image before queue finishes generating images

### ISSUE THREAD

**Issue by chris-faulkner** [spatie/laravel-medialibrary#1092]
Hi, thanks for the fantastic package, I wonder if you could advise on a simple way to make a placeholder for this situation. I found a previous issue which looked like it solved it but couldn't get it to work #1017 

I set queue to Database and uploaded an image (which has 2 conversions). I am not running the queue to process the images but it still returns the url for the conversion which doesn't exist:
`dd($this->getFirstMediaUrl('images', 'thumb'));`

This is what it dumps out as the url:
`"/media/14/conversions/Act_Pullup4-%28Custom%29-thumb.jpg"`

This shows no conversions are made yet in the folder:
![screenshot 2018-05-07 23 46 36](https://user-images.githubusercontent.com/25483015/39728948-4c117a2c-5251-11e8-8078-46a6d2241249.png)
So it's trying to load the conversion but it won't exist until the queue processes it.

I'm probably doing this wrong, but if you could spare a moment to correct me it would be very helpful.
Perhaps I need to check if the file exists separately?

Thanks for the great package!

**Comment by freekmurze** [comment]
You can tack on `nonQueued` to the conversion profile to make sure the conversion will be performed immediately.

Alternatively you can use the `hasGeneratedConversion` function which was recently added to the package: https://github.com/spatie/laravel-medialibrary/pull/1048/files

**Comment by Roywcm** [comment]
I also need this and tried the hasGeneratedConversion function. 
Maybe i'm doing something wrong, but it looks the 'generated_conversions' property never get's saved when the conversion is generated?

**Comment by Skullbock** [comment]
I noticed that too.

Created a PR that seems to fix it:
https://github.com/spatie/laravel-medialibrary/pull/1138
