### ISSUE TITLE
Use filesystem config parameter for s3 url

### ISSUE THREAD

**Issue by bradgenereux** [spatie/laravel-medialibrary#1093]
Laravel ships with a ```filesystems.disks.s3.url``` config parameter. I think it would make more sense to use this value for generating s3 urls instead of ```medialibrary.s3.domian```. This would also make it easier to work with multiple s3 disk configurations.

**Comment by freekmurze** [comment]
Changing this now is a breaking change. I'll revisit this when creating a new major version.

**Comment by freekmurze** [comment]
We now use the `url` property that is specified with a disk in the `filesystems` config file.
