### ISSUE TITLE
Return all media associated with a model

### ISSUE THREAD

**Issue by xron89** [spatie/laravel-medialibrary#1094]
I can't seem to return all the media associated with a model, or just return all the media. Because you access the model instance using a specific record it only ever returns the media associated with that record even using ```media``` 

How can I return all the media stored across all models?

**Comment by chris-faulkner** [comment]
`Media::all()`

Works for me, just add use statement at the top:
`use Spatie\MediaLibrary\Models\Media;`

Or did I misinterpret what you meant?

**Comment by freekmurze** [comment]
`Media` is just a plain model. So like @chris-faulkner said, all media can be retrieved with `Media::all()` or `Media::get()`.
