### ISSUE TITLE
Media Directory deleted for single collection file

### ISSUE THREAD

**Issue by RoussKS** [spatie/laravel-medialibrary#1095]
Hi,

We have stumbled upon an issue when using the single file collection feature for a new project.

When replacing a file, the whole directory where files are stored is being deleted while the database entries are still there.

We are using a custom Path Generator that follows the interface provided.
and we store multiple files for different collections (some single, some multiple) on the main model's entity folder.

We have noticed that for normal collections, upload/delete works fine.
However, when we try to reupload for single file collection, the file is first uploaded as expected (breakpointed and checked at that stage) and then the whole directory is being deleted instead of the rest of the files of the collection.

S3 is used for storage.
The culprit appears to be -> on the Filesystem Method called from [MediaObserver::deleted()](https://github.com/spatie/laravel-medialibrary/blob/master/src/MediaObserver.php#L34)
This is referencing to [FileSystem::removeAllFiles() line 103](https://github.com/spatie/laravel-medialibrary/blob/master/src/Filesystem/Filesystem.php#L103)

A quick logger revealed that it was deleting the whole directory. So the database model entries for the media were there, but the files were missing.

We understand that the original path generator uses the model id, which we do not use. So we wondered if there's a better way to clear a collection that does not rely on the Media ID itself.

I hope this makes sense. Let me know if you need any more details.

Many Thanks

**Comment by RoussKS** [comment]
Apologies for any inconvenience. We have rechecked the docs and found the explanation on [Custom Directory Structure (Path Generator)](https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-a-custom-directory-structure)

However, could we consider that as a feature?
Thanks

**Comment by freekmurze** [comment]
If you can solve this in a simple, well tested way, I'd accept a PR for it.
