### ISSUE TITLE
getFirstMediaUrl() doesn't retrieve the full path to the file

### ISSUE THREAD

**Issue by eichgi** [spatie/laravel-medialibrary#1097]
I am using v7 of this library, when I use the method:

`echo $inmueble->getFirstMediaUrl('destacadas');`

I got this: `//storage/1/1-1.jpg`

But a colleague is working on the same project also and the method shows him the full path:

`http://localhost:8888/inmuebles/public//storage/1/1-1.jpg`

Do I need to change my configuration or why I am not able to get the full path automatically?

**Comment by shabaz-ejaz** [comment]
How about if you try `$inmueble[0]->getFullUrl()`?

**Comment by eichgi** [comment]
I didn't find the `getFullUrl() `method on docs, also $inmueble it's already the model which it's related to the media library, not an array. Thanks for your suggestion!

**Comment by sebastiandedeyne** [comment]
Laravel uses the `app.url` config value to generate urls. You probably need to specify `APP_URL` in your `.env` file.

**Comment by eichgi** [comment]
APP_URL is already specified but by some reason it's not been attached to the img path, what else could it be?

**Comment by eichgi** [comment]
When I do: `dd(config('app.url'));` 

I got this: `"http://inmuebles.test/"` (what I defined in .env)

**Comment by sebastiandedeyne** [comment]
This might be related to the way your storage is configured, but you'd need to dive into the `LocalUrlGenerator` class to find out what's missing.

Did you try `fullUrl` as previously suggested? It's a public method on `Media`, I'd suggest doing that if you need a full path.

https://github.com/spatie/laravel-medialibrary/blob/v7/src/Models/Media.php#L45-L51

**Comment by eichgi** [comment]
I tried `$inmueble->getFirstMedia('destacadas')->getFullUrl();`

but I still got the same incomplete path:
`//storage/1/1-1.jpg`

**Comment by sebastiandedeyne** [comment]
hi @eichgi,

Not sure what's going on here. You'll need to add some debug statements to see where it's going wrong.

Here's a good place to get started, it's where we retrieve the disk's base url: https://github.com/spatie/laravel-medialibrary/blob/7e457f86b98943680dcea8ccb4a6e24c1de54739/src/UrlGenerator/LocalUrlGenerator.php#L49

**Comment by eichgi** [comment]
Sorry, I was kind off. Last day I changed the disk I was using (media) for public and everything went ok again. I guess I haven't tried but thanks for the help 👍

**Comment by mokhosh** [comment]
@eichgi I'm having the same problem, can you tell me how you solved yours?

**Comment by eichgi** [comment]
I think public is the default option disi, but publish them to ensure it is.

**Comment by alfonsobries** [comment]
In case someone has the same error in my case was the URL defined in the env file:

You should put the URL without the final slash:
Bad: `APP_URL=http://my-domain.test/`
Good: `APP_URL=http://my-domain.test`

**Comment by Shobuj718** [comment]
The problem may be solved,
before you can  use storage in public folder change APP_URL in  .env and config/App.php
http://localhost change to 
http://localhost/project/public
and run this may be ok.

**Comment by Shobuj718** [comment]
The problem may be solved,
before you can  use storage in public folder change APP_URL in  .env and config/App.php
http://localhost change to 
http://localhost/project/public
and run this may be ok.

**Comment by ToeiRei** [comment]
I could reproduce that problem on windows - sadly none of the solutions discussed here work.

**Comment by ingageco** [comment]
Same here - any solution? Running pretty close to a fresh install of Laravel

**Comment by ToeiRei** [comment]
@ingageco My install was a fresh one. Did you try cleaning all the caches?

**Comment by shortcodes** [comment]
i noticed that when `APP_URL` contains `https` `getFirstMediaUrl` return correctly full url but with there is a problem with `http`. Only partial url is being returned

**Comment by nelson1995** [comment]
Enter these commands `php artisan config:clear` to clear your configuration and `php artisan cache:clear` to clear your cache

Then var dump your `APP_URL`  by typing this code `dd(config('app.url'))` .

Remember to enter the above commands every time you make changes to your `.env` file.

**Comment by helloKeyur** [comment]
> In case someone has the same error in my case was the URL defined in the env file:
> 
> You should put the URL without the final slash:
> Bad: `APP_URL=http://my-domain.test/`
> Good: `APP_URL=http://my-domain.test`

Thank you this was help me in my case

**Comment by daskafa** [comment]
If you tried the above mentioned and did not get results, maybe you are making a mistake in the first place. Just like me :)

try this: `php artisan storage:link`

But the most important answer is that you edit the APP_URL in .env. Later, what I said will likely end your problem.

**Comment by mdzubaidul** [comment]
I am the same problem. And I am trying this cmd 

> php artisan storage:link

**Comment by Forsakenrox** [comment]
Same issue, no idea what is wrong. a little workaround to solve it - generate url like this:
` url($this->getFirstMediaUrl($collectionName, $conversionName));`
But we all know is that is not solution. Something wrong with media-library.

**Comment by Forsakenrox** [comment]
Good news everyone, I found solution for those, who make own custom disk for media library storage.
![image](https://user-images.githubusercontent.com/11795286/233040460-9991a4bb-d793-4aeb-b808-2acdf6ed1e4e.png)
Here is my config for media disk which i make to separate storage and media-library content. Disk must be public and you must define url parameter as required.

**Comment by spardano** [comment]
Guys, for you who not using .env file anymore, i think you should change your filesystem.php configuration like this: 

![image](https://github.com/spatie/laravel-medialibrary/assets/56375622/0d8b444b-51e4-4a94-a197-860def63c8f1)

hope this helps your problem

**Comment by yasinpixels** [comment]
> If you tried the above mentioned and did not get results, maybe you are making a mistake in the first place. Just like me :)
> 
> try this: `php artisan storage:link`
> 
> But the most important answer is that you edit the APP_URL in .env. Later, what I said will likely end your problem.

Solved, Thank you!
