### ISSUE TITLE
How can we achieve document encryption before saving files.

### ISSUE THREAD

**Issue by shabaz-ejaz** [spatie/laravel-medialibrary#1098]
Is there a way we can integrate Laravel's [Encryption ](https://laravel.com/docs/5.6/encryption#using-the-encrypter) mechanism with file uploads? So ideally what I'd like to achieve is before a file is uploaded we encrypt the contents and then decrypt when retrieving the document for download.

I know it can be achieved if we store and retrieve the files manually using `Storage` functions like [this solution](https://stackoverflow.com/questions/34624118/working-with-encrypted-files-in-laravel-how-to-download-decrypted-file) but is there a way we can easily do this in this media library before storing the file like this:

`$company->addMedia($file)->toMediaCollection();`

Or if you could show me a way we can extend the Media class to achieve this?

Thanks

**Comment by shabaz-ejaz** [comment]
@sebastiandedeyne Any way I can achieve this?

**Comment by fridzema** [comment]
I needed to clean svg's before storing it. I have found this way:

```
$model->addMediaFromBase64($this->cleanSvg($request->file('logo')), 'image/svg+xml')->usingFileName($request->file('logo')->getClientOriginalName())->toMediaCollection('logo');
```

I think you can use this also to encrypt the file.

**Comment by sebastiandedeyne** [comment]
We don't have any experience with encrypted files in the media library. Maybe the community has some answers.

What @fridzema suggested would work for storage, but not sure about the retrieval part.

**Comment by shabaz-ejaz** [comment]
@fridzema Thanks for your suggestion and examples.

Would something similiar work for say documents like .doc and .pdf? I know I'd need to read the contents of the file first with `file_get_contents()` so maybe something like:

`$model->addMediaFromBase64(Crypt::encryptString(file_get_contents($request->file('document'))))->usingFileName($request->file('document')->getClientOriginalName())->toMediaCollection('documents');`

**Comment by fridzema** [comment]
@shabaz-ejaz i think it should work with all documents. 
Downside of this method is that it is memory/cpu intensive to load the whole file and decrypt it, and you can't use browser caching of the file because you can't use the extension to show the file.

**Comment by shabaz-ejaz** [comment]
@fridzema Okay, so it seems like it encrypts the file perfectly but when I decrypt the file it returns the following error:

```
local.ERROR: The payload is invalid. {"userId":1,"email":"admin@example.com","exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The payload is invalid. at C:\\wamp\\www\\astrid-api-post-mvp\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\Encrypter.php:191)
[stacktrace]
```

The way I encrypt: 
`$documentUploaded = $company->addMediaFromBase64(Crypt::encrypt(base64_encode($file)))->usingFileName($file->getClientOriginalName())->toMediaCollection();`

Decrypt:
`$taskMedia = Crypt::decrypt(file_get_contents($taskMedia->getPath()));`

**Comment by fridzema** [comment]
@shabaz-ejaz Maybe you can test first without the encrypt/decrypt part, if that works and the file is displayed properly the encrypt/decrypt can easily be added after that. 
I haven't tested this method myself so i can not give a direct working answer.

Maybe you can play around with the order of functions like ```base64_encode(Crypt::encrypt($file))```

**Comment by shabaz-ejaz** [comment]
@fridzema I've tried that too. It keeps giving `payload is invalid`.

When I open the encrypted file in Notepad it looks like this:

`{"iv":"OEgwSuY7eBy202fE9ZdxKw==","value":"We2UcDvODKDv+iVV8wiCuiZqaho8UV83JjyXhV\/6\/X8=","mac":"b9e7967ad0f38c9064958070a3bea97f5463043bf27a4a6c8aee624d997fd4a2"}`

**Comment by fridzema** [comment]
@shabaz-ejaz Hmmm i think this occurs because of `addMediaFromBase64` transform it back to a file, it is not stored as base64 while you encrypt the base64 and not the file. 
Maybe at the retrieving part you can do something like this:
`Crypt::decrypt(base64_encode(file_get_contents($taskMedia->getPath()))`.

**Comment by shabaz-ejaz** [comment]
Hmmm interesting. So here is what i'm getting now:

`dump(file_get_contents($taskMedia->getPath()));`
 returns: 
`{"iv":"YzWg0r7H0opgh3CecWmc+Q==","value":"LCbAi14DYOWbSogWAJQESWd8XEoqdqpQoJ\/mjdAbvhD54juA2HVKrqxWtTF4WX7h","mac":"2211138f4e73fd59a9d7ef0dc3a26d09d2d42a236f3ce14cd7517f30b85ff224"}"`



`dump(base64_encode(file_get_contents($taskMedia->getPath())));`
returns:
`"eyJpdiI6Ill6V2cwcjdIMG9wZ2gzQ2VjV21jK1E9PSIsInZhbHVlIjoiTENiQWkxNERZT1diU29nV0FKUUVTV2Q4WEVvcWRxcFFvSlwvbWpkQWJ2aEQ1NGp1QTJIVktycXhXdFRGNFdYN2giLCJtYWMiOiIyMjExMTM4ZjRlNzNmZDU5YTlkN2VmMGRjM2EyNmQwOWQyZDQyYTIzNmYzY2UxNGNkNzUxN2YzMGI4NWZmMjI0In0="`



`dump(Crypt::decrypt(base64_encode(file_get_contents($taskMedia->getPath()))));`
returns:
`"Qzpcd2FtcFx0bXBccGhwMjBBRC50bXA="`

**Comment by fridzema** [comment]
You are right base64 was the method i was personally working with yesterday.
This methods are available https://docs.spatie.be/laravel-medialibrary/v7/api/adding-files#addmedia
I think that the `addMedia` is enough for your case.

**Comment by shabaz-ejaz** [comment]
So I don't need any of the base64 methods. Meaning I literally do this?

`$company->addMedia(Crypt::encrypt($file->getPath()))->toMediaCollection();`

**Comment by fridzema** [comment]
Yes, excuse me!

**Comment by fridzema** [comment]
Sorry i overlooked you previous answer a bit..
The `->getPath()` does output the path and is only needed with `file_get_contents()` you can try something like:
`$company->addMedia(Crypt::encrypt(file_get_contents($file)))->toMediaCollection();`

Maybe you can try first without the encryption/decryption part and with an simple txt file to easily examine the content of it.

**Comment by fridzema** [comment]
I have mad for myself a little example, this goes well:
```php
$encrypt = \Crypt::encrypt(file_get_contents($request->file('file')));
dd(\Crypt::decrypt($encrypt));
```

When i try to do `addMedia(\Crypt::encrypt(file_get_contents($request->file('file'))))` i am getting the error `File does not exist` to.

That was exactly why i have to go with base64 approach, i could not find a way to modify the upload file instance before processing. At this point you only have a string left and no path etc. Probably the addMedia wants to perform a `getPath()` on a string, thats not going to work.

For me it was a simple thing where base64 is good enough so i gave up real quick, but for your usecase i think you definitely should search how to modify the instance since base64 and encrypt/decrypt is far from efficient.

**Comment by shabaz-ejaz** [comment]
Yeah so seems like I cannot easily encrypt the file instance before upload. 

I guess I'm gonna have to manually store and retrieve documents without media library like [this example](https://stackoverflow.com/questions/34624118/working-with-encrypted-files-in-laravel-how-to-download-decrypted-file). If that doesn't work, I'm gonna have to bury my head in the sand.

**Comment by fridzema** [comment]
No problem, good luck @shabaz-ejaz ;)
