### ISSUE TITLE
How to find a img by file_name and remove it.

### ISSUE THREAD

**Issue by nickground** [spatie/laravel-medialibrary#110]
I can't find the documentation about how to do this. Please help me. 

Thanks.

**Comment by nickground** [comment]
Even though I can remove the item by using Collection delete() method, I think it's better to have a method that can be used to remove a media file.

**Comment by sebastiandedeyne** [comment]
You could query the media table and call delete on the resulting model.

```php
\Spatie\MediaLibrary\Media::where('file_name', $fileName)->first()->delete();
```

Deleting the actual file happens by listening to the Eloquent event that gets fired so you don't need to worry about that.
