### ISSUE TITLE
PHP-ffmpeg-package depends on old symfony/process version. Any alternatives?

### ISSUE THREAD

**Issue by mortenscheel** [spatie/laravel-medialibrary#1109]
Hi,
I can't install php-ffmpeg since a sub-dependency called alchemy/binary-driver requires symfony/process version ~2.0, and I'm currently using symfony/process v4.0.9.

Are there any alternative packages to use for video thumbnails?

**Comment by vintagesucks** [comment]
You may find [this](https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/470#issuecomment-372385064) useful.

**Comment by brendt** [comment]
@mortenscheel I suppose you were able to solve this? If not, feel free to comment, but I'm closing the issue.

FYI: if it is the case that it's not fixed yet, you're free to submit a PR if it's fixable here.
