### ISSUE TITLE
Multiple file uploads

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#111]
Can I user dropzone and upload multiple files? is this enough to handle multiple files dropped into dropzone?
```
$offer->addMedia($request->file('file'))->toCollectionOnDisk('gallery', 'media');
```

**Comment by kickthemooon** [comment]
it can handle it like this :)

**Comment by huglester** [comment]
Actually dropzone should be 'posting' files one by one, no?
