### ISSUE TITLE
Use image intervention for conversion

### ISSUE THREAD

**Issue by gildastema** [spatie/laravel-medialibrary#1110]
to solve my conversion problem I used image intervention at the registerconverstion method and inside I used a job that will convert to a background task. The conversion goes well but during the recovery of the image j to a problem.

**Comment by bloggervista** [comment]
Is intervention maintained these days?

**Comment by freekmurze** [comment]
This package only support the built in conversion methods that the spatie/image package provides. Using image intervention directly is not supported.
