### ISSUE TITLE
Why can't I return a media object using a foreign key 

### ISSUE THREAD

**Issue by xron89** [spatie/laravel-medialibrary#1111]
I want to grab a media object in my view using a foreign key; 

I have a function like this with my model; 
`	public function postImg()
	{
		return $this->hasOne(Media::class, 'id', 'image_id');
	}`
 and try to call it in my view like this - 
`{{ $post['image_id']->postImg }}` 

The value of `$post['image_id']` is the id of a media object. But this returns a "Trying to get property of non-object" error.

Do I have to loop over my results in the controller and foreach `image_id` lookup the media object there e.g. 
`$img = Media::find($post['image_id']);
$post['image_id'] = $img;`

**Comment by freekmurze** [comment]
`post['image_id']` probably returns an integer. You can't call methods on that.

Try this:
```
Media::find($yourId);
```
