### ISSUE TITLE
Problem with models that uses UUID as primary key?

### ISSUE THREAD

**Issue by shirshak55** [spatie/laravel-medialibrary#1112]
I searched but didn't found any specific issue may be many are using normal incrementing integer. The problem is particularly due to uuid field in tables and media library tables uses big int to store other's model foreign key.

Problem is user uses  unsigned integer as primary key but Post uses uuid as primary key? Is there anyway to solve this issue .

Thanks for this awesome package :)

**Comment by bloggervista** [comment]
@kalinichenko88  Ok i may use it but I guess it will create problem with non uuid models right?

**Comment by kalinichenko88** [comment]
@bloggervista yes, only one solving may used

**Comment by kalinichenko88** [comment]
@bloggervista not good using different primary keys in one project, IMHO

**Comment by bloggervista** [comment]
@kalinichenko88 Yeah I agree but I usually use other package and it may conflict with that package. Although my project is fully UUID.  Is there any solutions for such bro ?

Thanks

**Comment by kalinichenko88** [comment]
@bloggervista I rewriting primary keys and foreign keys in all migrations on side packages. Problems may be, but it's good solution for me. 
If problem will be in business logic Laravel DI or package configuration should solves this :-)

**Comment by bloggervista** [comment]
@kalinichenko88 yeah but that is abit tedious . Cannot we make this package flexible enough to support different key. May be lets say model_id represents other unique key like slug etc.?

Thanks

**Comment by kalinichenko88** [comment]
@bloggervista I think it's impossible without hacks

**Comment by bloggervista** [comment]
Can we use model slug or other unique key instead of primary key? 
I always like to hide primary key instead of exposing to public?

**Comment by freekmurze** [comment]
You can hide the ids by using a path generator
https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-a-custom-directory-structure

**Comment by golamrabbi3** [comment]
Hi, My question's different. How can I set default value to this $table->uuid('model_id'); ?

**Comment by harrysbaraini** [comment]
You can use your own model (as explained in https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-your-own-model).

Example:

```php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Spatie\MediaLibrary\Models\Media as BaseMedia;

class Media extends BaseMedia
{
    public $incrementing = false;

    protected static function boot()
    {
        static::creating(function (Model $model) {
            if (is_null($model->getOriginal('id'))) {
                $model->id = Str::uuid()->toString();
            }
        });
    }
}
```

**Comment by stemount** [comment]
@harrysbaraini's answer is *so* close, but it is missing `parent::boot()` which will cause `Undefined index: App\Models\Media`

`<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\Models\Media as BaseMedia;

class Media extends BaseMedia
{
    public $incrementing = false;

    /**
     * @see https://github.com/spatie/laravel-medialibrary/issues/1112#issuecomment-456622775
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function (Model $model) {
            if (is_null($model->getOriginal('id'))) {
                $model->id = Str::uuid()->toString();
            }
        });
    }
}
`

**Comment by khanakia** [comment]
I am getting an error `SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value`

@stemount i have implemented the same code as you mentioned

**Comment by hassamulhaq** [comment]
Just change media migration.

```
$table->morphs('model');
to
$table->uuidMorphs('model');
```

it will auto set model_id to uuid

**Comment by Lokman-Abd** [comment]
> Just change media migration.
> 
> ```
> $table->morphs('model');
> to
> $table->uuidMorphs('model');
> ```
> 
> it will auto set model_id to uuid

thnaks it works for me

**Comment by ferdyhape** [comment]
> Just change media migration.
> 
> ```
> $table->morphs('model');
> to
> $table->uuidMorphs('model');
> ```
> 
> it will auto set model_id to uuid

thank you, mas, I was looking for this for 3 hours, and it turns out that just by replacing the case like this, it really helps 👍

**Comment by ferdyhape** [comment]
> Just change media migration.
> 
> ```
> $table->morphs('model');
> to
> $table->uuidMorphs('model');
> ```
> 
> it will auto set model_id to uuid

@hassamulhaq 
thank you, sir, I was looking for this for 3 hours, and it turns out that just by replacing the case like this, it really helps 👍

**Comment by florianvieira** [comment]
Hello, I have a problem with this uuid change. 

To explain I have all my tables with a uuid as primary_key, I have set the model_id to uuid type but when I want to use the function $model->clearMediaCollection('images') it deletes the whole folder even if there are other elements that are not concerned. 

Have you ever had this problem?

**Comment by Ghazanfar-Sayed** [comment]
if you would like to support both big int models and uuids model
you should try this manipulation into migration
`$this->string('model_id', 36)->change()`

**Comment by jedlynch83** [comment]
> > > Just change media migration.
> > > ```
> > > $table->morphs('model');
> > > to
> > > $table->uuidMorphs('model');
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > it will auto set model_id to uuid
> > 
> > 
> > thnaks it works for me
> 
> Hi
> 
> Doing this in new migration, will overwrite all old records ? It already works fine using bigint Ids but the problem Im facing is that now I have one table that uses mongodb and it uses uuid instead bigint; So as far as I see I have to change to uuidMorphs to make it works, but what happend with my old data ?
> 
> Thanks in advance

You're a genius.  Works perfectly now.
