### ISSUE TITLE
fileupload rest api

### ISSUE THREAD

**Issue by sagarrokade404** [spatie/laravel-medialibrary#1113]
Hi i am new to laravel 
i was able to do crud api with laravel 5.6 
with some information i was able to find the spatie media Library is very great to work with in laravel 
will you be able to help me with File Upload CRUD API in laravel 
thank you in advance

**Comment by freekmurze** [comment]
Hi, your question is not really about our package, but more on how you would build up your app.

Please post your question on public fora where many kind people can give you more info:
- https://laravel.io
- https://larachat.co/
- https://laracasts.com/discuss
