### ISSUE TITLE
Different single file collections on one model

### ISSUE THREAD

**Issue by eichgi** [spatie/laravel-medialibrary#1114]
Is there a way to define several single file collection over one Model?

Example in docs refers to avatar images over one model, but I'd like to define several collections to one model but still using them as single file collections. 

Thanks!

**Comment by bernhardh** [comment]
I am quite new and maybe I missunderstand you, but you can define as many collections as you want and all of them can be single file collections. F.E.

```
public function registerMediaCollections()
{
    $this
        ->addMediaCollection('avatar')
        ->singleFile();
    $this
        ->addMediaCollection('other-single-image')
        ->singleFile();
    $this
        ->addMediaCollection('yet-other-single-image')
        ->singleFile();
    $this
        ->addMediaCollection('normal-collection');
}
```

**Comment by eichgi** [comment]
That sounds pretty obvious, I'll try it and let you know if works!
