### ISSUE TITLE
Regenerating images will keep adding same image urls to responsive images

### ISSUE THREAD

**Issue by DevDavido** [spatie/laravel-medialibrary#1115]
First I wanted to express a big **THANK YOU!** for this awesome package! It made dealing with media files and models much easier!

Back to the unexpected behaviour I just stumbled upon:
If I run `medialibrary:regenerate` with a conversion which has responsive images it will add those image urls to the database column `responsive_images` even it already has the exact same entries. Shouldn't be there a clear of the current image urls before adding the new ones?

**Comment by Elhebert** [comment]
+1 The url should be cleared before the new ones are added.

**Comment by robinvalk** [comment]
This can be closed as it's now implemented :+1:

**Comment by DevDavido** [comment]
Thanks @Elhebert 👍
