### ISSUE TITLE
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists

### ISSUE THREAD

**Issue by Moix1** [spatie/laravel-medialibrary#1116]
I have following error while migrating the package will you please help with it ?

Error :
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists (SQL: create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci

Thanks

**Comment by FaridAghili** [comment]
Maybe `php artisan migrate:fresh` could help.

**Comment by Moix1** [comment]
**=========This is Solution I Got ==========**

Got to your Laravel Application Folder 

1: Inside Folder you will see App Go to this folder
2: Now you will have multiple folders look for " Providers "
3: Inside this folder you will get File called " AppServiceProvider.php "
4: Open this file and add this line " Schema::defaultStringLength(191);  " inside function called public f 
    function boot() { Here paste it }
5: Save the file

Now you are good to go ;-)

**Comment by mattias-persson** [comment]
@Moix1 For more info on your solution, see the "Index Lengths & MySQL / MariaDB" section under  https://laravel.com/docs/5.6/migrations#indexes. This issue has nothing to do with this package and should probably be closed.

**Comment by sayeedazmal** [comment]
Schema::create('categories', function (Blueprint $table) {
            $table->increments('id');
            $table->timestamps();
            $table->string('name')->nullable();
            $table->text('details')->nullable();
            $table->string('status')->nullable();
            $table->string('status_changed_by')->nullable();
            $table->string('status_changed_at')->nullable();
            $table->string('entered_by')->nullable();
            $table->string('updated_by')->nullable();
            $table->string('restaurant_id')->nullable();
            });
When i do the migrate then Error show in
In Connection.php line 664:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'categories'
   already exists (SQL: create table `categories` (`id` int unsigned not null
   auto_increment primary key, `created_at` timestamp null, `updated_at` time
  stamp null, `name` varchar(1000) null, `details` text null, `status` varcha
  r(1000) null, `status_changed_by` varchar(1000) null, `status_changed_at` v
  archar(1000) null, `entered_by` varchar(1000) null, `updated_by` varchar(10
  00) null, `restaurant_id` varchar(1000) null) default character set utf8mb4
   collate utf8mb4_unicode_ci)


In Connection.php line 458:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'categories'
   already exists

**Comment by mattias-persson** [comment]
@sayeedazmal That's because you're trying to run a migration which creates the `categories` table, but you already have that table in your database. Remove the table from your database and run the command again.

It has nothing to do with this package though.

**Comment by safayet404** [comment]
> **=========This is Solution I Got ==========**
> 
> Got to your Laravel Application Folder
> 
> 1: Inside Folder you will see App Go to this folder 2: Now you will have multiple folders look for " Providers " 3: Inside this folder you will get File called " AppServiceProvider.php " 4: Open this file and add this line " Schema::defaultStringLength(191); " inside function called public f function boot() { Here paste it } 5: Save the file
> 
> Now you are good to go ;-)

Yes
Problem solved

**Comment by kibria-miran** [comment]
> 

this file already exists..same issue remains

**Comment by Rajeevkvish** [comment]
PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")

  2   C:\xampp\htdocs\workhome\vendor\laravel\framework\src\Illuminate\Database\Connection.php:501
      PDOStatement::execute()

**Comment by Rajeevkvish** [comment]
sir please solution

**Comment by 5maurosivamani** [comment]
> Maybe `php artisan migrate:fresh` could help.

working fine

**Comment by Bradensa24** [comment]
This worked for me.  Thanks Moix1.  Don't forget to put the use Illuminate at the top

use Illuminate\Support\Facades\Schema;
 
/**
 * Bootstrap any application services.
 */
public function boot(): void
{
    Schema::defaultStringLength(191);
}
