### ISSUE TITLE
I want to upload Multiple Images Using Media Library Package

### ISSUE THREAD

**Issue by Moix1** [spatie/laravel-medialibrary#1117]
Hey,

I have form which contain three images selection part for selecting multiple images,

Anyone please guide me how to do it ? I have installed that package in my project don't know how to start.
i'm beginner with laravel that is why confuse with it,

Laravel Version 5.6
Mysql version is update as required This Package
Php version 7+

Thanks

**Comment by vijaybajrot** [comment]
#1117 I have same issue with **uploading multiple files** .

My request data: 
![media-pack-issue_3478375](https://user-images.githubusercontent.com/30489828/40478537-eef7c576-5f66-11e8-9b8d-b10bfa6b6013.png)

**File Uploading Error:** 
![issue_65465465](https://user-images.githubusercontent.com/30489828/40479125-79e1cafa-5f68-11e8-832a-8b5b57b9203c.png)

**Whoops File Debug :** 
![issue_98787987r](https://user-images.githubusercontent.com/30489828/40479204-ace442ac-5f68-11e8-9a71-738ac6fd91e8.png)

**Comment by codebyray** [comment]
You can loop through the photos if you make them an array like so:
```php
foreach ($request->photos as $photo) {
    $company->addMedia($photo)
        ->toMediaCollection();
}
```

Name your inputs like:
```HTML
<input type="file" name="photos[]" />
<input type="file" name="photos[]" />
<input type="file" name="photos[]" />
<input type="file" name="photos[]" />
```

Hope this helps.

Regards,
Ray
