### ISSUE TITLE
getUrl() not working

### ISSUE THREAD

**Issue by voeurnchy** [spatie/laravel-medialibrary#1118]
It not working for both `s3` and `minio`
```php
$profile->getFirstMedia('avatar')->file_name();
\\ profile.jpg;
$profile->getFirstMedia('avatar')->getUrl();
get this error
(1/1) BindingResolutionExceptionUnresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Filesystem\FilesystemManager
```

### This working but bad idea and difficult to switch driver
```php
$path = "$img->id/$img->file_name";
echo config('filesystems.disks.minio.endpoint').config('filesystems.disks.minio.bucket')."/".$path;
echo Storage::cloud()->url($path);
\\ "https://play.minio.io:9000/uploads/34/f564bbec4cfe855153e2bc4435dcd2d2.jpg"
```

**Comment by freekmurze** [comment]
I'm guessing that this error is caused by a misconfiguration in your app. All the tests around this are working. 

Could you submit a failing test for us to look at?

**Comment by voeurnchy** [comment]
For installation and configuration, I followed [The Document](https://github.com/spatie/laravel-medialibrary#user-content-lumen-support)

I ran this comment `vendor/bin/phpunit`
![screen shot 2018-07-18 at 4 15 42 pm](https://user-images.githubusercontent.com/16317127/42872028-f6a9f6d0-8aa5-11e8-8f69-1ed8fbc248fa.png)

It seem checking only in `tests/ExampleTest.php`
Please advice me.

**Comment by MattWohler** [comment]
@voeurnchy did you ever resolve this?
