### ISSUE TITLE
Loop through collection

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#112]
I need to loop through a collection and have the urls of the images?

**Comment by sebastiandedeyne** [comment]
You can retrieve the images via the `getUrl()` function. If you need an array of URL's, you could use a map.

```php
$urls = $myModel->getMedia('images')->map(function (\Spatie\MediaLibrary\Media $media) {
    return $media->getUrl();
});
```

**Comment by kickthemooon** [comment]
I need to get media and a certain collection?

**Comment by sebastiandedeyne** [comment]
You could do this on any instance of `Illuminate\Support\Collection` containing `Media` items.

```php
\Spatie\MediaLibrary\Media::all()->map(/*...*/);
$myModel->media->map(/*...*/);
// etc.
```

**Comment by kickthemooon** [comment]
difficutlt to understand.

Lets say I have $mymodel and a collection 64

how would I grap these urls from that collection 64?

**Comment by sebastiandedeyne** [comment]
What do you mean by a collection 64? A collection named 64?

**Comment by kickthemooon** [comment]
yes

**Comment by sebastiandedeyne** [comment]
```php
$urls = $myModel->getMedia('64')->map(function (\Spatie\MediaLibrary\Media $media) {
    return $media->getUrl();
});
```

This would return an instance of `Illuminate\Support\Collection` containing all URL's. If you need them in an array, you can then call `$urls->toArray()`.

**Comment by kickthemooon** [comment]
great, thanks a lot @sebastiandedeyne I will try that

**Comment by kickthemooon** [comment]
ok, is there a chance now to get and array with value to be the url and the key to be the id of that image in the media table?

**Comment by sebastiandedeyne** [comment]
You could add a `keyBy` to the chain:

```php
$urls = $myModel->getMedia('64')
    ->keyBy('id')
    ->map(function (\Spatie\MediaLibrary\Media $media) {
        return $media->getUrl();
    });
```

http://laravel.com/docs/master/collections#method-keyby

**Comment by sebastiandedeyne** [comment]
Slight correction: you're going to have to use `transform` instead of `map` to preserve keys.

```php
$urls = $myModel->getMedia('64')
    ->keyBy('id')
    ->transform(function (\Spatie\MediaLibrary\Media $media) {
        return $media->getUrl();
    });
```

**Comment by kickthemooon** [comment]
the response I get is this:
```
{50: "/media/50/twitter cover photos for new year 2016.png", 51: "/media/51/174920-1280.png",…}

50: "/media/50/twitter cover photos for new year 2016.png"
51: "/media/51/174920-1280.png"
52: "/media/52/buy-instagram-followers.jpg"
```
is this ok? look strange to me this array :)

**Comment by sebastiandedeyne** [comment]
Isn't that what you're after? Laravel automatically converts collections to json when they're returned as a response.

**Comment by kickthemooon** [comment]
ok, yes thats what I want. I know im asking too much, but do you know how I would use this response in a javascript loop? I need to loop through this and reference the key and value in the loop?

Any suggestions?

**Comment by sebastiandedeyne** [comment]
I'd go over them with `Object.keys()` and a `forEach`

```js
Object.keys(myUrls).forEach(function(key) {
    var id = key;
    var url = myUrls[key];
});
```

**Comment by kickthemooon** [comment]
ok, but do I actually type "myUrls" I mean do I reference the response json array like that?

**Comment by sebastiandedeyne** [comment]
Well that subject's a bit too broad to discuss here :)

I'd suggest you check out laracasts/PHP-Vars-To-Js-Transformer for a simple implementation:

https://github.com/laracasts/PHP-Vars-To-Js-Transformer

For more info on the topic, here's a nice overview in a StackOverflow answer:

http://stackoverflow.com/questions/23740548/how-to-pass-variables-and-data-from-php-to-javascript

**Comment by Akhibemudu** [comment]
@sebastiandedeyne Please what if I intend to get a collection of media instead of Url
I used ur example to get this output
`  {"126":"\/storage\/Property\/73\/conversions\/a-thumbnail.jpg"
,"127":"\/storage\/Property\/73\/conversions\/b-thumbnail.jpg"}
`This output is looping through my conversion 'thumbnail' but my intend is to loop through 'product_image' collection
And secondly, please I want to ask, is it possible to perform different conversion only on the first photo among other photos the user uploaded i.e user upload 4 photos, perform conversion only on the first photo e.g img 1 -conversion 'thumbnail', 'medium' and other photos would remain untouch in product_image collection.
