### ISSUE TITLE
generated_conversions property never get's saved

### ISSUE THREAD

**Issue by Roywcm** [spatie/laravel-medialibrary#1122]
I tried the hasGeneratedConversion function.
Maybe i'm doing something wrong, but it looks like the 'generated_conversions' property never get's saved when the conversion is generated?

#1092

**Comment by Elhebert** [comment]
I'm experiencing the exact same thing. Which is quiet annoying to be honest.

**Comment by oliveready7** [comment]
Having the same issue.

Quick Fix: Listen for the 'ConversionHasCompletedEvent' and mark them yourself.

**Event Service Provider**

`php  
'Spatie\MediaLibrary\Events\ConversionHasBeenCompleted' => [ 
     'App\Listeners\MarkConversionAsGenerated'
],
`


**Crated 'MarkConversionAsGenerated listener**

`php

namespace App\Listeners;

use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\Conversion\Conversion;
use Spatie\MediaLibrary\Events\ConversionHasBeenCompleted;

class MarkConversionAsGenerated
{
    public function handle(ConversionHasBeenCompleted $event)
    {
        $event->media->markAsConversionGenerated($event->conversion->getName(), true);
        $event->media->save();
    }
}
`

**Comment by Elhebert** [comment]
There's a PR (#1138) open that will fix this 👌

**Comment by freekmurze** [comment]
This is fixed in the latests version.
