### ISSUE TITLE
Query builder scopes

### ISSUE THREAD

**Issue by HipsterJazzbo** [spatie/laravel-medialibrary#1123]
In #235 @sebastiandedeyne  mentioned you may accept a PR adding query builder scopes for `hasMedia()`(and probably, I assume, `doesntHaveMedia()`).

I'm happy do whip up the PR, however I wanted to check in first to see what they should be called? Those names are the obvious ones, but given the presence of the existing `hasMedia()` instance method, they won't work.

Thoughts?

**Comment by sebastiandedeyne** [comment]
That's a long time ago, pinging @brendt or @freekmurze to see if we still want this

**Comment by brendt** [comment]
For reference, from the old issue:

> I want to where logic on query builder "retrieve models where hasMedia"? It can be also improved by providing media collection name for specific hasMedia checks.

**Comment by freekmurze** [comment]
Let's go for `scopeWithMedia` and `scopeWithoutMedia`.
