### ISSUE TITLE
responsive images and csp

### ISSUE THREAD

**Issue by Elhebert** [spatie/laravel-medialibrary#1128]
Hi,

When using the library to generate responsive image, I have issues with my CSP settings.

I'm using your laravel-csp package with the default configuration.

The issue is that it put a `onload` attribute on the `<img>` tag. How would one make this CSP compliant without having to add `unsafe-inline` to the script directive ?

I've try putting a nonce on my image tag, but didn't worked 😔

**Comment by brendt** [comment]
Hi @Elhebert can you share the generated HTML with the added nonce on the image tag?

**Comment by brendt** [comment]
We're mainly using that script to allow for async image loading beneath the fold, though it would also probably solve your issue, as you're not relying on inline scripts anymore.

I did some digging and found this issue on the W3C repo. From what's written there, nonces are not supposed to work with inline event handlers, just with scripts: https://github.com/w3c/webappsec-csp/issues/13

So for now, you'll probably want to use the script we also use on the Spatie website, I'm going to discuss this internal, see if we can change the responsive image implementation. I'll be closing this issue for now, but feel free to keep commenting.

**Comment by bserprixwq** [comment]
Solved it by : 

* Overriding `responsiveImageWithPlaceholder.blade.php` 
  * removing the `onload` attribute
  * adding an attribute `data-responsive-image`
* Adding a JS snippet in my `app.js` : 
```javascript
document.querySelectorAll('img[data-responsive-image]').forEach((elem) => {
  elem.sizes =
    Math.ceil((elem.getBoundingClientRect().width / window.innerWidth) * 100) +
    'vw';
});

```
