### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by jsaade** [spatie/laravel-medialibrary#113]
I am trying to use medialibrary on my windows machine, but for some reason it is not generating any conversion. I have GD and imagemagick working via mamp. Am I missing anything?

**Comment by freekmurze** [comment]
It should all work on Windows machines. Did you implement the `hasMediaConversions`-interface? Are you getting an error message? Please make sure you followed all steps [described in the documentation](http://medialibrary.spatie.be/v3/converting-images/defining-conversions/).

**Comment by jsaade** [comment]
The solution already works on my mac machine and on our production ubuntu server.
I checked it out on my windows machine, there are no errors, the upload is moved to the correct folder, but the conversion sub-folder is always empty.

**Comment by freekmurze** [comment]
The medialibrary delegates image conversions to [Glide](http://glide.thephpleague.com/). Glide uses to [Imagine](https://imagine.readthedocs.org/en/latest/) to create the actual images. Do those packages work on your Windows machine?
