### ISSUE TITLE
How to display user avatar for each user while looping through all users.

### ISSUE THREAD

**Issue by UmarAbdullahi** [spatie/laravel-medialibrary#1131]
Hello, 
I am using the spatie media library to upload images for my users.
When I display my users using 
`$users = User::all();`
I want to be able to display each user and its associated avatar and portfolio, something like 
```
@foreach ($users as $user)
{{$user->name}}
{{$user->avatar}}
{{$user->portfolio}}
@endforeach
```
I've spent all day googling and still can't find what I want. 
Someone please tell me what to do.

**Comment by Okipa** [comment]
Hi @UmarAbdullahi,

Once you have declared your collections in your `User` model, you can get your avatar images like that :
```
// suppose you have declared an 'avatar' collection in your `User` model
$user->getMedia('avatar')->first()->getUrl(); // for example
```

All is well explained here : https://docs.spatie.be/laravel-medialibrary/v7/working-with-media-collections/defining-media-collections

**Comment by brendt** [comment]
@UmarAbdullahi the documentation linked by @Okipa should help you figure things out. One key aspect of the media library is that it can be coupled to every model, but that also means you cannot link one media file to a fixed field in those models. You'll always have to use the helper methods provided by the `HasMediaTrait`. More info can be found here: https://docs.spatie.be/laravel-medialibrary/v7/basic-usage/retrieving-media
