### ISSUE TITLE
Exception handling FileUnacceptableForCollection

### ISSUE THREAD

**Issue by xron89** [spatie/laravel-medialibrary#1134]
I'm trying to catch a "FileUnacceptableForCollection" error I've set up my handler as the following but it doesn't run; 

```php
public function render($request, Exception $exception)
    {

        if ($exception instanceof Spatie\MediaLibrary\Exceptions\FileCannotBeAdded\FileUnacceptableForCollection){
           dd('test');
        }

        return parent::render($request, $exception);
    }
```

**Comment by brendt** [comment]
This probably means the exception isn't thrown, or it is thrown in a queue. Media files can be generated in a queue, so the error might not show up in your browser, depending on how you've configured your project.
