### ISSUE TITLE
other intervention image manipulations

### ISSUE THREAD

**Issue by AlexECP** [spatie/laravel-medialibrary#114]
Is it possible to access the full set of manipulations offered by image intervention, for example adding text to an image?

**Comment by freekmurze** [comment]
Currently no. You're restricted to what [Glide](http://glide.thephpleague.com/) is offering.

**Comment by Gummibeer** [comment]
@freekmurze can you add it to **revisit for next major version**? I'm researching how to do it with the current code base without throwing *everything* away. I can/will share my results here - but it could take some time. My primary problem is the missing dependency injection possibility for the conversions & manipulations.
Could be that I have to rework the package in a fork cause I can't make it without changing the observer and so on.

But I think that an update to enable custom drivers (like other laravel packages) would be pretty good! :)

**Comment by meganedesigns** [comment]
I know this is an old request, but I'd like to add my +1.

There is a trim method in the Intervention library which allows for trimming/cropping transparent areas from images.

**Comment by freekmurze** [comment]
I this is easy to add I'll accept a PR for this on the `v8` branch. See #1726
