### ISSUE TITLE
Media is gone when delete of model failed

### ISSUE THREAD

**Issue by clzola** [spatie/laravel-medialibrary#1143]
When I try to delete a model from my database that uses `HasMediaTrait` and when that action fails because of foreign key constraint, I can see that media that is associated with that model has been deleted, even thou i have wrapped ->delete() inside transaction...

```
/**
     * @param ShopCategory $shop_category
     * @param ShopItem $shop_item
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(ShopCategory $shop_category, ShopItem $shop_item)
    {
        try {
            \DB::transaction(function() use ($shop_item) {
                $shop_item->delete();
            });
        } catch (\Throwable $exception) {
            return redirect()->action('Admin\ShopItemsController@show', [$shop_category, $shop_item])
                ->with('notification', 'Failed to delete shop item.')
                ->with('notificationLevel', 'warning')
                ->with('notificationTitle', 'Error!');
        }

        return redirect()->action('Admin\ShopCategoriesController@show', $shop_category)
            ->with('notification', 'The shop item was successfully deleted.')
            ->with('notificationLevel', 'success')
            ->with('notificationTitle', 'Deleted!');
    }
```

I can see that picture was deleted from hard disk, but it was not deleted from database...

**Comment by freekmurze** [comment]
The package will only delete files when Eloquent fires the `deleted` event. Here is the relevant code: 

https://github.com/spatie/laravel-medialibrary/blob/6b2bf387958b443d4adeacd047dde5cdbafa2946/src/MediaObserver.php#L39-L47

Try to find out why Eloquent is already firing that event.

**Comment by restronik** [comment]
Same issue. I don't know why, but when I use destroy() method instead of delete() method, its work... Media will not be deleted, when transaction fails. But when I use delete(), media deleted...
