### ISSUE TITLE
How to combine with spatie/laravel-translatable for different files on different languages

### ISSUE THREAD

**Issue by lmartins** [spatie/laravel-medialibrary#1144]
Hi,

I'm working on a project where I'm using both `spatie/laravel-medialibrary` and `spatie/laravel-translatable`.  this is working brilliantly for regular text fields, however I am now facing a situation where for a model I also need to have different images per language.

I've tried by instantiating a custom model for Media as described in the docs:

```php
<?php

namespace App;

use Spatie\MediaLibrary\Media as BaseMedia;
use Spatie\Translatable\HasTranslations;

class Media extends BaseMedia
{

  use HasTranslations;
  protected $translatable = ['file_name'];

}
```

But this doesn't seem to work as each time a language saves, it adds the expected notation, like `{"en":"file-for-eng.jpg"}` but overrides the previous value.

So, with the value above on the DB, if I then proceed to save a version for Japanese, I end up with:
`{"jp":"file-for-japanese.jpg"}`

when the expected result would be:
`{"en":"file-for-eng.jpg", "jp":"file-for-japanese.jpg"}`

Any way to achieve. this?

Thansk!

**Comment by lmartins** [comment]
Any chance I can get some feedback on this?

**Comment by freekmurze** [comment]
> I went with different collection for each language.

That seems like a good way to go about this 👍

**Comment by lmartins** [comment]
Thanks so much for the confirmation @freekmurze I appreciate it.

**Comment by Kashifwahaj** [comment]
You can custom_properties, its easier to manager

`  $collections = ['images'];

        foreach ($collections as $collection_name) {
            $attributes[$collection_name] = $this->getMedia($collection_name, ['lang' => App::getLocale()])->toArray();
        }
`

`
 if ($request->hasFile('image') && $request->file('image')->isValid()) {
            $request->user()->addMediaFromRequest('image')->withCustomProperties(['lang' => App::getLocale()])->toMediaCollection('images');
        }
`
