### ISSUE TITLE
Media of a soft deleted model are not deleted

### ISSUE THREAD

**Issue by mokhosh** [spatie/laravel-medialibrary#1146]
I was wondering why deleting the model doesn't delete the media like it's mentioned in the documentation. This was quite a confusion until I remembered we're using soft deletion for our model and that might be the problem.

I guess soft deletes must be considered too.

**Comment by ittikorns** [comment]
I came across the same problem since version 4. My workaround is to query the media first and then call the delete method.

```
$media = $story->media->where('file_name', $filename)->first();
$media->delete();
```

**Comment by freekmurze** [comment]
If you're using SoftDeletes you must force delete a model for the medialibrary to remove all files.

Here's the relevant code: https://github.com/spatie/laravel-medialibrary/blob/6b2bf387958b443d4adeacd047dde5cdbafa2946/src/MediaObserver.php#L39-L48

**Comment by ziming** [comment]
Hmm I tried force delete with the model cleanup package. But the files in S3 remains although the soft deleted record is force deleted
