### ISSUE TITLE
Using a custom class to generate url cause an error

### ISSUE THREAD

**Issue by Mdpproduction** [spatie/laravel-medialibrary#115]
Hi,
i'm trying to use this awesome package. And i want to change the default folder structure, with a custom class.
But during the conversation, i recieve this message:

**Reading Exif data is only possible, if the image is instantiated from a filepath**

Any suggestions ?

**Comment by freekmurze** [comment]
Hi, are you using the latest version of this package? Or you by any chance using S3?

**Comment by Mdpproduction** [comment]
I'm using the 3.10 release.

**Comment by freekmurze** [comment]
I've made a fix for a related problem in 3.10.2. Could you upgrade to that version?

**Comment by freekmurze** [comment]
The problem seems indeed to be related with the latest version of the Intervention package. Investigating...

**Comment by Mdpproduction** [comment]
I suspected it. Of course.

**Comment by freekmurze** [comment]
I have temporary put a constraint on the Intervention package inside our own Laravel Glide package. If you run `composer update` again Laravel Glide should upgrade to 2.2.6, the intervention package should downgrade to 2.3.2. 

I'll remove the constraint on the Intervention package as soon as wel have a proper fix.

**Comment by Mdpproduction** [comment]
Thanks man. Have a nice development time !

**Comment by freekmurze** [comment]
Meanwhile Oliver, the creator/maintainer of the Intervention package [has fixed the issue](https://github.com/spatie/laravel-glide/commit/a86af1f729aab7d1412e9317cae8a6eeaba7a574#commitcomment-14687463). Run `composer update` again to get the latests version of the Laravel Glide and Intervention Image packages.
