### ISSUE TITLE
Can't use CustomPathGenerator class

### ISSUE THREAD

**Issue by xyloshrike** [spatie/laravel-medialibrary#1152]
I've created my class at: App/Generators/CustomPathGenerator like this:

```
<?php

namespace App\Generators\CustomPathGenerator;

use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\PathGenerator\PathGenerator;

class CustomPathGenerator implements PathGenerator
{
    public function getPath(Media $media) : string
    {
        return $media->model_id . '/' . $media->id . '/';
    }

    public function getPathForConversions(Media $media) : string
    {
        return $this->getPath($media).'conversions/';
    }

    public function getPathForResponsiveImages(Media $media): string
    {
        return $this->getPath($media).'responsives/';
    }
}
```
And the medited the mediaibrary.php at config/app.php to look like this:

```
/*
     * The class that contains the strategy for determining a media file's path.
     */
    'path_generator' => App\Generators\CustomPathGenerator,
```

But it trows this error:

`Undefined constant 'App\Generators\CustomPathGenerator'`

Any idea why ?

**Comment by xyloshrike** [comment]
Solved, i was using the wrong namespace !

**Comment by riseoflex88** [comment]
To help others:
`'path_generator' => App\Generators\CustomPathGenerator,`
should be
`'path_generator' => \App\Generators\CustomPathGenerator::class,

**Comment by riseoflex88** [comment]
@xyloshrike can you post a copy of the working namespace, I'm also getting this issue and can't resolve it.
