### ISSUE TITLE
Custom media_model overwritten with composer update

### ISSUE THREAD

**Issue by woodgates** [spatie/laravel-medialibrary#1153]
Hi.

I'm using a custom media model which I have defined on vendor/.../medialibrary.php

'media_model' => App\Models\WgtMedia::class, 

The problem I have is when I run composer update this setting is overwritten with the default

'media_model' => Spatie\MediaLibrary\Models\Media::class,

How can I prevent this?

**Comment by Benjyclay** [comment]
Run this
```
php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="config"
```

It will publish the vendor config to the config directory in the root of your project

**Comment by woodgates** [comment]
Great, thanks!
