### ISSUE TITLE
How to install converted image optimizers in Laragon & WAMP Server

### ISSUE THREAD

**Issue by abdullahbutt** [spatie/laravel-medialibrary#1155]
How to install converted image optimizers in Laragon & WAMP Server?

https://docs.spatie.be/laravel-medialibrary/v6/installation-setup

There is guide on how to install all the optimizers on Ubuntu & how to install the binaries on MacOS (using Homebrew). But what about Windows? I use Laragon & WAMPServer. How to install them in this environment?

    JpegOptim
    Optipng
    Pngquant 2
    SVGO
    Gifsicle

**Comment by freekmurze** [comment]
Ask this question at the Laragon repo.
