### ISSUE TITLE
Non Queue conversion when adding media

### ISSUE THREAD

**Issue by Benjyclay** [spatie/laravel-medialibrary#1156]
Happy to create a PR for this but im just submitting this issue for viability.

I define my conversions in a shared trait. A feature that I would find helpful is the ability to remove a conversion from the queue when adding media. For example, 

```
$media = $this->addMedia( $file )
    ->toMediaCollection( 'some-random-files' )
    ->nonQueued('thumbnail');
```
This would add all but the thumbnail conversion to the queue and create the thumbnail conversion directly.

Let me know what you think.

**Comment by freekmurze** [comment]
I'm thinking that in most cases a given conversion profile should always be queued or should never be queued. I don't think that many users will need  the proposed functionality. So unless the PR is very very simple (and well tested en documented), I'm going to keeping things as they are for now.
