### ISSUE TITLE
getUrl() should return correct schema

### ISSUE THREAD

**Issue by divdax** [spatie/laravel-medialibrary#1161]
Given that i have a `.env` with
```
APP_URL=http://custom.url
```
and my site uses SSL (http -> 302 -> https)
```
getUrl()
```
generates the urls with http schema. Laravel is checking the current schema when generating urls even if the APP_URL is http.

Just a hint for small optimization. 😄

**Comment by freekmurze** [comment]
Feel free to submit a fully tested PR for this.
