### ISSUE TITLE
Different disk for conversions

### ISSUE THREAD

**Issue by patrickomeara** [spatie/laravel-medialibrary#1165]
Hi there, 

First of all, thank you for a great package.

Is it possible to have conversions on a separate s3 disk than the original?

We current have two subdomains `uploads.domain.com` and `cache.domain.com` I was hoping to keep the same setup while implementing medialibrary but can't find this specified in the docs.

**Comment by freekmurze** [comment]
A different disk for conversion is currently not supported by the package.

**Comment by patrickomeara** [comment]
Thanks @freekmurze
