### ISSUE TITLE
Error executing "PutObject" (RequestTimeTooSkewed) - Digitalocean Spaces

### ISSUE THREAD

**Issue by netanelwebninja** [spatie/laravel-medialibrary#1166]
Hey,
**I have the following code:**

`$this->addMediaFromBase64($img)->toMediaCollection('avatar');`

$this is a User class that use the HasMediaTrait, and $img contains base64 string.

My laravel app setup to use Digitalocean spaces as storage disk.

**When I run this code I get this error:**

`Aws\S3\Exception\S3Exception thrown with message "Error executing "PutObject" on "https://bluejay.ams3.digitaloceanspaces.com/14/medialibraryw1oh8c"; AWS HTTP error: Client error: `PUT https://bluejay.ams3.digitaloceanspaces.com/14/medialibraryw1oh8c resulted in a 403 Forbidden response:
<?xml version="1.0" encoding="UTF-8"?><Error><Code>RequestTimeTooSkewed</Code><RequestId>tx0000000000000000e7c72-005b369 (truncated...)
 RequestTimeTooSkewed (client):  - <?xml version="1.0" encoding="UTF-8"?><Error><Code>RequestTimeTooSkewed</Code><RequestId>tx0000000000000000e7c72-005b369d03-96829a-ams3a</RequestId><HostId>96829a-ams3a-ams3</HostId></Error>`

**What is the reason and how I can solve that ?**

**Comment by freekmurze** [comment]
This problem is probably not related to the medialibrary.  Judging from the error message the Flysystem driver for DO spaces expects that your system clock is set correctly. The error indicates that the time of your server is too far off from DO's clock. 

If the problem still persist, open up an issue at the repo of the Flysystem driver you are using.

**Comment by eichgi** [comment]
@netanelwebninja how did you manage to set your spaces url in this package?

I set this in medialibrary.php:

`'domain' => 'https://sfo2.digitaloceanspaces.com'`

but I am getting this error:

Error executing "PutObject" on "https://la-space.s3.sfo2.amazonaws.com/6/backgroundish.jpg"; AWS HTTP error: cURL error 6: Could not resolve host: la-space.s3.sfo2.amazonaws.com

instead something like you wrote (https://bluejay.ams3.digitaloceanspaces.com/14/medialibraryw1oh8c)

Any suggestions? Thanks!

**Comment by rdrglpzcnt** [comment]
did you fix it?
