### ISSUE TITLE
Large Remote Files and Slow issues!

### ISSUE THREAD

**Issue by irazasyed** [spatie/laravel-medialibrary#117]
Hey!

First of all, Thanks for building this awesome package. I was integrating this in one of our projects as it seemed very good and does the job well.

I have a few questions:

1. So right now i use guzzle to download large remote files using streams method (Async). I want to know, Does this package has support to download and associate large remote files using the `addMediaFromUrl ` method? The files are basically in mp4, mp3 and image formats (Can go up to 100 MB or more).
2. I noticed there seems to be some performance issues (I could be wrong though), But with my current method of associating the file by first downloading it using guzzle and then storing into the database seems to just work fine without any slowness (It's pretty straightforward), But as soon as i use this package's any methods to even associate local files, It takes up noticeable amount of time and feels a lil bit slow. Has anyone else felt this before or is there something i could do about it? (Testing on Homestead Env). What could be the reason?

Let me know. Thanks!

**Comment by irazasyed** [comment]
Here's a screenshot of the response time it took:
<img width="288" alt="Screenshot" src="https://cloud.githubusercontent.com/assets/1915268/11612993/c2ba7de6-9c36-11e5-9334-0f28c24684a7.png">

The first one is of without this package, It downloads remote file which is simply a tiny image in kb and saves it in local directory & adds a record to database and the second one is with this package, same thing but this time it's simply associating the local file that is already downloaded before (again same tiny image).

**Comment by freekmurze** [comment]
Hi,

there is no support for directly adding streams to the medialibrary. You'll have to download your file entirely first and than add it to the medialibrary. Internally the medialibrary will use a stream to copy a file to a remote filesystem.

I'm not aware of any performance issues with the package. A requesttime of 824 ms sounds a bit too high. Are you letting the package generate a thumbnail by any chance? Could you use a service such as Blackfire.io to pinpoint the source of the performance problem?

**Comment by irazasyed** [comment]
Hi,

Alright, That's fine. I'm just doing the same right now. First downloading the media to a temp. location and then attaching it.

It's actually processing an incoming request (Another service hits my webhook), Does some other tasks before saving the file. But as compare to with package, 824ms is still better. Now I've actually moved the media download to queue system. So its improved. But 6.38s with package is worst.

Also, I tested both with and without conversion turned on (thumbnails). Both make no difference. Same slowness.

As far as Blackfire.io is concerned, I don't have much experience with that but when i did run once, it highlighted `file_put_contents`. Lmk what i need to look at in Blackfire report, I can send over the screenshots or whatever is required to help trace the issues? Thanks!

**Comment by freekmurze** [comment]
Could you measure the performance of the file_put_contents statement?  I suppose it's the one in `HasMediaTrait`?

You could wrap the solution to [this SO question](http://stackoverflow.com/questions/3880149/best-way-to-measure-and-refine-performance-with-php) in a function  and place it right before and right after the statement.

**Comment by irazasyed** [comment]
So i did some debugging today and traced the issue.

It seems like this line of code is the reason behind it taking 5-6 seconds time: 
https://github.com/spatie/laravel-medialibrary/blob/master/src/Filesystem.php#L137

```php
$this->filesystem->disk($media->disk)->put('.gitignore', Gitignore::getContents());
```

Basically, It's first getting the file contents from the stub file and then putting it into the driver's root.

I modified to test (This is just for local testing, Since the issue for me is with local driver):

Replaced to this code:
```php
Gitignore::createIn(config("filesystems.disks.{$media->disk}.root"));
```

And It now works super fast as expected, All in ms count and not performance issues at all. I tested this several times. It's surprising to see it performing so well for just a small change. Even the remote file download and saving works super fast as expected. Maybe you should modify that code a lil bit to copy the file to the root instead of reading and writing like it does right now (I understand it also supports cloud driver but there has to be a better solution than that).

Let me know if you have any Q's. Thanks!

**Comment by irazasyed** [comment]
Update: Since i can see there is no real way to copy a file to a cloud with the standard storage system and the only way is to use put method, How about you do this:

```php
if(config("filesystems.disks.{$media->disk}.driver") == 'local') {
    Gitignore::createIn(config("filesystems.disks.{$media->disk}.root"));
} else {
    $this->filesystem->disk($media->disk)->put('.gitignore', Gitignore::getContents());
}
```

This too works absolutely good for local driver as expected and for cloud, it should work like before. Just experimenting few options. Lmk your inputs.

**Comment by freekmurze** [comment]
I've decided to remove that automatic adding of a .gitignore file alltogheter. I'll add some clear instructions in the documentation how to manually add the right directory to a project specific .gitigore file. I'll tag a new version with these changes in the near future.

**Comment by irazasyed** [comment]
That's even better and sounds good. Thanks! :+1:

**Comment by irazasyed** [comment]
P.S Let me know if you need any help. I can send a PR if you're busy (And you can ofc review and we can take things from there). :)

**Comment by freekmurze** [comment]
I'd gladly accept a PR that removes all functionality to create gitignores. :+1:

**Comment by irazasyed** [comment]
Cool, I'll submit it soon then :+1:

**Comment by freekmurze** [comment]
This issue is fixed by not creating a gitignore file.

**Comment by amosmos** [comment]
@freekmurze It's an old issue but I have a question - before you removed this functionality, where were gitignore files created? Inside each specific media resource folder? And also inside the conversions folder inside of that?

I guess now we shouldn't mimic that and only create one gitignore file in the public/media folder? Or maybe even just add that folder to the root gitignore file? What would you recommend?
