### ISSUE TITLE
Generated custom properties not showing up in database

### ISSUE THREAD

**Issue by matthewgovaere** [spatie/laravel-medialibrary#1170]
It appears conversions are not getting saved to the database (feature from #1020).

I'm adding the file like this...
```
$user
    ->addMedia($request->file('image'))
    ->toMediaCollection('avatar');
```
and added the conversions like this...
```
public function registerMediaCollections()
{
    $this
        ->addMediaCollection('avatar')
        ->useDisk('s3')
        ->singleFile()
        ->registerMediaConversions(function (Media $media = NULL) {
            $this
                ->addMediaConversion('small')
                ->format('jpg')
                ->fit('crop', 300, 300);

            $this
                ->addMediaConversion('medium')
                ->format('jpg')
                ->fit('crop', 500, 500);

            $this
                ->addMediaConversion('large')
                ->format('jpg')
                ->fit('crop', 1000, 1000);
        });
}
```

The `hasGeneratedConversion` method comes up as `false`, assuming because the `custom_properties` field in the database doesn't show any of the conversion data, even though the conversions are saved correctly within the file system.

I also did some variable dumps during the methods `markAsConversionGenerated` and `performConversions`, and noticed each conversion contains the proper `custom_properties` fields, but it appears they're never added to the `custom_properties` for the original media item that actually gets saved to the database.

**Comment by matthewgovaere** [comment]
I've temporarily solved the issue by just adding the custom properties myself, though I think the feature implies this is done automatically, so the solution below is just for anyone else running into the same problem and needs a quick fix.
```
$user
    ->addMedia($request->file('image'))
    ->withCustomProperties([
        'generated_conversions' => [
            'small' => true,
            'medium' => true,
            'large' => true,
        ]
    ])
    ->toMediaCollection('avatar');
```
Hoping to find some time soon to submit a PR with a permanent fix.

**Comment by freekmurze** [comment]
This should have been fixed in the latest version.
