### ISSUE TITLE
How to pass custom height and width ?

### ISSUE THREAD

**Issue by shankhadevpadam** [spatie/laravel-medialibrary#1172]
I want to convert the image using custom height and width not like this

```
public function registerMediaConversions(Media $media = null)
    {
    	$this->addMediaConversion('thumbnail')
             ->fit(Manipulations::FIT_CROP, 100, 100);

    }
```
i want to pass custom height and width dynamically while calling this function. like
```
$banner->addMedia($request->image, 200, 200)
                   ->toMediaCollection();
```
i have follow this [link](https://docs.spatie.be/laravel-medialibrary/v6/converting-images/defining-conversions#using-model-properties-in-a-conversion) also but no luck.

**Comment by hardikdangar** [comment]
are you using v7 or v6? if you are using v7 then the correct documentation for what you want is at,
[defining conversions](https://docs.spatie.be/laravel-medialibrary/v7/converting-images/defining-conversions)

**Comment by hardikdangar** [comment]
Only thing i can think of is you forgot the property in your model,
public $registerMediaConversionsUsingModelInstance = true;

**Comment by shankhadevpadam** [comment]
I have also added 
```
public $registerMediaConversionsUsingModelInstance = true;

public function registerMediaConversions(Media $media = null)
{
    	$this->addMediaConversion('thumbnail')
             ->fit(Manipulations::FIT_CROP, 100, 100);

        $this->addMediaConversion('image_250x250')
             ->fit(Manipulations::FIT_CROP, 250, 250);
}
```

**Comment by hardikdangar** [comment]
see the above code will generate new thumbnail automatically. but if you want to set custom height and width then you can do inplace generation like,


```
$newsItem = NewsItem::find(1);
$newsItem
   ->addMedia($pathToFile)
   ->toMediaCollection();

$newsItem->addMediaConversion('thumb')
     ->width($width)
     ->height($height);
```

**Comment by shankhadevpadam** [comment]
Then how to pass this height and width from

```
$newsItem = NewsItem::find(1);
$newsItem
   ->addMedia($pathToFile)
   ->toMediaCollection();
```

**Comment by shankhadevpadam** [comment]
My question is, i want to pass this custom height and width from the controller like

```
$newsItem = NewsItem::find(1);
$newsItem
   ->addMedia($pathToFile)
   ->width(120)
   ->heigth(120)
   ->toMediaCollection();
```
like this

**Comment by freekmurze** [comment]
Take a look at this page in the docs: https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/storing-media-specific-manipulations

```php
$newsItem
   ->addMedia($pathToFile)
   ->withManipulations([
      'thumb' => ['orientation' => '90'],
   );
```

**Comment by NurullahDemirel** [comment]
@freekmurze can ı pass width and height that ı want by using you told

**Comment by arhinful** [comment]
were you able to fixe @NurullahDemirel
