### ISSUE TITLE
Add custom VideoGenerator 

### ISSUE THREAD

**Issue by JinalSomaiya** [spatie/laravel-medialibrary#1176]
Using Spatie media library in one of my projects, I want to add conversions of video. when video is uploaded then add other resolutions videos to that particular media conversions folder.

So, How to do conversions for video?

please help me.

Thanks in advance!

**Comment by freekmurze** [comment]
This package cannot convert videos to other resolutions. Do this in your own app and add the converted videos to the medialibrary.
