### ISSUE TITLE
Save image resolution

### ISSUE THREAD

**Issue by divdax** [spatie/laravel-medialibrary#1181]
What about saving image resolution like file_size?
I know i could use `setCustomProperty('resolution,' ['width' => 100, 'height' => 50]);`

What is the best method to save this with hooking into the library instead of set this for every upload in my controllers?

**Comment by brendt** [comment]
Hi @divdax 

You'll want to use an event hook for this. Take a look at the documentation, which lists all available events. You can hook into these events with default Laravel code. My guess is that you want to hook into `MediaHasBeenAdded`.

If you don't mind me asking, what exactly do you want to use this for? As one media item has multiple files, depending on the conversions and responsive images; you cannot simply save one dimension as a custom property. Furthermore, in case of responsive images; you should never be concerned about the dimensions, as the browser will figure out which image to load using `srcset` and `sizes`.

If you just want to save the original image dimension, you can by hooking using events.
