### ISSUE TITLE
upgrading the database for v6 to v7

### ISSUE THREAD

**Issue by hohl** [spatie/laravel-medialibrary#1182]
I was just about to update Medialibrary from v6 to v7.3.10, when I encountered the following issue: I need to upgrade the structure of my database too. A small guide on the recommended way would have been nice in the UPGRADE.md (which only states that you need that field) and some TODO about prefixing the some file names.

What I did was the following.

1. I created a migration which adds: `$table->json('responsive_images')->nullable()`.

2. Then I ran: `./artisan medialibrary:regenerate` in the CLI.

3. Finally, I tried to undo the nullability. However, there are still `null` values in the database.

Since the `null` values aren't designed to be there by the library, what is the recommended way to upgrade the database? Is there any default value I can set all the existing column to?

**Comment by hohl** [comment]
Looks like...

1. migrate with `$table->json('responsive_images')->default('[]');`

2. then drop the default with `$table->json('responsive_images')->default(null)->change();`

... works for upgrading the database. But some official help/documentation would still have been nice (not that upgrading it in a wrong way causes unexpected side effects).

**Comment by freekmurze** [comment]
I'm glad you found the problem.

**Comment by vedmant** [comment]
Is there any official docs how to do this correctly?

**Comment by IChris2698I** [comment]
@hohl Thanks!

@freekmurze Could this be added to the UPGRADING.md guide?

**Comment by freekmurze** [comment]
@IChris2698I feel free to send a PR
