### ISSUE TITLE
Custom url generator doesn't exist

### ISSUE THREAD

**Issue by melokki** [spatie/laravel-medialibrary#1184]
Hello

I am trying to implement a custom Url generator class, but I am having some issues with this and cannot understand them.

This is my class so far

```
<?php

namespace App\Utils;

use Spatie\MediaLibrary\UrlGenerator\BaseUrlGenerator;

class GcsUrlGenerator extends BaseUrlGenerator
{

    /**
     * Get the url for a media item.
     *
     * @return string
     */
    public function getUrl(): string
    {
        return sprintf('https://domain.com%s/%s', $this->media->id, $this->media->file_name);
    }

    /**
     * Get the temporary url for a media item.
     *
     * @param DateTimeInterface $expiration
     * @param array $options
     *
     * @return string
     */
    public function getTemporaryUrl(DateTimeInterface $expiration, array $options = []): string
    {
        // TODO: Implement getTemporaryUrl() method.
    }

    /**
     * Get the url to the directory containing responsive images.
     *
     * @return string
     */
    public function getResponsiveImagesDirectoryUrl(): string
    {
        // TODO: Implement getResponsiveImagesDirectoryUrl() method.
    }
}
```

the problem is I am always getting an `InvalidUrlGenerator` exception `Class Spatie\MediaLibrary\UrlGenerator\GcsUrlGenerator doesn't exist`

At this point I don't know what else to do.

Where should I put this custom generator class?

**Comment by brendt** [comment]
Hi @melokki 

You'll have to register your custom URL generator in your `medialibrary.php` config file. Here's an example: https://github.com/spatie/laravel-medialibrary/blob/master/config/medialibrary.php#L77
Obviously, the class `Spatie\MediaLibrary\UrlGenerator\GcsUrlGenerator` won't exist, you'll have to use `\App\Utils\ GcsUrlGenerator`, the fully qualified class name.

Please also refer to the documentation: https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/generating-custom-urls#generating-custom-urls
