### ISSUE TITLE
Custom MediaObserver

### ISSUE THREAD

**Issue by dmitrybubyakin** [spatie/laravel-medialibrary#1186]
Is there any way to use my own implementation of the `Spatie\MediaLibrary\MediaObserver` ?

```php
class MyMediaObserver extends MediaObserver
{
    public function deleted(Media $media)
    {
    // I don't want to remove all files
    }
}
```

Now I have to write something like this:

```php
MyModel::getEventDispatcher()->forget('eloquent.deleted: Spatie\MediaLibrary\Models\Media')
MyModel::getEventDispatcher()->listen('eloquent.deleted: Spatie\MediaLibrary\Models\Media', $listener)
```

**Comment by brendt** [comment]
At the moment, this is not possible. The media observer is registered in the service provider. You're free to send a PR to make this configurable in the config, provided that it's backwards compatible and a test for it is added.
