### ISSUE TITLE
How can I store media on a non public path.

### ISSUE THREAD

**Issue by bcreeves** [spatie/laravel-medialibrary#1187]
In version 6 I could create a custom url generator with this as my getUrl() method:

```
public function getUrl() : string
{
    return '/asset/file/' . $this->getPathRelativeToRoot();
}
```

and then create a route to access the file:

```
Route::get('asset/file/{p1}/{p2}/{p3?}', function ($p1, $p2, $p3 = null) {
    $sub_path = $p3 ? '/' . $p3 : '';
    $path = storage_path('app/assets/' . $p1 . '/' . $p2 . $sub_path);
    return response()->file($path);
});
```
But that no longer works in version 7 as I get `Storage path '/path/to/storage/app/assets' is not part of public path`

Is there any way around not explicitly making the storage path public?

**Comment by freekmurze** [comment]
Could you PR a failing test for us to look at?
