### ISSUE TITLE
How can i access it?

### ISSUE THREAD

**Issue by halatef** [spatie/laravel-medialibrary#1199]
it's a stupid question, but how can i access the module after installing it!!

**Comment by kgenly** [comment]
Does this not answer your questions?

https://docs.spatie.be/laravel-medialibrary/v5/introduction

**Comment by halatef** [comment]
thanks @kgenly 
what am asking for is how to access it via URL, :)
i am asking about the view and rout name

**Comment by kgenly** [comment]
Ahh, gotcha. Not a question I can help with then. :)

**Comment by freekmurze** [comment]
I don't understand the question.  The docs contains a lot of examples on how to generate URLs: https://docs.spatie.be/laravel-medialibrary/v6/basic-usage/retrieving-media
