### ISSUE TITLE
getFirstMediaURL param incoherence

### ISSUE THREAD

**Issue by welcoMattic** [spatie/laravel-medialibrary#12]
Hi!

I'm trying to get the first (and only one) media in my collection with `getFirstMediaURL()` method.

Your documentation says to pass `collectionName` to this method, or your exemple show `getFirstMediaURL('detail')` where `detail` is a profile.

The method doesn't work with profile param, but works with collection name, but original profile is used by default.

Thanks for fix it

**Comment by freekmurze** [comment]
`getFirstMediaURL` expects two parameters. The first parameter should be a collection name, the second a name of an image profile.

The documentation was wrong. I've now corrected it.

Thanks for bringing this to my attention.

**Comment by welcoMattic** [comment]
Oh perfect! I'd not try to add a second parameter, my bad.

Thanks for updating documentation.
