### ISSUE TITLE
CustomPathGenerator for collection / model structure

### ISSUE THREAD

**Issue by riseoflex88** [spatie/laravel-medialibrary#1200]
I've created a CustomPathGenerator file based on the one in the docs, however I feel like I'm missing something in how to reference this in config/medialibrary.php, as it's just completely ignoring the file structure I've tried to set it. 

If anyone can help, I'd really appreciate it

**Desired structure:** 

media
---- model_type
------ collection_name
-------- 1
---------- file.jpg
-------- 2
---------- file.jpg

e.g. media/Activities/brochure-photo/1/bali.jpg

**app/Generators/CustomPathGenerator.php:** 
```
<?php
namespace App\Generators\CustomPathGenerator;

use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\PathGenerator\PathGenerator;

class CustomPathGenerator implements PathGenerator
{

    public function getPath(Media $media) : string
    {
        return str_replace('App\\', '', $media->model_type) . '/' . $media->collection_name . '/' . $media->id .'/';
    }

    public function getPathForConversions(Media $media) : string
    {
        return $this->getPath($media).'conversions/';
    }

    public function getPathForResponsiveImages(Media $media): string
    {
        return $this->getPath($media).'responsives/';
    }
}
```

**config/medialibrary.php includes:** 
`'custom_path_generator_class' => App\Generators\CustomPathGenerator::class,`

**Comment by riseoflex88** [comment]
By changing config/medialibrary.php to: 
`'path_generator' => \App\Generators\CustomPathGenerator::class`

I've got the file hooked up, however, now the error is..

`Declaration of App\CustomPathGenerator::getPath(Spatie\MediaLibrary\Media $media): string must be compatible with Spatie\MediaLibrary\PathGenerator\PathGenerator::getPath(Spatie\MediaLibrary\Models\Media $media): string`

If I change getPath to return 'abc' it still shows the same error, I really can't see the answer here.

**Comment by Jasper9041** [comment]
You have used an incorrect namespace for the Media class from the medialibrary package. Your first code fragment seems to suggest you used the correct namespace, but your error says otherwise. Maybe you've changed it?
The correct namespace for the Media class is `Spatie\MediaLibrary\Models\Media`, not `Spatie\MediaLibrary\Media`.

**Comment by riseoflex88** [comment]
@Jasper9041 thanks, that fixes this specific issue but in the hunt for the answer I've got myself into a world of pain. I've created a new job with the new issue
