### ISSUE TITLE
Class App\Generators\CustomPathGenerator doesn't exist

### ISSUE THREAD

**Issue by riseoflex88** [spatie/laravel-medialibrary#1203]
I'm getting the error `Class App\Generators\CustomPathGenerator doesn't exist` and have been stumped with various iterations of this for the last day. The docs almost oversimplify this in their explaination so I'm really struggling to work out where I've gone wrong since the example given is almost identical to mine. 

config/medialibrary.php contains: 
`'path_generator' => App\Generators\CustomPathGenerator::class,`

app/Generators/CustomPathGenerator.php contains: 
```
<?php
namespace App\Generators\CustomPathGenerator;

use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\PathGenerator\PathGenerator;

class CustomPathGenerator implements PathGenerator
{

    public function getPath(Media $media): string
    {
        return md5($media->id).'/';
    }

    public function getPathForConversions(Media $media): string
    {
        return $this->getBasePath($media).'/conversions/';
    }

    public function getPathForResponsiveImages(Media $media): string
    {
        return $this->getBasePath($media).'/responsive-images/';
    }

}
```

**Comment by riseoflex88** [comment]
Damn the answer was simple. My lack of understanding of php namespaces bit me in the arse here.

The namespace declared at the top of the file needs to be the name of the parent folder, not the name of the class as I was doing. 

So the top namespace should just be `namespace App\Generators`

So when this is used in config/medialibary, it's using the 'App\Generators' structure, and looking for a class named 'CustomPathGenerator'

**Comment by Akhibemudu** [comment]
Am having a similar issue, I have tried debugging it for 2 days now but dont seems to hv any progress, Please here is my code, for the custompathgenerator
`<?php
/**
 * Created by PhpStorm.
 * User: DELL
 * Date: 10/24/2018
 * Time: 11:51 AM
 */
namespace App\Helper;

namespace Spatie\MediaLibrary\Tests\Unit\PathGenerator;
use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\PathGenerator\PathGenerator;


class CustomPathGenerator implements PathGenerator
{
    public function getPath(Media $media) : string
    {
        //return md5($media->model_id).'/';

        $model = class_basename($media->model_type);
        return $model .'/'.$media->model_id.'/'.md5($media->id).'/';

    }

    /*
  * Get the path for conversions of the given media, relative to the root storage path.
  */
    public function getPathForConversions(Media $media): string
    {
        return $this->getBasePath($media).'/conversions/';
    }

    /*
     * Get the path for responsive images of the given media, relative to the root storage path.
     */
    public function getPathForResponsiveImages(Media $media): string
    {
        return $this->getBasePath($media).'/responsive-images/';
    }

    /*
     * Get a unique base path for the given media.
     */
    protected function getBasePath(Media $media): string
    {
        return $media->collection_name;
    }
}
`
Medialibrary
`    'path_generator' => App\Helper\CustomPathGenerator::class,
`
