### ISSUE TITLE
How to compress original image?

### ISSUE THREAD

**Issue by kgenly** [spatie/laravel-medialibrary#1204]
Okay, so take the use case of uploading user avatars. The maximum size that avatars in my app can ever be is 150x150 -- however, we allow uploading images up to 1000kb, that will then be scaled down using generated images to 150px (along with some other, smaller sizes) and cropped as necessary. This makes sense because often, people want to upload pictures of themselves taken with a phone, and don't have a lot of understanding of how to crop and resize the image themselves.

The media library very kindly avoids altering the original of an uploaded image, which in most cases, is a good thing that allows me to regenerate images at the drop of a hat, important in the case of, say, illustrations in a blog post. But in this case, storing a full-size photo of someone that will never be seen as more than a 150x150 thumbnail feels wildly excessive and a way to up my image hosting costs for no particular reason.

Is there a way to override this behavior and scale down/compress the *original* image, before it's saved to S3? I tried something like this:

```
$fileName = 'user' .'-'. time().'.'.$request->file->getClientOriginalExtension();

      $path = $request->file->path();

//Shrink the uploaded image
      Image::load($path)
      ->fit('crop', 150, 150)
      ->save();

      //Save the image into the media library
      $media = $profile->addMediaFromRequest('file')
      ->usingFileName($fileName)
         ->toMediaCollection('avatar');
```
This worked about 25% of the time, but the rest of the time the generated images for smaller sizes would only show a few "chunks" of the image and then the rest would be grey, like the original image's modifications hadn't finished before it tried to generate the other sizes.

I have a strong suspicion I'm doing something dumb. Can someone point me to the correct way of doing this?

Thanks so much! :)

**Comment by kgenly** [comment]
Nevermind; I'm discovering the issue is not that I was editing the original image. I'm getting this "generated images for smaller sizes would only show a few "chunks" of the image and then the rest are grey" issue on most images, regardless of whether or not I have manipulated the original.

**Comment by martinschenk** [comment]
found any solution? i also don't want to save the original.
