### ISSUE TITLE
laravel 5.6 failed LaravelMediaLibrary Migration.

### ISSUE THREAD

**Issue by Akhibemudu** [spatie/laravel-medialibrary#1205]
Please, I have this trouble with using LaravelMediaLibrary v7. 
 PHP v 7.3
Am trying to implement MediaLibrary on an existing laravel project v5.6, I have checked the requirement and hv followed the installation guide, but however when i tried to migrate, I get this error
![error](https://user-images.githubusercontent.com/25743690/43875459-69cc5c78-9b88-11e8-96c6-a6c7f34b8679.png)

Note.
I have configured my database in the AppServiceProvider to accept defaultStringLength(191) other tables seems to be fine during migration, but I dont understand why this issue keeps poping up when i try to migrate.
This seems to be my DB Server version: 10.1.31-MariaDB
am using PHPMyAdmin MySQL.

. Thank you for your contribution.

**Comment by Akhibemudu** [comment]
@freekmurze

**Comment by freekmurze** [comment]
I'm sorry but I just don't have the time to look into app specific problems. Pretty sure this error is caused by your environment and not by the package.

Try using MySQL instead of MariaDB.

**Comment by CaesarChan** [comment]
@Akhibemudu  the native json data type supported from mysql 5.7.8 and  mariadb 10.2。

**Comment by Akhibemudu** [comment]
Ok thank you @CaesarChan
