### ISSUE TITLE
FatalThrowableError when delete user

### ISSUE THREAD

**Issue by mohammad-y** [spatie/laravel-medialibrary#1206]
hello
When I delete a user, I get the following error

Argument 1 passed to App\User::Spatie\MediaLibrary\HasMedia\{closure}() must be an instance of Spatie\MediaLibrary\HasMedia\HasMedia, instance of App\User given, called in \vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php on line 360

Note: I also use softDelete for the user model.

**Comment by sebastiandedeyne** [comment]
Does your user model implement the `Spatie\MediaLibrary\HasMedia\HasMedia` interface?

**Comment by mohammad-y** [comment]
Yes
