### ISSUE TITLE
Add $model->addMediaFromContents($contents)

### ISSUE THREAD

**Issue by jhm-ciberman** [spatie/laravel-medialibrary#1207]
Actually I have a file stored by the Laravel Filesystem api. I only have access to it's content, not its URL. 
How can I add a file having only its content?

Example:
```php
public function seedMyDatabase(FakeImageGenerator $myService) 
{
  $imageContent = $myService->getImageContent()
  $product = factory(\App\Product::class);
  $product->addMediaFromContents($imageContent)->toMediaCollection();
}
```

**Comment by jozeflambrecht** [comment]
@jhm-ciberman Do you have a solution for this?

**Comment by jhm-ciberman** [comment]
Nope. I had to refactor my code to use paths instead of the Laravel storage
facade.
