### ISSUE TITLE
in relating the model i got this 

### ISSUE THREAD

**Issue by ELmardi2** [spatie/laravel-medialibrary#1208]
"Trait 'App\HasMediaTrait' not found"

**Comment by spacemudd** [comment]
You did not import the trait to the class you are working in.

I suggest you to learn PHP basics before digging into this.

**Comment by ELmardi2** [comment]
Thanks a lot of for your answer

Le ven. 17 août 2018 à 02:02, Shafiq al-Shaar <notifications@github.com> a
écrit :
