### ISSUE TITLE
get all media from collection, without relation to model

### ISSUE THREAD

**Issue by paulprok** [spatie/laravel-medialibrary#1210]
Hi, how can I get smth like:
$items = Media::getAllMedia($collection_name);
And I can use spatie methods (like getUrl()) of each of items?.

**Comment by kgenly** [comment]
How about...

> Media::where('collection_name', $collection_name)->get()

`

**Comment by paulprok** [comment]
In this way there are not available spatie methods like getUrl and conversions

**Comment by kgenly** [comment]
Are you accessing using a foreach loop? This seems to work fine for me, including with getURL

**Comment by freekmurze** [comment]
`Media` is just a plain model class. It has all methods to generate urls on it. The response of @kgenly seems correct 👍
