### ISSUE TITLE
split apart

### ISSUE THREAD

**Issue by gareth-ib** [spatie/laravel-medialibrary#1213]
It would be nice if all the media and file handling aspects were moved into a separate package(s) so that those could be used directly for non-eloquent media projects by you/community. And just have this project `require` that project and utilize it. I saw some of it is in the `spatie/image` project, but a lot of it seems to be integrated

great job on all these tools though, really!

**Comment by AlexVanderbist** [comment]
Thanks for the suggestion and the compliment! Most of these aspect/features are currently quite interwoven in the the package. I don't think there are any concrete plans to abstract any of these features into separate packages. 

However, all code is open source so feel free to abstract any of it to your own package.
