### ISSUE TITLE
Error InvalidArgumentException  : Driver [] is not supported (after v7.3.11)

### ISSUE THREAD

**Issue by rjsworking** [spatie/laravel-medialibrary#1214]
### UPDATE

I've get back to this issue to try to understand why does the same code work well under 7.3.11 version but not under 7.4.x and 7.5.x versions.
In order to find the issue, I've created a fresh L5.7 project with Mediaib 7.5.1, the very same code, the very same data and it works well,
The culprit is my .env file. I left an empty FILESYSTEM_DRIVER= setting in it.
With L5.7, Medialib 7.5.1 and the empty setting, it throws the exception in the image. 
With L5.6, Medialib <= 7.3.11 and the empty setting, it works ok.

Hi

Got this error when (re)generating responsive images after upgrade to latest version. It's working ok on v7.3.11 but not on v7.3.12 and v7.4.0.

The error is triggered here: vendor/spatie/laravel-medialibrary/src/Filesystem/Filesystem.php, in removeResponsiveImages method
```$allFilePaths = $this->filesystem->allFiles($responsiveImagesDirectory);```

![error_media_lib](https://user-images.githubusercontent.com/9252353/44627267-c7bf8600-a922-11e8-96b8-be512db12c57.png)

Responsive images generation code:
```
$filtered->each(function ($file) use ($model) {

    $model->addMedia($file->getPathname())
        ->preservingOriginal()
        ->withCustomProperties([
            'alt' => $model->details->first()->title,
            'title' => $model->details->first()->title,
        ])
        ->usingFileName($file->getBasename())
        ->withResponsiveImages()
        ->toMediaCollection('content');
});
```

Will stick to v7.3.11 until you provide a fix :)

Cheers

**Comment by lostlian** [comment]
I had this same issue. An the solution was to be quite simple. I was running jobs with horizon and after restart the horizon deamon it started to find the proper disk. Looks like jobs cache the current state of the code and if any changes it wont be applied to jobs
