### ISSUE TITLE
Laravel 5.7 support?

### ISSUE THREAD

**Issue by sinamiandashti** [spatie/laravel-medialibrary#1216]
Hello
could you please provide any information on this?

**Comment by sebastiandedeyne** [comment]
Support will be added when Laravel 5.7 is released. We don't expect any / too many breaking changes.

**Comment by Vanlombardi** [comment]
5.7 released and support is not provided yet. Any timing?

**Comment by Adasso** [comment]
Do you have a date for the release?

**Comment by sebastiandedeyne** [comment]
Laravel 5.7 has already been supported for a while :) https://github.com/spatie/laravel-medialibrary/releases/tag/7.4.1
