### ISSUE TITLE
  Class 'Intervention\Image\ImageServiceProvider' not found

### ISSUE THREAD

**Issue by altdev91** [spatie/laravel-medialibrary#1217]
Hello

When I run composer require spatie/laravel-medialibrary on cmder, I get error:

`Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:

  Class 'Intervention\Image\ImageServiceProvider' not found

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content`

Please help me fix it.

**Comment by AlexVanderbist** [comment]
Are you still experiencing this issue? Can you share the contents of your composer.json file? 

Feel free to close this issue if you're no longer having problems.
