### ISSUE TITLE
Large file uploading problem

### ISSUE THREAD

**Issue by emredipi** [spatie/laravel-medialibrary#1218]
Hello, I cannot upload large files. I increased memory_limit and upload_max_filesize in php.ini but it is not enough to work. I need something like chunk to upload or something else.

I tried to upload with laravel's default store method, it is working correctly. I also tried uploading with laravel's store then getting the image to media library but it is crashing again.
I am taking 500 error. Sometimes it is memory allocating error, sometimes it even cannot give error. (Only 500). What do I need to do ? I think the package crashes on image processing moment, not moving or uploading moment. If I use Amazon S3, will anything change about process ?

**Comment by tomhatzer** [comment]
Can you post the exact error message from your storage/logs/laravel.log file and show us the changes you made to your php.ini (variables you changed with old and new value) and also tell us if those changes are listed in phpinfo please (or if there are still the old values)?

**Comment by emredipi** [comment]
I changed memory_limit and max_upload_size values and it worked. Thanks...
