### ISSUE TITLE
[Feature Request] Support for Laravel Nova

### ISSUE THREAD

**Issue by shirshak55** [spatie/laravel-medialibrary#1222]
Update: From twitter I heard new nova media library is gonna come out :)

**Comment by bernhardh** [comment]
Not perfect yet, but maybe a starting point https://novapackages.com/packages/jameslkingsley/nova-media-library

**Comment by shirshak55** [comment]
@bernhardh  I think spatie is going to make it soon too . Yea started using your package and it is good experience also 

https://twitter.com/freekmurze/status/1036949435094364160

**Comment by freekmurze** [comment]
Working on it, could take a while tough

**Comment by shirshak55** [comment]
It would be nice if we can watch development from early stage :D

**Comment by dinandmentink** [comment]
Really good to hear you are working on this.

Is there any repo I can follow? Are you open to cocreation/PRs?

**Comment by illambo** [comment]
Hi @freekmurze any news about that? :pray:
Seems like the right time for something about it, with Nova 4 (with Vue 3 support) I have not found any packages that currently support the medialibrary (see https://github.com/ebess/advanced-nova-media-library/issues/311 and https://github.com/dmitrybubyakin/nova-medialibrary-field/issues/157).

Do you have any suggestions about it?
Thanks.
