### ISSUE TITLE
Upgrade from v6 to v7

### ISSUE THREAD

**Issue by nessimabadi** [spatie/laravel-medialibrary#1223]
Hi,
On the upgrading guide there's a TODO add instructions / or maybe a script.
Is that on the roadmap?

**Comment by sarhugo** [comment]
This is what I made:

- Regenerate the conversions for every media:
```
php artisan medialibrary:regenerate
```

- Delete old non prefixed files (here my conversion was called thumb):

```
find storage/app/media -name "thumb.jpg" -delete
```

**Comment by freekmurze** [comment]
We have some instructions here: https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md
