### ISSUE TITLE
Multiple Videos

### ISSUE THREAD

**Issue by matthewscalf** [spatie/laravel-medialibrary#1225]
What is the best way to have multiple videos associated for an HTML5 video? It makes sense to me to have a way to convert the videos to other formats like we do for images. Is that possible? Basically if a user uploads an mp4, I want to auto create the webm alternative.

Is it better to just force them to upload both versions? I'd prefer to automate it but was wondering how to incorporate that into this system (I love this system btw).

**Comment by freekmurze** [comment]
Video manipulation is out of scope for this package.
