### ISSUE TITLE
[Question] Default placeholder

### ISSUE THREAD

**Issue by slakbal** [spatie/laravel-medialibrary#1226]
Hi Spatie!!!

While writing the code again for the 100th time for the default behaviour for when a media object doesn't and that a specified placeholder is returned in it's place; I remembered that I made a recommendation in the past on a feature request thread that Freek started. So I scanned over the documentation quickly but couldn't spot something on the first glance, thus I would just kindly like to ask if this recommendation was ever considered and/or implemented?

Here the links to the specific recommendation in the conversation:

https://github.com/spatie/laravel-medialibrary/issues/858#issuecomment-356287609
https://github.com/spatie/laravel-medialibrary/issues/858#issuecomment-356290303

Kindest regards!

**Comment by freekmurze** [comment]
Feel free to submit a fully tested PR that adds this to the package. If the implementation is simple and I'll like the surround API I'll be sure to tag it.
