### ISSUE TITLE
WebP support added recently, but it is not fully implemented

### ISSUE THREAD

**Issue by DeftNerd** [spatie/laravel-medialibrary#1227]
As an example, if you try to create a media conversion to create webp thumbnails, errors abound
```
$this->addMediaConversion('thumb-webp')
    ->format('webp')
    ->fit('fill', 350, 350)
    ->background('FFFFFF');
```

Error (mildly edited) returns:
```
   Spatie\Image\Exceptions\InvalidManipulation  : Format should be one of `jpg`, `pjpg`, `png`, `gif`. `webp` given.

  at /var/www/website/vendor/spatie/image/src/Exceptions/InvalidManipulation.php:25
    21|         $validValues = self::formatValues($validValues);
    22| 
    23|         $name = ucfirst($name);
    24| 
  > 25|         return new self("{$name} should be one of {$validValues}. `{$invalidValue}` given.");
    26|     }
    27| 
    28|     public static function valueNotInRange(string $name, $invalidValue, $minValue, $maxValue)
    29|     {

  Exception trace:

  1   Spatie\Image\Exceptions\InvalidManipulation::invalidParameter("Format", "webp", "`jpg`, `pjpg`, `png`, `gif`")
      /var/www/website/vendor/spatie/image/src/Manipulations.php:429

  2   Spatie\Image\Manipulations::format("webp")
      /var/www/website/vendor/spatie/laravel-medialibrary/src/Conversion/Conversion.php:97

```

It appears that support for Webp has been added to `spatie/laravel-medialibrary`, but there is no support in `spatie/image` or `spatie/image-optimizer`. It might be due to the fact that `league/glide` doesn't support Webp yet (there is a pending merge to support it) even though the underlaying `intervention/image` library supports it. Sometimes it feels like this library is built on a stack of turtles. ;-)

At this early stage, what can we accomplish with `spatie/laravel-medialibrary` using WebP? It might be useful to specify in the documentation what works and doesn't work with WebP support.

**Comment by bernhardh** [comment]
Any updates to this?

**Comment by ixperiencenl** [comment]
Yes this would be very welcome as Google also changed it's Insights algorithm to look more at WebP formats also.

**Comment by AlexMcDee** [comment]
For solving this I added new constant 
```php
const FORMAT_WEBP = 'webp';
```
to class
```php 
class Manipulations
```
for quick fix.
I'm not found any way for overwriting default configs. 
Maybe someone have own solution?

**Comment by idragon81** [comment]
Would be better if we could extract out supported formats to a config file or retrieve it through generators' supportedExtensions() method

**Comment by freekmurze** [comment]
Feel free to send a PR to fix this.

**Comment by idragon81** [comment]
I think that there's a lot of architectural changes required for this.

The ImageGenerators class is on spatie/laravel-medialibrary and not on spatie/image
I think it should be the responsibility of the image library to check whether or not it can handle the file as an image and the medialibrary should just manage the media files and query the image library whenever we need to.

To achieve this I think the ImageGenerators should be a part of the image library instead. As this could take a great while to refactor, we should plan on making the necessary changes for the next major version.  Correct me if I'm wrong, I could be way off about this.

For the meanwhile, I will send a PR to spatie/image to temporarily fix the WebP issue

**Comment by Mina-R-Meshriky** [comment]
any updates!
I can see that spatie/image is adding support for webP on 1.7.0 in the Changelog. However the Latest Version on Packagist is 1.6.0

**Comment by freekmurze** [comment]
@Mina-R-Meshriky whoops, missed that. Just created a release for 1.7.0

**Comment by Kokil** [comment]
its 2023 !!!
