### ISSUE TITLE
registerMediaConversions() function is not working

### ISSUE THREAD

**Issue by eichgi** [spatie/laravel-medialibrary#1230]
```
public function registerMediaConversions(Media $media = null)
    {
        try {
            $this->addMediaConversion('mini')
                ->width(500)
                ->height(500)
                ->performOnCollections('avatar');
        } catch (InvalidManipulation $e) {
        }
    }
```

```
public function registerMediaCollections()
    {
        $this
            ->addMediaCollection('avatar')
            ->singleFile();
    }
```

When I attach the image to the model no error is showing up, even when I try to retrieve the path to mini I got this:

```
$personal->getFirstMedia('avatar')->getUrl('mini');
=> "/storage/2/conversions/1-mini.jpg"
```

![errar](https://user-images.githubusercontent.com/9018836/44997828-bc013e80-af76-11e8-9b5a-c1a68d7b8c08.png)

But as you can see no conversion is stored, only the main collection image.

I am using v7 of the library.

**Comment by freekmurze** [comment]
The tests around this prove that the functionality is working as intended. Could you PR a failing test?

**Comment by franzdumfart** [comment]
Had the same problem because I haven't setup a queue at this points. You need to do that and you will get the converted images.

**Comment by adellinocasas** [comment]
https://github.com/spatie/laravel-medialibrary/issues/1627
