### ISSUE TITLE
How do i update an image?

### ISSUE THREAD

**Issue by SaphiLC** [spatie/laravel-medialibrary#1232]
The documentation is REALLY confusing and bad overall (Retrieving media has a lot of stuff that should go to Associating files, like sanitizing has nothing to do with retrieving, for example...).
Anyways, im unable to find a way to update an image. The only way i see of doing this is by deleteing a previous one and creating a NEW database entry, wich i feel its a really bad idea, for example, imagine 1 million users update their profile photo... its just filling the autoincrement and html with numbers that i feel are not required ... so dont know, maybe there is something im missing, can you help me with this please?

**Comment by freekmurze** [comment]
There's an edit button on every page in the documentation, feel free to PR improvements.

> deleteing a previous one and creating a NEW database entry

This currently is the way to go. Feel free to create a fully tested and documented PR if you need this. If the code is simple I'll consider adding it to the package.
