### ISSUE TITLE
Can't upload photos on shared hosting

### ISSUE THREAD

**Issue by wiktor-mazur** [spatie/laravel-medialibrary#1233]
Hello,

I'm getting the following error on the shared hosting when trying to upload a photo:
`Unexpected error: The Process class relies on proc_open, which is not available on your PHP installation.`
which from my investigation is thrown by Symfony's Process class, because function_exists('proc_open') returns false in my environment.

Is is possible to still use medialibrary? Maybe disabling some feature like media conversions would fix this?

How do I resolve this issue?

**Comment by brendt** [comment]
Media conversions are a big part of the package, there isn't anything in place to simply disable them. I'm afraid that if `proc_open` will be a requirement for the package to work correctly. My suggestion would be to look at a cheap DigitalOcean droplet to run your project on.

**Comment by magarrent** [comment]
Hey! Has anyone dug into this? I'm trying different ways to convert the image but always throws the same error
