### ISSUE TITLE
[Suggestion] getLastMediaUrl()

### ISSUE THREAD

**Issue by danilogkir** [spatie/laravel-medialibrary#1237]
Hello, i think that it would be really useful for the package to have a `getLastMediaUrl()`

**Comment by freekmurze** [comment]
Thanks for your suggestion, but you can easily implement this in your own project.  I try to keep the package as light as it can be.

**Comment by itsrafsanjani** [comment]
If anyone still need this!

```php
App\Models\User.php

public function avatar()
    {
        return $this->getMedia('avatars')
                ->last()
                ->getUrl('thumb') ?? 'https://avatars.dicebear.com/api/bottts/' . $this->name. '.svg';
    }
```

Usage:

```php
auth()->user()->avatar()
```
