### ISSUE TITLE
Installation medialibrary {V.7} Failed for laravel 5.7 

### ISSUE THREAD

**Issue by Jaikangam93** [spatie/laravel-medialibrary#1240]
Getting this error 
Installation request for laravel/framework (locked at v5.7.3, required as 5.7.*) -> satisfiable  by laravel/framework [v5.7.3]
Installation failed, reverting ./composer.json to its original content.

**Comment by freekmurze** [comment]
The latest version of the medialibrary is compatible with L5.7
