### ISSUE TITLE
I  just can't make it work properly  [5.7] [TypeError]

### ISSUE THREAD

**Issue by NietzscheCoder** [spatie/laravel-medialibrary#1243]
Hey guys  I installed this package and everything works fine, I published  both migration and config files.

When I try to use it just as the README.md suggest
I'm doing the following on tinker

`$user = User::find(1)`
`$user->addMedia('/home/bob/db.png')->toMediaCollection('images');`

I get an error:

> TypeError: Argument 1 passed to Spatie/MediaLibrary/FileAdder/FileAdder::processMediaItem() must be an instance of Spatie/MediaLibrary/HasMedia/HasMedia, instance of App/User given, called in/var/www/html/wperp/vendor/spatie/laravel-medialibrary/src/FileAdder/FileAdder.php on line 296

My User.php has the following

`use Spatie\Permission\Traits\HasRoles;`
`use Spatie\MediaLibrary\HasMedia\HasMedia;`
`use Spatie\MediaLibrary\HasMedia\HasMediaTrait;`

`use App\Project;`

`class User extends Authenticatable`
`{`
   ` use Notifiable;`
    `use HasRoles;`
   ` use HasMediaTrait;`
   `....`

What am I doing wrong here?

Without using tinker I try to add the same snippet in a  create method of a controller and I get this error:
`Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)`
`Call to undefined function App\Http\Controllers\toMediaCollection()`

My create method:

> $user = User::create($user_create_validated)->addMedia(storage_path($request->input('file')))>toMediaCollection('images');

Is there something wrong with the code?

**Comment by freekmurze** [comment]
Change `>toMediaCollection` to `->toMediaCollection`

**Comment by savshit** [comment]
Hello,
I have error in below code:

```
$request->user()->addAllMediaFromRequest()->each(function ($fileAdder) use (&$filename) {
   $filename = $fileAdder->toMediaCollection()->getPath();
});
```
I get media data in $fileAdder, but when i do like $fileAdder->toMediaCollection() it give me an error.

Can anyone help on this?
Thank you.
