### ISSUE TITLE
Responsive image generation skipped

### ISSUE THREAD

**Issue by OpenHaus** [spatie/laravel-medialibrary#1244]
Hi,

I have this really weird issue I cannot solve and am not really able to locate.
I wrote a command to generate response images for use as backgrounds in my site.

```
$model
 ->addMedia($file)
 ->withResponsiveImages()
 ->toMediaCollection($collection);
```

This works fine on my local system, in my development system and has worked once in the live version of the site. I more or less accidentally called the command to generate the images again which should be no problem and is not a problem in the local and development environment. But in the live version the command now just adds the files to the model but skips the responsive image generation completely.

I clear out the collection before I (re-)add new media:

`$model->clearMediaCollection($collection);`

I have checked that the filesystem is writeable. There is no hint in the log file when debugging is enabled.

I have the latest versions installed:

spatie/laravel-medialibrary           7.5.1
laravel/framework                     v5.7.3

I had the same problem with previous versions (7.5.0, latest 7.4.x).

Any help and hint is appreciated. Thank you, also for an otherwise great library!

**Comment by kiwina** [comment]
Conversions are queued by default. try with sync driver to convert them

**Comment by OpenHaus** [comment]
Thank you that was the correct hint. Somehow the queue was never processed.
