### ISSUE TITLE
PDF thumbnail created with addMediaConversion results in greyscale jpeg

### ISSUE THREAD

**Issue by beard7** [spatie/laravel-medialibrary#1245]
The title says it all. I've registered media conversions in my model and I'm uploading PDFs.

Out of approximately 40 uploads, around 15 have resulted in grayscale thumbnails from colour PDFs.

There doesn't seem to be anything different about the PDFs. They are of various sizes: between 177KB and 3MB, some of the greyscale thumbs are from the larger PDFs and some from smaller PDFs.

Any ideas?

**Comment by freekmurze** [comment]
Cannot reproduce this, feel free to submit a fix should you find that this problem is caused by our package.
