### ISSUE TITLE
Dispatch event after media added

### ISSUE THREAD

**Issue by Nuranto** [spatie/laravel-medialibrary#1247]
I want to optimize (and eventually resize) image files on upload.

I wanted to deal with that using `Media::created` event, but the media is saved before the image is moved to final system file path.

A great thing would be to dispatch a new event  - "FileAdded" for example - so we can work on it directly.

Of course, the other option is to do this on a background task. But in that case, there is a risk of image being cached by client browser before optimize/resize.

(NB : Another solution, but more specific, would be to do something like this : `$obj->addMediaFromRequest('file')->optimize()->resize(Manipulations::FIT_MAX, 1500, 1000)->toMediaCollection('photos');`).
(NB2 : You will probably ask : why not leave optimize/resize to conversions ? Well, I will deal with a huge amount of images, and I'm trying to limit as much as possible the weight of medias...)

**Comment by AndreasHerss** [comment]
Can't you just use the events fired already? 
i'm thinking of the MediaHasBeenAdded event, it specifically says it's fired after the file is stored

https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/consuming-events

**Comment by Nuranto** [comment]
Because I've missed it -_-

You're absolutely right.

**Comment by reppair** [comment]
What I am looking for too :)
