### ISSUE TITLE
Naming the files on the disk

### ISSUE THREAD

**Issue by catalinux** [spatie/laravel-medialibrary#1250]
Is there a way to define globally a way to define how the files are saved  on the disk?

I know there is a way to use `usingFileName`, but I would like to be able to defined that all my files would be named something like `function(Media $media){ return 'filename-'.$media->getKey()}`

If this is not possible would it be Ok to make such feature?

**Comment by catalinux** [comment]
Is it Ok to open a PR for such a feature?

**Comment by freekmurze** [comment]
Feel free to submit a fully tested PR. if the code is simple enough for me to maintain I'll consider merging it 👍

**Comment by designvoid** [comment]
hey @freekmurze did a PR ever get submitted for this?

**Comment by freekmurze** [comment]
I don't think so.
