### ISSUE TITLE
I couldn't install this package with Laravel 5.7.*

### ISSUE THREAD

**Issue by eichgi** [spatie/laravel-medialibrary#1253]
Composer throws this message:

```
Problem 1
    - Installation request for spatie/laravel-medialibrary 7.0.0 -> satisfiable by spatie/laravel-medialibrary[7.0.0].
    - Conclusion: remove laravel/framework v5.7.6
    - Conclusion: don't install laravel/framework v5.7.6
    - spatie/laravel-medialibrary 7.0.0 requires illuminate/pipeline ~5.5.0|~5.6.0 -> satisfiable by illuminate/pipeline[5.5.x-dev, 5.6.x-dev, v
5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.6.0, v5.6.1, v5.6.
10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.2
6, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v
5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/pipeline 5.5.x-dev|don't install laravel/framework v5.7.6
.......
- Installation request for laravel/framework (locked at v5.7.6, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.6].
```

How can I achieve the installation?

**Comment by dundermave** [comment]
yup, not able to install on 5.7.*

**Comment by bscript** [comment]
Working fine on : Laravel Framework 5.7.6 
![fine](https://user-images.githubusercontent.com/43368124/46297852-608e9480-c5a6-11e8-8eda-dcae3631159c.png)

Could post your composer.json content here !

**Comment by eichgi** [comment]
@dundermave as you mentioned, it works. 

I guess the doc shoulnd't specify the version, just the name of the package as you did.

Thanks!

**Comment by MdkanokHossain** [comment]
I am also here stack with the same problem.

**Comment by leonardolouie** [comment]
same problem heree help T_T

**Comment by leonardolouie** [comment]
Gloudemans/shoppingcart not installing

**Comment by eichgi** [comment]
@MdkanokHossain & @leonardolouie did you already tried to use the command @dundermave posted before??

**Comment by ikikay** [comment]
Still won't work for me ... 5.6 or 5.7 ..

>composer require spatie/laravel-medialibrary

Using version ^7.5 for spatie/laravel-medialibrary
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v5.7.11
    - Conclusion: don't install laravel/framework v5.7.10
    - Conclusion: don't install laravel/framework v5.7.9
    - Conclusion: don't install laravel/framework v5.7.8
    - Conclusion: don't install laravel/framework v5.7.7
    - Conclusion: don't install laravel/framework v5.7.6
    - Conclusion: don't install laravel/framework v5.7.5
    - Conclusion: don't install laravel/framework v5.7.4
    - Conclusion: don't install laravel/framework v5.7.3
    - Conclusion: don't install laravel/framework v5.7.2
    - Conclusion: don't install laravel/framework v5.7.1
    - Conclusion: don't install laravel/framework v5.7.0
    - laravelcollective/html 5.6.x-dev requires illuminate/view 5.6.* -> satisfiable by laravel/framework[5.6.x-dev], illuminate/view[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravelcollective/html v5.6 requires illuminate/view 5.6.* -> satisfiable by laravel/framework[5.6.x-dev], illuminate/view[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravelcollective/html v5.6.1 requires illuminate/view 5.6.* -> satisfiable by laravel/framework[5.6.x-dev], illuminate/view[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravelcollective/html v5.6.10 requires illuminate/view 5.6.* -> satisfiable by laravel/framework[5.6.x-dev], illuminate/view[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravelcollective/html v5.6.2 requires illuminate/view 5.6.* -> satisfiable by laravel/framework[5.6.x-dev], illuminate/view[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravelcollective/html v5.6.3 requires illuminate/view 5.6.* -> satisfiable by laravel/framework[5.6.x-dev], illuminate/view[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravelcollective/html v5.6.4 requires illuminate/view 5.6.* -> satisfiable by laravel/framework[5.6.x-dev], illuminate/view[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravelcollective/html v5.6.5 requires illuminate/view 5.6.* -> satisfiable by laravel/framework[5.6.x-dev], illuminate/view[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravelcollective/html v5.6.6 requires illuminate/view 5.6.* -> satisfiable by laravel/framework[5.6.x-dev], illuminate/view[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravelcollective/html v5.6.7 requires illuminate/view 5.6.* -> satisfiable by laravel/framework[5.6.x-dev], illuminate/view[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravelcollective/html v5.6.8 requires illuminate/view 5.6.* -> satisfiable by laravel/framework[5.6.x-dev], illuminate/view[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravelcollective/html v5.6.9 requires illuminate/view 5.6.* -> satisfiable by laravel/framework[5.6.x-dev], illuminate/view[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - Can only install one of: laravel/framework[5.7.x-dev, 5.6.x-dev].
    - don't install illuminate/view 5.6.x-dev|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.0|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.1|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.10|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.11|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.12|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.13|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.14|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.15|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.16|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.17|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.19|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.2|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.20|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.21|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.22|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.23|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.24|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.25|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.26|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.27|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.28|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.29|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.3|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.30|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.31|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.32|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.33|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.34|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.35|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.36|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.37|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.38|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.39|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.4|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.5|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.6|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.7|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.8|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/view v5.6.9|don't install laravel/framework 5.7.x-dev
    - Installation request for laravel/framework 5.7.* -> satisfiable by laravel/framework[5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.2, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - Installation request for laravelcollective/html 5.6.* -> satisfiable by laravelcollective/html[5.6.x-dev, v5.6, v5.6.1, v5.6.10, v5.6.2, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].


Installation failed, reverting ./composer.json to its original content.

**Comment by leonardolouie** [comment]
@eichgi  i use other package and its work now https://github.com/darryldecode/laravelshoppingcart

**Comment by irfan-mirza686** [comment]
@eichgi .. i also try this "darryldecode" its work but "Gloudemans" not working .

**Comment by freekmurze** [comment]
This problem is not caused by this package.

Use `prohibits` to find out which package is the culprit of the problems: https://getcomposer.org/doc/03-cli.md#prohibits-why-not-

**Comment by nickforbizz** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install beyondcode/laravel-websockets 1.1.1
    - Conclusion: remove guzzlehttp/psr7 1.4.2
    - Installation request for beyondcode/laravel-websockets ^1.1 -> satisfiable by beyondcode/laravel-websockets[1.1.0, 1.1.1].
    - Conclusion: don't install guzzlehttp/psr7 1.4.2
    - beyondcode/laravel-websockets 1.1.0 requires guzzlehttp/psr7 ^1.5 -> satisfiable by guzzlehttp/psr7[1.5.0, 1.5.1, 1.5.2, 1.5.x-dev].
    - Can only install one of: guzzlehttp/psr7[1.5.0, 1.4.2].
    - Can only install one of: guzzlehttp/psr7[1.5.1, 1.4.2].
    - Can only install one of: guzzlehttp/psr7[1.5.2, 1.4.2].
    - Can only install one of: guzzlehttp/psr7[1.5.x-dev, 1.4.2].
    - Installation request for guzzlehttp/psr7 (locked at 1.4.2) -> satisfiable by guzzlehttp/psr7[1.4.2].


Installation failed, reverting ./composer.json to its original content.

**Comment by NeutroCoder** [comment]
Use the below code to install the latest package of the Laravel Media Library.

`composer require spatie/laravel-medialibrary`

![Capture](https://user-images.githubusercontent.com/45868877/57981986-9e381480-79f3-11e9-9639-3e70fc4ca225.PNG)

**Comment by ahmedsammygeek** [comment]
still can't install it after install  on laravel 5.7.28
composer require spatie/laravel-medialibrary

**Comment by tripletens** [comment]
i have similar issue with installing socialite
composer require laravel/socialite
i need help please

**Comment by CoryGrandstaff** [comment]
Did you find a solution Tripletens?

**Comment by tripletens** [comment]
Not yet

**Comment by tripletens** [comment]
composer require spatie/laravel-medialibrary

Let me try this one

**Comment by Towhid86** [comment]
how can i solve this problem forlaravel-medialibrary ......



![problem](https://user-images.githubusercontent.com/40929493/64437535-3d3e6480-d0e8-11e9-972c-9bed97053cdd.JPG)

**Comment by Bunix** [comment]
ok found a hacky solution provided by @jstoone:
add this to your composer.json:

{
    "require": {
+       "spatie/laravel-medialibrary": "^7.0.0"
    },
+   "provide": {
+       "ext-imagick": "*"
+   },
    "require-dev": {

    }
}

**Comment by Adamkaram** [comment]
try this version from maennchen/zipstream-php
"maennchen/zipstream-php": " ^1.2",
work for me after every thing i tried

**Comment by istiake5** [comment]
if you're trying to install it on Laravel 5.7, you should use an older version: composer require beyondcode/laravel-websockets:1.3

The latest (1.4) version only supports Laravel 5.8, 6.x and 7.x.
