### ISSUE TITLE
Media files are stored in public disk instead of the configured one

### ISSUE THREAD

**Issue by lasselehtinen** [spatie/laravel-medialibrary#1254]
For some reason the media files are now being stored in the public folder instead of the one configured in /config/filesystems.php. This used to work for just fine for over a year and I haven't touched the code. I cannot figure out why is it now using the public folder, that is not even the default filesystem in Laravel.

![image](https://user-images.githubusercontent.com/1290186/46279181-163ef080-c571-11e8-8411-3cafce69c17a.png)

![image](https://user-images.githubusercontent.com/1290186/46279025-aa5c8800-c570-11e8-91cc-a1b7f7007b92.png)

**Comment by lasselehtinen** [comment]
I think I solved the issue. I did run `php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="config"` after the upgrade, but it seems that it does not overwrite an existing file. So the default_filesystem has been actually changed to disk_name.

**Comment by michaelthuren** [comment]
Upgrading from a previous version to v8, the configuration was renamed from medialibrary.php to media-library.php. This caused the media_disk configuration to be ignored and fallback to public
