### ISSUE TITLE
Responsive images do not respect custom name

### ISSUE THREAD

**Issue by robinvdvleuten** [spatie/laravel-medialibrary#1257]
When I generate responsive images using the following code;

```php
$this->addMedia($file)
  ->usingName('avatar')
  ->withResponsiveImages()
  ->toMediaCollection('avatar');
```

I expect that each responsive variant is named like `avatar___medialibrary_original_400_400.jpg`, but they still have the original uploaded filename.

**Comment by freekmurze** [comment]
Feel free to PR a fix with tests for this.

**Comment by VincentKos** [comment]
@freekmurze did you really expect this behavior ? Aren't we supposed to use usingFileName() to rename the file and usingName() just for the name in the record?

**Comment by freekmurze** [comment]
@VincentKos you're right!
