### ISSUE TITLE
Storage path is not part of public path

### ISSUE THREAD

**Issue by nguyenhoangnam123** [spatie/laravel-medialibrary#1259]
Hi
My app is using laravel 5.6 and spatie media library. it works well on localhost but gets this error when upload to shared hosting:
`Storagepath `` is not part of public path /home/lcezuinhosting/qatech/public`

My file structure on shared hosting
![structure](https://user-images.githubusercontent.com/26792601/46462930-e6038600-c7ec-11e8-8fd0-b7b824be289a.png)
i put all files except public into new folder named **qatech**  and all files in public to public_html

My `filesystems.php`
![image](https://user-images.githubusercontent.com/26792601/46462164-e4d15980-c7ea-11e8-8bfa-c46b48fea70a.png)

Anybody help? Many thanks!

**Comment by AbdelElrafa** [comment]
Did you symlink your public/storage? 
Run `php artisan storage:link` 

> Create a symbolic link from "public/storage" to "storage/app/public"

**Comment by Joucke** [comment]
Also, is your public linked to your public_html?
