### ISSUE TITLE
[Question] Why do we need to call ->toMediaCollection() to save? 

### ISSUE THREAD

**Issue by AbdelElrafa** [spatie/laravel-medialibrary#1261]
I'm just wondering why do we need to call `->toMediaCollection()` to save the media? Can't it be called automatically in the destructor? 

Calling `$user->addMedia($path)` is just much cleaner. I'm aware that `toMediaCollection($collectionName, $diskName)` accepts these params, and is a useful function. However there are defaults set so calling it in the destructor would be a nice option. 

Happy to work on a PR for this just wondering if I'm missing something.

**Comment by freekmurze** [comment]
Thank you the suggestion, but leaving this as it is for now.
