### ISSUE TITLE
steps on conversion

### ISSUE THREAD

**Issue by mhardaniel123** [spatie/laravel-medialibrary#1264]
Hi sir, may i know the step by step process of conversion..

i already commented out the function but it is still running the conversion.. i don't get where it is happening.. pls. see below attached..

i need to know the logic so that i can input my own logic..
i'm using cloudinary as driver..

tnx..

![capture](https://user-images.githubusercontent.com/26666891/46732124-32ecce00-ccbf-11e8-8ee3-35394c685159.PNG)

**Comment by oluwajubelo1** [comment]
@mhardaniel , please can you show me an example of how to integrate cloudinary with this package? I've been finding it difficult. Thanks
