### ISSUE TITLE
File '/' does not exist when trying to upload an mp3/mp4 file

### ISSUE THREAD

**Issue by shabaz-ejaz** [spatie/laravel-medialibrary#1266]
I'm trying to upload MP3/MP4 audio files but I keep the following error:

> Spatie \ MediaLibrary \ Exceptions \ FileCannotBeAdded \ FileDoesNotExist
File `/` does not exist

![image](https://user-images.githubusercontent.com/29374282/46814752-49ebf880-cd71-11e8-8da7-6fb44ee6e4b6.png)

I have the following in my config:

`'max_file_size' => 1024 * 1024 * 100`

My PHP settings:

`upload_max_filesize = 1024M` and `post_max_size=1024M`

Running Laravel 5.6 and medialibrary 7.0.0

The file I am uploading is around 5MB.

Does anyone know what's going on here?

**Comment by freekmurze** [comment]
Probably your PHP process does not allow uploads bigger than the default, which is set to 2MB on most systems. Google a bit around on how to check this and allow for bigger uploads.

**Comment by awladdeleo** [comment]
did you solve the issue ??

**Comment by IVNtech** [comment]
I got the same problem, I figure out that the HTML FORM tag must have this code
enctype="multipart/form-data"

This way the request will handle the submit with an img on it.

```
<form method="" action="" enctype="multipart/form-data">
</form>
```

**Comment by dipakladanitatvasoft** [comment]
i am also facing same issue in laravel 9
