### ISSUE TITLE
How To Get Base64 String?

### ISSUE THREAD

**Issue by BenQoder** [spatie/laravel-medialibrary#1269]
How do i get base64 JPG string as tiny placeholder instead of SVG for progressive image loading?

I need this because I am using this this package to work on a React Native app and React Native doesn't work well with SVG even as base64 string.

I am seeking for an implementation to help me get base64 JPG string instead of base64 SVG

Thanks For Your Help In Advance.

**Comment by larry852** [comment]
```php
$path   = $media->getPath();
$type   = pathinfo($path, PATHINFO_EXTENSION);
$data   = file_get_contents($path);
$base64 = 'data:application/' . $type . ';base64,' . base64_encode($data);
return response()->json(['type' => $type, 'file' => $base64]);
```

**Comment by mknparreira** [comment]
This is worked for me. Thanks!!!!

**Comment by verybigelephants** [comment]
just a slight fix to the @larry852's answer:

$base64 = 'data:**image**/' . $type . ';base64,' . base64_encode($data);
