### ISSUE TITLE
Gallery model?

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#127]
so id like to make a Image model, a place to upload many images too.
so i created a model Image.php, I added two fields to it, title and desc.

Now with every image upload I get a new entry in the media table and the images table and I attach the image with the object.

```
public function store(Request $request) {

        $image = Image::create();

        $image->addMedia($request->file('file'))->toCollection('images');;

        return 'Image was saved successfully!';

    }
```

What I now need is to pull all the gallery objects images that are attached to them and loop through them the getMedia is not working for this like ...
```
$images = Image::all();
$images->getMedia('thumb');
```

any ideas how I could do this?

**Comment by freekmurze** [comment]
You can use `collection`'s `each` method for this.

```php
$images->each(function(Image $image) {
    $images->getMedia('thumb')->each(Media $media) {
          ...
    });
});
```

**Comment by kickthemooon** [comment]
the three dots? do I have to write something additional there?

**Comment by freekmurze** [comment]
Replace the three dots by the specific code that you want to be executed for every Media item that is related to `$images`.
