### ISSUE TITLE
Conversions directories are always attaching to 'root:root' owner on my server

### ISSUE THREAD

**Issue by ysfkaya** [spatie/laravel-medialibrary#1270]
Server Informations :

- Apache2

- Centos7

- PHP 7.2

When I upload a image to server then `conversions` directory always attaching to `root:root` owner. So I can't access by the client. 

When I contact to my server admin they said that : 

> The upload plug-in used for Laravel is changing the directory permissions to `root:root` 

What should I do ?

**Comment by nguyentranchung** [comment]
same problem, and cannot remove folder when insert new image

**Comment by nguyentranchung** [comment]
![image](https://user-images.githubusercontent.com/9611224/46956241-c8c59600-d0cf-11e8-8c88-cd05099c3719.png)

![image](https://user-images.githubusercontent.com/9611224/46956333-01656f80-d0d0-11e8-9724-f12f9df0aa65.png)
Bonus image

**Comment by ysfkaya** [comment]
@nguyentranchung Are you use supervisor or another 3rd party software for queues ?

**Comment by ysfkaya** [comment]
I'm using supervisor for queues. I was changes supervisor user root as a current user and did it works.

![screenshot_4](https://user-images.githubusercontent.com/16710972/46960113-6c01b580-d0a6-11e8-975c-4e7523902d90.png)
