### ISSUE TITLE
PDF to Image thumbnails have a black background - with possible solution

### ISSUE THREAD

**Issue by Dmarthaller** [spatie/laravel-medialibrary#1271]
I'm doing a media conversion for a a multi-page pdf document and it is generating the thumbnail for the first page but the background is all black. 

I have tried to change the generated image from jpg to png with no change.
I have tried to set the background to 'white' with no change.
I have tried to set the background to 'black' with no change.

This is the generated file: 
![image](https://user-images.githubusercontent.com/7152441/46982756-744ff580-d092-11e8-972a-7b389ce708f9.png)

This is the original file's first page:
![image](https://user-images.githubusercontent.com/7152441/46982798-a82b1b00-d092-11e8-87d1-2d1dab519143.png)

I'm not sure what to try next.

**Comment by Dmarthaller** [comment]
Well I found how to correct this issue. This package has a dependency on spatie pdf-to-image and in the src\Pdf.php class, getImageData Method which reads as:
```
  public function getImageData($pathToImage)
    {
        $imagick = new \Imagick();

        $imagick->setResolution($this->resolution, $this->resolution);

        $imagick->readImage(sprintf('%s[%s]', $this->pdfFile, $this->page - 1));

        $imagick->mergeImageLayers(\Imagick::LAYERMETHOD_FLATTEN);

        $imagick->setFormat($this->determineOutputFormat($pathToImage));

        return $imagick;
    }
```
Should be:
```
  public function getImageData($pathToImage)
    {
        $imagick = new \Imagick();

        $imagick->setResolution($this->resolution, $this->resolution);

        $imagick->readImage(sprintf('%s[%s]', $this->pdfFile, $this->page - 1));

        $imagick = $imagick->mergeImageLayers(\Imagick::LAYERMETHOD_FLATTEN);

        $imagick->setFormat($this->determineOutputFormat($pathToImage));

        return $imagick;
    }
```

How do I go about updating this in my project without overwriting the vendor file?

**Comment by Dmarthaller** [comment]
I have verified that manually changing the composer.json to include pdf-to-image v1.4 or greater has solved my problem.

**Comment by oluwajubelo1** [comment]
@Dmarthaller , can you please show me the way on how you solved this? I'll be grateful. Thanks
