### ISSUE TITLE
Single Collection bug with 5.7 ?

### ISSUE THREAD

**Issue by Nuranto** [spatie/laravel-medialibrary#1273]
Since I migrated to Laravel 5.7, all my single collection are not working anymore.

On upload, it seems that "clearMediaCollectionExcept" (called from `FileAdder::processMediaItem`) deletes the new uploaded file and not only the old one...

I did not identify the exact issue yet, I'll update if I find a fix.

**Comment by rubenvanassche** [comment]
@Nuranto, @ambengers, @anouarabdsslm are you using an Custom Path generator(https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-a-custom-directory-structure) ?

**Comment by Nuranto** [comment]
Sorry I did not update...
Yes, I use a custom path, and that was the issue... 
You *must* use media id as final folder....

**Comment by rubenvanassche** [comment]
@ambengers, @anouarabdsslm I made the same error when trying to find the error(using the model_id instead of the media id in the path generator). Can it be you made this error too? I will close the issue for now.

**Comment by ambengers** [comment]
@rubenvanassche apparently I did (code below). So this means we cannot use model_id in the path generator at all? Or can we use model_id but have to be in conjunction with the media_id?

```
/**
     * Get the path for the given media, relative to the root storage path.
     *
     * @param  Spatie\MediaLibrary\Models\Media $media
     * @return string
     */
    public function getPath(Media $media): string
    {
        return $media->model_type . '/'
            . $media->model_id . '/'
            . $media->collection_name . '/';
    }
```

**Comment by rubenvanassche** [comment]
@ambengers that's right, you should not use the model_id.
