### ISSUE TITLE
How to handle retina displays?

### ISSUE THREAD

**Issue by royduin** [spatie/laravel-medialibrary#1276]
Never thought about this but a client noticed images where a little bit blurry with a media conversion. I was cropping a image to 100px and I'm displaying 100px in the frontend. For now I've raised the size to 200px, so a 200px image will be loaded where a 100px image should be. Problem solved, but is that the way to go? And what about the responsive images feature build in?

**Comment by freekmurze** [comment]
Responsive images should look good on retina displays out of the box. Your browser will pick the right one for the screen used

The package does not do anything special for other images. Your browser will just try to display it as best as it can.

**Comment by royduin** [comment]
That's not the case as far as I know @freekmurze. Just inspect your thumbnail on the left of your message here on Github, displayed as 44px but a 88px is loaded. Change the url from 88 to 44 and you'll see the problem on a device with a retina display; a blurry image. I've "embedded" our avatars so you can compare:

<img width="44" src="https://avatars1.githubusercontent.com/u/483853?s=88&v=4"><img width="44" src="https://avatars1.githubusercontent.com/u/483853?s=44&v=4">

<img width="44" src="https://avatars1.githubusercontent.com/u/1703233?s=88&v=4"><img width="44" src="https://avatars1.githubusercontent.com/u/1703233?s=44&v=4">

**Comment by royduin** [comment]
Please reopen @freekmurze
