### ISSUE TITLE
::addMedia does not exist.

### ISSUE THREAD

**Issue by laravelcoder** [spatie/laravel-medialibrary#1280]
I keep getting this error when i try to upload a file. 
```
Method App\Http\Controllers\Admin\ClipsController::addMedia does not exist.
```
Here is my store function in the controller. 
```php
    public function store(StoreClipsRequest $request)
    {
        if (! Gate::allows('clip_create')) {
            return abort(401);
        }
        $clip = Clip::create($request->all());
        $request = $this->saveFiles($request);
        
        foreach ($request->input('videos', []) as $data)
        {
            $clip->videos()->create($data);
            $this->addMedia($request->input('videos[1][video]'))->toMediaCollection('videos', 'local');
        }

        foreach ($request->input('brands', []) as $data) 
        {
            $clip->brands()->create($data);
        }
        return redirect()->route('admin.clips.index');
    }
```
any assistance would be greatly appreciated. 
thanks

**Comment by nicolasbeauvais** [comment]
Hello @laravelcoder,

`addMedia` need to be called on a Eloquent Model, in your exemple you are calling the function on `$this` which in this context is a Controller, not a model.

You could take a look a the following piece of documentation to understand how to use this package:

[Preparing an Eloquent Model](https://docs.spatie.be/laravel-medialibrary/v7/basic-usage/preparing-your-model)

**Comment by laravelcoder** [comment]
Oops i was just trying different things here is the code it was supposed to be. 
```
    public function store(StoreClipsRequest $request)
    {
        if (! Gate::allows('clip_create')) {
            return abort(401);
        }
        $clip = Clip::create($request->all());
        $request = $this->saveFiles($request);
   
        foreach ($request->input('videos', []) as $data)
        {
            $clip->videos()->addMedia($request->input('videos[1][video]'))->toMediaCollection('videos', 'local');
        }
        foreach ($request->input('brands', []) as $data) 
        {
            $clip->brands()->create($data);
        }
        return redirect()->route('admin.clips.index');
    }
```

**Comment by nicolasbeauvais** [comment]
Again you are not calling the function on a model but on a  `HasMany` relationship. To get a collection of video you should use `$clip->videos` instead of  `$clip->videos` [documentation](https://laravel.com/docs/5.7/eloquent-relationships#relationship-methods-vs-dynamic-properties)

Clip <=> Videos is a one-to-many relationship, if you want to add the media to all the videos of your clip you could do it like this:

```php
$clip->videos->each(function ($video) use ($request) {
    $video->addMedia($request->input('videos[1][video]'))->toMediaCollection('videos', 'local');
});
```

Or retrieve the coreesponding video model and add the media:
```php
Video::find($id)->addMedia(...);
```
