### ISSUE TITLE
Use V6 with Laravel 5.7? 

### ISSUE THREAD

**Issue by Robertbaelde** [spatie/laravel-medialibrary#1284]
Is it possible to update Laravel to 5.7 without updating this package from V6 to V7? I don't like to upgrade the package to V7 because of the vague upgrade guide with the warning that the upgrade guide does not cover all changes.

**Comment by lmartins** [comment]
Should be possible but you should wait. Please see https://github.com/spatie/laravel-medialibrary/issues/1288

**Comment by freekmurze** [comment]
6.9.2 has support for L5.7
