### ISSUE TITLE
Many-to-Many polymorphic instead of Many-to-One polymorphic ?

### ISSUE THREAD

**Issue by AurelienMendes** [spatie/laravel-medialibrary#1285]
Hello .. 
I like so much your package but I don't really understand why you restrict the relationship to a Many-To-One instead of a Many-To-Many.

In many project I've to attach the same media to many Models ... so I can't use your package for this purpose and its' really shame.

Do you intend to do this transition one day ?

Many thanks,
Aurélien

**Comment by BenQoder** [comment]
I don’t think this package is intended for that purpose.

You can try creating a model that has Many-To-Many relationship then attach media library files to it.

**Comment by freekmurze** [comment]
For our projects Many-to-One makes much more sense. It's much lighter to work with. 

Feel free to fork our code and create a version that use the many-to-many.
