### ISSUE TITLE
v6.9.1 breaks backward compatibility

### ISSUE THREAD

**Issue by flowlep** [spatie/laravel-medialibrary#1288]
Hello,

It seems the new version v6.9.1 breaks the backward compatibility with v6.9.0.
For example, Media class is now in namespace : 
`Spatie\MediaLibrary\Models`
instead of 
`Spatie\MediaLibrary`

Could you check please ?

Thanks in advance :)

**Comment by lmartins** [comment]
Having the same issue and not really sure why. The model relocation seems to be related to v.7 although my dependencies still declare 6.9, which I've just tried to upgrade to 6.9.1 so I could upgrade to Laravel 5.7

**Comment by flowlep** [comment]
This release seems to be based on v7.5.1, not 6.9.*

**Comment by gpluess** [comment]
I think @flowlep is right, I just experienced the same issue

**Comment by kolydart** [comment]
+1
I had to downgrade to stop fatal error

**Comment by chrisGeonet** [comment]
Same here

In MediaLibraryServiceProvider.php line 33:
  Class 'Spatie\MediaLibrary\Media' not found

**Comment by palypster** [comment]
Same here, it's broken. It's obviously just a typo in a release name, even the code looks as in v7.

**Comment by freekmurze** [comment]
My apologies for these errors, I seem to have added a tag to the wrong branch.

I've unpublished 6.9.1 and made sure that 6.9.2 is tagged with the right branch as it's source.

Avoid installing 6.9.1, if you're already on it, simply run `composer update` to install 6.9.2.
