### ISSUE TITLE
change public to public_html and image uploaded to public

### ISSUE THREAD

**Issue by Khaled-Elfishawy** [spatie/laravel-medialibrary#1289]
i have change public to public_html and put the Application out of the public_html
ex:
ets/
 -app
 -routes
 ....
public_html/
 -css
 -media
 -js
 ...
the image should be uploaded to public_html/media
but i see that an public folder created on the ets/ folder and the images uploaded in it 
please help me upload the images to public_html/media

**Comment by freekmurze** [comment]
Make sure that the `disk` name you set in the config of this package matches one of the disks in the `filesystems` config file. Make sure that disk has the root path you want.
