### ISSUE TITLE
media retrieving problem

### ISSUE THREAD

**Issue by TechShankar** [spatie/laravel-medialibrary#1290]
i'm all setup correctly image saved correctly database and storage but retrieving null returned. anyone help me.

**Comment by pianistprogrammer** [comment]
I have the same issue too, all setup for me, I tried to inspect the url of the image to be shown i get something like this http://localhost/storage/1/conversions/Jeery-thumb.jpg which is the correct path, but the thumb doesn't show, Then i added the port on which my laravel project is served, then i saw the image localhost:8000/storage/1/conversions/Jeery-thumb.jpg. How can this be handled?

**Comment by Wikiki** [comment]
I have the same behavior :-(
Did you find how to solve this ?

**Comment by pianistprogrammer** [comment]
Yea, I used a different technique, saving the file to a folder called upload while sending a redefined file name to db
        ```
$file = $request->file('file');
        $ext = $file->getClientOriginalExtension();
        $newName = rand(100000, 1001238912) . "." . $ext;
        $file->move('uploads/file', $newName);
```
If you want more direction, hit me up jeremiahabimbola@outlook.com, I can send you files with already done codes
