### ISSUE TITLE
The root path /var/tmp/ is not readable.

### ISSUE THREAD

**Issue by atzen88** [spatie/laravel-medialibrary#1293]
Class `Spatie\Image\GlideConversion` using `sys_get_temp_dir()` in method `createGlideServer` to define the `cache-path` which can trow an error on some shared hostings. I have tried to set the path via php.ini but this had no effect in my enviroment

Error Output: The root path /var/tmp/ is not readable.

Finally I have overriden `sys_get_temp_dir()` with `$_SERVER['DOCUMENT_ROOT']./temp` which works for me.

Before I have tried to set this path to the path provided in the config parameter `temporary_directory_path` which has trown a new error for me and because I was tired i just have set the above solution. Error was, that `League\Glide\Server::construct` exptects `FilesystemInterface` as second argument but `TemporaryDirectory` was given.

**Comment by freekmurze** [comment]
I believe there's already an issue for this on the spatie/image repo where the error originates.

**Comment by crslp** [comment]
> Class `Spatie\Image\GlideConversion` using `sys_get_temp_dir()` in method `createGlideServer` to define the `cache-path` which can trow an error on some shared hostings. I have tried to set the path via php.ini but this had no effect in my enviroment
> 
> Error Output: The root path /var/tmp/ is not readable.
> 
> Finally I have overriden `sys_get_temp_dir()` with `$_SERVER['DOCUMENT_ROOT']./temp` which works for me.
> 
> Before I have tried to set this path to the path provided in the config parameter `temporary_directory_path` which has trown a new error for me and because I was tired i just have set the above solution. Error was, that `League\Glide\Server::construct` exptects `FilesystemInterface` as second argument but `TemporaryDirectory` was given.

Thank you very much!
This worked for me on a shared hosting and should be considered for implementation.

**Comment by JonathanDoelan** [comment]
@atzen88 @crslp I’m having the same problem how did you override `sys_get_temp_dir()`? I’m afraid I am not able to do this within my system!?

**Comment by crslp** [comment]
Sorry for responding late @JonathanDoelan 
I solved this the dirty way by changing the above mentioned code in 
`vendor/spatie/image/src/GlideConversion.php`
to:
`public function __construct(string $inputImage)
    {
        $this->temporaryDirectory = $_SERVER['DOCUMENT_ROOT'].'temp/';

        $this->inputImage = $inputImage;
    }
`
@freekmurze I could provide a PR if you agree on this solution.

**Comment by JonathanDoelan** [comment]
@crslp @freekmurze I’ve already solved it by switching to a hosting provider that provides read access to the temp directory. That was my main problem.

After that I had the problem that this temp folder was deleted while using `spatie/image` … but this was solved with this PR: [https://github.com/spatie/image/pull/118](https://github.com/spatie/image/pull/118)

So it might be dangerous if `$this->temporaryDirectory` is not `sys_get_temp_dir()` — as far as I understand the code.

**Comment by andimg93** [comment]
Any news on that? 
`vendor/league/flysystem/src/Adapter/Local.php line 81 {"exception":"[object] (LogicException(code: 0): The root path /tmp is not readable. at ...`
Got also that problem...

**Comment by damarev** [comment]
I have the same problem on a shared hosting environment: sys_get_temp_dir() is not readable.

The posibility of changing the temporary_directory_path at config/media-library.php already exists, but it is not used by ImageFactory.php for generating image conversions.

So a dirty solution would be, first explicitly set the temporary directory path at config/media-library.php
```
'temporary_directory_path' => storage_path('media-library/temp'),
```

And then change this line at [ImageFactory.php](https://github.com/spatie/laravel-medialibrary/blob/master/src/Support/ImageFactory.php#L11), to:
```
return Image::load($path)->useImageDriver(config('media-library.image_driver'))
                         ->setTemporaryDirectory(config('media-library.temporary_directory_path'));
 ```

So, makes sense for the ImageFactory to use the temporary directory setted at the config? Would a PR to fix this would be accepted?

**Comment by MelchiorKokernoot** [comment]
This does seem to be a workaround indeed! Altough I am not a big fan of changing dependencies in my vendor directory. Has anyone been able to achieve the same without modifying vendor files?

**Comment by poldixd** [comment]
I had the same issue with my shared hoster [All-Inkl](https://all-inkl.com/). My solution is to overwrite the `ImageFactory.php` with my own `ImageFactory.php` with the `setTemporaryDirectory()`method posted by @damarev .

composer.json
```json
    "autoload": {
        "psr-4": {...},
        "exclude-from-classmap": [
            "vendor/spatie/laravel-medialibrary/src/Support/ImageFactory.php"
        ],
        "files": [
            "app/Overwrites/Spatie/MediaLibrary/Support/ImageFactory.php"
        ]
    },
```

app/Overwrites/Spatie/MediaLibrary/Support/ImageFactory.php (own ImageFactory.php with the original namespace)
```php
<?php

namespace Spatie\MediaLibrary\Support;

use Spatie\Image\Image;

class ImageFactory
{
    public static function load(string $path): Image
    {
        return Image::load($path)->useImageDriver(config('media-library.image_driver'))
            ->setTemporaryDirectory(config('media-library.temporary_directory_path'));
    }
}
```

Don't forget to run `composer dump-autoload`.
