### ISSUE TITLE
Register media conversion (cropping, png format)

### ISSUE THREAD

**Issue by jafar-albadarneh** [spatie/laravel-medialibrary#1295]
Is there a way to register a conversion that crops a png image and keep it in the same format after conversion. 
i tried this:
```php
$this->addMediaConversion('thumb')
         ->crop('crop-center', 500, 375)
         ->format('png')
```
but it did not work, conversions folder was not created, only original image was there, while when i removed the format option, the conversion went well using this:
```
$this->addMediaConversion('thumb')
            ->crop('crop-center', 500, 375)
```

Is there a way to get it to work?

**Comment by freekmurze** [comment]
Your code seems correct, so there's something wrong with the configuration.

Make sure your model implements the right interface and uses the right trait: https://docs.spatie.be/laravel-medialibrary/v7/converting-images/defining-conversions

**Comment by audetcameron** [comment]
can you try       CROP_CENTER  instead of crop-center .  per docs. 
The following $cropMethods are available through constants of the Manipulations class:
CROP_TOP_LEFT, CROP_TOP, CROP_TOP_RIGHT, CROP_LEFT, CROP_CENTER, CROP_RIGHT, CROP_BOTTOM_LEFT, CROP_BOTTOM, CROP_BOTTOM_RIGHT.

**Comment by syazany** [comment]
If anyone is having this problem, make sure you check your queue connection. Restart queue if not using sync.
