### ISSUE TITLE
Regenerating Images Question

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#1297]
What happens when regenerating images?

I ask because I'm upgrading Laravel and have just upgraded Media Library to 7.5.1 - I wasn't able to see my images on my development app (local) until I regenerated them.

I'm concerned about doing this on my production servers because they are small droplets and there are hundreds of images. Is there a way to just get the database updated so the images are visible? Or do the files themselves have to be re-rendered and uploaded to S3?

If they're re-rendered and uploaded, are the old files deleted first? Is there a chance the files will become lost during regeneration? I don't have my buckets backed up at this point - makes me nervous...

Edit: I have videos in the library too; what happens to them?

**Comment by freekmurze** [comment]
When using the command without options it with loop over media items, and replace all generated files.

To generate only the missing files and not touch the existing fiiles use `--only-missing`

https://github.com/spatie/laravel-medialibrary/blob/e1d8fe917eff9b4440978516d93bde65df8c2fea/src/Commands/RegenerateCommand.php#L19
