### ISSUE TITLE
mediallibrary conversions in queue fails when redis port different then standard

### ISSUE THREAD

**Issue by dracon** [spatie/laravel-medialibrary#1298]
Hi.
I use laradock installation on server. I have 2 different docker containers with same setup, but different ports exposed by redis.
When I use redis with port 6378 on th second docker instance processing images fails when queued.
When i use conversion nonQueued it works fine.
I couldn't find any config where medialibrary uses redis port 6379 for queueing.
What could be the problem that conversions are not working on different redis port?

**Comment by rjsworking** [comment]
Hi. Perhaps because it reads the config/databse.php configuration file?
Cheers

**Comment by freekmurze** [comment]
Closing this because this is probably related to laradock / docker config and not this package.
