### ISSUE TITLE
firstly crop image and then make responsive images

### ISSUE THREAD

**Issue by aghayeff** [spatie/laravel-medialibrary#1299]
Hi!

Is it possible firstly crop image and then make responsive images?

For example, an uploaded photo firstly will be cropped to 450x300. Then responsive images will be generated from cropped image (450x300).
Something like this:

`$model->addMedia($request->image)->fit('crop', 450, 300)->withResponsiveImages()->toMediaCollection();`

Of course I can register multiple Media Conversions. But, I think this way could be more sensible.

**Comment by fkeloks** [comment]
Hello,

I have the same problem.

My code:
```php
public function registerMediaConversions(Media $media = null) {
    $this->addMediaConversion('full-hd')
        ->fit(Manipulations::FIT_FILL, 1920, 1080)
        ->background('white')
        ->optimize()
        ->withResponsiveImages();
}
```

This conversion produces an image in 1920x1080px but the responsive versions are not generated correctly.

**Comment by zangab** [comment]
yes you can, but u need to send the data (cropping points) to the backend. You can use e.g. this cropper to get the desired data on the frontend to send it to your backend https://fengyuanchen.github.io/cropperjs/.

there you would do something like:
`$cropValues = $media ? $media->getCustomProperty('crop') : [];`
and perform cropping like:
`$thumb->manualCrop($cropValues['width'], $cropValues['height'], $cropValues['x'], $cropValues['y']);`
the `thumb` is a defined conversion on `images` like:
`        $thumb = $this
            ->addMediaConversion('thumb')
            ->width(100)
            ->height(100)
            ->optimize()
            ->nonQueued();`

**Comment by aghayeff** [comment]
> his conversion produces an image in 1920x1080px but the responsive versions are not generated correctly.

Exactly! Did you find a solution?
