### ISSUE TITLE
Move media directory to storage

### ISSUE THREAD

**Issue by welcoMattic** [spatie/laravel-medialibrary#13]
Hi!

Do you think it is possible to manage media directory, as move it to storage directory ?
It makes my life easier when I deploy with Envoyer.io.

Thanks ;)

**Comment by welcoMattic** [comment]
EDIT: I found a solution to my problem in Envoyer.io documentation :

```
Managing Uploaded Files

When storing user uploaded files, you should store them in the storage directory of your application if you are using Laravel. Then, you may use the "Manage Linked Folders" feature of Envoyer to create a symbolic link from your public directory to the storage directory. The "Manage Linked Folders" button can be fonud on the "Deployment Hooks" tab of your project.

If you are not using Laravel, you will essentially follow the same process. However, you will need to manually create a storage directory in the deployment path of your application (the same directory level as the current symbolic link).
```

**Comment by sebastiandedeyne** [comment]
Hi @welcoMattic 

Not really following, why can't you just create a symlink in the public folder like the Envoy docs recommend?

**Comment by welcoMattic** [comment]
Hi @sebastiandedeyne!

I tried it on Envoyer.io : it works.

But on my Homestead local stack it doesn't work... Laravel seems resolve the `public/media` symlink.

For instance, when I `var_dump(public_path().'/media');`, Laravel display `/home/vagrant/lafideleidee/storage/media/`.

Do you have any idea if it's a Laravel issue ?

**Comment by welcoMattic** [comment]
Hi @sebastiandedeyne!

As on Envoyer.io, on my Homestead local stack it doesn't work... Laravel seems resolve the `public/media` symlink.

For instance on my Homestead stack, when I `var_dump(public_path().'/media');`, Laravel display `/home/vagrant/myproject/storage/media/`.

Do you have any idea if it's a Laravel issue ?

**Comment by welcoMattic** [comment]
After hours of debugging, it looks like the real problem is in the `imageProfileURLs` generation.

Settings : `'publicPath' => public_path() . '/app/media',`

- If I call `getOriginal` method, it returns -> `/app/media/9/image.jpg`
- If I call 'getUrl('detail')' method, it returns -> `/home/vagrant/project/storage/app/media/9/4-11.jpg`

I'm trying to fix it, but if you can help me, it will be pretty cool ;)

**Comment by sebastiandedeyne** [comment]
This is probably since the package assumes that the url's are relative to the public directory. If this is'nt the case you're using a non-standard server configuration for laravel, what do your url's look like if you're linking to files outside of the public directory?

Here's the culprit, could get tricky to refactor though: https://github.com/spatie/laravel-medialibrary/blob/master/src/Models/Media.php#L44

**Comment by welcoMattic** [comment]
Yes, I understand, but `getOriginalUrl()` gives me the good url for my medias stored in storage dir. But not `getUrl('detail')` method.

Cf. my last EDIT (https://github.com/spatie/laravel-medialibrary/issues/13#issuecomment-114992701)

**Comment by sebastiandedeyne** [comment]
Hmm, misunderstood. Sounds like a bug indeed, I'll try to look into it tomorrow.

**Comment by welcoMattic** [comment]
Thanks a lot! I'll continue to try debug it. See you tomorrow.

(I'm in France, you?)

**Comment by freekmurze** [comment]
We are currently refactoring the package.  There will be breaking changes but the general principles will stay the same. We'll support media libraries that aren't stored in the public path.

**Comment by welcoMattic** [comment]
Ok, perfect ! I fix this issue in my own code for the moment.
Do have any idea for the ETA of next-gen version?

**Comment by freekmurze** [comment]
Don't hold me to it, but I guess somewhere late July.

**Comment by freekmurze** [comment]
The next-gen version is coming along quite nicely. We are still testing it internally but you can read the documentation and code here: https://github.com/spatie/laravel-medialibrary/tree/next-gen

In that version there is an easy way to generate your own urls: https://github.com/spatie/laravel-medialibrary/tree/next-gen#generating-custom-urls

**Comment by welcoMattic** [comment]
Thanks a lot! I'm going to read it today.

Keep going, ans thanks for your work :+1:

**Comment by freekmurze** [comment]
v2.0.0 has been tagged. In that version there is an easy way to generate your own urls: https://github.com/spatie/laravel-medialibrary/tree/master#generating-custom-urls

**Comment by welcoMattic** [comment]
@freekmurze Thank you very much! I'll test it this weekend. I'll give you my feedback soon ;)
