### ISSUE TITLE
A custom filename for conversions file

### ISSUE THREAD

**Issue by Mdpproduction** [spatie/laravel-medialibrary#130]
Hi all,
i'd like to know if if possibile to assign a custom filename for the conversions file. Myabe is already possible ?

**Comment by freekmurze** [comment]
No this isn't possible. Retrieving an url to a converted media item depends on the name of the file. 
There are currently no plans to assign a custom file name.

**Comment by Mdpproduction** [comment]
Ok, but for seo purpose, if i use, big, thumb or other, maybe i could be penalized. So in that case, the only way is to not use conversions

**Comment by divdax** [comment]
@freekmurze I'm in the same situation. If you know the path of one conversion e.g. ```media/{id}/conversion/thumb.jpg``` you can go thru all conversions by incrementing the id.

The next thing is when you are using S3 with Cloudfront. An updated conversion never will be delivered until the cache expired. :(

If i set a custom filename with ```uniqueid()``` (59c4f4e1643f2.jpg) why not generateing the conversions like this?

```
- 1 (mediaid)
-- 59c4f4e1643f2.jpg
-- conversions
--- 59c4f4e1643f2_large.jpg
--- 59c4f4e1643f2_thumb.jpg
```

**Comment by freekmurze** [comment]
I'd consider merging in a PR if it's simple, well documented and well tested.
