### ISSUE TITLE
getURl and getPath dont work

### ISSUE THREAD

**Issue by laravelcoder** [spatie/laravel-medialibrary#1300]
I have tried to use both getPath and getUrl and neither work and i get this error.

Method Illuminate\Database\Eloquent\Collection::getpath does not exist.

**Comment by nicolasbeauvais** [comment]
This means that you are trying to call the `getPath` method on a Collection instead of an eloquent model.

You should use the method on the model like this:
```php
$collection->each(function ($model) {
    $model->getPath()
});

// or 

$collection->first()->getPath();
```

**Comment by laravelcoder** [comment]
do i create a function for this or just add it to the existing functions in
my model?

something like this
public function getPath($model){
    $collection->each(function ($model) {
        $model->getPath()
    });
}

Another question do you have a way to reference each media item globally

say {{ $user->avatar->getUrl() }}
something i can use to pull the auth::user avatar in my sidebar that will
always be available not just when on profile page using avatar and user?

$clip->videos->each(function ($data) use ($request) {
    $data->addMedia($request['videos'][1]['video'])->preservingOriginal()->toMediaCollection('videos');
    Log::info("SAVED TO MEDIA");
});

on the above function

do i need to specify where the files are stored for
toMediaCollection('videos') or does it look at medialibrary.php and
determine that accordingly?

right now im uploading the file to /uploads/clips/  but i am having
problems adding the upload into the media collection for videos

any advice would be appreciated.


thank you

phillip
