### ISSUE TITLE
Responsive Images with Owl Carrousel

### ISSUE THREAD

**Issue by lostlian** [spatie/laravel-medialibrary#1308]
How can I Work with responsive images and Owl Carrousel? have you try it?

**The problem?**

Owl Carrousel sets the size of the image container to the size of the image. So when the responsive image just loads. It loads the smallest image and owl carrousel sets the size of the carrousel as the smallest image. 

So it never load the better quality image.

**Comment by freekmurze** [comment]
We don't use Own Carrousel, so can't help you with this.
