### ISSUE TITLE
Pdf attachments not uploaded in Laravel 5.5.*, MediaLibrary 6.6.7

### ISSUE THREAD

**Issue by Theodory** [spatie/laravel-medialibrary#1309]
Our Laravel Project was written in Laravel 5.5.* and we installed Spatie version 6.6.7 last year but this week users complained that they can't upload pdf attachment on live version they're receiving 500 Server error and I have tried locally in windows 10 I have got this error and I I have failed to upload any attachment

> exception: "ErrorException"
file: "D:\xampp\htdocs\niajiri\vendor\spatie\laravel-medialibrary\src\Filesystem\DefaultFilesystem.php"
line: 96
message: "touch(): Unable to create file D:\xampp\htdocs\niajiri\storage\medialibrary/temp\MLZzAC6ejzoakC8QPwMJgDeIm6NnHCIx\kNQFUweb6ddGwmfm. because Permission denied"
trace: [{function: "handleError", class: "Illuminate\Foundation\Bootstrap\HandleExceptions", type: "->"},…]
0: {function: "handleError", class: "Illuminate\Foundation\Bootstrap\HandleExceptions", type: "->"}
1: {,…}
2: {file: "D:\xampp\htdocs\niajiri\vendor\spatie\laravel-medialibrary\src\FileManipulator.php", line: 72,…}
3: {file: "D:\xampp\htdocs\niajiri\vendor\spatie\laravel-medialibrary\src\FileManipulator.php", line: 39,…}

**Comment by freekmurze** [comment]
This is probably related with imagick permissions: https://alexvanderbist.com/posts/2018/fixing-imagick-error-unauthorized
