### ISSUE TITLE
Utilizing the custom properties

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#131]
Id like to have the ability of assigning two strings to any of my images, that would something like the title and the subtitle.

Maybe I could utilize the custom image properties for this?

How would I store / add a custom property to a certain media?

**Comment by freekmurze** [comment]
Take a look [at the documentation regarding custom properties](http://medialibrary.spatie.be/v3/advanced-usage/adding-custom-properties/). There's also a `setCustomProperty`-method that I'll add to the documentation soon.

**Comment by kickthemooon** [comment]
hope im not asking too much.
Id like to add a custom property, 'title' and 'subtitle' but on an existing media record?

**Comment by freekmurze** [comment]
You can use [this function on media](https://github.com/spatie/laravel-medialibrary/blob/master/src/Media.php#L157)

```
$media->setCustomProperty('title', '...');
$media->setCustomProperty('subtitle', '...');
```

**Comment by kickthemooon** [comment]
dont know whats wrong...
```
public function imgDesc(Request $request, $imgid) {

        $image = Media::find($imgid);

        $title = $request->input('title');
        $desc = $request->input('desc');

        $image->setCustomProperty('title', $title);
        $image->setCustomProperty('subtitle', $desc);

        return redirect('/admin/gallery/1');

    }
``` 

Unfortunately this is not saving anything to the db, everything goes through, no error no nothing but its not saved in the db under custom_properties.

Any ideas?

**Comment by freekmurze** [comment]
Try adding $image->save(); before redirecting

>

**Comment by kickthemooon** [comment]
haha, works, thanks Freek.

**Comment by irfanDC** [comment]
Same thing i want to do as @kickthemooon did, but I am using "spatie/laravel-medialibrary": "7.0.0" Here is the my snippet 
 if ($request->hasFile('assets')) {
            foreach ($request->file('assets') as $key => $file) {
                $pagecontent->addMedia($file)
                ->withCustomProperties(['caption' => 'test caption'])
                ->toMediaCollection('assets');
            }
        }

**Comment by irfanDC** [comment]
It is working. Thanks for great work :)
