### ISSUE TITLE
Interface 'Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions' not found

### ISSUE THREAD

**Issue by guillermoprojaslema** [spatie/laravel-medialibrary#1310]
Hi everyone: I'm using this wonderful package. The v.7 with laravel 5.6.

I'd like to crop an image. According the documentation is something like this 

```use Spatie\MediaLibrary\Media;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
```

But when I refresh the project, this error appears

```Interface 'Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions' not found```

What coud be wrong? I'd really appreciate your help

**Comment by wiwa1978** [comment]
Have the same issue. The v7 documentation also does not help

**Comment by freekmurze** [comment]
I believe the docs on this are correct.

**Comment by rizalfakhri** [comment]
> looks like maybe you were looking at the v.6 documentation? The [v.7 documentation](https://docs.spatie.be/laravel-medialibrary/v7/converting-images/defining-conversions#) has
> 
> ```
> use Illuminate\Database\Eloquent\Model;
> use Spatie\MediaLibrary\Media;
> use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
> use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
> ```

The documentation URL is not found.
