### ISSUE TITLE
Thumb not displaying 

### ISSUE THREAD

**Issue by pianistprogrammer** [spatie/laravel-medialibrary#1312]
I have everything all set up and I see the url of the image if I inspect the image url `http://localhost/storage/1/conversions/Jeery-thumb.jpg` but this url is returning 404 on my browser when i navigate to this path. I then tried it with the port my laravel project was running on 8000 and then it showed localhost:`8000/storage/1/conversions/Jeery-thumb.jpg` How should this be handled ?

**Comment by yemilgr** [comment]
only thumb images are showing 404 or all images ???

**Comment by pianistprogrammer** [comment]
all images....

**Comment by yemilgr** [comment]
Have you tried php artisan storage:link ??
I think this will solve the problem

**Comment by pianistprogrammer** [comment]
did that already, I can see the storage folder in the public

**Comment by Wikiki** [comment]
Same here. Did php artisan storage:link to but no luck.

**Comment by carbontwelve** [comment]
@yemilgr 
I can reproduce this issue running my Laravel app via `php artisan serve`. This causes the app to serve for development on `http://localhost:8000`. This library's `getUrl` method on the `Media` model doesn't set the port number in the url for the environment being used and therefore returns a url without the port number.

**Comment by mateo2181** [comment]
Any solution for this? I have the same problem. I am saving my images in public disk and I have run php artisan storage:link. 
Code:
`$p = Paciente::find(1); ` 
`$mediaItems = $p->getMedia(); `
`$publicUrl = $mediaItems[0]->getUrl(); `
`echo "<img src='" . $publicUrl . "' \>";`

**Comment by moebaca** [comment]
@carbontwelve Thank you my friend! This did the trick.

**Comment by brendt** [comment]
Was horizon running to generate the images behind the scenes? 

I'll be closing this issue, if anyone comes up with a concrete error, feel free to drop a reply.

**Comment by vlad1301** [comment]
> @yemilgr
> I can reproduce this issue running my Laravel app via `php artisan serve`.
> 
> Having looked into this further I can see that the issue is caused due to the `filesystems.php` config in my Laravel install using `env('APP_URL').'/storage'` and my `APP_URL` in `.env` is set to `http://localhost`.
> 
> @pianistprogrammer
> The solution is to change your `APP_URL` value to `http://localhost:8000`

Thank you. It worked for me

**Comment by jayprakash554** [comment]
Please run this on cmd
php artisan storage:link 

this is solve my problem

**Comment by kolyacd** [comment]
![code](https://user-images.githubusercontent.com/1945207/122858446-e6674680-d2df-11eb-9d10-ab5b0c9361cf.png)
be aware of the storage_path as well as the url

**Comment by llantasypartes** [comment]
> @yemilgr I can reproduce this issue running my Laravel app via `php artisan serve`.
> 
> Having looked into this further I can see that the issue is caused due to the `filesystems.php` config in my Laravel install using `env('APP_URL').'/storage'` and my `APP_URL` in `.env` is set to `http://localhost`.
> 
> @pianistprogrammer The solution is to change your `APP_URL` value to `http://localhost:8000`

Thanks, It worked for me =)

**Comment by doncadavona** [comment]
[Conversions](https://spatie.be/docs/laravel-medialibrary/v9/converting-images/defining-conversions) are queued by default, perhaps the queue worker is not running or is outdated, causing unprocessed thumb conversions until the queue worker is updated and running.

Stop the current queue worker then re-run it:

`php artisan queue:work`

**Comment by vanthuonghcmue** [comment]
> @yemilgr I can reproduce this issue running my Laravel app via `php artisan serve`.
> 
> Having looked into this further I can see that the issue is caused due to the `filesystems.php` config in my Laravel install using `env('APP_URL').'/storage'` and my `APP_URL` in `.env` is set to `http://localhost`.
> 
> @pianistprogrammer The solution is to change your `APP_URL` value to `http://localhost:8000`

Thanks, it worked for me <3

**Comment by bijoy-xpeedstudio** [comment]
> [Conversions](https://spatie.be/docs/laravel-medialibrary/v9/converting-images/defining-conversions) are queued by default, perhaps the queue worker is not running or is outdated, causing unprocessed thumb conversions until the queue worker is updated and running.
> 
> Stop the current queue worker then re-run it:
> 
> `php artisan queue:work`

yes it's working for s3.
