### ISSUE TITLE
extractVideoFrameAtSecond Help 

### ISSUE THREAD

**Issue by laravelcoder** [spatie/laravel-medialibrary#1313]
I have a clip model which contains videos and images field that allows mulitple files.  this is working just fine but i need some help. 
http://nimb.ws/5EUwRs (working)

I have screenshots being created from a conversion that adds the screenshots to 
videos/{id}/conversions

i have the images also working and creating conversions and responsive images at 
images/{id}/conversions

Is there a way to get the images generated on the video conversion from ->extractVideoFrameAtSecond(5)  to the 
images/{id}/conversions instead of the videos/{id}/conversions
http://nimb.ws/2kUwXI

**Comment by laravelcoder** [comment]
anyone?

**Comment by laravelcoder** [comment]
almost a month still no reply, so helpful...

**Comment by freekmurze** [comment]
See reply on the other issue you posted.
