### ISSUE TITLE
extractVideoFrameAtSecond repetition

### ISSUE THREAD

**Issue by laravelcoder** [spatie/laravel-medialibrary#1314]
Is there a way to make ->extractVideoFrameAtSecond run every 5 seconds?

Is there a way to meke ->extractVideoFrameAtSecond extract a image 5 seconds before the end?

**Comment by laravelcoder** [comment]
## Any help getting this working would be great.  Anyone?

**Comment by laravelcoder** [comment]
almost a month still no reply, so helpful...

**Comment by freekmurze** [comment]
> almost a month still no reply, so helpful...

Please keep in mind that everybody here is voluntarily and nobody is required to send responses. 

The functionality you want is currently not available in the package, please send a well tested PR if you want this.
