### ISSUE TITLE
       NYeKFjWehzNXT   KPfLqnxJTyx               mMgj        UVwYkot         AzdYS          csv   zIFkXhZXO               gPiocAPHEGGbT      nvSUonYdr     

### ISSUE THREAD

**Issue by rativardhan** [spatie/laravel-medialibrary#1315]
HdsAmV

**Comment by ludo237** [comment]
Cool story bro

**Comment by olipiskandar** [comment]
im so sad :-(

**Comment by realripley00** [comment]
Have you tried just using JQuery?

**Comment by victoryforphil** [comment]
I had the same issue. Someone please help. I tried npm, yarn, pip, wget, carrier pigeon, nothing will work.

**Comment by victoryforphil** [comment]
Also can confirm smoke signals resolve in a 404 error

**Comment by algiuxass** [comment]
I have exact same issue. Anyone has solved it?

**Comment by malikshahzad228** [comment]
+1

**Comment by NicTorgersen** [comment]
This doesn't work for me. Any other tips?

**Comment by rativardhan** [comment]
Just try to run composer update command
