### ISSUE TITLE
the File does not exist, on save/update

### ISSUE THREAD

**Issue by tanthammar** [spatie/laravel-medialibrary#1317]
I'm using "dev-master" because I wasn't able to install v7 on Laravel v5.7+
I am also using [https://github.com/jameslkingsley/nova-media-library](url) so I'm not sure which package that generates these errors.

In nova, on new/edit resource. When adding or replacing a file I get this error when I try to save:
![image](https://user-images.githubusercontent.com/21239634/48966641-dbd45b80-efd5-11e8-874d-4e7b96cb634d.png)

I suppose this has something to do with creating a temporary folder for the file?

I found this in FileDoesNotExist.php.
```
class FileDoesNotExist extends FileCannotBeAdded
public static function create(string $path)
    {
        return new static("File `{$path}` does not exist");
    }
```

It is used in FileAdder.php
```
public function toMediaCollection(string $collectionName = 'default', string $diskName = ''): Media
    {
        if (! is_file($this->pathToFile)) {
            throw FileDoesNotExist::create($this->pathToFile);
        }
```
**Everything is saved to both db and storage as it should**,  but I am unable to save the resource in nova.
If i try to hit "update" again I get the following error.
![image](https://user-images.githubusercontent.com/21239634/48966656-27870500-efd6-11e8-9093-2f952ca80815.png)

I understand that you cannot support a 3rd party package but I just wanted to know if this relates to your package or the other.

**Comment by tanthammar** [comment]
Solved. w spatie media library v7.5.2

**Comment by krns** [comment]
We also face this issue.. using spatie/laravel-medialibrary 7.5.5

**Comment by IVNtech** [comment]
I got the same problem, I figure out that the HTML FORM tag must have this code
enctype="multipart/form-data"

This way the request will handle the submit with an img on it.

<form method="" action="" enctype="multipart/form-data">
</form>
