### ISSUE TITLE
Can I define multiple database table for different model?

### ISSUE THREAD

**Issue by json-wong** [spatie/laravel-medialibrary#1319]
For big data considerations, I want to set different tables for different models, such as:

*Category model has a CategoryMedia and category_medias table, 
*Product model has a ProductMedia and product_medias table, 
*ProductOption model has a ProductOptionMedia and product_option_medias table
...

Is there any way to implement it?

**Comment by gavinhewitt** [comment]
I have the same question but I guess this is not possible or not intended to use it this way

**Comment by freekmurze** [comment]
This is currently not possible. Feel free to fork our code and make the necessary changes in your own copy.
