### ISSUE TITLE
Queue conversions multi-tenant site

### ISSUE THREAD

**Issue by msassa** [spatie/laravel-medialibrary#1320]
I have a multi-tenant site and alredy make work the media package correctly, extending the media model and setting the correct db connection.
The problem is that each tenant have their own database and S3 bucket.
So, when I use the queue to make the conversions, that job doesn't know about the auth user, or the s3 disk setted in the middelware.
I was thinking I need to pass an extra parameter to the job when is dispatched, or something like that, but I wasn't be able to solve this.
Any idea?

**Comment by atapatel** [comment]
@msassa Are you using a separate queue for tenant database?

**Comment by msassa** [comment]
yes @atapatel , each tenant has their own queue

**Comment by atapatel** [comment]
@msassa ina config/medilibrary.php change 'queue_name' according to your tenant .

**Comment by msassa** [comment]
But the problem is not the queue name. The problem is the queue process doesn't know about the tenant who run the task, db connection, s3 configuration ... and all data relative to the tenant.

**Comment by atapatel** [comment]
@msassa Awwwww. Let me think about it.

**Comment by atapatel** [comment]
@msassa i guess you need to run the worker on bases of the tenant.

**Comment by msassa** [comment]
Sorry, how is that?

**Comment by msassa** [comment]
No, I make a middleware and a method that overwrite the 'tenant' connection. That work just fine.
