### ISSUE TITLE
Ghostscript 9.26 breaks pdf to image conversions

### ISSUE THREAD

**Issue by jlmmns** [spatie/laravel-medialibrary#1323]
SO thread: https://stackoverflow.com/questions/53560755/ghostscript-9-26-update-breaks-imagick-readimage-for-multipage-pdf

Possible workaround according to a reply is to set `setImageDepth` again after the image operations.

... or downgrade Ghostscript, I guess.
Although 9.26 was released because of major security issues.

---

Update:

It's worth noting that this issue is also pdf-dependent, as some pdf files do get converted.
Likely to do with the pdf/image depth (dpi?).

**Comment by JeremyRoundill** [comment]
I'm hitting the same issue.

It seems to be only with the ps:alpha delegate (which I suspect is the reason some PDFs get converted successfully, and some do not), and running the command manually and removing the `-dFirstPage=1` and `-dLastPage=1` options from the gs command seems to fix things; although I get a segfault when they're included, which could be an issue on my end.

**Comment by JeremyRoundill** [comment]
My solution was to downgrade back to 9.22 and 9.18 on my two different environments. The `dFirstPage` and `dLastPage` options seem to work fine with them. I might have to give 9.25 a go when I've next got a bit of time.

**Comment by freekmurze** [comment]
Is this something that can be fixed from within our package?

**Comment by JeremyRoundill** [comment]
I haven't read into the package well enough to work that out, but if you're able to remove the dFirstPage and dLastPage options, it might fix it.

**Comment by freekmurze** [comment]
Those options can't be set from this package. Closing issue this because the issue does not originate nor can't be fixed here.
