### ISSUE TITLE
Help wanted: Get full urls from collection without model

### ISSUE THREAD

**Issue by josegus** [spatie/laravel-medialibrary#1325]
How can I get an array of urls (full or partials) without getting the related Media model in an API?

I have a trait that gaves me an array of full urls, but i dont want to get the "media" key value pair in the response.

My api response looks like:

![image](https://user-images.githubusercontent.com/13947849/49457055-87dd2a00-f7c0-11e8-82c6-280adb95fa97.png)

Everytime i need the "imagenes" value i get the "media" array. I only want the "imagenes" value.

**Comment by fhusquinet** [comment]
Media is a relationship which is likely loaded on your API controller. You can always hide it from your response if you want using ->setHidden(['media']) for example or by using a resource response to format your data the way you want it:
https://laravel.com/docs/5.7/eloquent-resources#resource-responses
