### ISSUE TITLE
Lumen support ?

### ISSUE THREAD

**Issue by loranger** [spatie/laravel-medialibrary#133]
My apologies : I didn't even test, but I'd like to know if it's possible to use medialibrary with Lumen ?

Let's say I need an API supporting image upload and manipulations. 
I would like it lightweight so I took a look at Lumen, but I definitely need medialibrary.
What should I do ?

**Comment by freekmurze** [comment]
I haven't tested it out. I assume it wouldn't work out of the box. If have no need for Lumen support myself. If you need this, I'd glady accept a PR.
