### ISSUE TITLE
UrlGeneratorFactory tries to resolve S3 URL generator

### ISSUE THREAD

**Issue by dorvidas** [spatie/laravel-medialibrary#1330]
When trying use img() on model I get error (using S3 disk):
`Unresolvable dependency resolving [Parameter #0 [ "required" $app ]] in class Illuminate\Filesystem\FilesystemManager (View: /srv/www/api.jetcamp.com/current/web/vendor/spatie/laravel-medialibrary/resources/views/image.blade.php) in <b>/srv/www/api.jetcamp.com/current/web/vendor/spatie/laravel-medialibrary/src/Models/Media.php</b> on line <b>0</b><br />`

After doing some debuging I found:
UrlGeneratorFactory tries to resolve S3UrlGenerator:
https://github.com/spatie/laravel-medialibrary/blob/6e5e355ecb262875320904f57c06dbe332eb3d36/src/UrlGenerator/UrlGeneratorFactory.php#L19

S3UrlGenerator then tries to resolve dependencies $config and $filesystemManager https://github.com/spatie/laravel-medialibrary/blob/6e5e355ecb262875320904f57c06dbe332eb3d36/src/UrlGenerator/S3UrlGenerator.php#L14

Illuminate\Filesystem\FilesystemManager has $app dependency, but for some reason container does not pick it up

To overcome this I created a bind in AppServiceProvider:
`$this->app->bind('Spatie\MediaLibrary\UrlGenerator\S3UrlGenerator', function ($app) {
            return new \Spatie\MediaLibrary\UrlGenerator\S3UrlGenerator(
                $app->make('Illuminate\Contracts\Config\Repository'),
                new \Illuminate\Filesystem\FilesystemManager($app)
            );
        });`

**Comment by im-sunil** [comment]
![image](https://user-images.githubusercontent.com/6269292/51415111-ad6c9a00-1b9a-11e9-953b-d5883e89b24b.png)

I am facing same issue Laravel Lumen version 5.7.*

**Comment by kalpeshtank** [comment]
@dorvidas 
how I can use and resolve the S3 URL issue? can you please help me on it.

**Comment by patsa** [comment]
@im-sunil @kalpeshtank 
Have you tried the solution from https://www.cnblogs.com/qaing123/p/11048485.html ?

Just add the following lines to `bootstrap/app.php`:
```
$app->bind(\Illuminate\Filesystem\FilesystemManager::class, function ($app) {
    return new \Illuminate\Filesystem\FilesystemManager($app);
});
```

**Comment by kalpeshtank** [comment]
> @im-sunil @kalpeshtank
> Have you tried the solution from https://www.cnblogs.com/qaing123/p/11048485.html ?
> 
> Just add the following lines to `bootstrap/app.php`:
> 
> ```
> $app->bind(\Illuminate\Filesystem\FilesystemManager::class, function ($app) {
>     return new \Illuminate\Filesystem\FilesystemManager($app);
> });
> ```

Thank you so much, it's working fine
