### ISSUE TITLE
Delete Media ?

### ISSUE THREAD

**Issue by VConsulting** [spatie/laravel-medialibrary#1334]
Hello,
I can not find a feature to edit or delete a media, so every time an avatar change in the profile user a new media is added.
So we should remove old avatars become useless at the time of change, how to do?

**Comment by michaellindahl** [comment]
You can just call `->delete()` on the Media object. However it sounds like you'd like to use a [single file collection](https://docs.spatie.be/laravel-medialibrary/v7/working-with-media-collections/defining-media-collections#single-file-collections).

> If you want a collection to hold only one file you can use singleFile on the collection. A good use case for this would be an avatar collection on a User model. In most cases you'd want to have a user to only have one avatar.

**Comment by villananda** [comment]
https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/soft-deletes/

use `->forceDelete()`

**Comment by elshobokshy** [comment]
@michaellindahl I love you for mentioning the single file collections. I give you my salute, fellow developer.

**Comment by MineChamp2000** [comment]
> You can just call `->delete()` on the Media object. However it sounds like you'd like to use a [single file collection](https://docs.spatie.be/laravel-medialibrary/v7/working-with-media-collections/defining-media-collections#single-file-collections).
> 
> > If you want a collection to hold only one file you can use singleFile on the collection. A good use case for this would be an avatar collection on a User model. In most cases you'd want to have a user to only have one avatar.

if someone is looking for an updated link in the docs, here it is: [Link](https://spatie.be/docs/laravel-medialibrary/v10/working-with-media-collections/defining-media-collections#a-idcontent-single-file-collections-1-hrefcontent-single-file-collections-1-classanchor-link-aria-hiddentrue-titlepermalinkaa-idcontent-single-file-collections-hrefcontent-single-file-collections-classanchor-link-aria-hiddentrue-titlepermalinkasingle-file-collections)
