### ISSUE TITLE
Video upload ends up maxing CPU and fills drive with temp files when thumbnail is past video length

### ISSUE THREAD

**Issue by michaellindahl** [spatie/laravel-medialibrary#1335]
I'm not sure why this is happening. I've uploaded a few small 1-3 MB files and now the CPU has spiked and `storage/medialibrary/temp` is filling with temporary files. This will continue until the disk is full. Any ideas what might be happening and how to resolve this? I am using a redis queue and the public disk.

**Comment by michaellindahl** [comment]
Recreated the issue. Looks like when I upload a video, I get the following error:

`copy(…/storage/medialibrary/temp/bfxLU1GSwE6sTHQMptQA6CXhHJxDSnrZ/HiquUPwrz0vS2fLk.jpg): failed to open stream: No such file or directory`

This error is because the file exists at `HiquUPwrz0vS2fLk.MP4` but for some reason the file extension did not keep. The job never ends and it keeps attempting to complete the job, ballooning out the temp directory until the disk is full.

I only have one conversion on this file:

```
$this->addMediaConversion('thumbnail')->queued()
            ->width(250)
            ->height(250)
            ->extractVideoFrameAtSecond(20)
            ->performOnCollections('videos');
```

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.
