### ISSUE TITLE
Custom headers always added as a custom property

### ISSUE THREAD

**Issue by denitsa-cm** [spatie/laravel-medialibrary#1336]
`custom_headers` are always saved as `custom_properties`, even if not set. Is this for any particular reason? 

I always have `{"custom_headers": []}` present in the column.

**Comment by freekmurze** [comment]
Mmmm, that shouldn't happen, I'd accept a fully tested PR that fixes this.

**Comment by denitsa-cm** [comment]
@freekmurze I've made a pull request for this. First pull request to an open source repo - yay!

**Comment by freekmurze** [comment]
@denitsa-cm Thank you and congrats on your code being merged and released.
