### ISSUE TITLE
is it possible to use slug instead of id for directory

### ISSUE THREAD

**Issue by laravelcoder** [spatie/laravel-medialibrary#1355]
can you tell me where i can adjust this so i can use the slug of the name instead of the id of the media item please?

**Comment by VincentKos** [comment]
yes it is, look here : https://github.com/spatie/laravel-medialibrary/blob/7.0.0/tests/Unit/PathGenerator/CustomPathGenerator.php

Looks like you need to implement this interface https://github.com/spatie/laravel-medialibrary/blob/master/src/PathGenerator/PathGenerator.php and then you can do whatever you want
