### ISSUE TITLE
shared host version

### ISSUE THREAD

**Issue by mohammad6006** [spatie/laravel-medialibrary#1359]
the code that I write to upload media works on local host

but after uploaded to shared host it return: 
`Argument 1 passed to Spatie\MediaLibrary\Helpers\File::getHumanReadableSize() must be of the type integer, null given, called in /home/..../vendor/spatie/laravel-medialibrary/src/Exceptions/FileCannotBeAdded/FileIsTooBig.php on line 14
`
and I dont have ssh access to install composer and integrated version of media library

php versions are same 7.2

is the way that I know what is the problem and which version should I upload to shared host?

**Comment by carbontwelve** [comment]
@mohammad6006 The fact that `FileIsTooBig.php` is being executed tells me the file being uploaded was too big for the file upload limit imposed by your shared hosting.

Line 14 of that file in 7.5 reads `$maxFileSize = File::getHumanReadableSize(config('medialibrary.max_file_size'));` With `medialibrary.max_file_size` returning `1024 * 1024 * 10`.

Have you modified that configuration value? It being `null` shouldn't happen.

**Comment by mohammad6006** [comment]
i didn't upload configuration file, but I upload it and solved the problem.

I think its a bug
