### ISSUE TITLE
orientation, not working as expected

### ISSUE THREAD

**Issue by Livijn** [spatie/laravel-medialibrary#1364]
I am trying to *rotate/orientate* [this picture](http://www.ashfordmanorlabradoodles.com/wp-content/uploads/2012/02/Lady-now-Maggie.jpg), but I am seeing strange results.

This is how I manipulate the image:

    $media = $this->addMedia($image)
            ->usingFileName(str_random(32) . '.' . $extension)
            ->withManipulations(['*' => ['orientation' => $orientation]])
            ->toMediaCollection($this->mediaCollectionName);

The image is uploaded, processed and I have verified that in the database it has saved the manipulation:  `{"*": {"orientation": "270"}}`.

However, using *270* or *90* is not rotating the picture at all. Using *180* actually rotates the image, but the image being already landscaped, it is an unwanted rotation.

I am saving the images to AWS S3 if that is relevant.

**Comment by tudorradubarbu** [comment]
Same here (but did you tried a php artisan queue:work?)

**Comment by brendt** [comment]
Is this still an issue for you? I can look into it if it is.

**Comment by Livijn** [comment]
It's still an issue, but it is not an issue for me anymore. If you get my point 😊 You can feel free to close this or try uploading that image yourself.
