### ISSUE TITLE
[Question/Advice] Storing "Pending" media

### ISSUE THREAD

**Issue by vpratfr** [spatie/laravel-medialibrary#1370]
Hi,

We have a domain object which contains user data. From that data, we generate a set of different [PDF, Word, Excel] documents. Those documents are generated on queues and their corresponding job may take several minutes to complete.

We would like to store the output documents as `Media` and link them to the domain object. Of course, while jobs are running, we want to show that status to the user.

In your API, you have functions to add media from existing file/stream/etc.

However, in our case, media file is not yet available.

Current solution I was thinking about:

- Create a Media object which has no info about the file/disk/etc.
- Store the job status as custom property + some info about it
- Once job is complete, replace the "placeholder" media object with the real file + run eventual convertions on that one

Did you already have to handle such a case? Any thought about the most elegant solution?

**Comment by Gummibeer** [comment]
I have a similar requirement because the upload to Azure Blob Storage is pretty slow. The whole upload request (~100mb file) takes around 1-2min because of the slow upload to azure. If I could do the upload, like all conversions, from a queue t would be awesome.

**Comment by freezer278** [comment]
I have same issue, can this be fixed?
