### ISSUE TITLE
Update the parent model, using Scout and Algolia

### ISSUE THREAD

**Issue by msassa** [spatie/laravel-medialibrary#1374]
I can't find a way to update the parent model (in order to update the index in Algolia) when a media is saved, or deleted.
I tryed with events, but doesn't feel right. And doesn't work even.

```
protected $listen = [
    'Spatie\MediaLibrary\Events\ConversionHasBeenCompleted' => [
            'App\Listeners\UpdateAlgoliaModelWhenConversionHasFinish'
    ],
];
```

```
class UpdateAlgoliaModelWhenConversionHasFinish
{
    public function handle($event)
    {
        if (method_exists($event->media->model, 'searchable')) {
            $event->media->model->searchable();
        }
    }
}
```

Any other idea how to reach this?

**Comment by eminos** [comment]
I'm having the same issue and wondering the same thing...

**Comment by eminos** [comment]
`$model->save();` to trigger the Algolia update, after adding the images, did the trick.

**Comment by msassa** [comment]
I will try it, thanks!
