### ISSUE TITLE
how to apply spatie media library on every page with already uploaded images 

### ISSUE THREAD

**Issue by haseeb-catalyst** [spatie/laravel-medialibrary#1383]

**Comment by atymic** [comment]
Can you provide some more information on your issue and the code you are using please?

**Comment by brendt** [comment]
My suggestion would be to read the documentation on how to add files as media: https://docs.spatie.be/laravel-medialibrary/v7/api/adding-files/#adding-files

You'd need to write some kind of command to convert your specific project
