### ISSUE TITLE
Doesn't work with STI(Single Table Inheritance) models

### ISSUE THREAD

**Issue by webappbuilder** [spatie/laravel-medialibrary#1385]
I use https://github.com/tightenco/parental package for STI models. For ex., i have App\Models\Content\Header model which extends App\Models\Content\Content basic one. I try attach file to Header  model. While processing upload i get message: Call to undefined method App\Models\Content\Content::registerAllMediaConversions(). But i deal with Header model, not STI parent one(e.g. Content).

**Comment by ultrono** [comment]
Yep, I get this too when using Horizon and Laravel 5.8. The original image uploads fine, but my queued conversions fail with the exact message you mention. After restarting horizon everything works fine.

**Comment by brendt** [comment]
I'm closing this issue because of the answer in #1333
