### ISSUE TITLE
dropzone, and associating with a particular model_id

### ISSUE THREAD

**Issue by trevorpan** [spatie/laravel-medialibrary#1387]
I'd like to associate media to a job_id. e.g. a user posts a job, with pics and files only related to that job. A user bids on that job.

How would you concurrently create a job, and upload files at the same time with one upload button?

edit: 
here's a post I found that solves this. However, it does not use the folder structure shown in this video for each record. Is this something you might implement in MediaLibrary?

https://www.youtube.com/watch?v=Ho9OVdxpFRM&feature=youtu.be

https://laraveldaily.com/multiple-file-upload-with-dropzone-js-and-laravel-medialibrary-package/#comment-91509

**Comment by Gummibeer** [comment]
@trevorpan if you use https://www.dropzonejs.com/ you can append form data to the file upload request.

```js
 $form.dropzone({
    addedfile: function (dzFile) {
        dzFile.mediaState = $('#media-state').val();
    },
    sending: function (dzFile, xhr, formData) {
        formData.append('state', dzFile.mediaState);
    },
});
```

```php
$job = new Job([
    'state' => $request->get('state'),
]);

$job->addMedia($request->file('file'));
$job->save();
```

**Comment by trevorpan** [comment]
Is it really that simple? 

Would this create 3 jobs if a person uploaded 3 files?

This is how I've currently got the create.blade setup:
`
@extends ('layouts.master')


@section ('content')


<div class="postjob">

 	<div class="postjobheading">
 		<h1>Post a job with BidBird!</h1>
 	</div>

	<div class="postjobdetails">
	
	<form method="POST" action="/jobs" enctype="multipart/form-data">
			@csrf
			<fieldset>

		  	<div class="form-group">
		  		<label for="jobtitle">Job Name:</label>
		  		<input type="text" class="form-control" name="jobtitle" id="jobtitle" placeholder="Enter Your Job Name ~" value="{{ old('jobtitle') }}" required>
		  	</div>

		  	<div class="form-group">
		  		<label for="bodytext">Body:</label>
		  		<textarea name="body" class="textarea" name="body" placeholder="Enter Job Description ~" value="{{ old('bodytext') }}" required></textarea>
		  	</div>

		  	<div class="form-group">
		  		<label for="projectaddress">Project address (only shown to winning bidder):</label>
		  		<input type="text" class="form-control" name="projectaddress" id="projectaddress" placeholder="Project address" value="{{ old('projectaddress') }}" required>
		  	</div>

		  	<div class="form-group">
		  		<label for="city">City:</label>
		  		<select class="form-control" name="city" id="" value="{{ old('city') }}" required> 
		  			<option value="phoenix">Phoenix</option>
		  		</select>
		  	</div>

		  	<div class="form-group">
		  		<label for="state">State:</label>
		  		<select class="form-control" name="state" id="" value="{{ old('state') }}" required> 
		  			<option value="arizona">Arizona</option>
		  		</select>
		  	</div>

		  	<div class="form-group">
		  		<label for="bodytext">Zip Code:</label>
		  		<input type="text" class="form-control" name="zipcode" id="zipcode" placeholder="Zip Code" value="{{ old('zipcode') }}" required>
		  	</div>

		  	<div class="form-group">
		  		<label for="biddertype">Who bids this job?:</label>
		  		<select class="form-control" name="biddertype" id="" required> 
		  			<option value="generalcontractor">General Contractor</option>
		  			<option value="subcontractor">Sub Contractor</option>
		  			<option value="materialssupplier">Materials Supplier</option>
		  		</select>
		  	</div>

		  	<div class="form-group">
		  		<label for="job">What is this job?:</label>
		  		<select class="form-control" name="job" id="" required> 

		  			<option value="materials">Materials</option>
		  		</select>
		  	</div>

		  	<div class="form-group">
		  		<label for="subjob">What is this sub-job?:</label>
		  		<select class="form-control" name="subjob" id="" required> 
		  			
	  			        <option value="concrete">Concrete</option>
	  			        <option value="lumber">Lumber</option>
                     	<option value="steel">Steel</option>
                        <option value="plumbing">Plumbing</option>
                        <option value="electrical">Electrical</option>
                        <option value="mechanical">Mechanical</option>
                        <option value="flooring">Flooring</option>
                        <option value="interiors">Interiors</option>
                      	<option value="roofing">Roofing</option>
                        <option value="landscape">Landscape</option>
		  		</select>
		  	</div>


		  	<div class="form-group">
		  		<label for="deadline">Bid Deadline is based on your estimated project value (be honest).</label>
		  		<select class="form-control" name="deadline" id="" required> 
		  			<option value="1">Up to $999 (1 week bidding allowance)</option>
		  			<option value="1">Between $1,000 and $9,999 (1 week bidding allowance)</option>
		  			<option value="2">Between $10,000 and $24,999 (2 week bidding allowance)</option>
		  			<option value="2">Between $25,000 and $49,999 (2 week bidding allowance)</option>
		  			<option value="3">Between $50,000 and $74,999 (3 week bidding allowance)</option>
		  			<option value="3">Between $75,000 and $124,999 (3 week bidding allowance)</option>
		  			<option value="3">Between $125,000 and $249,999 (3 week bidding allowance)</option>
		  			<option value="4">Between $250,000 and $499,999 (4 week bidding allowance)</option>
		  			<option value="4">Between $500,000 and $749,999 (4 week bidding allowance)</option>
		  			<option value="4">Between $750,000 and $999,999 (4 week bidding allowance)</option>
		  		</select>
		  	</div>
	
		 <div class="mediadropzone">
		        <label for="document">Documents</label>
		        <div class="needsclick dropzone" id="document-dropzone">

		        </div>
		</div>
	
	
	</fieldset>

				<div class="postjobsubmit">
				  	<button type="submit" class="btn btn-primary">Post job!</button>
				</div>
			
		</form>
	</div>

 
			@include ('layouts.errors')

</div>


@endsection

@section('scripts')
<script>
  var uploadedDocumentMap = {}
  Dropzone.options.documentDropzone = {
    url: '{{ route('jobs.storeMedia') }}',
    maxFilesize: 15, // MB
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    success: function (file, response) {
      $('form').append('<input type="hidden" name="document[]" value="' + response.name + '">')
      uploadedDocumentMap[file.name] = response.name
    },
    removedfile: function (file) {
      file.previewElement.remove()
      var name = ''
      if (typeof file.file_name !== 'undefined') {
        name = file.file_name
      } else {
        name = uploadedDocumentMap[file.name]
      }
      $('form').find('input[name="document[]"][value="' + name + '"]').remove()
    },
    init: function () {
      @if(isset($job) && $job->document)
        var files =
          {!! json_encode($job->document) !!}
        for (var i in files) {
          var file = files[i]
          this.options.addedfile.call(this, file)
          file.previewElement.classList.add('dz-complete')
          $('form').append('<input type="hidden" name="document[]" value="' + file.file_name + '">')
        }
      @endif
    }
  }
</script>
@stop
`

**Comment by trevorpan** [comment]
Is it really that simple?

Below is my go at using the above mentioned tutorial. Will this approach create (3) jobs if a user uploads (3) files?
`@extends ('layouts.master')


@section ('content')


<div class="postjob">

 	<div class="postjobheading">
 		<h1>Post a job with BidBird!</h1>
 	</div>

	<div class="postjobdetails">
	
	<form method="POST" action="/jobs" enctype="multipart/form-data">
			@csrf
			<fieldset>

                         form stuff...
		  	

		            <div class="mediadropzone">
		                <label for="document">Documents</label>
		            <div class="needsclick dropzone" id="document-dropzone">

		            </div>
		        </div>
	
	            </fieldset>

				<div class="postjobsubmit">
				  	<button type="submit" class="btn btn-primary">Post job!</button>
				</div>
			
		</form>
	</div>

 
			@include ('layouts.errors')
</div>

@endsection

@section('scripts')

<script>
  var uploadedDocumentMap = {}
  Dropzone.options.documentDropzone = {
    url: '{{ route('jobs.storeMedia') }}',
    maxFilesize: 15, // MB
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    success: function (file, response) {
      $('form').append('<input type="hidden" name="document[]" value="' + response.name + '">')
      uploadedDocumentMap[file.name] = response.name
    },
    removedfile: function (file) {
      file.previewElement.remove()
      var name = ''
      if (typeof file.file_name !== 'undefined') {
        name = file.file_name
      } else {
        name = uploadedDocumentMap[file.name]
      }
      $('form').find('input[name="document[]"][value="' + name + '"]').remove()
    },
    init: function () {
      @if(isset($job) && $job->document)
        var files =
          {!! json_encode($job->document) !!}
        for (var i in files) {
          var file = files[i]
          this.options.addedfile.call(this, file)
          file.previewElement.classList.add('dz-complete')
          $('form').append('<input type="hidden" name="document[]" value="' + file.file_name + '">')
        }
      @endif
    }
  }
</script>
@stop`

**Comment by Gummibeer** [comment]
My example will create 3 jobs. If you want to prevent this just pass a `job_id` key-value in the form and use it. In PHP you could also check if this `job_id` is present and if not create a job.

The `addedfile` and `sending` are default callbacks from dropzone. It offers a lot more - depending on your needs you can use them to send whatever you want to your controller.

**Comment by trevorpan** [comment]
ok, new at this. I'll give it a shot and get back. Thank you!
