### ISSUE TITLE
Append url by default when getting media

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-medialibrary#139]
Is it possible to append the URL or PATH instantly whenever you call $model->getMedia() ?

**Comment by freekmurze** [comment]
I'm not sure what you're asking. Could you give a more concrete code example of what you want?

You can get an url to a media object with `$media->getUrl()`, path: `$media->getPath()`.

**Comment by Cannonb4ll** [comment]
Well, like this:

I have a model item, which has multiple media items.

Whenever I do like: $model->getMedia() it returns 2 items, from out the database, but I want to have the URL aswell in that collection instantly, I do not want to have to do like: $model->getMedia()[0]->getUrl();

I would like to see that the URL is appended automatically to the collection you ask withing $model->getMedia() (even though theres multiple items in that collection)

Can I accomplish this with a custom media model?

**Comment by Cannonb4ll** [comment]
Fixed it by doing following:

    protected $appends = [
        'url'
    ];

    public function getUrlAttribute()
    {
        return $this->getUrl();
    }

**Comment by freekmurze** [comment]
:+1:
