### ISSUE TITLE
Files are not deleted from the disk in case of dynamic overwrite configuration

### ISSUE THREAD

**Issue by petrzavicak** [spatie/laravel-medialibrary#1392]
I spent 6 hours searching for the cause of the following case:

Within my own package that uses the Spatie Laravel media package, I overwrite several configurations within the Service Provider.

// MyPackageServiceProvider.php
$ this-> app ['config'] -> set ('medialibrary.media_model', \ Zavicak \ MyPackage \ App \ Models \ Media :: class);

Everything works correctly, but unfortunately there are no files to be deleted from the disk (both in the case of removing the media or removing the whole model).

If I copy the medialibrary.php configuration file into the config directory in the project and define my own model here, then everything is done correctly, including removing files from the disk. However, this behavior is wrong, I need to overwrite the configuration without affecting the user's medialibrary.php configuration file.

**Comment by intrepidws** [comment]
@petrzavicak I'm having this same problem though a bit more simplistic. In my case, I'm simply using the package but have defined a custom model via the `media_model` config item. This results in no media being deleted from the actual disk. Did you come up with a solution?

**Comment by shaneoliver** [comment]
I also have this issue when using a custom model. All other model observers are working (creating, updating, updated) except for the deleted observer. Calling $media->delete(); removes the row from the database, but doesn't remove the file from the directory.

To reproduce, create a mode that extends Media https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-your-own-model#using-your-own-model add, then delete the media.

**Comment by brendt** [comment]
Has anyone encountering this issue looked at it in depth as to why it's happening? Any suggestions on how to fix it? We're open for PRs.

**Comment by freekmurze** [comment]
If you are dynamically changing the media model you should manually register a `MediaObserver` for it that'll delete the files.

```
$mediaClass = config('medialibrary.media_model');

$mediaClass::observe(new MediaObserver());
```

**Comment by intrepidws** [comment]
@freekmurze Where would this be done? In AppServiceProvider.php?

**Comment by intrepidws** [comment]
Perhaps I'm doing this wrong, but Freek's suggested solution (https://github.com/spatie/laravel-medialibrary/issues/1392#issuecomment-514007770) did not work for me. I put the recommended code into my AppServiceProvider and was able to confirm that the `creating()` method from that Observer fires just fine, but the `deleted()` method does not. I also tested `deleting()`, even though it doesn't appear in the default Observer - which also does not fire.

The only solution that worked for me was to change my `use` statement to reference my custom model rather than `use Spatie\MediaLibrary\Media;`. Even that solution doesn't always work (it errors out with things like conversions), it really only works when all I am doing is deleting the media item specifically.

**Comment by freekmurze** [comment]
@intrepidws you should do this anywhere after you've dynamically changed the `medialibrary.media_model` config.

**Comment by argonzalez2016** [comment]
> I also have this issue when using a custom model. All other model observers are working (creating, updating, updated) except for the deleted observer. Calling $media->delete(); removes the row from the database, but doesn't remove the file from the directory.
> 
> To reproduce, create a mode that extends Media https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-your-own-model#using-your-own-model add, then delete the media.

Did you figure out a fix to this issue? I am currently experiencing this.
