### ISSUE TITLE
I already have a media() relationship, any ideas?

### ISSUE THREAD

**Issue by MattWohler** [spatie/laravel-medialibrary#1394]
Our business already uses a "Media" table / Eloquent Model as part of its business requirement.  MediaLibrary does comes with a config option to point to a new Model which is great, however there is a conflicting trait method, titled: `media()`.

The most obvious answer is to rename all the Eloquent model relationship methods. However in order not deviate from the business layer, does anyone have any other creative ideas on how I can solve this?

**Comment by mojowill** [comment]
Sorry for posting on an old thread, how did you solve this. We are facing a similar issue when creating our own model we can't override the media relationship.
