### ISSUE TITLE
Media Conversion Error

### ISSUE THREAD

**Issue by aapnatech** [spatie/laravel-medialibrary#1396]
Socket error 10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
↵ (connecting to localhost:11300)

**i am getting above erroe when i am try to impliment media conversion.**

**Comment by yashdhol** [comment]
also i am getting this error is there any solution?

**Comment by brendt** [comment]
This error happens because the server takes too long to respond. You probably want to use queues to generate images because generating them all in the same request takes too much time: https://docs.spatie.be/laravel-medialibrary/v7/converting-images/defining-conversions/#queuing-conversions
