### ISSUE TITLE
Clean up conversions

### ISSUE THREAD

**Issue by divdax** [spatie/laravel-medialibrary#1403]
Let's say i've defined two conversions, uploaded many files with this two conversions and after that i remove one conversion. To also clean up the storage it would be handy if we can delete undefined conversions with a new option for `medialibrary:clean --delete-undefined`.

What do you think? Is a PR welcome for this feature?

**Comment by riasvdv** [comment]
Deprecated conversions are already removed with the `clean` command. https://github.com/spatie/laravel-medialibrary/blob/master/tests/Feature/Commands/CleanCommandTest/CleanConversionsTest.php#L51
