### ISSUE TITLE
Media Regenerate command not working on ubuntu server 

### ISSUE THREAD

**Issue by MoinGandhi** [spatie/laravel-medialibrary#1404]
I want to generate conversation for an uploaded image. So, I have written below code.

`<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;

class TestCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'test:command';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
//        exec('php artisan medialibrary:regenerate --ids='.$this->mediaId)
         Artisan::call('medialibrary:regenerate', [
            '--ids' => $this->mediaId
        ]);
    }
}
`
Also, tried with php exec() function but it does not work on ubuntu server. It works fine in locally with exec() function.

I also tried other Laravel artisan commands, but it works on ubuntu server as well as locally. 

The only issue with php artisan medialibrary:regenerate command. Please let me know what's the issue. TIA.

**Comment by delenamalan** [comment]
Try adding `'--force' => true` to the array of arguments.  I.e. make it 
```
Artisan::call('medialibrary:regenerate', [
'--ids' => $this->mediaId, 'force' => true,
]);
```

**Comment by MoinGandhi** [comment]
Hello, @delenamalan, Thanks for the reply but force argument not working it says 

> The "force" argument does not exist.
![screen shot 2019-03-06 at 10 50 38 am](https://user-images.githubusercontent.com/34887731/53858074-a391df80-3ffe-11e9-9ad7-739865e13da8.png)

**Comment by MoinGandhi** [comment]
Hello @delenamalan, Now, it works. Thank you so much for your valuable reply. It works with --force => true

**Comment by delenamalan** [comment]
Cool, glad I could help :smile:
