### ISSUE TITLE
Add multiple media from request doesn't works with Lumen 5.7

### ISSUE THREAD

**Issue by mdeprezzo** [spatie/laravel-medialibrary#1407]
Good afternoon,
i'm facing a problem with lumen and the method "addMultipleMediaFromRequest".

The point is, if i use this method i get this message:

```
he current request does not have a file in a key named ...
```

instead the method "addMediaFromRequest" works fine. I've added all configuration for lumen, but someone can tell me if i'm missing something ?

I'm using the 7.0.0 version, and i've an array of files

**Comment by brendt** [comment]
We've recently merged a PR, which will probably solve your issue: https://github.com/spatie/laravel-medialibrary/pull/1471
