### ISSUE TITLE
Querstion : Generate Thumbnail  for existing Spatie Media.

### ISSUE THREAD

**Issue by atapatel** [spatie/laravel-medialibrary#1408]
Hello, 
i have add new media converstions for my model. How can i regenerate new converstion for old record?

**Comment by Aryan1** [comment]
You should always go through the documentation first, Your problem already has a solution here [https://docs.spatie.be/laravel-medialibrary/v7/converting-images/regenerating-images#regenerating-images](https://docs.spatie.be/laravel-medialibrary/v7/converting-images/regenerating-images#regenerating-images).

**Comment by atapatel** [comment]
@Aryan1 i have gone through docuements but above mentioned command is not working for me. 
p.s - it is not genertating images as well not saving in custom_properties.

**Comment by atapatel** [comment]
@Aryan1 Got it. My bad, got the solutions. it was in redis job.
