### ISSUE TITLE
Laravel - Publish Vendor Class Spatie\MediaLibrary\Models\Media in Spatie to configure it with MongoDB

### ISSUE THREAD

**Issue by rameezte** [spatie/laravel-medialibrary#1409]
here i have a Media class at Spatie\MediaLibrary\Models\Media path. it was creating PDO issues with this code.

`class Media extends Model implements Responsable, Htmlable
`so i tried this in there and it worked for the cause.

```
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
class Media extends Eloquent implements Responsable, Htmlable
```

now its fine as long its working but what about updating composer will remove everything i guess and PDO problem will appear again. so how can i publish it out there to make it permanent?

**Comment by PepijnDeWachter** [comment]
https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-your-own-model
this should help :)
