### ISSUE TITLE
Problem with valid extensions array at Conversion class

### ISSUE THREAD

**Issue by Chema-TM** [spatie/laravel-medialibrary#1411]
At _Spatie\MediaLibrary\Conversion_ in the **getResultExtension** method there is a comparison when you have `keepOriginalImageFormat = true` to get the `originalFileExtension`.

The problem is that some software saves the images with `.jpeg` extension which is not in the valid array `['jpg', 'pjpg', 'png', 'gif']`. The result is that the thumb conversion (for example) isn't with the original extension (jpg per default) and this is problem for custom tools that works with the media data, because if you want to manually generate an image path to the thumb, the file extension is not the expected.

For example, I've got a Custom Media Resource in Nova wich attach Spatie Media information stored in a database, and when I want to show a small preview of the media, I found that the extension is not as espected.

Technically there is no difference between `jpg` and `jpeg` files, and is easy to me change the extension, but for customers is not very effective.

Can you add support for jpeg files please? Or add the posibility to customize it.

Thanks a lot

**Comment by brendt** [comment]
This has been fixed in 7.6.5: https://github.com/spatie/laravel-medialibrary/releases/tag/7.6.5
