### ISSUE TITLE
Image not uploading and no row added in database

### ISSUE THREAD

**Issue by mannanzinat** [spatie/laravel-medialibrary#1414]
here is the controller: http://prntscr.com/n5z3bu
Dump: http://prntscr.com/n5z3pe
Model: http://prntscr.com/n5z3y1

**Comment by jannejava** [comment]
Look over the paths for the uploaded file in your controller. Maybe try using addMediaFromRequest().

**Comment by steffex** [comment]
Did you use multpart/form-data?

**Comment by simplenotezy** [comment]
I experience the same issue:

    /**
     * Assign avatar
     */
    
      if ($request->get('avatar')) {
          $person->addMediaFromRequest('avatar')->toMediaCollection('avatars');
      }

I know for a fact that the line is being run, as before when I forgot to add the `multipart/form-data` I recived the error: `The current request does not have a file in a key named `avatar``. Now I have added multipart, the request now succeeds, but no image is uploaded to database, and no error given either.

**Comment by simplenotezy** [comment]
I solved the issue changing ` if ($request->get('avatar')) {` to `if ($request->has('avatar')) {`. So I was a bit too fast, after changing form to multipart, `$request->get('avatar')` would not return true, however `$request->has('avatar')` does.

**Comment by riasvdv** [comment]
Please refer to the Laravel docs https://laravel.com/docs/master/requests#files

For files you need to use `$request->hasFile('avatar')` or `$request->file('avatar')` to get file info.
