### ISSUE TITLE
SVG not generating image conversions

### ISSUE THREAD

**Issue by matthewsuan** [spatie/laravel-medialibrary#1417]
I have Imagick installed on Forge with PHP7.2

Also, I use `'image_driver' => 'imagick'`

Here is my image conversion registration.

```
        $this
            ->addMediaConversion('thumb')
            ->fit(Manipulations::FIT_CROP, 244, 203)
            ->sharpen(10)
            ;
```

Now, when calling `$model->getFirstMediaUrl('featured', 'thumb')` on an svg uploaded file, it returns a url to its `png|jpg` converted file but its 404. Upon checking, the converted file is not on the server.

I may have missed something?

Ty

**Comment by brendt** [comment]
Here are some steps to troubleshoot:

- Are other conversions working correctly? 
- Are conversions performed as a queued job? Is Horizon running?

**Comment by matthewsuan** [comment]
I can confirm some conversions are working correctly. Only svg uploads are having this issue.

Conversions are performed on a queued job.

**Comment by brendt** [comment]
I'd suggest to debug, starting from the conversion class: https://github.com/spatie/laravel-medialibrary/blob/master/src/Conversion/Conversion.php#L104

**Comment by brendt** [comment]
I'll be closing this issue, as there doesn't seem to be any response. If anyone is experiencing the same issue, feel free to ping me and we'll take a look at it.

**Comment by verybigelephants** [comment]
i have encounered the same issue and in my case it was a problem that imagemagick plugin did not have "svg" (and other vector formats) support installed. check your `ImageMagick supported formats` for `imagick` plugin in `phpinfo()`

**Comment by Yiddishe-Kop** [comment]
For more clarity - you need to install the `ibmagickcore-6.q16-3-extra` plugin:

```
sudo apt-get install ibmagickcore-6.q16-3-extra
```
