### ISSUE TITLE
Add files directly to the media library without morph entity

### ISSUE THREAD

**Issue by kirkegaard** [spatie/laravel-medialibrary#1423]
Is it possible to add files directly to the media library? 

Say i wanna allow anonymous uploads to my media library, then i wont have a `User` for the morph rows. I havent been able to find a proper way of doing this so right now im keeping a separate model called something like `MediaEntities` but it seems like an extra step of what i really want.

**Comment by riasvdv** [comment]
See #1443

**Comment by nikolayandreev** [comment]
I agree that this would be a great addition to the plugin, because today I needed it too.. CKEDITOR ajax uploads, before Entity creation.

This is how I solved it, without looking for more packages other than the great media library.

```
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
```
```
$image = Image::make($request->upload)->stream('jpg', 80);

$fileName = time() . '.jpg'; // You can also get file extenssion here, I just don't need pngs

Storage::put("public/blog/images/{$fileName}", $image);

 return response()->json([
  'uploaded' => 1,
  'fileName' => $fileName,
   'url'      => asset("storage/blog/images/{$fileName}"), // You can also use Storage::url() here, but I needed the full url and not the path.
 ]);
```

**Comment by saeedvir** [comment]
you can use this :

https://gist.github.com/saeedvir/968ec62b1cfc33a1cbab8e07178a25c1
