### ISSUE TITLE
V7 - Can not convert image. Unknown operation `x`

### ISSUE THREAD

**Issue by bee-interactive** [spatie/laravel-medialibrary#1428]
Hi!

Here's what I'm trying to achieve:

I have a dynamic drag&drop upload to create cropped thumbnails. The user can upload a picture, chose the cropped area and save his selection. Then, in the backend, I save the original picture with the medialibrary package. Easy step for now.

But, on the fly, I want to save his cropped version, attached with the original file entry.

I tried with this technique:

```
$model
    ->addMedia(public_path('content/temp/'. $filename.'.jpg'))
    ->withManipulations([
        'thumbnail' => ['width' => $image['actions']['crop']['width'], 'height' => $image['actions']['crop']['height'], 'x' => $image['actions']['crop']['x'], 'y' => $image['actions']['crop']['y']]
    ])
    ->toMediaCollection($filename);
```

the $image variable is the cropped version datas that I get from the cropping script. (I use the Slim Image Cropper library)

Then, on my Model, I use this:

```
public function registerMediaConversions(Media $media = null)
{
    $manipulations = collect(json_decode($media->getAttributes('thumbnail')['manipulations']))->first();
    $this->addMediaConversion('thumbnail')->focalCrop(200, 300, $manipulations->x, $manipulations->y);
}
```

I'm not sure if this is the best or the right approach. But then, when I upload, I always get this "can not convert image. Unknown operation 'x'" error.. 

Does anyone have an idea or a direction to achieve this?
Thank you!

**Comment by tudorradubarbu** [comment]
I had one of this too.
Actually '_thumbnail_' doesn't work.

Try this:

   
 ``` $manipulations = collect(json_decode($media->getAttributes('thumbnail')['manipulations']))->first();
    $this->addMediaConversion('cropped')->crop('crop-center', $manipulations->x, $manipulations->y)
    ->format('jpg')
    ->performOnCollections('photos')
    ->nonQueued();
```

**Comment by brendt** [comment]
Based on the lack of replies, I suppose this issue is now resolved?
