### ISSUE TITLE
Query a certain collection from the media library

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#143]
I need to query all images with of the same media collection and then I need to be able to access two sizes I have registered in my views
```
public function registerMediaConversions()
    {
        $this->addMediaConversion('adminthumb')
            ->setManipulations(['w' => 207, 'h' => 154, 'fit' => 'crop'])
            ->performOnCollections('galleryfrontimages');

        $this->addMediaConversion('frontthumb')
            ->setManipulations(['w' => 200, 'fit' => 'crop'])
            ->performOnCollections('galleryfrontimages');

        $this->addMediaConversion('frontlarge')
            ->setManipulations(['w' => 800])
            ->performOnCollections('galleryfrontimages');
    }
```
So i need to query all images that are in the

'galleryfrontimages' collection 

and then i need to be able to access the sizes urls within the loop on the front end

{{ $image[frontthumb] }} and {{ $image[frontlarge] }}

Any ideas, suggestions? Thanks.

**Comment by sebastiandedeyne** [comment]
You're going to have to write your own query, the media library doesn't have such functionality out of the box.

First you'd have to retrieve all the media items, then retrieve the relevant data.

```php
use \Spatie\Medialibrary\Media;

Media::where('collection_name', 'galleryfrontimages')
    ->get()
    ->map(function (Media $media) {
        return [
            'frontthumb' => $media->getUrl('frontthumb'),
            'frontlarge' => $media->getUrl('frontlarge'),
        ];
    });
```

**Comment by kickthemooon** [comment]
Sebastian you rock :)
will try it if I have problems i'll get back to you. thanks.
