### ISSUE TITLE
Question:does responsive images support storing on cloud storage?

### ISSUE THREAD

**Issue by usernameunknown9999** [spatie/laravel-medialibrary#1435]
I managed to store original and converted image on cloud storage. When it comes to performing image conversions, it will store the temporary files on storage_path('medialibrary/temp') as I did not change the 'temporary_directory_path' in medialibrary.php. I receive an error saying 'driver [] is not supported.'

This is how my cloud storage looks like. There's converted image storing in conversions folder but inside responsive-images folder it is empty.
![Screen Shot 2019-05-08 at 11 03 48 am](https://user-images.githubusercontent.com/49546132/57346415-02034780-7181-11e9-9e91-8d679d4ced79.png)

**Comment by brendt** [comment]
Are you sure the responsive images are indeed generated? They are asynchronously generated by a job, so you need to make sure you queue worker is running.

**Comment by brendt** [comment]
I'll be closing this issue as there hasn't been any answer in a while. Feel free to reply still.
