### ISSUE TITLE
Using medialibrary with direct S3 uploaded files

### ISSUE THREAD

**Issue by CanardDrones** [spatie/laravel-medialibrary#1436]
Hi! Thanks for the awesome library.

I have to upload ginormous video files (60GB or so) to an S3 server. Given the size of the files I want to avoid the double upload (user->laravel->S3) and I'd like the user to upload the files directly to Amazon (user->S3).

I have been working for a while in a way to upload the files directly from the browser and I finally have it working. Now the question is: How can I still associate those files uploaded directly to S3 to an object using laravel-medialibrary?

I've thought of creating new Media models and assigning their parameters manually, and to download the files just do it normally using the 's3' disk, but I don't know if that's the best way to do it.

Any suggestions?
Thanks!

**Comment by hustlon** [comment]
Please post your method

**Comment by CanardDrones** [comment]
I ended up using the Amazon S3 JavaScript SDK to upload the files:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html

**Comment by brendt** [comment]
I suppose this issue is solved? If you'd like to share your approach, we'd highly appreciate it!

**Comment by eberkund** [comment]
Please do share, I am also curious about this. Thanks.

**Comment by netbuilding** [comment]
Your share will be much appreciated!
