### ISSUE TITLE
srcset isn't urlencoded? (spaces in file name issue)

### ISSUE THREAD

**Issue by eminos** [spatie/laravel-medialibrary#1437]
This is what getSrcset() and getUrl() outputs in srcset and src attributes respectively:

```
<img srcset="https://dev.exampledomain.se/storage/media/659/responsive-images/Tools Birch___medialibrary_original_2500_1850.jpg 2500w, https://dev.exampledomain.se/storage/media/659/responsive-images/Tools Birch___medialibrary_original_2091_1547.jpg 2091w, https://dev.exampledomain.se/storage/media/659/responsive-images/Tools Birch___medialibrary_original_1749_1294.jpg 1749w" 
src="/storage/media/659/Tools%20Birch.jpg" 
sizes="(min-width: 1300px) calc((1300px - 3rem) / 3),
(min-width: 701px) calc(33vw - 3rem),
calc(100vw - 3rem)">
```

The main issue is that the URLs in srcset aren't "urlencoded" so spaces are not "%20", which breaks the HTML parsing. Compare to src which works as expected (space in file name becomes "%20").

Also the full URL, including the protocol and domain, are in the srcset, but not in the src. I'd expect it to be the same at least (without protocol and domain preferably).

Is this a bug or am I doing something wrong?

**Comment by eminos** [comment]
I have now confirmed my original issue only applies to old images, added to medialibrary many months ago. New image files being added get spaces in filenames replaced with dashes.
I'm thinking this was not the case in an older version of medialibrary that was used when these old images were uploaded to the system.

The question is, how would I solve this? Write a script to rename all medialibrary images containing spaces (both the file name and in the DB)? Or is there a better or easier way?

**Comment by meduzen** [comment]
I encountered the same issue under version 7.0.0. The _fix_ was:
1. update to last version
2. `php artisan medialibrary:regenerate` (but didn’t regenerate problematic files, which queues systematically failing…)
3. re-upload problematic files with same bad naming (= filenames having special characters), and then the queue was going fine.

Strange.

**Comment by eminos** [comment]
@meduzen That is not the issue I'm having unfortunately. My issue is pretty clear and not strange (I can see the issue in the medialibrary source code) :)

1. I'm on latest version.
2. medialibrary:regenerate doesn't generate responsive images for original files.
3. Yes, re-uploading works, but that's what I don't wanna do since there are a lot of files with spaces in their filenames.

**Comment by brendt** [comment]
@eminos are you willing to submit a PR to fix this?

**Comment by eminos** [comment]
For my part it turned out there weren't that many images with spaces, so I just re-uploaded them manually again.

The other issue, which might be related, is how the URLs are formatted for **src** (full url with domain) vs **srcset** (only path, no domain). As far as I can see in the medialibrary sourcecode the URL generation for those two parts of the img tag are done differently. Maybe it can be refactored and improved, so the URL generation is done the same way.

I'd love to help but I think it's a bit out of my current knowledge regarding making changes to laravel packages and submitting a PR. I wish there was some good guide for that (the ones I've found are not really helpful).
