### ISSUE TITLE
Add ability to specify a custom config file

### ISSUE THREAD

**Issue by jlmmns** [spatie/laravel-medialibrary#1438]
Hola!

I'm implementing this package in one of our own packages, and since we're dealing with our own package, I don't want to rely on the global `/config/medialibrary.php` config file. Using that config file can result in errors if the end project is already using the medialibrary package.

So it would be great if all config values were extracted to their own methods, for easier overwriting of only those small methods.

It might be a good idea to be able to **specify a custom config file**. Maybe somewhere on the Media model. Because even if there are simple config methods, we would still probably have to extend each of those classes, which would still be a hassle.

**Comment by jlmmns** [comment]
#1439 I've created a pull request for this.

Any improvements I need to add?

**Comment by brendt** [comment]
It shouldn't be this package's concern on how it's used from the outside. If you're making a package that's requiring this one, that package should make sure its dependencies are properly configured.

My suggestion would be to build your package in such a way that it doesn't depend on the specific medialibrary config. Another problem to take into consideration: what if a user requires both your package and the media library separately?

We had a discussion on this topic a long time ago at the office, and came to the conclusion that it's not possible to keep all external factors into account from within this package. It's the concern of the systems using it to make sure it's properly configured.

**Comment by jlmmns** [comment]
If you specify the custom config file using a middleware for just the endpoints of a custom package, there won't be any problems if the medialibrary package is already being used somewhere else in the project.

That's the main reason why I've made it this way.

Medialibrary will only use the custom config file for the code that's under the middleware.

That's why I thought it would be a very flexible non-breaking optional feature. 😀

I actually see it as an improvement for every laravel package. To be able to always use a custom config file where needed.

**Comment by brendt** [comment]
I agree it would be a good feature for Laravel, but don't think every package should re-implement and maintain the same code. 

For now I suggest your package simply stating users shouldn't publish the medialibrary config file, but instead use yours. Your service provide should then manually build the medialibrary config.

**Comment by jlmmns** [comment]
You're right brendt, thanks!
