### ISSUE TITLE
A single image per models

### ISSUE THREAD

**Issue by nathanprins** [spatie/laravel-medialibrary#144]
I read that I could also ask questions if I was stuck so here it goes.

Is there a clean way to only add a single image to a model like, let's say, an avatar?
And if so, how would I go about binding it to a property? 
So I could do: $user->avatar to retrieve it.

Thanks in advance!

**Comment by freekmurze** [comment]
On your User model you could use [a mutator](https://laravel.com/docs/5.1/eloquent-mutators#accessors-and-mutators) to [retrieve the first image of a collection](http://medialibrary.spatie.be/v3/converting-images/retrieving-converted-images/):

```php
public function getAvatarAttribute()
{
    return $this->getFirstMediaUrl($collectionName, $conversionName);
}
```

**Comment by nathanprins** [comment]
Works perfectly! Thanks a lot!

**Comment by nathanprins** [comment]
If the model doesn't have media in a collection, how would I go about returning a default image? 
I was thinking of something like this:
```
public function getCoverAttribute(){
        $cover = ???
        if($this->hasMedia('cover')){
            $cover = $this->getFirstMedia('cover');
        }
        return $cover;
}
```
But what should I put at the ??? or should it be completely different?

**Comment by sebastiandedeyne** [comment]
Tough one, we generally handle cases like this in our views or wherever we need them.

```
@if($model->hasMedia('cover'))
    <img src="{{ $this->getFirstMedia('cover')->getUrl() }}">
@else
    <img src="defaultimage.jpg">
@endif
```

Alternatively you could create a new `Media` instance there without saving it, but that would probably limit you in some cases.

**Comment by nathanprins** [comment]
I guess you're right, seeing as the default cover photo is something more dependent on the design instead of the system behind it. This keeps things MVC!

Thanks again!
