### ISSUE TITLE
Media Conversion only work with queue connection "sync"

### ISSUE THREAD

**Issue by eliyas5044** [spatie/laravel-medialibrary#1441]
I have runnig a queue worker with Supervisor. config like this
```
[program:dailycricket-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/dailycricket-admin/artisan queue:work --sleep=3 --tries=3
autostart=true
autorestart=true
user=eliyas
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/html/dailycricket-admin/storage/logs/worker.log
```
> in `.env` file, queue connection is `QUEUE_CONNECTION=database`
It works fine with other jobs dispatched by my application. But `Spatie\MediaLibrary\Jobs\PerformConversions` failed everytime.

> Work with **queue** connection `sync` fine.

Here is my conversion setting in model
```
public function registerMediaCollections()
    {
        $this->addMediaCollection('posts')
            ->singleFile()
            ->registerMediaConversions(function (Media $media) {
                $this
                    ->addMediaConversion('featured_one')
                    ->width(542)
                    ->height(330)
                    ->sharpen(10);
                $this
                    ->addMediaConversion('featured_two')
                    ->width(263)
                    ->height(160)
                    ->sharpen(10);
                $this
                    ->addMediaConversion('latest')
                    ->width(84)
                    ->height(51)
                    ->sharpen(10);
            });
    }
```
It only save default image, but all conversions failed.
appreciate your help :)

**Comment by SvenSchoene** [comment]
Man, I had the issue that **somehow** the conversions didn't work anymore.

Your issue pointed me in the right direction: I have since switched to the database queue and I haven't had a queue worker running when working on a part of my application that was about uploading images.

This is probably not *really* helpful to you, since you're saying that your worker **is** running.  
But maybe someone else sees this and forgot about this. :)

**Comment by brendt** [comment]
@eliyas5044 how exactly does the jobs fail? Do you have any logging or error output?

**Comment by eliyas5044** [comment]
> full error output

```

**Comment by brendt** [comment]
This is a problem with file permissions, the package is unable to write files to the folders. Make sure you're running the queue worker with a user that has write access to the correct folders.
