### ISSUE TITLE
Add ability to save media without a model relationship

### ISSUE THREAD

**Issue by jlmmns** [spatie/laravel-medialibrary#1444]
It would be great if we could save media without a model relationship.

I already went ahead and created a [pull request](https://github.com/spatie/laravel-medialibrary/pull/1443) for this.

Related issues: #1384 #1423

**Comment by jlmmns** [comment]
#1384

**Comment by jlmmns** [comment]
#1443

**Comment by brendt** [comment]
Let's discuss this in the PR (#1443)

**Comment by n0nsensei** [comment]
Has this been implement, if so it would be great for file manager implementation
