### ISSUE TITLE
How to get the media added

### ISSUE THREAD

**Issue by kipouras** [spatie/laravel-medialibrary#1445]
I am trying to get the media objects added from a request using the code below:

public function addMedia(Request $request)
{
       $tmp = Auth::User()
                ->addAllMediaFromRequest()
                ->each(function ($fileAdder) {
                    $id = uniqid('', true);
                    $fileAdder
                        ->usingName($id)
                        ->usingFileName($id.'.jpg')
                        ->toMediaCollection();
                });
      return $tmp;
}

The request is an ajax request and the response I get is an array of empty objects.
ajax response: 

[{},{},{}]

Is there a way to get the media objects created on each request?

**Comment by brendt** [comment]
Please refer to the docs site to know how to work with this package: https://docs.spatie.be/laravel-medialibrary/v7/introduction/
