### ISSUE TITLE
How to fill image with watermark by grid?

### ISSUE THREAD

**Issue by egerb** [spatie/laravel-medialibrary#1447]
How to fill image with watermark like grid?
Tried 
`$this->addMediaConversion('thumbs-555')
                    ->width(555)
                    ->watermark(public_path().'/img/LOGO.png')
                    ->watermarkOpacity(50)
                    ->watermarkFit(Manipulations::FIT_FILL);`
Doesn't work for me.
Thanx.

**Comment by brendt** [comment]
Can you provide some more information? What exactly doesn't work? Maybe share your test images?

**Comment by egerb** [comment]
Thanx for reply, @brendt ,
Got image with next dimension w 500 h 400, 
Got watermark 30 x 30, and want fill image with grid of watermarks (one by one on full image height and width).

**Comment by brendt** [comment]
@egerb There's no support to have a watermark be repeated. You should be able to add several watermarks by calling the `apply()` method: https://docs.spatie.be/image/v1/usage/advanced-manipulations/#the-apply-method

So technically it's possible if you'd take the dimensions of the image, loop over them and add each cell of the grid one by one. But there's no support for it in this package.

**Comment by egerb** [comment]
I see, thanx a lot!
