### ISSUE TITLE
Media directory

### ISSUE THREAD

**Issue by AaronChengHao** [spatie/laravel-medialibrary#1448]
Does one media create a directory?When the data is so big, will there be many directories?

**Comment by timgavin** [comment]
Yes, for each image uploaded a separate (sequentially numbered) directory is created. Any conversions are saved within a subdirectory of the image directory.

For instance, your first images uploaded would be saved in a directory named `1`.

Here's what it looks like on my local machine while testing

```
storage
  |--app
    |--public
      |--1
        |--responsive-images
        |-- first-uploaded-image.jpg
      |--2
        |--responsive-images
        |-- second-uploaded-image.jpg
```

**Comment by AaronChengHao** [comment]
> 是的，对于上传的每个图像，创建了一个单独的（顺序编号的）目录。任何转换都保存在image目录的子目录中。
> 
> 例如，您上传的第一张图片将保存在一个名为的目录中`1`。
> 
> 这是测试时本地机器上的样子
> 
> ```
> storage
>   |--app
>     |--public
>       |--1
>         |--responsive-images
>         |-- first-uploaded-image.jpg
>       |--2
>         |--responsive-images
>         |-- second-uploaded-image.jpg
> ```

Thank you, but if the directory is too many, will it affect the program performance?

**Comment by timgavin** [comment]
Don't see how it could. Regardless, I, along with many others, use S3 in production. No performance issues.

**Comment by AaronChengHao** [comment]
@timgavin thanks
