### ISSUE TITLE
Responsive imagery being wiped with custom PathGenerator using shared directory

### ISSUE THREAD

**Issue by mdixon18** [spatie/laravel-medialibrary#1449]
This may not be what you would call an issue, but if you have any intention on merging in [#1443](https://github.com/spatie/laravel-medialibrary/pull/1443) or displaying every model based media in a shared directory then there is a potential issue with a custom PathGenerator when deleting responsive imagery.

In this instance I have decided, I want all media in one directory.
```
/*
 * Get the path for the given media, relative to the root storage path.
 */
public function getPath(Media $media) : string
{
        return '/';
}

/*
 * Get the path for conversions of the given media, relative to the root storage path.
*/
public function getPathForConversions(Media $media) : string
{
        return $this->getPath($media);
}

/*
 * Get the path for responsive images of the given media, relative to the root storage path.
*/
public function getPathForResponsiveImages(Media $media) : string
{
        return $this->getPath($media);
}
```

Now, when you are using `$media->withResponsiveImages();` it will use the `removeResponsiveImages` method inside the `Spatie\MediaLibrary\Filesystem\FileSystem`.

This function will delete all imagery, even other imagery because of the `str_contains` as shown.

```
$responsiveImagePaths = array_filter(
        $allFilePaths,
        function (string $path) use ($conversionName) {
                return str_contains($path, $conversionName);
        }
);
```
I have managed to fix this issue locally with a change to this function, but I am unsure if it is the best way to fix it.

Here is my suggested fix:
```
$responsiveImagePaths = array_filter(
            $allFilePaths,
            function (string $path) use ($conversionName, $media) {
                return str_contains($path, $conversionName) && str_contains($path, str_replace("." . $media->getExtensionAttribute(), '', $media->file_name));
            }
 );
```

Through this, when I upload several images it keeps all of the responsive images that it should, and if the filename is the same then it overwrites the relevant one. All i've done to do this is take the filename removed the extension and used it with the `$conversionName` variable to ensure that only the relevant media is deleted.

Hope this all makes sense!

**Comment by mdixon18** [comment]
Off the back of this, the Filesystem `removeAllFiles` method also doesn't work. As it then simply tries to delete the entire disks folder.

All i've done for my own usage is if the directory is set to / then to call `removeResponsiveImages` and `removeFile`. 

Not sure what the overall fix would be for this.

**Comment by brendt** [comment]
Hi @mdixon18 

> In this instance I have decided, I want all media in one directory.

I'm afraid this is an edge case this package won't support, this is also explicitly mentioned in [the docs](https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-a-custom-directory-structure/)

> There aren’t any restrictions on how the directories can be named. When a Media-object gets deleted the package will delete its entire associated directory. To avoid tears or worse, make sure that every media gets stored its own unique directory.
