### ISSUE TITLE
Ideas for video thumbnails?

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#145]
I'd like to create video thumbnails when I upload videos.

Any idea on how I could accomplish that?

**Comment by kickthemooon** [comment]
I have a method and model for my media library uploads:
```
public static function storeGallery(Request $request, $model, $collection, $disk='media') {

        $model->addMedia($request->file('file'))->withCustomProperties(['title_en'=>'', 'subtitle_en'=>'', 'title_ba'=>'', 'subtitle_ba'=>''])->toCollectionOnDisk($collection, $disk);
        return 'Media was saved successfully!';

    }
```
now at this point id like use the ffmpeg to make a thumbnail of that video I uploaded with something like this:
```
$frame = 10;
$movie = 'test.mp4';
$thumbnail = 'thumbnail.png';

$mov = new ffmpeg_movie($movie);
$frame = $mov->getFrame($frame);
if ($frame) {
    $gd_image = $frame->toGDImage();
    if ($gd_image) {
        imagepng($gd_image, $thumbnail);
        imagedestroy($gd_image);
    }
}
```
And after this id like to store it with the file under conversions so I can query it later.

What do you think of this idea, could you help me a little

**Comment by freekmurze** [comment]
Generating a video thumbnail is out of scope for this package. You'll have research the subject a bit to find the best way. Looking at the code example above it looks like you've started your research already. :smile: 

When you create an image of the video, you can of course just add that image to the media library.

**Comment by kickthemooon** [comment]
i can upload videos with media library already tried it, and it gets saved as any other media.
now, when i manage to get this thumbnail generated with ffmpeg I would love to save it in the folder the video got saved to under conversions. I mean i hope you understand what I mean.
Id like to know how I can make this conversion folder that gets created for the other images.

Any idea?

**Comment by freekmurze** [comment]
I think you want to manually add a file to the conversion folder? The package doesn't support this out of the box. That beging said, there's nothing that stops you from adding files to a conversion folder yourself. Be aware that deleting a media object will deleted the entire conversion folder as well. But that's probably good in this case.

**Comment by riter** [comment]
You can save the image in the MediaLibrary folder respecting how it saves the Thumbnails. Then you modify the Manipulations column of the database (respecting how it does with the images), so I assume that it will relate your video to the image. I think it can work
