### ISSUE TITLE
getFullUrl() is generating an incorrect URL for Arabic characters

### ISSUE THREAD

**Issue by mkwsra** [spatie/laravel-medialibrary#1451]
I spent some time in order to figure out the problem and the matter, in fact, it's not related directly to _Laravel Media Library_, it's PHP mentality.

in `vendor/spatie/laravel-medialibrary/src/UrlGenerator/BaseUrlGenerator.php:82:5`, the `pathinfo()` function is affected by PHP's `setlocale()`, and with default settings, it's slicing a portion of the URL as shown below:

![Screen Shot 2019-05-20 at 6 35 42 PM](https://user-images.githubusercontent.com/1743919/58083919-8fec2300-7bc2-11e9-8a0c-3e19154a29ac.png)

And after adding the proper _Locale_:
![Screen Shot 2019-05-21 at 12 26 56 PM](https://user-images.githubusercontent.com/1743919/58084541-c1b1b980-7bc3-11e9-80e1-4fbb09589a2b.png)

So perhaps there is a plan to tweak this function or another solution to implement? any help is appreciated.

**Comment by freekmurze** [comment]
If there's an easy, testable fix for us to implement, feel free to send a PR.

**Comment by Daniyal-Javani** [comment]
Can we consider `setlocale(LC_ALL, config('app.locale'));` as a fix?

**Comment by mkwsra** [comment]
It could be but I cannot test it now

**Comment by Daniyal-Javani** [comment]
My problem solved "temporarily" with adding what you said before adding media in Controller like this:
```
setlocale(LC_ALL, 'en_US.utf8');

$company->addMediaFromRequest('image')
       ->toMediaCollection('companies');
```
