### ISSUE TITLE
Add the shouldDeletePreservingMedia() method to the docs

### ISSUE THREAD

**Issue by Livijn** [spatie/laravel-medialibrary#1454]
You should add the `shouldDeletePreservingMedia()` method to the docs. Also, maybe it's just me, but the naming is strange. I think it would be easier to understand what it implies by renaming it to `shouldDeletePreserveMedia()`.

**Comment by freekmurze** [comment]
Please send a PR to our docs. There's an edit button to create a PR on each page of the docs.
