### ISSUE TITLE
Use latest stable version of zipstream-php?

### ISSUE THREAD

**Issue by herroworrd** [spatie/laravel-medialibrary#1458]
https://github.com/spatie/laravel-medialibrary/blob/6ffb8a41e60f024abd35ff47e08628354d6efd0e/composer.json#L32

Would be nice to have media-library use the latest version of zipstream. I'm getting some conflicts with other packages. 

Latest version is currently 1.1 but medialibrary is at ~0.4

**Comment by atymic** [comment]
As per the [changelogs](https://github.com/maennchen/ZipStream-PHP/blob/master/CHANGELOG.md#100---2019-04-17) there were some breaking changes from 0.x versions to 1.x verions.

I'll look into creating a pr, as the changes don't seem very complex.

**Comment by atymic** [comment]
Seems like there is a PR open here already: 
https://github.com/spatie/laravel-medialibrary/pull/1452

**Comment by freekmurze** [comment]
We'll continue thi sin #1452
