### ISSUE TITLE
PDF issue: Unsupported image type. GD driver is only able to decode JPG, PNG, GIF or WebP files.

### ISSUE THREAD

**Issue by Fab-Miami** [spatie/laravel-medialibrary#1460]
Hi,

I can not upload any pdf, pdf doesn't work.

Running Laravel 5.7 in dev on Xampp (windows 10). ImageMagik 7 is installed and works fine.

In my model:

`
 public function registerMediaCollections()
    {
        $this->addMediaCollection('vendor_document')
             ->useDisk('vendor_documents');
`

Uploading an image (jpg, gif or png) everything works perfectly fine.

Uploading a PDF, I'm getting this error:
`Intervention \ Image \ Exception \ NotReadableException
Unsupported image type. GD driver is only able to decode JPG, PNG, GIF or WebP files.`

Coming form line 57 of:
\vendor\intervention\image\src\Intervention\Image\Gd\Decoder.php

` 
            default:
                throw new \Intervention\Image\Exception\NotReadableException(
                    "Unsupported image type. GD driver is only able to decode JPG, PNG, GIF or WebP files."
                );`

I just spent my afternoon trying troubleshoot.... any idea?

**Comment by Fab-Miami** [comment]
Please, delete my question, I found the problem, it was linked to a pre-treatment, not to medialibrary.

**Comment by ixperiencenl** [comment]
I am having this problem too. I just can't get it to skip the image conversion if it's a PDF, DOCX or whatever other extension. How did you solve this?

**Comment by yoniyou-1** [comment]
Si explica tengo el mismo problema \vendor\intervention\image\src\Intervention\Image\Gd\Decoder.php:59 
- tambien quiero es subir pdf

**Comment by MdEahiaMondal** [comment]
i got same problem ..please help me.. how can i fixed it..

**Comment by e-hop** [comment]
+1

**Comment by mkwsra** [comment]
+1

**Comment by aliraza93** [comment]
Did anyone managed to solve the issue?

**Comment by yoniyou-1** [comment]
Hola, tenia problemas con el PDF para esta Librería. 
Prueben colocar esto en su formulario de creación:

`<div class="form-group">
    <label for="file" class="col-lg-3 control-label">Subir  Archivo(s)</label>
    <div class="col-lg" >
        <input type="file" name="file_up[]" id="file" data-initial-preview="{{isset($data->file) ? Storage::url("archivos/caratulas/$data->file") : "http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=Archivos+a+subir"}}" accept="*/*"/ multiple
        >
    </div>
</div>`

en el caso de editar

`
<input type="hidden" id="documentoajax" value="{{$data->id}}">
<div class="form-group">
<label for="file" class="col-lg-3 control-label">Subir Nuevo(s)  Archivo(s)</label>
<div class="file-loading">
    <input id="file" name="file_up[]" type="file" multiple>
`
Por alguna razón tuve colocar el JS de previsualización de pdfs para la edición en el archivo html de edición, en mi caso fue blade de laravel. coloque las funciones en unas etiquetas js dentro del archivo editar.blade.php al principio. con el siguiente contenido:

deje comentados algunos ejemplos que me funcionaron para presurizar los PDFs.


esto es en editar.blade.php
`
<script> var objetoFiles = [];
            var urlfilearray = [];
    </script>
     @foreach ($data->files as $file)
    <script>

        urlfilearray.push( "{{Storage::url('archivos/'.$data->id.'/'.$file->name)}}",);
        var urlfile = "{{Storage::url('archivos/'.$data->id.'/'.$file->name)}}";
        var namefile = "{{$file->name}}";
        var extensionfile = "{{$file->extension}}";
        var idfile = "{{$file->id}}";
        if(extensionfile == 'jpg' || extensionfile == 'png' || extensionfile == 'jpeg' ){
             objetoFiles.push (  { caption: namefile, url: urlfile, key: idfile, downloadUrl: urlfile },);
        }else{
        objetoFiles.push (  {type: extensionfile,  caption: namefile, url: urlfile, key: idfile, downloadUrl: urlfile },);
    }
    //alert("{{$file->name}}");
    </script>
     @endforeach

  <script>var urla = ["{{Storage::url('archivos/'.$data->id.'/aa.pdf')}}",
                    "{{Storage::url('archivos/'.$data->id.'/bb.pdf')}}"];

     /*console.log(urlfilearray);
     console.log(urla);*/

    /*var uraque = [{ url : "{{Storage::url('archivos/'.$data->id.'/aa.pdf')}}"},
     {url : "{{Storage::url('archivos/'.$data->id.'/bb.pdf')}}"}];

var myJsonString = JSON.parse(JSON.stringify(uraque));
  console.log(myJsonString);*/
    //console.log(urla);


//console.log(objetoFiles);

var hh = [
            {type: "pdf", url: "{{Storage::url('archivos/'.$data->id.'/aa.pdf')}}", }, // disable download
            {type: "pdf", url: "{{Storage::url('archivos/'.$data->id.'/bb.pdf')}}", },
        ];
  //console.log(hh);


  </script>   


<script> 

   /* $('#file').fileinput({



        language: 'es',
        allowedFileExtensions: ['jpg', 'jpeg', 'png', 'pdf'],
        //maxFileSize: 5000,
        maxFileCount: 5,
        showUpload: false,
        showClose: false,
        initialPreviewAsData: true,
        dropZoneEnabled: false,
        theme: "fas",
    });*/

               //'http://localhost:8000/storage/archivos/2/aa.pdf' otra buena "{{Storage::url('archivos/'.$data->id.'/aa.pdf')}}"
    /*var url1 = "{{Storage::url('archivos/'.$data->id.'/aa.pdf')}}",
        url2 = "http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Earth_Eastern_Hemisphere.jpg/600px-Earth_Eastern_Hemisphere.jpg";*/
        var url1 = "{{Storage::url('archivos/'.$data->id.'/aa.pdf')}}",
            url2 = "{{Storage::url('archivos/'.$data->id.'/bb.pdf')}}";

    $("#file").fileinput({
         language: 'es',
         //allowedFileExtensions: ['jpg', 'jpeg', 'png', 'pdf'],
        initialPreview: urlfilearray,
        //["/storage/archivos/2/aa.pdf","http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Earth_Eastern_Hemisphere.jpg/600px-Earth_Eastern_Hemisphere.jpg"],
        initialPreviewAsData: true,
        initialPreviewConfig: objetoFiles,


        /*[
            {type: "pdf", url: url1, }, // disable download
            {type: "pdf", url: url2, }
        ],*/
        /*[
            
            {type: "pdf", size: 8000, caption: "aa.pdf", url: url1, key: 1, downloadUrl: url1}, // disable download
            {type: "pdf", size: 8000, caption: "bb.pdf", url: url2, key: 2, downloadUrl: url2}
            
        ],*/
        
        overwriteInitial: false,
        maxFileCount: 20,
        showUpload: false,
        showClose: false,
        initialPreviewAsData: true,
        dropZoneEnabled: false,

        
        /*deleteUrl: "file/{{17}}",
        deleteExtraData: {_token: $("[name='_token']").val()},*/
        theme: "fas",
    });

   //alert('{{$data->id}}');



   
</script>
`

**Comment by yoniyou-1** [comment]
Espero que les funcione, lo que para mi funciono.

Me funciono esto en el formulario de creación. trabaje con laravel y su motor de plantillas blade.
```
<div class="form-group">
    <label for="file" class="col-lg-3 control-label">Subir  Archivo(s)</label>
    <div class="col-lg" >
        <input type="file" name="file_up[]" id="file" data-initial-preview="{{isset($data->file) ? Storage::url("archivos/caratulas/$data->file") : "http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=Archivos+a+subir"}}" accept="*/*"/ multiple
        >
    </div>
</div>
```

Me funciono esto en el formulario de Edición.

```
<input type="hidden" id="documentoajax" value="{{$data->id}}">
<div class="form-group">
<label for="file" class="col-lg-3 control-label">Subir Nuevo(s)  Archivo(s)</label>
<div class="file-loading">
    <input id="file" name="file_up[]" type="file" multiple>
</div>
</div>
```


para el caso de edición he tenido que agregar JS en el mismo formulario por alguna razón no funcionaba simplemente anclar un archivo js con las funciones que cree. 

acá podrá ver ejemplos y ejemplos comentados de código duro de como escribí lo que para mi funciono. 
```
<script> var objetoFiles = [];
            var urlfilearray = [];
    </script>
     @foreach ($data->files as $file)
    <script>

        urlfilearray.push( "{{Storage::url('archivos/'.$data->id.'/'.$file->name)}}",);
        var urlfile = "{{Storage::url('archivos/'.$data->id.'/'.$file->name)}}";
        var namefile = "{{$file->name}}";
        var extensionfile = "{{$file->extension}}";
        var idfile = "{{$file->id}}";
        if(extensionfile == 'jpg' || extensionfile == 'png' || extensionfile == 'jpeg' ){
             objetoFiles.push (  { caption: namefile, url: urlfile, key: idfile, downloadUrl: urlfile },);
        }else{
        objetoFiles.push (  {type: extensionfile,  caption: namefile, url: urlfile, key: idfile, downloadUrl: urlfile },);
    }
    //alert("{{$file->name}}");
    </script>
     @endforeach

  <script>var urla = ["{{Storage::url('archivos/'.$data->id.'/aa.pdf')}}",
                    "{{Storage::url('archivos/'.$data->id.'/bb.pdf')}}"];

     /*console.log(urlfilearray);
     console.log(urla);*/

    /*var uraque = [{ url : "{{Storage::url('archivos/'.$data->id.'/aa.pdf')}}"},
     {url : "{{Storage::url('archivos/'.$data->id.'/bb.pdf')}}"}];

var myJsonString = JSON.parse(JSON.stringify(uraque));
  console.log(myJsonString);*/
    //console.log(urla);


//console.log(objetoFiles);

var hh = [
            {type: "pdf", url: "{{Storage::url('archivos/'.$data->id.'/aa.pdf')}}", }, // disable download
            {type: "pdf", url: "{{Storage::url('archivos/'.$data->id.'/bb.pdf')}}", },
        ];
  //console.log(hh);


  </script>   


<script> 

   /* $('#file').fileinput({



        language: 'es',
        allowedFileExtensions: ['jpg', 'jpeg', 'png', 'pdf'],
        //maxFileSize: 5000,
        maxFileCount: 5,
        showUpload: false,
        showClose: false,
        initialPreviewAsData: true,
        dropZoneEnabled: false,
        theme: "fas",
    });*/

               //'http://localhost:8000/storage/archivos/2/aa.pdf' otra buena "{{Storage::url('archivos/'.$data->id.'/aa.pdf')}}"
    /*var url1 = "{{Storage::url('archivos/'.$data->id.'/aa.pdf')}}",
        url2 = "http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Earth_Eastern_Hemisphere.jpg/600px-Earth_Eastern_Hemisphere.jpg";*/
        var url1 = "{{Storage::url('archivos/'.$data->id.'/aa.pdf')}}",
            url2 = "{{Storage::url('archivos/'.$data->id.'/bb.pdf')}}";

    $("#file").fileinput({
         language: 'es',
         //allowedFileExtensions: ['jpg', 'jpeg', 'png', 'pdf'],
        initialPreview: urlfilearray,
        //["/storage/archivos/2/aa.pdf","http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Earth_Eastern_Hemisphere.jpg/600px-Earth_Eastern_Hemisphere.jpg"],
        initialPreviewAsData: true,
        initialPreviewConfig: objetoFiles,


        /*[
            {type: "pdf", url: url1, }, // disable download
            {type: "pdf", url: url2, }
        ],*/
        /*[
            
            {type: "pdf", size: 8000, caption: "aa.pdf", url: url1, key: 1, downloadUrl: url1}, // disable download
            {type: "pdf", size: 8000, caption: "bb.pdf", url: url2, key: 2, downloadUrl: url2}
            
        ],*/
        
        overwriteInitial: false,
        maxFileCount: 20,
        showUpload: false,
        showClose: false,
        initialPreviewAsData: true,
        dropZoneEnabled: false,

        
        /*deleteUrl: "file/{{17}}",
        deleteExtraData: {_token: $("[name='_token']").val()},*/
        theme: "fas",
    });

   //alert('{{$data->id}}');



   
</script>
```
