### ISSUE TITLE
--only-missing only works with nonQueued conversions

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-medialibrary#1465]
using --only-missing with medialibrary:regenerate only works if your conversions are nonQueued()

the problem code is located here https://github.com/spatie/laravel-medialibrary/blob/master/src/FileManipulator.php#L40-L50

For conversions that are queued(), the createDerivedFiles() method dispatches without passing along the only-missing flag, which causes performConversions() to be called without the onlyMissing flag set to true

If you log::debug the value of `$onlyIfMissing` you'll see that initially it is set to true and then becomes set to false and the conversions are redone for media entries that were already converted. This problem does not occur if you change the conversions to be nonQueued()

**Comment by brendt** [comment]
@vesper8 thanks for the report. Are you able to send a PR to fix this?

**Comment by ahmedofali** [comment]
@brendt Please Review the pull request and let me know if any .

**Comment by vesper8** [comment]
thank you @ahmedofali for submitting https://github.com/spatie/laravel-medialibrary/pull/1473

**Comment by ahmedofali** [comment]
@vesper8 Pleasure

**Comment by brendt** [comment]
Merged and tagged: https://github.com/spatie/laravel-medialibrary/releases/tag/7.6.3
