### ISSUE TITLE
Regenerate doesn't delete old conversions!

### ISSUE THREAD

**Issue by develsanket** [spatie/laravel-medialibrary#1475]
While running php artisan medialibrary:regenerate if I add a conversion it generate a new file for that conversion but when I remove a conversion it will not remove the converted file.

**Comment by riasvdv** [comment]
That's what `php artisan medialibrary:clean` is for

**Comment by AforDesign** [comment]
I've ran the media-library:clean command but it cleans nothing.

It shows 'All done!' after 1-2 seconds, but all old conversions remain.

Also, it would be nice to be able to clear old responsive src-set items.

**Comment by gordonnchy** [comment]
> I've ran the media-library:clean command but it cleans nothing.
> 
> It shows 'All done!' after 1-2 seconds, but all old conversions remain.
> 
> Also, it would be nice to be able to clear old responsive src-set items.

same problem here...
