### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by shellofyou** [spatie/laravel-medialibrary#148]
Problem 1
    - Conclusion: don't install spatie/laravel-glide 2.2.6
    - Installation request for spatie/laravel-medialibrary ^3.13 -> satisfiable by spatie/laravel-medialibrary[3.13.3].
    - Conclusion: don't install symfony/http-foundation v3.0.1|install spatie/laravel-glide 2.2.6
    - Conclusion: remove symfony/http-foundation v3.0.1|install spatie/laravel-glide 2.2.6
    - spatie/laravel-medialibrary 3.13.3 requires spatie/laravel-glide ^2.2.4 -> satisfiable by spatie/laravel-glide[2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8].
    - spatie/laravel-glide 2.2.4 requires league/glide 0.3.* -> satisfiable by league/glide[0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5].
    - spatie/laravel-glide 2.2.5 requires league/glide 0.3.* -> satisfiable by league/glide[0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5].
    - spatie/laravel-glide 2.2.7 requires league/glide 0.3.* -> satisfiable by league/glide[0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5].
    - spatie/laravel-glide 2.2.8 requires league/glide 0.3.* -> satisfiable by league/glide[0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5].

**Comment by freekmurze** [comment]
This is fixed. Try installing the package again.

**Comment by shellofyou** [comment]
Thank you very much!
