### ISSUE TITLE
spatie/pdf-to-image dependency enforces optional imagick to be installed on server

### ISSUE THREAD

**Issue by satyago** [spatie/laravel-medialibrary#1480]
This package lists ghostscript / imagemagick as optional dependencies based on whether PDF/SVG need to be rendered. However, it is still pulling in `spatie/pdf-to-image` by default, which has `imagick` listed as one of its enforced requirements.

Installing the `laravel-medialibrary` package on a server without the `imagick` extension being available will immediately fail.

**Comment by brendt** [comment]
As of now, I've added Imagick as a primary dependency. We'll revisit this in the nest major version.

Tagged here: https://github.com/spatie/laravel-medialibrary/releases/tag/7.6.4

**Comment by freekmurze** [comment]
In the next major version we'll probably move the `pdf-to-image` package to the development dependencies and remove the requirement for `imagick` on the medialibrary.

**Comment by jstoone** [comment]
I'm sorry for resurrecting this thread, but I figured that it couldn't hurt to share how I've resolved this issue.

My CI started squacking, because our docker setup doesn't have `ext-imagick` installed. So after some digging I ended up adding the following to my `composer.json`:
```diff
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
+       "spatie/laravel-medialibrary": "^7.0.0"
    },
+   "provide": {
+       "ext-imagick": "*"
+   },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    }
}
```
> _NB:_ The above is a "snipped" version of the stock composer file from laravel/laravel

This solved my problem, since I don't (yet) use any of the transformation options provided by the package.
So for everyone who's in a similar situation, can join the BYOI (Bring Your Own `imagic`) train. :tada:

**Comment by mokhosh** [comment]
@jstoone thanks man you saved me
@brendt but why tho?!

**Comment by freekmurze** [comment]
The `pdf-to-image` dependency has been moved to suggestions in the `v8` branch.
