### ISSUE TITLE
How to get the id of an added media

### ISSUE THREAD

**Issue by invaders-xx** [spatie/laravel-medialibrary#1482]
Dear all,

I have this code:
$media=$product->addMedia($image)->sanitizingFileName(function($fileName) {
                    return strtolower(str_replace(['#', '/', '\\', ' '], '_', $fileName));
                });
                $media->toMediaCollection($lang);
return ['success'=>'success','id'=>$media->id];

And I have an error:
 "message": "Undefined property: Spatie\\MediaLibrary\\FileAdder\\FileAdder::$id",

So how can I get the id of the added media ?

Many thanks in advance,

David

**Comment by riasvdv** [comment]
The `toMediaCollection` function returns the `Media` object.

In your case you'd have to do change the following:

```
$media->toMediaCollection($lang);
```

To

```
$media = $media->toMediaCollection($lang);
```
