### ISSUE TITLE
Is it possible to disable the queue for conversions?

### ISSUE THREAD

**Issue by mattmcardle** [spatie/laravel-medialibrary#1484]
My application has a similar architecture to what is described in this issue: https://github.com/spatie/laravel-medialibrary/issues/1320, and I am faced with the same problem.

From what I can see, there was no resolution to that issue, which is fine, I'm sure I will be able to figure out some way of rolling my own job and handler to perform the tenant connection before executing the conversions. 

In the meantime, can I disable the queue for the conversions, and have them performed synchronously?

**Comment by audetcameron** [comment]
use ->nonQueued()  on the conversion
```
        ->registerMediaConversions(function (Media $media) {
            $this->addMediaConversion('thumb')
            ->keepOriginalImageFormat()
            ->nonQueued()
            ->crop('crop-center', 50, 50);
        });
```

**Comment by AugustGarcia** [comment]
The answer from @audetcameron worked for me.  

Found this thread while looking for a way to automatically toggle the use of the queue on or off without having to set this for all models in registerMediaConversions. 

Looking through the actual code in **./vendor/spatie/laravel-medialibrary/src/Conversion/Conversion.php**:
```
class Conversion
{
    [...]

    protected $performOnQueue = true;

    [...]

    /**
     * Mark this conversion as one that should not be queued.
     *
     * @return $this
     */
    public function nonQueued()
    {
        $this->performOnQueue = false;

        return $this;
    }

    /**
     * Mark this conversion as one that should be queued.
     *
     * @return $this
     */
    public function queued()
    {
        $this->performOnQueue = true;

        return $this;
    }

    /**
     * Mark this conversion as one that should not be queued.
     *
     * @return $this
     */
    public function nonQueued()
    {
        $this->performOnQueue = false;

        return $this;
    }

    /*
     * Determine if the conversion should be queued.
     */
    public function shouldBeQueued(): bool
    {
        return $this->performOnQueue;
    }

    [...]
}
```
You could also change the default value for $performOnQueue in that class directly, but it's generally not ideal to edit code in the vendor folder. There's probably a better way to override this cleanly. 

What would be ideal is if there were an option to set the default for this were added to an easily-editable config file or similar (I didn't see one). Queues often run into issues with shared hosting in particular; obviously deploying Laravel to a VPS or similar is preferable, but there are plenty of Laravel projects that are on shared hosting for one reason or another.
