### ISSUE TITLE
Stop using `url()` helper for file urls

### ISSUE THREAD

**Issue by AlexVanderbist** [spatie/laravel-medialibrary#1485]
Currently we use Laravel's `url()` helper all over the place. However, this helper wasn't intended to create urls for files. For example executing `url('/image.jpg')` on http://example.com/index.php/test will output `http://example.com/index.php/image.jpg`.

I'd propose swapping this for our own implementation of the UrlGenerator (a bit like the `asset()` helper does).

See #1462

**Comment by freekmurze** [comment]
I refactored all usages away on the `v8` branch.
