### ISSUE TITLE
File updating problem

### ISSUE THREAD

**Issue by HasanurHimel** [spatie/laravel-medialibrary#1486]
I create Media Model and defind all the class according to your previous issues solution but when i going to update , it's given error like below . How can i solve this

Too few arguments to function Spatie\MediaLibrary\Filesystem\Filesystem::removeFiles(), 1 passed in D:\Xampp\htdocs\my-blog\app\Models\Media.php on line 27 and exactly 2 expected

this part of method i defined in my controller ,

if ($request->file('image')!=null){

            $existingImage=Media::where('model_id', $id)->first();
                $newFile = $request->file('image');
               $existingImage->updateFile($newFile);
        }

**Comment by vdbelt** [comment]
I would suggest updating to the latest release and going through the docs provided on https://github.com/spatie/laravel-medialibrary

You may not be using the library as intended. Perhaps you have implemented some work-around for a previous 'issue' for a different/older version of this package.

Passing tests show that the package is working. If you think there is a bug in the current release, you could submit a PR for us to look at.

**Comment by HasanurHimel** [comment]
Finally its work but i had to make some changes. Thanks
