### ISSUE TITLE
Model with multiple media conversions runs multiple update queries

### ISSUE THREAD

**Issue by getupkid** [spatie/laravel-medialibrary#1487]
I couldn't see any other issues raised for this. I'm pretty sure I am implementing my conversions correctly on my model.
I have 4 different media conversions one 1 model:

```
$this->addMediaConversion('lg')
                 ->width(600)
                 ->height(600)
                 ->sharpen(10)
                 ->keepOriginalImageFormat();

        $this->addMediaConversion('md')
                ->width(450)
                ->height(450)
                ->sharpen(10)
                ->keepOriginalImageFormat();

        $this->addMediaConversion('xs')
                ->width(150)
                ->height(150)
                ->sharpen(10)
                ->keepOriginalImageFormat();
                
        $this->addMediaConversion('sm')
                ->width(300)
                ->height(300)
                ->sharpen(10)
                ->keepOriginalImageFormat();

```
I've noticed that when I upload an image and the conversions run, there are 4 update queries in running that update the custom properties. Each update query adds the next media conversion to the JSON string. Should this not be just 1 update query?

Here are the updates queries:
![image](https://user-images.githubusercontent.com/4795041/60307113-c3665e00-9975-11e9-8ef5-1fd91deefa31.png)

As you can see, each update query is updating the same row, but adding the next custom property. Should this not just 1 query (the last one in the list) to update?

**Comment by brendt** [comment]
Feel free to submit a tested PR to optimise this.
