### ISSUE TITLE
Multiple filesystems

### ISSUE THREAD

**Issue by zr87** [spatie/laravel-medialibrary#1488]
Hey!

I'm using versions: L5.2,  ML ^4

I want to use two filesystems to handle media assets and 
the `config/laravel-medialibrary.php` file says:
```
  /*
     * The filesystems on which to store added files and derived images by default. **Choose
     * one or more of the filesystems you configured in app/config/filesystems.php**
     */
```
It says: `on or more`...
I configured Digital Ocean's Spaces disk and mapped to `spaces`.

By the above highlighted  comment I would expect the following to work:

```
    'defaultFilesystem' =>['media', 'spaces'],
```

**Comment by riasvdv** [comment]
That's a typo in the comment of the config file. `defaultFilesystem` only allows one default filesystem. To store the media on another disk, you can use the 
`->toCollectionOnDisk` function, see https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/working-with-multiple-filesystems/
