### ISSUE TITLE
QUESTION (not issue): How to print a pdf?

### ISSUE THREAD

**Issue by Fab-Miami** [spatie/laravel-medialibrary#1493]
Hi,

I'm displaying a png thumnail of an uploaded pdf.
We need a button which, when clicked, will send the related pdf to the printer.

Any idea on how to do that?

Thanks
FAB

**Comment by brendt** [comment]
Take a look at Laravel's file downloads and file responses: https://laravel.com/docs/5.8/responses#file-downloads
