### ISSUE TITLE
getUrl() ignores chinese characters

### ISSUE THREAD

**Issue by sooxiaotong** [spatie/laravel-medialibrary#1494]
I get this example, the file name is Chinese but it don't have any output.

current output:
> https://example.com/storage/39/.pdf

expected output:
> https://example.com/storage/39/中文.pdf

**Comment by vdbelt** [comment]
You may want to use 'setlocale()' prior to running your code. 

Related: https://github.com/spatie/laravel-medialibrary/issues/1287#issuecomment-462029178

**Comment by brendt** [comment]
I guess `setlocale` is the solution here, based on the previous issue. Thanks @vdbelt for pointing that out.
