### ISSUE TITLE
Conversions on specific collections not specific

### ISSUE THREAD

**Issue by eldiddio** [spatie/laravel-medialibrary#1495]
Following this guide: [performing-conversions-on-specific-collections](https://docs.spatie.be/laravel-medialibrary/v7/converting-images/defining-conversions/#performing-conversions-on-specific-collections)

I have added a method to my model like this:
```php
public function registerMediaConversions(Media $media = null)
{
    $this->addMediaConversion('thumb')
        ->width(48)
        ->height(48)
        ->performOnCollections('images');
}
```

However when I add a file to a different collection as described in the docs and then try retrieve the thumb conversion e.g.
```php
$media = $newsItem->addMedia($pathToImage)->toMediaCollection('other');
$media->getUrl('thumb');
```

It returns:

```
http://laravel.test/storage/1/conversions/1-thumb.jpg
```

As the thumb conversion is not applied to the collection the link it returns does not exist.

I have also tried the other method mentioned in the documentation: [registering-media-conversions](https://docs.spatie.be/laravel-medialibrary/v7/working-with-media-collections/defining-media-collections/#registering-media-conversions) but that has the same behavior. If I remove all the methods from the Model relating to conversions and try retrieve the URL it throws a exception.

Adding an image to the images collection works as expected.

I am using the basic public disk driver that comes shipped with Laravel.

Any help would be greatly appreciated.

**Comment by brendt** [comment]
`LocalUrlGenerator::getUrl()` won't do any checks on whether the file actually exists or not. 

You could add your own url generator by implementing `\Spatie\MediaLibrary\UrlGenerator\UrlGenerator` and registering it as `url_generator` in the config.

Keep in mind that if you're going to check whether a file exists every time you want to generate an URL, you'll probably experience an impact on performance.

I'd say the best solution would be to not get the thumb URL if you're not working with the correct collection, that's something you should know within the context of your project though.

**Comment by eldiddio** [comment]
Thanks for your reply Brent,

It would be good if the documentation [performing-conversions-on-specific-collection](https://docs.spatie.be/laravel-medialibrary/v7/converting-images/defining-conversions/#performing-conversions-on-specific-collections) is updated to reflect this

Docs currently say:

```php
// a thumbnail will be generated for this media item
$media = $newsItem->addMedia($pathToImage)->toMediaCollection('images');
$media->getUrl('thumb') // the url to the thubmnail

//but not for this one
$media = $newsItem->addMedia($pathToImage)->toMediaCollection('other collection');
$media->getUrl('thumb') // returns ''
```

Thanks

**Comment by brendt** [comment]
Feel free to submit a PR: https://github.com/spatie/laravel-medialibrary/tree/master/docs

👍
