### ISSUE TITLE
How to get media library photo from laravel Cache

### ISSUE THREAD

**Issue by HasanurHimel** [spatie/laravel-medialibrary#1497]
Simply Laravel Caching system we can use 

> Cache::forever('key', value)
### I've a blog model and simply i can store in cache of blogs table data .
but i want to cache media library data while i store at the time of blog create .and retrive data from cache in frontend. How can it possible

**Comment by freekmurze** [comment]
I don't understand the issue completely, I think, ... but cache things for the front end is out of scope for this package.
