### ISSUE TITLE
Supporting URLs as linked media

### ISSUE THREAD

**Issue by gabarba** [spatie/laravel-medialibrary#15]
Hi this is more of a question than anything on how easy it would be to adapt this package to store URL's of say blog posts or documents hosted on other sites. 

Does this package allow for something like that currently or will could this be something that is added in the future. I just came across this today and it looks like a more fleshed out version of what I have on a current project. On the face of it looks like it does everything I'm looking for with the exception of storing URLs instead of actual file locations.

Thanks again, this package an others you guys have look great.

**Comment by freekmurze** [comment]
This package is build for managing your own files and generating thumbnails and other derived images from them.  Storing url's to external would make the package more complex than it needs to be. 

You could create a seperate table to store url's to external sites.

**Comment by gabarba** [comment]
Thanks for the reply, I may fork your code and fiddle around with it in detail later. Right now I'm pretty much doing the same thing except instead of storing file paths i'm storing url for pretty much everything. It works but gets a little bit more complex when I start dealing with images in particular when I need to cache the image and generate and new url based on the cached size requested. The other problem I foresee in the future is not if but when I need to change the storage structure/path of locally stored files it becomes a pain to handle this. I like the concept of profiles to get different return types I may try to apply it to this package and say have a profile for urls to instead of doing some sort of transform I could just directly use the url that is stored.

**Comment by freekmurze** [comment]
We're currently creating a new version of this package. You can look at it in the "next-gen" branch. I'll see if we can add storing external url's elegantly there.
ETA for the next-gen branch to be released: somewhere  at the end of July.

**Comment by freekmurze** [comment]
Hi, unfortunately storing URL's will not be support in the next version of this package. Developing and supporting this would take us too much time.
