### ISSUE TITLE
laravel 5.2

### ISSUE THREAD

**Issue by PheRum** [spatie/laravel-medialibrary#150]
Will support laravel 5.2?

**Comment by freekmurze** [comment]
There was a problem with one of the dependencies. This has been solved. 

You should be able to install the package in L5.2 without any problems.


![screen shot 2016-01-25 at 14 45 29](https://cloud.githubusercontent.com/assets/483853/12552601/0725e836-c373-11e5-9c6c-da92f716054a.png)

**Comment by PheRum** [comment]
@freekmurze https://github.com/spatie/laravel-medialibrary/blob/master/composer.json#L23

**Comment by PheRum** [comment]
version 3.14
```
 [ErrorException]         
  Undefined index: scheme
```
dev-master all good

update your version for composer please

**Comment by freekmurze** [comment]
I fixed this is the newly tagged version 3.14.1
