### ISSUE TITLE
 Class 'Spatie\MediaLibrary\MediaLibraryServiceProvider' not found

### ISSUE THREAD

**Issue by ronssij** [spatie/laravel-medialibrary#1502]
`php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="migrations"`

It does not create a migrations files.

I followed the steps in https://github.com/spatie/laravel-medialibrary/issues/77

```
// config/app.php
'providers' => [
    ...
    Spatie\MediaLibrary\MediaLibraryServiceProvider::class,
];
```

and then I got this.

```
In ProviderRepository.php line 208:

  Class 'Spatie\MediaLibrary\MediaLibraryServiceProvider' not found

```

**Comment by freekmurze** [comment]
I'm thinking something went wrong while installing the package. Please try it in a vanilla Laravel app. Our tests indicate that the package is working fine and I was just able to install it myself in an vanilla Laravel 5.8 app.

**Comment by ronssij** [comment]
I really don't know what happened on the project I've created. What I did was:
- Install passport
- Install Spatie Query Builder
- Install Spatie Media Library

Then the errors began to show up.
What I did was I deleted the entire Laravel folder then install new Laravel project.
