### ISSUE TITLE
Is there a better way to upload multiple files at once?

### ISSUE THREAD

**Issue by GabMic** [spatie/laravel-medialibrary#1504]
I am using laravel 5.8.

I have an input that can upload multiple images:

`<input type="file" class="input" name="images[]" multiple>`

And this is how i attach the media, and it feels a bit off:

```
 foreach($request->images as $image){
       $ticket->addMedia($image)->toMediaCollection('images');
    }
```

Is there a better way?
Thanks.

**Comment by freekmurze** [comment]
Take a look at this method: https://docs.spatie.be/laravel-medialibrary/v7/api/adding-files/#addmultiplemediafromrequest
