### ISSUE TITLE
Can user wrapping his/her files in folders?

### ISSUE THREAD

**Issue by hakhsin** [spatie/laravel-medialibrary#1505]
By this package can I give user to be able to wrapping his/her files in folders?
I want to my user be able to wrapping her/his files in to folders like this structure:
user
* picture
  * private
    * image.jpg
    * image2.jpg ...
  * pic1.jpg
  * ...
* doc
  * ...

**Comment by freekmurze** [comment]
Take a look here: https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-a-custom-directory-structure/
