### ISSUE TITLE
Media specific manipulations get ignored when applying to multiple Libraries on same model

### ISSUE THREAD

**Issue by hoofdletterj** [spatie/laravel-medialibrary#1506]
Hi @freekmurze, first of all: awesome package, it's been a life saver!

One issue though: When I have a model with more than one media library, each one having the same (two) conversions, and I apply a media specific manipulation on all (first) images of a specific conversion, only the conversion of the first media library gets manipulated. 

**Example**
- I've added three libraries to a Dog: front, side and rear view. 
- On all libraries I have a "thumb" and "square" conversion.
- I've populated all three libraries with one image.
- I create a media specific manipulation (rotation) on the "square" conversion for the image in every library.

**Outcome**
- The manipulations for all the relevant items get correctly added to the database in the manipulations column.
- All three images (front/square, side/square and rear/square) get re-generated with the specified conversions.
- Only the first (front/square) is rotated.
- The other two images have a new timestamp but are unmodified relative to the initially generated image.

**The code I'm using**
(please note: this is a reproduced simplified version of a project ;) )
```
<?php

namespace App;

use Spatie\Image\Manipulations;
use Spatie\MediaLibrary\Models\Media;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Dog extends Model implements HasMedia
{
    use HasMediaTrait;

    public function registerMediaCollections()
    {
        $this
            ->addMediaCollection('front')
            ->registerMediaConversions(function (Media $media) {
                $this->addMediaConversion('square')
                    ->crop(Manipulations::CROP_CENTER, 300, 300);
                $this->addMediaConversion('thumb')
                    ->crop(Manipulations::CROP_CENTER, 600, 800);
            });
        $this
            ->addMediaCollection('side')
            ->registerMediaConversions(function (Media $media) {
                $this->addMediaConversion('square')
                    ->crop(Manipulations::CROP_CENTER, 300, 300);
                $this->addMediaConversion('thumb')
                    ->crop(Manipulations::CROP_CENTER, 600, 800);
            });
        $this
            ->addMediaCollection('rear')
            ->registerMediaConversions(function (Media $media) {
                $this->addMediaConversion('square')
                    ->crop(Manipulations::CROP_CENTER, 300, 300);
                $this->addMediaConversion('thumb')
                    ->crop(Manipulations::CROP_CENTER, 600, 800);
            });
    }

    public function doManipulations()
    {
        $images = ['front', 'side', 'rear'];

        foreach ($images as $image) {
            $item = $this->getMedia($image)->first();
            $item->manipulations = ['square' => ['orientation' => '90']];
            $item->save();
        }
    }
}
```

**Comment by freekmurze** [comment]
We recently tagged a fix for a similar problem in the underlying spatie/image package. Could you update your dependencies so you use the latest version? If you're in luck the problem should be solved, otherwise I'd welcome a PR that fixes this in the medialib.

**Comment by hoofdletterj** [comment]
Thanks for your blazing fast reply! Oof... I've updated spatie/image to v1.7.2 and spatie/laravel-medialibrary to v7.6.9 now, and still no dice.

Does this mean I'm out of luck, or could I still be missing something? Since investing in this package means a LOT of rework if those manipulations don't work. *looks worried

**Comment by freekmurze** [comment]
Currently I don't have the time to investigate and fix this myself. If you need to be fixed fast you'll have to dive in the code yourself and PR a fix with tests. Usually good PRs get merged fairly quickly.

**Comment by hoofdletterj** [comment]
Allright, despite this package seems yet to be a bit above my pay grade, I've spent most of my weekend digging around and tracing stuff. And I _might_ have found where it goes wrong.

(I'm documenting this for the community in the hopes someone has a quick fix and PR ready now the source might be a bit more clear.. I'm a bit hesitant to try and contribute to an OS project, b/c this would be my first one)

**identifying the broken code**
- `ConversionCollection::createForMedia()` is called by `FileManipulator->createDerivedFiles()` on line 33.
- Once that calls `setMedia()` -> `addManipulationsFromDb()` -> `addManipulationToConversion()` -> `addAsFirstManipulations()` on line 130 it creates the issue: 

**current outcome**
Because of the `optional($this->first(`... on line 130 it always grabs the first conversion with a certain name ("square" in my example above) and skips the rest. This results in merging the manipulation to the wrong ManipulationSequence (namely the one for the first Media object, in stead of the second or third)

**desired outcome**
Find and use the correct Conversion (and consequently its ManipulationSequence) to apply the manipulation to.

I currently have _no clue_ how to modify this. Maybe someone else has a brilliant idea? Of perhaps after reading this you're convinced you might be able to fix this in 5 seconds flat? 😉

And otherwise I'd really appreciate it if you'd attach a BUG and/or HELP NEEDED label to this issue.

Thanks again!!

**Comment by freekmurze** [comment]
We'll continue this in #1510
