### ISSUE TITLE
can't able to generate s3 URL when i had set default as s3 at the time of upload 

### ISSUE THREAD

**Issue by kalpeshtank** [spatie/laravel-medialibrary#1507]
my defult driver 
`  'default' => env('FILESYSTEM_DRIVER', 's3'),`

**Comment by brendt** [comment]
I'm afraid I don't quite understand what this issue is about. Perhaps the docs can help you? https://docs.spatie.be/laravel-medialibrary/v7/ I'd suggest carefully reading through them.

Feel free to come back to this issue with more information, but for now I'll be closing it.

**Comment by kalpeshtank** [comment]
@brendt 
ok, now it's fixed and thanks to you for a response. :)
