### ISSUE TITLE
Inherit connection from subject in FileAdder

### ISSUE THREAD

**Issue by drtheuns** [spatie/laravel-medialibrary#1511]
If I use an Eloquent model with a custom connection and want to add media to it, how do I ensure the media goes to the same connection. In this case the connection is _dynamic_, meaning overriding the Media class and setting a static connection is not a viable option.

Example:

```php
$organization = Organization::find(1);
$user = User::on($organization->connection)->find(1);

// This will try to save the media to the default connection, rather than the one on the user.
$user->addMedia($something)->toMediaCollection();
```

Perhaps we could extend the FileAdder? Maybe something like:

- Accept a beforeSave closure to modify the Media object before saving:

```
$user->addMedia($something)
     ->beforeSave(function (Media $media) {
         // edit media here...
         return $media;
     })
      ->toMediaCollection();
```

- or: explicitly set the connection:

```
$user->addMedia($something)
     ->setConnection($organization->connection)
     ->toMediaCollection();
```

- or: simply set the media connection equal to the subject connection:

```
// FileAdder::toMediaCollection
$media->setConnection($this->subject->getConnectionName());
```

How could I go about doing this?

**Comment by ixperiencenl** [comment]
@drtheuns did you manage to solve this issue?

**Comment by drtheuns** [comment]
@ixperiencenl Sorry for the late reply.

No we didn't manage to fix this issue using the media library. In the end we switched the config `database.default` while executing the `addMedia` and set it back afterwards.

Thinking about it now, it _might_ be possible to hack something together using the `withAttributes` on the `FileAdder` (and maybe Laravel's attribute mutators?). Either way, I don't see any solution built into this library for now. I still think some kind of `beforeSave` callback would be flexible enough to fulfill most use-cases.
