### ISSUE TITLE
Spatie \ MediaLibrary \ Exceptions \ FileCannotBeAdded \ FileUnacceptableForCollection

### ISSUE THREAD

**Issue by danielshongo** [spatie/laravel-medialibrary#1517]
when I delimit the file type, I get this error, but I want to catch the error in my management, but it always returns false
 public function render($request, Exception $exception)
    {

        if ($exception instanceof FileUnacceptableForCollection) {
             dd($exception);
           return redirect()->back()->with('error', 'Nous acceptons seulement le fichier gif,jpg');
        }
        return parent::render($request, $exception);
    }

**Comment by brendt** [comment]
What returns false? This check? `$exception instanceof FileUnacceptableForCollection` 

If that's the case, you either missed an import, or the exception you're catching isn't an instance of `FileUnacceptableForCollection`.

I don't think this is an issue related to the media library, so I'll be closing this issue. Feel free though to keep the conversation going if you think it's relevant.

**Comment by mahmoud-ow** [comment]
hi danielshongo, try using the correct nameaspace,  code will look like this

`
if($exception instanceof \Spatie\MediaLibrary\Exceptions\FileCannotBeAdded\FileUnacceptableForCollection){
            return redirect()->back()->with(['error' => 'Nous acceptons seulement le fichier gif,jpg']);
}
`
