### ISSUE TITLE
Media in storage vanished

### ISSUE THREAD

**Issue by Archvist** [spatie/laravel-medialibrary#1519]
Been using the media library for a over a year now, at 2 different times 2 websites launched fairly close to one-another and both have lost most of the original media the websites launched with. E.g the oldest media. 

I wanted to confirm there is no setting, or override that only allows X numbers of directories to be created, or deleted media after X months. Anything that could result in the oldest media on the site being removed. 

There is still some media on the site newer content, but oldest files had been removed. Note you can still upload media it works as expected. This is the 2nd independently hosted website this has happened too.

**Comment by freekmurze** [comment]
We are using this package in the vast majority of our projects and have never encountered the problem you are describing.
