### ISSUE TITLE
Files and directories are created ignoring umask

### ISSUE THREAD

**Issue by tontonsb** [spatie/laravel-medialibrary#1520]
I've set umask 002, so I could remove files and directories created by web server. However, the package creates 755-permission directories with 644-permission files inside.

This is probably because of utilizing Laravel's Filesystem which utilizes Flysystem, which puts either 0755 or 0700...

**Comment by freekmurze** [comment]
This package doesn’t do anything regarding setting file permissions. If you are having problems please open up an issue at either Laravel or Flysystem.

**Comment by mehdiyaq** [comment]
I have the same problem. in server permission for created folders is 755 but created folders by media library have 700 permission. the server man said it has umask problem.

**Comment by mehdiyaq** [comment]
this modification fixed the problem:

        'media' => [
            'driver' => 'local',
            'root'   => public_path('media'),
            'url'    => env('APP_URL').'/media',
            'permissions' => [
                'dir' => [
                    'public' => 0777,
                    'private' => 0755,
                ],
            ],
        ],

**Comment by francosalcedo** [comment]
> this modification fixed the problem:
> 
> ```
>     'media' => [
>         'driver' => 'local',
>         'root'   => public_path('media'),
>         'url'    => env('APP_URL').'/media',
>         'permissions' => [
>             'dir' => [
>                 'public' => 0777,
>                 'private' => 0755,
>             ],
>         ],
>     ],
> ```

Very thanks!
