### ISSUE TITLE
UI Question

### ISSUE THREAD

**Issue by asilverstein** [spatie/laravel-medialibrary#1521]
I'm sorry for asking a question you must have received hundreds of times, but is there any GUI (already-built views, components, pages, etc.) that make use of the many features offered by laravel-medialibrary? Some kind of "starter kit" perhaps? 

Thanks.

**Comment by freekmurze** [comment]
Currently there is not, but we're thinking about providing that too. No ETA though, at the minimum this is at least half a year away.
