### ISSUE TITLE
Images width is more than 4000pixels can't upload

### ISSUE THREAD

**Issue by Kyawzino** [spatie/laravel-medialibrary#1522]
Images width is more than 4000px can't upload images 
response HTTP ERROR 500
page's not woking 
how to fix it.
please reply .

**Comment by freekmurze** [comment]
I bet this is due to some constraint of your environment. Please make sure you can upload that image to your server without making use of our package. 

Google a bit around post max size and file max size settings in the php ini file.

**Comment by msassa** [comment]
I have the same problem, images larger than 4050px take a long time to perform conversions. And all the queue is delayed.
I try with an image of 4100x2000px, with a weight of 600kb and the delay is incredibly large.
While with a 4050x2000px, with a weight of 2.2Mb, the delay is 2 seconds.
The conversions I am applying is a simple resize.
Any way to avoid this? It's breaking completely my queue

**Comment by msassa** [comment]
I think this was solved changing the image driver to imagick.
https://github.com/spatie/laravel-medialibrary/issues/395#issuecomment-258824206
