### ISSUE TITLE
Cannot create video  thumbnail using extractVideoFrameAtSecond

### ISSUE THREAD

**Issue by shortcodes** [spatie/laravel-medialibrary#1529]
Hello. I want to create a video frame from video/ images mixed collection

``` 
public function registerMediaConversions(Media $media = null)
{
...
    $this->addMediaConversion('thumb')
     ->height(100)
     ->extractVideoFrameAtSecond(1)
     ->performOnCollections('gallery');
```

Video thumbnail are not being generated althougth no error occur. Urls via `getUrl('thumb')` are generated correctly but under them there are 404 errors for video files. Image files work ok. I am using simple avi files. What i do wrong?

**Comment by shortcodes** [comment]
Somebody uses it successfully?

**Comment by Shandur** [comment]
@shortcodes Hey!
I'd suggest you to check if your server(local/dev/prod) has FFMPEG and FFProbe installed.
There are lines from medialibrary.php that tells:
```
    /*
     * FFMPEG & FFProbe binaries paths, only used if you try to generate video
     * thumbnails and have installed the php-ffmpeg/php-ffmpeg composer
     * dependency.
     */
    'ffmpeg_path' => env('FFMPEG_PATH', '/usr/bin/ffmpeg'),
    'ffprobe_path' => env('FFPROBE_PATH', '/usr/bin/ffprobe'),
```

Buy I've not seen any mentions in documentation about it.
Here is a link that should help you http://ftrack.rtd.ftrack.com/en/stable/administering/managing_local_installation/configuring_ffmpeg.html

Cheers!

**Comment by shortcodes** [comment]
@Shandur Hej. Thanks for an answer. It appears I didn't have installed ffmpg. But now when it is installed nothing changed. Still got 404 where video thumbnails should be. It is weird because generating those thumbnails consumes preety much of server time. I have (for test purposes) some of video assets on AWS bucket and some on public disk but neither on AWS nor locally vide thumbnails are not being generated.

**Comment by iamsantoshyadav** [comment]
Is there any solution for that

**Comment by cpraught** [comment]
@iamsantoshyadav - not only do you have to install ffmpeg using the link above in @Shandur's answer, you ALSO need to use composer to install the php-ffmpeg/php-ffmpeg package. I had the exact same problem as above, and was only able to fix it after installing the two separate packages. Works like a charm now though!
