### ISSUE TITLE
how I can add a title and a description

### ISSUE THREAD

**Issue by danielshongo** [spatie/laravel-medialibrary#1530]
that is my codes

$admin=auth()->guard('admin')->user();
$admin->addMedia($request->avatarslider)
->toMediaCollection('sliders');

i wish to add the title and description  in database and 
in the following I will display in the view, help me please

**Comment by atymic** [comment]
You can use custom properties to add a title/description to a media item.

https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-custom-properties/

```php
$admin=auth()->guard('admin')->user();
$admin
    ->addMedia($request->avatarslider)
    ->withCustomProperties([
        'title' => 'hello',
		'description' => 'wow very image',
    ])
    ->toMediaCollection('sliders');
```
