### ISSUE TITLE
how can i  get media collection

### ISSUE THREAD

**Issue by danielshongo** [spatie/laravel-medialibrary#1531]
that is my codes

 public function index()
    {
 $avatars=articles::all()->getMedia();
dd( $avatars);
 }
but i get this error
BadMethodCallException
Method Illuminate\Database\Eloquent\Collection::getMedia does not exist.

**Comment by VincentKos** [comment]
You can't do that i beleive.

Media are associated to a model, not a collection of models. 

`articles::first()->getMedia() // this will work`

**Comment by danielshongo** [comment]
It sends me back null, but I  have the record in my table, I want to have all the colletion of my media

**Comment by danielshongo** [comment]
he send me back this 
Collection {#357 ▼
  #items: []
}

**Comment by danielshongo** [comment]
I should determined the name of my colletion, thank you, he send back the last recording, I wish to have all the colletion of the table

**Comment by danielshongo** [comment]
I found in solution with a brother(Bitfumes, https://bitfumes.com) on skype, here is the solution
   $ppp=[];
  $at=articles::all();
  Foreach($at as $article){
  $ppp[]=$article->getMedia('sliders');
}

**Comment by MrX123123** [comment]
Hi ghost, 
> in your view, loop like so:
> 
> ```
> @foreach ($articles as $article)
>   @foreach ($article->getMedia('sliders') as $image)
>   <div class="-item">
>       <img src="{{ asset($image->getUrl()) }}">
>   </div>
>   @endforeach
> @endforeach
> 
> 
> // if single image in the collection, you can just use $article->getFirstMediaUrl()

you saved my day ! Many thanks !!!

**Comment by f04d** [comment]
i think you should use **getMediaConversionNames** instead of **getMedia**


@foreach($media->getMedia() as $item)
    @foreach($item->getMediaConversionNames() as $conversion)
        <img src="{{ $item->getUrl($conversion) }}" alt="{{ $conversion }}">
    @endforeach
@endforeach
