### ISSUE TITLE
how can I extract the media in my view

### ISSUE THREAD

**Issue by danielshongo** [spatie/laravel-medialibrary#1535]
that is the codes of  my controller

  public function index(){
   	$title='With me | Home';
   	$ppp=[];
	$at=articles::all();
	Foreach($at as $article){
	$ppp[]['media']=$article->getMedia('sliders');
	$ppp[]['title']=$article->titre;
	}
   	return view('welcome',compact('title','ppp'));
   }
I want to get  {{ $media }} for all the responsive image

**Comment by freekmurze** [comment]
I don't understand the question. Here is the documentation on responsive images: https://docs.spatie.be/laravel-medialibrary/v7/responsive-images/getting-started-with-responsive-images/
