### ISSUE TITLE
Eager loading relationship and calling getMedia()

### ISSUE THREAD

**Issue by danielshongo** [spatie/laravel-medialibrary#1536]
Firstly thank you for this package, a wonderful, wonderful package. Saved me many hours and I find the quality of code in any Spatie package to be top notch!

I'm using the package in a project that manages the article, but When I come to display all  article with foreach 

   public function index(){

   	$title='With me | Home';
	$articlesget=articles::all();
	Foreach($articlesget as $article){
	$mediaslider[]['media']=$article->getMedia('sliders');
	$titreslider[]['title']=$article->titre;
	$descritslider[]['descr']=$article->description;
	}
   	return view('welcome',compact([
   		'title',
   		'mediaslider',
   		'descritslider',
   		'titreslider'
   	]));
   }
// View
@for ($i = 0; $i < count($mediaslider); $i++)
{{ $mediaslider[$i]['media'][0]->getUrl() }}
@endfor

This works fine however I am left with rather a lot of queries when I investigate using Laravel's Debugbar.

My question is, is there a way to eager load or  method rather than having so many queries?

**Comment by freekmurze** [comment]
You can eager load the media relation

https://laravel.com/docs/master/eloquent-relationships#eager-loading

**Comment by ersanyakit** [comment]
any news?
