### ISSUE TITLE
Any plans for docset integration for available documentation?

### ISSUE THREAD

**Issue by damms005** [spatie/laravel-medialibrary#1537]
Sometimes it is easier to reference documents offline. Are there any plans to make [Spatie docs](https://docs.spatie.be) available offline? (e.g. as [Docset](https://kapeli.com/docsets)?)

**Comment by vdbelt** [comment]
You could just pull down this repo, and open the docs in your preferred IDE, editor or markdown reader (/docs folder).

**Comment by damms005** [comment]
That's true; but I use a good number of Spatie's tools across my projects. So to pull down each of those repos may not be as efficient (remember it's about just briefly checking some implementation or quickly peeking at something).

Having a plan for stuff like Zeal will help in making Spatie's tools easy to use (like Vuejs and Tailwindcss, which both have Zeal's docset, btw)

**Comment by brendt** [comment]
No plans for this at the moment, if you have the source code on your machine, you also have the docs. We might look into this in the future, but that will be an issue unrelated to the media library.
