### ISSUE TITLE
Fatal error: Class name must be a valid object or a string

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-medialibrary#154]
I cannot seem to add media to a simple user model.

My code:

     auth()->user()->addMedia($request->file('file'))->toCollection('avatar');

The error im recieving:

```
FatalThrowableError in ConversionCollection.php line 64:
Fatal error: Class name must be a valid object or a string
```

Model implements HasMediaConversions, uses HasMediaTrait and has a function registerMediaConversions. Reverting the model back to default media trait without conversions does not seem to work either, same error is occurring.

What am I doing wrong?

**Comment by freekmurze** [comment]
On first glance the package doesn't seem able to figure out to which model the media should be related. Did you perform the migrations the package provides? Can you verify that the `media` table has a `model_type` column?
