### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by ashutoshSce** [spatie/laravel-medialibrary#1540]
Hello. I was planning to upgrade my project to laravel 6.0 which is also using Laravel medialibrary and it seems that spatie/laravel-medialibrary does not support Laravel 6.0.

**Comment by vdbelt** [comment]
Laravel 6.0 has not yet been released. Once it is, spatie packages will be updated to support L6.0.

**Comment by kyle-rusby** [comment]
![Alt Text](https://media.giphy.com/media/26gJAzOW1B7EdvWRG/giphy.gif)

Any ideas on a timeline for when this will be updated?

**Comment by freekmurze** [comment]
Sometime next week.
