### ISSUE TITLE
Protected properties in src/FileAdder/FileAdder.php with no getters

### ISSUE THREAD

**Issue by brobey8** [spatie/laravel-medialibrary#1541]
Hi,

I am using this package and it is working nicely, I am having to use the addAllMediaFromRequest function which as you know loops over an array of inputs in the request, building a fileAdder object for each. 

The problem is that I am wanting to get the properties of these files for adding some historical information of when they were added, their file names etc. However I cannot access any of these properties on the class as they're all protected and there are no getters.

I would like it to work like this:

        $entity->addAllMediaFromRequest()
            ->each(function ($fileAdder) use ($id) {
                Helper::createRevisionRecord(Entity::find($id), '   attachment added', '', $fileAdder->getFileName());
                $fileAdder->toMediaCollection('attachments');
            });

**Comment by brendt** [comment]
`FileAdder::toMediaCollection` returns the media item, could you read the required information from there?

**Comment by brobey8** [comment]
Thanks for the reply @brendt I didn't end up using it in this way but I have noted your comment as a way to do this in the future. Closing the issue.
