### ISSUE TITLE
Deleting a media only deletes the file, not the associated folder on S3

### ISSUE THREAD

**Issue by ziming** [spatie/laravel-medialibrary#1543]
Hi,

According to the docs, it says:

> When a Media-object gets deleted the package will **delete its entire associated directory**. To avoid tears or worse, make sure that every media gets stored its own unique directory.

I tried it (my filesystems is S3) and what happens is only the file get deleted. the associated id folder doesn't get deleted. It becomes an empty folder instead (i.e. folder 123 for media id 123 still exist but empty)

What did I do wrong?

Thank you.

**Comment by freekmurze** [comment]
I think this is a bug, i'd accept a PR that fixes this.

**Comment by Gummibeer** [comment]
The same issue is on Azure - I beliefe that this is related to the blob-storage and that they don't know directories but `Filesystem::getMediaDirectory()` creates the directory - in blob storages this will result in a normal blob.

The error is here that it only excludes the driver `name` if it's `s3`. So it doesn't exclude by the driver or does it exclude other blob storages.
https://github.com/spatie/laravel-medialibrary/blob/cd121dfc4f361324e897d894b574f4bc4fe481c3/src/Filesystem/Filesystem.php#L202-L204

**Comment by webcrazy** [comment]
I just tested this issue with my s3 and looks like working fine.

**Comment by Gummibeer** [comment]
@webcrazy what's the name of your filesystem S3 storage? Is it `s3` like the driver or something else?

**Comment by webcrazy** [comment]
@Gummibeer laravel media library driver s3. 
1. I created a bucket in amazon s3
2. I created a bucket
3. created IAM user
then I uploaded a few images associated an eloquent user. And I deleted that user and every folder inside bucket is gone. So I think it's working as expected.

**Comment by ziming** [comment]
what is the iam policy you used?

**Comment by webcrazy** [comment]
@ziming  AmazonS3FullAccess

**Comment by Gummibeer** [comment]
@webcrazy could you change the name of your storage to something else and try if it still deletes the "folder"?

**Comment by webcrazy** [comment]
@Gummibeer you mean the bucket name?

**Comment by Gummibeer** [comment]
@webcrazy no I mean the name of your filesystem storage in the Laravel config.
So in the `config/filesystems.php`.

**Comment by webcrazy** [comment]
@Gummibeer  I changed it to local, tested with a few images and still working it fine.

**Comment by ziming** [comment]
Looks like this is fixed.

**Comment by freekmurze** [comment]
I just tested this, and it seems to work for me. I guess your experiencing the issue because of a permission problem on S3.

**Comment by ziming** [comment]
@freekmurze I can confirm it is not a permission issue as I did not went back to change my S3 bucket policy. However some weeks or months after I posted this. The delete started working again

So most likely what happened is that 1 of the future updates after my issue post fixed it. So either way it can be closed :).

**Comment by vedmant** [comment]
Strangely, I'm having the same issue, `$media->delete();` returning `true`, but doesn't delete a database entry without any errors, however deletes the media file itself.

"laravel/framework": "^10.48",
"spatie/laravel-medialibrary": "^10.15",
