### ISSUE TITLE
Latest commit killed online Docs?

### ISSUE THREAD

**Issue by KMB** [spatie/laravel-medialibrary#1546]
Looks like that as of today the v7 of the docs is not available anymore:
https://docs.spatie.be/laravel-medialibrary/v7/introduction
gives me a 404.

v6 is working fine, but it's missing stuff.
https://docs.spatie.be/laravel-medialibrary/v6/introduction

**Comment by freekmurze** [comment]
Thank you for bringing this to my attention, we’ll fix this soon.

**Comment by silverqx** [comment]
Yes, v7 docs disappeard few mins ago.

**Comment by freekmurze** [comment]
@riasvdv is on it to bring back the docs. Meanwhile you could just use the /docs directory in this repo.

**Comment by chrisGeonet** [comment]
how strange. The commit to remove the docs looks intentional. There's a mention of it in the changelog too.

**Comment by riasvdv** [comment]
All back! The removal of the docs was indeed intentional for archive downloads (composer uses this) to not pollute and increase people's vendor folders too much.

We used the same archive download for generating the docs, but this change broke it, so now we use a sparse checkout instead!

**Comment by silverqx** [comment]
thx
