### ISSUE TITLE
Soft deleting

### ISSUE THREAD

**Issue by poudigne** [spatie/laravel-medialibrary#155]
Hi, I looked over the doc about soft delete, but didn't seen anything. I'm using this library and i soft delete my models, i'd like to keep the image when a models with a media collection get deleted. and delete them only when I " hard delete" the models.

Did i miss anything? Does this lib handle this behaviour ?

**Comment by freekmurze** [comment]
In the latest and greatest version of the medialibrary [a function called `deletePreservingMedia`](https://github.com/spatie/laravel-medialibrary/blob/3.14.1/src/HasMedia/HasMediaTrait.php#L308) was added that deletes only the media and leaves the files alone.

In the next major version of the package (ETA somewhere in 2016) we'll add better support for soft deletes.

**Comment by poudigne** [comment]
Awesome. thanks

**Comment by dennisoderwald** [comment]
Hi @freekmurze,

a better support for soft deletes is not added so far or not documented?

**Comment by freekmurze** [comment]
Sorry, because I don't use soft deletes myself, support for it hasn't been added.

**Comment by vesper8** [comment]
I am also really hurting to find a workaround to prevent deletion of media rows (and the media itself) when a model is softDeleted. I know you have added logic to preserve the media itself. But I want to be able to restore the media entirely. Anyone got a workaround?
