### ISSUE TITLE
How can I save just a converted media?

### ISSUE THREAD

**Issue by piterog** [spatie/laravel-medialibrary#1550]
Guys, I'm using:

```
    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('profile')
             ->width(200)
             ->performOnCollections('profile');
    }
```

But I don't wanna a original file, how can I save just a converted media?

Thank you!

**Comment by freekmurze** [comment]
This currently is not possible with the medialib. Manipulate the image to the wanted format before adding it to the medialib.

**Comment by xperator** [comment]
Any updates on this? I need the same thing where I need to save a manipulated/optimized version of original image.
I can't do any image manipulation before passing it to `addMedia`. I keep getting :
`Only strings, FileObjects and UploadedFileObjects can be imported`

Do I really need to save the manipulated image on the disk and then load it for `addMedia` and then delete it..?

**Comment by projct1** [comment]
Some problem. I dont need store fat original. Remove him manually?

**Comment by projct1** [comment]
> Manipulate the image to the wanted format before adding it to the medialib

Why manually do the work of converting an image when medialibrary ALREADY converts it as we indicated in model settings?
