### ISSUE TITLE
Prevent auto append of "media" when return eloquent

### ISSUE THREAD

**Issue by Trexology** [spatie/laravel-medialibrary#1551]
Whenever I return an eloquent object, somehow the media relation is returned together with my attribute, how can I off this auto-loading feature?

"author": {
                    "id": 1,
                    "nick_name": "master",
                    "avg_rate": null,
                    "count_rate": null,
                    "avatar": "http://localhost/storage/1/emma-not-smiling-35x45_1_orig.jpg",
                    "media": [ **<---- remove this part**
                        {
                            "id": 1,
                            "model_type": "App\\Models\\User",
                            "model_id": 1,
                            "collection_name": "avatar",
                            "name": "emma-not-smiling-35x45_1_orig",
                            "file_name": "emma-not-smiling-35x45_1_orig.jpg",
                            "mime_type": "image/jpeg",
                            "disk": "public",
                            "size": 161041,
                            "manipulations": [],
                            "custom_properties": [],
                            "order_column": 1,
                            "created_at": "2019-09-03 16:34:55",
                            "updated_at": "2019-09-03 16:34:55"
                        }
                    ],

**Comment by jodak94** [comment]
up

**Comment by irfanDC** [comment]
did you resolved ? I also facing this issue

**Comment by Elsuqui** [comment]
If you are using "getMedia", it internally uses "loadMedia", that method adds a "media" relation to the model.

My example: I was using the "getFirstMedia" method to extract the media URL, but it uses loadMedia. 

My solution:  I change it

From this:

```php

protected function getImageUrlAttribute() : string
{
    return $this->getFirstMedia('main_photo')?->getFullUrl() ?? "";
}

````
to this:

```php

protected function getImageUrlAttribute(): string
    {
        $main_photo = $this->getMediaRepository()
             ->getByCollectionName('main_photo')
             ->first();
        return $main_photo ? $main_photo->getFullUrl() : "";
    }

```

**Comment by Thinkro** [comment]
Super old issue, but using this in a SPA where Laravel just returns json, using the method e.g. $user->getFirstMediaUrl('avatar') returns the whole "media" relationship in embedded in the user.

Are there better methods to do this? what @Elsuqui proposed is quite verbose.

<img width="413" alt="Screenshot 2023-03-09 at 11 13 39" src="https://user-images.githubusercontent.com/113018109/223991021-d8870643-f0bf-4e9e-9f0f-be841fba834e.png">
