### ISSUE TITLE
not updating because of imagick

### ISSUE THREAD

**Issue by mokhosh** [spatie/laravel-medialibrary#1553]
I was using version 7.11 with Laravel 5.8 just fine. I decided to update Laravel to version 6.0 and media library to version 7.12 but now I get this error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-medialibrary ^7.12.0 -> satisfiable by spatie/laravel-medialibrary[7.12.0].
    - spatie/laravel-medialibrary 7.12.0 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
```

I also tried downloading imagick, putting the dll in my ext folder and setting the php.ini file, but the issue is still there.
Any ideas on a) why it is suddenly requiring me to install the optional imagick dependency b) how to install imagick?

**Comment by mokhosh** [comment]
ok found a hacky solution provided by @jstoone:
add this to your `composer.json`:
```json
{
    "require": {
+       "spatie/laravel-medialibrary": "^7.0.0"
    },
+   "provide": {
+       "ext-imagick": "*"
+   },
    "require-dev": {

    }
}
```

**Comment by pbgswd** [comment]
the provide statement was how I got it done today after a lot of time having this problem.

**Comment by RobertCordes** [comment]
Thanks @mokhosh. Your solution is hacky but i works :)
