### ISSUE TITLE
Disable/skip mediaconversions

### ISSUE THREAD

**Issue by prullenbak** [spatie/laravel-medialibrary#1556]
Is it possible to add media to a model and skipping the mediaconversions? I'm trying to write a feature test and I don't want to generate thumbnails etc. every time I run the tests. 

So something like $model->addMedia($media)->withoutConversions(); Or something like that?

Thanks!

**Comment by freekmurze** [comment]
Feel free to submit a PR for this. Make sure to include tests and an updated docs 👍

**Comment by prullenbak** [comment]
Lol. I wasn't trying to tell you this should be in there, just wondering :)

But maybe if I have time soon, I will try to add something. 

Thanks for this (and other) great package(s)!
