### ISSUE TITLE
[Question] Optimization tools with Laravel Vapor

### ISSUE THREAD

**Issue by okaufmann** [spatie/laravel-medialibrary#1557]
Hi,

I just started Laravel Vapor (no experience with Lambdas yet) and ask myself how to use medialibrary's optimisation tools (https://docs.spatie.be/laravel-medialibrary/v7/installation-setup/#optimization-tools). 

I think these can't be installed in a Lambda Function (not tested yet though). 

Are there any other Vapor Users, thought about this?

**Comment by ArjenNZ** [comment]
I used this and it's working fine for now :) 

https://github.com/ysugimoto/aws-lambda-image
