### ISSUE TITLE
Other File Types

### ISSUE THREAD

**Issue by davidbankes** [spatie/laravel-medialibrary#156]
We want to be able to add other files types. I know this can be done by extending the model (which we've done successfully), but it appears to me that the conversion process will error out. On FileManipulator::createDerivedFiles, it looks like any added file type specified in our Media extension would go through to attempt conversion, and probably cause an error.

Ideally we'd like to be able to have a file have multiple file types, but that's a whole different can o' worms.

**Comment by freekmurze** [comment]
The file types are indeed uses by the package to determine which manipulations can be performed on it. 
If you need to add your own file types you could just save [a custom property](http://medialibrary.spatie.be/v3/advanced-usage/adding-custom-properties/) on an instance of `App\Models\Media`.
