### ISSUE TITLE
Imagick dependency and Laravel Vapor

### ISSUE THREAD

**Issue by patrickomeara** [spatie/laravel-medialibrary#1563]
I've just tried to update to `v7.12.1` where the dependency for imagick has been removed.

https://github.com/spatie/laravel-medialibrary/commit/2382f0d23d00991e87581c084b801cd93cfb55c1

Imagick is still required in `spatie/pdf-to-image` I've forked `laravel-medialibrary` to try to decouple that dependency as per your comment on https://github.com/spatie/laravel-medialibrary/issues/1480#issuecomment-511309245

However this looks like a BC issue for `v7.*`. 

I'm wondering what the plan is to get to `v8.*` of `laravel-medialibrary`, do you see this being a big release with many new features as per the label https://github.com/spatie/laravel-medialibrary/issues?utf8=%E2%9C%93&q=label%3A%22revisit+for+next+major+version%22+ or is it possible there could be a smaller release to move this dependency on `pdf-to-image` back out of `requirements` and into `suggests`?

I'm trying to get my app ready for Vapor and this is a blocker at the moment, I'm happy to use the solution that @jstoone suggested https://github.com/spatie/laravel-medialibrary/issues/1480#issuecomment-516918009 but I believe this dependency issue needs to be addressed properly. 

I'm currently on `v7.6.3` with no dependency on `imagick` but this doesn't support Laravel 6. I'm trying to find the reason the dependency was added in a patch release, maybe @brendt can shed some light?

```
 Problem 1
    - Installation request for spatie/pdf-to-image 1.8.2 -> satisfiable by spatie/pdf-to-image[1.8.2].
    - spatie/pdf-to-image 1.8.2 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
  Problem 2
    - spatie/pdf-to-image 1.8.2 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
    - spatie/laravel-medialibrary 7.12.1 requires spatie/pdf-to-image ^1.2 -> satisfiable by spatie/pdf-to-image[1.8.2].
    - Installation request for spatie/laravel-medialibrary 7.12.1 -> satisfiable by spatie/laravel-medialibrary[7.12.1].
```

**Comment by Houbsi** [comment]
Hi @patrickomeara 
> PHP extension imagick is missing from your system
shows that you have to install imagick as a php extension and stuff.

if you install poppler-utils it fixed the issue for me

`sudo apt install poppler-utils`

**Comment by ceejayoz** [comment]
@Houbsi Vapor is serverless. IIRC, they recently added imagick to the builds, but you won't be able to install stuff via apt.

**Comment by Houbsi** [comment]
Sorry @ceejayoz i overread the point of vapor. Have not yet the time and money to get into vapor ;)
So if i understand you currectly, this issue is with a current build on vapor not there anymore?

**Comment by ceejayoz** [comment]
@Houbsi I believe this issue is resolved in Vapor. Imagick was added 22 days ago: https://github.com/laravel/vapor-php-build/commit/95abc4446af16f13bf964893f49dd26f7d4359ae
