### ISSUE TITLE
Backup of S3 files

### ISSUE THREAD

**Issue by elwin** [spatie/laravel-medialibrary#1565]
Hi there! This is a question rather than an issue.

I'm currently using medialibrary to store images on DigitalOcean Spaces and figuring out a way to keep them backed up.

I was thinking of storing the files simultaneously to two different storage systems, e.g. DO spaces + AWS S3 (essentially a mirror) but reading only from one, however, this doesn't protect me from errors made from my side (e.g. accidentally delete all files from the app).

What approaches do you take?

**Comment by freekmurze** [comment]
This question is out of scope of the medialibrary. Implementing a backup strategy is your responsability, the package doesn't take care of this.

I think you can enable some kind of backup on S3 itself.
