### ISSUE TITLE
Not installing on Laravel 6

### ISSUE THREAD

**Issue by daugaard47** [spatie/laravel-medialibrary#1567]
I'm trying to install this package with a Fresh install of Laravel 6. 

Tried with version 7.12.0: `composer require "spatie/laravel-medialibrary:^7.12.0"` as it mentions "add support for Laravel 6".

I get the following error.

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Symfony\Component\Debug\Exception\FatalThrowableError  : Class name must be a valid object or a string

  at D:\laragon\www\mysite\vendor\spatie\laravel-medialibrary\src\MediaLibraryServiceProvider.php:33
    29|         ], 'views');
    30|
    31|         $mediaClass = config('medialibrary.media_model');
    32|
  > 33|         $mediaClass::observe(new MediaObserver());
    34|
    35|         $this->loadViewsFrom(__DIR__.'/../resources/views', 'medialibrary');
    36|     }
    37|

  Exception trace:

  1   Spatie\MediaLibrary\MediaLibraryServiceProvider::boot()
      D:\laragon\www\mysite\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  2   call_user_func_array([])
      D:\laragon\www\mysite\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```
Can anyone help me solve this issue so I can get it up and going? Any help would be appreciated.

**Comment by francoism90** [comment]
Works fine here on Laravel 6.0, maybe the vendor directory has been corrupted. Could you try again in a clean copy?

**Comment by tnorthcutt** [comment]
I am running into this same problem. @francoism90 what do you mean by "vendor directory has been corrupted"? 

@daugaard47 Were you able to get this fixed?

**Comment by daugaard47** [comment]
@tnorthcutt No, I ran a new clean install of laravel and still ran into the exact same problem again. Really have no idea why this is happening. If you figure it out, please let me know what you did to get it working and I'll do the same.

**Comment by tnorthcutt** [comment]
@daugaard47 Will do. I tried on a clean install of Laravel and had success there... but in my app, I did `rm -rf ./vendor && rm -rf composer.lock`, then tried `composer install` and ran into the same problem 🙁

**Comment by tnorthcutt** [comment]
@freekmurze I would love to help solve this! Can you provide any guidance on how I can debug, what information would be helpful, etc.?

**Comment by SvanThuijl** [comment]
In the MediaLibraryServiceProvider the config does not seem to load directly after publishing. I did publish the config file manually by copying the file and cleared my config cache manually by removing the bootstrap/cache/config.php.

Running composer dump-autoload and the issue is resolved.

**Comment by heagueron** [comment]
I am also experimenting trouble installing the package on Laravel 6.

PS C:\Users\luise\laravel\event_backend> composer require "spatie/laravel-medialibrary:^7.0.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-medialibrary 7.0.0 -> satisfiable by spatie/laravel-medialibrary[7.0.0].
    - Conclusion: remove laravel/framework v6.0.3
    - Conclusion: don't install laravel/framework v6.0.3
    - spatie/laravel-medialibrary 7.0.0 requires illuminate/database ~5.5.0|~5.6.0 -> satisfiable by illuminate/database[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/database 5.5.x-dev|don't install laravel/framework v6.0.3
    - don't install illuminate/database 5.6.x-dev|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.0|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.16|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.17|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.2|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.28|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.33|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.34|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.35|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.36|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.37|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.39|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.40|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.41|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.43|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.5.44|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.0|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.1|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.10|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.11|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.12|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.13|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.14|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.15|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.16|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.17|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.19|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.2|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.20|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.21|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.22|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.23|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.24|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.25|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.26|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.27|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.28|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.29|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.3|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.30|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.31|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.32|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.33|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.34|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.35|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.36|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.37|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.38|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.39|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.4|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.5|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.6|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.7|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.8|don't install laravel/framework v6.0.3
    - don't install illuminate/database v5.6.9|don't install laravel/framework v6.0.3
    - Installation request for laravel/framework (locked at v6.0.3, required as ^6.0) -> satisfiable by laravel/framework[v6.0.3].


Installation failed, reverting ./composer.json to its original content.
PS C:\Users\luise\laravel\event_backend>

**Comment by ssmusoke** [comment]
Running in the same issue on Mojave, PHP 7.2.12, composer 1.7.3 

"require": {
        "php": "^7.2",
        "facade/ignition": "^1.6",
        "fideloper/proxy": "^4.0",
        "intervention/image": "~2.4",
        "laravel/framework": "^6.0",
        "laravel/nova": "^2.3",
        "laravel/tinker": "^1.0",
        "league/flysystem-aws-s3-v3": "^1.0",
        "spatie/laravel-fractal": "^5.6",
        "spatie/laravel-medialibrary": "^7.0.0",
        "tymon/jwt-auth": "dev-develop"
    },

**Comment by francoism90** [comment]
I didn't had trouble with this package, but I remember having the same issue with other packages that should be compatible with Laravel 6. Anyway, a workaround is to remove them (backup/commit project first!), upgrade to Laravel 6 and finally reinstall the missing packages. Also use `composer outdated` to check out-of-dated packages, before trying to upgrade to Laravel 6.

**Comment by tnorthcutt** [comment]
@francoism90 In my case, the app was already on Laravel 6 (and was started on Laravel 6), so there's nothing to upgrade 😕 .

If it helps anyone debugging this, this line in `MediaLibraryServiceProvider::boot()` returns `null`:         
```
$mediaClass = config('medialibrary.media_model');
```

**Comment by tnorthcutt** [comment]
I was finally able to get this working by commenting out most of `MediaLibraryServiceProvider::boot()` (except for the `$this->publishes()` portion at the top), then publishing the config file, then running `artisan config:clear`. Then, I was able to delete the published config file, uncomment the `boot()` method, and things still worked. Hopefully that's helpful to someone.

**Comment by riasvdv** [comment]
I can't reproduce this on a fresh Laravel 6 install (^6.2 in composer), maybe something was fixed to solve this in the Laravel release.

**Comment by devilstars** [comment]
Same error here:
```
Symfony\Component\Debug\Exception\FatalThrowableError  : Class name must be a valid object or a string

at C:\laragon\www\bggg\vendor\spatie\laravel-medialibrary\src\MediaLibraryServiceProvider.php:33
    29|         ], 'views');
    30|
    31|         $mediaClass = config('medialibrary.media_model');
    32|
  > 33|         $mediaClass::observe(new MediaObserver());
    34|
    35|         $this->loadViewsFrom(__DIR__.'/../resources/views', 'medialibrary');
    36|     }
    37|

Exception trace:

1   Spatie\MediaLibrary\MediaLibraryServiceProvider::boot()
      C:\laragon\www\bggg\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

2   call_user_func_array([])
      C:\laragon\www\bggg\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

Please use the argument -v to see more details.
```

Clean laravel 6.2 installation.

@SvanThuijl's solution helped to solve it.

**Comment by ManukMinasyan** [comment]
I have the same error with laravel 6.2.

**Comment by kevinmakwana** [comment]
I have the same error with laravel 6.2.

**Comment by amirasyraf** [comment]
Experiencing the same error on Laravel 6.2

**Comment by CharlyZA** [comment]
> In the MediaLibraryServiceProvider the config does not seem to load directly after publishing. I did publish the config file manually by copying the file and cleared my config cache manually by removing the bootstrap/cache/config.php.
> 
> Running composer dump-autoload and the issue is resolved.

This worked perfectly for me with Laravel v6.5.1. Thank you so much

**Comment by waitaamon** [comment]
Experiencing the same in laravel 6.2. tried solutions above but none worked

**Comment by MfundoM** [comment]
I installed a new project 
composer create-project --prefer-dist laravel/laravel project_name
and then ran spatie, and it worked.

**Comment by dev4indglobal** [comment]
> bootstrap/cache/config.php

worked for me.
thanks @SvanThuijl

**Comment by RomkaLTU** [comment]
Same problem.

**Comment by artifex-media** [comment]
Same problem.

**Comment by artifex-media** [comment]
> In the MediaLibraryServiceProvider the config does not seem to load directly after publishing. I did publish the config file manually by copying the file and cleared my config cache manually by removing the bootstrap/cache/config.php.
> 
> Running composer dump-autoload and the issue is resolved.

Can you clarify which file is 'the config file' we have to manually copy? 

> In the MediaLibraryServiceProvider the config does not seem to load directly after publishing. I did publish the config file manually by copying the file and cleared my config cache manually by removing the bootstrap/cache/config.php.
> 
> Running composer dump-autoload and the issue is resolved.

Worked for me.
@riasvdv This issue is still present, even on the latest Laravel version.

**Comment by kopiiez** [comment]
Symfony\Component\Debug\Exception\FatalThrowableError  : Class name must be a valid object or a string

  at C:\Feyverly\feyverly-plan-svc\vendor\spatie\laravel-medialibrary\src\MediaLibraryServiceProvider.php:33
    29|         ], 'views');
    30|
    31|         $mediaClass = config('medialibrary.media_model');
    32|
  > 33|         $mediaClass::observe(new MediaObserver());
    34|
    35|         $this->loadViewsFrom(__DIR__.'/../resources/views', 'medialibrary');
    36|     }
    37|

  Exception trace:

  1   Spatie\MediaLibrary\MediaLibraryServiceProvider::boot()
      C:\Feyverly\feyverly-plan-svc\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  2   call_user_func_array([])
      C:\Feyverly\feyverly-plan-svc\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

I'm try to run composer dump-autoload but still same problem

**Comment by irfanm96** [comment]
@SvanThuijl 's solution worked for me as well.

**Comment by Mekaeil** [comment]
> In the MediaLibraryServiceProvider the config does not seem to load directly after publishing. I did publish the config file manually by copying the file and cleared my config cache manually by removing the bootstrap/cache/config.php.
> 
> Running composer dump-autoload and the issue is resolved.

Thanks @SvanThuijl

**Comment by jaap** [comment]
I had the same issue when upgrading from 7 to 8.
The config file has been renamed from `medialibrary.php` to `media-library.php`.
I got it fixed by commenting everything in the `boot` function within
`vendor/spatie/laravel-medialibrary/src/MediaLibraryServiceProvider.php`
After that run `php artisan config:clear`
Then uncomment and run `compser dump-autolad`.

I think this would al not be necessary if you'd clear your config just before updating.

**Comment by VitaliyPetroff** [comment]
1. Manualy create /config/media-library.php
2. Fill it with data from repo laravel-medialibrary/config/media-library.php
3. Remove the bootstrap/cache/config.php
2. Run php artisan optimize

And it works, for me.

**Comment by Naceflynda** [comment]
Using version ^2.6 for gloudemans/shoppingcart
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gloudemans/shoppingcart ^2.6 -> satisfiable by gloudemans/shoppingcart[2.6.0].
    - Conclusion: remove laravel/framework v7.16.1
    - Conclusion: don't install laravel/framework v7.16.1
    - gloudemans/shoppingcart 2.6.0 requires illuminate/events 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.*|| 5.6.* || 5.7.* -> satisfiable by illuminate/events[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - don't install illuminate/events 5.4.x-dev|don't install laravel/framework v7.16.1
    - don't install illuminate/events 5.5.x-dev|don't install laravel/framework v7.16.1
    - don't install illuminate/events 5.6.x-dev|don't install laravel/framework v7.16.1
    - don't install illuminate/events 5.7.17|don't install laravel/framework v7.16.1
    - don't install illuminate/events 5.7.18|don't install laravel/framework v7.16.1
    - don't install illuminate/events 5.7.19|don't install laravel/framework v7.16.1
    - don't install illuminate/events 5.7.x-dev|don't install laravel/framework v7.16.1
    - don't install illuminate/events v5.4.0|don't install laravel/framework v7.16.1
    - don't install illuminate/events v5.4.13|don't install laravel/framework v7.16.1
    - don't install illuminate/events v5.4.17|don't install laravel/framework v7.16.1

**Comment by Naceflynda** [comment]
Using version ^2.6 for gloudemans/shoppingcart
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gloudemans/shoppingcart ^2.6 -> satisfiable by gloudemans/shoppingcart[2.6.0].
    - Conclusion: remove laravel/framework v7.16.1
    - Conclusion: don't install laravel/framework v7.16.1
    - gloudemans/shoppingcart 2.6.0 requires illuminate/events 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.*|| 5.6.* || 5.7.* -> satisfiable by illuminate/events[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - don't install illuminate/events 5.4.x-dev|don't install laravel/framework v7.16.1
    - don't install illuminate/events 5.5.x-dev|don't install laravel/framework v7.16.1
    - don't install illuminate/events 5.6.x-dev|don't install laravel/framework v7.16.1
    - don't install illuminate/events 5.7.17|don't install laravel/framework v7.16.1
    - don't install illuminate/events 5.7.18|don't install laravel/framework v7.16.1
    - don't install illuminate/events 5.7.19|don't install laravel/framework v7.16.1
    - don't install illuminate/events 5.7.x-dev|don't install laravel/framework v7.16.1
    - don't install illuminate/events v5.4.0|don't install laravel/framework v7.16.1
    - don't install illuminate/events v5.4.13|don't install laravel/framework v7.16.1
    - don't install illuminate/events v5.4.17|don't install laravel/framework v7.16.1

**Comment by bsam2019** [comment]
If you are getting the error in deployment, delete the config in the cache by doing the following;

sudo rm (YOU PROJECT PATH HERE)/bootstrap/cache/config.php

on ubuntu server
This solved my problem
