### ISSUE TITLE
Cannot save big file

### ISSUE THREAD

**Issue by eroslover** [spatie/laravel-medialibrary#1568]
I faced out with a problem that I can't save a big file because the file size value is out of range for type integer.
I understand that I can write additional migration with `$table->unsignedBigInteger('size')->change();`
But why don't you change `$table->unsignedInteger('size')` to `$table->unsignedBigInteger('size')` in migration stab?

**Comment by freekmurze** [comment]
You are the first one to report this, so not too many people have use the medialib with such large files.

I've updated the migration.

If you see further improvements, feel free to PR them.
