### ISSUE TITLE
Support for media library folder per model

### ISSUE THREAD

**Issue by cre8websolutions** [spatie/laravel-medialibrary#157]
As of now, all media is stored under one folder.
This package would be much better and much more flexible if you could specify custom paths for every user for example, or another desired model.

Example:
```
/users/12345678/media/1/filename.jpg
/users/12345678/media/2/filename.jpg
/users/87654321/media/1/filename.png
```

Where `/users/12345678/media/` is your own specified path per user model.

Any ideas when this will get supported, or if there is a flexible workaround?

At least being able to specify multiple media root folders would be very helpful.

**Update:**
Would it be a proper workaround to use `collection_name` for this?
Then `collection_name` would get the model's media key. (`12345678` in my case)
I could then make a custom route with the model's media key as a parameter, and query the media with `collection_name = 12345678`.
Any ideas?

**Comment by freekmurze** [comment]
Take a look at the documentation about [using a custom directory structure](http://medialibrary.spatie.be/v3/advanced-usage/using-a-custom-directory-structure/).

**Comment by tristanbailey** [comment]
Just to add an updated link for future help, as the docs moved:
https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/using-a-custom-directory-structure
