### ISSUE TITLE
Return value of XYZ::getFallbackMediaPath() must be of the type string, null returned

### ISSUE THREAD

**Issue by NKDM44** [spatie/laravel-medialibrary#1572]
In HasMediaTrait.php:

Line: 283: return optional -> null, but function expects string
    public function getFallbackMediaPath(string $collectionName = 'default') **: string**
    {
        return optional($this->getMediaCollection($collectionName))->fallbackPath;
    }

That wasn't intended, right?

**Comment by freekmurze** [comment]
This has been fixed in the latest version.
