### ISSUE TITLE
Responsive images being deleted.

### ISSUE THREAD

**Issue by Nathanw** [spatie/laravel-medialibrary#1574]
Issue with responsive image conversions being deleted if the name contains the word of another conversion e.g. `large` and `x-large`. If `x-large` is defined before `large` when running the conversion for `large` it will delete the `x-large` conversions. I believe this is because of this code: `return Str::contains($path, $conversionName);` in [Filesystem@removeResponsiveImages:133](https://github.com/spatie/laravel-medialibrary/blob/master/src/Filesystem/Filesystem.php#L133).

**Comment by rubenvanassche** [comment]
Hi @Nathanw 

I tried to reproduce your issue but the images still exist.

I have a User:
```php
class User extends Authenticatable implements HasMedia
{
    use HasMediaTrait;

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('grey-large')
            ->greyscale()
            ->withResponsiveImages();

        $this->addMediaConversion('large')
            ->withResponsiveImages();
    }
}
```

And a test:

```php
public function testBasicTest()
{
    /** @var \App\User $user */
    $user = factory(User::class)->create();

    $user->addMedia(public_path('image.png'))
        ->preservingOriginal()
        ->toMediaCollection();

    Artisan::call('medialibrary:regenerate --only=large');

    dd($user->media);
}
```

When looking into the `public/1/responsive-images` directory I can find conversation for large and grey-large. 

Could you please tell me what I need to change so my grey-large conversions would be deleted?

**Comment by Nathanw** [comment]
@rubenvanassche will take a look at this tomorrow and get back to you with a reproducible test.

**Comment by Nathanw** [comment]
Hey @rubenvanassche if you run your tests again but use the s3 driver you should see it remove the "grey-large" responsive images. This could be with how s3 matches file names but i'm not sure.

**Comment by rubenvanassche** [comment]
Hi @Nathanw,

I just ran the test i've written above on s3 and still have both the `large` and `grey-large` images. Can you provide your failing test?
