### ISSUE TITLE
Laravel 6, error on adding with composer require

### ISSUE THREAD

**Issue by pbgswd** [spatie/laravel-medialibrary#1578]
Using laradock, Laravel 6, seems to be an issue here when adding package with composer require spatie/laravel-medialibrary

laradock@084ffc0ed756:/var/www/fresh/laravel$ composer require spatie/laravel-medialibrary
Using version ^7.14 for spatie/laravel-medialibrary
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing spatie/pdf-to-image (1.2.2): Loading from cache
  - Installing myclabs/php-enum (1.7.2): Loading from cache
  - Installing maennchen/zipstream-php (1.2.0): Loading from cache
  - Installing spatie/laravel-medialibrary (7.14.1): Loading from cache
spatie/laravel-medialibrary suggests installing league/flysystem-aws-s3-v3 (Required to use AWS S3 file storage)
spatie/laravel-medialibrary suggests installing php-ffmpeg/php-ffmpeg (Required for generating video thumbnails)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Symfony\Component\Debug\Exception\FatalThrowableError  : Class name must be a valid object or a string

  at /var/www/fresh/laravel/vendor/spatie/laravel-medialibrary/src/MediaLibraryServiceProvider.php:33
    29|         ], 'views');
    30| 
    31|         $mediaClass = config('medialibrary.media_model');
    32| 
  > 33|         $mediaClass::observe(new MediaObserver());
    34| 
    35|         $this->loadViewsFrom(__DIR__.'/../resources/views', 'medialibrary');
    36|     }
    37|

  Exception trace:

  1   Spatie\MediaLibrary\MediaLibraryServiceProvider::boot()
      /var/www/fresh/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  2   call_user_func_array([])
      /var/www/fresh/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by freekmurze** [comment]
I'm able to install the package in a fresh copy of Laravel.

I'm not a Laradock user, so haven't tested it with that.

I'd accept a PR that fixes this for Laradock users.

**Comment by pbgswd** [comment]
@freekmurze I must admit I am stumped by this one. I did all the commands with composer and artisan to clear out bad states in Laravel. I asked a peer about it as well and he only said it looks to be happening really early in the execution cycle. It may have been caused by something else that I have not figured out yet.

**Comment by tpra** [comment]
Happened here too. Solved by hand-deleting laravel's cache files in bootstrap/cache.
