### ISSUE TITLE
Error when uploading to cloudinary

### ISSUE THREAD

**Issue by oluwajubelo1** [spatie/laravel-medialibrary#1579]
Good day @freekmurze ,
I got this error message when trying to upload files to cloudinary, feof() expects parameter 1 to be resource, null given. The error message shows me a snippet of where the issue is coming from, it's from :
vendor\spatie\laravel-medialibrary\src\Filesystem\Filesystem.php
while (! feof($stream)) {
            $chunk = fread($stream, 1024);
            fwrite($targetFileStream, $chunk);
        }

Thanks.

**Comment by freekmurze** [comment]
Seems like the error is occuring somewhere in the Filesystem layer. To work with external filesystems the package just used Laravel filesystem abstraction, which uses Flysystem under the hood.

For issue around this, open an issue at the tracker of flysystem or the flysystem driver you are using.
