### ISSUE TITLE
Support for querying collections with a regular expression

### ISSUE THREAD

**Issue by cre8websolutions** [spatie/laravel-medialibrary#158]
It would be helpful if you could retrieve all media of a specific `collection_name` with a regular expression.
This way you could easily manage a virtual folder structure.

Example:
```
$user->getMedia('invoices/*');
$user->getMedia('invoices.*');
$user->getMedia('projects.{name-of-category}.*');
```

**Comment by freekmurze** [comment]
Although it's a cool idea, I don't think many users of the package will need this functionality.

If you want this, implement it in your own application.
