### ISSUE TITLE
Use two different media tables

### ISSUE THREAD

**Issue by VitoScarangella** [spatie/laravel-medialibrary#1580]
I'm sharing the same database for two different laravel application, but i want to split media table one for each application. I'd like to call the second one as "ge_media" and from that application handle all the uploads and settings for that particular media table.

**Comment by freekmurze** [comment]
Out of the box the medialibrary doesn't support this behaviour. What you could do is use custom models. On a model you can specify which db table should be used (this is handled by Laravel).

In the config file of the medialibrary you can specify the model to be used. You can dynamically change this value in your code.
