### ISSUE TITLE
Unsupported image type. GD driver is only able to decode JPG, PNG, GIF or WebP files

### ISSUE THREAD

**Issue by ixperiencenl** [spatie/laravel-medialibrary#1584]
When trying to upload files like PDF's, DOCX or MPEG4, I always get this error. The upload is completed but this error pops up.

PDF's aren't being generated but DO upload. 

I already tried a custom Generator, but it looks like the MediaLibrary doesn't take this into account.
The error comes from Intervention\Image\Exception\NotReadableException and gives this because the file extension isn't correct according to this. But when I add a custom generator it looks like that is being ignored...

Please help, already took a day from my time to try to fix this... :(

Also, when I do a regeneration of the files, the PDF's show up. Uploading images works fine.

I work on Ubuntu 18.04 and have the libraries needed installed.

**Comment by ixperiencenl** [comment]
Looks like no one has or had this problem?

**Comment by Treggats** [comment]
I've messaged you in Slack, but also posting here to keep everyone up to date on the progress.

This package is, as far as I can see, for images only. So there is no support for non images like a pdf.
When dealing with pdf's I'd suggest using the [pdf-to-image](https://github.com/spatie/pdf-to-image) package to create an image from your pdf and then use Medialibrary to create a thumbnail.

**Comment by ixperiencenl** [comment]
PDF generating does work when running the **regenerate** command. Also, in the documentation it states: "The PDF generator requires Imagick and Ghostscript. If you’re running into issues with Ghostscript have a look at issues regarding Ghostscript."

**Comment by Houbsi** [comment]
The mediaconversion can be done automatically.
But i suppose that your error maybe coming from one of the filetypes.
Did you manage to get one of the file types working? I would start trying one filetype and checking if it worked. And then go further.

**Comment by freekmurze** [comment]
By default, the media library can generate thumbnails for images and PDFs.

If something works on the cli, but not during a webrequest, then it's probably caused by a discrepancy between the configuration of the PHP CLI and the PHP that handles web requests. Make sure both environments have access to Imagick and Ghostscript.

**Comment by Treggats** [comment]
@Houbsi @freekmurze this was resolved a while ago by my colleague. But this issue wasn't updated unfortunately.

Our app was trying to generate a thumbnail for non image/pdf files and we worked around this.

Thanks for closing @freekmurze

**Comment by e-hop** [comment]
+1 i'm facing this error          "intervention/image": "^2.5",

**Comment by xlcrr** [comment]
Same error here v2.6.1 when uploading from iOS

**Comment by devmount** [comment]
Same error here when uploading SVGs (current Laravel 10).

> Unsupported image type image/svg+xml. GD driver is only able to decode JPG, PNG, GIF, BMP or WebP files.

The SVG actually does get uploaded, but this error is thrown.

**Comment by snaix93** [comment]
I've installed the latest version of laravel ignition package by spatie and it fixed the issue in my case.

`composer require spatie/laravel-ignition 2.1.3`
