### ISSUE TITLE
Conversionfolder not creating

### ISSUE THREAD

**Issue by cfreak** [spatie/laravel-medialibrary#159]
Hey,

i have a system (Laravel 5.1) running on many different servers, and on one server, there is all working fine, but the conversions folder and file didn't get generated. GD and Imagick is installed. Do you have any idea why?

Best Regards
Max

**Comment by freekmurze** [comment]
Are you using queuesto generate converions? And if so, are your queues running?

**Comment by cfreak** [comment]
yeah, thanks! Now it's running again.
