### ISSUE TITLE
Delete function removes to much

### ISSUE THREAD

**Issue by adminfriso** [spatie/laravel-medialibrary#1592]
When calling the delete function on the media eventually in Filesystem.php the removeAllFiles method is called. Here the complete directory with its contents is deleted.
When overriding the default behaviour for path generation there are cases that there is other content in the directory of the media that is deleted.
EG, for the scouts group i developed a photo book (going opensource soon ;) ). here the media is stored in the original directory structure. 1 folder with all files of that activity. when deleting 1 file the complete folder with the other content is also removed.

**Comment by freekmurze** [comment]
That behaviour is documented. See last paragraph here: https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-a-custom-directory-structure/

**Comment by adminfriso** [comment]
Do you have any suggestions to let this work in my case?
