### ISSUE TITLE
php artisan medialibrary:regenerate --only-missing on S3 driver using minio

### ISSUE THREAD

**Issue by jariesdev** [spatie/laravel-medialibrary#1595]
Hi, first of all thank you for your wonderful work with this package. 

I have an issue regarding `php artisan medialibrary:regenerate --only-missing` command it appears that not checking if the file already exists and once run it updates all conversions. I can check because all timestamp has been updated and taking lots of time to finish

**Comment by freekmurze** [comment]
Can you PR a failing test for us to fix?

**Comment by AbdullahFaqeir** [comment]
@freekmurze this issue still exists, when trying to regenerate the missing conversions it regenerates all the images which accordingly takes a lot of time.

**Comment by bzarzuela** [comment]
I have the same issue right now. The --only-missing flag does not seem to work. I'm storing my media on an S3-compatible storage provider: Cloudflare R2.
