### ISSUE TITLE
Cannot install the package with laravel 6.2

### ISSUE THREAD

**Issue by MelimeliDev** [spatie/laravel-medialibrary#1599]
Problem 1
- Installation request for spatie/laravel-medialibrary 7.0.0 -> satisfiable by 
spatie/laravel-medialibrary[7.0.0].
- Conclusion: remove laravel/framework v6.3.0
- Conclusion: don't install laravel/framework v6.3.0
- spatie/laravel-medialibrary 7.0.0 requires illuminate/bus ~5.5.0|~5.6.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev]
- don't install illuminate/bus v5.6.35|don't install laravel/framework v6.3.0  
- Installation request for laravel/framework (locked at v6.3.0, required as ^6.2) -> satisfiable by laravel/framework[v6.3.0].

my laravel is actually version 6.2, please help :D

**Comment by zohaibhassan156** [comment]
Same problem with Laravel 6.3

**Comment by elnurxf** [comment]
Same here
Installation request for laravel/framework (locked at v5.8.35, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.35].

**Comment by freekmurze** [comment]
I'm able to install the package in the newest version of Laravel.

How you tried installing it in a vanilla copy of Laravel?

**Comment by MelimeliDev** [comment]
I just tried again with a fresh vanilla copy of laravel 6.4.0 (laravel new ...)
Failed again, same error.

Problem 1
    - Installation request for spatie/laravel-medialibrary 7.0.0 -> satisfiable by spatie/laravel-medialibrary[7.0.0].
    - Conclusion: remove laravel/framework v6.4.0
    - Conclusion: don't install laravel/framework v6.4.0
    - spatie/laravel-medialibrary 7.0.0 requires illuminate/database ~5.5.0|~5.6.0 -> satisfiable by illuminate/database[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/database 5.5.x-dev|don't install laravel/framework v6.4.0
....
- don't install illuminate/database v5.6.9|don't install laravel/framework v6.4.0
    - Installation request for laravel/framework (locked at v6.4.0, required as ^6.2) -> satisfiable by laravel/framework[v6.4.0].

**Comment by freekmurze** [comment]
@rubenvanassche can you try to recreate this?

**Comment by elnurxf** [comment]
Able to install without specified version by:
composer require spatie/laravel-medialibrary

It's automatically detects and installs version ^7.14
