### ISSUE TITLE
vendor:publish not publishing in 5.1

### ISSUE THREAD

**Issue by DraperStudio** [spatie/laravel-medialibrary#16]
I am testing your version from the next-gen branch at the moment and the config and migration don't get published unless I do a little change in the ServiceProvider even though I get a success message on publishing.

I have to change the `$this->app->configPath` and `$this->app->basePath` to `config_path` and `database_path`.

```
__DIR__.'/../resources/config/laravel-medialibrary.php' => $this->app->configPath('laravel-medialibrary.php'),
__DIR__.'/../resources/config/laravel-medialibrary.php' => config_path('laravel-medialibrary.php'),
```

```
__DIR__.'/../resources/migrations/create_media_table.php' => $this->app->basePath('database/migrations/'.$timestamp.'_create_media_table.php'),
__DIR__.'/../resources/migrations/create_media_table.php' => database_path('migrations/'.$timestamp.'_create_media_table.php'),
```

**Comment by freekmurze** [comment]
Thanks for letting me now. I'll be sure to check and fix this issue before the new version gets released.

**Comment by freekmurze** [comment]
This has been fixed. v2.0.0 has been tagged.

If you have a next-gen version installed, please step through the installation instructions again, we've moved some classes.
