### ISSUE TITLE
passing paramaters to registerMediaConversions

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#160]
Is there a way to pass model property parameters to this method.
Like I have one model "widget" and then i have a slider widget, a sidebar widget etc. and now I want, if the widget is a slider widget, to have a certain conversion and if the widget is some other type of widget, another conversion?

Not sure if i makes sense?

**Comment by freekmurze** [comment]
Media conversions will only be registered once. 

The easiest way to achieve what I think you're trying to achieve is to register conversions for each type of widget. The `performOnCollections`might also be helpful.

http://medialibrary.spatie.be/v3/converting-images/defining-conversions/
