### ISSUE TITLE
Set order_column when associating a file

### ISSUE THREAD

**Issue by stefan377** [spatie/laravel-medialibrary#1602]
Hi,
how can I set a order_column when I associate a file? In documentation I see only a method for changing value after retrieving the media item. 
Is there something like
```
        $product
                        ->addMediaFromUrl($url)
                        ->setOrder(10)
                        ->toMediaCollection('productImages');
```

**Comment by freekmurze** [comment]
> Personally, I would keep track of which media models were generated and keep their id's in an array. Later i would use Media::setNewOrder([11, 2, 26]) to set the correct ordering.

Agreed.
