### ISSUE TITLE
public_path() issues

### ISSUE THREAD

**Issue by chisumo2016** [spatie/laravel-medialibrary#1603]
I am trying to add the image using media library   with the following piece of code  below
$locationObject->addMediaFromUrl(public_path('images/locations/' . $slug . '.jpg' ))
            ->toMediaCollection('photo');

but when i run php artisan migrate: fresh --seed I get the error on the console  as shown below 

Spatie\MediaLibrary\Exceptions\FileCannotBeAdded\UnreachableUrl [49;22m : [33mUrl `C:\laragon\www\Real-Estate-Application\public\images/locations/birmingham.jpg` cannot be
reached[39m

Can some assist, please? .I am running my application on laragon server

**Comment by TimothePearce** [comment]
You should try to use the `addMedia()` methods instead.

```php
$locationObject = Location::find(1);
$locationObject
   ->addMedia(public_path('images/locations/' . $slug . '.jpg' ))
   ->toMediaCollection();
```
