### ISSUE TITLE
 getfirstmediaurl() on null

### ISSUE THREAD

**Issue by lingotacro** [spatie/laravel-medialibrary#1605]
hi since i begin to use this library i have this probem when i try to retrieve the mediaUrl.
to get mediasUrl i do that : 
**`$datasB->getFirstMediaUrl('page_img')`**
and i get always this error when the medias does not exist 
**call to a member function getfirstmediaurl() on null**
pls i need to your answer .

**Comment by freekmurze** [comment]
Make sure `$datasB` contains a model and not `null`

**Comment by AhmedMub** [comment]
Hi, I know that it's an old closed issue but in case someone googles it as I did, 
using `$model->getFirstMediaUrl('collection')` for not exists media it returns an empty string so you can simply use a condition `if(!empty($model->getFirstMediaUrl('collection')))`
