### ISSUE TITLE
responsive images manipulation and watermark

### ISSUE THREAD

**Issue by tariksisbacak** [spatie/laravel-medialibrary#1608]
Hi,

How do I add watermark to the responsiveImages collection?

I used spatie/image but I get "Server error" error with laravel valet.

Thanks

**Comment by atymic** [comment]
Can you post some more specific errors? 
There's not a lot to go on in your issue.

**Comment by tariksisbacak** [comment]
I solved the problem. but i want to apply watermark to responsive images 

withResponsiveImages()

this way you can do it with thumb and watermark.

`
            $this->addMediaConversion($media->basename.'-watermark')
            ->watermark(public_path('assets/images/logo.png'))
            ->nonQueued();`

**Comment by tariksisbacak** [comment]
Solved.

```
public function registerMediaConversions(Media $media = null)
    {

        $this->addMediaConversion('thumb')
            ->width(180)
            ->height(180)
            ->sharpen(10)
            ->performOnCollections('images')
            ->nonQueued();

        $this->addMediaConversion('large')
            ->width(1024)
            ->watermark(public_path('assets/images/logo.png'))
            ->watermarkOpacity(50)
            ->sharpen(10)
            ->watermarkPosition(Manipulations::POSITION_CENTER)
            ->withResponsiveImages()
            ->performOnCollections('images')
            ->nonQueued();

    }
```

I only have one question. What should I do to use the original file instead of the large thumbnail ? 

<img width="561" alt="Screen Shot 2019-10-31 at 13 34 24" src="https://user-images.githubusercontent.com/15222704/67939696-2a757700-fbe3-11e9-8f69-42b5836aa8aa.png">

**Comment by mundix** [comment]
if I want to spread the watermark image all over the large image ? how i do that /?  
what do i need to set here 

this->addMediaConversion('large')
            ->width(1024)
            ->watermark(public_path('assets/images/logo.png'))
            ->watermarkOpacity(50)
            ->sharpen(10)
            ->watermarkPosition(Manipulations::POSITION_CENTER) => ???? need to repeat all over the image in a specific orientation 
            ->withResponsiveImages()
            ->performOnCollections('images')
            ->nonQueued();

**Comment by essana3** [comment]
try:
`            ->watermarkPosition(Manipulations::POSITION_TOP_LEFT)
            ->watermarkHeight(100, Manipulations::UNIT_PERCENT)
            ->watermarkWidth(100, Manipulations::UNIT_PERCENT)
`

**Comment by mundix** [comment]
i think this will fit the watermark all over the main image, with a percent. correct me if i'm wrong?
