### ISSUE TITLE
Creating single file collection on the fly

### ISSUE THREAD

**Issue by lukadriel7** [spatie/laravel-medialibrary#1609]
Hello, Thank you again for the great packages (I almost always check Spatie when I need something).
I am trying to implement a comic viewer where each page of an issue is a single file collection.
The problem is I don't know in advance the number of pages so I would like to know if it is possible to
create single file collection without defining them in the model.
I would normally use a collection for all the pages but due to the high frequency of editing the pages
and the difficulty of updating existing media files, I think the way to go is single file collection. 
Thank you again

**Comment by lukadriel7** [comment]
Hello again, I have been looking for a way to do this with no success.
Should I assume that it isn't possible ?

**Comment by freekmurze** [comment]
You could try to do something like this (assuming you have the number of pages somewhere on your model


```php
            public function registerMediaCollections()
            {
                foreach($this->number_of_pages as $pageNumber) {
                    $this->addMediaCollection('page_' . $pageNumber)->singleFile;
                }
            }
