### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by AEK-BKF** [spatie/laravel-medialibrary#161]
I'm trying to install your package but an error tells me :

>  Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - spatie/laravel-medialibrary 3.14.1 requires spatie/laravel-glide ^2.2.4 -> no matching package found.
>     - spatie/laravel-medialibrary 3.14.0 requires spatie/laravel-glide ^2.2.4 -> no matching package found.
>     - Installation request for spatie/laravel-medialibrary ^3.14 -> satisfiable by spatie/laravel-medialibrary[3.14.0, 3.14.1].
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by AEK-BKF** [comment]
@freekmurze  please could you help me ....

**Comment by freekmurze** [comment]
I just tested this and it works perfectly here in a vanilla Laravel 5.2 installation. 

Which version of Laravel are you using? Could you post your composer.json file?

**Comment by AEK-BKF** [comment]
I'm using 5.1
here my composer.json :
"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",        
        "laravelcollective/html": "5.1.*",
        ...
        ... 
        "spatie/laravel-glide": "^3.0",
        "spatie/laravel-medialibrary": "3.14.1",
        "intervention/image": "^2.3"

**Comment by freekmurze** [comment]
You don't need to separately require `spatie/laravel-glide` and `intervention/image`. Requiring the medialibrary will automatically pull in the right versions of those packages.

**Comment by AEK-BKF** [comment]
Thanks, I can install it now, but an error occurs 
←[37;41m  Undefined index: baseURL  ←[39;49m
what's this ?

**Comment by AEK-BKF** [comment]
lol sorry i solved the issue ^^  it's ok now
thanks a lot :))

**Comment by freekmurze** [comment]
Np! Have fun using the package.
