### ISSUE TITLE
Retorno em branco ao tentar recuperar uma imagem

### ISSUE THREAD

**Issue by eduardaarosaa** [spatie/laravel-medialibrary#1610]
Estou tentando recuperar imagens de uma consulta, está limitada a 3 imóveis, e queria recuperar as imagens dos imóveis.
![view_foto](https://user-images.githubusercontent.com/36130064/67729642-9af87a00-f9d0-11e9-8965-9a8c485ccd8b.png)

Essa é minha view 

![metdo](https://user-images.githubusercontent.com/36130064/67729661-b5caee80-f9d0-11e9-9187-690a6e791bc2.png)

Esse é meu metodo

Simplesmente não retorna erro, nem nada apenas fica em branco a tela

**Comment by freekmurze** [comment]
Please use English when creating issues.

**Comment by eduardaarosaa** [comment]
Sorry, I not know. 
I will write other issues in English. 
Thanks
