### ISSUE TITLE
Using own model

### ISSUE THREAD

**Issue by RomanNur** [spatie/laravel-medialibrary#1611]
Hi, I'am trying to use my own model (table) instead of standard `media` one. 
I changed parameter 'media_model' in medialibrary.php to my own class like this
`'media_model' => App\Models\App\CustomMedia::class`
Then in the CustomMedia.php model I wrote the following
```
namespace App\Models\App;
use Spatie\MediaLibrary\Models\Media as BaseMedia;

class CustomMedia extends BaseMedia
{
    protected $table = 'app_files';
}
```

Now, when I'am entering the index page of a resource with image parameter:
```
...
class ArticlesResource extends Resource
{
    public static $model = 'App\Models\Articles\Article';

    public function fields(Request $request)
    {
        return [
            Images::make('Photos'),
        ];
    }
...
```

I'am getting an error like 
`... unknown column 'app_files.model_id' ...`

app_files - is the name of my table, where I want to store images instead of library. I don't have a column 'model_id' there, I have a different name for this column. The same goes for other standart columns from the `media` table - I either don't want to store some columns or have a different name for them.

The question is - can I even store images in the way I want or the column's names fro `media` are set in stone?

**Comment by freekmurze** [comment]
It's better to use the original column names.

**Comment by RomanNur** [comment]
So as of now, it's impossible to use any other table/ column names except standard `media` table and standard columns? Why is there an option to change the model in the config then? I'am not complaining, just curious. I will use default `media` than.

**Comment by freekmurze** [comment]
This allows you to add extra methods and add extra fields to a model.
