### ISSUE TITLE
Blank Return When Trying to Return Media

### ISSUE THREAD

**Issue by eduardaarosaa** [spatie/laravel-medialibrary#1612]
I am trying to retrieve images from a query, it is limited to 3 properties, and wanted to retrieve images from properties.

![view](https://user-images.githubusercontent.com/36130064/67767958-4dabf500-fa30-11e9-9d8d-6723b819f008.png)
These my view 

![controller](https://user-images.githubusercontent.com/36130064/67767988-556b9980-fa30-11e9-9719-40691f8c3fb4.png)

These my controller 

Simply returns no error, nothing just blanks the screen

**Comment by freekmurze** [comment]
Seems like this is unrelated to our package.
