### ISSUE TITLE
withManipulations work only for '*'

### ISSUE THREAD

**Issue by bogatyrev-dev** [spatie/laravel-medialibrary#1614]
```
$material->addMedia($file)
            ->withManipulations([
                '*'         => ['orientation' => '90'],
                'thumb' => ['filter' => 'greyscale'],
            ])
            ->usingFileName($fileName)
            ->toMediaCollection($collectionName);
```
'thumb' conversion registered in model

I expect the thumb to be rotated 90 and greyscale. but it only rotated

**Comment by tariksisbacak** [comment]
I tried, but i couldn't get it to work. However, you can define registerMediaConversions and do it with spatie/image.

https://docs.spatie.be/image/v1/image-manipulations/effects

```
   public function registerMediaConversions(Media $media = null)
    {

        $this->addMediaConversion('thumb')
           ->grayscale()
            ->width(180)
            ->height(180)
            ->sharpen(10)
            ->nonQueued();
   }
```

**Comment by bogatyrev-dev** [comment]
@tariksisbacak ty for answer. The above is just an example. In my production code i need withManipulations()

I found a solution.
In my code above i use  `->toMediaCollection($collectionName);`
But `->performOnCollections($collectionName)` was not written in my registerMediaConversions
```
   public function registerMediaConversions(Media $media = null)
    {
            $this->addMediaConversion('thumb')->performOnCollections($collectionName)
   }
```

Аfter i added it everything everything work as it should
