### ISSUE TITLE
Trigger event on a specific model

### ISSUE THREAD

**Issue by allaniftrue** [spatie/laravel-medialibrary#1617]
How do you trigger ```Spatie\MediaLibrary\Events\MediaHasBeenAdded``` event on a specific model?

**Comment by freekmurze** [comment]
If you add media to a model, the event will be fired.

**Comment by allaniftrue** [comment]
I mean on a specific model only, so that it won't trigger on other models with media.

**Comment by allaniftrue** [comment]
Nvm, I just added a check for model_type to filter which event can only pass through. Thanks!
Example:

````php
public function handle(MediaHasBeenAdded $event)
{
    if ($event->media->model_type === 'App\Project') {
        ...
    }
}
````
