### ISSUE TITLE
File Formats

### ISSUE THREAD

**Issue by hugofabricio** [spatie/laravel-medialibrary#162]
This library is just to upload images? Or you can send other file formats using it?

**Comment by freekmurze** [comment]
The medialibrary can store images of any kind.

**Comment by hugofabricio** [comment]
Yes, but also saves txt, doc, pdf, video and other formats?

**Comment by freekmurze** [comment]
Sorry, I mistyped my previous answer. The medialibrary can store *files* of any kind.  Thumbnails can be generated for images and pdf's.
