### ISSUE TITLE
Unable to install on Laravel 6.5

### ISSUE THREAD

**Issue by mebron** [spatie/laravel-medialibrary#1624]
Getting following error:-
Installation request for laravel/framework (locked at v6.5.0, required as ^6.2) -> satisfiable by laravel/framework[v6.5.0]

please update

**Comment by fsaravi** [comment]
I install it in laravel/framework 6.5 and it works without any problem.
maybe your composer.lock file creates this problem.
can you remove composer.lock file and try again.

**Comment by mebron** [comment]
noway, still getting error

Installation request for spatie/laravel-medialibrary 7.0.0 -> satisfiable by spatie/laravel-medialibrary[7.0.0].
    - Conclusion: remove laravel/framework v6.5.0
    - spatie/laravel-medialibrary 7.0.0 requires illuminate/bus ~5.5.0|~5.6.0 -> satisfiable by illuminate/bus[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.15, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, 
v5.6.6, v5.6.7, v5.6.8, v5.6.9].
