### ISSUE TITLE
Specify folder for S3 storage dynamically (during media creation / upload)

### ISSUE THREAD

**Issue by connecteev** [spatie/laravel-medialibrary#1628]
#675 addressed the problem of not being able to customize the path / folder for storage in S3.

However, there still is no way (that I know of) to save images (for different collections) in different sub-folders. For example, a saveTo() would be useful:

```
        $profile
            ->addMediaFromUrl($imgToAttachToProfile)
            ->saveTo('profile_pictures')
            ->usingFileName('profile_picture_' . $profile->id . '.jpg')
            ->toMediaCollection('profile_picture', 's3');

```

**Comment by freekmurze** [comment]
We don't need this functionality ourselves, so probably we won't add this.

**Comment by techguydev** [comment]
I think that the media library already organize everything for you in the DB, so it does not matter if you save the media in just one folder in S3.
