### ISSUE TITLE
Upload and Delete

### ISSUE THREAD

**Issue by hugofabricio** [spatie/laravel-medialibrary#163]
To upload the original image is not deleted and to delete a record, all related files are not deleted.
Someone else is with this problem?

**Comment by webcrazy** [comment]
Yeah @hugofabricio  if I delete a media record by
```
Media::find(1)->delete();
```
Database record delete and associated file doesn't delete.

**Comment by webcrazy** [comment]
It should be like this.
```
Article::find(1)->deleteMedia($media_id);
```
and works for me.

**Comment by hugofabricio** [comment]
In doc:

Deleting a model with associated media will also delete all associated files

```$newsItem->delete();```

My problem: the media related to my model are not excluded.

**Comment by hugofabricio** [comment]
Sorry for my English, when deletes something, the media are not deleted.

My code:

```if ($user = $this->users->find($id)):
    // Delete user
    $user->delete();
    // Success message
    $message = "Usuário <b>{$user->full_name}</b> excluído com sucesso.";
    // Create log
    Activity::log($message, Sentinel::Check()->id);
    // Success alert
    flash()->success($message);
endif;```

**Comment by Akhibemudu** [comment]
@webcrazy ur answer still delete all media (images) of Article using the deleteMedia($media_id), Is there a way to delete each image of Article without deleting all images of Article. 
Am using v7 laravel 5.8

**Comment by villananda** [comment]
https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/soft-deletes/
