### ISSUE TITLE
Conversion file names

### ISSUE THREAD

**Issue by aleksandertabor** [spatie/laravel-medialibrary#1636]
Currently after conversion names are generated with this scheme:
```
public function getConversionFile(string $file): string
    {
        $fileName = pathinfo($file, PATHINFO_FILENAME);
        $fileExtension = pathinfo($file, PATHINFO_EXTENSION);
        $extension = $this->getResultExtension($fileExtension) ?: $fileExtension;
        return "{$fileName}-{$this->getName()}.{$extension}";
    }
```
source:
https://github.com/spatie/laravel-medialibrary/blob/master/src/Conversion/Conversion.php

where **getName()** is conversion name like 'thumb'.
output is: originalName-**thumb**.jpg

**_Question:_** Is it possible to get custom file names for conversions without name inside or use subfolders for each conversion and keep the original name of file? Maybe is it possible to create inferface similar to PathGenerator for setting up: https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-a-custom-directory-structure/#using-a-custom-directory-structure ?

**example:**
1/conversions/thumb/originalName.jpg
1/conversions/thumb/originalName.webp
1/conversions/desktop/originalName.jpg
1/conversions/desktop/originalName.webp

**Comment by hubertnnn** [comment]
I think https://github.com/spatie/laravel-medialibrary/issues/1686 is related to this as well.

One case that I would add is that we might want to secure some of the files.
I had a project where thumbs were supposed to be available for free but HD versions of image were sold, so different and secure paths were important.

Having a way to fully customize paths to conversions (including disk, path and filename) would be helpful.

**Comment by freekmurze** [comment]
I'll take a look at this when creating a new major version of the package.

**Comment by freekmurze** [comment]
Conversion file namers have been implemented in `v8`
