### ISSUE TITLE
Max filesize for multiple files counted together

### ISSUE THREAD

**Issue by sdudasko** [spatie/laravel-medialibrary#1637]
Is there a way to check `maxFileSize` for all files together? For example, we have `maxFileSize` set to 20MB so the user can attach either one big file with the size of 20MB or 20 files with the size of 1MB.

If there is not any built-in way do you have an idea how would I implement this feature?

**Comment by Houbsi** [comment]
@sdudasko where do you want to check it? 
the configuration in the package is for 1 file only.
If you want to do more elaborate checks you need to do some validation with laravel itself i presume.

**Comment by freekmurze** [comment]
Yup, create a validation rule where you loop over a collection a calculate the current size yourself.
