### ISSUE TITLE
How to convert HEIC images

### ISSUE THREAD

**Issue by jozeflambrecht** [spatie/laravel-medialibrary#1638]
Is there a way to convert images (from a form request) from .HEIC (iPhone) to .PNG/.JPEG?

**Comment by freekmurze** [comment]
No .HEIC isn't supported yet. You have to convert it yourself to .png or .jpeg before adding it the medialibrary.

**Comment by peccommunications** [comment]
It's 2021 - will this be available or do we need to convert it first still?

**Comment by freekmurze** [comment]
@peccommunications maybe you will be the one contributing this in 2021?

**Comment by nikitabuida** [comment]
> @peccommunications maybe you will be the one contributing this in 2021?

Wouldn't it be adding 
if (config('media-library.image_driver') === 'imagick') {
            $mimeTypes[] = 'image/tiff';
            $mimeTypes[] = 'image/heif';
        }

to function supportedMimeTypes() (and extensions) analogous with tiff support?

Recent versions of ImageMagic come with heic support.
