### ISSUE TITLE
How to control maximum file size during runtime?

### ISSUE THREAD

**Issue by jameslkingsley** [spatie/laravel-medialibrary#1643]
I need to limit the upload file size based on the user's remaining storage space - right now I'm using this:

```php
class Medialibrary
{
    /**
     * Runs the given closure with the given size as the maximum file upload size.
     *
     * @return mixed
     */
    public static function maximumFileSize(int $bytes, callable $closure)
    {
        $default = config('medialibrary.max_file_size');

        config(['medialibrary.max_file_size' => $bytes]);

        $response = call_user_func($closure);

        config(['medialibrary.max_file_size' => $default]);

        return $response;
    }
}
```

and then I'm using it like this:

```php
Medialibrary::maximumFileSize($user->disk_usage->remaining, function () use ($request, $model) {
    return $model->addMediaFromDisk($request->key)
        ->toMediaCollection('attachments');
});
```

I'm wondering whether there is a better way to accomplish this, that is perhaps already built into the library? Maybe something like this:

```php
$model->addMediaFromDisk($request->key)
    ->maximumFileSize($user->disk_usage->remaining)
    ->toMediaCollection('attachments');
```

**Comment by freekmurze** [comment]
You can use media collections to restrict file sizes.

https://docs.spatie.be/laravel-medialibrary/v7/working-with-media-collections/defining-media-collections/#only-allow-certain-files-in-a-collection

`Spatie\MediaLibrary\File` has a size property.

**Comment by jameslkingsley** [comment]
This doesn't override the default `max_file_size` configuration option. I need the default max file size to remain at 10 MB, except on a particular model where it has an unlimited size (as uploading is being directly handled by S3).

**Comment by jameslkingsley** [comment]
By using my original solution, will I run into issues with changing the config during runtime?

**Comment by nmfzone** [comment]
+1 for controlling file size during runtime. Not really needed, but I think it's good to have it.

For now, we can set the max file size to big value, then let the Laravel Validation handle it per collection.
