### ISSUE TITLE
Documentation is gone?

### ISSUE THREAD

**Issue by tanthammar** [spatie/laravel-medialibrary#1649]
Today the documentation for v7 and v6 returns 404.
I can only find docs for v5.

https://docs.spatie.be/laravel-medialibrary/v7/introduction

Has it moved?

**Comment by djunehor** [comment]
The documentation is back😀

**Comment by jorisatabix** [comment]
It's gone again

**Comment by djunehor** [comment]
I'm not sure what the problem is, but I can access both v7 and v6 documentation

**Comment by jorisatabix** [comment]
It has returned indeed.

**Comment by freekmurze** [comment]
This is fixed.
