### ISSUE TITLE
Spatie\MediaLibrary\Jobs\PerformConversions pointing to wrong project folder

### ISSUE THREAD

**Issue by teddyhendryanto** [spatie/laravel-medialibrary#1650]
Hi,

Is there anyone who face same problem with mine?
Whenever I dispatch PerformConversions, it pointing to wrong project folder.
I got this kind of error message:
League\Flysystem\FileNotFoundException: File not found at path: 11428/01885f06c66321c0e45e1c3bd05b16171743e1ca.png in **/srv/www/xox_middleware**/vendor/league/flysystem/src/Filesystem.php:389

In fact, my image is under **/srv/www/black_admin**.

I tried to run php artisan clear:cache, config:clear, but  no luck.
Kinda frustrate.
What should I do to fix this?

Need your help, guys.

"spatie/laravel-medialibrary": "^7.6"
"laravel/framework": "5.7.28"
"php": "7.2.17"

**Comment by Houbsi** [comment]
Quick question, what is the filesystem / media disk folder did you setup in the config/medialibrary.php and the filesystems.php / your .env
I suppose this is a config issue :) Or that you are giving the path to the file a bit wrong. 

`$document
                        ->addMediaFromDisk($file, 'local')
                        ->toMediaCollection();`

Here my Code searches the current $file from Request->file() where laravel saves everythin, from the 'local' storage (set in config/filesystems.php

Greetings
