### ISSUE TITLE
How to assign an algolia media path?

### ISSUE THREAD

**Issue by trevorpan** [spatie/laravel-medialibrary#1651]
Are there any specific preparations on this package needed to make media clickable with algolia?
It seems like if a model has the HasMedia trait the path would be accessible. 

My basic goal is for Algolia to populate an image associated with a post on my site's search page.

I've implemented the `toSearchableArray()` in the model. However, it's not clear how to make the image shown. e.g. we wouldn't be making searches for a imageurl. So, how is this accomplished?

Thank you,

Trevor

**Comment by freekmurze** [comment]
That could work, yes!

**Comment by trevorpan** [comment]
https://discourse.algolia.com/t/image-path-with-two-indices/9452/7

Do you have any idea on how to merge the Model index and Media index or at least use? I thought possibly a MySQL view would work:
https://stitcher.io/blog/eloquent-mysql-views

Brent said views can't be updated.

This is all I'm trying to include in the Job.php index:
```
<img class="jobthumbnail" src="{{ $job->getMedia('document')->first()->getUrl('thumbnail') }}">
```
Should the `toSearchableArray()` be put on the Media.php file? Just not sure how to retrieve a model separate from the one `toSearchableArray()` is on...
