### ISSUE TITLE
Issue installing package with composer

### ISSUE THREAD

**Issue by Fredericld** [spatie/laravel-medialibrary#1652]
Hi,

I am running the laravel 6. 
Tried to install the package

` "require": {
        "php": "^7.1.3",
        "spatie/laravel-medialibrary" : "^7.0.0"
    },`

Here is he error I got 
`Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Symfony\Component\Debug\Exception\FatalThrowableError  : Class name must be a valid object or a string

  at C:\projects\projects\fcms1\vendor\spatie\laravel-medialibrary\src\MediaLibraryServiceProvider.php:33
    29|         ], 'views');
    30|
    31|         $mediaClass = config('medialibrary.media_model');
    32|
  > 33|         $mediaClass::observe(new MediaObserver());
    34|
    35|         $this->loadViewsFrom(__DIR__.'/../resources/views', 'medialibrary');
    36|     }
    37|

  Exception trace:

  1   Spatie\MediaLibrary\MediaLibraryServiceProvider::boot()
      C:\projects\projects\fcms1\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  2   call_user_func_array([])
      C:\projects\projects\fcms1\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

I have not done any migration at this stage, nor published the config file

Running my app, the following line is highlighted with the error
`$mediaClass::observe(new MediaObserver());`
`"Class name must be a valid object or a string"
`

**Comment by Fredericld** [comment]
Tried with 
`"require": { "php": "^7.1.3", "spatie/laravel-medialibrary" : "^7.16.0" },`

Same error

**Comment by rohan-krishna** [comment]
Having the same error. Laravel 6.2.

**Comment by Fredericld** [comment]
I got it work eventually. My system runs on Laravel 6.6.2
I deleted manually the config.php file in bootstrap/config, ran a composer update and no error.

If you still have issues, review this    https://github.com/spatie/laravel-medialibrary/issues/1567
