### ISSUE TITLE
Associating files

### ISSUE THREAD

**Issue by Ashish-Kushwaha** [spatie/laravel-medialibrary#1654]
i am getting error ......

Spatie\MediaLibrary\Exceptions\FileCannotBeAdded\FileDoesNotExist
File `builder1.jpg` does not exist

**Comment by lucasweaver10** [comment]
I'm getting this as well if anyone can help. Using Laravel 6 and latest version of Spatie.

**Comment by lucasweaver10** [comment]
@Ashish-Kushwaha Were you able to find a fix?

**Comment by freekmurze** [comment]
There's too little information to go on. Current tests indicate that all behaviour for adding files is working as intended.

 Please submit a failing test for us to fix.

**Comment by arnakoguzhan** [comment]
Looks like #1317  and #1062 point the same issue
