### ISSUE TITLE
Utilizing a custom generator on a per model basis does not work according to documentation

### ISSUE THREAD

**Issue by tdondich** [spatie/laravel-medialibrary#1655]
Per documentation at https://docs.spatie.be/laravel-medialibrary/v7/converting-other-file-types/creating-a-custom-image-generator/ , you should be able to add a getImageGenerators method in your model in order to use a custom generator specific to that model.

Unfortunately, it appears that this method will never get called as the getImageGenerators() method is called on the Spatie Media model and it gets the generators from the config file and never attempts to fetch from the model.   You'd have to do this with a custom Media model instead of just using the Spatie Media model with custom generators defined our own models as the documentation describes.

Let me know if a PR would warrant allowing this.  This would modify the HasMedia and HasMediaTraits to include a blank getImageGenerators method that by default returns an empty collection.  Then the Spatie media model can call this method from the model instance and if it's not empty, use the generators returned; otherwise default to getting the generator list from configuration.  This will allow the process in documentation to work and existing behavior to still function.  I'd be happy to create one if you feel comfortable with the approach described.

**Comment by freekmurze** [comment]
I'd welcome a PR with tests that adds this.Thanks!

**Comment by vismutx** [comment]
Really need test PR?

It does not work without that bureaucracy?
it can't work as described.
Here is method from **ImageGeneratorFactory**
and it is used only in ImageGeneratorFactory.

```
class ImageGeneratorFactory
{
    public static function getImageGenerators(): Collection
    {
        return collect(config('media-library.image_generators'))
            ->map(function ($imageGeneratorClassName, $key) {
                $imageGeneratorConfig = [];

                if (! is_numeric($key)) {
                    $imageGeneratorConfig = $imageGeneratorClassName;
                    $imageGeneratorClassName = $key;
                }

                return app($imageGeneratorClassName, $imageGeneratorConfig);
            });
    }
....
```

**Comment by vismutx** [comment]
@freekmurze

**Comment by freekmurze** [comment]
@vismutx 

> It does not work without that bureaucracy?

Test are not bureaucracy. Here are some of my thoughts on testing: https://testing-laravel.com/importance-of-testing
