### ISSUE TITLE
The Media\Model depends on non-existant function on UrlGenerator interface

### ISSUE THREAD

**Issue by drtheuns** [spatie/laravel-medialibrary#1656]
In the `Spatie\MediaLibrary\Models\Media` class there is the following function:

```
public function getPath(string $conversionName = ''): string
{
    $urlGenerator = UrlGeneratorFactory::createForMedia($this, $conversionName);

    return $urlGenerator->getPath();
}
```

The `UrlGeneratorFactory::createForMedia` returns a type of the `UrlGenerator` interface, which does not contain the `getPath()` function.

We had written our own `UrlGenerator` according to the docs, but when it went live we were seeing errors with the `PerformConversions` due to this unexpected method call which we hadn't implemented.

**Comment by nguyentranchung** [comment]
same with me

**Comment by freekmurze** [comment]
Modify the interface now is a breaking change. We'll correct this in the next major version of the package.

**Comment by freekmurze** [comment]
This has been fixed on the `v8` branch.
