### ISSUE TITLE
Upload medias before creating model object.

### ISSUE THREAD

**Issue by biholaindrasinh** [spatie/laravel-medialibrary#1658]
I have a situation where I want to upload images for the products while creating a product. My script author already used this package and providing product images upload on the edit product. How do I provide product images upload on to create a product?

**Comment by salierg** [comment]
This is a good question.
We have a begining of an answer on this page:
https://github.com/spatie/laravel-medialibrary/issues/68

**Comment by freekmurze** [comment]
We'll improve upon this in a new major release of the package.

**Comment by pjhartin** [comment]
Out of interest @freekmurze, do you have an ETA on a major release? 
I'm was about to integrate this package into our product, however, I didn't realise that media items do not have their own discrete IDs as in https://github.com/plank/laravel-mediable. 

Everything else around the package is perfect.

**Comment by freekmurze** [comment]
A rough estimate would be somewhere Q2 2020.

**Comment by pjhartin** [comment]
@freekmurze Thanks for the quick response on the ETA. Looking forward to it!
