### ISSUE TITLE
deleteMedia by custom_path_generator_class

### ISSUE THREAD

**Issue by Fanamurov** [spatie/laravel-medialibrary#166]
public function getPath(Media $media)
	{
		$model = class_basename($media->model_type);
		return $model . '/';
	}

	public function getPathForConversions(Media $media)
	{
		$model = class_basename($media->model_type);
		return $model. '/'. $media->name .'/';
	}

Works:
/media/{ModelName}/file.jpg
/media/{ModelName}/filenamePath/files_conversions

Goal: I want to be able to replace all the media files in the model faster and easier

Upload fine, but:

If I used deleteMedia: 
`Page::find(Input::get('model_id'))->deleteMedia(Input::get('id'));`
All folder /media/{ModelName} is deleted, not only:
/media/{ModelName}/file.jpg
/media/{ModelName}/filenamePath/files_conversions

Fix:
\Medialibrary\Filesystem:

    public function removeFiles(Media $media)
    {
		$pathGenerator = PathGeneratorFactory::create();
		$this->filesystem->disk($media->disk)->deleteDirectory($pathGenerator->getPathForConversions($media));
		$this->filesystem->disk($media->disk)->delete($pathGenerator->getPath($media) .'/'. $media->file_name);

        //$this->filesystem->disk($media->disk)->deleteDirectory($this->getMediaDirectory($media));
    }

**Comment by freekmurze** [comment]
Your fix will not clean up the media folder itself but only the files inside it. This behaviour is probably what you want, but most users of the package won't want this.

If you need some custom deletion behaviour you can [use your own model](http://medialibrary.spatie.be/v3/advanced-usage/using-your-own-model/) and overriding the delete function.
