### ISSUE TITLE
Downloaded zip file cannot be opened error after 7.14.2

### ISSUE THREAD

**Issue by ziming** [spatie/laravel-medialibrary#1660]
Hi,

After updating laravel-medialibrary beyond 7.14.2

Downloaded zip files (generated by MediaStream) could no longer be opened.

Attaching a screenshot

https://share.getcloudapp.com/z8un7dWz

For now I downgrade back to laravel-medialibrary 7.14.2 as it is the last working version where downloaded generated zip file could be opened. So my guess is something in 7.16.0 broke it

Thank you! :)

**Comment by rubenvanassche** [comment]
Hi @ziming could you send a corrupt zip file as example? I think this has something to do with #1604, but checking the zip file will provide me more info about the crash.

**Comment by gabrielesbaiz** [comment]
Hi, I have the same problem. I attach the file so you can check.

[my-files.zip](https://github.com/spatie/laravel-medialibrary/files/3963941/my-files.zip)

**Comment by rubenvanassche** [comment]
Hi @gabrielesbaiz, could it be that there are nog files in the archive? In one extractor the archive crashes, in another it opens but says the archive is empty. Could you provide an archive with at least one file so I can do some more testing?

Thanks!

**Comment by ziming** [comment]
For mine it is a pdf file in the zip.

**Comment by rubenvanassche** [comment]
@ziming could you please share your zip file?

**Comment by ziming** [comment]
[documents.zip](https://github.com/spatie/laravel-medialibrary/files/4006805/documents.zip)

A sample pdf inside. Hope it helps

**Comment by rubenvanassche** [comment]
@ziming Sorry for the late response, we all had some vacation here 😄 

When I open the documents.zip file I've no problems opening it and extracting the zip file, I've also checked the zip integrity and this all looks correct.

**Comment by ziming** [comment]
Well I just tried again and I can't. I'm on Mac OS Mojave 10.14.6 if it helps.

**Comment by rubenvanassche** [comment]
I'm on 10.15.1 tried both the default extractor and the unarchiver, both work without problems, this is the file you've put in the zip:

[credit-bureau-report-28_Dec_2019.pdf](https://github.com/spatie/laravel-medialibrary/files/4031177/credit-bureau-report-28_Dec_2019.pdf)

**Comment by ziming** [comment]
I am using the unarchiver actually.

https://share.getcloudapp.com/bLuGdXQ9

**Comment by ziming** [comment]
Update:

It works with the unarchiver. But not the default extractor.

**Comment by rubenvanassche** [comment]
Okay so some digging in the binary learned something:

`50 4B 03 04 2D 00 08 00 08 00 2C 79 9C 4F 00 00 00 00`

Those last 4 zero pairs are the CRC of the Zip Archive, they are null and probably shouldn't. I think the unarchiver ignores this and doesn't do a checksum but other extractors do and fail. I guess this has something todo with this PR: https://github.com/spatie/laravel-medialibrary/pull/1604.

**Comment by rubenvanassche** [comment]
Hi @ziming, 

Since I cannot test on my computer if the zipfile is broken, can you please in your projects vendor directory change the following line:

https://github.com/spatie/laravel-medialibrary/blob/726a00cbfc8b7343dd0c558938b9eb5f613b7eec/src/MediaStream.php#L76

to: 

```php
        $zip = new ZipStream($this->zipName);
```

And check of the problem still occurs?

**Comment by ziming** [comment]
Okay let me try it now and get back to you

**Comment by ziming** [comment]
Yup! it works.

I upgraded medialibrary from 7.14.2 to the latest 7.18.0

Upload a file, tried to download, can't open zip.

Then I change that line in `src/MediaStream.php` as mentioned.

Tried download again, able to open zip this time.

Hope it helps!

**Comment by rubenvanassche** [comment]
Hi everyone, just tagged a new release https://github.com/spatie/laravel-medialibrary/releases/tag/7.18.1 that disables the zero header, can you please check if everything is working as expected?
