### ISSUE TITLE
Double //

### ISSUE THREAD

**Issue by piep14** [spatie/laravel-medialibrary#1663]
I have a concern. This code:

`$post->getMedia()->last()->getUrl()`

Give : 

> location: "//storage/7/calendar.png"

Why there is // who bug my URL?

Thanks

**Comment by freekmurze** [comment]
According to our tests this shouldn't happen, could you submit a failing test for us to fix?

**Comment by piep14** [comment]
My code is : 

`public function posts()
{
    $post = Post::findOrFail(request()->id);
    if (!empty(request()->file()['file'])) {
        $post->addMedia(request()->file()['file'])->toMediaCollection();
        $post->save();
    }

    $response = [
        'location' => $post->getMedia()->last()->getUrl()
    ];

    return Response::json($response);
}`

How should I proceed to show you the concern? I use your bookstore regularly though, and I do not know the reason. An idea where I can look can be? thank you

**Comment by ninthspace** [comment]
This just happened to me, because I had a trailing slash in my APP_URL.
