### ISSUE TITLE
Unexpectedly removes all files from folder

### ISSUE THREAD

**Issue by andreipan** [spatie/laravel-medialibrary#1664]
If to use a custom path generator and store files in one folder. 
After call **$model->clearMediaCollection($collection);** it removes all files within folder even if files referred to other **$model**. It was unexpected behaviour for me.

**Comment by freekmurze** [comment]
That behaviour is documented, see last paragraph here: https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-a-custom-directory-structure/
