### ISSUE TITLE
When attaching files from disk use the copy method

### ISSUE THREAD

**Issue by greatwitenorth** [spatie/laravel-medialibrary#1669]
When using the `addMediaFromDisk()` method it looks like the system makes a direct copy of the file. For files hosted on a remote provider this means that the file needs to be downloaded to the server, then re-uploaded. I'd like to propose that we utilize the copy command instead if available. 

For example, changing this:
https://github.com/spatie/laravel-medialibrary/blob/1a882349f216855a37583dff81ff44bd1ec4ea63/src/Filesystem/Filesystem.php#L47-L66

To something like this:
```php
    public function copyToMediaLibraryFromRemote(RemoteFile $file, Media $media, ?string $type = null, ?string $targetFileName = null)
    {
        $storage = Storage::disk($file->getDisk());

        $destinationFileName = $targetFileName ?: $file->getFilename();

        $destination = $this->getMediaDirectory($media, $type).$destinationFileName;

        $this->filesystem->disk($media->disk)
            ->getDriver()->copy(
                $file->getKey(),
                $destination
            );
    }
```

I've tested the above with S3 and it seems to work. Although I haven't texted with any other drivers. Any thoughts?

**Comment by freekmurze** [comment]
Will this work with very large files? Does it use streams under the hood?

**Comment by leitom** [comment]
This causes big problems with serverless(laravel vapor) we get errors like:
fwrite(): Write of 1204224 bytes failed with errno=28 No space left on device
When the file already is within a s3 bucket its not rational to copy that file from s3 down to lambda/server and then reupload it back to the s3 bucket.

**Comment by leitom** [comment]
Solution for now is to remove the default `extra_headers` property in the config.

```php
'remote' => [
        /*
         * Any extra headers that should be included when uploading media to
         * a remote disk. Even though supported headers may vary between
         * different drivers, a sensible default has been provided.
         *
         * Supported by S3: CacheControl, Expires, StorageClass,
         * ServerSideEncryption, Metadata, ACL, ContentEncoding
         */
        'extra_headers' => [
            'CacheControl' => 'max-age=604800',
        ],
    ],
```
