### ISSUE TITLE
Query media library by custom property

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#167]
I have custom property "youtube_url" now id like to query media where that custom property is an empty string.

A method im using now is this:
```
public static function getGalleryThumbAndLarge(){
        $frontimages = Media::where('collection_name', 'galleryfrontimages')
            ->orderByRaw('RAND()')
            ->get()
            ->map(function (Media $media) {
                return [
                    'frontthumb' => $media->getUrl('frontthumb'),
                    'frontlarge' => $media->getUrl('frontlarge'),
                ];
            });

        return $frontimages;
    }
```
now id like the same but where the youtube_url custom property is empty.

and then id also like to query the opposite, only images where the custom property "youtube_url" is not empty.

Any ideas?

**Comment by freekmurze** [comment]
Maybe I'm missing something but I guess you could just [retrieve the value of the custom property](http://medialibrary.spatie.be/v3/advanced-usage/adding-custom-properties/) and use that in your mapping.

**Comment by kickthemooon** [comment]
i was looking at that but unfortunately im not sure how i would use it in my mapping to 

ONLY 

get images where the custom property "youtube_url" is empty or to 

ONLY 

get the images that have something saved to that property.

**Comment by freekmurze** [comment]
Easiest way would be to just get all media and [filtering](https://laravel.com/docs/5.1/collections#method-filter) out the records you need.

**Comment by kickthemooon** [comment]
Working fine with [filtering](https://laravel.com/docs/5.1/collections#method-filter), thanks.

**Comment by vesper8** [comment]
After some fiddling I found the json query that works:

```
            $post->media[0]->setCustomProperty('invalid', true);
            $post->media[0]->save();
```
and then to exclude posts that are marked as invalid 

```
            $posts = Post::whereHas('media', function ($query) {
                $query->whereRaw(
                    '!(custom_properties != "[]" AND json_extract(`custom_properties`, "$[0].invalid") = true)'
                );
            })
            ->get();
```

**Comment by jameznew90** [comment]
I needed a solution for this the other day. Laravel now has out the box json where clauses:

```
Media::where('model_type','App\Category')->whereJsonContains('custom_properties->tags',$searchTerm)->get();
```

https://laravel.com/docs/5.8/queries#json-where-clauses
