### ISSUE TITLE
Make URL generator method trim trailing slash

### ISSUE THREAD

**Issue by trevorgehman** [spatie/laravel-medialibrary#1673]
In the below method, if you provide a URL with a trailing slash in `config('medialibrary.s3.domain')`, the URL won't properly generate:

https://github.com/spatie/laravel-medialibrary/blob/c32f794d1247a1bbd50d604ff4e602550cfcd7f4/src/UrlGenerator/S3UrlGenerator.php#L21-L39

I think it makes sense to duplicate what Laravel's Filesystem manager does and automatically do a `rtrim` on the base URL:

https://github.com/laravel/framework/blob/5b1b3675748649da19c9b6308d1ade25f41eabd5/src/Illuminate/Filesystem/FilesystemAdapter.php#L563-L573

This way, you can provide the "domain" (or more accurately, the URL) for the media item in either format:

- `AWS_URL=https://s3.amazonaws.com/my-bucket/`
- `AWS_URL=https://s3.amazonaws.com/my-bucket`

It's a minor thing, but I figured worth mentioning. Would you accept a PR for this?

**Comment by freekmurze** [comment]
Yes, send a PR with tests. Thanks!
