### ISSUE TITLE
Retrive single image from collection by id

### ISSUE THREAD

**Issue by satputekuldip** [spatie/laravel-medialibrary#1675]
[https://github.com/spatie/laravel-medialibrary/issues/175](url)

I have using this method to retrieve single image by id

`function view(Request $request, $collection_name, $id)`
    `{`
        `$category = Category::where('collection_name',$collection_name)->first();`
        `$image = $category->getMedia($collection_name, ['id' => $id]);`
        `return $image;`
`}` 

but it returning empty array [ ]

**Comment by enniosousa** [comment]
`getMedia()` method return a [Collection](https://laravel.com/docs/master/collections), so you can use `where()` ([the collection method](https://laravel.com/docs/master/collections#method-where)) to apply a condition, last you can call the method `first()` that response the media model.

```
function view(Request $request, $collection_name, $id)
{
    $category = Category::where('collection_name',$collection_name)->first();
    $image = $category
        ->getMedia($collection_name) // it return a collection of Media Model
        ->where('id', $id) // filter all items from collection with this condition
       ->first() // get first item from collection. it could be a Media model or null if the collection is empty
    ;
return $image;
}
```
