### ISSUE TITLE
[Question ]Does this package support Digital Ocean and multiple folder issue?

### ISSUE THREAD

**Issue by gyan111** [spatie/laravel-medialibrary#1676]
**Question 1**
Does this package support Digital Ocean? 

I guess it supports as it supports s3 and Figital Ocean uses the same.

**Question 2**

I see it created folders for each id as specified by in the documents.

Suppose I have 10 thousand users and each user have have 100 images. 

It is going to create 1 millions folders. Apart from that others images are also  there.

Is it suitable to create so many folders in a single folder?

Is there a way we can define(create) folders dynamically according to the type. 

e.g, 

Root Folders
Userr folder | Product Folder
Many Folders | Many Folders |

**Comment by imannms** [comment]
**Answer for Question 1:**
Yes. You can use Digital Ocean with S3 driver.

**Answer for Question 2:**
Yes. You can define your folders dynamically.
Read the doc: [https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-a-custom-directory-structure/](https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-a-custom-directory-structure/)

**Comment by gyan111** [comment]
Thank you so much for your answer.
Regarding the folder.

I am not asking about the folder structure.
I have gone through the documents already.


My question is, can we save a file to specific folder while creating/associating/uploading?

**Comment by imannms** [comment]
My bad, I overlooked your 2nd question.

No. You can't do that, according to #1628.

Please close this issue if this answered your question.
