### ISSUE TITLE
[Question] Changing collection of media

### ISSUE THREAD

**Issue by gyan111** [spatie/laravel-medialibrary#1678]
Can a media be changed from one collection to another?

**Comment by freekmurze** [comment]
You can just change the `collection_name` in the database and regenerate the conversion for that model.

**Comment by cp-vrkansagara** [comment]
@freekmurze Can you provide us a little example for this?

**Comment by JoseLuisRNP** [comment]
> @freekmurze Can you provide us a little example for this?

Maybe something like:

```php
$myMedia = Media::find(1);
$myMedia->update(['collection_name' => 'collection_to_move']);
Artisan::call('media-library:regenerate --ids=' . $myMedia->id);
```

**Comment by LeonSkrilec** [comment]
It's better to use [move](https://spatie.be/docs/laravel-medialibrary/v9/advanced-usage/moving-media) method because it automatically triggers conversion jobs. 
If you want to change collection only, just pass existing model to the method.
