### ISSUE TITLE
Download files outside public_html on extern driver

### ISSUE THREAD

**Issue by vanrijs** [spatie/laravel-medialibrary#1679]
Hi!

Installed this library last week and moved some strict confidential files to a folder outside the public_html on an extern driver (server with another ip). So I have: 
/home/user_x/data (driver private)
/home/user_x/public_html/uploads (driver public)

Downloading/using files from public isn't an issue because I can use the getUrl function. 
I'm not completely sure what the best way is to download files from the /data (private driver) folder. I now use getPath for the private driver:

`
    public function getPath() : string
    {
        return $this->getPathRelativeToRoot();
    }
`

In the download controller I use
`
$file = \Storage::disk('private_driver')->read($mediaItem->getPath());
`
Is this the best way to let my users download private stored files?

**Comment by freekmurze** [comment]
I think that is a valid way to go about this. 👍
