### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by webcrazy** [spatie/laravel-medialibrary#168]
Hello
When pdf file is uploaded, I got this error.

```
FileNotFoundException in File.php line 37:
The file "/tmp/phpUjWNTH" does not exist
```

But after I refresh, the file is alrady uploaded.
Any suggestion would be very appreciated.

**Comment by freekmurze** [comment]
Can you post the entire trace of the error? Are you only having a problem with uploading pdf's? Or are you getting the same problem with any type of file?

**Comment by webcrazy** [comment]
Thanks for your quick reply. I found my error. That was because of I'm trying to update the file name that was already upload to mediaLibray. That's why I got file not found exception with temp file location.
