### ISSUE TITLE
Is it improper to call withResponsiveImages() on registerMediaCollections() ?

### ISSUE THREAD

**Issue by trevorpan** [spatie/laravel-medialibrary#1680]
After updating to Laravel 6.0 and Spatie-medialibrary 7.0 I was getting the error below; prior to these upgrades this call did not affect anything. 

`Bad Method Call ... \MediaCollection::withResponsiveImages does not exist.`
```
public function registerMediaCollections()
    {        
$this->addMediaCollection('jobfullpage')
            ->acceptsFile(function (File $file) {
                return $file->mimeType === ['image/jpeg, image/jpg, image/png, application/pdf, application/docx, application/xlsx, application/csv, video/avi, video/mpeg, video/mov, video/mp4'];
            })
            ->withResponsiveImages()
            ->useDisk('media');
```
I did use `withResponsiveImages()` with `registerMediaConversions()`; https://docs.spatie.be/laravel-medialibrary/v7/responsive-images/getting-started-with-responsive-images/#generating-the-necessary-images says it's the essential place as the collection will get these responsive images.

Can I safely remove the `withResponsiveImages()` from `registerMediaCollections()`.

Thank you,
Trevor

**Comment by freekmurze** [comment]
Currently `withResponsiveImages` is not available on a custom media collection. Right now, you must use `withResponsiveImages` when actually adding the file. 

I'd accept a PR with tests that adds `withResponsiveImages` when defening a media collection.

**Comment by trevorpan** [comment]
@freekmurze wow, that'd be awesome. I'm trying to launch this site in the next week or so, but will do my best to put together the PR! 

Thank you and happy new year!

**Comment by freekmurze** [comment]
We'll continue this in #1681
