### ISSUE TITLE
Custom non image generator

### ISSUE THREAD

**Issue by cliffordjames** [spatie/laravel-medialibrary#1682]
Hi, I'm trying to write generator for wav to mp3 conversions. In the docs there is only an example for an image generator and in the config I can only add a generator to the image_generators array.

Is there a secret or undocumented way to add generators for anything but images?

Thanks in advance!

**Comment by freekmurze** [comment]
Generators are meant to create thumbnail representation of files. Converting audio to another format is not supported.
