### ISSUE TITLE
Is there a less repetitive way to check if an upload already exists?

### ISSUE THREAD

**Issue by marbuser** [spatie/laravel-medialibrary#1685]
My title is a bit vague so let me explain. I've got a form and when I do a file upload, I submit the file with the form. However, I've noticed that when I'm editing an existing resource, and submit the edit, medialibrary just assumes it's a new upload and reuploads the file again. 

Of course I can do an if-check in my controller to check if the filename is the same (since I'm using a hash of the file as the file name), but this becomes very repetitive especially when you have 20+ models that all require image uploads. I was wondering if medialibrary had any sort of functionality like this built in already that I'm perhaps not aware of, or if there was some type of technique I could apply to reduce repetition for this specific task?

I was also wondering if medialibrary was smart enough to determine what files have changed if you are doing a multiple-file upload? E.G say I have the files; `1.jpeg, 2.jpeg, 3.jpeg` already uploaded, but I then replace `1.jpeg` with `test.jpeg` but leave the other 2 the same, is there anyway I can make it so that medialibrary only replaces the `1.jpeg` record in the database and persists the other 2?

Thanks and any help is appreciated!

**Comment by freekmurze** [comment]
The media library does not offer that functionality. You'll need to manually perform the checks you want.
