### ISSUE TITLE
Conversions on different disk

### ISSUE THREAD

**Issue by cliffordjames** [spatie/laravel-medialibrary#1686]
Is it possible to store some of the conversions on different disks?

Example:

Upload .wav to prive disk
Store waveform.png to public disk
*any other audio conversions on this file will be done outside media library but are stored as conversions on the private disk*

Other option can be just to add more media files to the model instead of conversions of the .wav

**Comment by freekmurze** [comment]
Currently this is not possible, but I'll take a look when we'll working on a new major version.

**Comment by freekmurze** [comment]
This has been added in the upcoming `v8`. 

https://github.com/spatie/laravel-medialibrary/blob/fe23ae0975190a0a6d270798109f088ec4b09e83/docs/advanced-usage/working-with-multiple-filesystems.md#storing-conversions-on-a-separate-disk

**Comment by cliffordjames** [comment]
That’s great news!

Thanks a lot!

Met vriendelijke groet,

Clifford James
