### ISSUE TITLE
addMediaFromUrl with basic auth 

### ISSUE THREAD

**Issue by hirenkeraliya** [spatie/laravel-medialibrary#1687]
I have used a Mailgun inbound email. they respond to an attachment URL but that is restricted with the basic authentication so how can I upload the file with basic authentication.

https://sw.api.mailgun.net/v3/domains/xxx.com/messages/eyJwIjpmYWxzZSwiayI6ImZhMTU0NDkwLWVmYzgtNDVlNi1hYWMyLTM4M2EwNDY1MjJlNCIsInMiOiI2NmU1NmMzNTIwIiwiYyI6InRhbmtiIn0=/attachments/0

The link for the attachment is as per given above.

How can I use `addMediaFromUrl`?

Thanks.

**Comment by riasvdv** [comment]
`addMediaFromUrl` does not support adding headers. You can use [Guzzle](https://github.com/guzzle/guzzle) to retrieve your file and then add it to the media collection.
