### ISSUE TITLE
Defining conversions not only for first page of pdf documents

### ISSUE THREAD

**Issue by Houbsi** [spatie/laravel-medialibrary#1689]
Hi,

i love the library but for a project i'm trying to get a preview off all the pages included in the pdf. I have not yet found a possibility to do it via the package.

Can someone help me? Or put me into the direction where it is generated and i could maybe implement something on my own? :)

**Comment by freekmurze** [comment]
Medialibrary can save multiple sizes of thumbnail, but not thumbnails for all pages of a PDF. You need to handle that yourself.

To do it manually you could use our pdf-to-image package. 
https://github.com/spatie/pdf-to-image#other-methods

**Comment by Houbsi** [comment]
Thanks @freekmurze. You have to many packages, I need to check them all out.
