### ISSUE TITLE
Watermarks with Glide for conversion

### ISSUE THREAD

**Issue by judantus** [spatie/laravel-medialibrary#169]
I'm trying this but it does not work for attributes **mark**:

`$this->addMediaConversion('thumb')`
`         ->setManipulations([`
`                 'w' => 800, `
`                 'h' => 600, `
`                 'mark'=> public_path('img/logo.png'),`
`                 'markw' => 50,`
`                 'markpos' => 'top-right'
`          ])`
`         ->performOnCollections('images');`

What am I doing wrong? Thanks

**Comment by freekmurze** [comment]
Watermarks are not supported in the version of Glide (0.3) that the media library is requiring.

Somewhere this year we'll create a new major version of the medialibrary where Glide 1.0 is supported.
