### ISSUE TITLE
Filesize limitations on registerMediaConversions

### ISSUE THREAD

**Issue by Houbsi** [spatie/laravel-medialibrary#1690]
`     public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->width(71)
            ->height(100);
    }
`

I have this in my code. But it seems that at some point when the pdf is to big (Something over 10MB), the job completeley failes for the above conversion.

When i go through the pdf with spatie/pdf-to-image and create an image from every page it workes fine.

I have not yet found the way how the conversion is done in the medialibrary any help is welcome.

**Comment by Houbsi** [comment]
Hi,
new finding,
If i add "->nonQueued();" it works fine. Takes ages what i don't want, but it works.
The Log shows that the argument "id" is missing on the queued version.

**Comment by freekmurze** [comment]
I'm going to close for now because the package probably isn't in error here, but feel free to keep the converstation going.
