### ISSUE TITLE
Change event from `deleting` to `deleted`

### ISSUE THREAD

**Issue by sharifzadesina** [spatie/laravel-medialibrary#1692]
Sometimes it fails to delete the parent model, cause of reasons like foreign key restrictions.
In these cases, all files are already lost. this is no good.

**Comment by freekmurze** [comment]
Our tests verify that everything is working as intended. Could you please PR a failing test for us to look at?

**Comment by sharifzadesina** [comment]
@freekmurze Why you closed the issue? this is a serious problem. I never said any of the tests fails, please give attention to the example:
```php
$model->getMedia(); // we have X number of medias

$model->delete(); // deleting model fails cause of SQL error

$model->getMedia(); // we have 0 number of medias, but the model still exists
```
This is cause of `deleting` method [here](https://github.com/spatie/laravel-medialibrary/blob/master/src/HasMedia/HasMediaTrait.php#L41).

**Comment by freekmurze** [comment]
Your initial description was unclear. Now I understand your suggestion. I'll discuss this change with our team and come back to this.

**Comment by sharifzadesina** [comment]
@freekmurze Thank you.
I checked the history of the file. It seems the event was `deleted` before, and it changed by a PR to `deleting`.
Please check [this](https://github.com/spatie/laravel-medialibrary/commit/9bb823c45530e2184efa125d6c806a9d818da732#diff-8246722ea432067e07204c941d75195b).

**Comment by sharifzadesina** [comment]
This issue is related to PR #808

**Comment by freekmurze** [comment]
I think we should keep the current behaviour, so that model can be used in a custom path generator.

**Comment by sharifzadesina** [comment]
@freekmurze Current behavior causes serious bugs in production if the SQL query fails (this can happen many times) if we change the event to `deleted` the custom path generator will also work, cause the model will be removed from the database but its attributes are already loaded to memory and are accessible.

**Comment by freekmurze** [comment]
I've decided to keep the current behaviour. I don't think this is a big problem as not many people are reporting issues with this. 

For your current project, make sure you don't have queries failing, and if they, you'll need to manually fix this.

We'll probably improve on this behaviour in the next major version of the package.

**Comment by kshailoobekuulu** [comment]
> I've decided to keep the current behaviour. I don't think this is a big problem as not many people are reporting issues with this.
> 
> For your current project, make sure you don't have queries failing, and if they, you'll need to manually fix this.
> 
> We'll probably improve on this behaviour in the next major version of the package.

I have encountered the same issue. In my model before deleting I have to send curl request to another service and if the request fails I have to show an error message or smth like that. In this case I also  lose all the images. In my opinion it would be great to delete media after deleting event.
