### ISSUE TITLE
issue with inserting a new record

### ISSUE THREAD

**Issue by halah-m** [spatie/laravel-medialibrary#1693]
Hello,

My code used to work when I insert a new record in the media table
`$model->addMediaFromUrl($url)->withCustomProperties([
   'header' => 'headers'
 ]
)
->toMediaCollection('web');`

but now I recive this error `Array to string conversion` in this line `->toMediaCollection('web')`

Laravel: 6.10.1
spatie/laravel-medialibrary: 7.18.0
PHP: 7.2

**Comment by gkarugi** [comment]
@halah-m I am experiencing the same issue with saving new media. This has come about after upgrading to laravel 6. How did you fix this?
