### ISSUE TITLE
Compatibility Questipn

### ISSUE THREAD

**Issue by MathiasWeisheit** [spatie/laravel-medialibrary#1694]
Hi, I want to use your great lib.
can I use it with laravel 6.
Is it possible to use laravels secure Private storage instead of public?
can I use it with api routes?

**Comment by freekmurze** [comment]
Yes, yes and yes.

**Comment by MathiasWeisheit** [comment]
Great!!!!
I will try it.

**Comment by MathiasWeisheit** [comment]
Do you have an config example für the private storage?

**Comment by freekmurze** [comment]
No, you just have to use a disk who's path is not in the public directory. For more info on disk head over to the Laravel docs.
