### ISSUE TITLE
getMedia('') returns all media, is this intended behaviour?

### ISSUE THREAD

**Issue by ju5t** [spatie/laravel-medialibrary#1697]
I know we can use $item->media to get all media for a selected item, but I prefer the same output as getMedia(). As it turns out, you can run `getMedia('')` and pass an empty `$collectionName` as argument. This will load all media with `loadMedia()` and supports empty strings.

https://github.com/spatie/laravel-medialibrary/blob/9fa2989f826da065d098f6f865cc7ad755c35d33/src/HasMedia/HasMediaTrait.php#L505-#L521

This seems to be expected / intended behaviour. I didn't expect this to be honest. I know it's hard to predict the future but can I expect this to stay like this or did I wake a sleeping dog?

Thanks for all the hard work by the way. It's very much appreciated!

**Comment by freekmurze** [comment]
It's a fair remark, I agree that it's a little bit inconsistent now. Changing this will be a breaking change. I'll fix this in a new major release.

**Comment by freekmurze** [comment]
This has been implemented on the `v8` branch.

**Comment by aliwesome** [comment]
Isn't it a good idea that we could have multiple arguments as `$collectionNames` for input?
```
// same behavior 
$item->getMedia($collectionName);

// expected behavior for multiple collections
$item->getMeida($collectionNames);
```
