### ISSUE TITLE
Conflicting with spatie/laravel-paginateroute

### ISSUE THREAD

**Issue by coding-sunshine** [spatie/laravel-medialibrary#17]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: spatie/string[2.0.0, 1.9.1].
    - Can only install one of: spatie/string[2.0.0, 1.9.1].
    - Can only install one of: spatie/string[2.0.0, 1.9.1].
    - spatie/laravel-medialibrary dev-master requires spatie/string ^2.0 -> satisfiable by spatie/string[2.0.0].
    - Installation request for spatie/laravel-medialibrary dev-master -> satisfiable by spatie/laravel-medialibrary[dev-master].
    - Installation request for spatie/string == 1.9.1.0 -> satisfiable by spatie/string[1.9.1].

**Comment by freekmurze** [comment]
This will be fix in the next release of laravel-paginateroute which will be released later today.

**Comment by sebastiandedeyne** [comment]
Fixed in the latest paginateroute release.

https://github.com/spatie/laravel-paginateroute/releases/tag/1.4.0
