### ISSUE TITLE
ImagickException in Pdf.php line 124: Invalid filename provided

### ISSUE THREAD

**Issue by webcrazy** [spatie/laravel-medialibrary#170]
Hello again

I got like that when I upload pdf file. In local development, It's fine and in production I got error like that.
my server is LEMP with hhvm.
```
ImagickException in Pdf.php line 124: Invalid filename provided
```
And thumbnail for pdf file isn't generate.
Thanks

**Comment by freekmurze** [comment]
There are no guaranties the medialibrary will work with hhvm. I know there's a little subtle differences between php en hhvm that might get in the way.

Are you using hhvm on your local machine as well?

**Comment by webcrazy** [comment]
Sorry It's fixed now. It's permission issue.
