### ISSUE TITLE
Zip file inside a zip file

### ISSUE THREAD

**Issue by gauravmak** [spatie/laravel-medialibrary#1700]
The package is already supporting the [zip file download feature](https://docs.spatie.be/laravel-medialibrary/v7/downloading-media/downloading-multiple-files/) which is great.

We need to let the user download a zip file that contains:
1. A few media items and
2. A zip file containing a few other media items

Is this possible to implement?

Thanks, as always.

**Comment by freekmurze** [comment]
This currently is not possible. You'll have to create such a zip yourself.
