### ISSUE TITLE
Get placeholder value to be used in API response

### ISSUE THREAD

**Issue by martinkolarov** [spatie/laravel-medialibrary#1703]
Any recommended approach to manually get the appropriates placeholder value for a given conversion? I'm using Laravel solely as an API and React in the frontend. 

So far I've come up with the following "hack", but do not believe in any way that this is a proper solution (this is in my base Media model)

```
    /**
     * Extract Placeholder from Srcset
     *
     * @param $conversion
     * @return array|int
     */
    public function getPlaceholder($conversion)
    {
        preg_match('(data:image\/[^;]+;base64[^"]+)', $this->getSrcset($conversion), $match);

        $placeholder = explode(' ', array_shift($match));

        return array_shift($placeholder);
    }
```

The function above returns the base64 placeholder.

**Comment by freekmurze** [comment]
If you're looking for the path to the placeholder, you could also look in the `responsive_images` property on media. The generated place holder should be in there somewhere.
