### ISSUE TITLE
customize image height

### ISSUE THREAD

**Issue by lingotacro** [spatie/laravel-medialibrary#1706]
when i try to define image height it not work only width is set 
this is my model code's
`public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('events_thumb')
            ->width(257)
            ->height(579);
    }`
when i retrive converter image he height is 170

**Comment by freekmurze** [comment]
When using width and height it will try to contain your image within the given width and height. So the actual width and height of the resulting image may differ.

Take a look at our docs, to know more. The section on fits might be interesting for you.

https://docs.spatie.be/image/v1/image-manipulations/resizing-images/
