### ISSUE TITLE
Media not deleting when deleting model instance?

### ISSUE THREAD

**Issue by marbuser** [spatie/laravel-medialibrary#1707]
I'm deleting a model instance and it would appear the media isn't cascading? I swear I had this working before and now it no longer seems to be working?

I've setup my collections in my model like so;
```php
    /**
     * Laravel Media Library Collection Setup.
     */
    public function registerMediaCollections()
    {
        $this->addMediaCollection('icon')
            ->singleFile()
            ->acceptsFile(function (File $file)
            {
                return collect([
                    'image/jpeg', 'image/png'
                ])->contains($file->mimeType);
            });
    }
```
I know I can manually delete it in my destroy controller method, but I'd rather have the automated stuff working to make it way cleaner. :)

Hopefully someone can tell me what I'm missing or changed since I swear this was working yesterday. Also I'm using S3 if that makes a difference, but these aren't even being removed from the DB so I assume the delete event isn't even being executed.

**Comment by StApostol** [comment]
Are you using HasMediaTrait? 
Also, check that your models have correctly `boot` methods.

**Comment by ziming** [comment]
Seem similar to this

https://github.com/spatie/laravel-medialibrary/issues/1543

**Comment by StApostol** [comment]
It’s just that when I rewrote boot in the model, some boot methods from traits fell off

**Comment by marbuser** [comment]
@StApostol Can you be a bit more specific and provide an example? I'm not entirely sure what you mean.

@freekmurze Why did you close this? It clearly isn't solved. :/

**Comment by StApostol** [comment]
@marbuser I don’t remember exactly, but maybe my code was breaking that I called self in the boot method

can you share your model (traits, boot, version laravel and medialibrary)?

**Comment by marbuser** [comment]
@StApostol Here is one my implementations, as well as my "media" model. As a note, I'm using a custom package for UUID hence why the model class comes from a strange path. :)
```php
<?php

namespace App\Models;

use GoldSpecDigital\LaravelEloquentUUID\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Article extends Model implements HasMedia
{
    use HasMediaTrait, SoftDeletes;
}
```

Media Model:
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\Models\Media as BaseMedia;

class Media extends BaseMedia
{
    public $incrementing = false;

    /**
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function (Model $model)
        {
            if ( is_null($model->getOriginal('id')) ) {
                $model->id = Str::uuid()->toString();
            }
        });
    }
}
```

**Comment by StApostol** [comment]
@marbuser It's strange, I not see problems in code. Have you tried changing the storage to local?

Just if there is no problem locally, then the problem is in API to S3

**Comment by marbuser** [comment]
@StApostol I don't think it's an issue with S3. The package is failing to even remove records from the database on delete.

@freekmurze I really think this needs to be reopened as it seems like an actual bug... It was pretty irresponsible of you to close it so quickly when a discussion about this issue hadn't even taken place.

**Comment by ziming** [comment]
@marbuser I think @freekmurze closed it because it is similar to 

https://github.com/spatie/laravel-medialibrary/issues/1543

So this issue is more of a duplicate.

**Comment by zitooo** [comment]
The problem seems to be the softdelete. My model with associated media used the softdelete and both, the record in the "media" table and the respective folder, were not deleted. I removed the softdelete and the problem is gone.

**Comment by Stehos** [comment]
@zitooo  I would like to ask you abot problem with deleting model and all attached medias to this model.

my model is:
```
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Image\Manipulations;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Product extends Model implements HasMedia
{
    use SoftDeletes;
    use HasFactory;
    use InteractsWithMedia;

```


from the doc: https://spatie.be/docs/laravel-medialibrary/v10/basic-usage/retrieving-media
When a Media instance gets deleted all related files will be removed from the filesystem.

Deleting a model with associated media will also delete all associated files. If you use soft deletes, the associated files won't be deleted.

$yourModel->delete(); // all associated files will be deleted as well


But when I try to delete my model via tinker like:
`Product::find(5448)->delete();`

Only the model is marked as deleted (column deleted_at is updated)

But all media still exist and all files are still on disk.

I tried to remove **use SoftDeletes;** but without result.


Thank you for your reply.
