### ISSUE TITLE
Sorting Media model with spatie/eloquent-sortable ?

### ISSUE THREAD

**Issue by Okipa** [spatie/laravel-medialibrary#1708]
Hello there,

Would you consider to implement your own `spatie/eloquent-sortable` package on the `Media` model instead of the built-in sorting trait ?

Currently, if we try to add the `spatie/eloquent-sortable` trait to a custom `Media` model, we have conflicts with the built-in trait that are not easy to solve (I am struggling with this right now !).

I think this would not be a breaking change and the media model would be empowered with sorting abilities that are maintained on a specific package.

Thoughts ?

**Comment by Okipa** [comment]
In fact, according to the [PHP doc](https://www.php.net/manual/en/language.oop5.traits.php) we could override the `IsSorted` trait in the custom `Media` model like this:

```php
use IsSorted, SortableTrait {
        SortableTrait::scopeOrdered insteadof IsSorted;
        SortableTrait::setHighestOrderNumber insteadof IsSorted;
        SortableTrait::getHighestOrderNumber insteadof IsSorted;
        SortableTrait::determineOrderColumnName insteadof IsSorted;
        SortableTrait::setNewOrder insteadof IsSorted;
        SortableTrait::shouldSortWhenCreating insteadof IsSorted;
    }
```

But this is currently not possible because of the difference in the `scopeOrdered` signature method.

**Comment by freekmurze** [comment]
For the vast majority of users, the light implementation of sortable works good enough. 

Right now, I don't want to add a new dependency for media library.

**Comment by Okipa** [comment]
You're right, this is a sufficient implementation for most of users and your wish to keep this package as light as possible is fully understandable. After a second thought, I would do exactly the same.

I just still see an annoying point here and I wonder if there would be a way to solve this : providing the ability to set our own `Media` model allows us to empower it with additional abilities or to customize treatments, which is just great ! But in this precise case, the use of the `IsSorted` trait in the Media model prevents us to implement a custom sorting treatment like adding your `eloquent-sortable` trait or another one: there is no way to disable the use of the `IsSorted` trait to remove the built-in sorting behavior.

But I may miss something here ? How would you do this if you would have to ?
