### ISSUE TITLE
Always getting the same extension in the conversion path 

### ISSUE THREAD

**Issue by ivanvermeyen** [spatie/laravel-medialibrary#171]
Hi

I have an Eloquent model that has a few media collections, each with a number of conversions:

        $this->addMediaConversion('thumb')
            ->setManipulations(['w' => 200, 'h' => 100, 'fit' => 'max', 'fm' => 'png'])
            ->performOnCollections('logo');

        $this->addMediaConversion('thumb')
            ->setManipulations(['w' => 400, 'h' => 400, 'fit' => 'crop', 'fm' => 'jpg'])
            ->performOnCollections('cover');

The logo should always be a PNG, the cover a JPG.
These conversions are successfully saved in the correct format.

But when I try to get the path to a conversion, it always returns a PNG extension, no matter if it's a cover or a logo. The media ID in the path is correct though.

        $media = $this->getFirstMedia('cover');

        if ($media) {
            return $media->getPath($conversion); // returns /home/vagrant/..../storage/media/4/conversions/thumb.png
        }

I've been trying to find out how it determines the extension, but I keep getting lost :)

Hope you can shine a light on this. Maybe I'm missing something obvious.

**Comment by freekmurze** [comment]
[This is the line of code that figures what extension the url should have](https://github.com/spatie/laravel-medialibrary/blob/master/src/UrlGenerator/BaseUrlGenerator.php#L87). 

Try to strategically place some var_dump statements to see where it goes wrong. You're also welcome to submit a failing test.

**Comment by ivanvermeyen** [comment]
Thanks for the pointer :) I think I found it...
I'm using the same conversion name for different collections on the same model.
A `thumb` for a PNG logo and a `thumb` for a JPG cover.

On [this line](https://github.com/spatie/laravel-medialibrary/blob/master/src/Conversion/ConversionCollection.php#L40) the collection of all of the model's media conversions is searched for the first conversion name match. But it doesn't check if the collection matches too.

So on [this line](https://github.com/spatie/laravel-medialibrary/blob/master/src/Media.php#L78) `getByName()` returns the first `thumb` conversion that it finds, which is of course always the same one.

I don't know if you want to allow for duplicate conversion names in this way. It seemed logical when I was writing it, but I could also just use unique names. :)

**Comment by freekmurze** [comment]
Yup, you're right: there is a problem if some conversions have the same name. In my mind conversion names should always been unique, but the code does not enforce that. 

I'm quite hesitant on adding an exception when a collection name is not unique because that would be a breaking change. So you're best option now would indeed to use unique names.

In any case, thanks for bringing this to my attention. I'll address it when creating a next major version.
