### ISSUE TITLE
Feature Request: Folders in Media Stream generated zip file

### ISSUE THREAD

**Issue by ziming** [spatie/laravel-medialibrary#1712]
It will be great if for every media collection we can specify the folder name then all files in that media collection will be in that folder inside the generated zip file.

Would be really helpful when we use MediaStream to create a zip file consisting of files from multiple media collections attached to the same record.

**Comment by freekmurze** [comment]
I'd accept a PR that adds this to the package.

**Comment by hulkur** [comment]
It's not that simple as in first glance.

Simplest way as I see it would be to use `$media->model->getMediaCollection('name')->pathName` in `PathGenerator::getBasePath()`, but `getMediaCollection` calls `registerMediaCollections` and so model will eventually have same collection registered 4 times.

**Comment by ziming** [comment]
Why closed? Is it related to 8.1.0?

**Comment by jomo77** [comment]
Freekmurze just merged my PR #1818 .

Now you can set a Zip-Subfolder for each Media File.

See my PR #1819 for a quick documentation.

**Comment by ziming** [comment]
great if it can be done together with add to media collection

**Comment by ziming** [comment]
Closing this issue as I can do it with @jomo77  approach. Although it's a little troublesome
