### ISSUE TITLE
conversion condition

### ISSUE THREAD

**Issue by forksoft** [spatie/laravel-medialibrary#1715]
Hi everyone!

Thanks for this beautiful package.

But I have a little question.
```php
    public function registerMediaCollections()
    {
        $this->addMediaCollection('adsPhotos')
            ->registerMediaConversions(function (Media $media) {
                $this->addMediaConversion('preview')
                    ->fit(Manipulations::FIT_CROP, 1100, 1100)
                    ->optimize()
                    ->performOnCollections('adsPhotos');
            });
    }
```

How do I different manipulate based on resolution or orientation? For example: If image is vertical - need to add border.

**Comment by freekmurze** [comment]
That behaviour is not possible now. If you want this you'll need to check the orientation, add making the manipulations manually before adding it to the medialib.
