### ISSUE TITLE
How to create medias on different folders according to models names?

### ISSUE THREAD

**Issue by otavio-araujo** [spatie/laravel-medialibrary#1716]
The pattern is to save uploaded medias to folders named 1, 2, 3...

What i want is to save collections on different folders.
For example:

Save category mediacollectio to category folder then 1, 2, 3....

Is that possible to do that?

**Comment by freekmurze** [comment]
You can use a path generator for this: https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-a-custom-directory-structure/
