### ISSUE TITLE
Class 'Illuminate\Foundation\Application' not found

### ISSUE THREAD

**Issue by lowconquer** [spatie/laravel-medialibrary#1718]
Problem to add file to media 
`$target->addMedia($path)
                    ->preservingOriginal()
                    ->toMediaCollection('targets');`

**Laravel Framework** :  Lumen (5.8.12) (Laravel Components 5.8.*)
**spatie/laravel-medialibrary** :  7.8.12

**Comment by freekmurze** [comment]
We don't support Lumen. If possible, upgrade to Laravel.
