### ISSUE TITLE
getMedia(); not working

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#172]
```
Call to undefined method Illuminate\Database\Query\Builder::getMedia()
```
so im trying to call get media on a model but its throwing me this...

any ideas?

**Comment by freekmurze** [comment]
Probably you forgot to call `get()` at the end of your query.

**Comment by kickthemooon** [comment]
no it was much more severe lol, i forgot implements HasMediaConversions and use HasMediaTrait :)
