### ISSUE TITLE
tmp directory is deleted

### ISSUE THREAD

**Issue by sdudasko** [spatie/laravel-medialibrary#1720]
Is there a possibility that when tmp files are handled the tmp directory is deleted? On my local machine, everything is working just fine but when I try to upload a file, it works fine but at some point, the temporary directory is deleted and it stops working since the temporary directory is missing.

I cannot debug when the directory gets deleted.

EDIT:
The temporary directory is not placed in a project folder - it is placed in a server system folders.

**Comment by sdudasko** [comment]
The folder was deleted from the server when tmp dir was empty after handling file upload. guess it's a server preference, or is it?

**Comment by freekmurze** [comment]
Guess so, yeah.
