### ISSUE TITLE
Call to undefined method Symfony\Component\Process\Process::fromShellCommandline()

### ISSUE THREAD

**Issue by marbuser** [spatie/laravel-medialibrary#1722]
Only have this package installed, assume `image-optimizer` is a dependency but at no point do I acces or use it in my code. All I'm doing is running this test to create a new "Product".

```php
    {
        $this->withoutMiddleware(VerifyCsrfToken::class);

        Storage::fake('s3');

        UploadedFile::fake()
            ->image('image.jpg')
            ->storeAs('temp', 'image.jpg');

        $user = factory(User::class)->create();

        $this->actingAs($user)
            ->post('/products', $attributes = [
                'name' => 'A New Product Name',
                'description' => 'A New Product Description',
                'images' => ['image.jpg'],
                ]
            ])
            ->assertRedirect('/products');

        $images = Media::where(['file_name' => 'image.jpg'])->first();

        Storage::disk('s3')->assertExists("{$images->id}/image.jpg");
    }
``` 

This causes the error;
![image](https://user-images.githubusercontent.com/34422459/74102870-73de4680-4b82-11ea-9c89-c18c974a24f0.png)

No clue why it's happening. I recently moved from macOS to Windows (WSL) and on macOS this worked fine.

**Comment by freekmurze** [comment]
I cannot reproduce this. Make sure to update all dependancies to the latest version.
