### ISSUE TITLE
Conversions failing for unknown reason?

### ISSUE THREAD

**Issue by frequentredundancy** [spatie/laravel-medialibrary#1724]
Laravel Media-Library Version: 7.18.2
PHP Version: 7.4.2
Laravel Version: 6.14.0 (It's 6.2 in my composer file but `composer show` is showing 6.14.0 for some reason.)
OS: Windows 10 + WSL (Ubuntu 18.04)

The issue I'm having is that when I define a media conversion on a model like below;
```php
    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->width(640)
            ->height(480)
            ->performOnCollections('images');
    }
```

It doesn't actually generate the conversions, and causes a 502. When running my tests, I also get this error below;
```
PHPUnit\Framework\ExceptionWrapper  : Call to undefined method Symfony\Component\Process\Process::fromShellCommandline()

  at /vendor/spatie/image-optimizer/src/OptimizerChain.php:97
     93|         $command = $optimizer->getCommand();
     94| 
     95|         $this->logger->info("Executing `{$command}`");
     96| 
  >  97|         $process = Process::fromShellCommandline($command);
     98| 
     99|         $process
    100|             ->setTimeout($this->timeout)
    101|             ->run();
```

I initially thought this might be because GD was installed incorrectly or was bugging out, but after reinstalling multiple times as well as trying Imagick as well and having the issue still persist, I'm convinced something else must be causing this, but I have no clue what. I've also noticed someone else posted something similar in the issues but they didn't provide much information about the issue so I figured I'd make my own.

Hopefully someone can provide some ideas or a solution, because as soon as I remove the `registerMediaConversions` function from my model, all my tests pass, the 502 goes away in my real testing, and everything works as intended.

**Comment by staticdreams** [comment]
Have you looked at #1714  ? It helped me.
