### ISSUE TITLE
Image has deleted 

### ISSUE THREAD

**Issue by lingotacro** [spatie/laravel-medialibrary#1725]
all my images on my site have been deleted the storage folder located in the public folder is also empty. I don't know what this is due to.
in the console all images display 404 error

**Comment by freekmurze** [comment]
There's too little info for us to go on. Our tests indicate that the package is working as intended. No other reports around this issue have come in.

 If you find the package is somehow in error, PR a failing test for us to fix, or explain how we can recreate the problem.
