### ISSUE TITLE
Preparing v8

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-medialibrary#1726]
I'm preparing a new major version of the media library. 

I don't have any big new features planned. I see `v8` as a clean up released where we take care of some technical debt and drop support for anything below PHP7.4.

Your contributions are welcome as a PR on the `v8` branch.

If you have feature requests, let me know!

**Comment by salierg** [comment]
Upload media before creating Model would be a very nice feature for this release.
See this thread:

https://github.com/spatie/laravel-medialibrary/issues/1658

**Comment by freekmurze** [comment]
@salierg I'm prepping something behind the scenes that 'll take care of this.

**Comment by dfox288** [comment]
Possibility to dynamically add media conversions to the model would we very great.

**Comment by lcdss** [comment]
Would be great to keep Lumen support (which was broken by a small change in the MediaObserver class to check the Laravel version). I don't know what changes were made and will be made until the v8 gets released, but I believe it wouldn't be hard to keep the support even if it's not something you need to.

**Comment by freekmurze** [comment]
@lcdss  Feel free to submit a fix to the `v8` branch.

**Comment by mattdfloyd** [comment]
Feature request: When adding media from disk to a collection, if the remote file and the media disk are the same, move the remote file to the destination instead of reading and writing streams.

Specifically looking to add a file on S3 located at `tmp/file1.jpg` in BucketX to a media collection using the same bucket on S3.

**Comment by freekmurze** [comment]
@mattdfloyd That's a nice idea. I welcome a fully tested PR that adds this to the package.

**Comment by freekmurze** [comment]
v8 has been released 🎉
