### ISSUE TITLE
Get image sizes syncroniously but resize asynchronously 

### ISSUE THREAD

**Issue by ivandokov** [spatie/laravel-medialibrary#1727]
Sometimes you may need to know all transformations names upfront but still leave the resizing for a queued job. For example if you want to append the img tag with srcset into WYSIWYG editor and store it in the database. The images may take awhile to be processed in the background but that's fine as it won't take long and it is not a disaster to have a missing image for a few seconds until it is generated.

I couldn't find a way to achieve this with the current code.

**Comment by freekmurze** [comment]
This is currently indeed not possible, and kinda hard to achieve without performing the actual transformations.

**Comment by ivandokov** [comment]
Is it possible to extract the img tag generation if we use alternative transformation calculator which is not based on size (kb) calculations but using a fixed sizes or percentage of the original width. Then we will not need to make the transformations upfront to get all the sizes.
