### ISSUE TITLE
Urls generated for s3 multiple disks does not respect config file

### ISSUE THREAD

**Issue by d4mn** [spatie/laravel-medialibrary#1729]
If we have multiple s3 disks when generating urls library hardcoded domain from only s3 disk as in this line
`https://github.com/spatie/laravel-medialibrary/blob/c1b1a607e8f0c89114725d0e4335b0408f9f0687/src/UrlGenerator/S3UrlGenerator.php#L38`

Thanx :)

**Comment by freekmurze** [comment]
This has been solved in the upcoming new major version. See the `v8` branch.

**Comment by d4mn** [comment]
Whoops my bad sorry!
