### ISSUE TITLE
Wrong output extension for conversions

### ISSUE THREAD

**Issue by rcerljenko** [spatie/laravel-medialibrary#1734]
Laravel: 6.15.1
PHP: 7.4
Media library: latest

I've noticed that PNG conversions are stored as JPEGs. In `registerMediaConversions()` I've specified only `width` and `height` and nothing more. Also, I've installed all optimizers from documentation.
in general the problem is that uploaded PNGs originals are fine, but their conversions are stored as JPEGs.

**Comment by gazben** [comment]
Never mind. `keepOriginalImageFormat()`
