### ISSUE TITLE
If using remote filesystem (FTP), removeAllFiles() throws exception

### ISSUE THREAD

**Issue by jruszo** [spatie/laravel-medialibrary#1737]
Hello!

I wrote a simple URL and Path generator, to store media files on FTP backend.
If I store the files like that:
```
images/1/62 - media directory
images/1/62/conversions - conversions directory
images/1/62/responsive-images - responsive images
```

Deleting an image throws exception, as Filesystem.php uses the following order:
https://github.com/spatie/laravel-medialibrary/blob/master/src/Filesystem/Filesystem.php#L144
```       
collect([$mediaDirectory, $conversionsDirectory, $responsiveImagesDirectory])
````
Due to this ordering, first it will delete the mediaDirectory, which recursively removes conversions and responsive-images as well, which results in exception: "local.ERROR: ftp_rmdir(): 4/4/62/conversions: No such file or directory"

I simply put $mediaDirectory  to the end of the list in collect() and it resolved my issue

It seems issues #1625 is caused by this similarly

**Comment by leoflapper** [comment]
@jruszo having the same issue. The only possible solution to fix this issue for now is to edit the file directly?

**Comment by freekmurze** [comment]
I accept a PR that improves this behaviour.

**Comment by DenMette** [comment]
@freekmurze, see my pull request for this issue

**Comment by freekmurze** [comment]
Fixed in latest version.
