### ISSUE TITLE
php 7.4 

### ISSUE THREAD

**Issue by timeshift92** [spatie/laravel-medialibrary#1739]
Type of Spatie\\MediaLibrary\\Models\\Media::$casts must be array (as in class Illuminate\\Database\\Eloquent\\Model)

**Comment by freekmurze** [comment]
Please provide some more info, I don't know if this an error message or a suggestion or...

**Comment by timeshift92** [comment]
Hello, is. My English very bad :(,  this error message, php have require declare field casts as

```
Spatie\MediaLibrary\Models\Media
Need
 array $casts =[ ]
Current
$casts = []
```

**Comment by Cranavvo** [comment]
Can confirm this is happening on my development environment too running PHP 7.4, will need to explicitly declare the type in your classes.

**Comment by freekmurze** [comment]
I still don't understand the problem. All tests are returning green.

**Comment by Cranavvo** [comment]
I discovered why this is happening, it's all to do with when your IDE starts being too much of a smart-ass and type-declaring your class variables, and then automatically matches their supers (in which case the laravel vendor files) and then when you get stuff like Spatie packages, that arent' type defined then.... kaboom.

✌🏼

**Comment by timeshift92** [comment]
> I discovered why this is happening, it's all to do with when your IDE starts being too much of a smart-ass and type-declaring your class variables, and then automatically matches their supers (in which case the laravel vendor files) and then when you get stuff like Spatie packages, that arent' type defined then.... kaboom.
> 
> ✌🏼

Thanks for your work, you have to fork and work = (

**Comment by wmfairuz** [comment]
> I discovered why this is happening, it's all to do with when your IDE starts being too much of a smart-ass and type-declaring your class variables, and then automatically matches their supers (in which case the laravel vendor files) and then when you get stuff like Spatie packages, that arent' type defined then.... kaboom.
> 
> ✌🏼

I'm getting the same error. What do you mean by IDE being too much of a smart-ass? What we can do in this case? Thanks

**Comment by muhghazaliakbar** [comment]
I have same issue :(
