### ISSUE TITLE
502 Bad Gateway, pdf-file uploaded and thumbnail doesn't generate. 

### ISSUE THREAD

**Issue by webcrazy** [spatie/laravel-medialibrary#174]
Hello

I have setup the server with php5.6, nginx, php5-fpm. When I upload the pdf file, it does uploaded and thumbanil doesn't generate and got 502 bad gateway.

I've already done googling almost the whole day and still doesn't work. Any help would be very appreciate.

**Comment by freekmurze** [comment]
Probably your error is caused by server configuration and not by this package. I suspect you'll find an error in the nginx logs of your server.
