### ISSUE TITLE
Making images non publicly accessible?

### ISSUE THREAD

**Issue by techdaddies-kevin** [spatie/laravel-medialibrary#1740]
I feel like this should be possible, but I can't figure out how to do this from reading the docs. We are building a service where the product IS the uploaded image. Therefore, it's important that we protect the original image from being downloaded. The problem is that we need to generate a thumbnail of the image when it's added to the system, and this thumbnail SHOULD be publicly accessible, obviously.

So is there a way to store the original image in a non-public location, but store a specific conversion (In this case the 'thumb' conversion) in a public location? I feel like this is a basic thing and is almost definitely possible, but for the life of me I can't figure out a way to do it.

**Comment by notomato** [comment]
I'm in the same boat...you can use a different disk for source media (private settings) and media library (public settings).

I'm not sure if the library has an option to NOT copy the source image to the location where resized images are generated though.

**Comment by freekmurze** [comment]
In the upcoming `v8` of this package you'll be able to save the conversions on another disk than the original.

Probably `v8` will be released somewhere later this month. We'll provide the steps to upgrade.
