### ISSUE TITLE
ftp_mkdir(): Can't create directory: File exists

### ISSUE THREAD

**Issue by akoSalman** [spatie/laravel-medialibrary#1745]
I want to send files over FTP
Main directory is created and the main file is uploaded, but when conversions are going to be uploaded, I get these erorr.

`
ftp_mkdir(): Can't create directory: File exists {"exception":"[object] (ErrorException(code: 0): ftp_mkdir(): Can't create directory: File exists at /.../public_html/vendor/league/flysystem/src/Adapter/Ftp.php:377)
`

How can I fix it?
Thanks in advance.

**Comment by freekmurze** [comment]
I'm thinking this should be solved in flysystem.

**Comment by masoud-me** [comment]
I have same problem

**Comment by hesamzakerirad** [comment]
Same here, any solutions for this problem?
