### ISSUE TITLE
Displaying responsive images

### ISSUE THREAD

**Issue by diegorodriguezvidal** [spatie/laravel-medialibrary#1746]
Nice package!

The docs says that to display responsive images I just need to place:
`{{ $yourModel->getFirstMedia() }}`  in blade view
once I have  generated the necessary images through:
`$yourModel
   ->addMedia($yourImageFile)
   ->withResponsiveImages()
   ->toMediaCollection();`

I am using collections so I am placing:

`{{ $yourModel->getFirstMedia('my_collection_name') }}` in my blade view.

The problem is I am getting:

`<img src="my-image.jpg">`

instead of:

`<img srcset="/media/1/responsive-images/testimage___medialibrary_original_188_105.png 188w, /media/1/responsive-images/testimage___medialibrary_original_158_88.png 158w, /media/1/responsive-images/testimage___medialibrary_original_132_74.png 132w, /media/1/responsive-images/testimage___medialibrary_original_110_61.png 110w, ...`

 when rendering the page.

Is there anything I am missing?

**Comment by Adamkaram** [comment]
you can do 
php artisan storage:link
and in your config you need to change the default filesystem to public instead of local in filesystem.php config file inside config directory
