### ISSUE TITLE
Issue with getUrl returning duplicate root url

### ISSUE THREAD

**Issue by rovillesarate** [spatie/laravel-medialibrary#1747]
Hi! I am encountering an error when using the getUrl and getFullUrl

The link being returned is 
`http://localhost:8000/storage/http://localhost:8000/storage/30/image-sample.jpg`
instead of
`http://localhost:8000/storage/30/image-sample.jpg`

my .env file 
```
APP_URL=http://localhost:8000
ASSET_URL=http://localhost:8000
```
MediaLibrary config is using the public
`'disk_name' => env('MEDIA_DISK', 'public'),`

FileSystem config
```
        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
```

Tried tweaking the Spatie Local URL generator
```
    public function getUrl(): string
    {
        $url = $this->getBaseMediaDirectoryUrl().'/'.$this->getPathRelativeToRoot();
        $url = $this->makeCompatibleForNonUnixHosts($url);
        $url = $this->rawUrlEncodeFilename($url);
        $url = $this->versionUrl($url);
        return $url;
    }
```
removing the getBaseMediaDirectoryUrl() seems to work
```
    public function getUrl(): string
    {
        $url = $this->getPathRelativeToRoot();
        $url = $this->makeCompatibleForNonUnixHosts($url);
        $url = $this->rawUrlEncodeFilename($url);
        $url = $this->versionUrl($url);
        return $url;
    }
```
but just wondering if i have a wrong configuration that is why this is happening.

Hope to hear from you guys. Thanks

**Comment by cpaciencia** [comment]
I am starting with Laravel, I had the same problem as you.
I solve it:

`php artisan storage: link`

in the config/filesystems.php file
I added
```
'media' => [
             'driver' => 'local',
             'root' => storage_path ('app / public'),
             'url' => '/ storage',
             'visibility' => 'public',
         ],
```

my file config/media-library.php

` 'disk_name' => env('MEDIA_DISK', 'media'),`

in my .env file
`MEDIA_DISK = 'media'`


and run to clear config
`php artisan config: clear`

to test it well and to see the effect, in the developer options your browser disables the cache and put the connection a little slower

Hope this can help you
