### ISSUE TITLE
Retrieving From all Post item

### ISSUE THREAD

**Issue by acitjazz** [spatie/laravel-medialibrary#175]
How to Retrieving From all Post item ?
this is my code

>     
use \Spatie\Medialibrary\Media;
class PostController extends Controller{
public function index()
    {
      $posts = Post::latest('published_at')->published()->get();
      $square150 = $posts->getMedia('thumbnail')->getUrl('square-150');
      return $square150;
    }

but i'm getting error

```
BadMethodCallException in Macroable.php line 81:
Method getMedia does not exist.
```

how to fix it?

**Comment by freekmurze** [comment]
Does your `Post` class use the `HasMediaTrait` ?

http://medialibrary.spatie.be/v3/converting-images/defining-conversions/

**Comment by acitjazz** [comment]
yes this my `post` class
```javascript
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;
class Post extends Model implements SluggableInterface, HasMedia, HasMediaConversions
{
  use HasMediaTrait;

  public function registerMediaConversions()

    {
        $this->addMediaConversion('square-150')
            ->setManipulations(['w' => 150, 'h' => 150, 'fit' => 'crop', 'fm' => 'jpg'])
            ->performOnCollections('thumbnail');
    }
```

**Comment by freekmurze** [comment]
Found it!

This will return al collection of posts:
```
$posts = Post::latest('published_at')->published()->get();
```
You should call the `getMedia`-method on a single Post model.
