### ISSUE TITLE
How to set the visibility of original image private and the conversions public? (S3 storage)

### ISSUE THREAD

**Issue by netorawebagency** [spatie/laravel-medialibrary#1753]
Hello,

I'm using the DigitalOcean Spaces (an S3 compatible block storage) and I have this problem: when I upload an image, I show a blurred one (done by a conversion) and the original one is downloadable only with specific permissions.

Now I noticed that the directory structure that uses medialibrary is like this:

/8/filename.jpg (original one)
/8/conversions/filename.jpg (converted one)

So it's really simple to go back from the converted one to the original: is there a way to set only the original image as private and the conversions as public?

Otherwise, is there a way to generate custom/randomic file names that are different between the original file and converted one? This could be another good way to achieve what I want, because the listing of contents of the directory is prohibited.

**Comment by techdaddies-kevin** [comment]
The upcoming release of this library is supposed to add the ability to store each conversion on a different disk. This should allow you (And me, I'm waiting on this functionality too) to store your low quality images on a public disk and your high quality images on a private disk.

**Comment by fawadahmad** [comment]
Any further updates on this?
I don't want my original image to be publicly accessible by URL. But the conversions should be public.
