### ISSUE TITLE
Putting classes on responsive images

### ISSUE THREAD

**Issue by mokhosh** [spatie/laravel-medialibrary#1754]
Is there any way to put classes on generated html for responsive images?
I know we can publish the view, but that would put the class on all generated responsive images. How about when we wanna put the class in a specific instance?

**Comment by freekmurze** [comment]
Right now, publishing the views is the way the go.

**Comment by mokhosh** [comment]
So we can't have responsive images in one page have a class and in some other page another set of classes?

**Comment by georgeboot** [comment]
You can do something like:

```blade
{{ $model->getFirstMedia()->img('default', ['class' => 'block object-cover w-full h-full lg:h-auto']) }}
```

**Comment by pwnz22** [comment]
> You can do something like:
> 
> ```
> {{ $model->getFirstMedia()->img('default', ['class' => 'block object-cover w-full h-full lg:h-auto']) }}
> ```
> 
> That will render to:
> 
> ```
> <img class="block object-cover w-full h-full lg:h-auto" loading="auto" srcset="srcset here" onload="this.onload=null;this.sizes=Math.ceil(this.getBoundingClientRect().width/window.innerWidth*100)+'vw';" sizes="1px" src="fallback img" width="1500">
> ```

This solution only for media-library v8 ?

**Comment by georgeboot** [comment]
Yes. See https://docs.spatie.be/laravel-medialibrary/v8/advanced-usage/rendering-media/#main
