### ISSUE TITLE
serve images from S3 with cloudfront/cloudflare?

### ISSUE THREAD

**Issue by NoySegal** [spatie/laravel-medialibrary#1756]
I want to serve my S3 images with cloudfront, I've tried to change:
`'domain' => 'https://'.env('AWS_BUCKET').'.s3.amazonaws.com',`
in medialibrary.php to be the link to cloudfront but it doesn't register the change. not sure what I'm doing wrong.

**Comment by lostincode** [comment]
Hi,

You can do something like this (replacing the full value):

```php
    's3' => [
        /*
         * The domain that should be prepended when generating urls.
         */
        'domain' => env('AWS_CLOUDFRONT_URL'),
    ],
```

Then, inside your `.env` file add your cloudfront url:

```
AWS_CLOUDFRONT_URL=https://xxxx.cloudfront.net
```

**Comment by joselara** [comment]
With 8.0 use config/filesystems.php 

```
 's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_S3_CLOUDFRONT'),
        ],
```

**Comment by amouly** [comment]
Is this still being supported? or has been removed?

**Comment by tmrsiteops** [comment]
It seems that the URL is no longer being constructed from the individual `bucket`, `region` and `url` properties of `s3` and now requires that the full URL to the location is set as the `url` property. In my case I wanted to use Linode Object Storage, so I set an env variable, `AWS_URL=https://bucket-name.region-name.linodeobjects.com`, and used that env variable for the value of the `url` property of `s3` in config/filesystems.php. Now the image urls are constructed as expected.
