### ISSUE TITLE
What permission should I set for media-library

### ISSUE THREAD

**Issue by webcrazy** [spatie/laravel-medialibrary#176]
Hello.

I got this error when I try to upload images and pdf files.

```
[2016-03-08 08:43:50] production.ERROR: exception 'ErrorException' with message 'mkdir(): Permission denied' in /home/website/vendor/league/flysystem/src/Adapter/Local.php:350
Stack trace:
.....
```

I tried with giving permission to media folder by 755, 766 [ got above issue ]
When I try with 777, got  502 bad gate way for pdf files only.

In the past, I think it was because of hhvm and I removed. but same issue.

Please help.

**Comment by webcrazy** [comment]
Sorry... It's server incorrect configuration.

**Comment by bertalanimre** [comment]
I have a very similar issue ATM. I can upload a picture without any error, but I cannot replace it with a newly uploaded picture. I have to remove the original first, then I can upload the new one. I'm getting a very similar error message.
`HandleExceptions->handleError(2, 'mkdir(): Permission denied', '/var/www/html/myproject/vendor/league/flysystem/src/Adapter/Local.php', 367, array('dirname' => '31/conversions', 'config' => object(Config), 'location' => '/var/www/html/myproject/public/media/31/conversions', 'umask' => 18, 'visibility' => 'public'))`

What was your answer to your issue?

**Comment by avanisolanki** [comment]
I have the same issue when I upload media queue gets failed with permission denied error message. I created issue for the same https://github.com/spatie/laravel-medialibrary/issues/952.
