### ISSUE TITLE
Setting the 'media' table name before migration runs or prefixing the table at the very least

### ISSUE THREAD

**Issue by VinceG** [spatie/laravel-medialibrary#1763]
As the title states, it seems that using 'media' is going to be a big risk since it's such a common name. if we could set the name in the config or at the very least prefix this table with something else that'll be extremely helpful. 🙏

**Comment by freekmurze** [comment]
You can use a custom media model (see the docs on that) and set the table name on that custom model (take a look for that in the Laravel docs).
