### ISSUE TITLE
Pdf conversation not working in mac.

### ISSUE THREAD

**Issue by depixedprojects** [spatie/laravel-medialibrary#1765]
I am using 
laravel 6.x 
media library: ^7.0.0

Pdf conversation is not working. I followed all document steps.
What  things are necessary to generate thumb from pdf?

```php
use Illuminate\Database\Eloquent\Model;

use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class Client extends Model implements HasMedia
{
    use HasMediaTrait;

    public function registerMediaConversions(Media $media = null)
    {

        $this->addMediaConversion('thumb')
            ->width(368)
            ->height(232)
            ->extractVideoFrameAtSecond(5);
    }

**Comment by Christophvh** [comment]
This is all in the docs. https://docs.spatie.be/laravel-medialibrary/v8/converting-other-file-types/using-image-generators/#pdf

Your driver needs to be Imagick & you need ghostscript.
