### ISSUE TITLE
When installing the package, this message appears

### ISSUE THREAD

**Issue by amenov** [spatie/laravel-medialibrary#1768]
When installing the package, this message appears:
Package spatie/laravel-medialibrary at version ^8.0.0 has a PHP requirement incompatible with your PHP version (7.2.28)

I can not understand what is wrong...

**Comment by freekmurze** [comment]
This package requires PHP 7.4

**Comment by dbarrington** [comment]
Is there any workaround for php 7.3? 7.4 is still pretty new for our production environment.
