### ISSUE TITLE
Order column don't wordk?

### ISSUE THREAD

**Issue by lionalex** [spatie/laravel-medialibrary#1769]
I created a script that give an order_column to my files
`$media->order_column = $ordering_position;
$media->save();`

But when a load the model images
`$product->getMedia("images")`
I have always same list not ordered. Why?

**Comment by francoism90** [comment]
Don't you need to add ordered?
```
$ orderedRecords = MyModel::ordered()->get();
```

**Comment by lionalex** [comment]
The question was related to have list media ordered.
I solved the question:
if I get the media in this way
`$myModel->media`
the list is not ordered. But if I get the media list in this way
`$list = $myModel->getMedia("images")`
the result is ordered.

I hope this solution can help anyone.
