### ISSUE TITLE
Get all galleries and only the first media item

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#177]
So i have a model Gallery.
One object has many media items
Now i want to do this:

get all gallery objects and get the url of the first media item that is attached to the gallery...

any suggestions?

**Comment by sebastiandedeyne** [comment]
Do the results need to be in a specific shape? You could just retrieve all Gallery models, and query the media item when you need it.

```php
$galleries = Gallery::all();

foreach ($galleries as $gallery) {
    echo $gallery->getFirstMedia()->getUrl();
}
```
