### ISSUE TITLE
The root path /tmp is not readable.

### ISSUE THREAD

**Issue by NormanHuth** [spatie/laravel-medialibrary#1776]
Ich bekomme immer die Fehlermeldung: "The root path /tmp is not readable."
Die Temp Ordner haben alle 777 Rechte.
Ich habe diesen Beitrag gefunden, aber die Änderung half leider auch nicht.
https://github.com/spatie/laravel-medialibrary/issues/1293

**Comment by freekmurze** [comment]
Please reopen a new issue in English.
