### ISSUE TITLE
The root path /tmp is not readable

### ISSUE THREAD

**Issue by NormanHuth** [spatie/laravel-medialibrary#1777]
I always get the error message: "The root path /tmp is not readable."
The temp folders all have 777 permissions.
I found this post, but unfortunately the change did not help.
https://github.com/spatie/laravel-medialibrary/issues/1293

**Comment by NormanHuth** [comment]
My Hoster ([All-Inkl.com](https://all-inkl.com/)) changed the temp path and now it's works.

**Comment by damarev** [comment]
Duplicate of #1293
