### ISSUE TITLE
Keep original image format

### ISSUE THREAD

**Issue by triadsk** [spatie/laravel-medialibrary#178]
Hello, 

first of all, thanks for your amazing package! 
We are currently using medialibrary v2 and we're stuck with one problem. Media collections are outputting in one file format (jpg by default), which can be set by 'fm' manipulation. However, we would like to always keep the original file format, meaning that when I upload jpg or png, I would like to always get one or the other, just resized according to manipulations defined. 

How can we do this? We have not come up with any solutions so far. 

Thanks a lot!

**Comment by freekmurze** [comment]
Currently there isn't a way to do this I think. It would be nice feature for the package. When I have time I'll add it to v3 (upgrading from v2 to v3 is very easy). 

If you need this quick, I'd be happy to accept a PR on v3.
