### ISSUE TITLE
N + 1 problem to get the images

### ISSUE THREAD

**Issue by Ehsan1733** [spatie/laravel-medialibrary#1780]
If we have a foreach loop at blade and get the image below the image code

`$modelName->getMedia('posts')->first()->getUrl('medium'))`

Every time the foreach loop is executed, the query is once sent query to the database.
It causes the problem of the n + 1 problem.

How to get in the controller all data with a one query send to the database ?

**Comment by Ehsan1733** [comment]
The solution I found was that

`$post = Post::with('media')->get();`

Is there another solution?

**Comment by freekmurze** [comment]
That is the correct way
