### ISSUE TITLE
Handling large amount of media

### ISSUE THREAD

**Issue by kishoth-dq** [spatie/laravel-medialibrary#1783]
Hi
If we have large number of media files lets say like 1 million having it all on same directory will it be a performance issue? even though file systems are capable of handling more files when a directory grow with many files will it not be slow?
Any advice/suggestions? thanks.

**Comment by freekmurze** [comment]
I've not used this myself with that many objects. Largest collection I used this with runs in the thousands and there it runs fine.

I guess for millions of objects, you'll need to experiment a little bit. If there are any things that can be improved performance wise, send in a PR! 👍
