### ISSUE TITLE
Responsive file names don't follow conversion file names

### ISSUE THREAD

**Issue by pikseli** [spatie/laravel-medialibrary#1784]
Ability to use conversion file namers in v8 was a great addition! Thank you!

However, responsive file names don't respect the format defined in the custom implementation of `ConversionFileNamer`.

I think responsive images should either follow that format or there should also be `ResponsiveImagesFileNamer` allowing custom file names for responsive images too.

Any thoughs?

**Comment by freekmurze** [comment]
Yeah, I agree and I do accept PRs that add this, including tests and updated docs, in a non-breaking way.

**Comment by Nielsvanpach** [comment]
PR merged in v9
