### ISSUE TITLE
Return type declaration must be compatible with HasMedia->media()

### ISSUE THREAD

**Issue by cjlaborde** [spatie/laravel-medialibrary#1785]
Getting this error on the page after setting up 
https://docs.spatie.be/laravel-medialibrary/v8/basic-usage/preparing-your-model/

`Symfony\Component\Debug\Exception\FatalErrorException
Declaration of App\Room::media() must be compatible with Spatie\MediaLibrary\HasMedia::media(): Illuminate\Database\Eloquent\Relations\MorphMany`

I am supposed to fill this method that was added after?
`    /**
     * @inheritDoc
     */
    public function media()
    {
        // TODO: Implement media() method.
    }
`

`
namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Room extends Model implements HasMedia
{
    use InteractsWithMedia;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'home_type', 'room_type', 'booking_type', 'accommodate', 'bedrooms', 'bathrooms', 'listing_name', 'summary', 'address', 'is_tv', 'is_kitchen', 'is_air', 'is_heating', 'is_internet', 'is_active', 'price',
    ];
//    protected $guarded = [];
    /**
     * @var int|string|null
     */

    private $user_id;

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function path()
    {
        return route('rooms.show', $this);
    }

    /**
     * @inheritDoc
     */
    public function media()
    {
        // TODO: Implement media() method.
    }

    /**
     * @inheritDoc
     */
    public function addMedia($file)
    {
        // TODO: Implement addMedia() method.
    }

    /**
     * @inheritDoc
     */
    public function copyMedia($file)
    {
        // TODO: Implement copyMedia() method.
    }

    /**
     * @inheritDoc
     */
    public function hasMedia(string $collectionMedia = ''): bool
    {
        // TODO: Implement hasMedia() method.
    }

    /**
     * @inheritDoc
     */
    public function getMedia(string $collectionName = 'default', $filters = [])
    {
        // TODO: Implement getMedia() method.
    }

    /**
     * @inheritDoc
     */
    public function clearMediaCollection(string $collectionName = 'default')
    {
        // TODO: Implement clearMediaCollection() method.
    }

    /**
     * @inheritDoc
     */
    public function clearMediaCollectionExcept(string $collectionName = 'default', $excludedMedia = [])
    {
        // TODO: Implement clearMediaCollectionExcept() method.
    }

    /**
     * @inheritDoc
     */
    public function shouldDeletePreservingMedia()
    {
        // TODO: Implement shouldDeletePreservingMedia() method.
    }

    /**
     * @inheritDoc
     */
    public function loadMedia(string $collectionName)
    {
        // TODO: Implement loadMedia() method.
    }

    public function addMediaConversion(string $name): Conversion
    {
        // TODO: Implement addMediaConversion() method.
    }

    public function registerMediaConversions(Media $media = null)
    {
        // TODO: Implement registerMediaConversions() method.
    }

    public function registerMediaCollections()
    {
        // TODO: Implement registerMediaCollections() method.
    }

    public function registerAllMediaConversions()
    {
        // TODO: Implement registerAllMediaConversions() method.
    }
}`

**Comment by freekmurze** [comment]
All those added methods are implemented through the `InteractsWithMedia` trait. I think you can just remove those methods in your own class.
