### ISSUE TITLE
Using dropzone error during saving

### ISSUE THREAD

**Issue by Mdpproduction** [spatie/laravel-medialibrary#179]
Hi,
i notice that if i tried to use medialibrary with dropzone, i got an error during save the relationship with media:

> Integrity constraint violation: 1048 Column 'model_id' 

But i don't understand why. Any suggestions ?

**Comment by freekmurze** [comment]
Did you save the model where you want to attach media to?

**Comment by Mdpproduction** [comment]
I've a nested controller like this pages.medias. And i retrieve the model with automatic binding of L5.2. But maybe i'm missing something

**Comment by freekmurze** [comment]
Try to make sure if the model your attaching media to has an id :-)

**Comment by Mdpproduction** [comment]
Ok sorry, always my fault!! You're right
