### ISSUE TITLE
Error when installing , Laravel 7

### ISSUE THREAD

**Issue by anasmahjub1** [spatie/laravel-medialibrary#1790]
Class name must be a valid object or a string

  at vendor/spatie/laravel-medialibrary/src/MediaLibraryServiceProvider.php:33
    29|         ], 'views');
    30| 
    31|         $mediaClass = config('medialibrary.media_model');
    32| 
    33|         $mediaClass::observe(new MediaObserver());
    34| 
    35|         $this->loadViewsFrom(__DIR__.'/../resources/views', 'medialibrary');
    36|     }
    37|

**Comment by anasmahjub1** [comment]
just php artisan config:clear

**Comment by trippo** [comment]
delete bootstrap/cache/config.php
