### ISSUE TITLE
New php-ffmpeg/php-ffmpeg release

### ISSUE THREAD

**Issue by francoism90** [spatie/laravel-medialibrary#1791]
There is a new `php-ffmpeg/php-ffmpeg` v0.15 release, this may cause breaking.

**Comment by freekmurze** [comment]
Media library requires `^0.14`. Composer won't pull in `0.15`, so I think we're good.

**Comment by francoism90** [comment]
@freekmurze Will you update to `0.15`? Seems this added an useful `setInitialParameters` method:
```
$format = new FFMpeg\Format\Video\X264();
$format->setInitialParameters(array('-acodec', 'libopus'));
$video->save($format, 'video.avi');
```

https://github.com/PHP-FFMpeg/PHP-FFMpeg/pull/703

Thanks. :)

**Comment by freekmurze** [comment]
Sure, send a PR for that. If all tests remain green, I'll merge it 👍
