### ISSUE TITLE
Upgrade to v8 - (re)generate uuid's?

### ISSUE THREAD

**Issue by francoism90** [spatie/laravel-medialibrary#1792]
I'm testing the new v8 release and it seems uuid's are only being generated one create and not on update: https://github.com/spatie/laravel-medialibrary/blob/af698ec0ee87bb2131cfe3d31bf25fd0c54526a7/src/MediaCollections/Models/Concerns/HasUuid.php#L12

Would it be better to simple add this to the `HasUuid` trait or maybe to the regenerate command so on upgrade every media record has the correct uuid?

Thanks!

**Comment by freekmurze** [comment]
They only get generated on create by design. Why would you want to have the regenerated on update?

**Comment by francoism90** [comment]
@freekmurze I don't want to regenerate them. I'm upgrading from v7 and would like to fill the records that don't have uuids, which is basically all of them.

**Comment by freekmurze** [comment]
I wanted to keep the trait small and don't want it do handle any responsablities regarding to upgrading.

Users that upgrade are responsible for filling that column themselves the first time.

It can be done with this one liner that I'll add to the upgrade guide.

```
Media::cursor()->each(fn(Media $media) => $media->update(['uuid' => Str::uuid()]));
```
