### ISSUE TITLE
[Discussion] Conversion url helpers

### ISSUE THREAD

**Issue by Christophvh** [spatie/laravel-medialibrary#1797]
Hi, 

Thanks again for the amazing package, we use it all the time in our projects.

We mainly use Laravel for API's (GraphQL or REST) with a React SPA front-end. 
One thing I always add when installing the package is something like the following code, which is in a custom media Model:

```php
    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['full_url', 'conversion_urls'];
    
    /**
     * Adds the full url in case conversions aren't ready yet
    */
    public function getFullUrlAttribute(): string
    {
        if ('spaces' === $this->disk) {
            return $this->getTemporaryUrl(now()->addSeconds(config('media-library.temporary_url_lifetime')));
        }

        return $this->getFullUrl();
    }

    /**
     * Return all the available conversions for the model including the url
     */
    public function getConversionUrlsAttribute(): array
    {
        $conversions = ConversionCollection::createForMedia($this);

        return $conversions->flatMap(function (Conversion $conversion) {
            $conversionUrl = $this->getFullUrl($conversion->getName());
            if ('spaces' === $this->disk) {
                $conversionUrl = $this->getTemporaryUrl(
                    now()->addSeconds(config('media-library.temporary_url_lifetime')),
                    $conversion->getName()
                );
            }

            return [
                $conversion->getName() => $this->hasGeneratedConversion($conversion->getName()) ? $conversionUrl : null,
            ];
        });
    }
```

This way it is easy for graphQL queries or API-resources to always have a conversion_urls[] array available with all the different conversion sizes and their URL. If we use a cloud disk we return a temporary URL otherwise we just return the full URL. 

My question would be, are you open to such a pull request and any suggestion on a more robust implementation before a start on it?

**Comment by freekmurze** [comment]
We've not have many questions to add something like this in the package, so just add this logic to all applicable models in your project.

**Comment by jandante** [comment]
Hi @Christophvh 

That's interesting. Now I'm always iterating over a collection to fetch the media items before returning them to the Inertia view.
This seems the more elegant solution.

Is that the correct usecase?

Best Regards
