### ISSUE TITLE
Store conversions on different disks (disk per conversion)

### ISSUE THREAD

**Issue by techdaddies-kevin** [spatie/laravel-medialibrary#1799]
First off, thank you! for adding the ability to store conversions on a different disk than the original. That has been very helpful! Unfortunately, I hit a roadblock today. Let me describe the scenario:

Administrator (Non technical user) is uploading massive photos for sale via his site.  The end user is NOT purchasing these huge photos, though. The end user is only purchasing photos that are 1920x1080, give or take. In other words, these uploaded photos need to be downsized. We do not need to keep the original massive images around after they've been resized. However, because these photos are for sale, they must be protected and not publicly accessible. Unfortunately, with the current system, I cannot tell medialibrary to put some conversions (The 1920x1080 images) on a private disk and some conversions (The thumbnails) on a public disk unless I'm just missing something obvious here.

Here's some code to hopefully describe my issue:

```php
$this->addMediaCollection('main') //Main image; Administrator is uploading a 6000x3000 image
            ->useDisk('products') // We want to store the big image on a private disk
            ->storeConversionsOnDisk('public') // We want to store the thumbnails on a public disk
            ->singleFile()
            ->registerMediaConversions(function (Media $media) {
                $this->addMediaConversion('thumb')
                    ->width(100)
                    ->height(100);

                $this->addMediaConversion('watermarked')
                    ->width(1280)
                    ->height(720)
                    ->watermark(storage_path('watermark.png'))
                    ->watermarkPosition(Manipulations::POSITION_CENTER);
        });
```

Is it possible to change the above code so that the original upload is resized to 1920x1080 and still be stored on a private disk? Ideally, I'd really just like the ability to resize the file in-place rather than registering a conversion for it, but I don't think that's currently possible.

**Comment by freekmurze** [comment]
Thanks for clearly explaining your issue. Storing specific conversions on specific disks is quite... specific. I think that not many people need this functionality, so I'm not going to add this behaviour in the package now, but I'll reconsider this when working on a new major version.

What you could do, is to add your files multiple to the media lilbrary. You could use custom properties on the media to keep track which ones belong together. It's not ideal I know.

**Comment by techdaddies-kevin** [comment]
I understand, but to reiterate, I don't necessarily need that functionality. If there was simply a way to alter the original file in place, that would solve my issue completely. There is definitely a use case for that, like in my example where we are allowing 30mb uploads but we want to resize them down and discard the original huge file. This way we still have an "original" to run our conversations against but it's not ridiculously massive.

**Comment by techdaddies-kevin** [comment]
Actually, looks like I can probably achieve what I want using an event listener on the `MediaHasBeenAdded` event to resize the original in-place before the conversions take place.

**Comment by freekmurze** [comment]
Or you could modify the image before actually adding it to the medialib.

**Comment by techdaddies-kevin** [comment]
Using a third-party library that interfaces with Nova to do the media adding and it doesn't give me a way to do that, unfortunately.

Just wrapped up the event listener and it works great. Just need to be sure to update the filesize column in the media table after resizing so that downloads continue to function. Commenting here for posterity / future users needing a solution to this scenario.
