### ISSUE TITLE
if I don't specify registerMediaConversions method in my model then its giving me error

### ISSUE THREAD

**Issue by coding-sunshine** [spatie/laravel-medialibrary#18]
If I don't specify registerMediaConversions method in my model using the trait it gives me following error :
Call to undefined method Illuminate\Database\Query\Builder::registerMediaConversions()

**Comment by coding-sunshine** [comment]
I don't want to convert files still I have to add a blank registerMediaConversions function to the model.
any solution.

**Comment by freekmurze** [comment]
I'll fix this in the next release, probably somewhere end of this week.

**Comment by freekmurze** [comment]
Version 2.2.0 adds a `hasMediaWithoutConversions`-interface
