### ISSUE TITLE
Keeping original file names with suffix

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#180]
How hard would it be to modify this AMAZING package to keep the original file name in the conversions but just add the conversions that a user defined in the model as a suffix like blablabla-200x100?

I think it would be nice, what do you guys think?

**Comment by freekmurze** [comment]
That's a good suggestion. I'll keep this in mind when creating the next major version of the package. (ETA: in next half year).

If you need this quick, I'd accept a non-breaking PR.

**Comment by grumpysi** [comment]
+1 for this

**Comment by tomcoonen** [comment]
+1

**Comment by thequiet** [comment]
+1

Will help with many user's SEO efforts. Thanks for the great package.

**Comment by freekmurze** [comment]
You all will be happy to know that this is now implemented in `v7` of the medialibrary, which will be released early next year.

If you have a file named `my-awesome-picture.jpg` and a conversion on in named `thumb` the derived image will be named `my-awesome-picture-thumb.jpg`

**Comment by thequiet** [comment]
@freekmurze Awesome!! This is a much welcome addition - thank you for the update. Excited to use v7.

**Comment by plakhin** [comment]
Is this available as an additional option or an only available option?

**Comment by freekmurze** [comment]
This will be the only available option.

**Comment by plakhin** [comment]
please leave the option to not include original filename in derived image filename, I see filenames in local languages with various additional symbols very often and it looks too messy...
