### ISSUE TITLE
[8.x] Media conversions breaks when using Cached Adapter

### ISSUE THREAD

**Issue by rcerljenko** [spatie/laravel-medialibrary#1800]
PHP version: 7.4.4
Laravel version: 7.3
Media Library version: 8.0.6

Following [Laravel docs](https://laravel.com/docs/7.x/filesystem#driver-prerequisites), user is advised to use `league/flysystem-cached-adapter` package when using remote storage (like AWS S3). The easiest way to use it is to modify AppServiceProvider boot() method and do something like this (memory cache):
```
use League\Flysystem\Filesystem;
use Illuminate\Support\Facades\Storage;
use League\Flysystem\Cached\CachedAdapter;
use League\Flysystem\Cached\Storage\Memory;

Storage::extend('s3', function ($app, $config) {
	return new Filesystem(new CachedAdapter($app['filesystem']->createS3Driver($config)->getDriver()->getAdapter(), new Memory));
});
```

Doing so breaks file upload with following error:
https://imgur.com/a/OGZZY9L

But the strange thing is that the file actually gets uploaded. The library throws that error when trying to run specified media conversions for that model. It's trying to get the path prefix from the cached adapter.

My media conversions are (just one):
```
public function registerMediaConversions(?Media $media = null): void
{
	$this->addMediaConversion('thumb')
		->width(828)
		->height(828)
		->keepOriginalImageFormat()
		->nonQueued();
}
```

EDIT: This was not the case with v7 of the library if that helps.

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.
