### ISSUE TITLE
Spatie\MediaLibrary\Support\UrlGenerator\BaseUrlGenerator::getDiskName() must be of the type string, 					null returned

### ISSUE THREAD

**Issue by eslam2010011** [spatie/laravel-medialibrary#1802]
Spatie\MediaLibrary\Support\UrlGenerator\BaseUrlGenerator::getDiskName() must be of the type string,
					null returned

lib/v8.0.6

**Comment by alibarthi** [comment]
Hi,

Please see https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md , doing the following will solve it.

> Add a conversions_disk field to the media table (you'll find the definition in the migrations file of the package) and for each row copy the value of disk to conversions_disk.

I`ve made the same mistake and missed that line too 😄

**Comment by eslam2010011** [comment]
Thank you

**Comment by upcoders** [comment]
Helped me, too.

**Comment by nikitabuida** [comment]
`Media::cursor()->each(fn (Media $media) => $media->update(['conversions_disk' => $media->disk]));`

**Comment by ArmandoRiveroPi** [comment]
This solved it for me, similar to the previous comment from @nikitabuida but in SQL terms:
```sql
update media set conversions_disk = disk where conversions_disk is null;
```
