### ISSUE TITLE
heroku 

### ISSUE THREAD

**Issue by eslam2010011** [spatie/laravel-medialibrary#1807]
When I upload a large 5mb file this bug occurs. Is there a solution to this? Thank you.

 "POST /api/upload HTTP/1.1" 503 299 "-" "PostmanRuntime/7.24.0
2020-03-29T19:37:30.037700+00:00 heroku[router]: sock=backend at=error code=H18 desc="Server Request Interrupted" method=POST path="/api/upload" host=still-harbor-49571.herokuapp.com request_id=e5e1811e-0dd4-46f6-9b82-853aae1c7143 fwd="156.209.117.224" dyno=web.1 connect=1ms service=48354ms status=503 bytes=473 protocol=https

**Comment by eslam2010011** [comment]
this is what Heroku says about H18 error: "Either the client socket or backend (your app’s web process) socket was closed before the backend returned an HTTP response. The sock field in the log has the value client or backend depending on which socket was closed." see https://devcenter.heroku.com/articles/error-codes#h18-request-interrupted

**Comment by eslam2010011** [comment]
and this is happening not every time. Sometimes I can upload a file without problems. I think I know what's going on...

**Comment by eslam2010011** [comment]
upload a very small file (1Kb), you won't have an error. The problem happens when the file is long enough so that Heroku drops connection with our app

**Comment by freekmurze** [comment]
I'm thinking the error is more related to Heroku than this package.

**Comment by Haoui-Hamza** [comment]
the same issue  for me and i think that the error is related to Heroku
