### ISSUE TITLE
PHP 7.4.1 Version Check Error

### ISSUE THREAD

**Issue by DubStepMad** [spatie/laravel-medialibrary#1809]
Hi, I am currently getting the following error:
`- spatie/laravel-medialibrary 8.0.6 requires php ^7.4 -> your PHP version (7.4.1) overridden by "config.platform.php" version (7.3.2) does not satisfy that requirement.`

**Comment by freekmurze** [comment]
The solution is in the error message. In your composer.json you must set the `config.platform.php` to `7.4`.
