### ISSUE TITLE
accepts('audio/*')

### ISSUE THREAD

**Issue by elshobokshy** [spatie/laravel-medialibrary#1810]
Hello,

        $this->addMediaCollection('audio')
            ->accepts('audio/*')
            ->maxFileSize(50 * 1000 * 1000)
            ->singleFile();

In these few lines, `accepts('audio/*')` converts my .mp3 to .mpga, any idea how to prevent that?

**Comment by freekmurze** [comment]
The medialibrary does nothing to convert audio, so probably caused by something in your project.
