### ISSUE TITLE
syntax error, unexpected '$conversion' (T_VARIABLE), expecting ',' or ')'

### ISSUE THREAD

**Issue by cjlaborde** [spatie/laravel-medialibrary#1814]
::Composer\Autoload\includeFile
vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Media.php:174

The error message is showing that the issue is here.

` public function getMediaConversionNames(): array

    {

        $conversions = ConversionCollection::createForMedia($this);

 

        return $conversions->map(fn (Conversion $conversion) => $conversion->getName())->toArray();

    }`
I had this error before and suddenly appeared.
It got fixed by restarting my OS and now appeared again.

Here is the Network Preview.

Symfony\Component\Debug\Exception\FatalThrowableError: syntax error, unexpected '$conversion' (T_VARIABLE), expecting ',' or ')' in file /home/john/Sites/real/vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Media.php on line 174

#0 /home/john/Sites/real/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/john...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Spatie\\MediaLib...')
#2 /home/john/Sites/real/vendor/spatie/laravel-medialibrary/src/MediaLibraryServiceProvider.php(23): spl_autoload_call('Spatie\\MediaLib...')
#3 [internal function]: Spatie\MediaLibrary\MediaLibraryServiceProvider->boot()
#4 /home/john/Sites/real/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#5 /home/john/Sites/real/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /home/john/Sites/real/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#7 /home/john/Sites/real/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#8 /home/john/Sites/real/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#9 /home/john/Sites/real/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\Container\Container->call(Array)
#10 /home/john/Sites/real/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(839): Illuminate\Foundation\Application->bootProvider(Object(Spatie\MediaLibrary\MediaLibraryServiceProvider))
#11 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Spatie\MediaLibrary\MediaLibraryServiceProvider), 21)
#12 /home/john/Sites/real/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): array_walk(Array, Object(Closure))
#13 /home/john/Sites/real/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#14 /home/john/Sites/real/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(219): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#15 /home/john/Sites/real/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(156): Illuminate\Foundation\Application->bootstrapWith(Array)
#16 /home/john/Sites/real/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Foundation\Http\Kernel->bootstrap()
#17 /home/john/Sites/real/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#18 /home/john/Sites/real/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#19 /home/john/.composer/vendor/cpriego/valet-linux/server.php(208): require('/home/john...')
#20 {main}

I am using PHP 7.4 on Ubuntu 18.04 LTS.

**Comment by freekmurze** [comment]
This error indicates that your are not running the right PHP version. 

Please check it properly: http://freek.dev/php-version

**Comment by padre** [comment]
@cjlaborde I have the same error. Have you been able to fix it?

**Comment by robotNIXX** [comment]
> This error indicates that your are not running the right PHP version.
> 
> Please check it properly: http://freek.dev/php-version

Hello. What version PHP should be used? I got the same issue with PHP v.7.4.4. 
Thank you!

**Comment by thadallender** [comment]
I have the same issue. I'm using:

- PHP v7.4.4.
- laravel 7.6.2
- spatie/laravel-medialibrary 8.2.0

The parse error is occurring on line 174 in vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Media.php:

`return $conversions->map(fn (Conversion $conversion) => $conversion->getName())->toArray();`

**Comment by mmguide2003** [comment]
Same here, too! Using php 7.4.4..

**Comment by aboodlibda** [comment]
same error i need solution

**Comment by freekmurze** [comment]
All the package tests are running fine. The package does bot contain a syntax error. Please use the link above for insteuctions how to properly test your PHP version. Check it on the CLI and in a browser. Post your results here.

**Comment by devfelipereis** [comment]
Same error. 

Here it was happening in the build process. I was using an old version of composer that was using an old version of php.
No I'm using the latest version of composer and the error has gone.

If you are using docker with multstage build, check your composer version.

**Comment by mintymatt** [comment]
### (Solution) Same Error

My issue was with Hyne Laravel Tenancy, you need to make sure it creates the right webserver (nginx/apache2) configuration that matches to the [right PHP FPM version](https://tenancy.dev/docs/hyn/5.3/nginx#set-up). My configuration matched to an exact PHP version of 7.3 (oops).

Example (may be different for you) I needed to update the nginx configuration files from 
```
fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
```
to 
```
fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
```
I also fixed `php-sock` in the `./config/webserver.php` config.

### Local setup

* Using PHP 7.4.4
* (Composer running on PHP 7.4.1), with `"php": "^7.4.0"`
* Laravel 7.0
* Laravel Media Library 8.2

### Error Message

```
ParseError
syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')'
```
`vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Media.php:174`

**Comment by renepardon** [comment]
Same problem with PHP 7.4.5

```bash
PHP 7.4.5 (cli) (built: Apr 16 2020 12:37:51) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies
```

I'm using "spatie/laravel-medialibrary": "^8.2.0",

**Comment by freekmurze** [comment]
@renepardon what about your web environment? Which php version? 

https://freek.dev/1598-how-to-check-which-version-of-php-you-are-running

**Comment by mtx-z** [comment]
I just had the same issue. Thing is, my Webserver was running with PHP 7.4.4, but my CLI was still under 7.3.x.

**1. Test your web server PHP version**

- Create a php file with `<?php phpinfo(); ?>` and check your version
- If your version is incorrect, you need to change which PHP version/installs your webserver is using

**2. From the CLI you are using, do:**

- `php -v` to get the current version
- `php --ini` to find .ini location
- if your version is incorrect, you may need to update your environment PATH to add/edit correct PHP version path to it.

**Comment by AbanoubNassem** [comment]
same issue 

```
PHP 7.4.5 (cli) (built: Apr 18 2020 03:17:54) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies
```

error:

`[2020-04-27 19:29:00] local.ERROR: syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')' {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')' at /Volumes/Data/websites/abcodes/vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Media.php:175)`

**Comment by freekmurze** [comment]
To all seeing this error message: the package does not contain a syntax error. Our tests are running fine. You probably are not using the right PHP version. 

Here are instructions to check it properly in both environment. (running php -v` is not enough) 
https://freek.dev/1598-how-to-check-which-version-of-php-you-are-running
