### ISSUE TITLE
Delete image in a queue

### ISSUE THREAD

**Issue by rodurma** [spatie/laravel-medialibrary#1816]
Hello,

I would like to suggest a feature to delete images in a queue. This would be very useful especially when using amazon S3 for example and you delete a record that has many images linked to it.

Thanks.

**Comment by freekmurze** [comment]
I'll consider adding this to a future version of the medialibrary. For now, handle this situating in your own project by dispatching a job of your own to delete your model and media.

**Comment by dambridge** [comment]
Sorry for the necro bump, but found myself looking at the same situation today. I'd like to delete a model instantly, then queue the actual deletion of associated models (media, comments, etc etc). Just checking to see if this is somehow possible now?
