### ISSUE TITLE
Is Responsive images only for Blade and not vue.js?

### ISSUE THREAD

**Issue by cjlaborde** [spatie/laravel-medialibrary#1817]
I been studying the docs to figure out how to use responsive images with vue.js.

https://docs.spatie.be/laravel-medialibrary/v8/responsive-images/getting-started-with-responsive-images/
This is the blade example
<h1>My greyscale responsive image</h1>
{{ $media('my-conversion') }}

Yet have not figure out how to get the responsive images to display from the Get request with Axios.

**Comment by muhghazaliakbar** [comment]
I have same problem to generate responsive image in vue.js

**Comment by borovez** [comment]
I have this exact same problem... I would like to query for the responsive srcset on demand via an API route for my vue.js

I am generating the responsive images like so:

```
$this->addMediaConversion('thumb')
            ->width(130)
            ->height(130)
            ->fit(Manipulations::FIT_CROP, 130, 130)
            ->withResponsiveImages()
            ->nonQueued();
```
The responsive images are successfully generated, however, when I query for the Media collection with getMedia(), the media objects returned do not contain any data in the responsive_images array:

```
Spatie\MediaLibrary\MediaCollections\Models\Media {#3556
         id: 12,
         model_type: "App\Product",
         model_id: 125,
         uuid: "1a509bbf-dc4d-4e44-9618-6612f0c32a3e",
         collection_name: "product_gallery",
         name: "Hero-image8",
         file_name: "56bb729f53bf74faa4b34b46ac31af11.jpg",
         mime_type: "image/jpeg",
         disk: "public",
         conversions_disk: "public",
         size: 34612,
         manipulations: "[]",
         custom_properties: "{"generated_conversions": {"large": true, "thumb": true, "medium": true}}",
         responsive_images: "[]",
         order_column: 3,
         created_at: "2020-05-05 18:11:21",
         updated_at: "2020-05-05 18:11:21",
},
 ```

**Comment by cjlaborde** [comment]
It seems default image when there is no image is also not working with media library when using vue.js. Getting a Call to a member function getUrl() on null
