### ISSUE TITLE
addMediaFromUrl not working redirect url

### ISSUE THREAD

**Issue by tnduc** [spatie/laravel-medialibrary#1820]
> https://api2.musical.ly/aweme/v1/playwm/?video_id=v07025790000bpagqcvhpliigi473f4g

to

> http://v16.muscdn.com/bf815f9b3fdde0b5b462b1649c464939/5e8df7f2/video/n/v0102/f1e9f16674df453ebb8051c18175ff92/?a=1233&br=1874&bt=937&cr=0&cs=0&dr=0&ds=6&er=&l=202004081012090101890362000C190F01&lr=musically&qs=0&rc=amk6bGxva2ZqczMzPDgzM0ApaGc6Omk3NWQ1N2YzNTZpNmcxMDFkZm1zbl5fLS00LzRzczExM15fMTEwYy9iMS9hLl46Yw%3D%3D&vl=&vr=

use
> addMediaFromUrl("https://api2.musical.ly/aweme/v1/playwm/?video_id=v07025790000bpagqcvhpliigi473f4g")

return file ```playwm.x-empty```

How to fix this problem?

**Comment by alibarthi** [comment]
Hi,

The addMediaFromUrl function needs to use [HTTP context options](https://www.php.net/manual/en/context.http.php). Three quick ways for adding this feature:

1. by adding a new config option. We can override and revert the config at runtime (for example for cases when some urls require autentication). It`s not nice, but avoids the breaking change in option 2. 

2. by adding a new $httpContext param in the addMediaFromUrl function (it will be a breaking change though)

```
public function addMediaFromUrl(string $url, array $httpContext = null, ...$allowedMimeTypes): FileAdder
    {
        if (! $stream = @fopen($url, 'r', false, $httpContext)) {
            throw UnreachableUrl::create($url);
        }
        ...
```

3. a combination of the first two options which allows overriding default config values by merging the config array with the $httpContext param array.

@tnduc Until this feature is available, you can simply override the InteractsWithMedia trait addMediaFromUrl function and use the approach in options 2 above.

**Comment by CheesyTech** [comment]
Has this problem been solved?
