### ISSUE TITLE
MediaLibrary Trait 'App\HasMediaTrait' not found

### ISSUE THREAD

**Issue by apostleyemi** [spatie/laravel-medialibrary#1825]
Pls I am having this error, trying to upload image . Trait 'App\HasMediaTrait' not found.
I am a bit new in Laravel. I am Using Laravel 7

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Spatie\MediaLibrary\Conversion\Conversion;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\Models\Media;

`class Books extends Model implements HasMedia
{
    use  HasMediaTrait;

 
    protected $fillable=[

        	'title',	'author',	'category',	'abstract',	'cost',	'cover',	'book_uploaded',

    ];
}
`
` public function store(Request $request)
    {
        //return $request->all();
        $book=new Books();
        $book->addMedia($request->get('uploadfile'))->toMediaCollection('images');
        return redirect()->back();
    }`

**Comment by vdbelt** [comment]
In `laravel-medialibrary` v8 the trait was renamed to `Spatie\MediaLibrary\InteractsWithMedia`. 

So just replace `use HasMediatrait` with `use InteractsWithMedia` and you should be good to go.

See https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md#from-v7-to-v8
