### ISSUE TITLE
Error in installation medialibrary 8.1

### ISSUE THREAD

**Issue by k90mirzaei** [spatie/laravel-medialibrary#1826]
Hi everyone I'm trying to install media library in laravel 7.4 but it have bellow error:

` Problem 1
    - Installation request for symfony/console 5.0.1 -> satisfiable by symfony/console[v5.0.1].
    - Installation request for spatie/laravel-medialibrary ^8.1 -> satisfiable by spatie/laravel-medialibrary[8.1.0].
    - Can only install one of: symfony/process[v5.0.1, 4.4.x-dev].
    - Can only install one of: symfony/process[4.4.x-dev, v5.0.1].
    - Can only install one of: symfony/process[4.4.x-dev, v5.0.1].
    - Conclusion: install symfony/process 4.4.x-dev
    - Installation request for symfony/process 5.0.1 -> satisfiable by symfony/process[v5.0.1].
`

Whats wrong with this package, As here [link](https://packagist.org/packages/spatie/laravel-medialibrary) explains the package I resolve requirements :

`    "require": {
        "php": "^7.2.5",
        "cyrildewit/eloquent-viewable": "^5.2",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/socialite": "^4.3",
        "laravel/tinker": "^2.0",
        "morilog/jalali": "^3.1",
        "santigarcor/laratrust": "^5.2",
        "symfony/console": "5.0.1",
        "symfony/process": "5.0.1"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },`

**Comment by freekmurze** [comment]
It seems like one of the other dependencies of your app requires Symfony 4 components, while the medialibrary requires Symfony 5.

**Comment by freekmurze** [comment]
The package requires PHP 7.4
