### ISSUE TITLE
Feature suggestion: support config for getResponsableAttachmentName(MediaItem $item)

### ISSUE THREAD

**Issue by assertchris** [spatie/laravel-medialibrary#1830]
As the title suggests, I was wondering if you'd be open to me contributing configuration support for deriving the name of of the downloaded file, in  `toResponse`. I'd also like to add the ability to switch to the `streamDownload` method in case the `stream` method is insufficient...

**Comment by freekmurze** [comment]
Sure, go ahead! Thanks Christoph!
