### ISSUE TITLE
How can i use a CustomGeneratorPath only in a model with media library

### ISSUE THREAD

**Issue by mundix** [spatie/laravel-medialibrary#1831]
Hi , i need some help,  i understand how it work path_generator in the config/medialibrary.php  array, but this is of all medias , i want to create a folder with users and user id, then media and the file 
ex: users/23/media/myfile.jpg, if i use the path_generator, that path i want , isn't saved in the media database, this path work on the fly only ,  is I'm not logged doesn't work  , how i can made that happens

**Comment by simioluwatomi** [comment]
I wrote this CustomPathGenerator some time ago. Note that some classes may have changed.

```
use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\PathGenerator\PathGenerator;

class CustomPathGenerator implements PathGenerator
{
    public function getPath(Media $media): string
    {
        return $media->collection_name . '/' . $media->id . '/';
    }

    public function getPathForConversions(Media $media): string
    {
        return $this->getPath($media).'conversions/';
    }

    public function getPathForResponsiveImages(Media $media): string
    {
        return $this->getPath($media).'responsives/';
    }
}
```

So the top-level name of the folder would be the name of the media collection defined in the model. And the remaining folders will take a cue from it.

For your use case, you could use

```
    public function getPath(Media $media): string
    {
        return $media->model_type. '/' . $media->model_id . '/media';
    }
```

Hope this helps

**Comment by szwss** [comment]
thanks
