### ISSUE TITLE
Files being Moved to the Storage folder and can't be accessed in Blade

### ISSUE THREAD

**Issue by miked1213** [spatie/laravel-medialibrary#1832]
When I upload a file it gets moved to the storage folder in my Laravel project.  I have the storage link setup so it does also get moved to the public folder but when I try to access the file to display it in blade it pulls it from the storage folder and not the public folder. 

Blade code:  <img src="{{ $channel->image() }}" alt="{{ $channel->name }}">

Is there a way to pull it from the public folder so I can access it via blade.

**Comment by freekmurze** [comment]
There's too little info here to help you.
