### ISSUE TITLE
Generate Conversion after Media has been added

### ISSUE THREAD

**Issue by Christophvh** [spatie/laravel-medialibrary#1833]
We are currently working on a preview for 3D models. 

The goal is after you upload a 3D model a headless chrome browser is opened. This renders the 3D model and shows a preview. We take a screenshot with your excellent BrowserShot package. And now it should generate conversions for this image.

Our current setup is. 
- We upload a 3D file in nova 
- We check for the event "MediaHasBeenAdded"
- We generate the screenshot.

I would like to use the custom Image generators, but the problem seems that the conversion is being triggered while the image is being uploaded so not afterward. Since the preview needs the model to be available this won't work.

So any pointers on how to generate conversions for an existing model based on an external image?

**Comment by freekmurze** [comment]
The preferred way would be to let the custom image generator create the screenshot somehow: https://docs.spatie.be/laravel-medialibrary/v8/converting-other-file-types/creating-a-custom-image-generator/

If that is not possible maybe you could use the custom generator to generate a temporary dummy conversion.

Afterwards, in another process generate and store your conversion.
After that replace the temporary dummy conversion. You can find the path with `$media->get path($nameOfYourconsversion)`
