### ISSUE TITLE
Manipulation `useFallbackUrl` does not exist

### ISSUE THREAD

**Issue by cjlaborde** [spatie/laravel-medialibrary#1834]
https://docs.spatie.be/laravel-medialibrary/v8/working-with-media-collections/defining-media-collections/#defining-a-fallback-url-or-path

Based on the example it shows how to for getFirstMediaUrl or getFirstMediaPath

```
use Spatie\MediaLibrary\MediaCollections\File;
...
public function registerMediaCollections(): void
{
    $this
        ->addMediaCollection('avatars')
        ->useFallbackUrl('/images/anonymous-user.jpg')
        ->useFallbackPath(public_path('/images/anonymous-user.jpg'));
}
```

The question is how to make it work for Thumbnails?
Tried this and didn't work
```
    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')
             ->width(300)
             ->height(300)
             ->sharpen(10);

        $this->addMediaConversion('thumb')
            ->useFallbackUrl('/images/rooms/default.png')
            ->useFallbackPath(public_path('/images/rooms/default.png'));
    }
```

Tried this as well and same error
```
    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')
             ->width(300)
             ->height(300)
             ->sharpen(10)
            ->useFallbackUrl('/images/rooms/default.png')
            ->useFallbackPath(public_path('/images/rooms/default.png'));
   }
```

**Comment by samirmh-dev** [comment]
You don't need to add fallback path/URL for conversion. Conversion will be use fallback URL/path of it's parent collection.

**Comment by ajay-patidar** [comment]
> You don't need to add fallback path/URL for conversion. Conversion will be use fallback URL/path of it's parent collection.

It's not using parent collection fallback URL/Path.

```
use Spatie\MediaLibrary\MediaCollections\File;
...
public function registerMediaCollections(): void
{
    $this
        ->addMediaCollection('logo')
        ->useFallbackUrl('/images/anonymous-logo.jpg')
        ->useFallbackPath(public_path('/images/anonymous-logo.jpg'));
}

public function registerMediaConversions(Media $media = null): void
{
    $this->addMediaConversion('small_logo')
             ->fit(\Spatie\Image\Manipulations::FIT_STRETCH, 18, 14)
             ->sharpen(10)
             ->nonOptimized();
}
```
and trying to get the first media URL without conversion like below it's giving fallback URL

`<img src="{{ $model->getFirstMediaUrl('logo') }}">`

But when I'm not getting how I can use the Conversion small logo? below code return null

`<img src="{{ $model->getFirstMediaUrl('small_logo') }}">`

**Comment by samirmh-dev** [comment]
@ajay-patidar 

> > You don't need to add fallback path/URL for conversion. Conversion will be use fallback URL/path of it's parent collection.
> 
> It's not using parent collection fallback URL/Path.
> 
> ```
> use Spatie\MediaLibrary\MediaCollections\File;
> ...
> public function registerMediaCollections(): void
> {
>     $this
>         ->addMediaCollection('logo')
>         ->useFallbackUrl('/images/anonymous-logo.jpg')
>         ->useFallbackPath(public_path('/images/anonymous-logo.jpg'));
> }
> 
> public function registerMediaConversions(Media $media = null): void
> {
>     $this->addMediaConversion('small_logo')
>              ->fit(\Spatie\Image\Manipulations::FIT_STRETCH, 18, 14)
>              ->sharpen(10)
>              ->nonOptimized();
> }
> ```
> 
> and trying to get the first media URL without conversion like below it's giving fallback URL
> 
> `<img src="{{ $model->getFirstMediaUrl('logo') }}">`
> 
> But when I'm not getting how I can use the Conversion small logo? below code return null
> 
> `<img src="{{ $model->getFirstMediaUrl('small_logo') }}">`

because you used wrong function paramters I think 🤔 

It must be:

`<img src="{{ $model->getFirstMediaUrl(COLLECTION_NAME, CONVERSION_NAME) }}">`

Did you defined different media collections for different conversions ? If yes it's wrong way

**Comment by ajay-patidar** [comment]
> @ajay-patidar
> 
> > > You don't need to add fallback path/URL for conversion. Conversion will be use fallback URL/path of it's parent collection.
> > 
> > 
> > It's not using parent collection fallback URL/Path.
> > ```
> > use Spatie\MediaLibrary\MediaCollections\File;
> > ...
> > public function registerMediaCollections(): void
> > {
> >     $this
> >         ->addMediaCollection('logo')
> >         ->useFallbackUrl('/images/anonymous-logo.jpg')
> >         ->useFallbackPath(public_path('/images/anonymous-logo.jpg'));
> > }
> > 
> > public function registerMediaConversions(Media $media = null): void
> > {
> >     $this->addMediaConversion('small_logo')
> >              ->fit(\Spatie\Image\Manipulations::FIT_STRETCH, 18, 14)
> >              ->sharpen(10)
> >              ->nonOptimized();
> > }
> > ```
> > 
> > 
> > and trying to get the first media URL without conversion like below it's giving fallback URL
> > `<img src="{{ $model->getFirstMediaUrl('logo') }}">`
> > But when I'm not getting how I can use the Conversion small logo? below code return null
> > `<img src="{{ $model->getFirstMediaUrl('small_logo') }}">`
> 
> because you used wrong function paramters I think 
> 
> It must be:
> 
> `<img src="{{ $model->getFirstMediaUrl(COLLECTION_NAME, CONVERSION_NAME) }}">`
> 
> Did you defined different media collections for different conversions ? If yes it's wrong way
> 
> for your example:
> 
> `<img src="{{ $model->getFirstMediaUrl('logo', 'small_logo') }}">`

Thank you for your quick reply.
It's working now. but the conversion is not applying on the fallback image.
can you help me with this?

**Comment by samirmh-dev** [comment]
> > @ajay-patidar
> > > > You don't need to add fallback path/URL for conversion. Conversion will be use fallback URL/path of it's parent collection.
> > > 
> > > 
> > > It's not using parent collection fallback URL/Path.
> > > ```
> > > use Spatie\MediaLibrary\MediaCollections\File;
> > > ...
> > > public function registerMediaCollections(): void
> > > {
> > >     $this
> > >         ->addMediaCollection('logo')
> > >         ->useFallbackUrl('/images/anonymous-logo.jpg')
> > >         ->useFallbackPath(public_path('/images/anonymous-logo.jpg'));
> > > }
> > > 
> > > public function registerMediaConversions(Media $media = null): void
> > > {
> > >     $this->addMediaConversion('small_logo')
> > >              ->fit(\Spatie\Image\Manipulations::FIT_STRETCH, 18, 14)
> > >              ->sharpen(10)
> > >              ->nonOptimized();
> > > }
> > > ```
> > > 
> > > 
> > > and trying to get the first media URL without conversion like below it's giving fallback URL
> > > `<img src="{{ $model->getFirstMediaUrl('logo') }}">`
> > > But when I'm not getting how I can use the Conversion small logo? below code return null
> > > `<img src="{{ $model->getFirstMediaUrl('small_logo') }}">`
> > 
> > 
> > because you used wrong function paramters I think
> > It must be:
> > `<img src="{{ $model->getFirstMediaUrl(COLLECTION_NAME, CONVERSION_NAME) }}">`
> > Did you defined different media collections for different conversions ? If yes it's wrong way
> > for your example:
> > `<img src="{{ $model->getFirstMediaUrl('logo', 'small_logo') }}">`
> 
> Thank you for your quick reply.
> It's working now. but the conversion is not applying on the fallback image.
> can you help me with this?

did you check log files? did you see something is not normal here? and check media directory to see if conversions added or not

**Comment by farhad321** [comment]
Hello 
I have this problem .
