### ISSUE TITLE
Permission denied while deleting tmp

### ISSUE THREAD

**Issue by hassanzeaiter** [spatie/laravel-medialibrary#1836]
Every time I attach an image, the media conversion throws an error. It looks like it's trying to delete /tmp to clean up the temp items even after changing `temporary_directory_path`
`rmdir(/users/{username}/tmp/{appname}): Permission denied`

- Laravel 7.2.2
- spatie/laravel-medialibrary 7.19.3
- PHP 7.4.4

I know that this issue must be fixed after https://github.com/spatie/image/pull/45/files but it seems not.

```
if ($this->directoryIsEmpty($conversionResultDirectory) && $conversionResultDirectory !== '/tmp') {
    rmdir($conversionResultDirectory);
}
```

**Comment by freekmurze** [comment]
I cannot reproduce the problem, and the tests are also running file, so I'm thinking this is caused by something specific to your system. Feel free to send a PR that fixes it for you.
