### ISSUE TITLE
syntax error, unexpected '$conversion'

### ISSUE THREAD

**Issue by PixelTijgers** [spatie/laravel-medialibrary#1837]
Yesterday I installed MediaLibrary v.8.0.0 locally. This afternoon, when I tried to load the homepage, I got this error:

`syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')'`

**Rule 174:**
`return $conversions->map(fn (Conversion $conversion) => $conversion->getName())->toArray();`

- File: vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Media.php:174
- Laravel version: 7.0
- Php version: 7.4.5

Any thoughts?

**Comment by freekmurze** [comment]
Make sure you are running PHP 7.4

https://freek.dev/1598-how-to-check-which-version-of-php-you-are-running

**Comment by rabol** [comment]
I have the same issue

And I have php v 7.4.5, so just refereing to a chack of the php version is not really helpful

**Comment by freekmurze** [comment]
Our tests prove that the package is working on PHP 7.4

I still think either your web requests or CLI are not using the right PHP version. The package has no syntax errors.

If you feel the package is in error, please submit a failing test. If you find the root of the problem, let us know.

**Comment by PixelTijgers** [comment]
I can confirm for @freekmurze. My issue was that the CLI said my server was running on PHP version 7.4, which wasn't.

Unfortunately @rabol , I cannot give you the link I used to upgrade my PHP version correctly. But after I had done that, it worked. So this IS a PHP version issue running on your system.
