### ISSUE TITLE
This extension really needs php 7.4?

### ISSUE THREAD

**Issue by fabiomlferreira** [spatie/laravel-medialibrary#1838]
I'm facing a huge problem with the requirement of PHP 7.4, many control panels for webservers don't support yet PHP 7.4. 

I think it's good to use last technologies, but we must be some caution, this extension is highly used and require PHP 7.4 can cause problem for many.

I think a good strategy is this package require the same PHP version that last version of Laravel. What did you think?

**Comment by freekmurze** [comment]
We don't use older versions of PHP anymore. Either upgrade to PHP 7.4 or use an older version of the package.

**Comment by fabiomlferreira** [comment]
Ok I understant that. But I think for the future is a good approach don't require the last versions of php, many systems can use other extensions that don't support it, and it's better do the same that Laravel does, don't require exactly the last versions of PHP but requires one that is stable and don't very old.

Since this is package so used for so many programmers I think this is a good approach.
