### ISSUE TITLE
How to add Multiple Media by URL

### ISSUE THREAD

**Issue by tahirafridi** [spatie/laravel-medialibrary#1840]
Hello guys!
I've checked all the issues but didn't find the answer, also checked the documentation for adding the media via URL in bulk. Is there still any way builtin in the library, for adding the multiple images via URL.

Right now I'm sending all the URL via ajax call to the controller method and then loop the images one by one to save the media, which is taking too much time.

Example code here, at least tell me if there is no official support so I'm doing correct?

![image](https://user-images.githubusercontent.com/4971486/79696492-7b168480-8296-11ea-9ddb-fd2806015e15.png)

**Comment by freekmurze** [comment]
There is no dedicated method to do this indeed.

**Comment by pandisoft** [comment]
#1843

**Comment by srloois** [comment]
Same problem!

**Comment by srloois** [comment]
Same problem! There should be a method to add multiple media and that recognizes the array sent by `<input type="file" multiple>`
