### ISSUE TITLE
add media from s3 url

### ISSUE THREAD

**Issue by gildastema** [spatie/laravel-medialibrary#1843]
i have issue i want to add media from url. 
my media is s3 link.
s3.amazonaws.com/appforest_uf/f1553861654768x167262731893531600/ppimg.jpg.
But i have error

**Comment by abishekrsrikaanth** [comment]
It would easier to advise on the issue if you can add the error information.

**Comment by freekmurze** [comment]
Too little info.

**Comment by pandisoft** [comment]
I have the same issue here, trying to add AWS file URL to modal media, i guess AddMedia() accepts absolute path only

My code i used 
$exists = Storage::disk('article')->exists( $file );
                if ( $exists ){
                    // article disk uses s3 driver
                   // Storage::disk("article")->url($file) this returns AWS file URL
                    $article->addMedia(Storage::disk("article")->url($file))->toMediaCollection('article', 'article_attachments');
                } 
is there a way to attached a URL to modal? instead of re-store the file!
