### ISSUE TITLE
add Media::getMediaConversionNames() method to Media model

### ISSUE THREAD

**Issue by unstoppablecarl** [spatie/laravel-medialibrary#185]
I recently found I needed a way to list the conversion names for an admin control panel where I wanted to list and display all conversions of an image. I was surprised I could not find a way to easily do this (maybe I am missing something?). I extended the `Media` model class and added this method to it. Is there a reason this was left out? Is this worth making a PR for?

```php
    public function getMediaConversions() {
        $collection = ConversionCollectionFactory::createForMedia($this);
        return $collection->map(function ($conversion) {
            return $conversion->getName();
        })->toArray();
    }
```

**Comment by freekmurze** [comment]
I didn't need that function myself and nobody was really missing it, that's why it isn't included in the package.

Your implementation seems ok. I'd accept that if you choose to create a PR for it (please add also add a test to ensure that it works correctly).

**Comment by freekmurze** [comment]
This is included in v4 which will be released somewhere this month.
