### ISSUE TITLE
Which method to use when a file is uploded to s3 directly.

### ISSUE THREAD

**Issue by Luddinus** [spatie/laravel-medialibrary#1852]
Hi, first all great package.

I'm using dropzone to upload a file to s3 directly. Then I receive a callback with the url of the uploaded image.

When I use this:
```
$model->addMediaFromUrl($s3Url)->toMediaCollection();
```
It takes a lot (20 Mb file e.g.). I read the source a little and I realize that it gets the all "file".

I was thinking to use "addMediaFromDisk" but the problem is the same.

```
$temporaryFile = tempnam(sys_get_temp_dir(), 'media-library');
file_put_contents($temporaryFile, $stream);
```

Which method should I use to only save the data in media table? I thought to manually save the record, but maybe I am missing something?

Using the v7 of the package.

Thanks!

**Comment by Luddinus** [comment]
Maybe this issue is related, not sure: https://github.com/spatie/laravel-medialibrary/issues/1669

**Comment by msonowal** [comment]
@Luddinus 
You just need to use the s3 driver on the media and filesystems and it will work

**Comment by Luddinus** [comment]
@msonowal That's not the problem. It works.

The thing is using s3 driver, when you upload one file to s3 directly, spatie media library "downloads" the whole file to get some information of the file (like filesize or whatever).

**Comment by msonowal** [comment]
@Luddinus  thats not true, I even verified that before using as in my all files are uploaded to s3 then linked here,
In the inner it uses league s3 adapter to get meta information by querying api calls you can debug that

**Comment by rick20** [comment]
Hi @Luddinus have you found the solution? I have similar use case. My app directly uploads every file to s3 and I only need to link the url to the media table.

**Comment by Luddinus** [comment]
Hi @rick20,

I use this: https://github.com/spatie/laravel-medialibrary/issues/1669#issue-537721619

and made a class which extends the spatie Spatie\MediaLibrary\Filesystem\Filesystem (then retrieving from laravel ioc)
