### ISSUE TITLE
An error occurred with the name of the table medias' doesn't exist 

### ISSUE THREAD

**Issue by samehdoush** [spatie/laravel-medialibrary#1870]
It has been working fine and the project has been working for a year, but upon updating composer
The following error occurred
Base table or view not found: 1146 Table 'medias' doesn't exist (SQL: select * from `medias` where `medias`.`model_id` in (1) and `medias`.`model_type` = 
But its name is the table in the database "media" not "medias"
It has thousands of rows
What should I do to solve this problem?

Details of the current project:
laravel/framework  v7.10.3
"spatie/laravel-medialibrary": "^7.0.0",

It was working properly to issue 
laravel/framework  v7.9.2

**Comment by AEK-BKF** [comment]
Same here, I've just update the composer, and got that error !!!

**Comment by AEK-BKF** [comment]
I fixed it by renaming the table `media` to `medias`  in Database !

**Comment by lloricode** [comment]
same here
using `PHP7.2`

**Comment by lloricode** [comment]
> I fixed it by renaming the table `media` to `medias` in Database !

that's one of the solution, but this need to be done on library itself

**Comment by lloricode** [comment]
this is occure when updating this

```
vagrant@homestead:~/code/project$ composer update
Loading composer repositories with package information                                                                                                Updating dependencies (including require-dev)         
Package operations: 0 installs, 7 updates, 0 removals
  - Updating doctrine/inflector (1.3.1 => 1.4.0): Loading from cache
  - Updating symfony/polyfill-php72 (v1.15.0 => v1.16.0): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.15.0 => v1.16.0): Loading from cache
  - Updating symfony/polyfill-intl-idn (v1.15.0 => v1.16.0): Loading from cache
  - Updating symfony/polyfill-iconv (v1.15.0 => v1.16.0): Loading from cache
  - Updating symfony/polyfill-php73 (v1.15.0 => v1.16.0): Loading from cache
  - Updating symfony/polyfill-ctype (v1.15.0 => v1.16.0): Loading from cache
Writing lock file

```

**Comment by lloricode** [comment]
@AEK-BKF best solution is you can ovverride model implementation [here](https://github.com/spatie/laravel-medialibrary/blob/7.19.3/config/medialibrary.php#L26)

then in your own model musbe like this
```php
<?php

namespace App\Models;

class Media extends \Spatie\MediaLibrary\Models\Media
{
    protected $table = 'media';
}

```

**Comment by synthor** [comment]
https://github.com/spatie/laravel-medialibrary/issues/1864

**Comment by sgc-fireball** [comment]
PR for 7.x
https://github.com/spatie/laravel-medialibrary/pull/1873

**Comment by lloricode** [comment]
this should be close
