### ISSUE TITLE
Not installing on Laravel 7 

### ISSUE THREAD

**Issue by mohamedhabibwork** [spatie/laravel-medialibrary#1871]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v7.10.3
    - Conclusion: don't install laravel/framework v7.10.3
    - spatie/laravel-medialibrary 6.0.0 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.1.0 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.1.1 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.1.2 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.1.3 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.2.0 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.2.1 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.3.0 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.4.0 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.4.1 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.4.2 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.5.0 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.6.0 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.6.1 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.6.2 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.6.3 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.6.4 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.6.5 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.6.6 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.6.7 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.6.8 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - spatie/laravel-medialibrary 6.6.9 requires illuminate/database ~5.5.0|~5.6.0 -> satisfiable by illuminate/database[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43
, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.3
5, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - spatie/laravel-medialibrary 6.7.0 requires illuminate/database ~5.5.0|~5.6.0 -> satisfiable by illuminate/database[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43
, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.3
5, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - spatie/laravel-medialibrary 6.8.0 requires illuminate/database ~5.5.0|~5.6.0 -> satisfiable by illuminate/database[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43
, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.3
5, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - spatie/laravel-medialibrary 6.9.0 requires illuminate/database ~5.5.0|~5.6.0 -> satisfiable by illuminate/database[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43
, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.3
5, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - spatie/laravel-medialibrary 6.9.1 requires illuminate/database ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by illuminate/database[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v
5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30,
v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5
, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - spatie/laravel-medialibrary 6.9.2 requires illuminate/database ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by illuminate/database[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v
5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30,
v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5
, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - spatie/laravel-medialibrary v6.x-dev requires illuminate/database ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by illuminate/database[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36
, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.3
0, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.
7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - don't install illuminate/database 5.5.x-dev|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.16|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.17|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.2|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.28|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.33|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.34|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.35|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.36|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.37|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.39|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.40|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.41|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.43|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.5.44|don't install laravel/framework v7.10.3
    - don't install illuminate/database 5.6.x-dev|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.1|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.10|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.11|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.12|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.13|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.14|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.15|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.16|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.17|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.19|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.2|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.20|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.21|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.22|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.23|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.24|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.25|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.26|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.27|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.28|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.29|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.3|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.30|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.31|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.32|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.33|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.34|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.35|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.36|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.37|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.38|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.39|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.4|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.5|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.6|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.7|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.8|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.6.9|don't install laravel/framework v7.10.3
    - don't install illuminate/database 5.7.17|don't install laravel/framework v7.10.3
    - don't install illuminate/database 5.7.18|don't install laravel/framework v7.10.3
    - don't install illuminate/database 5.7.19|don't install laravel/framework v7.10.3
    - don't install illuminate/database 5.7.x-dev|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.1|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.10|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.11|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.15|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.2|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.20|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.21|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.22|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.23|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.26|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.27|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.28|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.3|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.4|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.5|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.6|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.7|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.8|don't install laravel/framework v7.10.3
    - don't install illuminate/database v5.7.9|don't install laravel/framework v7.10.3
    - Installation request for laravel/framework (locked at v7.10.3, required as ^7.0) -> satisfiable by laravel/framework[v7.10.3].
    - Installation request for spatie/laravel-medialibrary ^6.0.0 -> satisfiable by spatie/laravel-medialibrary[6.0.0, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.2.0, 6.2.1, 6.3.0, 6.4.0, 6.4.1, 6.4.2, 6.5.0, 6.6.0, 6.6.1, 6.6.2, 6.6.3, 6.6.4, 6.6.5, 6.6.6, 6.6.7, 6.6.8, 6.6.9,
 6.7.0, 6.8.0, 6.9.0, 6.9.1, 6.9.2, v6.x-dev].

**Comment by freekmurze** [comment]
Our tests prove that the package can't be installed fine. Please check your PHP version, Laravel version, other dependancies.

**Comment by manzhos** [comment]
Hi.

make enable:
extension=exif

in your php.ini

(It worked for me :) )

**Comment by artifex-media** [comment]
Same issue, @manzhos suggestion did not fix it as it already was enabled for me.
@mohamedhabibwork were you able to fix it?
