### ISSUE TITLE
[Can't install] on latest [laravel, php]

### ISSUE THREAD

**Issue by scheMeZa** [spatie/laravel-medialibrary#1872]
Reproduce:
1. Install latest laravel
1. Try and install package

Output:
```
    - Can only install one of: symfony/process[4.4.x-dev, v5.0.8].
    - Can only install one of: symfony/process[v4.4.0, v5.0.8].
    - Can only install one of: symfony/process[v4.4.0-BETA1, v5.0.8].
    - Can only install one of: symfony/process[v4.4.0-BETA2, v5.0.8].
    - Can only install one of: symfony/process[v4.4.0-RC1, v5.0.8].
    - Can only install one of: symfony/process[v4.4.1, v5.0.8].
    - Can only install one of: symfony/process[v4.4.2, v5.0.8].
    - Can only install one of: symfony/process[v4.4.3, v5.0.8].
    - Can only install one of: symfony/process[v4.4.4, v5.0.8].
    - Can only install one of: symfony/process[v4.4.5, v5.0.8].
    - Can only install one of: symfony/process[v4.4.6, v5.0.8].
    - Can only install one of: symfony/process[v4.4.7, v5.0.8].
    - Can only install one of: symfony/process[v4.4.8, v5.0.8].
    - Installation request for symfony/process (locked at v5.0.8) -> satisfiable by symfony/process[v5.0.8].
```

```
Installation failed, reverting ./composer.json to its original content.
```

**Comment by freekmurze** [comment]
Our testsuite seems to run fine, so this is likely a problem at your end.

**Comment by tomredhot** [comment]
Same here.
Php 7.4.5
![image](https://user-images.githubusercontent.com/5106847/81519207-bd386080-9340-11ea-85b1-396858af9e34.png)

**Comment by scheMeZa** [comment]
Thank goodness, I've reinstalled almost everything as I can't find anything about this problem using google. Glad someone else has the issue too #progress

**Comment by scheMeZa** [comment]
@freekmurze Can we open the issue again?

**Comment by tomredhot** [comment]
@scheMeZa just check if exif extension is active on your PHP. 
It's good for me, after activating it
(check others requirements too)
![image](https://user-images.githubusercontent.com/5106847/81561541-9ce5c180-9393-11ea-92ee-da3a7656a91d.png)

**Comment by scheMeZa** [comment]
That's embarrassing... Thank you @tomredhot, and I apologise for a useless issue @freekmurze

**Comment by lomotech** [comment]
Just want to ask, why in `composer.json` do not have `ext-exif` is required? I think it will solve this problem right?
