### ISSUE TITLE
Issue with requirements for v8

### ISSUE THREAD

**Issue by ArtA-Seppe** [spatie/laravel-medialibrary#1874]
I want to upgrade from v7 to v8 to be able to use the new `ConversionFileNamer` functionality.
After upgrading to php 7.4 from 7.2, running `composer require spatie/laravel-medialibrary:8.2.6` or `composer require spatie/laravel-medialibrary:">=8.0.0"` throws a requirements error about Laravel v5.8.38. It tells me Laravel 6 or higher is required.
Since the requirements in the [docs](https://docs.spatie.be/laravel-medialibrary/v8/requirements/) state that `Laravel 5.5.0+` is required, this error conflicts with that.

If this is expected behaviour, the requirements in the docs need to get updated.
If not, why is this error thrown?

__My config:__
* Laravel Framework 5.8.38
* PHP 7.4.5
* Mac OS 10.15.4
* ImageMagick 7.0.10-8

**Comment by freekmurze** [comment]
Fixed it in the docs.
