### ISSUE TITLE
InvalidConversion - Changing model relation/regenerating thumbnails

### ISSUE THREAD

**Issue by ralphmorris** [spatie/laravel-medialibrary#1880]
Hi there,

I have a create form which allows users to upload images before it's relation (Post model) is created. To do this I temporarily assign the media item to the current user in a pending state. After the Post is created I swap the model_type and model_id to the Post models class/id.

I have different thumbnails sizes for both the User and Post models so run the below code trigger the regenerating of thumbnails after changing the related model.

```
            Artisan::call('medialibrary:regenerate', [
                '--ids' => $item->id,
                '--force' => true
            ]);
```

However, I'm occasionally seeing Spatie\MediaLibrary\Exceptions\InvalidConversion in Sentry coming up during this regenerate.

Should this work? Or is there a better way to do this? 

Thanks!
Ralph

**Comment by freekmurze** [comment]
I'm thinking this should work, and I don't know where your error is coming from.

We will handle this use case of temporary uploads in the upcoming pro version of this package: https://medialibrary.pro
