### ISSUE TITLE
GD | ImageMagick module not available with this PHP installation

### ISSUE THREAD

**Issue by tnduc** [spatie/laravel-medialibrary#1887]
I use **laradock**.

 Defining conversions 
```
$this->addMediaConversion('thumb')
     ->width(368)
     ->height(232)
     ->extractVideoFrameAtSecond(20)
     ->performOnCollections('videos');
```

`PerformConversionsJob` fail when I use `GD`or `ImageMagick` 

### Stacktrace & Additional info:
![Annotation 2020-05-18 151209](https://user-images.githubusercontent.com/26267956/82189706-04fb5100-991a-11ea-932f-0fcd50e31670.png)
![Annotation 2020-05-18 151228](https://user-images.githubusercontent.com/26267956/82189716-0af13200-991a-11ea-8f9c-32cbe0b037d1.png)

I tried using `intervention/image` to process images with ` imagick` it work properly.

sample code
```
$manager = new Intervention\Image\ImageManager(array('driver' => 'imagick'));

$manager->make($path)->resize(300, 200)->save('bar.jpg');
```

**Comment by freekmurze** [comment]
Installing gd or imagick on Laradock is out of scope for this issue tracker.

**Comment by tnduc** [comment]
> Installing gd or imagick on Laradock is out of scope for this issue tracker.

I installed imagick and gd on `php-fm` and `workspace`, and I also tried using the `intervention/image` library to check if imagick worked.

![Annotation 2020-05-18 214800](https://user-images.githubusercontent.com/26267956/82227162-95a15380-9951-11ea-9bb4-f71f2a00b3b0.png)
![Annotation 2020-05-18 214726](https://user-images.githubusercontent.com/26267956/82227168-9803ad80-9951-11ea-9a62-856466abc5c2.png)
