### ISSUE TITLE
medialibrary:regenerate on S3

### ISSUE THREAD

**Issue by PhilMarc** [spatie/laravel-medialibrary#189]
I am using a S3 disk and my files (pictures) are displaying correctly using Laravel 5.2 and latest media-library package.

At this point I required "league/flysystem-aws-s3-v3".

I get the following error when trying to regenerate thumbs on s3
`[League\Flysystem\FileNotFoundException]  File not found at path: 1/5534273b0e867.jpg`

So I changed it back to local driver, and I still have the same error, simply because my rows in the SQL media table are set with 's3' in the 'disk' column.
Maybe it would be useful to have an option to store locally AND on s3 at the same time. Or maybe a command to switch back and update the 'disk' column automatically?

**Comment by freekmurze** [comment]
Currently, image regeneration is only supported on local disks. I'll add a little note on that in the docs.

**Comment by Syrok** [comment]
It (image regeneration) working for me on S3.
But sometimes got this error "File not found at path" too.

**Comment by PhilMarc** [comment]
Indeed it is working! I placed my files at the root of the S3 bucket, and now the regeneration of the thumbnails work.
They were put in a subfolder before, which Cloudfront was redirecting to, so the pictures displayed successfully, but the regeneration was looking for the files at the root of the bucket, and not in the /media subfolder. 
This is maybe something you can specify in the filesystems.php config file under the S3 array, but for now I'd rather leave it at the root.
