### ISSUE TITLE
[Question] Manipulation to crop by ratio

### ISSUE THREAD

**Issue by sanjitkung** [spatie/laravel-medialibrary#1899]
So far I did not find anything related to it. Seems like I have calculate the dimensions by my self.

- How can I get current file  that is under manipulation in `registerMediaConversions` method to calculate dimensions?
- Is there any other existing way to achieve the same?

**Comment by freekmurze** [comment]
I don't know what manipulation you need exactly, but these are the ones the package offers now: https://docs.spatie.be/image/v1/image-manipulations/overview/
