### ISSUE TITLE
Functionality to add remote media links

### ISSUE THREAD

**Issue by coding-sunshine** [spatie/laravel-medialibrary#19]
Hi, yours is a great library and i am loving to use it.
I haws wondering how we can add remote urls as a media so it doesn't give file not found exception?
I am working on an app where you can upload your files or just add links to Youtube/vemeo or any direct images to the section and it will fetch from there.
I wanted to know if that is possible with your package?

**Comment by freekmurze** [comment]
This package is built around adding files, there are currently no plans to add url's. But I'll take a look in the next weeks if this can be elegantly added to the package.

**Comment by coding-sunshine** [comment]
thanks very much :)

**Comment by freekmurze** [comment]
As we do not need this functionality ourselves adding it is low priority. If you need this, feel free to submit a pull request.

**Comment by coding-sunshine** [comment]
Thanks, will submit a PR soon.

**Comment by cviebrock** [comment]
+1 on this.  Something like `$model->addMediaFromUrl($remoteUrl)->toMediaLibrary()` would be nice to have.

**Comment by freekmurze** [comment]
I think it would be nice to have this. It's still low priority for us, but we'd happily accept a good PR that adds this to the package.

**Comment by freekmurze** [comment]
Thanks to @cviebrock this feature is now available in v.3.8.0

**Comment by Sisifo-Developer** [comment]
+1 to this request.

Unfortunately, I have not the knowledge for a PR...
