### ISSUE TITLE
Call to a member function filter() on string

### ISSUE THREAD

**Issue by poriazarei** [spatie/laravel-medialibrary#1905]
**PHP: v7.4.6
Laravel: v5.8
Media Library: 7.0.0**

Hey guys 

I saved my photos to collections

`if (is_array($request->file('photos'))) {`
`$photoPath=$value->getPathname();`
`//$photoPath is  C:\xampp\tmp\phpD359.tmp`
`$comp = new CompetitionItem();`
`$comp->addMedia($photoPath)->toMediaCollection();`
`$comp->save();`

this all worked and saved photo in media table and in storage/app/public 

but when i call the media by this way

` $media = CompetitionItem::first();`
` $item=$media->getMedia();`

and i got this is error:

`Call to a member function filter() on string`

Am I doing something wrong or can someone validate the problem?

**Comment by techguydev** [comment]
I am having this same problem @poriazarei , did you solve it?

Suddenly I am getting this error:

Call to a member function filter() on null

**Comment by poriazarei** [comment]
In my case i had a column named as media in my CompetitionItem table so i changed my column name and problem solved
