### ISSUE TITLE
Installing with laravel 5.1

### ISSUE THREAD

**Issue by sidis405** [spatie/laravel-medialibrary#192]
I've been using this package a number of times on various projects (includind L5.1) but today i started getting this:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/laravel-medialibrary 3.17.0 requires spatie/laravel-glide ^2.2.4 -> satisfiable by spatie/laravel-glide[2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8].
    - spatie/laravel-medialibrary 3.17.1 requires spatie/laravel-glide ^2.2.4 -> satisfiable by spatie/laravel-glide[2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8].
    - spatie/laravel-medialibrary 3.17.2 requires spatie/laravel-glide ^2.2.4 -> satisfiable by spatie/laravel-glide[2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8].
    - spatie/laravel-glide 2.2.8 requires league/glide 0.3.* -> no matching package found.
    - spatie/laravel-glide 2.2.7 requires league/glide 0.3.* -> no matching package found.
    - spatie/laravel-glide 2.2.6 requires league/glide 0.3.* -> no matching package found.
    - spatie/laravel-glide 2.2.5 requires league/glide 0.3.* -> no matching package found.
    - spatie/laravel-glide 2.2.4 requires league/glide 0.3.* -> no matching package found.
    - Installation request for spatie/laravel-medialibrary ^3.17 -> satisfiable by spatie/laravel-medialibrary[3.17.0, 3.17.1, 3.17.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

Anyone can shed any light on this?

**Comment by sebastiandedeyne** [comment]
Odd, could you post the contents of your `composer.json` file?

**Comment by sidis405** [comment]
Of course. 


{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "laracasts/flash": "^2.0",
        "illuminate/html": "^5.0",
        "laracasts/presenter": "^0.2.1",
        "barryvdh/laravel-debugbar": "^2.2",
        "league/glide": "^1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}


Brand new project. Just setting it up now.

**Comment by sebastiandedeyne** [comment]
Unfortunately this package isn't compatible with `league/glide` v1.0 yet (we can't just bump it up since it has some breaking changes). For now you'll have to use Glide v0.3.

Later on this year we'll be releasing a v4.0 which will upgrade the Glide dependency.

**Comment by sidis405** [comment]
Understood. 
Yep went with glide .3 and all was good-

Thank you :)
