### ISSUE TITLE
Glide Image Api on Laravel-medialibrary

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-medialibrary#193]
Originally posted in the laravel-glide repository by @PhilMarc: https://github.com/spatie/laravel-glide/issues/51

Using Medialibrary, I can successfully modify the media conversions, using `setManipulations` in my Model file, for instance orientating thumbnail pic of 90 degrees:

```php
//Post.php
public function registerMediaConversions() {
    $this->addMediaConversion('thumb')->setManipulations(['or' => 90])->performOnCollections('images');
}
```

However, I would like to perform this manipulation on the original media itself, not on the conversion.
In order to do that, I tried to modify my upload controller this way:

```php
//UploadController.php
$post->addMedia($image)->manipulations(['or' => '90'])->toMediaLibrary('images');
```

But the manipulation doesn't work. Any clue of what I am doing wrong? Is the Glide Api supported only for media conversions?

**Comment by sebastiandedeyne** [comment]
If you want to apply conversions to the original, you'll have to do so before adding it to the media library. E.g.:

```php
$toBeAddedToTheMediaLibrary = '/path/...';

GlideImage::create($image)
    ->modify(['or' => '90'])
    ->save($toBeAddedToTheMediaLibrary);

$post->addMedia($toBeAddedToTheMediaLibrary)->toMediaLibrary('images');
```

**Comment by PhilMarc** [comment]
Makes perfect sense now, thank you.

**Comment by PhilMarc** [comment]
About your solution, 
`GlideImage::create($image)` is only available in Glide v3 (I am using v2 at the moment)

When I try to require the latest Glide v3, I get the following error:

`spatie/laravel-medialibrary 3.17.3 requires spatie/laravel-glide ^2.2.4 -> no matching package found.`

**Comment by freekmurze** [comment]
Currently the medialibrary only has support for laravel-glide v2.
I'm currently working on the next major release of the medialib which will
have support for laravel-glide v3 / Glide v1
ETA: end of may.





Freek Van der Herten
Samberstraat 69 D
2060 Antwerpen
T:  +32 3 292 56 79
M: +32 495 84 27 91
https://spatie.be
