### ISSUE TITLE
pls help me

### ISSUE THREAD

**Issue by DeeJaVu** [spatie/laravel-medialibrary#195]
hello, im new in php and im trying to upload a file but im getting this error

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id' cannot be null (SQL: insert into `media` (`name`, `file_name`, `disk`, `collection_name`, `size`, `custom_properties`, `manipulations`, `model_type`, `model_id`, `order_column`, `updated_at`, `created_at`) values (ssss, ssss.jpg, media, default, 81741, [], [], App\Pin, , 1, 2016-04-05 02:28:57, 2016-04-05 02:28:57))`

my post request looks like this

```php
public function store(Request $request) {
		$this->validate($request, [
			'file' => 'required|mimes:jpg,jpeg,png,bmp,gif,svg,mp4,webm',
		]);
		
		$file = $request->file('file');

		$pin = new Pin;
		$pin->title = $request->title;
		$pin->description = $request->description;
		$pin->user_id = $request->user()->id;
		$pin->image = $file;
		$pin->addMedia($file)
			->preservingOriginal()
			->toMediaLibrary();
		$pin->save();

		return redirect('pin/' . $pin->id)
			->with('notice', 'Successfully created new Pin');
	}
```

**Comment by freekmurze** [comment]
You should save your pin model before adding media to it.

On Tuesday, 5 April 2016, Deejavu <notifications@github.com> wrote:

> hello, im new in php and im trying to upload a file but im getting this
> error
>
> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id'
> cannot be null (SQL: insert intomedia(name,file_name,disk,collection_name,
> size,custom_properties,manipulations,model_type,model_id,order_column,
> updated_at,created_at) values (ssss, ssss.jpg, media, default, 81741, [],
> [], App\Pin, , 1, 2016-04-05 02:28:57, 2016-04-05 02:28:57))
>
> my post request looks like this
>
> public function store(Request $request) {        $this->validate($request, [            'file' => 'required|mimes:jpg,jpeg,png,bmp,gif,svg,mp4,webm',        ]);        $file = $request->file('file');        $pin = new Pin;        $pin->title = $request->title;        $pin->description = $request->description;        $pin->user_id = $request->user()->id;        $pin->image = $file;        $pin->addMedia($file)            ->preservingOriginal()            ->toMediaLibrary();        $pin->save();        return redirect('pin/' . $pin->id)            ->with('notice', 'Successfully created new Pin');    }
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/spatie/laravel-medialibrary/issues/195>
>


-- 
Freek Van der Herten
https://spatie.be
+32 495 84 27 91
