### ISSUE TITLE
Trait deleted event not firing

### ISSUE THREAD

**Issue by a-komarev** [spatie/laravel-medialibrary#196]
I've found one strange Laravel behavior.

**Case 1** *(fail)*
```php
Photo::where('id', $id)->delete();
```

**Case 2** *(success)*
```php
$photo = Photo::where('id', $id)->first();
$photo->delete();
```

**Case 3** *(success)*
```php
Photo::destroy($id);
```

Looks similar, isn't it?

But in **Case 1** `deleted` event in `bootHasMediaTrait()` wouldn't been fired in deletable model's trait (when you are deleting model via delete query). **Case 2** & **Case 3** will delete model and attached media files.

[Unit test in my local sandbox](https://github.com/cybercog/laravel-medialibrary/commit/253f258743871199d93b49dc5baa71e4d56a7998) (it's failing).

*I'm using latest stable version of L5.2.*

**Comment by a-komarev** [comment]
I found already created [ticket about delete query not firing events](https://github.com/spatie/laravel-medialibrary/issues/196).

**Comment by freekmurze** [comment]
Yeah, this cannot be solved in this package. The event will only be fire when deleting a model. When the query builder is used, no events will be fired.
