### ISSUE TITLE
Watch out if this PR gets merged

### ISSUE THREAD

**Issue by rcerljenko** [spatie/laravel-medialibrary#1960]
Recent fix for cached adapter in laravel framework can (maybe) cause problems here since you fixed it on your side recently.

Laravel PR: https://github.com/laravel/framework/pull/33602
Your fix: #1803

**Comment by freekmurze** [comment]
Thanks for the heads up!

**Comment by rcerljenko** [comment]
Np... it actually got merged and released in Laravel 7.21.0
