### ISSUE TITLE
Class name must be a valid object or a string [Installation Error]

### ISSUE THREAD

**Issue by takielias** [spatie/laravel-medialibrary#1988]
PHP 7.4
Laravel 7
Getting this error during installation Process https://prnt.sc/tyisk5

**Comment by PKuebler** [comment]
We have the same error.

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error

  Class name must be a valid object or a string

  at vendor/spatie/laravel-medialibrary/src/MediaLibraryServiceProvider.php:23
    19|         $this->registerPublishables();
    20|
    21|         $mediaClass = config('media-library.media_model');
    22|
  > 23|         $mediaClass::observe(new MediaObserver());
    24|
    25|         $this->loadViewsFrom(__DIR__.'/../resources/views', 'media-library');
    26|     }
    27|

      +8 vendor frames
  9   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Spatie\MediaLibrary\MediaLibraryServiceProvider))

      +5 vendor frames
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by alexdin** [comment]
I have this problem too. 
In PHP 7.4 
Laravel 7 
on 8.5 and 8.4 :(

**Comment by alexdin** [comment]
> We have the same error.
> 
> Laravel v7.24.0
> Laravel medialibrary 8.5.0
> PHP 7.4.9
> 
> ```
> > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> > @php artisan package:discover --ansi
> 
>    Error
> 
>   Class name must be a valid object or a string
> 
>   at vendor/spatie/laravel-medialibrary/src/MediaLibraryServiceProvider.php:23
>     19|         $this->registerPublishables();
>     20|
>     21|         $mediaClass = config('media-library.media_model');
>     22|
>   > 23|         $mediaClass::observe(new MediaObserver());
>     24|
>     25|         $this->loadViewsFrom(__DIR__.'/../resources/views', 'media-library');
>     26|     }
>     27|
> 
>       +8 vendor frames
>   9   [internal]:0
>       Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Spatie\MediaLibrary\MediaLibraryServiceProvider))
> 
>       +5 vendor frames
>   15  artisan:37
>       Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
> ```
> 
> ```
> // media-library.php
> ...
>     /*
>      * The fully qualified class name of the media model.
>      */
>     'media_model' => Spatie\MediaLibrary\MediaCollections\Models\Media::class,
> ...
> ```
 I found the reason. Laravel caches config.
Need delete cached files in bootstrap/cache. Its resolve not isset config in: 
`  $mediaClass = config('media-library.media_model');`

**Comment by vtxmg** [comment]
Same problem ... Please tell us how to solve it?

**Comment by takielias** [comment]
> 
> 
> @takielias, @PKuebler
> 
> > We have the same error.
> > Laravel v7.24.0
> > Laravel medialibrary 8.5.0
> > PHP 7.4.9
> > ```
> > > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> > > @php artisan package:discover --ansi
> > 
> >    Error
> > 
> >   Class name must be a valid object or a string
> > 
> >   at vendor/spatie/laravel-medialibrary/src/MediaLibraryServiceProvider.php:23
> >     19|         $this->registerPublishables();
> >     20|
> >     21|         $mediaClass = config('media-library.media_model');
> >     22|
> >   > 23|         $mediaClass::observe(new MediaObserver());
> >     24|
> >     25|         $this->loadViewsFrom(__DIR__.'/../resources/views', 'media-library');
> >     26|     }
> >     27|
> > 
> >       +8 vendor frames
> >   9   [internal]:0
> >       Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Spatie\MediaLibrary\MediaLibraryServiceProvider))
> > 
> >       +5 vendor frames
> >   15  artisan:37
> >       Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> > Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
> > ```
> > 
> > 
> > ```
> > // media-library.php
> > ...
> >     /*
> >      * The fully qualified class name of the media model.
> >      */
> >     'media_model' => Spatie\MediaLibrary\MediaCollections\Models\Media::class,
> > ...
> > ```
> 
> I found the reason. Laravel caches config.
> Need delete cached files in **bootstrap/cache**. Its resolve not isset config in:
> ` $mediaClass = config('media-library.media_model');`

Did you resolve this issue?

**Comment by alexdin** [comment]
> Did you resolve this issue?
Yes 

1. clear laravel cached files bootstrap/cache/*.php .
2. rerun composer require for your package.

**Comment by n3omaster** [comment]
Same issue here installing https://github.com/wingsline/laravel-blog package

Solved with proposed solution, just delete all bootstrap/cache/*.php files

Thanks!

**Comment by rocknrold** [comment]
> > Did you resolve this issue?
> 
> Yes
> 
> 1. clear laravel cached files bootstrap/cache/*.php .
> 2. rerun composer require for your package.


Using Laravel Framework 8.37.0

Hooray It works, Thanks man!!!

**Comment by njoguamos** [comment]
> > Did you resolve this issue?
> 
> Yes
> 
> 1. clear laravel cached files bootstrap/cache/*.php .
> 2. rerun composer require for your package.

Thanks. It worked.

**Comment by sungkhum** [comment]
In case anyone else was unable to run `php artisan cache:clear` (I had errors).
Run this:
`rm -rf bootstrap/cache/*`
Then you should be able to run `php artisan cache:clear`
And then `composer require "spatie/laravel-medialibrary:^9.0.0"` should run without error.

**Comment by kazoostudios** [comment]
Worked for me too! :)

**Comment by joostvanhoof** [comment]
I don't get this error locally but every time I deploy to production. I tried removing all the files from the cache on the server and the redeploying but that didn't solve the issue. Anyone else has this?

**Comment by light2000** [comment]
my model getMorphClass method return a integer value cause this issue. 
 i use
 `Relation::enforceMorphMap([
           2 => MyModel::class,
        ]);`  
it's ok now
