### ISSUE TITLE
Value order_column per collection_name

### ISSUE THREAD

**Issue by ceesvanegmond** [spatie/laravel-medialibrary#200]
Hi there,

Quick small question, see image below:
![schermafbeelding 2016-04-11 om 12 09 40](https://cloud.githubusercontent.com/assets/883497/14423875/5b9c0524-ffde-11e5-8019-6f67d115d40f.png)

Should the value of the `order_column` depend on the `collection_name`? In this case, that isn't the case. Should the row with id = 3 not having an `order_column` of 1 instead of 3 because it's in a different collection?

**Comment by freekmurze** [comment]
The order_column handling is not that sophisticated :smile: When adding a new row, it will just get the highest order number + 1. 

So the ordering of the items is correct, but be aware that there are gaps in the numbering.

**Comment by ceesvanegmond** [comment]
@freekmurze So what's the advantage of having this order_column?

**Comment by freekmurze** [comment]
When calling `getMedia` the returned `Media` objects are sorted by the value in `order_column`.

**Comment by ceesvanegmond** [comment]
Would it be an good idea to make the `order_column` depend on the type of collection?

**Comment by freekmurze** [comment]
imho it isn't really necessary. When using `updateMedia` the values of `order_column` will be recalculated.

What problem are you facing?

**Comment by amosmos** [comment]
I want to allow the users to add media to models and control their order. I want to believe it's pretty common feature.

**Comment by nicolasbeauvais** [comment]
Hi @amosmos,

I never used the `order_column` so I don't know how we can fix your problem by using it, but here is a simple solution for you:

First add a `order` custom property to the media that needs it:

```php
$media1 = $model->addMedia($pathToFile)
                ->withCustomProperties(['order' => 1])
                ->toMediaLibrary();

$media1 = $model->addMedia($pathToFile)
                ->withCustomProperties(['order' => 2])
                ->toMediaLibrary();
```

then you can use the custom property to sort your medias:

```php
$medias = $model->getMedia();

$ordered = $medias->sortBy(function ($media, $key) {
    return $media->getCustomProperty('order');
});
```

I hope this can help you :smile:

**Comment by amosmos** [comment]
Hey - yes that's very helpful!

One thing though is how do I add the order value when I add the media -> it needs to be one more then the highest existing order value for the model's media collection.

Then also how do I make changes to the order, when the user wants to change the order of images\files.

I must say I am really surprised this is not a common request. I thought that's the main use for this package...

**Comment by sebastiandedeyne** [comment]
We use the current implementation of `order_column` for the same use case in our CMS. We have an uploader component that creates a json string, which we in turn use to update the media through the (undocumented) `updateMedia` method.

https://github.com/spatie/laravel-medialibrary/blob/master/src/HasMedia/HasMediaTrait.php#L187

> it needs to be one more then the highest existing order value for the model's media collection

Why does it need to be exactly one higher than the existing value? Say you have collection A and B:

```
$media1 = Add media to collection A => order_column = 1
$media2 = Add media to collection B => order_column = 2
$media3 = Add media to collection A => order_column = 3
```

Collection A doesn't have any media with `order_column = 2`, but that doesn't really matter since 1 and 3 will still sort correctly.

**Comment by amosmos** [comment]
@sebastiandedeyne - I understand that - but how can you accomplish a change in order of the photos? Let's say now the user want to change the order of the photos in collection A.

**Comment by sebastiandedeyne** [comment]
Our uploader component creates a json string with an array of media, e.g.:

```json
"media": [
  { "id": 2, ... },
  { "id": 1, ... },
  { "id": 3, ... }
]
```

The string gets parsed by the server, and sets the `order_column` property based on the order of the media in the array, so now media 1 would have `order_column: 2`, media 2 `order_column: 1` and media 3 `order_column: 3`.

The order column is generated by a simple local variable: https://github.com/spatie/laravel-medialibrary/blob/master/src/HasMedia/HasMediaTrait.php#L210

If you're interested in the JavaScript side of things, our uploader is also open sourced (it's a medium-sized Vue project): https://github.com/spatie-custom/blender-media

**Comment by amosmos** [comment]
@sebastiandedeyne Just so I'll know I understand:

So after you run an update with `updateMedia` you end up with duplicate values in `oreder_column` in the table - correct? (Because now the ordering was done only on this specific collection?)

**Comment by sebastiandedeyne** [comment]
Correct—If this is an issue in your app you'll need to write a more complex method to determine the `order_column` value.

**Comment by amosmos** [comment]
No, actually that is how I would expect this column to behave originally. Not sure why it's not like that from the begin with, but alright - this library is still so awesome!!

**Comment by amosmos** [comment]
Hey @sebastiandedeyne  - one more question... I see in the updateMedia function, that the first thing it does is deleting the media items that are not in the passed array.. So when I send an array with only the specific model and collection's images, all the rest will be deleted...?

**Comment by freekmurze** [comment]
All the media not present in the passed array that are in the specified collection name will indeed be deleted. 

In hindsight, the method could have been named better (`syncMedia` or something better).

**Comment by amosmos** [comment]
There are different collections AND different models - this means that no items from other collections will be deleted but also items from different models in the same collection name will also not be deleted right?

**Comment by freekmurze** [comment]
That is correct.
