### ISSUE TITLE
ErrorException: rewind(): stream does not support seeking. Cannot download zip file

### ISSUE THREAD

**Issue by ziming** [spatie/laravel-medialibrary#2017]
Since Aug 19, 2020 3:46:54 AM UTC (At least from what I know. So it may be even earlier)

ErrorException: rewind(): stream does not support seeking

My apps have been getting this error when trying to return a MediaStream (that is a zip file download containing multiple files)

Downloading of individual file still work.

**Comment by ziming** [comment]
Okay fixed it by downgrading "league/flysystem-aws-s3-v3" to 1.0.25.

1.0.26 broke something

I shall file my issue there.

**Comment by gabrielesbaiz** [comment]
> 1.0.26 broke something

Even 1.0.28 gives this error. I confirm downgrading to 1.0.25 works.

**Comment by ziming** [comment]
Reopening this issue, Frank replied

https://github.com/thephpleague/flysystem-aws-s3-v3/issues/212

**Comment by rcerljenko** [comment]
probable upcoming fix from laravel itself:
https://github.com/laravel/framework/pull/34001

**Comment by freekmurze** [comment]
Closing this as this bug doesn't originated in this package.
