### ISSUE TITLE
sanitizingFileName() does not allow array-format callbacks (static class methods)

### ISSUE THREAD

**Issue by squatto** [spatie/laravel-medialibrary#2029]
I am using my own `Media` model and have added a filename sanitization method to it: (using the method from my idea in #2027)

```php
namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\MediaCollections\Models\Media as BaseMedia;

class Media extends BaseMedia
{
    use SoftDeletes;

    public static function sanitizeFilename(string $filename): string
    {
        return implode('.', array_map([Str::class, 'slug'], explode('.', $filename)));
    }
}
```

I am attempting to use this as the callable:

```
$productType
    ->addMediaFromRequest("file.$index")
    ->sanitizingFileName([Media::class, 'sanitizeFilename'])
    ->withCustomProperties(['index' => $index])
    ->toMediaCollection('files');
```

However, this produces this error:

`Typed property Spatie\MediaLibrary\MediaCollections\FileAdder::$fileNameSanitizer must be an instance of Closure or null, array used`

`$fileNameSanitizer` is defined as `protected ?Closure $fileNameSanitizer;` which is preventing these types of callbacks from being used.

That being said, I can certainly wrap the static method call in a short closure, similar to how you do it:

```php
->sanitizingFileName(fn ($filename) => Media::sanitizeFilename($filename))
```

However, it could be helpful to allow the native array syntax as well.

Thanks!

**Comment by freekmurze** [comment]
Closing this for now. Feel free to PR enhancements.
