### ISSUE TITLE
InteractsWithMedia->clearMediaCollection not compatible with HasMedia->clearMediaCollection

### ISSUE THREAD

**Issue by mauricehofman** [spatie/laravel-medialibrary#2033]
After implementing the 'HasMedia' interface with the 'InteractsWithMedia' trait on a model in Laravel Framework 6.18.33 ( media library 8.5), i get the following error in PHPstorm:

![hasmedia-error-msg](https://user-images.githubusercontent.com/3535931/92227364-7863a700-eea6-11ea-9a3d-f999ec23c063.png)

`Declaration of 'InteractsWithMedia->clearMediaCollection([collectionName: string = 'default'])' must be compatible with 'HasMedia->clearMediaCollection([collectionName: string = 'default'])' `

When i check these classes, i see no difference between the methods.

HasMedia:
`public function clearMediaCollection(string $collectionName = 'default'): self;`
InteractsWithMedia:
`public function clearMediaCollection(string $collectionName = 'default'): self`  (it returns self)

Medialibrary works without any problems in this class/project. I`m not sure if this is a problem with the package, or a problem with PHPstorm.

**Comment by freekmurze** [comment]
I'm thinking it's a bug in PhpStorm. The package seems to work just fine.
