### ISSUE TITLE
both lazy & attributes give "undefined method"

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-medialibrary#2035]
from the [docs](https://spatie.be/docs/laravel-medialibrary/v8/advanced-usage/rendering-media#breadcrumb)

- ex.
```
$item->getFirstMedia('cover')->attributes(['class' => 'my-class'])->lazy()
```

```
Call to undefined method Spatie\MediaLibrary\MediaCollections\Models\Media::attributes()
// &
Call to undefined method Spatie\MediaLibrary\MediaCollections\Models\Media::lazy()
```

might be related to using `->withResponsiveImages()` but i could be wrong, if yes i could PR some clarification on the [rdme](https://github.com/spatie/laravel-medialibrary/blob/master/docs/advanced-usage/rendering-media.md)

**Comment by freekmurze** [comment]
I think the docs were missing an `img()` call. 

```php
$item->getFirstMedia('cover')->img()->attributes(['class' => 'my-class'])->lazy()
```

I've correct this. If there are other things wrong, feel free to PR fixes.

**Comment by ctf0** [comment]
it wont work in its current state if the `$item->getFirstMedia('cover')` or `$item->getFirstMedia('cover')->img()`

to make this global and future prof, i think we can wrap both methods with `optional`, if its ok with u i can make a PR.

**Comment by freekmurze** [comment]
Feel free to PR any improvements you see. Be sure to include tests.

**Comment by ctf0** [comment]
can u reopen the ticket so we can easily track it
