### ISSUE TITLE
Lumen Integration?

### ISSUE THREAD

**Issue by atapatel** [spatie/laravel-medialibrary#204]
Is there any plan for integrating this packages with lumen micro framework?

**Comment by freekmurze** [comment]
Nope, we don't use Lumen in our company. But we'd accept a PR that adds
Lumen compatibility.

On Thursday, 14 April 2016, Ajay Patel <notifications@github.com> wrote:

> Is there any plan for integrating this packages with lumen micro framework?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/spatie/laravel-medialibrary/issues/204>
>


-- 
Freek Van der Herten
https://spatie.be
+32 495 84 27 91
