### ISSUE TITLE
Registered Media Conversions are not Generated when using addMediaFromDisk

### ISSUE THREAD

**Issue by hero0690** [spatie/laravel-medialibrary#2051]
Laravel: 7.0
Version: 8.6

I have followede the set up and added this following code registered to my model. 
The conversions are not generated when using laravel vapor with s3.

Although the jobs are being called, the conversions are not generated. 
But when using a file directly, it does generate the conversions. 

Is S3 not supported on new versions anymore?

```
 public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('large')
            ->width(1920)
            ->height(1080)
            ->keepOriginalImageFormat();

        $this->addMediaConversion('small')
            ->width(426)
            ->height(240)
            ->keepOriginalImageFormat();
    }
```

It works when you use the addMedia

``` 
$model->addMedia($file) 
            ->toMediaCollection('my-collection');
```

But won't work with addMediaFromDisk using S3 Key
```

$model->addMediaFromDisk($key) 
            ->toMediaCollection('my-collection');
```

**Comment by ashgibson** [comment]
Can confirm I am experiencing the same issue.

**Comment by freekmurze** [comment]
We've made a few fixes around conversions on now local disks. Could you try again using the latest version? If they are not, please open up a new issue.
