### ISSUE TITLE
Spatie\MediaLibrary\Jobs\PerformConversions does not implement SelfHandling

### ISSUE THREAD

**Issue by gbaudoin** [spatie/laravel-medialibrary#206]
In Laravel 5.2: ["All jobs are now self-handling by default, so you can remove this interface from your classes."](https://laravel.com/docs/master/upgrade).

But this is not the case in Laravel 5.1. Without it, the queue listener errors:
`InvalidArgumentException]
  No handler registered for command [Spatie\MediaLibrary\Jobs\PerformConversions]`

**Comment by freekmurze** [comment]
Fixed in v4.0.1 of this package.
