### ISSUE TITLE
Moving item to new model can result in error during processUnattachedMedia

### ISSUE THREAD

**Issue by jeroendelau** [spatie/laravel-medialibrary#2072]
I ran into an issue that a move action results in:
`fopen(.../storage/medialibrary/temp/oAxyPUS7vWtc6GyEsXjJVphw3e6nBx05//logo.jpg): failed to open stream: No such file or directory`

This appears to happen in a very particular situation. 
Moving an item from an existing model to a new, unsaved model.
The issue seems to be caused by the attaching of the media to the model asynchronously.
During copy: 

- `fileAdder->attachMedia() // line 148-365`  detects that the model has not been persisted, and delays attachment
- It sets a listener on the create event of the model
- The temporary directory is removed as the last action of copy
- On model save > `HasMediaTrait::processUnattachedMedia() `is looking for the deleted file and fails

Automatically saving the target model during copy probably not the solution, as it can lead to unintended consequences.

So as a quick fix we could:
1. Throw an exception if the target model does not exist during a `media->copy()`
2. Update documentation

**Comment by freekmurze** [comment]
Thanks for reporting!

Feel free to send a PR that fixes this.
