### ISSUE TITLE
How manipulate the image before upload? and don't keep the original file

### ISSUE THREAD

**Issue by astrO1** [spatie/laravel-medialibrary#2074]
First congratz! for this amazing package.

My problem is that every time a user uploads an image, he upload the original file and always is large sometimes like 4mb and 5mb, and after that, he makes the conversions.

How can I make manipulation on the file before the ->addMedia($file) to not upload the large original file?

```

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->fit(Manipulations::FIT_FILL, 200, 200)
            ->sharpen(10);

        $this->addMediaConversion('icon')
            ->fit(Manipulations::FIT_FILL, 100, 100)
            ->sharpen(10);

        $this->addMediaConversion('large')
            ->width('1024')
            ->sharpen(10);

        $this->addMediaConversion('medium')
            ->width('600')
            ->sharpen(10);
    }
```

My function from the conversion is working fine but I don't want the original file upload or just make a manipulation before upload

**Comment by freekmurze** [comment]
Manipulating the image beforehand is out of scope for this package. You need to manipulate the image yourself. 

Consider using https://spatie.be/docs/image/v1/introduction for this.
