### ISSUE TITLE
Missing remote headers for conversions when disk != conversions_disk

### ISSUE THREAD

**Issue by rcerljenko** [spatie/laravel-medialibrary#2078]
In situation where we have different `conversions_disk` from `disk` there's a bug in `MediaCollections\Filesystem` class in method `copyToMediaLibrary()` on line [104](https://github.com/spatie/laravel-medialibrary/blob/master/src/MediaCollections/Filesystem.php#L104).
The problem is that this line is checking `$media->getDiskDriverName() === 'local'` regardless of the media type (original file or conversion / responsive images).
Since we have that check in the line above we can reuse that to something like this:
```
$diskDriverName = (in_array($type, ['conversions', 'responsiveImages']))
            ? $media->getConversionsDiskDriverName()
            : $media->getDiskDriverName();

if ($diskDriverName === 'local') { // line 104
// ...
}
```
Result of the problem is that conversions are saved without passing a `remote.extra_headers` config which (in my case) results in unreadable S3 files => saved without `'ACL' => 'public-read'` header.

**Comment by freekmurze** [comment]
I'd accept a PR with tests that fixes this.

**Comment by rcerljenko** [comment]
Ok here it is:
https://github.com/spatie/laravel-medialibrary/pull/2080

**Comment by freekmurze** [comment]
We'll handle this further in #2080
