### ISSUE TITLE
W3C break : loading="auto" is not an HTML valid value

### ISSUE THREAD

**Issue by Okipa** [spatie/laravel-medialibrary#2079]
According to these resources, it seems that the the `auto` value for the `loading` HTML attribute does not exist:
* https://html.spec.whatwg.org/multipage/urls-and-fetching.html#lazy-loading-attribute
* https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-loading

It is actually breaking W3C XHTML validator.

In the package documentation, it is told that it is a possible value and it seems that it is quite often used: https://spatie.be/docs/laravel-medialibrary/v8/api/defining-conversions#useloadingattributevalue.

Would you accept a PR that would remove the use of the `auto` value, in favor of the `eager` and `lazy` ones ?

**Comment by sebastiandedeyne** [comment]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/1561079/94659339-6984de80-0304-11eb-9ae5-e53dd579067d.png">

I suppose we missed the warning :)

I'd accept a PR that changes the default configuration `default_loading_attribute_value` to `eager`.

**Comment by Okipa** [comment]
Thanks for your quick answer !

Just another question: why not to trigger `lazy` by default as it is one of the real gain offered by responsive images ? (It would still be possible to opt for `eager` loading if the standard behaviour is wished).

**Comment by sebastiandedeyne** [comment]
Because `eager` is still the default browser behaviour, and I don't believe we should be hijacking that.

Maybe the best solution would be to not add any `loading` attribute unless explicitly specified.

**Comment by Okipa** [comment]
I think you are right: the `auto` attribute is supposed to apply the default browser lazy loading behavior, which is the same as not declaring anything.

I'll make my PR forward this direction.

**Comment by freekmurze** [comment]
We'll continue this in #2081
