### ISSUE TITLE
Question about FileAdder.php toCollectionOnDisk

### ISSUE THREAD

**Issue by Ermac25** [spatie/laravel-medialibrary#208]
I'm trying to understand how the creation of a new media entry works, FileAdderFactory.php calls
setSubject and setFile from FileAdder.php, but i don't find where toCollectionOnDisk is called.

ps. I'm trying to see if i can update the associated file of a media model.

**Comment by sebastiandedeyne** [comment]
`toCollectionOnDisk` doesn't get called automatically but should be called manually in your own application's code, e.g.:

```php
$newsItem->addMedia($request->file('image'))->toCollection('images');
```

(`toCollection` calls `toCollectionOnDisk` under the hood)
