### ISSUE TITLE
syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')'

### ISSUE THREAD

**Issue by mostafasamirs** [spatie/laravel-medialibrary#2090]
syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')'
_____
vendor\spatie\laravel-medialibrary\src\MediaCollections\Models\Media.php:182

**Comment by freekmurze** [comment]
PHP 7.4 is required

**Comment by akashict** [comment]
Am also getting the same error. Am using PHP7.4.11. I have checked the version in both CLI and using phpinfo(). Both versions are matching. Still am getting the same error.
