### ISSUE TITLE
Adding conversions per single image

### ISSUE THREAD

**Issue by mattboban** [spatie/laravel-medialibrary#210]
Hi,  
this might have been asked before but is it possible to add and regenerate conversions per image. I can add and alter manipulations per image, which is fine, but they are tied to the named conversions specified in the model. 

I'm trying to preserver conversions (with a unique name) derived from a single image so they can be used even if a new conversion is made.
An example would be 2 different image cuts derived for the same original image.

Would this be possible within the current codebase?

**Comment by freekmurze** [comment]
Take a look at the current `medialibrary:regenerate` command. If you run that all the derived images will be regenerated. So you can run that after you've added a conversion.

You can let the command regenerate all media tied to a certain model class or for a specific media id.

**Comment by mattboban** [comment]
True, that would regenerate given items, but it doesn't address my issue of trying to have independent named conversions done on a single media item (conversions that are not defined on the model itself, but rather at media creation).

**Comment by freekmurze** [comment]
Another approach is to manipulate your image (using [laravel-glide](https://github.com/spatie/laravel-glide)) before adding it to the medialibrary. Would that work for your use case?

**Comment by ceesvanegmond** [comment]
Having the same problem as @mattboban. Ideally you want to have the manipulations per item in your `media` table.  Using the approach @freekmurze is offering this isn't the case.

**Comment by freekmurze** [comment]
You can store [media specific manipulations in the database](https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/storing-media-specific-manipulations). Could that be of use to you?

**Comment by tomcoonen** [comment]
@freekmurze The media specific manipulations only work if the same manipulation exists on the model?

```
 protected function addManipulationToConversion(array $manipulation, string $conversionName)
    {
        foreach ($this as $conversion) {
            if ($conversion->getName() === $conversionName) {
                $conversion->addAsFirstManipulation($manipulation);
                return;
            }
        }
    }
```
https://github.com/spatie/laravel-medialibrary/blob/master/src/Conversion/ConversionCollection.php#L128

I think if you drop this requirement it would be more flexible.
And you could partially solve this https://github.com/spatie/laravel-medialibrary/issues/180

**Comment by freekmurze** [comment]
We could introduce a special conversionName like `*`. If that's used in a stored manipulation on a Media object we could use that for every conversion. 

Thoughts?

**Comment by tomcoonen** [comment]
In my specific case I also needed the conversion name to change for SEO requirements, and since my conversion name prefix is known I solved it this way for now: https://github.com/creacoon/laravel-medialibrary/commit/b297525e1fac0e455fd720b8bf6caff4bb4bdaae
On the conversion set on the parent model, I can now set the converion name with a prefix-property (product name in this case).

**Comment by mattboban** [comment]
@tomcoonen can you put up a sample code of your implementation as Im curious about the prefix usage.

Thanks

**Comment by tomcoonen** [comment]
@mattboban I currently use it like this;
```
$images = $product->getMedia('product-images');
```
And then for each image I get the conversion I need:
```
$image->getUrl($product->slug.'-large');
```

Does it make sense?

**Comment by freekmurze** [comment]
Closing this for now.
