### ISSUE TITLE
touch(): Utime failed: No such file or directory

### ISSUE THREAD

**Issue by sojeda** [spatie/laravel-medialibrary#2109]
I have a problem when i try **addMediaFromDisk**

`
$user
            ->addMediaFromDisk('')
            ->toMediaCollection(User::AVATAR);
`

![image](https://user-images.githubusercontent.com/17851841/95792099-25f18380-0cb9-11eb-8362-0f156606e5b3.png)

The problem is on Filesystem.php in a copyFromMediaLibrary method.

Any ideas?

I think is a problem with a Windows directory, I use Windows 10 and Docker.

**Comment by freekmurze** [comment]
Our test suite indicates that this is working correctly. Could you PR a failing test for us to fix?

I'd also accept a PR that fixes this for you.
