### ISSUE TITLE
syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')' 

### ISSUE THREAD

**Issue by mdalamin2** [spatie/laravel-medialibrary#2111]
The error comes from the localhost URL

![Screenshot_7](https://user-images.githubusercontent.com/51871198/95959814-cd3ef980-0e24-11eb-9700-4fa9bcb5e505.png)

![Screenshot_2020-10-14 🧨 syntax error, unexpected '$conversion' (T_VARIABLE), expecting ')'(1)](https://user-images.githubusercontent.com/51871198/95959574-7507f780-0e24-11eb-973b-936e3e085857.png)

**Comment by freekmurze** [comment]
You'll need PHP 7.4 to use the package.

**Comment by akashict** [comment]
Am also getting the same error. Am using PHP7.4.11. I have checked the version in both CLI and using phpinfo(). Both versions are matching. Still am getting the same error.

**Comment by t-chatoyan** [comment]
`    public function getMediaConversionNames(): array
    {
        $conversions = ConversionCollection::createForMedia($this);

        return $conversions->map(function (Conversion $conversion) { return $conversion->getName(); })->toArray();
    }
`
