### ISSUE TITLE
Media specific manipulations ordering

### ISSUE THREAD

**Issue by a-komarev** [spatie/laravel-medialibrary#212]
I need to perform multiple actions step-by-step to prepare thumbnail. For real it's a replication of frontend logic on backend after uploading. Don't even ask why I need such a *"great idea"* to do so in a project.

**Frontend:**

1. User see [JS library](http://codecanyon.net/item/html-5-upload-image-ratio-with-drag-and-drop/full_screen_preview/8712634).
2. User dropping an image with dimensions `1024x512` to canvas.
3. User zooming in and moving an image over canvas.
4. User clicking on submit button.
5. Image sending to backend as base64 with manipulations info:

```
{
    "imageOriginalWidth":"1024",
    "imageOriginalHeight":"512",
    "imageWidth":"520",
    "imageHeight":"260",
    "width":"220",
    "height":"220",
    "left":89,
    "top":40
}
```

**Backend:**

1. Store original image and all manipulations from frontend.
2. Shrink image to size: `520x260`. (Because user has zoomed image to this dimensions).
3. Crop rectangle `220x220` from result of step 2, with coordinates `x=89`, `y=40`.
4. Store result as `220x220` thumbnail.

I've used this code:

```php
$media->manipulations = [
    'thumb' => [
        'fit' => 'contain',
        'w' => 520,
        'h' => 260,
        'rect' => '220,220,89,40',
    ],
];
```

**What an issue here?**

First of all `rect` is performed and only after `fit` + `w` + `h` will be made. And output result is different from frontend. There is no way to define ordering of manipulations. I need to make sizing, and only after then - cropping.

*I'm using medialibrary v3*

**Comment by a-komarev** [comment]
It looks like you are just bypassing image manipulations as array to the Glide, so it's Glide issue then :(

**Comment by freekmurze** [comment]
What could be done to make is happen is allow multiple manipulations be stored in the db for the same conversion.

Something like this:
````
$media->manipulations = [
    'thumb' => [
           ['rect' => '220,220,89,40',],
           [
                'fit' => 'contain',
                'w' => 520,
                'h' => 260,
           ]
    ],
];
```

It's a bit of work to integrate this in the medialib, but I'd accept a PR that adds this to the package in an non-breaking way.

What you could do in the short term is using [laravel-glide](https://github.com/spatie/laravel-glide) to manipulate your image before adding it to the medialibrary. You could storge the orginal in a collection `orginals` and your crops in a collection `crops`. It's a bit of a workaround, but it'll work.

**Comment by a-komarev** [comment]
@freekmurze I thought about extending syntax like you provided, will have a time to dive deeper in this issue in the end of May.

Is it ok if I will make it in media library v3? Current project where I need this feature can't have PHP7 on board because of swarm of old native PHP code which has a lot of deprecated functions, and that why I can't move to v4 right now.

**Comment by freekmurze** [comment]
There should be feature parity between v3 and v4.

If features get added to v3, I'd like a PR that adds them to v4 as well.

**Comment by a-komarev** [comment]
Sure, I'm pretty sure I will need it on v4 on the other incoming project :}

**Comment by freekmurze** [comment]
Closing this for now. Like mentioned before, I'd accept a PR that adds this to the package.

**Comment by a-komarev** [comment]
Ok sure! I'm in progress to dive in it.

**Comment by a-komarev** [comment]
@freekmurze This issue is very complicated than I've thought before. I can't see a way to implement it without full rewriting conversion class at this moment and maybe even more, or am I missed any *light* way to implement this?

**Comment by freekmurze** [comment]
I don't think there is a big rewrite necessary, but the change isn't light as well. I'll work on it when I have some time on my hands.
