### ISSUE TITLE
Responsive image isn't used, when filename ends with "_"

### ISSUE THREAD

**Issue by bernhardh** [spatie/laravel-medialibrary#2121]
If you have images with filenames ending with "_" they will get rendered as "regular" images (they will use the `image.blade.php` instead of the `responsiveImage.blade.php` view), even if you use `withResponsiveImages()` method. The responsive files and the base64 encoded version are generated.

I have tracked it down and the error is because of the following:

The problem is with one line in the `Spatie\MediaLibrary\MediaCollections\Models\Media\RegisteredResponsiveImages` constructor:

```php
->filter(fn (ResponsiveImage $responsiveImage) => $responsiveImage->generatedFor() === $this->generatedFor);
```

where the `$responsiveImage->generatedFor()` looks like this:

```php
    public function generatedFor(): string
    {
        $propertyParts = $this->getPropertyParts();

        array_pop($propertyParts);

        array_pop($propertyParts);

        return implode('_', $propertyParts);
    }
```

The problem is, that if you image filename ends with "_", the result of the `generatedFor` method is `_YOURCOLLECTIONNAME` instead of `YOURCOLECTIONNAME`, so the filter in the `RegisteredResponsiveImages` constructor will not find the correct collection.

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this. 

@Nielsvanpach can you make sure this is fixed in v9?

**Comment by freekmurze** [comment]
This one can be closed I guess.
