### ISSUE TITLE
UrlGenerator::getPath() is referenced by Media but is not part of the UrlGenerator interface

### ISSUE THREAD

**Issue by unstoppablecarl** [spatie/laravel-medialibrary#214]
Media::getPath() references UrlGenerator::getPath() but getPath is not part of the UrlGenerator interface.

https://github.com/spatie/laravel-medialibrary/blob/master/src/Media.php#L78

**Comment by freekmurze** [comment]
You're right, this isn't 100% correct. Is this causing you problems?

**Comment by unstoppablecarl** [comment]
I just wrote my own UrlGenerator that implemented the interface but got an error when there was no UrlGenerator::getPath() function. So I copied it from the LocalUrlGenerator and it worked fine. Not a huge deal but if you are leveraging the interface it should be complete.

**Comment by freekmurze** [comment]
I will improve this in a next major version of the package.
