### ISSUE TITLE
V9 small config and typo issues

### ISSUE THREAD

**Issue by Okipa** [spatie/laravel-medialibrary#2149]
I just upgraded to v9 and I noticed a small issue: the config file adds this new line:

```php
    /*
     * The fully qualified class name of the model used for temporary uploads.
     */
    'temporary_upload_model' => Spatie\MediaLibraryPro\Models\TemporaryUpload::class,
```

I wonder if it wouldn't be safer to comment this by default as this package is supposed to work without `MediaLibraryPro` ? Right now, it currently breaks static analysis.

I also noticed that the v9 doc still mention v8 for installation and in other places. It could confuse package users.

=> Would you accept a small PR that fix these points ?

**Comment by freekmurze** [comment]
> I also noticed that the v9 doc still mention v8 for installation and in other places. It could confuse package users.

I'd accept a PR that fixes this.

> I just upgraded to v9 and I noticed a small issue: the config file adds this new line:
It's not needed to put this in comments, that will only make installing the Pro version harder. I've made sure that this setting does not break the regular media lib.
