### ISSUE TITLE
Problem when using public directory symlinked to storage directory

### ISSUE THREAD

**Issue by Crinsane** [spatie/laravel-medialibrary#216]
I'm facing this exact same problem as https://github.com/spatie/laravel-medialibrary/issues/190, it looks like I've done everything correctly, but I still get the same exception. What for me seems to be a problem is this method:

```php
// LocalUrlGenerator.php
/*
 * Get the path where the whole medialibrary is stored.
 */
protected function getStoragePath() : string
{
    $diskRootPath = $this->config->get('filesystems.disks.'.$this->media->disk.'.root');

    return realpath($diskRootPath);
}
```

The first line returns the correct path `/home/vagrant/website/public/storage/media`.
But the call to `realpath()` turns the path into `/home/vagrant/website/storage/app/public/media`.

What am I doing wrong?

**Comment by freekmurze** [comment]
That `realpath` call is indeed problematic when symlinking dirs.

You can solve this by pointing the disk where the media is on to the real directory and use a [custom url generator](https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/generating-custom-urls) to generate urls. In my projects I use this one:

```
namespace App\Services;

use Spatie\MediaLibrary\UrlGenerator\LocalUrlGenerator;

class MediaLibraryUrlGenerator extends LocalUrlGenerator
{
    /**
     * Get the url for the profile of a media item.
     *
     * @throws \Spatie\MediaLibrary\Exceptions\UrlCouldNotBeDetermined
     */
    public function getUrl() :  string
    {
        return '/media/'.$this->getPathRelativeToRoot();
    }
}
```

But I'm thinking we could also ditch the call to `realpath`. If you can confirm it works and if all the tests on travis return green I'd accept a PR that removes that call.

**Comment by kickthemooon** [comment]
@Crinsane Did you try Freek's suggestion? does it work?

**Comment by kickthemooon** [comment]
@freekmurze I need ti implement this custom url generator like you are using it.

I am not sure where to create this class "MediaLibraryUrlGenerator" ?
and how to to set this up exactly?

1. I created a folder "services" under my app folder
2. Copied your little implementation that you posted about
```
namespace App\Services;

use Spatie\MediaLibrary\UrlGenerator\LocalUrlGenerator;

class MediaLibraryUrlGenerator extends LocalUrlGenerator
{
    /**
     * Get the url for the profile of a media item.
     *
     * @throws \Spatie\MediaLibrary\Exceptions\UrlCouldNotBeDetermined
     */
    public function getUrl() :  string
    {
        return '/media/'.$this->getPathRelativeToRoot();
    }
}
```

Now how can I start using this?

**Comment by borealsmith** [comment]
Hi, 
First of all thank you @freekmurze for this awesome package.
As I am facing now the same issue as @Crinsane  I was wondering  if there are some updates on this issue.

Cheers,

**Comment by kickthemooon** [comment]
@borealsmith I solved this by using the customUrlGenerator. after setting up a custom url generator the symlink was working without issues.

**Comment by borealsmith** [comment]
Thank you @kickthemooon I will do the same. I was very much interested for a PR overcoming this issue since Laravel 5.3 directory structure recommands using symlinks from public to storage.

**Comment by Dalamar** [comment]
Hey, it's been a while since the last discussion on this subject but the issue still exists and we still limited to use symlinked directories due to the realpath thing.

How can I help to overcome this issue? Should I bring PR?
