### ISSUE TITLE
You need to have media library pro installed to make this work

### ISSUE THREAD

**Issue by upeksha1996** [spatie/laravel-medialibrary#2162]
In my blade files I was trying to retrieve media` $mediaItems = $yourModel->getMedia();` according to documentation (https://spatie.be/docs/laravel-medialibrary/v8/basic-usage/retrieving-media)

But I get the following error
```
Spatie\MediaLibrary\MediaCollections\Exceptions\FunctionalityNotAvailable
You need to have media library pro installed to make this work.
```

I posted this thinknking this might be a bug, since Im following the basic usage section and only using media library.

**Comment by upeksha1996** [comment]
### **Stack Trace:**

Facade\Ignition\Exceptions\ViewException: You need to have media library pro installed to make this work. (View: D:\Dawn\ERP_v8_2\ERP\resources\views\crud\catelog-items\base.blade.php) in file D:\Dawn\ERP_v8_2\ERP\vendor\spatie\laravel-medialibrary\src\MediaCollections\Exceptions\FunctionalityNotAvailable.php on line 11

#0 D:\Dawn\ERP_v8_2\ERP\vendor\spatie\laravel-medialibrary\src\Support\MediaLibraryPro.php(13): Spatie\MediaLibrary\MediaCollections\Exceptions\FunctionalityNotAvailable::mediaLibraryProRequired()
#1 D:\Dawn\ERP_v8_2\ERP\vendor\spatie\laravel-medialibrary\src\MediaCollections\Models\Collections\MediaCollection.php(37): Spatie\MediaLibrary\Support\MediaLibraryPro::ensureInstalled()
#2 D:\Dawn\ERP_v8_2\ERP\vendor\laravel\framework\src\Illuminate\Support\helpers.php(115): Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection->toHtml()
#3 D:\Dawn\ERP_v8_2\ERP\vendor\laravel\framework\src\Illuminate\View\Compilers\Concerns\CompilesComponents.php(174): e(Object(Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection))
#4 D:\Dawn\ERP_v8_2\ERP\resources\views/crud/catelog-items/base.blade.php(81): Illuminate\View\Compilers\BladeCompiler::sanitizeComponentAttribute(Object(Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection))
#5 D:\Dawn\ERP_v8_2\ERP\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(107): require('D:\Dawn\ERP_v8_...')
#6 D:\Dawn\ERP_v8_2\ERP\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(108):
...............................


**### Failing Code:**
```
//base.blade.php
...
<x-form.file name="images" :values="isset($catelogItem)?$catelogItem->media:null" :disable="$disable" />
...
```
```
//file.blade.php
<x-form.form-input :name="$name">
....
    <div id="{{$name}}_preview" class="d-flex flex-row flex-wrap">
        @foreach($values as $value)
        <div class='p-2'><img class='img-thumbnail' style='max-height:60px' height='60' src='{{$value->getUrl()}}'></div>
        @endforeach
    </div>
...
</x-form.form-input>
```

**### Success Code**
```
//base.blade.php
...
<x-form.file name="images" :values="isset($catelogItem)?$catelogItem:null" :disable="$disable" />
...
```
```
//file.blade.php
<x-form.form-input :name="$name">
...
    <div id="{{$name}}_preview" class="d-flex flex-row flex-wrap">
        @foreach($values->media as $value)
        <div class='p-2'><img class='img-thumbnail' style='max-height:60px' height='60' src='{{$value->getUrl()}}'></div>
        @endforeach
    </div>
...
</x-form.form-input>
```

**Comment by francoism90** [comment]
"The Pro version of the package offers Blade, Vue and React components to handle uploads to the media library and to adminster the content of a medialibrary collection."

If you need this, buy the pro version. :)

**Comment by upeksha1996** [comment]
@francoism90  I'm sorry  I thought this was a bug since it was not in the pro media library section in the documentation and it has nothing mentioned that I cant use these methods in the blade files. May be it is better to mention it in the documentation. (https://spatie.be/docs/laravel-medialibrary/v8/basic-usage/retrieving-media)
