### ISSUE TITLE
Issue with HasMedia interface on fresh installation

### ISSUE THREAD

**Issue by Drillan767** [spatie/laravel-medialibrary#2164]
Hello,

I just tried to install the library on a fresh installation of Laravel 8.13, and followed your installation guide to make it work.

However, I stumbled upon an error at the section "[Preparing your model](https://spatie.be/docs/laravel-medialibrary/v8/basic-usage/preparing-your-model)", where it says to add `implements HasMedia` then `use InteractsWithMedia`:

![image](https://user-images.githubusercontent.com/16261166/98400555-7f549480-2064-11eb-961e-17f2692860a8.png)

As you can see, "HasMedia" is underlined with red, and on hovering, I get the following error:

![image](https://user-images.githubusercontent.com/16261166/98400616-9e532680-2064-11eb-92d9-b62944870cf5.png)

**Comment by Bapawe** [comment]
This appears to be a bug in PhpStorm instead of a bug in the package.
Also see the latest comment in this related issue: https://github.com/spatie/laravel-medialibrary/issues/1999

The bug still hasn't been fixed, i just checked in the latest version of PhpStorm 2020.3 EAP.

**Comment by pelmered** [comment]
They have this for the example in this issue: https://youtrack.jetbrains.com/issue/WI-53288
But it still does not work with this package. I reported this so hopefully, we will get a fix before the 2020.3 release.
