### ISSUE TITLE
Default settings for jpegoptim / webp optimization

### ISSUE THREAD

**Issue by Jon78** [spatie/laravel-medialibrary#2170]
Hi,

For image optimization we use both https://github.com/spatie/laravel-image-optimizer and the optimization in Media Library. We've noticed however that our jpeg conversions aren't as optimized as Google wants them to be :stuck_out_tongue:

This config sets the maximum quality to 85% in jpegoptim: https://github.com/spatie/laravel-image-optimizer/blob/d4785b4433192d04dee4ac7b68af143f1659206f/config/image-optimizer.php#L18 while the one in Media Library doesn't set a maximum: https://github.com/spatie/laravel-medialibrary/blob/master/config/media-library.php Resulting in hardly any optimization at all.

Also, the option for Webp optimization seems to be missing.

You might want to streamline these configs.

Jon

**Comment by freekmurze** [comment]
Hi @Jon78 feel free to PR improvements to our default config 👍

**Comment by Jon78** [comment]
#2171 should work

**Comment by freekmurze** [comment]
Thanks!
