### ISSUE TITLE
how to get a media file path (not its directory) ?

### ISSUE THREAD

**Issue by samerzaki** [spatie/laravel-medialibrary#2178]
hello, I'm using a custom media path generator and it works perfectly during uploading to disk:(public or s3), but when retrieving file path, it return its directory path not the file path itself
cod:
```
$media = Media::find(36);
$path = $media->getPath();
dd($path);
```
**expected result**:  media/images/380f350e2e152bcf9abd68a3c21adfa5/img.jpeg
**output result**:  media/images/380f350e2e152bcf9abd68a3c21adfa5/
it works fine with disk (s3) but local storage no

**Comment by samerzaki** [comment]
I found out
It turns out that while uploading the file, the getPath() in MyCustomPathGenerator is used but after that when retrieving the uploaded file path, It used the getPath() in MyCustomUrlGenerator.

**Comment by divian86** [comment]
> hello, I'm using a custom media path generator and it works perfectly during uploading to disk:(public or s3), but when retrieving file path, it return its directory path not the file path itself
> cod:
> 
> ```
> $media = Media::find(36);
> $path = $media->getPath();
> dd($path);
> ```
> 
> **expected result**: media/images/380f350e2e152bcf9abd68a3c21adfa5/img.jpeg
> **output result**: media/images/380f350e2e152bcf9abd68a3c21adfa5/
> it works fine with disk (s3) but local storage no
Could you help me i assume i'm doing something wrong?
When i  try this:
$media = Media::find(36);
$path = $media->getPath();
dd($path);
i get Call to undefined method Modules\Media\Entities\Media::getPath()

how should the Media model look like in order for the above to work?

Tnx
