### ISSUE TITLE
Image doesn't load with correct url

### ISSUE THREAD

**Issue by avitus-pereira** [spatie/laravel-medialibrary#2179]
I am uploading an image and creating a thumbnail of it. The image is saved in the correct folder. I opened the folder and verified it. I do a redirect->back() to the same view. The img tag on the page shows the new image url. But it doesn't display the image. If i copy this url from the img tag into another tab, the image is displayed. The image is only displayed by the img tag if i manually refresh my browser. I tried refreshing the page via jquery once its loaded, but still the image doesn't show. Not sure if this is related to media library or something to do with the browser. I am using laravel 6 with media library 7.

**Comment by freekmurze** [comment]
I'm thinking this isnt't related to our package.

**Comment by avitus-pereira** [comment]
> I'm thinking this isnt't related to our package.

I feel so too.have not really found s solution. Will update here once come across it. Thanks 👍
