### ISSUE TITLE
Algolia search function not working in docs

### ISSUE THREAD

**Issue by jozeflambrecht** [spatie/laravel-medialibrary#2182]
The search function of the documents does not work.
Example:
![image](https://user-images.githubusercontent.com/11506957/99410075-0c4ae980-28c0-11eb-81b6-885fc3224bf6.png)

I do not see errors in the console, did a hard refresh, ..

**Comment by riasvdv** [comment]
This is an issue with our Algolia docsearch config, see https://github.com/algolia/docsearch-configs/pull/2792, 

I've added a few more versions to be more future proof

Should be fixed once they merge that PR
