### ISSUE TITLE
Media Library Attachment Not Working When Multiple

### ISSUE THREAD

**Issue by swartjie** [spatie/laravel-medialibrary#2185]
Hey Guys,

So I just followed the guide to setup the x-media-library-attachment front-end, and the dingle instance (<x-media-library-attachment name="avatar" />) works perfectly.

But as soon as I want to handle multiple files it fails... Not sure why though, Can you please help me debug?

`<x-medialibrary-attachment multiple name="documents"/>`

Response:
`Unable to locate a class or view for component [medialibrary-attachment].`

**Comment by swartjie** [comment]
I just noticed the typo... There's a typo missing a - in the class name.
The guide on your site https://spatie.be/docs/laravel-medialibrary/v9/handling-uploads-with-media-library-pro/handling-uploads-with-blade may just need to be recommended :)

**Comment by freekmurze** [comment]
Feel free to send a PR to fix the docs (you'll find the docs as markdown files in the `/docs` directory of this repo)

**Comment by eznix86** [comment]
Just writing for future users:
- Create a morphable Model called Attachment / Document 
- Then you can attach it to any model you want, which relates to that one media
