### ISSUE TITLE
Upload Not Working 

### ISSUE THREAD

**Issue by swartjie** [spatie/laravel-medialibrary#2187]
Hey Guys,

I'm having a very hard time getting the medialibrary pro addon to work.
Essentially it does create the UI interface, and I can click and it responds visually, But I can't upload a file.

If I drag a file over it, Chrome just opens it up in a new tab (as if there wasn't an upload box) and clicking on it does not open the select box where I can choose a file.

What can I check? I did follow the setup guide step by step though...

**Comment by freekmurze** [comment]
Could you please open up an issue at https://github.com/spatie/laravel-medialibrary-pro ? Make sure to fill in all things asked in the issue template. This will help us in helping you better.screenshot). It's hard to help you if you only say "it is not working",  so include as much info as possible (errors messages, screenshots...)
