### ISSUE TITLE
Image Meta Data gets stripped even when using nonOptimized

### ISSUE THREAD

**Issue by mattcrn** [spatie/laravel-medialibrary#2188]
I need to keep the meta data(copyright) in my images when converting them.
When I use `nonOptimized()` the filesize increases, but the meta data is still missing.

```php
$this->addMediaConversion('original')->nonOptimized();
```

I tried removing `--strip-all` from Jpegoptim, but with no luck.

**Steps to reproduce:**
- add media conversion with nonOptimized option
- add image with meta information

**Expected outcome:**
meta information is still present on the conversion

**actual outcome:**
meta information is missing from the conversion

**Versions:**
- medialibrary: `7.18.0`
- laravel: `5.7.29`
- php: `7.3`

**Comment by freekmurze** [comment]
I would also think that removing `--strip-all` would be enough.

I would accept a PR that fixes this.

**Comment by mattcrn** [comment]
I narrowed it down to Glide.
 It seems the Glide library doesn't keep exif data, so even when not optimizing, the data gets stripped.
Possible solution would be to use a [library for adding exif data](https://github.com/zetdev/IptcJpeg) and parsing the data from the original and adding it to conversions afterwards.

**Comment by freekmurze** [comment]
It could also be considered to fix this at the source, and add an option for this at Glide.
