### ISSUE TITLE
Ability to cast image to default image for model

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-medialibrary#219]
Hi, I have a idea for this package which I encountered last time.

Lets say we have a store product, this store product has multiple images, wouldnt it be cool if you can say 'Set this image as main image', so the product always has multiple images, but 1 main image (to display on frontpages and such).

**Comment by sailingdeveloper** [comment]
Couldn't you use custom attributes for this?

**Comment by Cannonb4ll** [comment]
It would save more time if you can do ->setDefault() rather than doing ->withCustomProperties(['default =>  true])

**Comment by sailingdeveloper** [comment]
I like the sound of that. +1

**Comment by freekmurze** [comment]
You can [use your own media model](https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/using-your-own-model) to add any function you like to `Media`-objects.

**Comment by Cannonb4ll** [comment]
You mean by adding scope's to the custom model? (What would be the right approach?)

**Comment by freekmurze** [comment]
You can solve this in multiple ways.

If you want a syntax like use `$media->setAsMainImage()` you can add a function to your custom media model that marks that media object as the default (you can use custom properties for marking). The function should also unmark all Media object that have a relation to the same model.

To retrieve the default object you could use the `getFirstMedia` function. It accepts a filter as the second parameter:

```php 
 $yourModel->getFirstMedia('your-collection-name', ['default' => 'yes'])
```

On your model class you could introduce a function named `getDefaultImage`

```php
// in a model class

public function getDefaultImage()
{
   return $this->getFirstMedia('your-collection-name', ['default' => 'yes'])
}
```
