### ISSUE TITLE
Could not find a matching version of package spatie/laravel-medialibrary-pro.

### ISSUE THREAD

**Issue by jongravois** [spatie/laravel-medialibrary#2190]
I **do** have ```"spatie/laravel-medialibrary": "^8.0.0",``` installed.

I ran ```composer require spatie/laravel-medialibrary-pro``` and got this error

```
[InvalidArgumentException]
  Could not find a matching version of package spatie/laravel-medialibrary-pro. Check the package spelling, your ver
  sion constraint and that the package is available in a stability which matches your minimum-stability (dev).
```

**Comment by freekmurze** [comment]
Media Library Pro requires v9 of laravel-medialibrary. You'll also need a license.
Instructions in the docs: https://spatie.be/docs/laravel-medialibrary/v9/handling-uploads-with-media-library-pro/installation

**Comment by jongravois** [comment]
I have an unlimited license

**Comment by freekmurze** [comment]
Nice! That you'll only need to upgrade to laravel-medialibrary v9. Upgrading shouldn't be too difficult. There are instructions here: https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md#from-v8-to-v9
