### ISSUE TITLE
Unable to Install MediaLibrary Pro

### ISSUE THREAD

**Issue by jongravois** [spatie/laravel-medialibrary#2193]
I apologize for my ignorance but I have been trying this since I purchased an unlimited license.

I **had** MediaLibrary 8 installed but wasn't using it so I uninstalled the 8. version and removed the table from my database along with the record in the migration table ... so, a fresh start, eh.

According to the docs
```
Media Library Pro is a paid add-on package for Laravel Media Library. In order to use it, you must have the base version of media library installed in your project. Here are the installation instructions for the base version.
```

Clicking that link takes me to the base installation where I am given **two** choices: [1] ```If you only use the base package issue this command``` with a command and [2] ```If you have a license for media library pro, you should use laravel-media-library-pro```, so I run the second command ```composer require spatie/laravel-medialibrary-pro```

I get this in the Terminal:
```
 [InvalidArgumentException]
  Could not find a matching version of package spatie/laravel-medialibrary-pro. Check the package spelling, your ver
  sion constraint and that the package is available in a stability which matches your minimum-stability (dev).
```

PLEASE HELP!!!

**Comment by slzrdev** [comment]
You must follow step by step the instructions provided and it will work. https://spatie.be/docs/laravel-medialibrary/v9/handling-uploads-with-media-library-pro/installation

**Comment by jongravois** [comment]
I am trying to follow the instructions provided …

On that page you linked, the first paragraph states

Media Library Pro <https://spatie.be/docs/laravel-medialibrary/v9/handling-uploads-with-media-library-pro/medialibrary.pro> is a paid add-on package for Laravel Media Library. In order to use it, you must have the base version of media library installed in your project. Here are the installation instructions for the base version <https://spatie.be/docs/laravel-medialibrary/v9/installation-setup>.

To me that implies I have to follow that like to continue given you must have the base version of media library installed. So following that link, I get to

If you have a license for media library pro, you should use laravel-media-library-pro

The command provided there is what is causing my error.
composer require spatie/laravel-medialibrary-pro

**Comment by freekmurze** [comment]
Did you perform these steps? https://spatie.be/docs/laravel-medialibrary/v9/handling-uploads-with-media-library-pro/installation#requiring-media-library-pro

If you think the wording, can be better, feel free to send a PR (there's a little edit button on top of every page).

**Comment by jongravois** [comment]
What confused me was the link to installing the base version right after the phrase "you must have the base version of media library installed”. By clicking that link, I was taken away from the actual instructions to allow me to install. I didn’t know until I ignored the link and kept reading that page that the base is installed with Media Library Pro … stupid me, but I thought I was following the correct procedure.

Given that, I installed the package successfully but am now struggling with the CSS installation because I don’t have a webpack.config.js file. But I will keep working on it.

PLEASE, if I sounded brash or disrespectful, accept my apology. I am a huge Spatie fan. Not only do I sponsor Spatie, but I have also purchased Laravel Package Training, Laravel Beyond Crud, Laravel Backup Server. So the last thing I want to do is come across as mean or hateful.

Thanks!!!
Jon

**Comment by freekmurze** [comment]
> PLEASE, if I sounded brash or disrespectful, accept my apology. I am a huge Spatie fan. Not only do I sponsor Spatie, but I have also purchased Laravel Package Training, Laravel Beyond Crud, Laravel Backup Server. So the last thing I want to do is come across as mean or hateful.

No harm done, I didn't think that at all! Feel free to continue asking questions. And thanks for the support 👍

**Comment by jongravois** [comment]
Exactly which file do I put the following in? (LOL, I have never done anything with mix before other than what the installer does for me)

mix.override((webpackConfig) => {
    webpackConfig.resolve.modules = [
        "node_modules",
        __dirname + "/vendor/spatie/laravel-medialibrary-pro/resources/js",
    ];
});

**Comment by freekmurze** [comment]
@AdrianMrn can you answer this one?

**Comment by AdrianMrn** [comment]
@jongravois That code goes in your `webpack.mix.js` file. You can see what that looks like over here: https://github.com/spatie/laravel-medialibrary-pro-app/blob/master/webpack.mix.js

If you're using a version of laravel-mix lower than 6 (6 is currently in beta, so if you only followed the install instructions, this is likely), you'll have to use this code instead:

```js
mix.webpackConfig({
    resolve: {
        modules: [
            "node_modules",
            __dirname + "/vendor/spatie/laravel-medialibrary-pro/resources/js",
        ],
    },
});
```

**Comment by ltd300** [comment]
I'm having the same issue as [jongravois] I bought the pro version, and it seems so simple but maybe  I'm missing some package or something, do I need to install react? Let me show you after my installation and all the efort that I see. check picture below
I have bootstrap 4 and Laravel 8, I have livewire installed and I'm adding the tailwind CSS as a CDN like alpine but still nothing

![Screen Shot 2022-08-26 at 10 48 16 AM](https://user-images.githubusercontent.com/6537367/186933514-926c63df-aff1-49cf-aa60-f68aca51b651.png)
