### ISSUE TITLE
medialibrary base package (not pro) reference Pro package in config file.

### ISSUE THREAD

**Issue by SirLamer** [spatie/laravel-medialibrary#2196]
This line here: https://github.com/spatie/laravel-medialibrary/blob/9.1.5/config/media-library.php#L38

This references a dependency on the Pro package which may not be installed with the base package. This will generate errors, particularly during optimization on the production environment.

This setting should be addressed in a separate config file for the pro package.

**Comment by freekmurze** [comment]
What error will be generated?

**Comment by SirLamer** [comment]
Errrrrrr... yeah I suppose you're right, no error in runtime. But IDEs do report an error.

**Comment by freekmurze** [comment]
I'm going to leave it like is, because it's a nice for user of media library pro, to only bother with one file.

If this hinders you in some way, remove the entry from your config file.
