### ISSUE TITLE
media_model in Temporary Upload

### ISSUE THREAD

**Issue by dseeger** [spatie/laravel-medialibrary#2202]
Hello

In media library pro - Spatie\MediaLibraryPro\Models\TemporaryUpload 
the media Model set in config/media-library.php is not used. Instead it uses  Spatie\MediaLibrary\MediaCollections\Models\Media, ignoring the config setting.

Can that be changed?

Cheers
Dominik

**Comment by freekmurze** [comment]
The `TemporaryUpload` model is for internal use only.  I currently don't see a reason for adding support to let it work with another media model.

I'm closing this issue here as this concerns spatie/media-library-pro.  If you want to continue to conversation, create a new issue there.
