### ISSUE TITLE
Media is not uploaded with proper custom headers on S3

### ISSUE THREAD

**Issue by ebbbang** [spatie/laravel-medialibrary#2203]
When uploading a media that has custom headers for S3, if the remote file which is used to upload media is on the same disk then the file is copied directly. During this process, the custom headers expected in the new file are not inserted.

This is specifically happening in v8 of Media Library as the copy logic was not there till v7.
Check copyToMediaLibraryFromRemote() function in file src/MediaCollections/Filesystem.php line 52 of v8.

E.g.
1.Temp file is uploaded with private ACL.
2. Now when that file is used to upload to the new public location public ACL is provided through medialibrary.php config file.
3. Now maybe to improve performance, if both the files are on the same disk, they are just copied over and not re-retrieved and uploaded.
4. As the file is just copied over the extra custom headers are never applied.

**Comment by freekmurze** [comment]
This test proves that custom headers are working: https://github.com/spatie/laravel-medialibrary/blob/07302270b9ddbeb1c58de51321d3d73545d21639/tests/Feature/S3Integration/S3IntegrationTest.php#L223-L249

If this is not what you mean, please submit a failing test for me to look at (or even a PR that fixes the problem for you).

**Comment by ChrisThompsonTLDR** [comment]
@freekmurze I can confirm that what @ebbbang says is true.

To replicate this, upload a file to S3 with non-public ACL.  Then try to move it using

```
$plan->addMediaFromDisk($this->thumbnail->getRealPath(), config('livewire.temporary_file_upload.disk'))
    ->addCustomHeaders(config('media-library.remote.extra_headers'))
    ->toMediaCollection(Plan::MEDIA_THUMBNAIL, config('media-library.disk_name'));
```

`config('livewire.temporary_file_upload.disk')` is a temporary directory on S3, so the file already exists on S3 with private ACL.  The file is written to S3 by Livewire, not by anything to do with `spatie/laravel-medialibrary`.

The call to `addCustomHeaders()` doesn't actually set new headers on the file as it is moved from the tmp dir on S3 to the final location.  The media row in the database however is updated with

```
{"custom_headers": {"ACL": "public-read", "CacheControl": "max-age=604800"}}
```

The test you reference isn't testing adding media from the disk to another location on the disk.  It's testing writing a file
to the disk and then checking its headers.

Existing test:

1. laravel-medialibrary write file to S3 with custom headers
2. check that custom headers are there

Actual issue:

1. write file to disk with Livewire (private ACL)
2. make a new media model with laravel-medialibrary
3. set headers
4. write media to S3
5. read headers

**Comment by ChrisThompsonTLDR** [comment]
@freekmurze a followup to my preview comment.  It appears that the `copyFileOnDisk()` that is called at https://github.com/spatie/laravel-medialibrary/blob/master/src/MediaCollections/Filesystem.php#L80-L84 doesn't apply any custom headers.

If that method is changed to this nasty hack, everything works as expected.

```
    protected function copyFileOnDisk(string $file, string $destination, string $disk): void
    {
        $this->filesystem->disk($disk)
            ->copy($file, $destination);

        $this->filesystem->disk($disk)
            ->setVisibility($destination, \League\Flysystem\AdapterInterface::VISIBILITY_PUBLIC);
    }
```

Obviously this would be better if we weren't making a second call to S3, but I wasn't able to find a way to set headers during a copy operation from the Flysystem adapter.  This hack also doesn't take into account any dynamically configured things, but it works and shows what we're seeing and how to fix.

**Comment by ebbbang** [comment]
@ChrisThompsonTLDR The issue is fixed, merged and tagged. Happy coding.
