### ISSUE TITLE
PDF image generation not included by default

### ISSUE THREAD

**Issue by thejacer87** [spatie/laravel-medialibrary#2207]
in the docs, there is no mention of requiring `spatie/pdf-to-image` in composer to enable PDF image generation
https://spatie.be/docs/laravel-medialibrary/v8/converting-other-file-types/using-image-generators#pdf. the pdf generator is enabled by default in the config, so out of the box, it won't work

i made a PR here: https://github.com/spatie/laravel-medialibrary/pull/2206/files

it looks like it mentions to pdf-to-image in the v9 docs, so maybe it was an oversight. either way this PR should be merged in OR the v8 docs need an update to make sure user enables the required package

**Comment by freekmurze** [comment]
I'd accept a PR to the docs.
