### ISSUE TITLE
clearMediaCollectionExcept() and $media->delete() delete all media files from the disk

### ISSUE THREAD

**Issue by plakhin** [spatie/laravel-medialibrary#2223]
`$myModel->clearMediaCollectionExcept('default', $mediaCollection)` deletes all image files from the disk. Despite it keeps DB records for media passed in $mediaCollection, all media and conversions files for the model are being deleted from the disk.

tested on v8 and v9.4

**Comment by plakhin** [comment]
just tried `$media->delete()` and it also deletes all media files for the model from disk.
I guess this might be an issue with custom `MediaPathGenerator`.

**Comment by plakhin** [comment]
I found that the problem is that `removeAllFiles(Media $media)` method of `Spatie\MediaLibrary\MediaCollections\Filesystem` class deletes the entire directory.
How this behavior can be changed? I'm storing all media files for the model inside the same directory but with different file names.

**Comment by freekmurze** [comment]
Hi,

the medialibrary assumes that each media has it's own directory and than no other files are placed in that directory. This is by design and we probably won't change this behaviour.

**Comment by plakhin** [comment]
@freekmurze thanks for response.
I understand your point and anyway thank you for releasing and maintaining this brilliant library.
However, I will be happy if someday you make Filesystem class swappable via config or container.

**Comment by cristian-araujo** [comment]
> Hi,
> 
> the medialibrary assumes that each media has it's own directory and than no other files are placed in that directory. This is by design and we probably won't change this behaviour.

it need to be in the documentation, it's very important I lost many files for this behaviour
