### ISSUE TITLE
AddMediaFromRequest

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#223]
my controller
```
$report = MedicalReport::create($request->except(['report_images[]']));

$images = $request->file('report_images', []);

foreach($images as $image){
    $report->addMediaFromRequest($image)->toCollection('medical-reports');
}

```

the error
```
Call to undefined method Illuminate\Database\Query\Builder::addMediaFromRequest()
```

Any ideas what i am mission?

**Comment by freekmurze** [comment]
Please check if `$report` contains an Eloquent model

**Comment by kickthemooon** [comment]
i realized what it is.
I have 3.17.
Cant install 4.0 because i dont have php 7
:(
pitty

**Comment by moraleslevi** [comment]
Just in case anyone else comes across this issue. You can emulate the same functionality of `addMediaFromRequest` with this:

`if (request()->hasFile('image_field'))
{
    $work->addMedia(request()->file('image_field'))->toCollection('images');
}`
