### ISSUE TITLE
Array to String conversion error

### ISSUE THREAD

**Issue by ziming** [spatie/laravel-medialibrary#2237]
Recently I started receiving this error to a previously working code

ErrorException: Array to string conversion Exception

.../vendor/laravel/framework/src/Illuminate/Support/Str.php:494

```php
$result .= (array_shift($replace) ?? $search).$segment;
```

Laravel Framework version: 8.19.0
Medialibrary version: 9.4.1
PHP: I tried it on both PHP 7.4 and 8.0

I dumped the variables from Sentry out if it helps in debugging. Sorry but I'm not sure how to fix it yet (Or if this is a laravel/framework bug). Although what I suspect is that the empty array values in $replace should have been encoded as string first with json_encode

```php
$replace = [
  [], // should it have been a string? '[]' ? Also not sure why it is empty array
  [],
  42,
  'books',
  '34f394a5-5057-41d0-818e-254b09c2b36a',
  1,
  '2020-12-17 17:13:28',
  '2020-12-17 17:13:28',
];

$search = '?';

$subject = "insert into `media` (`name`, `file_name`, `disk`, `conversions_disk`, `collection_name`, `mime_type`, `size`, `custom_properties`, `generated_conversions`, `responsive_images`, `manipulations`, `model_id`, `model_type`, `uuid`, `order_column`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

$segments = explode($search, $subject);

// return  $segments;
$result = array_shift($segments);


// return $result;

// This is inside a loop in Str::replaceArray(...) method, but for your convenience I i'm not running it in a loop.
$result .= array_shift($replace) ?? $search; // Error Array to string conversion exception. The 1st item in $replace is []

// return $result;
```

Hope it helps!

**Comment by ziming** [comment]
As for my code to add the file it is this

```php
$this->addMedia($file)
                ->usingFileName("{$customFileName}")
                ->withCustomProperties(['zip_filename_prefix' => 'comedy/'])
                ->toMediaCollection('comedy');
```

**Comment by freekmurze** [comment]
Could you PR a test for this that show that it is failing?

**Comment by ziming** [comment]
hmm okay I try later or another day after my dinner.

**Comment by ziming** [comment]
My bad fixed it. I upgraded from v8 to v9 recently and wasn't aware that there is a new generated_conversions column now.

Closing the issue.

**Comment by AbdullahJisat** [comment]
eterteter

**Comment by KelvinMuriithi** [comment]
What exactly did you do?
