### ISSUE TITLE
Preview thumbnail not working

### ISSUE THREAD

**Issue by Robinvm** [spatie/laravel-medialibrary#2244]
Ive implemented the medialibrary, uploading works great, the thumbnail shows. But as soon as i refresh the page, the thumbnail does not show anymore, it is saved correctly. I use Vue2 and use the pro version.

**Comment by freekmurze** [comment]
Can you try to see if it works correctly in the demo app?
https://github.com/spatie/laravel-medialibrary-pro-app

Closing this here, if you continue to have problems, open up a issue at the media-library-pro repo.
