### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by dseeger** [spatie/laravel-medialibrary#2247]
The broken links I came accross are in the section 'Creating custom Vue components'.
They all pint to github.com/spatie/laravel-medialibrary-pro/...

There might be more of those in other sections.

**Comment by freekmurze** [comment]
Only license holders of media library pro can see that repo.

**Comment by dseeger** [comment]
I am a licence holder holder. What do I have to do to get access?

**Comment by freekmurze** [comment]
@dseeger Make sure you connect your spatie.be profile to GitHub and then you should have access. If not, send us a mail at info@spatie.be 👍
