### ISSUE TITLE
Path Without Domain

### ISSUE THREAD

**Issue by akhzarjaved** [spatie/laravel-medialibrary#2249]
I have media object and i'm trying to access only storage path from it.
```
dd([
      $media->getUrl('thumb') ,
      $media->getFullUrl('thumb')
  ]);
```

This code returns same url 
![image](https://user-images.githubusercontent.com/50201631/103867531-5777c080-50e9-11eb-9586-debf1b4dce02.png)

How do we get the path without domain/storage `Like laravel $request->file->store() works`

**Comment by freekmurze** [comment]
The package always returns full urls, this is by design. If you want relative URLs, you need to add some methods of your own to do that.

**Comment by akhzarjaved** [comment]
> The package always returns full urls, this is by design. If you want relative URLs, you need to add some methods of your own to do that.

Got it

**Comment by AngelinCalu** [comment]
@freekmurze,  so `getUrl` and `getFullUrl` are by design returning the same thing?

**Comment by jonasva** [comment]
This also confused me, as in the [docs](https://spatie.be/docs/laravel-medialibrary/v7/basic-usage/retrieving-media) it says `getFullUrl` returns 'url including domain'. Which makes me think that `getUrl` would return the url excluding the domain. Might be good to add a note in the docs that both `getFullUrl` and `getUrl` do the same thing.

**Comment by websitevirtuoso** [comment]
Why do we need 2 methods which do the same? maybe better remove 1 of them. It will remove confuses

**Comment by blaqdog** [comment]
In order to remove domain from url of an image, you have to remove `env('APP_URL')` from `url` in config
for example, if you have media disk set up in you `config/filesystems.php`:
```
'media' => [
    'driver' => 'local',
    'root'   => public_path('media'),
    //'url'    => env('APP_URL').'/media', // - here is what you need to remove
    'url'    => '/media',
    'visibility' => 'public',
    'throw' => false,
],
```
