### ISSUE TITLE
Conversions should keep source image format (png, gif only)

### ISSUE THREAD

**Issue by marsd** [spatie/laravel-medialibrary#225]
For all conversions, I have noticed that the default output format is jpg. For png and gif formats, some images might have transparency which will be lost during the conversion process. 

I have experimented with adding `'fm' => 'src'` and while this kept the correct source format, the filename is saved with `_filename_.src`. 
```
public function registerMediaConversions()
{
    $this->addMediaConversion('thumb_square_big')
        ->setManipulations([
            'w'   => 400,
            'h'   => 400,
            'fit' => 'crop',
            'fm'  => 'src',
        ])
        ->performOnCollections('upload');
}
```

Is there a "correct" way to achieve this?

**Comment by freekmurze** [comment]
Currently there is no option to keep the source image format. By default it'll convert images to `jpg` and `fm` can be used to convert all images of that profile to a specific format.

I'll add an option to keep to original format in the future. If you need this quick, I'd accept a PR.

**Comment by hugofabricio** [comment]
@freekmurze This pr will be accepted?

**Comment by bstrahija** [comment]
This would really be great if you could merge it in.

**Comment by freekmurze** [comment]
I'll try to make some time for this soon. If you need it quick, create a PR and be sure to add some tests.

**Comment by bstrahija** [comment]
There's already a PR in this issue that works perfectly.

**Comment by freekmurze** [comment]
I see that @marsd committed some code to his own repo. There currently is no PR.

**Comment by bstrahija** [comment]
Yeah I though it was a PR. Added it now: https://github.com/spatie/laravel-medialibrary/pull/237

**Comment by freekmurze** [comment]
Cool, thanks!

**Comment by freekmurze** [comment]
The PR has been merged. Changes are present in v4.2

**Comment by elephantux** [comment]
"spatie/laravel-medialibrary": "^4.10"

All image formats stored with .src extension :(

**Comment by elephantux** [comment]
'''
UploadedFile {#605 ▼
  -test: false
  -originalName: "cover.jpg"
  -mimeType: "image/jpeg"
  -size: 940996
  -error: 0
  path: "/tmp"
  filename: "phpdvrddw"
  basename: "phpdvrddw"
  pathname: "/tmp/phpdvrddw"
  extension: ""
  realPath: "/tmp/phpdvrddw"
  aTime: 2017-01-04 19:42:24
  mTime: 2017-01-04 19:42:24
  cTime: 2017-01-04 19:42:24
  inode: 654100
  size: 940996
  perms: 0100600
  owner: 900
  group: 900
  type: "file"
  writable: true
  readable: true
  executable: false
  file: true
  dir: false
  link: false
}
'''

Empty extension on any uploaded file. Why?

**Comment by langeuh** [comment]
Is there any way to achieve this in V5?

**Comment by freekmurze** [comment]
@AlexVanderbist is investigating this.

**Comment by AlexVanderbist** [comment]
Currently the `format()` conversion is available which allows you to set the conversion's output filetype:
```php
$this->addMediaConversion('png_conversion')
        ->format(Manipulations::FORMAT_PNG);
```

However there is no way to do something like `format('src')`.

@freekmurze maybe a `keepOriginalImageFormat()` method on the conversion is a good solution? Or should I implement the `format('src')` way in the Image package?

**Comment by langeuh** [comment]
Hi @AlexVanderbist, @freekmurze 

I'm using the `format()` to make everything a png since my thumbnails need to keep the transparency. But because of that .jpg's get turned into .png's as well.

The `format('src')` makes more sense to me and should imo be the default. I never understood why it defaults to a 'jpg' format. Probably because of speed and smaller size results. But if you want all your thumbs to be a .jpg, then you could use the format() function for that specific conversion.

Thanks for looking into this

**Comment by AlexVanderbist** [comment]
I agree, it's a bit strange that every image conversion defaults to a .jpg instead of the original format.

I can only imagine this is because in the spatie/image package the underlying glide package defaults to jpeg encoding. If this is the case it would probably make sense to make the spatie/image package default to the original image type.

**Comment by freekmurze** [comment]
In our primary use case for this package (displaying images and their conversion on a webpage) it does make sense to convert every image to a `jpg` by default.

However I get that there is a need to keep the original format. 

@AlexVanderbist please add that `keepOriginalImageFormat` function.
