### ISSUE TITLE
Error with addMediaFromDisk() using AWS S3 disk and ASPX files

### ISSUE THREAD

**Issue by mpryvkin** [spatie/laravel-medialibrary#2251]
Using laravel-medialibrary version 7.19.5 and PHP 7.2 to add ASPX file from AWS S3 disk using the code below.

```
$mediaItem = $model
    ->addMediaFromDisk(
        'uploads/e372fbba-d8c6-48fb-b724-9a222185d033-1610084966911.aspx', 
        's3'
    )
    ->usingName('test.aspx')
    ->usingFileName('test.aspx')
    ->toMediaCollection('attachments');
```

In the production code I am getting the following exception (amended/trimmed to hide sensitive info).

```
Log error Unable to create a model (finfo::file(uploads/e372fbba-d8c6-48fb-b724-9a222185d033-1610084966911.aspx): failed to open stream: No such file or directory)
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'finfo::file(upl...', '/web/...', 37, Array)
#1 /web/vendor/spatie/laravel-medialibrary/src/Helpers/File.php(37): finfo->file('01503e5d-81c0-4...')
#2 /web/vendor/spatie/laravel-medialibrary/src/Filesystem/Filesystem.php(102): Spatie\MediaLibrary\Helpers\File::getMimetype('uploads/e372fbba-d8c6-...')
#3 /web/vendor/spatie/laravel-medialibrary/src/Filesystem/Filesystem.php(63): Spatie\MediaLibrary\Filesystem\Filesystem->getRemoteHeadersForFile('uploads/e372fbba-d8c6-...', Array, '')
#4 /web/vendor/spatie/laravel-medialibrary/src/Filesystem/Filesystem.php(40): Spatie\MediaLibrary\Filesystem\Filesystem->copyToMediaLibraryFromRemote(Object(Spatie\MediaLibrary\Helpers\RemoteFile), Object(App\Models\Media), NULL, 'test...')
#5 /web/vendor/spatie/laravel-medialibrary/src/FileAdder/FileAdder.php(376): Spatie\MediaLibrary\Filesystem\Filesystem->addRemote(Object(Spatie\MediaLibrary\Helpers\RemoteFile), Object(App\Models\Media), 'test...')
#6 /web/vendor/spatie/laravel-medialibrary/src/FileAdder/FileAdder.php(364): Spatie\MediaLibrary\FileAdder\FileAdder->processMediaItem(Object(App\Models\Model), Object(App\Models\Media), Object(Spatie\MediaLibrary\FileAdder\FileAdder))
#7 /web/vendor/spatie/laravel-medialibrary/src/FileAdder/FileAdder.php(263): Spatie\MediaLibrary\FileAdder\FileAdder->attachMedia(Object(App\Models\Media))
#8 /web/vendor/spatie/laravel-medialibrary/src/FileAdder/FileAdder.php(271): Spatie\MediaLibrary\FileAdder\FileAdder->toMediaCollectionFromRemote('attachmen...', '')
#9 /web/app/Http/Controllers/Traits/HandlesMedia.php(219): Spatie\MediaLibrary\FileAdder\FileAdder->toMediaCollection('attachmen...')
```

While experimenting I found that the issue only affects files with some extensions (such as `.ASPX` or custom such as `.THIS-IS-CUSTOM-FILE`) that are not present in the `magic` file used by the system to determine MIME type.

If I try adding remote file with extensions such as TXT or PDF to a collection, no exception occurs and line (`src/Helpers/File.php(37)`) is never invoked.

The line (`src/Helpers/File.php(37)`) is invoked only for remote files with unregistered exception (such as `.ASPX`) and `finfo->file()` tries to read remote file locally which causes the exception.

It is worth noting that if I run the command above in Tinker console and ignore the exception, file gets added to the `media` table with blank `mime_type` column, see below.

**Tinker:**
```
>>> $mediaItem = $model->addMediaFromDisk('uploads/e372fbba-d8c6-48fb-b724-9a222185d033-1610084966911.aspx', 's3')->usingName('test.aspx')->usingFileName('test.aspx')->toMediaCollection('attachments');
PHP Warning:  finfo::file(uploads/e372fbba-d8c6-48fb-b724-9a222185d033-1610084966911.aspx): failed to open stream: No such file or directory in /vendor/spatie/laravel-medialibrary/src/Helpers/File.php on line 37
=> App\Models\Media {#4979
     name: "test.aspx",
     file_name: "test.aspx",
     disk: "s3",
     collection_name: "attachments",
     mime_type: "",
     size: 0,
     responsive_images: "[]",
     manipulations: "[]",
     model_id: 108,
     model_type: "App\Models\Model",
     uuid: "66c96d3f-2036-425f-9691-2d4fa6d29fd0",
     order_column: 439,
     updated_at: "2021-01-08 17:50:48",
     created_at: "2021-01-08 17:50:48",
     id: 574,
     ...
```
**Database:**
```
# select name, file_name, mime_type, disk, size from media where id=574;
   name    | file_name | mime_type | disk | size
-----------+-----------+-----------+------+------
 test.aspx | test.aspx |           | s3   |    0
```

**Comment by freekmurze** [comment]
Could you send a PR that fixes this issue for your app?

**Comment by mpryvkin** [comment]
Seem like the problem is in the `Spatie\MediaLibrary\Filesystem\Filesystem::getRemoteHeadersForFile()` function where remote file uploaded to AWS S3 doesn't have `Content-Type` header as in case with ASPX file. I suspect `getRemoteHeadersForFile()` is called with `$mimeType` equal to `null`. In this case on line 102 below `File::getMimeType($file)]` attempts to determine MIME type as if the file was local and not remote which causes the error.

https://github.com/spatie/laravel-medialibrary/blob/5e2057a926e0b72e5156e9a76a6a8dfadd89a9ce/src/Filesystem/Filesystem.php#L100-L107

Seems like `File::getMimeType()` should never be called in `getRemoteHeadersForFile()` since it assumes the file is local. Is it safe to replace line 102 above with the line below?
```
$mimeTypeHeader = $mimeType ? ['ContentType' => $mimeType] : [];
```

**Comment by mpryvkin** [comment]
Just tested retrieving MIME type for ASPX on AWS S3 in Tinker session.
```
>>> Storage::disk('s3')->mimetype('uploads/e372fbba-d8c6-48fb-b724-9a222185d033-1610084966911.aspx')
=> ""
```

Also checked in AWS Console that file has metadata key-value pair with key `Content-type` set to empty string.

So `$mimeType` will be set initially to empty string in the code above. 

Using proposed workaround would result in returning `Content-type` header set to empty string as well.

**Comment by freekmurze** [comment]
Feel free to PR the solution that worked for you. Make sure to include tests.
