### ISSUE TITLE
Conversion doesn't work with queues

### ISSUE THREAD

**Issue by elfeffe** [spatie/laravel-medialibrary#2252]
This is related to 
https://github.com/spatie/laravel-medialibrary/issues/1296

I have my media disk

```
'media' => [
            'driver'     => 'local',
            'root'       => public_path('media'),
            'url'        => env('APP_URL') . '/media',
            'visibility' => 'public',
        ],
```

And then my conversion
```
 $this
                ->addMediaConversion('big')
                ->optimize()
            ;
```

But it only works if I don't use queues, if I use them I get:

> League\Flysystem\FileNotFoundException: File not found at path: 102/caravaggio.jpg in /media/psf/www/neoteo/vendor/league/flysystem/src/Filesystem.php:389

The file is located at

`public/media/102/caravaggio.jpg`

I'm using the latest version of Laravel and this package

**Comment by elfeffe** [comment]
@freekmurze can I share any information that can help to debug it?

**Comment by freekmurze** [comment]
I currently don't have time to help debug projects. The testsuite proves that queued conversion are working. If possible, submit a failing test for me to look at.
