### ISSUE TITLE
Odd behaviour with singleCollection and CustomPathGenerator in s3 storage

### ISSUE THREAD

**Issue by diegoldev** [spatie/laravel-medialibrary#2253]
I was checking closed issues and figured out some related issues (#1273 && #1337) but I can´t understand where's the problem in order to be able to solve the mine one.

Seems that if your custom path not ended with media_id the entire collection is deleted (the uploaded file as welll).

But the unique restriction described in the documentation is that every media object must have a unique path

`There aren't any restrictions on how the directories can be named. When a Media-object gets deleted the package will delete its entire associated directory. To avoid tears or worse, make sure that every media gets stored its own unique directory.`

Specifically, in my case, I'm making the path as below:

 ```php       
 if ($media->model_type === Subscriber::class) {
            if ($media->collection_name ==='avatar') {
                return 'subscriber/avatar/model-id-' . $media->model_id . '/';
            }
        }
```
Worth mentioning that I'm using s3 storage.

Could be that s3 storage directory structure is interpreted in differente way of tradition OS filesystem?

**Comment by christophheich** [comment]
Can confirm this issue. Currently using the following custom path generator for Minio (S3 Compatible Storage): 

`
    public function getPath(Media $media): string
    {
        return $this->path . str_replace('\\', '/', $media->collection_name) . '/' . strtolower(basename($media->model_type)) . '/' . $media->model_id . '/';
    }
`

The path will be collectionName/modelName/modelId (/avatar/student/18/) when adding singleFile to a media collection the first upload works completly as excepted, the second upload however will delete the complete collection (everything inside /avatar/)

If i do not add singlFile and instead clear the collection before uploading a new picture it works as expected.

**Comment by christophheich** [comment]
As stated [here ](https://github.com/spatie/laravel-medialibrary/issues/1273#issuecomment-456709755) the model_id should not be used, if the model_id will be changed to id of the media file it works as expected.

Guess this can be closed?

**Comment by diegoldev** [comment]
@christophheich In the refered link says that shoud not be used, but not explain why

In the documentation is defined that 

>There aren't any restrictions on how the directories can be named. When a Media-object gets deleted the package will delete its entire associated directory. To avoid tears or worse, make sure that every media gets stored its own unique directory.

If I comply  with that statement, why I should not use?
