### ISSUE TITLE
keepOriginalImageFormat() needs to apply to all Collections

### ISSUE THREAD

**Issue by DominicGebhart** [spatie/laravel-medialibrary#2269]
Hi,

i was struggling 2 days with the Problem that the URLs from Conversions where not correct when i used the keepOriginalImageFormat().

f.ex.

```
public function registerMediaCollections(): void
{
        $this->addMediaCollection('header')
            ->singleFile()
            ->registerMediaConversions(function () {
                $this->addMediaConversion('small')
                    ->fit(Manipulations::FIT_CROP, 250, 125);
                $this->addMediaConversion('default')
                    ->fit(Manipulations::FIT_CONTAIN, 500, 250);
            });

        $this->addMediaCollection('icon')
            ->singleFile()
            ->registerMediaConversions(function () {
                $this->addMediaConversion('small')
                    ->fit(Manipulations::FIT_CROP, 80, 80)
                    ->keepOriginalImageFormat();
                $this->addMediaConversion('default')
                    ->fit(Manipulations::FIT_CONTAIN, 120, 120)
                    ->keepOriginalImageFormat();
            });
 }
```

when i upload a .png file and call `$model->getMedia('icon')->first()->getUrl('small')`
it will return `https://localhost/storage/18/conversions/5f6b01072d0fa040b1df1774edbfd77a-small.jpg`
and not a .png
so the conversion is crated as png but the url will always return .jpg for the conversions

I found out, that you have to set `keepOriginalImageFormat()` on every collection conversions in order for the `getUrl()` to return the correct file extension.

so this is working
```
public function registerMediaCollections(): void
{
        $this->addMediaCollection('header')
            ->singleFile()
            ->registerMediaConversions(function () {
                $this->addMediaConversion('small')
                    ->fit(Manipulations::FIT_CROP, 250, 125)
                    ->keepOriginalImageFormat();
                $this->addMediaConversion('default')
                    ->fit(Manipulations::FIT_CONTAIN, 500, 250)
                    ->keepOriginalImageFormat();
            });

        $this->addMediaCollection('icon')
            ->singleFile()
            ->registerMediaConversions(function () {
                $this->addMediaConversion('small')
                    ->fit(Manipulations::FIT_CROP, 80, 80)
                    ->keepOriginalImageFormat();
                $this->addMediaConversion('default')
                    ->fit(Manipulations::FIT_CONTAIN, 120, 120)
                    ->keepOriginalImageFormat();
            });
 }
```

I currently have not the time to investigate this further and to make a PR. I will stick with setting the keepOriginalImageFormat() to all. But maybe someone else got the time to look into this, i guess it should be working when it's only set to one MediaCollection, if i'm wrong then it should be described somewhere.

Running on Laravel v8.21.0
Medialibrary v9.0.0
PHP 7.4

**Comment by CaReS0107** [comment]
How about, file format for exemple my file name is New text document.txt and when is stored in media column file_name is stored like New-text-document.txt but i need to keep original file name. any sugestion please?

**Comment by freekmurze** [comment]
Calling `keepOriginalImageFormat` on each collection seems the way to go for now.
