### ISSUE TITLE
How to handle multiple file inputs with addMediaFromRequest?

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#227]
So the addMediaFromRequest expects the request key
in my case the request key is images[] so it is an array of files
after which the key becomes and integer.

![multiple-file-upload](https://cloud.githubusercontent.com/assets/7913974/15217592/912b369c-185c-11e6-88b8-313cc1e402a3.jpg)

so $request->file('images') returns this:
```
array:2 [▼
    0 => UploadedFile {#364 ▶}
    1 => UploadedFile {#356 ▶}
  ]
```

when i do this
```
$report->addMediaFromRequest('images')->toCollection('medical-reports');
```
i get this error
```
FileCannotBeAdded in FileCannotBeAdded.php line 13:
Only strings, FileObjects and UploadedFileObjects can be imported
```

and when I do this
```
foreach($request->file('images') as $image){
            $report->addMediaFromRequest($image)->toCollection('medical-reports');
        }
```
I get this error
```
FileCannotBeAdded in FileCannotBeAdded.php line 49:
The current request does not have a file in a key named `C:\wamp64\tmp\php3894.tmp`
```
Which is the true, the request does not have any key names by the tmp upload path of the file

Now I am not sure how to feed the addMediaFromRequest method...

**Comment by freekmurze** [comment]
When uploading multiple files with the same name in the request, do not use `addMediaFromRequest`

Get the files of the request and add them manually.

Try this:

```php
foreach($request->file('images') as $image) {
   $report->addMedia($image)->toCollection('medical-reports');
}
```

**Comment by theinhlamaw** [comment]
I was looking for the same answer for Laravel Medialibrary v.7 here. The following code works for me.

```php
foreach($request->file('images') as $image) {
   $report->addMedia($image)->toMediaCollection('medical-reports');
}
```
I only need to change toCollection() to toMediaCollection(). Thanks @kickthemooon and @freekmurze.

**Comment by ridislam** [comment]
@freekmurze how can I show these media in list view page?

**Comment by Mohammed-Alama** [comment]
> @freekmurze how can I show these media in list view page?

try to add it to specific media collection then use `getMedia('collection_name')` to get media

**Comment by Alhiane** [comment]
@theinhlamaw  it's slow the server whene using foreach

**Comment by tayyabzino19** [comment]
You can also try this 
 if ($request->hasFile('photos')) {
                $fileAdders = $product->addMultipleMediaFromRequest(['photos'])
            ->each(function ($fileAdder) {
                $fileAdder->toMediaCollection('products');
            }); }
