### ISSUE TITLE
Dropbox Filesystem

### ISSUE THREAD

**Issue by Rhincodon** [spatie/laravel-medialibrary#228]
Hi, I am trying upload media to dropbox filesystem and got this error:

```
ERROR: InvalidArgumentException: 'data' has bad type; expecting string, got resource in vendor/dropbox/dropbox-sdk/lib/Dropbox/Checker.php:22
```

Using League Dropbox Filesystem.

Change `put` to `putStream` in this [line](https://github.com/spatie/laravel-medialibrary/blob/master/src/Filesystem.php#L64) helps.

**Comment by freekmurze** [comment]
Could not reproduce this. Please reopen if the problem still persists.
