### ISSUE TITLE
How to upload file to 'local' and 's3' storage on the same time

### ISSUE THREAD

**Issue by pashtostories** [spatie/laravel-medialibrary#2293]
Is it possible to pass array of storage disks inside `toMediaCollection()` like below:

`$newsItem->addMedia($pathToAFile)->toMediaCollection('images', ['s3', 'local'])`

I want to be able to upload file to both local storage and s3 storage in same time so that in future I can easily serve file from any of these storages.

**Comment by drbyte** [comment]
> `$newsItem->addMedia($pathToAFile)->toMediaCollection('images', ['s3', 'local'])`

That would probably be more elegant. Without it perhaps `copy` it afterward? https://spatie.be/docs/laravel-medialibrary/v9/advanced-usage/moving-media#copying-media

**Comment by freekmurze** [comment]
I'd accept a PR with tests and updated docs for this.

**Comment by shikolat** [comment]
I have the same issue
i cloned the object

**Comment by pashtostories** [comment]
> > `$newsItem->addMedia($pathToAFile)->toMediaCollection('images', ['s3', 'local'])`
> 
> That would probably be more elegant. Without it perhaps `copy` it afterward? https://spatie.be/docs/laravel-medialibrary/v9/advanced-usage/moving-media#copying-media

Do I need to create a new table for it just like `media` table? I didn't understand the fully concept of copying file.

**Comment by drbyte** [comment]
I think to use the `copy` method for storing on multiple disks, you would first store it, then retrieve the media object, then use the copy command to copy it again to the same model but to a different disk.

I haven't tried it, but I'm guessing:
```
$yourModel->addMedia($pathToFile)->toMediaCollection('collection-name', 's3');
$mediaItem = $yourModel->getMedia()->first();
$copiedMediaItem = $mediaItem->copy($yourModel, 'collection-name', 'local');
```
There are downsides: this registers the media item into the media table twice, so you may have to accommodate that in your app to avoid displaying duplicates. Also, if the media is updated you'd need to do something about updating the copy on the other disk.

I don't use this library often. Others may have better ideas.

**Comment by freekmurze** [comment]
Closing as some possible strategies have been suggested. Feel free to PR improvements.
