### ISSUE TITLE
Can't use conversions: Operation not permitted

### ISSUE THREAD

**Issue by laravelpro** [spatie/laravel-medialibrary#230]
Hi, when I add a conversion, the image is not generated:

ErrorException in GlideImage.php line 67:
rename(/tmp/fB760HCQkpqhBJd3thumb.png/a7ea43680990f34f595276da8b85f03e,/home/vagrant/Code/llaravel5/storage/medialibrary/temp/kR53PLNp3abgLD15/fB760HCQkpqhBJd3thumb.png): Operation not permitted

Please help to solve the issue.

**Comment by laravelpro** [comment]
//        rename($conversionResult, $outputFile);

        if( copy($conversionResult, $outputFile) )
        {
            unlink($conversionResult);
        }

So I have to replace the rename function and it works. 

Can you update the package?

**Comment by canvural** [comment]
The error is about your storage folder permissions i think.

**Comment by freekmurze** [comment]
Thinking the same as @canvural: please check that `/home/vagrant/Code/llaravel5/storage/medialibrary/temp/` exists and that your php process is allowed to write there.

**Comment by tcsehv** [comment]
I know it is a closed issue, but this might help people that run into the same issue. I had the same issue when using vagrant with VMWare Fusion while using the default shared folder settings for my project files. The files where moved (with rename), but php still triggered an error. 
When I changed the shared folder settings to NFS the problem was gone. Another option is to suppress the error by using @rename, but ugh.

**Comment by matriphe** [comment]
I found this error too. The image was renamed and existed, but the error occured. 

I were on Mac, it said:

```
ErrorException in GlideImage.php line 67:
rename(/var/tmp//UuVUlLnpaBWh2nB2thumbnail.jpg/b2d297c271f2457bf482ee90d5ff439e, /home/matriphe/dev/laravel/storage/medialibrary/temp/XMFM21eCqTsI2n0z/UuVUlLnpaBWh2nB2thumbnail.jpg): Operation not permitted
```

Both `/var/tmp//UuVUlLnpaBWh2nB2thumbnail.jpg/b2d297c271f2457bf482ee90d5ff439e` and `/home/matriphe/dev/laravel/storage/medialibrary/temp/XMFM21eCqTsI2n0z/UuVUlLnpaBWh2nB2thumbnail.jpg` existed.

Both directories has been `chmod`-ed to 777.

**Comment by matriphe** [comment]
@laravelpro in what file did you change the function?

**Comment by matriphe** [comment]
just did what @laravelpro did, by changing `rename` function to `copy` on laravel-glide's `GlideImage.php` and worked like charm.

I think using `copy` instead of `rename` is great option.

**Comment by matriphe** [comment]
I've been looking for this issue. Now it's confirmed that it's a ownership and permission problem. 

On my OSX 10.11, I changed ownership of `/var/temp` folder using `chown -R {username}:staff /var/tem` (notice `staff` group). 

I use PHP 7.0 from Homebrew. I don't know why why the images were uploaded to `/var/tmp`. Changing `upload_tmp_dir` in `php.ini` has no effect.

It might help someone who facing the same problem with mine.

**Comment by bakerstreetsystems** [comment]
I had the same problem and @matriphe's suggestion helped. I ran the following command and now everything works great:

`sudo chown -R {your username}:staff /var/tmp`

I'm on a Mac running macOS Sierra with Mamp Pro running PHP 7.
