### ISSUE TITLE
laravel-medialibrary:^9.0.0 incompatible with PHP 8.0.1

### ISSUE THREAD

**Issue by nille** [spatie/laravel-medialibrary#2310]
Following the instructions on [https://spatie.be/docs/laravel-medialibrary/v9/installation-setup](https://spatie.be/docs/laravel-medialibrary/v9/installation-setup) I tried to add laravel-medialibrary with `composer require "spatie/laravel-medialibrary:^9.0.0"`but getting the error:

```
[InvalidArgumentException]
Package spatie/laravel-medialibrary at version ^9.0.0 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
``` 

I'm running Laravel Sail which, as of writing this, ships with PHP 8.0.1.

**Comment by freekmurze** [comment]
I'm thinking we already allow all PHP 8.0.X versions.

https://github.com/spatie/laravel-medialibrary/blob/94ab6828965d9277c09e0b2f84682b0f31de32a1/composer.json#L25
