### ISSUE TITLE
/private/var/tmp error with Livewire Integration

### ISSUE THREAD

**Issue by daylightstudio** [spatie/laravel-medialibrary#2316]
I'm using the non-pro version of the library with Livewire and am getting an error trying to add to a media collection with `$resource->addMedia($file)->toMediaCollection($collection, $disk)` where it can't find the originally uploaded file in the `private/var/tmp` folder (on a Mac). 
```
/private/var/tmp/tQuzyBKOIsr59ILP50UGHZXB8h18jG-metabGlsbGFyZF9ieWVfYnllLmdpZg==-.gif
```

This part of the path is created by Livewire and is not the real tmp file name:
```
tQuzyBKOIsr59ILP50UGHZXB8h18jG-metabGlsbGFyZF9ieWVfYnllLmdpZg==-.gif
```

Livewire is using `tmpfile()` to create the file originally:
https://github.com/livewire/livewire/blob/b647ac63378ea02bdac975f70a4e57aea84bda0b/src/TemporaryUploadedFile.php#L21

If I change this to`getRealPath()` it uses the path that is in the `storage/app/livewire-tmp` directory and works:

https://github.com/spatie/laravel-medialibrary/blob/227b47bd001df05a7f3fdc7c7e5d801def61be27/src/MediaCollections/FileAdder.php#L104

```
//$this->pathToFile = $file->getPath().'/'.$file->getFilename();
$this->pathToFile = $file->getRealPath();
```

I realize that throwing Livewire into the mix may complicate it but I thought that a change to use `getRealPath()` could maybe be an easy fix (famous last words...)??? `getRealPath()` would return `false` if the path wasn't correct being one difference I can think of.

As an example, here is the Livewire Component. The error occurs when saved:
```
class FileTestUploadLivewire extends Component
{
    use WithFileUploads;

    public $photo;

    public function save()
    {
        // For testing... this model is using the 'HasMedia' trait
        $resource = Example::find(1);

        // Error happens on the following line:
        $resource->addMedia($this->photo)->toMediaCollection('default', 'media');
    }

    public function render()
    {
        return view('filetestupload-livewire');
    }
}
```

`filetestupload-livewire`:
```
<form wire:submit.prevent="save" enctype="multipart/form-data">
    <input type="file" wire:model="photo">

    @error('photo') <span class="error">{{ $message }}</span> @enderror

    <button type="submit">Save Photo</button>
</form>
```

Lastly, for reference, this is the `$photo` object on save
```
Livewire\TemporaryUploadedFile {#615 ▼
  +"disk": "local"
  #storage: Illuminate\Filesystem\FilesystemAdapter {#685 ▶}
  #path: "livewire-tmp/qObFvXUTXerwxsHFN2aHjrmjdNTRdG-metabGlsbGFyZF9ieWVfYnllLmdpZg==-.gif"
  -test: false
  -originalName: "qObFvXUTXerwxsHFN2aHjrmjdNTRdG-metabGlsbGFyZF9ieWVfYnllLmdpZg==-.gif"
  -mimeType: "application/octet-stream"
  -error: 0
  #hashName: null
  path: "/private/var/tmp"
  filename: "qObFvXUTXerwxsHFN2aHjrmjdNTRdG-metabGlsbGFyZF9ieWVfYnllLmdpZg==-.gif"
  basename: "phpDODoCf"
  pathname: "/private/var/tmp/phpDODoCf"
  extension: ""
  realPath: "/myfakefolder/testing/storage/app/livewire-tmp/qObFvXUTXerwxsHFN2aHjrmjdNTRdG-metabGlsbGFyZF9ieWVfYnllLmdpZg==-.gif"
  aTime: 2021-03-06 16:32:10
  mTime: 2021-03-06 16:32:10
  cTime: 2021-03-06 16:32:10
  inode: 8680582352
  size: 2715703
  writable: false
  readable: false
  executable: false
  file: false
  dir: false
  link: false
}
```

**Comment by daylightstudio** [comment]
Come to think of it, this seems like it may be something Livewire should fix instead so I've opened a ticket there with a suggestion for them to fix:
https://github.com/livewire/livewire/issues/2598

**Comment by freekmurze** [comment]
Closing this issue as it should be fixed on the Livewire side.
