### ISSUE TITLE
Class 'League\Glide\ServerFactory' not found since spatie/image/1.10.3

### ISSUE THREAD

**Issue by FrancoisVinatis** [spatie/laravel-medialibrary#2326]
Hi !

Since spatie/image/1.10.3 i get this error :

![image](https://user-images.githubusercontent.com/19688556/110658184-c5ac3280-81c1-11eb-879b-7864991fa7bf.png)

it is working when i'm locking the version of on spatie/image/1.10.2

**Comment by Nielsvanpach** [comment]
This has been reverted in 1.10.4
