### ISSUE TITLE
[Question] Is there a query builder scope for hasMedia?

### ISSUE THREAD

**Issue by mahony0** [spatie/laravel-medialibrary#235]
I examined documentation a bit but can't see scope method like this feature. Is there a way for achieving this?

I want to where logic on query builder "retrieve models where hasMedia"? It can be also improved by providing media collection name for specific hasMedia checks.

**Comment by sebastiandedeyne** [comment]
There currently aren't any scopes provided by the package, we'd accept PR's that add some though, as long as they're not too specific.
