### ISSUE TITLE
Issue with installation v9.5

### ISSUE THREAD

**Issue by webmastervinay** [spatie/laravel-medialibrary#2368]
Lower version of spatie/laravel-medialibrary works fine. But v9.5 is unable to install. I guess there is some issue with spatie/temporary-directory package version.

spatie/laravel-medialibrary 9.5.0 requires spatie/temporary-directory ^1.1 -> found spatie/temporary-directory[1.1.0, ..., 1.3.0] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match.

![image](https://user-images.githubusercontent.com/5024049/113421070-0fb2bd80-93e8-11eb-913a-51c9b8da5171.png)

**Comment by freekmurze** [comment]
I cannot reproduce this. I think this is caused by the dependencies in your particular app. Feel free to provide us with a minimal app in which you recreate the problem.

**Comment by ScriptMintSolution** [comment]
After investigating further, I noticed that the issue comes when spatie/laravel-backup package is installed. Here is a video http://youtube.com/watch?v=riFNCwVYEnU to reproduce the issue where I used a fresh laravel appliation.
