### ISSUE TITLE
Version 9.5.1 return always the FallbackUrl

### ISSUE THREAD

**Issue by rslanzi** [spatie/laravel-medialibrary#2372]
After updating to version 9.5.1 the links to images converted to thumbail (`->getFirstMediaUrl('posts', 'thumb')`) no longer work. By downgrading to version 9.5.0 everything works normally again.

**Comment by omarhen** [comment]
+1

**Comment by Tofandel** [comment]
Introduced by https://github.com/spatie/laravel-medialibrary/pull/2369

Are your thumbnails actually generated?

**Comment by omarhen** [comment]
> Introduced by #2369
> 
> Are your thumbnails actually generated?

generated or not yet 

returning the original image If exists is better than returning FallbackUrl

**Comment by rslanzi** [comment]
> Are your thumbnails actually generated?

For me, yes. Images and thumbnails exist.

**Comment by Tofandel** [comment]
Did you migrate from v8 to v9? If yes are the images prior to v9 going to fallback and the newly created ones going correctly to the url?

**Comment by rslanzi** [comment]
> Did you migrate from v8 to v9? If yes are the images prior to v9 going to fallback and the newly created ones going correctly to the url? 
No, I have upgraded from 9.4 to 9.5.1.  I upgraded from 8 to 9 on 18 January but everything works fine up to version 9.5.0.

> You might want to check the `generated_conversions` column of the media table, check if you have some content in it (You should have `{"thumb": true}`) if you don't you have an underlying issue

In the database, the conversions are stored in the 'custom_properties' column while the 'generated_conversion' column, as per the instructions here https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md, are set to an empty array [].

By inserting {"thumb": true} as you suggested, it actually works.

**Comment by rslanzi** [comment]
Thanks @freekmurze! 9.5.3 solve the "problem".

**Comment by Tofandel** [comment]
@rslanzi Your problem will only partially be fixed, as now the lib thinks your thumbnails are not generated because of the missing `{"thumb": true}` so it will display the original file instead, so make sure to debug and check that your server is calling `markAsGenerated` when generating the thumbnails and that you have no error within the call

**Comment by rslanzi** [comment]
> @rslanzi Your problem will only partially be fixed, as now the lib thinks your thumbnails are not generated because of the missing `{"thumb": true}` so it will display the original file instead, so make sure to debug and check that your server is calling `markAsGenerated` when generating the thumbnails and that you have no error within the call

Thanks @Tofandel, I manually updated the `generated_conversions` column by carrying the conversions that were in the `custom_properties` column. Maybe you should update the documentation, now it seems to be a step only if you are using Media Library Pro: '_If you are using Media Library Pro, you should copy the values you now have in the generated_conversions key of the custom_properties column to generated_conversions_'.

**Comment by Tofandel** [comment]
Making a PR for the doc right now

**Comment by rslanzi** [comment]
Great! Thanks
