### ISSUE TITLE
Question: responsiveImageWithPlaceholder onload=null?

### ISSUE THREAD

**Issue by CSenshi** [spatie/laravel-medialibrary#2375]
What is the purpose of doing `onload=null; `?

I used Livewire to load data and loaded data showed only tiny placeholder of image. Removing `onload=null; ` fixed it and rendered image, so I want to know what is purpose of this part of code? Does it break anything?

https://github.com/spatie/laravel-medialibrary/blob/d9900e222354bec0f0f99054c8414db7012e8448/resources/views/responsiveImageWithPlaceholder.blade.php#L1

**Comment by willemvb** [comment]
`onload=null` just ensures that the current `onload` function is cleaned up after first use and doesn't run twice. It fixed weird `history.back()` and cache behavior before.

I can imagine this conflicts with Livewire, so just go ahead and remove it. Let us know in case you encounter any issues with this, so we can consider to update the script accordingly.

**Comment by cbaconnier** [comment]
Removing `onload=null` did work on Firefox, but does an incredible amount of requests with Chrome. It basically keeps trying to update the image. I don't have a solution at the moment other than not using srcset.
