### ISSUE TITLE
When new responsive image added, old responsive images  are deleted from responsive-images folder

### ISSUE THREAD

**Issue by abrampl** [spatie/laravel-medialibrary#2378]
Problem with function generateResponsiveImages -> cleanResponsiveImages -> removeResponsiveImages

```php
public function removeResponsiveImages(Media $media, string $conversionName = 'media_library_original'): void
    {
        $responsiveImagesDirectory = $this->getResponsiveImagesDirectory($media);

        $allFilePaths = $this->filesystem->disk($media->disk)->allFiles($responsiveImagesDirectory);

        $responsiveImagePaths = array_filter(
            $allFilePaths,
            fn (string $path) => Str::contains($path, $conversionName)
        );

        $this->filesystem->disk($media->disk)->delete($responsiveImagePaths);
    }
```

When new image added example

```
$model->addMedia(storage_path('Foto1.jpg'))->setFileName('Foto1.jpg')->withResponsiveImages()->preservingOriginal()->toMediaCollection('Fotos')
$model->addMedia(storage_path('Foto2.jpg'))->setFileName('Foto2.jpg')->withResponsiveImages()->preservingOriginal()->toMediaCollection('Fotos')
```

all previous responsive-images for Foto1 are deleted !!!

**Comment by thomaskenne** [comment]
I have the same problem. 
The responsive_images column in the media table is also being pruned for the "first" set of responsive images.

**Comment by kyosifov** [comment]
@brendt @freekmurze 

Any update on this? I get the same problem.

**Comment by freekmurze** [comment]
When we don't post something, there's no update.

**Comment by brendt** [comment]
If anyone is up to submitting a failing test as a PR, we can look into fixing it. We never had to deal with regenerations from scratch, so this issue is rather low priority for us.

**Comment by freekmurze** [comment]
Like @brendt said, we haven't experienced this issue ourselves, so for now we're not going to invest time in it.

Feel free to PR a fix with tests 👍
