### ISSUE TITLE
Add base64 support for `addMedia`

### ISSUE THREAD

**Issue by taliptako** [spatie/laravel-medialibrary#238]

**Comment by freekmurze** [comment]
Please provide some info on what you'd expect the medialibrary to do. If possible add some code that you'd like to work and state why you need this.

**Comment by taliptako** [comment]
I'm using cropit in my project [](https://github.com/scottcheng/cropit) and with this plugin users pick a photo and crop it.
This plugin create base64 code for this image also other popular similiar tools do the same.
So i should save this image to my media library easily but i cant, only i can do is decode this code and after save it with file_put_contents function

**Comment by a-komarev** [comment]
Here is my quick solution for this.

```php
/**
 * Get file content from base64 string.
 *
 * @param $data
 * @return string
 */
private function getBase64Content($data)
{
    list($type, $data) = explode(';', $data);
    list(, $data) = explode(',', $data);
    $data = base64_decode($data);

    return $data;
}

/**
 * Saves temporary file from base64 string.
 *
 * @param $filename
 * @param $data
 * @return File
 */
private function saveFileFromBase64($filename, $data)
{
    $data = $this->getBase64Content($data);
    file_put_contents($filename, $data);
    $file = new File($filename);

    return $file;
}
```

**Comment by freekmurze** [comment]
I'd accept a PR that adds a `addMediaFromBase64` to the package. You can some cues from the [`addMediaFromUrl`](https://github.com/spatie/laravel-medialibrary/blob/b62a50f6c629a4c00ef558d6fc459b001639a38b/src/HasMedia/HasMediaTrait.php#L80) method.

**Comment by a-komarev** [comment]
it should be in `addMediaFromUrl` because v3 don't have `addMediaFromRequest` method or there are any other reasons to place it there? Base64 is not an URL and will come from request.

**Comment by taliptako** [comment]
I have problem with picture extensions because before sending my picture to AddMedia i should save it to somewhere and i think i should use temporary folder for this.But i cant save temporary file with extension(not sure).

> $tmpFile = tempnam(sys_get_temp_dir(), 'media-library');
        file_put_contents($tmpFile, $stream);

        $filename = basename(parse_url($url, PHP_URL_PATH));

This code snippet from addMediaFromUrl function in this example you get extension from url but if i save my picture to temporary folder i cant send you a image path with extension for this media library save pictures without extensions.

We should find best way to do this.
And i thought maybe we can use this code in AddMedia i find this code from this package.
[https://github.com/Intervention/image](url)

>     /**
     * Determines if current source data is base64 encoded
     *
     * @return boolean
     */
    public function isBase64()
    {
        if (!is_string($this->data)) {
            return false;
        }
        return base64_encode(base64_decode($this->data)) === $this->data;
    }

**Comment by a-komarev** [comment]
@taliptako You can get an extension from example I've provided above:

```php
list($type, $data) = explode(';', $data);
list(, $data) = explode(',', $data);
list(, $extension) = explode(':', $type);
$data = base64_decode($data);
```

- `$data` - exact file content.
- `$extension` - file extension.
- `$type` - file mime/type

**Comment by a-komarev** [comment]
@taliptako I've updated an example.

**Comment by taliptako** [comment]
@a-komarev Thank you i will use your example until the new feature.

**Comment by a-komarev** [comment]
@taliptako Do you plan to make a PR for this feature?

**Comment by taliptako** [comment]
@a-komarev Actually no :) Should i close the issue ?

**Comment by a-komarev** [comment]
@taliptako :sob:

**Comment by freekmurze** [comment]
I'll close this for now. Reopen if somebody would like to work on a PR for this.

**Comment by fgreinus** [comment]
This has now been implemented and successfully merged btw :-).

**Comment by freekmurze** [comment]
Yup, functionality was added to `v5.2`
