### ISSUE TITLE
Dynamic media conversations ?

### ISSUE THREAD

**Issue by elieandraos** [spatie/laravel-medialibrary#239]
This is not a bug, but just a question. 
Is there a way to have conversions and manipulations set dynamically (not hard coded in the model) ? 

For example, i have a site that generates micro blogs for users, but each user will have the ability to define his own blog header image size or even posts thumbnails. I will have one model 'blog' and one model 'post', but many conversions defined by the users eventually.

**Comment by freekmurze** [comment]
Take a look at the docs on [storing media specific manipulations](https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/storing-media-specific-manipulations).

**Comment by elieandraos** [comment]
@freekmurze awesome thanks :)
