### ISSUE TITLE
File name normalization

### ISSUE THREAD

**Issue by huglester** [spatie/laravel-medialibrary#240]
Hello,

where would it be best to put filename normalization?

For example"
"image (1).jpg"
I would like to run "str_slug($filename)", so I get better, error-less filenames?

Thank you

**Comment by freekmurze** [comment]
You can use `usingFileName` to set the filename to anything you want:

```php
$yourModel
   ->addMedia($pathToFile)
   ->usingFileName($normalizedFileName)
   ->toMediaLibrary();
```

**Comment by nelson6e65** [comment]
How can I change the name only, not the extension?

**Comment by LiamKarlMitchell** [comment]
If you have it as a a file already on disk, 
As seen in InteractsWithMedia addMediaFromUrl
```php
$mediaExtension = explode('/', mime_content_type($temporaryFile));
$filename = "{$filename}.{$mediaExtension[1]}";
```

But there is also the method sanitizingFileName which can take a callable so could do the slug or regex's etc in that.
But would have to extract the extension from the file name if so I suppose which is a tad naff.
