### ISSUE TITLE
Setting 'public' permission for files uploaded on S3

### ISSUE THREAD

**Issue by cobisja** [spatie/laravel-medialibrary#241]
Hi,

First of all let me tell you that your library is awesome. It save me a lot of time and avoid me to be writing boilerplate code. Nice!!

I would like to ask you, Is it possible to set the permission for an image (or whatever file) when it is uploaded to S3 via your library?. I mean, the picture I uploaded has a "private" permission by default, and I would like make it "public" readable. I was digging on the web and I found something like:

`php
$s3 = \Storage::disk('s3');
$filePath = '/support-tickets/' . $imageFileName;
$s3->put($filePath, file_get_contents($image), 'public'); // Setting to 'public' the attribute.
`
The code above was took from [https://chrisblackwell.me/upload-files-to-aws-s3-using-laravel/](url)

However I want to do the same thing but using your library.

Any clue?

Thanks in advance

**Comment by freekmurze** [comment]
Thanks for the kind words on the package. 

I don't know the exact setting by heart, but I'm pretty sure that in S3 you can specify somewhere (via a policy  I believe) that all uploaded files should be public.

**Comment by cobisja** [comment]
Oh I see, well I'm going to do more researching :p

Thanks so much!

2016-06-14 17:52 GMT-04:00 Freek Van der Herten <notifications@github.com>:

**Comment by palpalani** [comment]
Add the custom header `'ACL' => 'public-read',` to `config/laravel-medialibrary.php`.

Complete example:

```'extra_headers' => [
            'CacheControl' => 'max-age=604800',
            'ACL' => 'public-read',
        ]```

**Comment by divdax** [comment]
@freekmurze a policy in this case is a "global thing".

@palpalani This makes all files public after this config change.

I want to set "public" permission only on certain files. With Laravel's Storage Facade you can do this how @cobisja already mentioned.
```php
$s3->put($path, $content, 'public');
```
With a simple s3 policy you only can make all files public but not only some of them.

It would be great to set the permission for every single upload. 👍

**Comment by omacesc** [comment]
@divdax thanks for your answer, but do you know any way to apply public read to the conversions? thanks!

**Comment by divdax** [comment]
@omacesc no it's a bug i already reported: #868

**Comment by LiamKarlMitchell** [comment]
Does this have a fix yet?

**Comment by aurawindsurfing** [comment]
> @freekmurze a policy in this case is a "global thing".
> 
> @palpalani This makes all files public after this config change.
> 
> If you want to set the permission for every upload individually you can do this like so even your bucket is set to private:
> 
> ```
>     $model->addMedia($file)
>         ->addCustomHeaders([
>             'ACL' => 'public-read'
>         ])
>         ->toMediaCollection($type);
> ```

This also works for Digital Ocean Spaces

Thank you!

**Comment by reppair** [comment]
Is there a way to configure the `ACL` header only for the conversions? Say as part of the conversions definition? I'd like to keep the original file private.
