### ISSUE TITLE
Adding media to specific directory

### ISSUE THREAD

**Issue by palpalani** [spatie/laravel-medialibrary#242]
I am uploading files to S3. I want upload files to specific folder. 

Using `usingFileName`, i can able to change file name. but i am not able to upload specific folder. How to upload to specific folder.

**Comment by joaosalless** [comment]
@palpalani see this documentation:

https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/using-a-custom-directory-structure
and
https://github.com/spatie/laravel-medialibrary/blob/3.9.0/tests/PathGenerator/CustomPathGenerator.php

**Comment by freekmurze** [comment]
Thanks for giving the right answer @joaosalless

**Comment by palpalani** [comment]
Yes, It works.
Thanks for the information.
