### ISSUE TITLE
Possible performance boost when copying request media

### ISSUE THREAD

**Issue by Synchro** [spatie/laravel-medialibrary#2423]
I have been finding that processing a request is quite slow when using ML from MLP, so I did a little profiling.

The `copyFromMediaLibrary`method in `src/MediaCollections/Filesystem.php` does this:

```php
    public function copyFromMediaLibrary(Media $media, string $targetFile): string
    {
        touch($targetFile);

        $stream = $this->getStream($media);
        $targetFileStream = fopen($targetFile, 'a');

        while (! feof($stream)) {
            $chunk = fgets($stream, 1024);
            fwrite($targetFileStream, $chunk);
        }

        fclose($stream);

        fclose($targetFileStream);

        return $targetFile;
    }
```

This seems an inefficient way of writing a stream to disk, so I changed it to:

```php
    public function copyFromMediaLibrary(Media $media, string $targetFile): string
    {
        file_put_contents($targetFile, $this->getStream($media));
        return $targetFile;
    }
```

When handling a 7Mb JPEG image upload, this cut about 14% from the request processing time, and all seemed to work fine. In this particular request it exchanged 68,000 calls to `fwrite` for a single call to `file_put_contents`.

I thought I'd report this as an issue first as I don't know if there are other concerns I've not thought of. Manually copying the file in chunks is usually a sign of memory conservation, however, I believe that file_put_contents should do the same thing behind the scenes as it copies directly from the input stream to the written file. Other things that I thought might be significant is if file operations are being done on things that are not local files, like S3, however, it doesn't look like that applies here.

If you think this looks OK, I'll turn it into a PR.

### Before:

![image](https://user-images.githubusercontent.com/81561/117293707-06e35a80-ae72-11eb-8615-b51751106ac7.png)

### After:

![image](https://user-images.githubusercontent.com/81561/117293672-fa5f0200-ae71-11eb-9ed8-2da36f220292.png)

Note that the green/pink box to the right of the blue `stream_select` box has essentially disappeared.

**Comment by freekmurze** [comment]
If this works well for very big files without memory consumption exploding, I'd accept a PR 👍

**Comment by Synchro** [comment]
I wrapped these in log calls to get memory and time numbers. These are for handling the exact same 7Mb JPEG. I stopped and restarted `artisan serve` immediately before saving in each case.

### `fwrite` method:
```
[2021-05-06 12:41:15] local.DEBUG: memory before 14680064  
[2021-05-06 12:41:16] local.DEBUG: time 0.36153388023376  
[2021-05-06 12:41:16] local.DEBUG: memory after 14680064  
[2021-05-06 12:41:16] local.DEBUG: memory peak 25169920  
```
0.36 seconds, 25M peak RAM

### `file_put_contents` method:
```
[2021-05-06 12:38:00] local.DEBUG: memory before 4194304  
[2021-05-06 12:38:00] local.DEBUG: time 0.010936975479126  
[2021-05-06 12:38:00] local.DEBUG: memory after 4194304  
[2021-05-06 12:38:00] local.DEBUG: memory peak 14684160  
```
0.01 seconds, 14M peak RAM

Those stats look very encouraging, but it could use more testing. I'm having trouble testing with bigger files due to other issues (independent of what I'm changing), in particular I get this:

    Fatal error: Maximum execution time of 60+2 seconds exceeded (terminated) in 
    vendor/intervention/image/src/Intervention/Image/Imagick/Decoder.php on line 26

even when the server has only been running for about 10 seconds!

I'm also having trouble convincing MLP to accept files bigger than the 12M default, even though I've changed every setting to allow at least 64M and cleared config cache.

**Comment by freekmurze** [comment]
We'll continue this in #2425
