### ISSUE TITLE
Illuminate\Database\QueryException  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'media' already exists

### ISSUE THREAD

**Issue by nelson1995** [spatie/laravel-medialibrary#2426]
Hello guys.

I've encountered an error when running the command `php artisan migrate:rollback` to rollback the tables in my database . Apparently the command doesn't delete the table from database. I don't know if I'm doing it wrong or it's just an error. **![Screenshot_2021-05-06 Screenshot from 2021-05-06 18-12-57 png (PNG Image, 1366 × 768 pixels) – Scaled (82%)](https://user-images.githubusercontent.com/17122386/117324032-16759a00-ae98-11eb-977a-8107bd56ec5c.png)**

**Comment by freekmurze** [comment]
We don't provide a down migration. You should add that one yourself.

**Comment by nelson1995** [comment]
> We don't provide a down migration. You should add that one yourself.

Should i add it on the create media migration ?

**Comment by vedmant** [comment]
@freekmurze Why you don't provide down method, it's just a few lines, absences of this creates problems for lots of people, I personally had errors and had to create it manually when started few recent projects. What is the reasoning to not have down() method in migration?

**Comment by freekmurze** [comment]
In development we always start from a fresh db with `php artisan migrate:fresh --seed`.
In production we never migrate down, as in most cases that is a dangerous thing to do, because probably you haven't have written tests for that scenario.

**Comment by vedmant** [comment]
@freekmurze During the very beginning of a new project development it's often convenient to run `migrate:refresh`, this package breaks this functionality by default, also `artisan make:migration create_some_table` always automatically created down method. Sure down() method is not needed on later stages, but not having this causing errors on lots of people's projects.

**Comment by freekmurze** [comment]
Try running `migrate:fresh`. It's even more convenient as you don't need `down` migrations, and there are no downsides for most apps.

Feel free to add a `down` method yourself should you need it.

**Comment by vedmant** [comment]
@freekmurze Yes, I added `down` methods, but still this package causes two artisan commands to fail, it's not a good reason to make error two commands and make people google for the problem, basically stealing their working time.

**Comment by freekmurze** [comment]
> Yes, I added down methods, but still this package causes two artisan commands to fail

Feel free to send a PR to docs with instructions for people that want to have `down` methods.

> basically stealing their working time

That's a bit harsh, no?

**Comment by vedmant** [comment]
@freekmurze Why not just to add `down` method? There will be no need for documentation and people will not have to search for it when having this error.

**Comment by freekmurze** [comment]
For the reasons we stated above: we don't use it ourselves for our projects and any of our packages, and because people often don't have tests for running `down` migrations.

It makes sense for us to only support things we need ourselves and build package in a way that they are perfect for our projects.

**Comment by vedmant** [comment]
@freekmurze This makes sense if your package is private, but this is public package with a lot of downloads, you basically saying that you don't care about all other people that use this package.

**Comment by freekmurze** [comment]
I have often stated that we create these packages for our own projects, and that it wouldn't be sustainable for us if you build packages according to other peoples "rules". It seems that a lot of people do seem to like our work and find it useful for their projects.

If you don't like how we handle things, I've listed a few alternatives in the readme for you to try out.
