### ISSUE TITLE
UPGRADING sample migration produced invalid SQL

### ISSUE THREAD

**Issue by ethanclevenger91** [spatie/laravel-medialibrary#2428]
**MariaDB:** `mariadb  Ver 15.1 Distrib 10.5.8-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2` via Laravel Homestead

When running the migration documented in the UPGRADE guide: 

```SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>"$.generated_conversions", `media`.`updated_at` = ? where `generated_convers...' at line 1 (SQL: update `media` set `generated_conversions` = custom_properties->"$.generated_conversions", `media`.`updated_at` = 2021-05-06
22:35:58 where `generated_conversions` is null or `generated_conversions` =  or JSON_TYPE(generated_conversions) = 'NULL')```

That arrow syntax is unfamiliar to me. Not sure if it's valid in MySQL but not MariaDB or if something got merged in #2384 funny, but it isn't working with the above version of MariaDB.

**Comment by freekmurze** [comment]
This package requires MySQL

**Comment by ethanclevenger91** [comment]
For anyone here who isn't familiar with the syntax and wants to know exactly what the issue is -

The `->` operator in MySQL is the JSON_EXTRACT operator. Syntactic sugar currently not supported in MariaDB. See [this documentation](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_json-column-path) for understanding how it works in MySQL and [this feature request](https://jira.mariadb.org/browse/MDEV-13594) for its status in MariaDB.

Seems to me that dropping it for `JSON_EXTRACT` in full would be a trivial change to this package to support MariaDB, but MariaDB has dropped any notion of being a MySQL drop-in replacement, so incompatibilities are only likely to become more numerous.

**Comment by haleyngonadi** [comment]
@ethanclevenger91  Thanks for taking your time to explain. What solution did you use in the project?

**Comment by ethanclevenger91** [comment]
@haleyngonadi I'll probably be migrating to MySQL. I don't know if @freekmurze would entertain a PR to add MariaDB compatibility. I'm pretty sure it has the same features, just not the pretty syntax, so the functionality would likely be maintained.

**Comment by haleyngonadi** [comment]
> @haleyngonadi I'll probably be migrating to MySQL. I don't know if @freekmurze would entertain a PR to add MariaDB compatibility. I'm pretty sure it has the same features, just not the pretty syntax, so the functionality would likely be maintained.

Thanks for your reply. I migrated and now it works fine :)

**Comment by pepijn-vanvlaanderen** [comment]
A small rewrite will fix this for MariaDB:
`
                'generated_conversions' => DB::raw("JSON_EXTRACT(custom_properties, '$.generated_conversions')"),`

**Comment by ethanclevenger91** [comment]
@pepijn-vanvlaanderen That would get the migration functional, yep, but @mperezsc's comment implies this exists in the plugin code itself somewhere, too. I haven't had a chance to look for it.
