### ISSUE TITLE
Replicating a model

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-medialibrary#243]
Currently I am replicating a model, and I want to have to media copied aswell whenever a model is replicated.

    $newProduct = $product->replicate();

    $newProduct->push();

$product contains media, but the media is not copied whenever I replicated it. Is there a nice and short way to do this?

**Comment by sebastiandedeyne** [comment]
Don't think there's a short way to do it. I'd replicate the model without the media, then loop over all the media and use the new instance's `addMedia` method to make sure the files are added correctly.

Quick sketch, not sure if this will all work as-is:

```php
$newProduct = $product->replicate(['media']);

$newProduct->push();

$product->media->each(function (Media $media) {
    $newProduct->addMedia($media->getPath())
        ->preservingOriginal()
        ->withProperties($media->toArray())
        ->toCollection($media->collection_name);
});
```

**Comment by ceesvanegmond** [comment]
@sebastiandedeyne 👍

**Comment by jeremykenedy** [comment]
I have updated the code above to work with S3 and updated package methods:

```
$clonedItem = $item->replicate(['media']);

$clonedItem->push();

foreach ($event->media as $media) {
    assert($media instanceof Media);
    $props = $media->toArray();
    unset($props['id']);
    $clonedItem->addMediaFromUrl(Storage::disk('s3')->url($media->getPath()))
        ->preservingOriginal()
        ->withProperties($props)
        ->toMediaCollection($media->collection_name);
}
```

**Comment by kablin** [comment]
I try it, but got an error

Integrity constraint violation: 1062 Duplicate entry '.......' for key 'media_uuid_unique'

**Comment by markcameron** [comment]
A slightly modified and updated code, needed to unset some extra properties and I couldn't get the `addMediaFromUrl` working consistently, so using `addMediaFromDisk()` instead (left addMediaFromUrl commented should you need it).

Working with S3

```php
use Illuminate\Support\Facades\Storage;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
...

$clonedItem = $item->replicate(['media']);

$clonedItem->push();

foreach ($original->media as $media) {
    assert($media instanceof Media);
    $props = $media->toArray();
    unset($props['id']);
    unset($props['original_url']);
    unset($props['preview_url']);
    unset($props['uuid']);
    $replica->addMediaFromDisk($media->getPathRelativeToRoot(), $media->disk)
        // ->addMediaFromUrl(Storage::disk('media')->url($media->getPath())))
        ->preservingOriginal()
        ->withProperties($props)
        ->toMediaCollection($media->collection_name);
}
```
