### ISSUE TITLE
[Help] Can’t send a file response for the storage folder in Laravel 5.2 on Homestead

### ISSUE THREAD

**Issue by Banandrew** [spatie/laravel-medialibrary#244]
Hey,

I don’t think the question is specifically medialibrary-related, but decided to ask it here, because StackOverflow was littered with similar questions without an answer. What I wanted to do, is to protect my private files, so that only their owners could access them. I changed my public disk to storage folder:

``` PHP
'orders' => [
    'driver' => 'local',
    'root'   => storage_path('files/orders'),
],
```

And created a routed controller to be able to make files private (I intentionally excluded this logic from the example):

``` PHP
class FileController extends Controller
{
    public function getFile($slug)
    {
        $media = Media::where('slug', $slug)->first();

        return response()->file($media->getPath());
    }
}
```

The `getPath()` method returns the correct path to the file: `/home/vagrant/code/project/storage/files/orders/2/b414a7416571145ea9dcf9bda9a845a2.jpg`. I think it finds the file, because if it didn’t, I’d be getting a 404 error; it finds the file, sends a 200 status, but shows nothing in the browser—looks like so:

![capture](https://cloud.githubusercontent.com/assets/6409354/16260062/3b2bc7f2-386e-11e6-9ba7-038653397040.PNG)

Maybe I’m doing something completely wrong, or is it a Homestead/medialibrary use case issue? Would you approach implementing file permissions the same way with the package? Thanks!

**Comment by sebastiandedeyne** [comment]
If you're keeping your media files inside the storage directory, you won't be able to serve them as-is. There are two options:

a) Move the disk to `public_path`
b) Create a symlink in the `public` folder to `storage/files`

How exactly are you protecting your private files? Alternatively, you could create a regular route, e.g. `/files/{name}`, have your application catch it, and return the contents of the file if the currently logged in user has permission for it, that way you can keep all your authorization logic in your application.

**Comment by sebastiandedeyne** [comment]
Just realised that was what you're doing already, whoops!

Looks good to me at first sight, could it be a header issue?

**Comment by Banandrew** [comment]
I tried responding with a specific header, but it didn’t help:

```PHP
return response()->file($media->getPath(), [
    'Content-Type' => 'image/jpeg'
]);
```

>b) Create a symlink in the public folder to storage/files

But isn’t it the same as having everything in `public_path`? I mean, everybody can access a url and get to the file, it just points to another directory, correct? I already created one, it works perfectly, but doesn’t resolve the privacy issue, am I missing something?

**Comment by sebastiandedeyne** [comment]
Re: the symlink part, I misunderstood your issue first so you can ignore that.

I just created this route as a test and it works, so you're definitely on the right track.

```php
Route::get('/image', function () {
    return response()->file(\Spatie\MediaLibrary\Media::first()->getPath());
});
```

```html
<img src="/image">
```

Are you getting a response when you go straight to the url? And what do the response headers look like in Chrome's network inspector?

**Comment by Banandrew** [comment]
That’s relieving, thank you.

>Are you getting a response when you go straight to the url?

Yeah, the route is set up like so:

``` PHP
// When I open http://localhost:3000/files/2RmYR3
// I get this blank 200 response I mentioned in the first commentary.
Route::get('files/{slug}', [
    'as'   => 'get.file',
    'uses' => 'FileController@getFile',
]);
```

Here’re the response headers:

![capture](https://cloud.githubusercontent.com/assets/6409354/16281200/e28be718-38cb-11e6-8dee-838b84cf713c.PNG)

**Comment by sebastiandedeyne** [comment]
`content-length` seems to be missing, so I assume the server isn't sending the data through. `connection: close` seems odd, shouldn't that be `keep-alive` too? I don't really know enough about networking to provide any meaningful hints on the cause though.

**Comment by Banandrew** [comment]
Thanks for reaching out, Sebastian, I’ll keep digging.
