### ISSUE TITLE
Interface conflict between HasMedia and InteractsWithMedia-Trait

### ISSUE THREAD

**Issue by typoworx-de** [spatie/laravel-medialibrary#2474]
First of all great work this library!

I have some improvements for this library. In original state with fresh library there already is a syntax-conflict between HasMedia-Interface and InteractsWithMedia-Trait.

Interface hasMedia declaration:
```php
    /**
     * Get media collection by its collectionName.
     *
     * @param string         $collectionName
     * @param array|callable $filters
     *
     * @return \Illuminate\Support\Collection
     */
    public function getMedia(string $collectionName = 'default', $filters = []): Collection;
```

and for InteractsWithMedia-Trait:
```php
    /**
     * Get media collection by its collectionName.
     *
     * @param string $collectionName
     * @param array|callable $filters
     *
     * @return MediaCollections\Models\Collections\MediaCollection
     */
    public function getMedia(string $collectionName = 'default', $filters = []): MediaCollections\Models\Collections\MediaCollection
```

The first syntax bug is obviously, that the return-type of Interface and Trait is completly different! The Interface hasMedia should use the return-type of ```\Spatie\MediaLibrary\MediaCollections\MediaCollection```.

**Comment by typoworx-de** [comment]
Hmm, just noticed there seem to be multiple return-types?

\Spatie\MediaLibraryMediaCollections\Models\Collections\MediaCollection
\Spatie\MediaLibrary\MediaCollections\MediaCollection

May be there should be a generic interface which are representant for all of these return types so that all of the given return types implement such interface being able to use the new GenericMediaCollection-Interface as return-type in Methods. This way there would be no more interface complains and each of the interface still can have it's own Interface-Declaration.

**Comment by hyptrance** [comment]
how to solve this issue?

**Comment by mrethical** [comment]
Was able to solve this issue by implementing `\Spatie\MediaLibrary\HasMedia` on the model where the `InteractsWithMedia` is used. 
But tbh I find it redundant. Maybe we can do something to the return type of `getMedia`.

Just for some reference: https://github.com/spatie/laravel-medialibrary/pull/2335

**Comment by danielsum** [comment]
Got the same issue => quick workaround is simply to skip the implements HasMedia ?

**Comment by Ginger-liam** [comment]
I'm having this issue too, but it's not causing any problems. I just can't stand the red line under my code XD.
