### ISSUE TITLE
CleanCommand has an unexpected token ";"

### ISSUE THREAD

**Issue by huubk** [spatie/laravel-medialibrary#2489]
I just updated my project a minute after an updated version of CleanCommand was pushed 
and composer gave me an error:

syntax error, unexpected token ";"

at vendor/spatie/laravel-medialibrary/src/MediaCollections/Commands/CleanCommand.php:62

**Comment by freekmurze** [comment]
I've release a new version that fixes the problem.

My apologies for the inconvenience.

**Comment by huubk** [comment]
No worries:-) Thanks for all the great work!

**Comment by prullenbak** [comment]
I'm sorry too! Thanks @freekmurze !
