### ISSUE TITLE
file name extension

### ISSUE THREAD

**Issue by ziming** [spatie/laravel-medialibrary#25]
Hi,

First of all, thanks for creating this package.

I have been playing with it and 1 issue so far was that it seem the file extensions are removed (pdf, or png.etc). How do I retain the file extensions as well as some control over the file name?

Thank you.

**Comment by freekmurze** [comment]
Hi,

by default the name of a media object is indeed the name of the file without the extension. 

If you want to change the name you can to this:
```php
$media = $yourModel->addMedia($file);
$media->name = 'This is a new file name';
$media->save();
```

If you want to get the filename do this:
```php
$media->file_name;
```

Once added to the medialibrary the name of the file itself cannot be changed. So, if needed, you'll have to change the name of the file before adding it the medialibrary.

**Comment by ziming** [comment]
Hi,

Thanks for the response.

I pretty like the part about the package randomly generating a file name. However I just want to retain the file extension.

Also hmm...are there any tips for putting and using it in storage folder? The files are supposed to only be accessible by the users allowed to it, not everyone. Currently I store them in the public folder though.

**Comment by freekmurze** [comment]
The package will not generate a random name. Probably you are just using the temporary name of the upload. You can get the original name of the file with the `clientGetOriginalName`-function.
```php
$file = Input::file('file');
$fileName = $file->getClientOriginalName();
```

If you want to add some sort of security you should move the medialibrary out of the public folder. A great place to store the files would be the storage folder. Next, you should [write a custom url generator](https://github.com/spatie/laravel-medialibrary#generating-custom-urls). The generated url should point to a controller that determines if the user can access the file.

That's how I would go about it.

**Comment by ziming** [comment]
Ah I see, I will research on how to do that (custom url generator, and controller to link to storage folder). Yea I guess it was the temporary name of the upload, every file starts with the name php

**Comment by ziming** [comment]
Hi @freekmurze I tried to write my own UrlGenerator and I run into a particular issue.

My getUrl function is something like this

```
public function getUrl()
    {
        return action('MediaController@show', $this->id); // get the media and initiate downloads
    }
```

Well $this->id didn't work and I'm wondering if you know how could I get the id to pass on to the controller if you happen to do something similar before.

**Comment by freekmurze** [comment]
If your UrlGenerator extends the BaseUrlGenerator then you can access the id of the requested media with `$this->media->id`

**Comment by ziming** [comment]
Thank you.
