### ISSUE TITLE
Media::getPath uses UrlGeneratorFactory

### ISSUE THREAD

**Issue by kmbt** [spatie/laravel-medialibrary#250]
Hi again,

While trying to use a custom URL generator I have encountered a strange sort of behavior, namely the `Media::getPath` uses `UrlGeneratorFactory` instead of `PathGeneratorFactory`, thus getting an Url generator instead of path generator to call `getPath()` method on.

That seems to be no problem if you use a `LocalUrlGenerator`, as it implements the `getPath()` method. However in the [docs](https://docs.spatie.be/laravel-medialibrary/v3/advanced-usage/generating-custom-urls) it is only mentioned that you need to implement the `getUrl()` method in the url generator. This seems to make sense if you assume that you use `UrlGenerator` to generate URLs and `PathGenerator` to generate paths, however that seems not to be the case in the code. Please correct me if I'm thinking wrong.

I am using laravel-medialibrary v3 and the problem happened when I have done the following:

1. I have implemented a custom url generator which inherits after `BaseUrlGenerator` (as in the docs)
2. I have modified the `laravel-medialibrary.php` config file accordingly
3. I have not implemented a path generator, nor have I configured any other than default
4. I have retrieved a `Media` object from database and tried to use `->getPath()` method on it.

The interpreter complained of not having `getPath` method on my custom URL generator object.

My workaround was to inherit the UrlGenerator after LocalUrlGenerator (which, strangely, implements `getPath` method)  instead of the suggested `BaseUrlGenerator`.

Also, while inspecting the code I have found out that the `UrlGeneratorFactory` tries to set a `PathGenerator` for `Media` object by calling the `PathGeneratorFactory`. This is not taken into account in the `Media::getPath` method. Maybe that is a deliberate decision, however at first glance, to me it looks like a sort of a workaround from the past which might need cleanup one way or another.

**Comment by freekmurze** [comment]
Hi,

thanks for bringing this to my attention.

 I'll clean up the `UrlGenerators` and `PathGenerators` in the next major version of the package. Though the code around them is indeed a bit messy, it seems to work for most people.
