### ISSUE TITLE
Breaks when running php artisan migrate:refresh on fresh installation

### ISSUE THREAD

**Issue by vickymessii** [spatie/laravel-medialibrary#2500]
Running fresh `php artisan migrate` works fine.
but when you run `php artisan migrate:refresh`  breaks because media Migration don't have down function.

Adding this can fix.

```
 public function down()
    {
        Schema::dropIfExists('media');
    }
```

Steps to produce: 

create a new laravel project 
install medialibrary 

Run  `php artisan migrate`  

Then run 

`php artisan migrate:refresh`

**Comment by freekmurze** [comment]
We don’t add down migrations because in our projects, we never use them. Add a down migration manually in your project.
