### ISSUE TITLE
SOLID type not recognize when using border method on media conversion

### ISSUE THREAD

**Issue by antweny** [spatie/laravel-medialibrary#2501]
on adding media conversion the Border method recognize overlay, expand and shrink only when tried to pass solid as a third parameter throw an error below
![image-error](https://user-images.githubusercontent.com/28085591/124244216-5f0fa380-db27-11eb-942a-d29d8077e95a.JPG)

On **image\src\Manipulations.php** file only three constant declared and solid constant is missing as show below
![image-const](https://user-images.githubusercontent.com/28085591/124244801-0096f500-db28-11eb-95c7-fe3e47b9e0bb.JPG)

add another `const BORDER_SOLID= 'solid';` the error is gone

**Comment by freekmurze** [comment]
Feel free to submit a PR that fixes this on the spatie/image repo. Make sure to also add a test. Thanks!
