### ISSUE TITLE
Would it be possible for you to show a working example

### ISSUE THREAD

**Issue by phillipmadsen** [spatie/laravel-medialibrary#251]
In the model / controller / and view. Also does it create the relationships automatically when you use the model configuration or do we still need to implement them?

**Comment by nicolasbeauvais** [comment]
Have you looked at the online documentation https://docs.spatie.be/laravel-medialibrary/v4/introduction ? Lots of examples in it.

The relationship is automatically created when your use the `HasMediaTrait` in your model Class.

**Comment by freekmurze** [comment]
I'm planning on writing a tutorial on how to use the medialibrary on my blog https://murze.be soon.
