### ISSUE TITLE
GD Library extension not available with this PHP installation. ("v8.0.0")

### ISSUE THREAD

**Issue by rhoyle** [spatie/laravel-medialibrary#2515]
Intervention\Image\Exception\NotSupportedException
GD Library extension not available with this PHP installation.

I am using Laravel v8.49.2, with php v8.0.0 Zend Engine v4.0.0-dev

C:\xampp\htdocs\ironman\vendor\intervention\image\src\Intervention\Image\Gd\Driver.php:19

**Comment by Anticom** [comment]
What does `php -m` give you? You should have `gd` in the list of extensions. Otherwise your GD Extension just isn't set up correctly.
