### ISSUE TITLE
Generating responsive images causes an event loop.

### ISSUE THREAD

**Issue by glukash** [spatie/laravel-medialibrary#2516]
Hello
In a method:
Spatie\MediaLibrary\ResponsiveImages\ResponsiveImageGenerator::generateResponsiveImage(...)
there is a call to:
Spatie\MediaLibrary\ResponsiveImages\ResponsiveImage::register($media, $fileName, $conversionName);
In this method there is a $media->save(); call wich fires an event: Spatie\MediaLibrary\MediaCollections\Models\Observers\MediaObserver::updated(Media $media)
This event calls $fileManipulator->createDerivedFiles($media); and loop is started again.

Should it not be $media->saveQuietly(); in: Spatie\MediaLibrary\ResponsiveImages\ResponsiveImage::register(Media $media, $fileName, $conversionName) to save without firing an event?

**Comment by francoism90** [comment]
What kind of media files are causing this issue? Are they videos?

This can happen because of a job timeout, resulting in an endless loop.
As workaround I have created my own job for creating images for (large) video files.
