### ISSUE TITLE
Not returning full url when APP_URL uses https

### ISSUE THREAD

**Issue by tugamars** [spatie/laravel-medialibrary#2521]
Hello, i have the following code in a API endpoint:
```php 
           $dets=[
                'url'=>$civilian->picture->url,
                'thumbnail'=>$civilian->picture->thumbnail,
                'preview'=>$civilian->picture->preview,
            ];

return response($dets);
```
And the problem is that in one of the instances that is deployed it returns the expected result, with full url, but in another one it doesnt:

Machine 1:
```json
{
	"data": {
		"url": "http://example.com/storage/5/phpcFPhbX",
		"thumbnail": "http://example.com/storage/5/conversions/phpcFPhbX-thumb.jpg",
		"preview": "http://example.com/storage/5/conversions/phpcFPhbX-preview.jpg"
	}
}
```

Machine 2:

```json
{
	"data": {
		"url": "/storage/43/phpERamva",
		"thumbnail": "/storage/43/conversions/phpERamva-thumb.jpg",
		"preview": "/storage/43/conversions/phpERamva-preview.jpg"
	}
}
```

After passing a few hours trying to figure out the problem and comparing extensions and installations I found absolutely nothing and then i noticed that the only difference in the URLs on APP_URL was that the one that worked was "http://" and the other one "https://". By changing that (the protocol in APP_URL), the second machine started returning the expected output. 

Any idea what is the reason for this?

**Comment by erikn69** [comment]
maybe related #2524
