### ISSUE TITLE
GetUrl / GetFullUrl not correct on use of other disk

### ISSUE THREAD

**Issue by robov** [spatie/laravel-medialibrary#2524]
When I use the public filesystem

```
echo $item->getFirstMedia()->getUrl();
https://example.local/storage/11/7ad319a06c5e15832c051fccb014d62f.gif

echo $item->getFirstMedia()->getFullUrl();
https://example.local/storage/11/7ad319a06c5e15832c051fccb014d62f.gif
```

They both return the same

When I use another disk calles "items"
Defined as:
```
        'items' => [
            'driver' => 'local',
            'root' => storage_path('app/public/items'),
        ],
```
        
In the databasetable media on that record, the disk is correctly mentioned as 'items'        
        
The getters return something like this:        
```
echo $item->getFirstMedia()->getUrl();        
/storage/13/7ad319a06c5e15832c051fccb014d62f.gif

echo $item->getFirstMedia()->getFullUrl();
https://example.local/storage/13/7ad319a06c5e15832c051fccb014d62f.gif
```

However this is all wrong
the full url where the image is accessible now is (with the extra 'items' subdirectory) should be
https://example.local/storage/**items**/13/7ad319a06c5e15832c051fccb014d62f.gif

Any ideas ?

**Comment by mrofi** [comment]
Hi, @robov. Try this configuration :
```php
     'items' => [
            'driver' => 'local',
            'root' => storage_path('app/public/items'),
            'url' => env('APP_URL').'/storage/items',
            'visibility' => 'public',
     ],
```
