### ISSUE TITLE
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'media' already exists

### ISSUE THREAD

**Issue by bhavingajjar** [spatie/laravel-medialibrary#2534]
php artisan migrate:refresh
when I run after install media library getting "SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'media' already exists" this error

**Comment by bhavingajjar** [comment]
https://github.com/spatie/laravel-medialibrary/pull/2535 fixed by this solution

**Comment by erikn69** [comment]
You have to implement `down` method on your aplication, not on the package
