### ISSUE TITLE
MediaRepository::getCollection(): Argument #1 ($model) must be of type Spatie\MediaLibrary\HasMedia

### ISSUE THREAD

**Issue by stonkeep** [spatie/laravel-medialibrary#2540]
Help

I'm getting this error, when I'm loading the resource detail page (Laravel Nova)

`Spatie\MediaLibrary\MediaCollections\MediaRepository::getCollection(): Argument #1 ($model) must be of type Spatie\MediaLibrary\HasMedia, App\Models\CoordenadorPedagogico given, called in /var/www/html/vendor/spatie/laravel-medialibrary/src/InteractsWithMedia.php on line 290`

I'm using `use InteractsWithMedia;` trait

Help

**Comment by erikn69** [comment]
Not a bug, really easy, just use `hasMedia`

```php
class Model extends \Eloquent implements \Spatie\MediaLibrary\HasMedia
{
     use \Spatie\MediaLibrary\InteractsWithMedia;
```
