### ISSUE TITLE
Attempt to read property "currentTeam" on null

### ISSUE THREAD

**Issue by Hnooz** [spatie/laravel-medialibrary#2542]
**i'm trying to make watermark with team image but when i use queue i got this error** 

ErrorException: Attempt to read property "currentTeam" on null in 
/home/hnooz/Documents/projects/laravel/logis/app/MediaLibrary/TeamMediaPathGenerator.php:15

**this is my custom pathGenerator**

``` php
 protected function getBasePath(Media $media): string
    {
        $team_name = auth()->user()->currentTeam->name;

        return $team_name.'/'.$media->getKey();
    }
```

**this is conversions code**
``` php
public function registerMediaConversions(Media $media = null): void
 {
      $team_watermark = auth()->user()->currentTeam->path;
      if ($team_watermark) {
          $this->addMediaConversion('thumb')
              ->watermark(public_path('storage'.$team_watermark))
              ->watermarkOpacity(50)
              ->watermarkPosition(Manipulations::POSITION_CENTER)
              ->watermarkHeight(50, Manipulations::UNIT_PERCENT)
              ->watermarkWidth(50, Manipulations::UNIT_PERCENT)
              ->optimize();
      }
  }
```

**Comment by runthis** [comment]
@Hnooz Just a guess, hope it helps: If you have not solved this, that error means `auth()->user()` is null. Is the user authenticated? Probably wanna double check that, maybe ensure whatever route is being hit has an auth middleware.

**Comment by erikn69** [comment]
If you use queue `auth()->user()` does not exist because job has no login, you have to send `$team_name` to queue

**Comment by Hnooz** [comment]
thank you @erikn69 i solved the problem but i forget to close the issue

**Comment by Hnooz** [comment]
thank you @erikn69 i solved the problem but i forget to close the issue
