### ISSUE TITLE
Saving Media Fails Silently

### ISSUE THREAD

**Issue by delta1186** [spatie/laravel-medialibrary#2550]
I am stuck.  Maybe this is a bug, but I will admit I cannot get an exception thrown.   I am attempting to migrate legacy attachments from an old database/site to a new version which will use the media-library.  We have created custom database migrations and seeders.  In the seeders I am migrating all of the old files into the media library.  Here is where I am having an issue.  The old attachments table converted the files to a guid or appended a prefix to the file, but did store the original file name.  So I in my seeder I am using the following code.

```
$attachments = DB::connection('db_old')
                        ->table('attachments')
                        ->select('*')
                        ->get();

        foreach ($attachments as $attachment) {
            if ($attachable = $this->getAttachableObject($attachment->attachable_type, $attachment->attachable_id)) {
                $filename = Str::of($attachment->file_name)->replace(' ', '_')->__toString();
                $name = substr($filename, 0, strrpos($filename, "."));

                $attachable
                        ->addMediaFromDisk('attachments/' . $attachment->path, 'public')
                        ->usingName($name)
                        ->usingFileName($filename)
                        ->toMediaCollection($this->getCollection($attachment->attachable_type));
            }
        }
```
```
public function getAttachableObject($type, $id)
    {
        if ($type === 'App\Models\Ticket') {
            return Ticket::find($id);
        }

        if ($type === 'App\Models\TicketReply') {
            return TicketReply::find($id);
        }

        return null;
    }
```
So when I don't use usingFileName($name) my seeder works.  When I do use it, then when it gets to ` $model->media()->save($media);` below the code just stops and the seeder just quits executing in the terminal.  I cannot share the log output here because it contains user details.  But I can say that the loop above gets through about 30 attachments and fails on the same file every time.  But is here the weird part.  If I run the seeder again then it will pickup where it failed the failed file with work, but then error again.  The second time it gets about 36 files done.  3rd attempt 148 files and then stops.  Like I said if I restore all the original files then it will stop on that same file and if I don't use the useFileName method it will work without any issues.

```
protected function processMediaItem(HasMedia $model, Media $media, self $fileAdder)
    {
        $this->guardAgainstDisallowedFileAdditions($media, $model);

        $this->checkGenerateResponsiveImages($media);
info('media-try-save');
info($media->file_name);
        $model->media()->save($media);
info('media-saved');

        if ($fileAdder->file instanceof RemoteFile) {
```

Let me know what I need to do.  I could probably just work around this, but if this is a bug, then I would love to get it resolved.

**Comment by brendt** [comment]
Hi @delta1186 

This migration issue sounds like it's outside the scope of this package. It _might_ be possible that there's an underlying bug in the media library, but we won't be able to spend time on trying to reproduce it. 

If it turns out there's a bug and you're able to pinpoint it, feel free to submit a tested PR, which I'll be happy to review and merge.
