### ISSUE TITLE
InvalidArgumentException - League\Flysystem\Filesystem::writeStream expects argument #2 to be a valid resource

### ISSUE THREAD

**Issue by nirosha-jayasinghe** [spatie/laravel-medialibrary#2554]
I'm using my app in a `vapor` environment with S3 storage. When I try to upload a relatively large video file (more than 300MB), I'm getting this error.

`InvalidArgumentException - League\Flysystem\Filesystem::writeStream expects argument #2 to be a valid resource`

**Controller**

```
$media = $product->addMediaFromDisk($mediaKey, 's3')
                ->withCustomProperties(['uploaded_by' => tenant_user()->getKey()])
                ->usingName($name)
                ->usingFileName($fileName)
                ->toMediaCollection('product-media');
```

according to the trace, it comes from `vendor/spatie/laravel-medialibrary/src/MediaCollections/Filesystem.php` line 73

```
$this->streamFileToDisk(
            $storage->getDriver()->readStream($file->getKey()),
            $destination,
            $media->disk,
            $headers
        );

```
In here, ` $storage->getDriver()->readStream($file->getKey())` returning `false`. Files below 300MB get uploaded without a problem.

**Stack trace**
                     
<img width="1028" alt="Screenshot 2021-08-17 at 7 24 43 PM - edited" src="https://user-images.githubusercontent.com/57827730/129934344-f165f30f-91c4-400e-b9e5-0ce3f8df5130.png">

**Exception**

<img width="1117" alt="Screenshot 2021-08-17 at 7 24 19 PM" src="https://user-images.githubusercontent.com/57827730/129936241-a40a4c59-5bfd-4098-b193-6b7f7117fa3f.png">

**Comment by devsquad-luan-freitas** [comment]
Hi, I'm having the same problem
