### ISSUE TITLE
Exception when model is using `getMorphClass()`

### ISSUE THREAD

**Issue by erikn69** [spatie/laravel-medialibrary#2565]
if model are using `getMorphClass()` throws exception

Example:
```php
public function getMorphClass() {
   return 'Users';
}
```
Throws:
```php
Class "Users" not found
/var/www/vendor/spatie/laravel-medialibrary/src/Conversions/ConversionCollection.php#50

$modelName = Arr::get(Relation::morphMap(), $media->model_type, $media->model_type);
/** @var \Spatie\MediaLibrary\HasMedia $model */
$model = new $modelName();
```
`getMorphClass` used for `spatie/laravel-permission`
https://spatie.be/docs/laravel-permission/v4/advanced-usage/extending#extending-user-models

How to set the class on `Relation::morphMap()`? or how to set default prefix for models?
Are you reception PR for this?

**Comment by MirasMustimov** [comment]
@erikn69 hello, have you found a solution to this error? I am seeing the same error.

**Comment by erikn69** [comment]
I forgot to declare `Relation::morphMap()` on the service provider, after add it all works for me
