### ISSUE TITLE
Method to list missing images.

### ISSUE THREAD

**Issue by Garbee** [spatie/laravel-medialibrary#257]
There should be a method to look over all of the registered media files and check for their existence. Further a command should be provided to output the list for easy verification.

For example:
```sh
php artisan medialibrary:checkExistance

# If all exist
All media files exist in storage.

# If some are missing
ID: 66 missing
ID: 67 missing
ID: 89 missing
Some media files weren't found in storage. Please verify that the listed media files exist.
```

There would be an internal class/method that could be called for doing the check. That would return a collection of the media objects which a developer could then do whatever they want with. In the case of the command, it just pulls the ID out. However, one could program an administration view using those objects and filtering them to help upkeep files that may get missing.

The command would have signature like so:

`medialibrary:checkExistence {--only= : A comma separated list of models to check for.} {--except= : A comma separated list of models to exclude from the check.}`

This will allow developers to specify targets against associated models to check for. Making it easy for them if they are either only looking for one area that may have been corrupted or trying to exclude an area they know may have fluctuation.

Sound acceptable?

**Comment by freekmurze** [comment]
Discussion continues in #259
