### ISSUE TITLE
Media Library creates warning during ide helper's model generation

### ISSUE THREAD

**Issue by mirzazeyrek** [spatie/laravel-medialibrary#2571]
Steps to reproduce :

`composer require --dev barryvdh/laravel-ide-helper`
`php artisan ide-helper:models -N`

Output:

`Error resolving relation model of App\Models\Media:temporaryUpload() : You need to have media library pro installed to make this work.`

Is there a way to prevent this warning while creating ide helpers other than manually modifying vendor files ?

**Comment by joaopalopes24** [comment]
@mirzazeyrek Did you manage to solve it?

**Comment by damms005** [comment]
I simply did this:

```
    public function temporaryUpload(): BelongsTo
    {
        return $this->belongsTo(Media::class);
    }
```
