### ISSUE TITLE
Regeneration command doesn't work with s3

### ISSUE THREAD

**Issue by stijntilleman** [spatie/laravel-medialibrary#260]
The regeneration command doesn't accept multiple ids when passing them to the command

php artisan medialibrary:regenerate --ids=39 <- updates id 39

php artisan medialibrary:regenerate --ids=39,40 <- still only updated 39

**Comment by nicolasbeauvais** [comment]
I had the same issue, after some investigation I found that the symfony console component doesn't parse the argument, it just put it in an array

https://github.com/symfony/console/blob/master/Input/ArgvInput.php#L248-L251

so your agruments "39,40" will be casted to
```
array:1 [
  0 => "39,40"
]
```

I don't know if there is a syntax to force the array creation from the command line, I tried:
`39,40`
`"39,40"`
`[39,40]`
`"[39,40]"`
All return the same result.

In the other hand:
`Artisan::call('medialibrary:regenerate', ['--ids' => [39, 40]])` works perfectly.


A simple solution will be to modify the RegenerateCommand:
`{--ids=*}` to `{--ids=}` to avoid the useless casting

and explode the argument on line 78:
```php
if ($mediaIds) {
    $mediaIds = explode(',', $mediaIds);
    return $this->mediaRepository->getByIds($mediaIds);
}
```

But this should work without any workaround :/

**Comment by freekmurze** [comment]
Thanks for investigating this @nicolasbeauvais 

Fixed (with the proposed workaround) in version `4.4.1`.
