### ISSUE TITLE
Need some help please

### ISSUE THREAD

**Issue by phillipmadsen** [spatie/laravel-medialibrary#261]
I  am trying to get my product model to save the product images in a table but not sure how to associate it with the model instance for retrieval. 

My code:
```
 public function store(CreateProductRequest $request)
    {
        $input = $request->all();
        $product = $this->productRepository->create($input);

        $product =  \App\Models\Product::find(1);
        $pathToFile = '/products/';
        $product->addMediaFromRequest('image')->toMediaLibrary()->toCollection('product_images');
}
```

my table
```
Schema::create('product_images', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('product_id')->unsigned();
            $table->string('path');
            $table->timestamps();
        });
```

**Comment by freekmurze** [comment]
Hi, you don't need to create a separate table for storing the relations between products and images. This is done by the package in the `media` table.

You'll find a good examples on how to [associate](https://docs.spatie.be/laravel-medialibrary/v4/basic-usage/associating-files) and [retrieve](https://docs.spatie.be/laravel-medialibrary/v4/basic-usage/retrieving-media) media in the [docs](https://docs.spatie.be/laravel-medialibrary/v4).
