### ISSUE TITLE
sorry for botherhing.

### ISSUE THREAD

**Issue by FaksZutzu** [spatie/laravel-medialibrary#2612]
Hi installed update version 9.8.1 and my media died relationships are not found despite anything, reverting back to 9.8.0 reverts the issue.
Thanks, Best Regards,
Oskars.

**Comment by freekmurze** [comment]
Our tests indicate that everything is working correctly. I'm going to assume that the error is caused by something specific to your project.

Should you find that our package is in error, feel free to open a new issue with as much info on how we can reproduce the error in a vanilla Laravel app
