### ISSUE TITLE
Cannot install Spatie medialibrary using terminal

### ISSUE THREAD

**Issue by TineshSuresh** [spatie/laravel-medialibrary#2616]
PHP Version: 8.0.11
Composer Version: 2.1.9

Hi, the problem when i try to install this package using terminal it shows this error:

*********************************************************************************
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/laravel-medialibrary[9.8.0, ..., 9.8.1] require spatie/image ^1.4 -> satisfiable by spatie/image[1.4.0, ..., v1.x-dev].
    - spatie/image[1.8.0, ..., v1.x-dev] require spatie/image-optimizer ^1.1 -> satisfiable by spatie/image-optimizer[1.1.0, ..., 1.4.0].
    - spatie/image[1.7.7, ..., 1.8.1] require spatie/image-optimizer ^1.0 -> satisfiable by spatie/image-optimizer[1.0.0, ..., 1.4.0].
    - spatie/image-optimizer[1.0.0, ..., 1.1.4] require php ^7.0 -> your php version (8.0.11) does not satisfy that requirement.
    - spatie/image[1.4.0, ..., 1.7.6] require php ^7.0 -> your php version (8.0.11) does not satisfy that requirement.
    - spatie/image-optimizer[1.1.5, ..., 1.2.1] require php ^7.2 -> your php version (8.0.11) does not satisfy that requirement.
    - spatie/image-optimizer[1.3.0, ..., 1.4.0] require psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires spatie/laravel-medialibrary ^9.8 -> satisfiable by spatie/laravel-medialibrary[9.8.0, 9.8.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

*************************************************************************************

But if i manually put the the package name manually in composer.json like this and run composer update ;
"spatie/laravel-medialibrary": "^9.8.1"

It install fine but downgrade the psr/log version in laravel...

Thank You...

**Comment by miladkian** [comment]
Same Issue with Laravel sail clean installation.

**Comment by PaolaRuby** [comment]
Seriusly, just follow the suggestion and add	-W

**Comment by TineshSuresh** [comment]
> First, composer give you suggestions
> 
> > Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> 
> Second, the downgrade of `psr/log` is `guzzlehttp/guzzle` problem, not from this package
> 
> https://github.com/spatie/laravel-medialibrary/blob/13514710bda92cdb0c3ead3728965d6773c9722b/composer.json#L45
> 
> 
> https://github.com/guzzle/guzzle/blob/7ec2e2a6653521433fd759f6f800ab1bb463ab6c/composer.json#L69

Thank you for the clarification. I will close this issue. Thank you

**Comment by lukebouch** [comment]
I'm having the same issue.
