### ISSUE TITLE
Custom model saves media twice

### ISSUE THREAD

**Issue by jamesinglis** [spatie/laravel-medialibrary#262]
I have implemented a custom model for the Media object so that I can add additional fields that will be searchable (unlike custom properties). Media is hosted on S3 so a bit of latency is to be expected when saving media, however I have found when adding media and setting a custom field, running the Eloquent::save() method to commit the table changes also triggers the media processing for a second time.

The code for this section of the image handling is:

`$media = $model->addMedia($incoming_values['image'])->preservingOriginal()->toCollectionOnDisk($incoming_values['media_type']); // takes 3-5 seconds to upload and generate thumbnails`
`$media->caption = $incoming_values['caption'];`
`$media->save(); // takes 3-5 seconds to upload and generate thumbnails a second time`

I've been able to code around this, but it's a bit of a nuclear option to completely remove and then re-add the event dispatcher:

`$eventDispatcher = Media::getEventDispatcher();`
`Media::unsetEventDispatcher();`
`$media->save();`
`Media::setEventDispatcher($eventDispatcher);`

Is there a cleaner way you're aware of to achieve the same result as above?

**Comment by freekmurze** [comment]
Mmm, strange, are you by any chance using [a custom property called `manipulations`](https://github.com/spatie/laravel-medialibrary/blob/master/src/MediaObserver.php#L25-L27)?
