### ISSUE TITLE
share media

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [spatie/laravel-medialibrary#2629]
### Discussed in https://github.com/spatie/laravel-medialibrary/discussions/2628

<div type='discussions-op-text'>

<sup>Originally posted by **abhishek-pokhriyal** October 16, 2021</sup>
i have a warehouse project in where item is created with a number of imates. So if i say

item - 'chairs`
quantity - 5
image files - 2

this will create 5 new rows in the items table. each item will share the 2 image files. if i do not share then 2 images will be stored for each of the 5 items = 10 images!

is there a way to share single media with different model instances?</div>

**Comment by razisayyed** [comment]
You can create an intermediate table that has a one to many relationship with Chair Model.

```
<?php

namespace App\Models;

use App\Models\Chair;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class ChairSharedMedia extends Model implements HasMedia
{
    use InteractsWithMedia;

    public function chairs()
    {
        return $this->hasMany(Chair::class);
    }
}
```

```
<?php

namespace App\Models;

use App\Models\ChairSharedMedia;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Chair extends Model implements HasMedia
{

    use InteractsWithMedia;

    public function sharedMedia()
    {
        return $this->belongsTo(ChairSharedMedia::class);
    }
}
```

now you can use `$chair->sharedMedia->media()` for the shared media items and `$chair->media()` for unique items.
