### ISSUE TITLE
[BUG] Generating Original Name of the File

### ISSUE THREAD

**Issue by tzsk** [spatie/laravel-medialibrary#2630]
### System Info:
- PHP Version: 7.4
- Laravel Media Library Version: ^9.4

### Bug:
There seems to be a problem with the `FileNamer::originalFileName()` method. It looks like it is a RegEx problem. The issue is for certain file name strings throws errors. We can reproduce the issue with any filename containing square brackets provided the content inside the square brackets should contain a space.

### Reproduce in Tinker:
Try running the following  code in `tinker` (`php artisan tinker`)
```php
$sanitizedFileName = app('\Spatie\MediaLibrary\MediaCollections\FileAdder')->defaultSanitizer('Myrtle and Moss - INSPIRE [Base Preset].xmp');

#=> "Myrtle-and-Moss---INSPIRE-[Base-Preset].xmp"

app(config('media-library.file_namer'))->originalFileName($sanitizedFileName);

#=> <warning>PHP Warning:  preg_replace(): Compilation failed: range out of order in character class at offset 32 in /vendor/spatie/laravel-medialibrary/src/Support/FileNamer/FileNamer.php on line 14</warning>
#=> TypeError: Return value of Spatie\MediaLibrary\Support\FileNamer\FileNamer::originalFileName() must be of the type string, null returned
```

**Comment by PaolaRuby** [comment]
Regex removed #2587, update your composer
