### ISSUE TITLE
Files that aren't images

### ISSUE THREAD

**Issue by Benpxpx** [spatie/laravel-medialibrary#264]
Are we able to use this library to manage file types other then images?
We're looking to make a system with word documents, and I was hoping to use this library to achieve this.

Or is there a way i can define the word doc type so that it will be able to handle word docs?

**Comment by freekmurze** [comment]
The package can handle any type of file. So you should be able to add `doc`-files to the medialibrary.

**Comment by Benpxpx** [comment]
Thought that might be the case, I've managed to get word docs working.
Many thanks
