### ISSUE TITLE
Can I change the default db connection in config?

### ISSUE THREAD

**Issue by iCodem** [spatie/laravel-medialibrary#266]
Hello, I have three databases in my laravel project and I want medialibrary to use a connection other that the default one. how can I set medialibrary to do so?

**Comment by freekmurze** [comment]
You can [use your own model](https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/using-your-own-model) and [specify a connection on that model](https://laravel.com/docs/5.2/eloquent) (look for "database connection" on that page).

**Comment by iCodem** [comment]
Thanks for your quick response. Appreciate it.
