### ISSUE TITLE
Help me to get started

### ISSUE THREAD

**Issue by chirag6451** [spatie/laravel-medialibrary#267]
HI 

New to Laravel and this library. I have created required changes in model and images are getting copied to folders, all ok. However I am not able to generate thumbnails, i have followed a documentations and have implemented registerMediaConversions() and made it nonQueued. However I am not sure if I need to call any method to generate images? When I call

 $thumbURL=$mediaItems[0]->getUrl('thumb');
        echo $thumbURL; 

it gives me path like /media/7/conversions/thumb.jpg 

But I dont see any such file or folder 'conversions' . Can you please help by providing simple steps?

**Comment by freekmurze** [comment]
If you [define a conversion on a model](https://docs.spatie.be/laravel-medialibrary/v4/converting-images/defining-conversions) and [add a file](https://docs.spatie.be/laravel-medialibrary/v4/basic-usage/associating-files) you should be generate a derived file and [retrieve a path to the generated file](https://docs.spatie.be/laravel-medialibrary/v4/converting-images/retrieving-converted-images). 

I'm planning on writing an extensive blogpost that introduces the package. Might be a while until it gets published.

**Comment by chirag6451** [comment]
Thanks, as I wrote I can retrieve the path but actual/physical folders/files are not there on given path. please help. It would be very useful to have full blog.

**Comment by chirag6451** [comment]
OK I just found something, I dont know why but if we use as per your documentations 

```
 $User->addMediaFromUrl($url)
          ->toMediaLibrary();
```
it does not create conversions folder and thumbs but if we use like

$User->addMediaFromUrl($url)
          ->toMediaLibrary('');
```

It does create. I dont know why

**Comment by bjornbjorn** [comment]
Hi, I agree that this is a bit confusing ... I think the reason for the behaviour is because ->toMediaLibrary() takes a collection name as first parameter, and when you run it without a parameter the collection name used is 'default'.

Most likely you have defined your thumbs conversion to run on the 'images' collection only, like this:

```    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
            ->setManipulations(['w' => 512, 'h' => 288])
            ->performOnCollections('images');
    }```

So it won't run on your 'default' collection. Not sure why it does run when you specify an empty string as the collection like you did though.
