### ISSUE TITLE
Implicit conversion from float [float_value] to int loses precision

### ISSUE THREAD

**Issue by ajzamora** [spatie/laravel-medialibrary#2678]
Triggers when using withResponsiveImages()
Steps to reproduce:
- call $modelName->addMediaFromRequest('image')->withResponsiveImages()->toMediaCollection();
- upload an image

Using:
- media-library 9
- php 8.0.13
- laravel 8

Error points to line 46 of FileSizeOptimizedWidthCalculator.php
//protected function finishedCalculating(int $predictedFileSize, int $newWidth): bool

first time using this, still checking if it is only on my end.

**Comment by freekmurze** [comment]
Our tests indicate that this is working properly. Feel free to PR a failing test and/or fix for this.

**Comment by mojowill** [comment]
I'm seeing the same issue on conversions with `withResponsiveImages()`

- PHP 8.1.3
- Laravel 9.2.0
- Media Library 10.1.1
