### ISSUE TITLE
Your Recommended Practice to Organize FolderStructure Based on Entity Types

### ISSUE THREAD

**Issue by iCodem** [spatie/laravel-medialibrary#268]
Dear @freekmurze I want to have a folder for each entity type in storage structure. my root folder is 'media'. I want for example 'category', 'product', 'brand' folders under it and store each entity media in its corresponding folder. I'd appreciate your suggestion on how to implement this

**Comment by freekmurze** [comment]
Take a look at "[Using a custom directory structure](https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/using-a-custom-directory-structure)" in the docs. 

Only do this if you have a good reason to do so. The default directory structure should work ok for most projects.

**Comment by iCodem** [comment]
I've been studying this topic in documentation before hand. but I how do I tell media-library to use new path generators based on entity types?

**Comment by freekmurze** [comment]
The `getPath` function of your own `PathGenerator` should determine the type of the media and return in which directory the medialibrary should store that file.

Is this the info you're looking for?
