### ISSUE TITLE
Finfo extension Problem on shared hosting

### ISSUE THREAD

**Issue by iCodem** [spatie/laravel-medialibrary#269]
Is there any workaround to bypass need of finfo PHP extension? My shared hosting doesnt allow installing any extensions and doesnt have this extension.

**Comment by freekmurze** [comment]
Composer has an `--ignore-platform-reqs` option to skip those requirements.

https://getcomposer.org/doc/03-cli.md

**Comment by iCodem** [comment]
Thanks for answer but I didn't mean that. In Helpers namespace there's a File.php which utilizes Finfo class (line 55)

**Comment by freekmurze** [comment]
It seems that we use that class to determine the mime type of a file. Most hosts do provide that extension, so I'm probably not going to remove / replace that.

You're free to fork this package to add your own mimetype detection. (or you could move to hosting that does provide that extension).

**Comment by iCodem** [comment]
Yes thanks anyways man

**Comment by iCodem** [comment]
you have done much for the community. cheers
