### ISSUE TITLE
Slow downs with large media tables

### ISSUE THREAD

**Issue by petsoukos** [spatie/laravel-medialibrary#2705]
I'm facing issues with add media to my models when there's a huge media table.

My table is over 14m entries large with media. It appears that just adding a media to this table is very very slow, over 10s in my case.

Steps to reproduce. Have a huge media table >10m entries
```
$yourModel->addMedia($pathToFile)->toMediaCollection();
```

Can be solved by adding an index to the order_column of the media table.

**Comment by PaolaRuby** [comment]
Make a PR if you know how to fix it 👍

**Comment by freekmurze** [comment]
14 million, that's a lot 😅 

Feel free to PR a note in the docs about this 👍
