### ISSUE TITLE
Deleting custom property

### ISSUE THREAD

**Issue by iCodem** [spatie/laravel-medialibrary#271]
How can I delete a custom property from a mediaItem?

**Comment by freekmurze** [comment]
There currently isn't. You could set the property to `null`.

I'd accept a PR that adds a `removeCustomProperty` method to the `Media` class.

**Comment by iCodem** [comment]
Thanks guys. so I'd suggest adding this feature as well: ability to change/update CustomProperty after adding new media.

**Comment by freekmurze** [comment]
Added `removeCustomProperty` in version `4.6.0`

You can update a custom property by just setting it again.
