### ISSUE TITLE
Links to Vue Examples are broken

### ISSUE THREAD

**Issue by kimulisiraj** [spatie/laravel-medialibrary#2716]
[In docs](https://github.com/spatie/laravel-medialibrary/blob/main/docs/handling-uploads-with-media-library-pro/creating-custom-vue-components.md) all links to the vue2 and vue3 are broken 👇
-   [Vue 3 collection component](https://github.com/spatie/laravel-medialibrary-pro/tree/master/resources/js/media-library-pro-vue3-collection)

**Comment by freekmurze** [comment]
You need a media library pro license too view that repo.
