### ISSUE TITLE
How to add a media from a blob url?

### ISSUE THREAD

**Issue by Sjos12** [spatie/laravel-medialibrary#2721]
### Discussed in https://github.com/spatie/laravel-medialibrary/discussions/2720

<div type='discussions-op-text'>

<sup>Originally posted by **Sjos12** January 10, 2022</sup>
Hi, 

I'm trying to upload an image from my react spa to my laravel api. 
I've got the image blob url from `URL.createObjectUrl(file)`. 
When I send it to the backend and provide the blob url in the `addMedia()` method it gives me the following error. 

`File blob:http://localhost:3000/4c902f7a-de2f-4d44-9bfc-de0d16cce71f does not exist`

When I paste the url in the browser the image does exists. My question is: Are there any methods for adding blobs and if not, is there an alternative for uploading my image?

</div>

**Comment by PaolaRuby** [comment]
Not a bug

**Comment by Sjos12** [comment]
If blob:http://localhost:3000/4c902f7a-de2f-4d44-9bfc-de0d16cce71f is a path of an image. Doesn't it mean the documentation is not complete (since it doesn't specify what kind of path) or the package is missing functionality since it cannot add from blob urls?

**Comment by Sjos12** [comment]
Upon further reading this blob url is only accessible within the same browser instance. So as @PaolaRuby said this should not be the expected to work.

**Comment by szwss** [comment]
I also ran into this problem, how did I solve it, 
``` 
blob:http://localhost:3000/4c902f7a-de2f-4d44-9bfc-de0d16cce71f 
``` 
The client returned this URL, which is accessible in the browser
