### ISSUE TITLE
 Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames

### ISSUE THREAD

**Issue by Tofandel** [spatie/laravel-medialibrary#2729]
The method 
```
json_encode($this->getFirstMedia('logo'));
```

Triggers an infinite loop since I updated the lib from 9.9 to 9.11

It seems to loop when trying to json_encode the result, but downgrading back to 9.9 didn't fix the issue so I'm investigating

For some reason it's not happening on a local environnement but is happening on a staging one

Edit: It's very likely that XDEBUG has smoked and is showing a wrong line as the loop culprit as it seems to be coming from laratrust instead

**Comment by kskrlinnorth2** [comment]
I am getting same error when trying to get media via accessor.

```
public function getAvatarUrlAttribute()
{
    $media = $this->getFirstMedia('avatar');
    return $media ? $media->getUrl() : null;
}
```
