### ISSUE TITLE
FatalErrorException in Media.php line 51

### ISSUE THREAD

**Issue by giorgoskorakas** [spatie/laravel-medialibrary#275]
Hi, 

after installing the package i get this error. The error is followed by the message: 
"Default value for parameters with a class type hint can only be NULL"

From the point i set the provider:
Spatie\MediaLibrary\MediaLibraryServiceProvider::class,
in app.php i get the error.

I need some help here.

Wait for you reply

Thank you,

George K.

**Comment by freekmurze** [comment]
I cannot reproduce this. Could you try using the latest version of the package in a fresh copy of Laravel?

**Comment by nicolasbeauvais** [comment]
Looks like #248

**Comment by giorgoskorakas** [comment]
Thank you all for your help. The issue i had is resolved.
