### ISSUE TITLE
Conflict with `nunomaduro/larastan`

### ISSUE THREAD

**Issue by ewilan-riviere** [spatie/laravel-medialibrary#2765]
- laravel-medialibrary: `10.0.0`
- nunomaduro/larastan: `2.0.0`
- Laravel: `9.0`
- OS: Windows 10

### Description

When I install `spatie/laravel-medialibrary` with [`nunomaduro/larastan`](https://github.com/nunomaduro/larastan), I've an error when I execute larastan. This error can be checked on [this repository](https://gitlab.com/ewilan-riviere/laravel-larastan).

```bash
composer require "spatie/laravel-medialibrary:^10.0.0"
```

### Laravel code where the issue was found

```bash
./vendor/bin/phpstan analyse
```

```bash
Note: Using configuration file C:\workspace\projets\laravel-app\phpstan.neon.
This file is included multiple times:
- C:\workspace\projets\laravel-app\vendor\nunomaduro\larastan\extension.neon

It can lead to unexpected results. If you're using phpstan/extension-installer, make sure you have removed corresponding neon files from your project config file.
```

Larastan works when I remove *laravel-media-library*.

## Fix option

I've an answer from [canvural on larastan repo](https://github.com/nunomaduro/larastan/issues/1116#issuecomment-1033526263).

>They require `phpstan/extension-installer` in their [composer.json](https://github.com/spatie/laravel-medialibrary/blob/main/composer.json#L38) Which is a tool that automatically registers PHPStan extensions.
>
>So please open an issue there. They should remove that from their composer.json Or move it to `require-dev`

**Comment by freekmurze** [comment]
A fix has been released. Thanks for reporting.
