### ISSUE TITLE
PHP Fatal error:  Declaration of Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection::jsonSerialize() must be compatible with Illuminate\Supp ort\Collection::jsonSerialize(): arr

### ISSUE THREAD

**Issue by DanielvdSpoel** [spatie/laravel-medialibrary#2767]
When i install Laravel-medialibary (v10) in a laravel 9 project I get the following error: 
`[Wed Feb  9 17:11:47 2022] PHP Fatal error:  Declaration of Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection::jsonSerialize() must be compatible with Illuminate\Supp
ort\Collection::jsonSerialize(): array in C:\Users\USER\Documents\x\x\x\vendor\spatie\laravel-medialibrary\src\MediaCollections\Models\Collections\MediaCollection.php on line 51
`

**Comment by freekmurze** [comment]
Can you share a vanilla Laravel app where you see this problem?

**Comment by DanielvdSpoel** [comment]
I'm not able to reproduce it on a vanilla Laravel app. The only thing I did was install it and add the trait/interface. Currently unable to debug more becouse PHPstorm is refusing to load the project. Will look if i can reproduce it

**Comment by DanielvdSpoel** [comment]
I'm able to reproduce it on a new Laravel (9) installation using Jetstream. Repository for the app is https://github.com/DanielvdSpoel/spatie-media-test

**Comment by DanielvdSpoel** [comment]
I also found the solution, the `jsonSerialize` in the `Spatie\MediaLibrary\MediaCollections\Models\Collections` needs to add a return type of `array`

**Comment by DanielvdSpoel** [comment]
Interesting, was working on a pull request but saw that it was already fixed 7 days ago, the install command on the docs still installs the version with this bug included, meaby something to look at?

**Comment by smartified** [comment]
Just upgrade to version 10.2.* and you will be fine

**Comment by marcelo-kazalukian** [comment]
> 10.2

Hi How can I update it to version 10.2.*?

I run composer update but spatie library still on version 10.0.0

thanks so much

**Comment by marcelo-kazalukian** [comment]
> Just upgrade to version 10.2.* and you will be fine

Hi, How can I update it to version 10.2.*?

I run composer update but Spatie library still on version 10.0.0

thanks so much

**Comment by smartified** [comment]
> > 10.2
> 
> Hi How can I update it to version 10.2.*?
> 
> I run composer update but spatie library still on version 10.0.0
> 
> thanks so much

Just go into your composer.json and change it from 10.0.0 to 10.2.* and run composer update
![image](https://user-images.githubusercontent.com/16135819/184102586-af51b7a4-9091-45d4-b417-dddc6a46de58.png)

**Comment by marcelo-kazalukian** [comment]
> > > 10.2
> > 
> > 
> > Hi How can I update it to version 10.2.*?
> > I run composer update but spatie library still on version 10.0.0
> > thanks so much
> 
> Just go into your composer.json and change it from 10.0.0 to 10.2.* and run composer update ![image](https://user-images.githubusercontent.com/16135819/184102586-af51b7a4-9091-45d4-b417-dddc6a46de58.png)

It worked. Thanks so much.

**Comment by s00ar** [comment]
> > > 10.2
> > 
> > 
> > Hi How can I update it to version 10.2.*?
> > I run composer update but spatie library still on version 10.0.0
> > thanks so much
> 
> Just go into your composer.json and change it from 10.0.0 to 10.2.* and run composer update ![image](https://user-images.githubusercontent.com/16135819/184102586-af51b7a4-9091-45d4-b417-dddc6a46de58.png)

You saved my life!!!!

**Comment by MooseSaeed** [comment]
> > > 10.2
> > 
> > 
> > Hi How can I update it to version 10.2.*?
> > I run composer update but spatie library still on version 10.0.0
> > thanks so much
> 
> Just go into your composer.json and change it from 10.0.0 to 10.2.* and run composer update ![image](https://user-images.githubusercontent.com/16135819/184102586-af51b7a4-9091-45d4-b417-dddc6a46de58.png)

@ultrasibz @marcelo-kazalukian @s00ar  When running composer update after changing it to 10.2.* composer started to remove many things. Is it safe to continue with the package this way?

![Image description](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/iz0wx0k3izyz6uhaff2u.png)

**Comment by badredy** [comment]
i reinstalled the package without version and it's fine for me : 
composer require "spatie/laravel-medialibrary"
