### ISSUE TITLE
Responsive images of a conversion from a collection changed in v10?

### ISSUE THREAD

**Issue by mojowill** [spatie/laravel-medialibrary#2778]
I've upgraded an application to L9 and Media Library 10 however the responsive images seem to be behave differently and are giving me an exception:

I have a blade component for a card which I pass in a video:

```blade
@php
    $thumbnail = $video->getFirstMedia('thumbnail');
@endphp

<div class="relative group">
    <div class="overflow-hidden w-full bg-gray-200 rounded-md shadow-md aspect-video group-hover:opacity-75">
        <div class="relative">

            <a href="{{ route('video.show', $video->id) }}">
                @if($thumbnail)
                    {{ $thumbnail('app-thumbnail') }}
                @else
                    <img src="{{ asset('images/video.png') }}" alt="Video Thumbnail">
                @endif
            </a>

<snip...>
```

This gets the first media from a collection called thumbnail and then should display the responsive images for the app-thumbnail conversion, worked fine on Laravel 8 and ML 9 however I now get

`Found 1 error while validating the input provided for the GetObject operation: [Key] expected string length to be >= 1, but found string length of 0`

I've dumped `$thumbnail` and can see the conversion available there.
![Screenshot 2022-02-14 at 11 21 44](https://user-images.githubusercontent.com/865606/153855081-e574ecf8-747e-4e37-b5b1-f7d2e77568ad.png)

Has something changed with ML10 that I need to be aware of?

**Comment by mojowill** [comment]
Adding out put from Ray as well which captures the exception. To add files etc are in place on S3 without issues and I can see the files have been generated and put in the correct place.

![Screenshot 2022-02-14 at 11 55 56](https://user-images.githubusercontent.com/865606/153859934-b20bc39a-6484-4941-a4a6-e61b17719e52.png)

**Comment by dimifontaine** [comment]
I get the exact same exception when using the getSrcset method on a media. It's working in Laravel 8 but failing in Laravel 9. Images are stored in S3 as well.

In a JsonResource I have: 
```php
$featured_media = $this->getFirstMedia('featured-images');
return [
    'featured_image'    => [
        'url' => $featured_media->getUrl('banner'),
            'srcset'    => $featured_media->getSrcSet('banner'),
             'title'     => $featured_media->getCustomProperty('title'),
             'alt'       => $featured_media->getCustomProperty('alt'),
    ],
]
```
Exception: `Found 1 error while validating the input provided for the GetObject operation: [Key] expected string length to be >= 1, but found string length of 0`

Here's the Laravel Forge's exception stacktrace if that can help.
![Screenshot 2022-02-16 at 08 00 02](https://user-images.githubusercontent.com/1719260/154170278-2659e743-3532-4b33-8e11-ae8ffd905a62.png).

**Comment by freekmurze** [comment]
That strange... I'm a bit short on time to investigate this actively, but I would welcome a PR that fixes this.

**Comment by mojowill** [comment]
Looking at this in more detail it seems that `getBaseMediaDirectoryUrl()` calls down to https://github.com/thephpleague/flysystem/blob/ea4542acf038d2ac37fa36df6a29a25f6dc41a63/src/PathPrefixer.php#L36 (eventually via `laravel/framework/illuminate/AwsS3V3Adaptor.php`) which strips out the forward slash?

**Comment by matt127127** [comment]
In the function getResponsiveImagesDirectoryUrl (DefaultUrlGenerator) line 34,

Just change the return statement from 
` 
return Str::finish(url($base.$path), '/');
`
to
`
return Str::finish($this->getDisk()->url($path), '/');

`
and comment out
`
        $base = Str::finish($this->getBaseMediaDirectoryUrl(), '/');
`

**Comment by sebastiaanluca** [comment]
Can confirm @matt127127's solution works.

**Comment by freekmurze** [comment]
@matt127127 Could you PR your solution?

**Comment by matt127127** [comment]
> @matt127127 Could you PR your solution?

https://github.com/spatie/laravel-medialibrary/pull/2837

**Comment by sebastiaanluca** [comment]
I saw that the PR has been merged into v9. Will it be released as a fix for v10 too?

**Comment by freekmurze** [comment]
Ah right, I still need to do this. If you need it fast, send a PR and I'll tag and release quickly 👍
