### ISSUE TITLE
Spatie docs still showing v9 as latest version

### ISSUE THREAD

**Issue by jackcruden** [spatie/laravel-medialibrary#2782]
<img width="538" alt="Screen Shot 2022-02-15 at 11 32 31" src="https://user-images.githubusercontent.com/2648061/154054453-2b44ec0a-aaf5-4ad5-b385-cbfad602d14c.png">

https://spatie.be/docs/laravel-medialibrary/v10/introduction

**Comment by vinitsainyam** [comment]
Symfony Exception
- Model namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class ServiceRequestFile extends Model implements HasMedia
{
    use InteractsWithMedia;
    use SoftDeletes;

    protected $fillable = [
        'file_name', 'service_request_id', 'mail_id', 'model_type',
    ];

    public function getListingFilePathAttribute()
    {
        $listingImagePath = $this->getFirstMediaUrl('service_request_files');

        if (! $listingImagePath) {
            $listingImagePath = 'images/image-not-available.png';
        }

        return $listingImagePath;
    }

    public function getTemporaryUrlAttribute()
    {
        $urlExpiration = \Carbon\Carbon::now()->addMinutes(5);
        $conversionName = '';
        $s3Options = [];

        $url = $this->getFirstMedia('service_request_files')->getTemporaryUrl($urlExpiration, $conversionName, $s3Options);

        return  $url;
    }
}

File Upload Code :
                $serviceRequestFile->addMedia($fileInput)->preservingOriginal()->toMediaCollection('service_request_files');
