### ISSUE TITLE
MediaLib Pro License Key Issue

### ISSUE THREAD

**Issue by nolros** [spatie/laravel-medialibrary#2792]
Unsure where to submit this request. 

I purchased a single server license on 24th Jan this year: Receipt # 32993684

I'm attempting to install Media Pro. I've followed all the steps to auth.json. When I run composer to install, I'm getting the following error:

curl error 60 while downloading https://satis.spatie.be/packages.json: SSL certificate problem: certificate has expired  

I suspect the error is related to the GitHub repo invitation expiring. As I've been traveling, I've been unable to get to the installation until today. 

How would I get another invite to the Pro repo?  

Many Thanks
Nolan

**Comment by freekmurze** [comment]
For the GitHub invite, send a mail to `support@spatie.be` and we'll get it sorted.

For the SSL problem: if you take a look at satis.spatie.be you'll see that it has a valid certificate. This is a newer Let's Encrypt certificate. Some older systems can't handle this type of certificate anymore. I believe it could be resolved by upgrading `OpenSSL` to the latest version.

**Comment by nolros** [comment]
Sent and waiting for activation

**Comment by WouterBrouwers** [comment]
@nolros I've sent the invite!

**Comment by nolros** [comment]
As always you guys are awesome. Thank you!
