### ISSUE TITLE
Reading Exif data is not supported by this PHP installation.

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-medialibrary#280]
Is this a common error or am I doing something wrong?

**Comment by freekmurze** [comment]
This package will read out exif data. Probably your PHP installation doesn't have the right extension installed.

**Comment by dopyoman** [comment]
What extension would need to be enabled to fix this? I'm running into this error as well.

**Comment by freekmurze** [comment]
You need the exit extension: http://php.net/manual/en/exif.installation.php

**Comment by joebenson** [comment]
I also ran into this. Perhaps adding `exif` as a dependency in the docs would be helpful for others. Just a suggestion. Would've saved me a few extra minutes. Stellar package overall!

**Comment by freekmurze** [comment]
Added a note to the docs.

**Comment by ultrono** [comment]
The following may be of help to users of LaraDock.

You can change the `PHP_FPM_INSTALL_EXIF` .env variable from `false`to `true`. After making the change simply run `docker-compose build php-fpm`.

**Comment by HeptaAurium** [comment]
If on windows, just locate your php.ini file, and change this line `;extension=exif ` to `extension=exif `

**Comment by leonelunderscore** [comment]
> If on windows, just locate your php.ini file, and change this line `;extension=exif ` to `extension=exif `

Even if you're a Linux user

**Comment by kcdon4smart** [comment]
An uncaught Exception was encountered

Type: Intervention\Image\Exception\NotSupportedException

Message: Reading Exif data is not supported by this PHP installation.


Please how do i fix this.

i tried uploading a Profile pix on my E-Commerce platform and it said this above, Please i need Please.
