### ISSUE TITLE
When using cloudinary image driver, images get uploaded but cannot be deleted

### ISSUE THREAD

**Issue by matthiastjong** [spatie/laravel-medialibrary#2808]
I am using the [codebar-ag/laravel-flysystem-cloudinary](https://github.com/codebar-ag/laravel-flysystem-cloudinary) to add a disk to the Laravel `filesystem.php` using:

```
'disks' => [
        //

        'cloudinary' => [
            'driver' => 'cloudinary',
            'cloud_name' => env('CLOUDINARY_CLOUD_NAME'),
            'api_key' => env('CLOUDINARY_API_KEY'),
            'api_secret' => env('CLOUDINARY_API_SECRET'),
            'url' => [
                'secure' => (bool) env('CLOUDINARY_SECURE_URL', true),
            ],
        ],

    ],
```

Uploading files using the `media-library` is working. However, when I use `$media->delete()`, the media does not get deleted in the Cloudinary storage bucket.

When I delete the media using the Storage facade via `Storage::disk('cloudinary')->delete($media->getPath());`, then it **does** get deleted in the external bucket.

**Comment by freekmurze** [comment]
We don't maintain the Cloudinary driver, and deletion seems to work for all built-in functionality. Best to open an issue at the cloudinary driver repo.

**Comment by matthiastjong** [comment]
Could you elaborate on how the media gets deleted?
