### ISSUE TITLE
getMedia order by id desc

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#282]
So I want the most recent uploads to be first when using getMedia() on my model.

I cant seem to find a way beside querying the Media table directly.

I would like to order things on top of using getMedia()...

**Comment by kickthemooon** [comment]
Its ok. querying the media table directly works fine:
```
$media = Media::where('model_type', 'App\MediaLibrary')->orderBy('id', 'desc')->get();
```
I got a little confused, thought some methods wont work but everythings alright :)

**Comment by dliebel** [comment]
Hello

I have a problem getting the url of the image

This is my model
`namespace App\Models;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

class BlogPost extends Model implements HasMedia
{
    use HasMediaTrait;
    public $table = 'blog_post';

    public function addImage($path){
        $this->addMedia($path)
             ->preservingOriginal()
             ->toMediaCollection();
    }
    public function getImage(){
        $media = $this->getMedia();
        $ruta = $media[0]->getUrl();
        return $ruta;
    }
}`


This my method when I want to get the url of the image

`$postQuery=  BlogPost::where('status', '=', 1)
                            ->orderBy('id', 'asc')
                            ->select(['title','description','article','date_published','banner_imagen'])
                            ->get();
            $postsSend=array();
            foreach( $postQuery as $q ){
                $post = array();

                if( $q->hasMedia('images') ){
                    $post['imagen'] = $q->getMedia();
                }else{
                   $post['imagen'] = 'noUrl';
                }
                $postsSend[]=$post ;
            }
            $statusCode=200;
            $response = [
                'post'=>$postsSend
            ];
             return response()->json($response, $statusCode);`

I do not know where I'm wrong

**Comment by dliebel** [comment]
One not so elegant solution was the following

`$postQuery=  BlogPost::where('status', '=', 1)
                            ->orderBy('id', 'asc')
                            ->select(['id','title','description','article','date_published','banner_imagen'])
                            ->get();

            $postsSend=array();

            $media=array();

            foreach( $postQuery as $q ){

                $post = array();

                $post['id'] = $q->id;
                $post['title'] = $q->title;
                $post['description'] = $q->description;
                $post['article'] = $q->article;
                $post['banner_imagen'] = $q->banner_imagen;
                $media= Media::where([
                        ['model_type', '=', 'App\Models\BlogPost'],
                        ['model_id', '=',  $q->id] ])
                        ->orderBy('id', 'desc')->first();
                if (!empty($media)) 
                   $post['imagen'] = $media['id'] ."/".$media['file_name']; 
         
                $postsSend[]=$post ;
            }`

**Comment by humaneguy** [comment]
Hi. I had a reason to order in an application I'm working on, now.

You can use this code:
```php
return $user->getMedia('reports')->toQuery()->orderByDesc('created_at')->get();
```
