### ISSUE TITLE
UUID Invalid

### ISSUE THREAD

**Issue by yahya077** [spatie/laravel-medialibrary#2825]
### Discussed in https://github.com/spatie/laravel-medialibrary/discussions/2786

<div type='discussions-op-text'>

<sup>Originally posted by **yahya077** February 16, 2022</sup>
I'm trying to upload image to 'api/media-library-pro/uploads' from postman. I get 200 status and success response.

But when i do `$model->syncFromMediaLibraryRequest(<response object>)->toMediaCollection('thumb')`
It returns invalid uuid error. I genarate uuid with uuid.v4() from postman. One of my uuid is 'beb9d892-38bc-4ec3-a9de-5f745c9c307d'.

I'm using media-library-pro and it is works on web page.
 
How can I sync image from *Spatie\MediaLibraryPro\Models\TemporaryUpload* to *MyModel*.</div>

**Comment by booni3** [comment]
Did you find a solution to this? I have the same issue. I have tried `enable_temporary_uploads_session_affinity = false` in config as some others say this helped, but not for me.

I am using the livewire components and get this error when trying to upload multiple files.
