### ISSUE TITLE
Solved: PHP Fatal error:  Declaration of Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection::jsonSerialize() must be compatible with Illuminate\Support\Collection::jsonSerialize(): array

### ISSUE THREAD

**Issue by frifrafry** [spatie/laravel-medialibrary#2826]
Bug found using
"laravel/framework": "9.1.0"
"spatie/laravel-medialibrary": "10.0.0"

Just change in _Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection.php_ line 51:
`public function jsonSerialize()`
to
`public function jsonSerialize(): array`

to fix this issue.

**Comment by freekmurze** [comment]
Could you create a PR for this?

**Comment by frifrafry** [comment]
My bad, this is already included in the master branch!
I used the (outdated) npm package.
