### ISSUE TITLE
spatie/laravel-medialibrary[10.0.0, ..., 10.1.2] require illuminate/bus ^9.0

### ISSUE THREAD

**Issue by diazsasak** [spatie/laravel-medialibrary#2830]
Hi, i try to install the package with this command:

composer require "spatie/laravel-medialibrary:^10.0.0"

but I got this error. i have try to composer update, --with-all-dependencies also --ignore-platform-reqs but not solved.

![image](https://user-images.githubusercontent.com/7880137/157633264-7a2572e9-784d-4fbe-a52e-3a2488e60c72.png)

Any help? Thank you

"laravel/framework": "^8.75"

**Comment by erikn69** [comment]
Look at the requirements and choose the right version

**Comment by diazsasak** [comment]
@erikn69 yes. at the end i follow the requirement https://filamentphp.com/docs/2.x/spatie-laravel-media-library-plugin/installation . 

i thought it can use the latest version. thank you
