### ISSUE TITLE
Conversion fails after upload to S3 using MediaLibary Pro

### ISSUE THREAD

**Issue by dambridge** [spatie/laravel-medialibrary#2854]
**Details**

- Laravel 9.5.1
- Media Library Pro 2.1.8.

I've been struggling with getting conversions running after uploading a file to S3. The file is upload just fine, but I get the error `**Unsupported image type application/x-empty. GD driver is only able to decode JPG, PNG, GIF, BMP or WebP files.**` immediately following the post. 

When I check the `media` table after the initial temporary upload, all data is there; however, after submitting and therefore uploading to s3, the `mime_type` is `application/x-empty` and 'size` is 0. I'm assuming the size missing creates the error in mime-type detection.

**Comment by ale1981** [comment]
I am also having this same issue with S3

**Comment by dambridge** [comment]
As far as I can tell so far, it looks like somewhere in the `toMediaCollectionFromTemporaryUpload` method of `FileAdder.php` the `$pathToFile` is not getting set?

**Comment by ale1981** [comment]
I tried downgrading to media library to 10.2.0 but the issue still persisted, I had to downgrade to 10.1.5 and it's now working fine, so something that was changed between 10.1.5 and 10.2.0 is causing the issue.

**Comment by dambridge** [comment]
Sadly, didn't work for me. Downgraded to 10.15 as you suggested and tried again, but same issue persists. I can't see in the Pro repo, so not sure what may have changed in there either.

**Comment by dambridge** [comment]
I'll leave this open for now; in the meantime I'm going to go back to home-brewing something. :-(

**Comment by ale1981** [comment]
10.15 or 10.1.5?

**Comment by SaurabhKharivale** [comment]
On laravel 8 with medialibrary 9 everything works perfectly with my setup.

But after upgrading to laravel 9 and medialibrary 10.3.0, I am facing the same issue but with google cloud storage. I am using [spatie/laravel-google-cloud-storage](https://github.com/spatie/laravel-google-cloud-storage) package along with laravel-medialibrary-pro.

Downgrading to 10.1.5 or below didn't work for me.

Here are my initial finding:
1. **Image file is not uploaded to cloud storage only directories are created**
After uploading images through frontend, directroies gets are created on gcs but image file is missing. Then it tries to generate thumbnails, but this fails as image does not exists and it results in following error.
```Unsupported image type application/x-empty. GD driver is only able to decode JPG, PNG, GIF, BMP or WebP files.```
If file was uploaded then above error won't occur according to me.

2. **Disabling thumbnail generation gives an impression that everything is ok but its not.**
If I disable thumbnail generation in config by setting ```generate_thumbnails_for_temporary_uploads``` to **false** then everything works. Both "temporary_upload" and "media" tables contains the relevant records but image file does not get uploaded to cloud storage.

3. **Flysystem v3 might be the reason for this issue**
As laravel 9 is using the newer Flysystem v3 which was heavily refactored this might have broken something.
Also, I noticed the upload function of  [current flysystem google adapter](https://github.com/thephpleague/flysystem-google-cloud-storage/blob/fb35a43c8e18037822c7d48ef42c301362e3c05f/GoogleCloudStorageAdapter.php#L123) does not pass all the config options when compared to [old spatie google adapter](https://github.com/spatie/flysystem-google-cloud-storage/blob/bc37457030570804b820326faa8c63e835b3252b/src/GoogleCloudStorageAdapter.php#L124). I tried to add all missing config options but still image files were not uploaded.

@dambridge in your case, does files are uploaded to S3 and are you able to view those in browser from s3 link?

Maybe @freekmurze or his team can look into this issue

**Comment by richan-fongdasen** [comment]
It works for me after installing the specific package versions.

```
spatie/laravel-medialibrary: 10.1.4
spatie/laravel-medialibrary-pro: 2.1.6
```

**Comment by freekmurze** [comment]
I'll try to look into this soon. Feel free to open a PR if you already know the solution and want it to be released quickly 👍

**Comment by dambridge** [comment]
@SaurabhKharivale Hey there. Actually, my file does get uploaded properly, it's just the media table update that goes awry.

**Comment by dambridge** [comment]
@freekmurze Cheers for that and I'm sure we'll keep digging collectively.

**Comment by dambridge** [comment]
@richan-fongdasen OK, I mucked about following your lead, and this is now working for me on S3:
```
spatie/laravel-medialibrary        10.3.0
spatie/laravel-medialibrary-pro    2.1.6
```

**Comment by dambridge** [comment]
@richan-fongdasen Can I ask how you force the laravel-medialibrary package to that version? I tried editing composer.json in the pro package to reflect that, but no matter what I do it sticks to 10.3.0

**Comment by ale1981** [comment]
@dambridge I forced my package version using the following in my composer.json
```
        "spatie/laravel-medialibrary": "10.1.5",
        "spatie/laravel-medialibrary-pro": "^2.0",
```
Setting the version of laravel-medialibrary also downgraded laravel-medialibrary-pro to 2.1.6

**Comment by ale1981** [comment]
It seems this is related to the laravel-medialibrary-pro components rather than laravel-medialibrary. I just amended my composer.json to force laravel-medialibrary-pro to use 2.1.6 and the latest version of laravel-medialibrary which is currently 10.3.0 and it works fine.
```
        "spatie/laravel-medialibrary": "^10.0",
        "spatie/laravel-medialibrary-pro": "2.1.6",
```

**Comment by dambridge** [comment]
@ale1981 That setup properly populates the media table for me, but fails to upload the table, *or* display the thumbnail

**Comment by dambridge** [comment]
Yeah, so again:
```
spatie/laravel-medialibrary        10.3.0 
spatie/laravel-medialibrary-pro    2.1.12
```
Uploads the file successfully, and updates the media table with the `TemporaryUploadFile`  for model_type, and gets the size. But as soon as it tries to run the thumbnail, the error occurs as no size and mime_type are saved.

**Comment by dambridge** [comment]
Hmmmmm. OK, upon looking at all temporary uploads in `/storage/media-library/temp`, they're all 0 bytes!

**Comment by dambridge** [comment]
Anyway, I've been digging in here for 3-4 days now. I'm going to use something else and come back to Pro later if it gets updated. I'll leave it open.

**Comment by dambridge** [comment]
Okaaaaay! Testing some hackery in the package itself here (FYI, I haven't forked or anything, as I don't think I'm a good enough dev to get through the whole testing/PR thing, noob factor is strong.) But here's what I did to get it working:

In `vendor/spatie/laravel-medialibrary-pro/src/Models/TemporaryUpload.php`:

Lines 138/139 of the move Media function, I added:
```
$size = $media->size;
$mime_type = $media->mime_type;
```

And In `vendor/spatie/laravel-medialibrary-pro/src/Actions/ConvertLivewireUploadToMediaAction.php`, in the `createFromS3LivewireUpload` method, on line 162 I added:
`'mime_type' => $livewireUpload->getMimeType(),` which apparently was missing?

This gets things working for me, at least in some fashion. However, thumbnails still get the error 👎

**Comment by martin-ro** [comment]
Changing versions didn't help for me. I don't use medialibrary-pro. Uploading with a livewire component to S3 the file is actually uploaded into the bucket in `livewire-tmp` but then get's wiped when submitting. Log shows
`Unsupported image type application/x-empty. GD driver is only able to decode JPG, PNG, GIF, BMP or WebP files.`
or with imagick `Unable to read image from path (/tmp/GlideQ7hupS)`.

Those are related to the file not being found when the conversion is attempted. When I remove all conversion for the collection the upload silently fails. Fail in the sense that the file does not exist in s3 storage while the record is in the db though.

It previously worked and after a composer update my tests didn't catch this new behavior.

**Comment by martin-ro** [comment]
This worked at least for me:

in `config/media-library.php`

```php
'remote' => [
        /*
         * Any extra headers that should be included when uploading media to
         * a remote disk. Even though supported headers may vary between
         * different drivers, a sensible default has been provided.
         *
         * Supported by S3: CacheControl, Expires, StorageClass,
         * ServerSideEncryption, Metadata, ACL, ContentEncoding
         */
        'extra_headers' => [
            'CacheControl' => 'max-age=604800',
            // 'ACL' => 'public-read',
        ],
    ],
```

commenting out `'ACL' => 'public-read'` fixed it. 

¯\_(ツ)_/¯

**Comment by dambridge** [comment]
Interesting. I'll give it a go.

**Comment by dambridge** [comment]
Nah, nothing. Still can't find the temp file or something

**Comment by freekmurze** [comment]
I'm going to try to get to the bottom of this today. Any tips or suggestions are very welcome.

**Comment by freekmurze** [comment]
I'm having a hard time replicating this using the regular media library. 

I've created a fresh Laravel app and installed the media library. 

[This command](https://github.com/spatie/medialibrary-app/blob/9bb7262565ee127940c20f847c63a5b7b598c23e/app/Console/Commands/AddMediaCommand.php#L8) can successfully upload files to S3 and it also creates correct links to conversions. 

<img width="1298" alt="CleanShot 2022-03-30 at 10 21 18@2x" src="https://user-images.githubusercontent.com/483853/160785720-311aab21-fe82-40f3-ae34-b37069044b53.png">

All seems to be working correctly.

I've put my app [in this repo](https://github.com/spatie/medialibrary-app). Could you test if this works for you. (Don't forget to fill in the `AWS_` env variables to a bucket of your own.

**Comment by martin-ro** [comment]
I cloned the app and it works - uploads, conversion all fine. 

**But if you add** 

```php
'extra_headers' => [
    'CacheControl' => 'max-age=604800',
    'ACL' => 'public-read', // <-----
],
```

you get the error. Check the [Ray](https://flareapp.io/share/95JqxE07#F57) here.

When I was trying to debug that yesterday I found in some server log an entry saying something about "ACL .. not .. allowed.." or similar. I can't find that log right now but that eventually lead me to that config.

**Comment by freekmurze** [comment]
If also adapted the Blade Attachment example in the [media library pro demo app](https://github.com/spatie/laravel-medialibrary-pro-app) to use S3.

I could successfully submit that form and the resulting image was copied to S3, conversions were generated.

<img width="1572" alt="CleanShot 2022-03-30 at 12 55 26@2x" src="https://user-images.githubusercontent.com/483853/160816011-1954a7a7-c4af-4900-a1be-ea109d8a3327.png">

<img width="1135" alt="CleanShot 2022-03-30 at 12 56 42@2x" src="https://user-images.githubusercontent.com/483853/160816114-9b796c63-585e-4ed4-a315-1b0ad4f19a0a.png">

I did found out however that when your S3 credentials are not correct, that it fails with the error message mentioned by @dambridge 

If you see this error, please make sure that your S3 credentials are correct. Test it out by manually sending something to S3 using the configured disk. We'll try to display a clearer error message when we detect S3 is not correctly configured.

**Comment by martin-ro** [comment]
Thanks for looking into this.

The credentials is not the issue I think. Have you tried to run the command with that ACL setting? With the same bucket and same AWS credentials you will see that error described by most here.

Anyway, it works for me now..

**Comment by dambridge** [comment]
Hey! I deleted my media-library and media-library-pro vendor directories and reinstalled. I removed the ACL setting in config per @martin-ro but still didn't work.

Then.....

I had my `config/livewire` `temporary_file_upload.disk` set to s3, per the instructions on working with Livewire. I reverted to `null` and voila, worked like a charm!

**Comment by freekmurze** [comment]
Great! Going to close this issue as it seems to be resolved. I'll improve our docs on this point soon.

**Comment by martin-ro** [comment]
This is closed but i just noticed this error came back for me. Manually uploading works but my tests fail when using a livewire component to upload an image.

`Unsupported image type application/x-empty. GD driver is only able to decode JPG, PNG, GIF, BMP or WebP files.` again.

Pretty frustrating.. if anyone can figure this out please let me know.

**Comment by ryanmortier** [comment]
Having the exact same issue. I just recently updated my PHP from v7.4 to v8.1, Laravel from v8 to v9, and Media Library Pro from v9 to v10.

GD gives me the following:
```
Unsupported image type application/x-empty. GD driver is only able to decode JPG, PNG, GIF, BMP or WebP files.
```

Imagick gives me the following:
```
Unable to read image from path (/tmp/Glide8fN9rc).
```

I'm using Livewire/Blade with the local filesystem driver. I'm not using S3. I don't have have my livewire config even published.

**Comment by langeuh** [comment]
![Screenshot 2022-04-22 at 14 39 40](https://user-images.githubusercontent.com/5647964/164716028-ce5df684-71ca-4742-b356-ddf354c89a87.png)

i too got this error after upgrading
for me the `'visibility'=>'public'` caused the error in the S3 config settings
