### ISSUE TITLE
Media folders

### ISSUE THREAD

**Issue by mjubouri** [spatie/laravel-medialibrary#2858]
Hello Dear,

I have a problem with the media folder in public, any files I upload it the folder will be 700 permission, and I tried to change the folder -R chmod but it's still the same problem

**Comment by PaolaRuby** [comment]
Set default permissions on config file

**Comment by mjubouri** [comment]
> Set default permissions on config file

But in other project I didn't set any default permissions and its work,

I need to understand the problem?
