### ISSUE TITLE
PHP Fatal Error  Illuminate\Support\ServiceProvider::mergeConfigFrom()

### ISSUE THREAD

**Issue by xtrasmal** [spatie/laravel-medialibrary#288]
Hi there,

On production, I see the following error when running the phpunit tests to see where my problem is. Right now I can upload, media get's added to the database, but I do not see the file on my filesystem. The only lead that I have is the following error:

```bash
PHP Fatal error:  Illuminate\Support\ServiceProvider::mergeConfigFrom(): 
Failed opening required '/home/forge/loranto.com/vendor/spatie/laravel-medialibrary/src/src/../resources/config/laravel-medialibrary.php' (include_path='/home/forge/loranto.com/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php') 
in /home/forge/loranto.com/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php on line 67
```

**Comment by xtrasmal** [comment]
Ok seems to be solved. The error is gone after updating to 4.8.
But. any ideas why images do get added to the database, but the actual storing of the file does not go through. No error.

**Comment by nicolasbeauvais** [comment]
Where do you try to save the medias ?

**Comment by xtrasmal** [comment]
Ok, locally it works when I have a symlink from the public folder to the storage folder:
```
media@ -> ../storage/media
```

**Comment by xtrasmal** [comment]
Blegh.. I knew this was something simple like a typo. Changed it to the real folder.

```
media@ -> ../storage/app/public/media
```

Sorry for this. This webshop is taking me 12 hours a day and I might need to buy me a crate of beer and a rubberboat with a palmtree.

![Palmtree](http://www.jb-inflatables.nl/wp-content/uploads/2014/05/opblaasbaar_palmboomklimmen-1-940x652.jpg)

**Comment by freekmurze** [comment]
Haha, epic comment! 😂

**Comment by sdeering** [comment]
How did you solve this? @xtrasmal

**Comment by sdeering** [comment]
Looks like removing vendor dir and composer install did it for me.

**Comment by Kwenziwa** [comment]
> Looks like removing vendor dir and composer install did it for me.

This worked for me 👍
