### ISSUE TITLE
php artisan medialibrary:clear  Force does not exist

### ISSUE THREAD

**Issue by xtrasmal** [spatie/laravel-medialibrary#289]
Hi there,

when running: php artisan medialibrary:clear
on a Forge provisioned Laravel Framework version 5.2.41 server I get the following error:

```
[Symfony\Component\Console\Exception\InvalidArgumentException]
  The "force" option does not exist.
```

**Comment by nicolasbeauvais** [comment]
This error has been issued in the [last version of medialibrary](https://github.com/spatie/laravel-medialibrary/releases/tag/4.8.0)  :smile:

**Comment by xtrasmal** [comment]
thnks
