### ISSUE TITLE
getMedia() doesn't return media with collection set

### ISSUE THREAD

**Issue by ziming** [spatie/laravel-medialibrary#29]
I expected getMedia() to return all media regardless of collection name, but it doesn't turns out this way. If I did

```
$object->addMedia($file, $file->getMimeType());
```

$object->getMedia() returns me nothing.

**Comment by freekmurze** [comment]
As mentioned in the documentation calling `getMedia()` without a collection name will return all items in a collection named 'default'. I'll add a method do get all media in a future version. If you need this quick, feel free to make a PR.

**Comment by ziming** [comment]
Not in a hurry, thank you. Though if I do make a pull request, what do you like the method to be named?

**Comment by freekmurze** [comment]
The name `getAllMedia` sounds good to me.

**Comment by freekmurze** [comment]
I'm releasing v3 of the package this week. The `getMedia`-function in that version will return all media regardless of collection name.

**Comment by ziming** [comment]
Thanks
