### ISSUE TITLE
Command `media-library:regenerate` fails when regenerating large amount of media

### ISSUE THREAD

**Issue by saulens22** [spatie/laravel-medialibrary#2909]
### Error

When trying to regenerate large amount of media thumbnails, at some point (~10k media records) error is thrown:
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 403`

It happens because `media-library:regenerate` command tries to load all models from database.

### Possible solutions

* chunk `Media` results - `MediaRepository` class should return `QueryBuilder` for `chunk()` method to work properly. 
* add `--starting-from-id` equivalent `--to-id` (or similar) for manual chunking

**Comment by kb6673** [comment]
I worked around this recently with something like this `php -d memory_limit=512M  artisan media-library:regenerate ...`

---

Incidently, I found `--starting-from-id ` didn't work
