### ISSUE TITLE
Help with conversions

### ISSUE THREAD

**Issue by jjdrake** [spatie/laravel-medialibrary#293]
I'm looking into refactoring my current media functionality to use this package instead.  I'm currently passing user-generated cropping dimensions to a queued job which saves the cropped images based on the provided dimensions.  Are there any examples of doing similar with this package?  Specifically, I'm not sure how to pass any user-generated dimensions to a configured queue.

On a related note, from what I've read regarding the _manipulations_ function, it claims to be regenerating the images.  Is there any built-in way of generating the manipulated images based on user-provided criteria without regenerating the images?

**Comment by freekmurze** [comment]
Hi, 

you can use `manipulations` to add some media specific conversions. More info:  https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/storing-media-specific-manipulations

For you second question I assume that you want to perform some media manipulations without them being stored in the media library. Take a look at [the underlying Glide package](https://github.com/spatie/laravel-glide) for that.
