### ISSUE TITLE
Related media from foreign tables referencing main table doesn't get deleted.

### ISSUE THREAD

**Issue by jihad28** [spatie/laravel-medialibrary#2938]
Recreating the bug.

For example we have `categories` and `sub_categories` table.
Each table interacts with media.

#### Categories Table
```php
Schema::create('categories', function (Blueprint $table) {
    $table->id();
    $table->string('name');
    $table->text('description')->nullable();
});
```
#### Sub Categories Table
```php
Schema::create('sub_categories', function (Blueprint $table) {
    $table->id();
    $table->foreignId('category_id')->references('id')->on('categories')->cascadeOnDelete();
    $table->string('name');
    $table->text('description')->nullable();
    $table->string('code');
    $table->string('rack');
    $table->string('row');
});
```

When a category gets deleted their media is also deleted with it's sub categories.
But the sub categories media will remain.

I know I can fix this with deleting event in boot function inside the categoy model like so
```php
public static function boot() {
    parent::boot();
    static::deleting(function ($model) {
        $subCategories = SubCategory::where('category_id', $model->getKey());
        foreach($subCategories as $sub) {
            $sub->delete(); // This will trigger the deleting listener inside InteractsWithMedia
        }
    }
}
```

But the issue is there can be a lot of relations and doing this in every model is not good, and will led to repetitive code.

This will be very useful feature if it's fixed.

**Comment by PaolaRuby** [comment]
>this in every model is not good, and will led to repetitive code.

Make a trait

**Comment by jihad28** [comment]
> >this in every model is not good, and will led to repetitive code.
> 
> Make a trait

Okay so how do i get all relationships for a model and loop through them to delete their media?

This should be done inside InteractsWithMedia Trait.

**Comment by PaolaRuby** [comment]
>Okay so how do i get all relationships for a model and loop through them to delete their media?

the same code on a trait, It looks so easy that I don't think it's necessary to explain it. your code is not the best, look at this `SubCategory::where('category_id', $model->getKey());`, just use a `hasMany`, with that you can do everything on a trait

> This should be done inside InteractsWithMedia Trait.

Not, the package can delete other relations, really the worst idea

**Comment by jihad28** [comment]
No you got me wrong.
What I mean is that i will make the trait and this trait will be used in a lot of models.
So the models that the trait is used can have multiple relationships and most of them has media.
I want to get all relationships from the model that the trait is used and if it's cascade also delete their media.

**Not all models have relationships with SubCategory so it should jot be static inside the trait**

**Comment by jihad28** [comment]
Also i forgot the get on `SubCategory::where('category_id', $model->getKey())`

Sorry for the that.

**Comment by PaolaRuby** [comment]
> Not all models have relationships with SubCategory so it shouldn't be static inside the trait

Obviously

>So the models that the trait is used can have multiple relationships and most of them has media.
I want to get all relationships from the model that the trait is used and if it's cascade also delete their media.

Of course, easy with a trait for avoid duplicate the code

>No you got me wrong.

No, i did get you, you didn't get the idea, maybe you are new on php

>Also i forgot the get on `SubCategory::where('category_id', $model->getKey())`

Not, about that, if you plan to put that in a trait , obviously you won't achieve anything, read the laravel documentation
[eloquent-relationships](https://laravel.com/docs/9.x/eloquent-relationships)

**Comment by PaolaRuby** [comment]
```php
static::deleting(function ($model) {    
    foreach($model->mediaRelations ?: [] as $relation) {
        $model->{$relation}()->get()->each(function($sub){
            $sub->delete();
        });
    }
}
```

**Comment by jihad28** [comment]
Thank You for helping out.
