### ISSUE TITLE
Upload not working 5.2

### ISSUE THREAD

**Issue by packytagliaferro** [spatie/laravel-medialibrary#294]
So I love the premise of the library but cant get it to work with my 5.2 setup. Your docs on GitHub and https://docs.spatie.be/laravel-medialibrary/v4/introduction appear to be different as well (I tried both and neither work.) Seems pretty basic, but I am new to Laravel 

Github way
`$user->addMedia($file->file('image'))->toCollection('images');`
_Error: Call to a member function file() on string_

Website
`$user->addMediaFromRequest('image')->toCollection('images');`
_Error: Call to undefined method Illuminate\Database\Query\Builder::addMediaFromRequest()_

my full controller:

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;
use App\Http\Requests;
use App\User;
use Auth;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

class UserMediaController extends Controller implements HasMedia
{
    use HasMediaTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function showMedia()
    {
        return view('user/media');
    }

    public function uploadMedia(Request $request)
    {
        $files  = $request->all();
        $user   = Auth::user();

        foreach ($files as $file){
           $user->addMediaFromRequest('image')->toCollection('images');
        }

        /*$validator = Validator::make(
            $input_data, [
            'image_file.*' => 'required|mimes:jpg,jpeg,png,bmp|max:20000'
            ],[
                'image_file.*.required' => 'Please upload an image',
                'image_file.*.mimes' => 'Only jpeg,png and bmp images are allowed',
                'image_file.*.max' => 'Sorry! Maximum allowed size for an image is 20MB',
            ]
        );*/
    }

}
```

this also fails with just a single upload:

```
 public function uploadMedia(Request $request)
 {
        $user   = Auth::user();

        $user->addMedia( $request->file('image') )->toCollection('images');
}
```

I am using Dropzone.js to handle the front end if that matters.

**Comment by freekmurze** [comment]
Which version of the medialibrary / PHP are you using?

What does `$request->file('image')` contain?

**Comment by nicolasbeauvais** [comment]
Also the `HasMedia` interface and the `HasMediaTrait`trait should be used on your model not on your controller ([preparing your model](https://docs.spatie.be/laravel-medialibrary/v4/basic-usage/preparing-your-model)) which is the reason why you can't use `addMediaFromRequest` on your user model.

**Comment by packytagliaferro** [comment]
@freekmurze  Its Medialibrary V. 4 and PHP V. 7. 

@nicolasbeauvais , whoops. I just came back to this project and I did have all the on the User Model. I accidentally added it to the controller.  But when I remove it I still get the same error even with those trates in the User model. Here is what the upload response is if I print $file in the loop:
```

Reszc9X2LqPCCCFm1PoD0zHqdXXun5nnZ7NskZ7gArray
(
    [0] => Illuminate\Http\UploadedFile Object
        (
            [test:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 
            [originalName:Symfony\Component\HttpFoundation\File\UploadedFile:private] => alarm-news-pic-5.jpg
            [mimeType:Symfony\Component\HttpFoundation\File\UploadedFile:private] => image/jpeg
            [size:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 120482
            [error:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 0
            [pathName:SplFileInfo:private] => /Applications/MAMP/tmp/php/php2efdGJ
            [fileName:SplFileInfo:private] => php2efdGJ
        )

    [1] => Illuminate\Http\UploadedFile Object
        (
            [test:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 
            [originalName:Symfony\Component\HttpFoundation\File\UploadedFile:private] => alarm-news-pic-6.jpg
            [mimeType:Symfony\Component\HttpFoundation\File\UploadedFile:private] => image/jpeg
            [size:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 116141
            [error:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 0
            [pathName:SplFileInfo:private] => /Applications/MAMP/tmp/php/phpnFIaEs
            [fileName:SplFileInfo:private] => phpnFIaEs
        )

)
```


User Model:
```
<?php

namespace App;

use Zizaco\Entrust\Traits\EntrustUserTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

class User extends Authenticatable implements HasMedia
{
     use EntrustUserTrait; // add this trait to your user model
     use HasMediaTrait; //this is for the media library
     .............................More code
```

**Comment by DotFreelance** [comment]
It looks to me like you're taking the filename from your request and directly dropping that in, and that's why it cannot call the method `file()`... are you certain your **file upload form** has the Laravel required property `files => true`?

**Comment by freekmurze** [comment]
I'm assuming that your upload form hasn't got the right field (like @DotFreelance said).

Reopen this issue if you're still having troubles.

**Comment by packytagliaferro** [comment]
@freekmurze @DotFreelance  per Laravel 5.2 I dont use formbuilder but just a regular form that allows uploads

`<form id="real-dropzone" class="dropzone" action="/media" method="post" enctype="multipart/form-data">`

**Comment by freekmurze** [comment]
`v5` of the medialibrary has a new method `createAllFromRequest()`. Docs: https://docs.spatie.be/laravel-medialibrary/v5/api/adding-files#addallmediafromrequest

Reopen this issue if that method doesn't work for you.
