### ISSUE TITLE
Passing collection name to registerMediaConversions()

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#295]
For each user-provided image I want to create a thumbnail and assign the images to the user's collection, which is named after their username. This works if I hardcode it, but I can't figure out how to pass a dynamic collection name (such as their username) to `registerMediaConversions()` in my `Post` model.

#### PostController
```
public function store(Request $request)
{
    $user = User::find(1);
    $post = Post::create([
        'user_id' => $user->id,
        'title' => $request->title,
        'body' => $request->body,
    ]);

    foreach($request->file('file') as $image) {
        $post->addMedia($image)->toCollection($user->username);
    }
    return back()->withInput();
}
```

#### Post Model
```
namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Post extends Model implements HasMediaConversions
{
    use HasMediaTrait;

    protected $fillable = ['user_id', 'title', 'body'];

    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
             ->setManipulations(['w' => 368, 'h' => 232])
             ->performOnCollections();
    }

```

**Comment by timgavin** [comment]
Figured it out. It was automated and right in front of my face and I totally missed it! :P

**Comment by timgavin** [comment]
Is it possible to pass parameters to `registerMediaConversions()`?

**Comment by nicolasbeauvais** [comment]
What would be the parameter that you send to `registerMediaConversions()` ?

**Comment by timgavin** [comment]
I think I was asking about  passing a`username`. I originally thought I'd like to store all of a user's images inside a folder named with their username.

Something like this

```
joedoe
--imageOne
----conversions
--------imageOne.jpg

janedoe
--FluffyCats.jpg
--conversions
----tnFluffyCats.jpg
--StarWars
---LightsaberSquirrels.jpg
--conversions
----tnLightsaberSquirrels.jpg
```

**Comment by nicolasbeauvais** [comment]
There is a built-in functionality to help you change the directory structure of the medias:
https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/using-a-custom-directory-structure

Hope this can solve your problem :)

**Comment by timgavin** [comment]
Thanks. I already have the figured out; I'm using unique hashes as my directory names now. Users will be uploading lots of pictures so I was hoping to be able to organize them by username instead of having thousands and thousands of hashed directories. :)
