### ISSUE TITLE
SSL Operation failed with code 1

### ISSUE THREAD

**Issue by matthaselip** [spatie/laravel-medialibrary#2953]
the following error occurred:
` ErrorException

  file_put_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000126:SSL routines::unexpected eof while reading

  at vendor/spatie/laravel-medialibrary/src/Downloaders/DefaultDownloader.php:17
     13▕         }
     14▕
     15▕         $temporaryFile = tempnam(sys_get_temp_dir(), 'media-library');
     16▕
  ➜  17▕         file_put_contents($temporaryFile, $stream);
     18▕
     19▕         return $temporaryFile;
     20▕     }
     21▕ }

      +2 vendor frames
  3   app/Console/Commands/MigrateOfferImages.php:94
      App\Models\Offer::addMediaFromUrl()

      +13 vendor frames
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
`

using addMediaFromUrl seemed to have caused this issue, when retrieving files from a domain with https.  an example of the code currently is:

`try {
                        $offer->addMediaFromUrl('https://my-domain.com/files/offers/'.$thumbnail['file_name'])
                            ->withCustomProperties([
                                'start_date' => (isset($thumbnail['start_date']) && strlen($thumbnail['start_date']) > 0)?$thumbnail['start_date']:'',
                                'end_date' => (isset($thumbnail['end_date']) && strlen($thumbnail['end_date']) > 0)?$thumbnail['end_date']:'',
                                'status' => 'Enabled',
                                'image_link' => (isset($thumbnail['image_link']) && strlen($thumbnail['image_link']) > 0)?$thumbnail['image_link']:''
                            ])
                            ->toMediaCollection('Offer Featured Images');
                            $this->totalNumOfMediaFiles+=1;
                        } catch(UnreachableUrl $url) {
                            $this->errors[] = 'https://my-domain.com/files/offers/'.$thumbnail['file_name'];
                            $this->totalNumOfMediaFiles+=1;
                            continue;
                        } catch(QueryException $e) {
                            $this->errors[] = 'https://my-domain.com/files/offers/'.$thumbnail['file_name'].'-error: '.$e->getMessage();
                            $this->totalNumOfMediaFiles+=1;
                            continue;
                        } catch(\ErrorException $exception) {
                            $this->errors[] = 'https://my-domain.com/files/adverts/'.$thumbnail['file_name'].' -error: '.$exception->getMessage();
                            $this->totalNumOfMediaFiles+=1;
                            continue;
                        }`

Laravel Framework - 8.40
laravel-medialibrary - 9.0.0
php version 8.1.*

I found an article about this here:
[https://phpshowcase.com/question/file_get_contents-ssl-operation-failed-with-code-1-openssl-error-messages-error-0a000126-ssl-routines-unexpected-eof-while-reading](url)

**Comment by PaolaRuby** [comment]
impossible to read without indentation, use markdown correctly
