### ISSUE TITLE
Implicit incompatible float to int conversion is deprecated

### ISSUE THREAD

**Issue by elfeffe** [spatie/laravel-medialibrary#2959]
I'm getting this error:

Implicit conversion from float 40492.52199999999 to int loses precision in /media/psf/www/filament-commerce/vendor/spatie/laravel-medialibrary/src/ResponsiveImages/WidthCalculator/FileSizeOptimizedWidthCalculator.php on line 46

It's related to https://github.com/spatie/laravel-medialibrary/issues/2678
And seems to be a problem related to PHP 8.1 https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string

**Comment by fredsal** [comment]
Wich version of the package? laravel version?

**Comment by elfeffe** [comment]
> 

No, not related to that.

**Comment by vladski** [comment]
The deprecation message is triggered when calculating responsive image width by /ResponsiveImages/WidthCalculator/FileSizeOptimizedWidthCalculator.php and method finishedCalculating(int $predictedFileSize, int $newWidth).  Method calculateWidths() from the same class passes $predictedFileSize parameter which is not integer as required. It needs to be rounded and casted to int.

**Comment by QuentinGab** [comment]
Hi,
I solved this in a pr  (merged) not long ago https://github.com/spatie/laravel-medialibrary/pull/3145
