### ISSUE TITLE
MariaDb issue when upgrading from v8 to v9

### ISSUE THREAD

**Issue by lcresswell** [spatie/laravel-medialibrary#2969]
I ran into an issue when upgrading from v8 to v9 when using a Mariadb database. I was getting 
`Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>"$.generated_conversions", `media`.`updated_at` = ? where (`generated_conver...' at line 1 (SQL: update `media` set `generated_conversions` = custom_properties->"$.generated_conversions", `media`.`updated_at` = 2022-06-29 08:04:38 where (`generated_conversions` is null or `generated_conversions` =  or JSON_TYPE(generated_conversions) = 'NULL') and JSON_LENGTH(custom_properties) > 0)` 
when I added the AddGeneratedConversionsToMediaTable migration. 

The solution in the end was to edit the migration file, line 31.

Change
`'generated_conversions' => DB::raw('custom_properties->"$.generated_conversions")`
To
`'generated_conversions' => DB::raw('JSON_EXTRACT(custom_properties, "$.generated_conversions")')`

Think this could possibly be added to the docs as anyone using a MariaDb database will run into this issue.

**Comment by angeljqv** [comment]
It is not possible to put an example for each db and for each db version, the file is an example that you must adapt to your needs
