### ISSUE TITLE
Using Vite as a bundler in the pro docs

### ISSUE THREAD

**Issue by schonhoff** [spatie/laravel-medialibrary#2971]
Hello,

after Laravel is migrated to Vite as a standard bundler the docs needs a little bit of love. I tried different things but couldn't get the following code to work:
https://spatie.be/docs/laravel-medialibrary/v10/handling-uploads-with-media-library-pro/installation#content-using-the-css

If this isn't the right place for it feel free to move this in the discussion section :-)
Thanks for the great work!

**Comment by schonhoff** [comment]
Hello,

any updates on this? I still have trouble to use it with vite and don't know how to use the pro version on it. :-( Would love to see the docs updated or to have a working example so I can adopt my application.

Best regard!

**Comment by plakhin** [comment]
I've manage to get Media Library Pro working with vite.

1. `vite.config.js`:
```diff
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';

export default defineConfig({
    plugins: [
        laravel([
            'resources/js/app.js',
        ]),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
    ],
    resolve: {
        alias: {
            '@': '/resources/js',
+           'spatie-media-lib-pro': '/vendor/spatie/laravel-medialibrary-pro/resources/js',
        },
    },
});

```

2. `resources/js/app.js`:
```diff
import './bootstrap';
import '../css/app.css';
+import 'spatie-media-lib-pro/media-library-pro-styles/src/styles.css';
...
```

3. import in my component like this:
```js
...
import { MediaLibraryAttachment } from 'spatie-media-lib-pro/media-library-pro-vue3-attachment';
import { MediaLibraryCollection } from 'spatie-media-lib-pro/media-library-pro-vue3-collection';
...
```

**Comment by schonhoff** [comment]
Thank you so much!

Hoped for a paid product the docs would be updated more quickly. :-/

**Comment by freekmurze** [comment]
Thank you!
