### ISSUE TITLE
[Question] Using subfolder on s3 disk

### ISSUE THREAD

**Issue by mahony0** [spatie/laravel-medialibrary#298]
I didn't come across similar usage yet, but I want to use medialibrary like this way:

```php
$user->addMedia('user-image.png')->toCollectionOnDisk('avatar', 's3');

$user->addMedia('user-banner.png')->toCollectionOnDisk('banner', 's3');
```

these collections are on the same s3 bucket but need to upload to separate folders as well. It should be stored in "avatar/user-image.png" and "banner/user-banner.png". This is easy on "local" driver with "root" value, but don't know how on s3.

**Comment by freekmurze** [comment]
Perhaps a [`PathGenerator`](https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/using-a-custom-directory-structure) can help you here.

**Comment by mahony0** [comment]
Sure, thanks for help. I made it with
```php
$media->getDiskDriverName()
```
in my CustomPathGenerator
