### ISSUE TITLE
Bug introduced on PR 2992 - ordering 

### ISSUE THREAD

**Issue by rmsj** [spatie/laravel-medialibrary#2994]
Hi there.

This PR https://github.com/spatie/laravel-medialibrary/pull/2992 has introduced a bug on the `order by` clause.

Queries will look like this `select "file_name" from "media" where "media"."model_type" = ? and "media"."model_id" = ? and "media"."model_id" is not null and "collection_name" = ? order by "order_column" asc, "size" desc` when trying to order the result set with anything like `orderByDesk('size')

**Comment by freekmurze** [comment]
I've reverted the changes of that PR.
