### ISSUE TITLE
addMediaFromBase64 Not Uploading With File Extension

### ISSUE THREAD

**Issue by reasecret** [spatie/laravel-medialibrary#2996]
I'm working on Livewire with Summernote editor. I'm using this code for get images thoose added to editor.

```
        $dom = new \DomDocument();
        $dom->loadHtml($this->pageBody, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
        $pageImages = $dom->getElementsByTagName('img');

        if ($pageImages) {
            foreach ($pageImages as $k => $img) {
                $data = $img->getAttribute('src');
                $this->page->addMediaFromBase64($data)->toMediaCollection('pageImages');
            }
        }
```
The problem is, if I use like this images not uploading with original extensions. Uploading like this: `med57B7.tmp` `medEECA.tmp` 
Saving same file names to database of course.

And if I use `usingFileName(Str::random().'.jpg')`, unique file names are generating. BUT this Livewire component is **page edit** component and when I update my page, same images uploading again with different names and new database records are creating.

Is there a way to use file's original name or check that images exists on disk and database?

**Comment by patinthehat** [comment]
@reasecret Just following up on this issue - have you resolved it, or is it still ongoing? If so, would it be possible for you to provide a sample project that demonstrates the issue described? Thanks!

**Comment by reasecret** [comment]
> @reasecret Just following up on this issue - have you resolved it, or is it still ongoing? If so, would it be possible for you to provide a sample project that demonstrates the issue described? Thanks!

Sorry for delay. I've decided to use another package for this project. Nobody write anything almost since 4 months. Thanks for your interest anyway.
