### ISSUE TITLE
Base64 mime type

### ISSUE THREAD

**Issue by yemnaosman** [spatie/laravel-medialibrary#2997]
Hi!

When uploading a certain base64 docx file, we get the following error:
`The file with properties name: application-(2).docx, size: 27026, mime: application/vnd.openxmlformats-officedocument.wordprocessingml.documentapplication/vnd.openxmlformats-officedocument.wordprocessingml.document was not accepted into the collection named cv of model`

Our collection accepts application/vnd.openxmlformats-officedocument.wordprocessingml.document mime types.

When opening the file and saving it, the problem is no longer occurs and it's not with all docx base64 encoded files. We have an example if needed, but contains personal data and can't be editted because the problem is gone. So if needed I can send the file through email or whatever you prefer.

Thanks for all the awesome packages!

**Comment by patinthehat** [comment]
@yemnaosman As you mentioned that this only occurs with some files and not others, can you provide a bit more detail as to what commonalities exist between the problem files? Can you provide several sample files as well as example code that demonstrates this issue?
