### ISSUE TITLE
Using with Laravel 5.3 RC1

### ISSUE THREAD

**Issue by bstrahija** [spatie/laravel-medialibrary#300]
Is there a way to use the package with L5.3 RC1? I know it's not out yet, but I'm starting a project and would like to use 5.3 but for now the package can not be installed.

**Comment by freekmurze** [comment]
Hi,

we probably won't have time to investigate how to do this properly before the release next week at Laracon. Rest assured that this package will be one of the first that we will make L5.3 compatible as soon as L5.3 gets released officially.
