### ISSUE TITLE
PDF-to-image

### ISSUE THREAD

**Issue by a-wenzel** [spatie/laravel-medialibrary#301]
Hey,

i got after the latest updates a Problem with my Permissions. When i regenerate the files, i got errors at the PDFs

```
Media 333 could not be regenerated because `file_put_contents(pKxUs21BU1VIexia.jpg): failed to open stream: Permission denied

Media 334 could not be regenerated because `file_put_contents(ri06MFfcKYzpxt3s.jpg): failed to open stream: Permission denied

Media 335 could not be regenerated because `file_put_contents(HuhH9MpOjWHKGPNZ.jpg): failed to open stream: Permission denied

Media 336 could not be regenerated because `file_put_contents(brnAWs8ovK4PxoZ6.jpg): failed to open stream: Permission denied

Media 337 could not be regenerated because `file_put_contents(11nPzlIaaMNsuCQp.jpg): failed to open stream: Permission denied

Media 338 regenerated

Media 339 could not be regenerated because `file_put_contents(4FW90nx3ExQBeObz.jpg): failed to open stream: Permission denied

Media 340 could not be regenerated because `file_put_contents(aKo9hWZTDdZzSsAM.jpg): failed to open stream: Permission denied

Media 341 regenerated

Media 342 regenerated

Media 343 regenerated
```

That definitly worked a last updates before... How can i solve this?

Thanks

**Comment by a-wenzel** [comment]
Just for info - JPG, PNG conversions still working. Only PDFs are failing. I tryed it on two different systems... local in my VM (Homestead) and on my live system.

Im the only one with that Problem after the latest updates?

Thanks

**Comment by nicolasbeauvais** [comment]
Hi @a-wenzel, thanks for reporting this bug, I think I found the cause, can you take a quick look at the #308 PR and tell me if it fixes it for you ? 

Sorry for introducing it in the codebase :-1:

**Comment by a-wenzel** [comment]
hey @nicolasbeauvais work like a charm. Thank you very much.

**Comment by freekmurze** [comment]
Thanks @nicolasbeauvais for providing a PR. It has been merged. You can now just upgrade to `4.8.3` to fix the error.
