### ISSUE TITLE
Latest optimisation is sort order query breaks media copy for single file collections

### ISSUE THREAD

**Issue by victor-priceputu** [spatie/laravel-medialibrary#3015]
1. Create a model
2. Attach a media to the model, after registering the media collection as a single file.
3. Attach another media to the model (basically have 1 media item with order 2)
4. Move another media from another model to this one

Expected: the new media would belong to the model
Actual: the old media belongs to the model

This can be replicated with other steps as well, for example:
Have a model with 2 media items (which have order 1 and 2)
Move a media item from another model (that has the order 1)

The copied media has order 1, not 3. Biggest issue is in Single model collections.

Because copy persist the order of the media, of that order number is lower than the latest entry you have for the model, then the order of the collection is broken. When using single file collection it completely breaks the copy functionality.

Issue introduced with the optimisation in https://github.com/spatie/laravel-medialibrary/pull/2840

**Comment by freekmurze** [comment]
Could you PR a tests that proves that this is broken?

**Comment by victor-priceputu** [comment]
I will make one as soon as I can spare some time

**Comment by victor-priceputu** [comment]
PR created with the test, that is failing locally. Thank you for looking into this
