### ISSUE TITLE
Watermarks Support

### ISSUE THREAD

**Issue by threeel** [spatie/laravel-medialibrary#302]
Does the library support Watermarks on generated images?

**Comment by timgavin** [comment]
+1

**Comment by freekmurze** [comment]
I think so, via [Glide](http://glide.thephpleague.com/1.0/api/watermarks/)

You should be able to use `mark`, `markh`, `markw` and `markfit` in a [conversion](https://docs.spatie.be/laravel-medialibrary/v4/converting-images/defining-conversions).

**Comment by timgavin** [comment]
@threeel 

This adds and centers a watermark PNG to a thumbnail conversion

```
->setManipulations([
     'w' => 350,
     'fm' => 'src',
     'mark' => public_path('assets/img/watermark.png'),
     'markfit' => 'fill',
     'markpos' => 'center',
 ])
```

**Comment by freekmurze** [comment]
Thanks for providing an example @timgavin 

@threeel Reopen this issue if you can't get it to work.

**Comment by threeel** [comment]
sorry to reopen i just needed to say Thank you! i really appreciate all the work that you guys do!

**Comment by freekmurze** [comment]
❤️
