### ISSUE TITLE
Images doesn't seam to be uploaded to Google Storage Cloud

### ISSUE THREAD

**Issue by alexgomez88** [spatie/laravel-medialibrary#3038]
On the company we have a site that works with Google Storage Cloud, we tested on or Local using minio and everything works great but on production, images do not seam to be uploaded. We test with Laravel FilesystemManager directly (Storage::put, Storage::delete etc) and it works perfectly, but using Media Library it doesn't throw any error.

The project is based on:
        "laravel/framework": "^8.0",
        "spatie/laravel-medialibrary": "^9.0.0",

**Comment by PaolaRuby** [comment]
Only Laravel Medialibrary 10.x is supported

**Comment by patinthehat** [comment]
@alexgomez88 Can you provide some sample code to demonstrate that this is in fact a bug within the package itself? Thanks!

**Comment by patinthehat** [comment]
I'm closing this issue as it appears to be stale and does not present as a bug with the library itself.  Please open a new issue if this was done in error. Thank you!
