### ISSUE TITLE
Video Thumbnails are not being generated

### ISSUE THREAD

**Issue by ams-ryanolson** [spatie/laravel-medialibrary#3063]
OK, so Lets start with code

App\Models\User
   ```
 public function registerMediaConversions(Media $media = null): void
    {
        $this
            ->addMediaConversion('thumb')
            ->width(368)
            ->height(232)
            ->extractVideoFrameAtSecond(1)
            ->performOnCollections('stories')
            ->nonQueued();
    }
```
media-library.php
```
    'ffmpeg_path' => env('FFMPEG_PATH', '/usr/local/bin/ffmpeg'),
    'ffprobe_path' => env('FFPROBE_PATH', '/usr/local/bin/ffprobe'),
```
Test Route
```
Route::get('test', function() {
    $video = new \Spatie\MediaLibrary\Conversions\ImageGenerators\Video();
    echo $video->convert('demo.mov');
});
```
StoryController.php (snip)
```
$model = Auth::user();

        //if request is a video
        if($request->hasFile('video') && $request->file('video')->isValid()){
        $media = $model->addMediaFromRequest('video')
        ->toMediaCollection('stories');
        }
```
When the video is uploaded, it is added to the library successfully. The issue is no thumbnail is being generated based on the model information. When I use the test route, it does generate the thumbnail successfully. I am not sure what I am missing but after 8 hours I am starting to wonder if this is a bug or if there is more troubleshooting I can do. 

Nothing is showing up in the laravel.log, nothing is showing up on the frontend, nothing is showing up out of the ordinary in Telescope so I am at a loss.

**Comment by mertasan** [comment]
Can you add an example of the code where you use the model information?

I tried your codes and it works. Maybe I can help. But I need more examples.

**Comment by ams-ryanolson** [comment]
@mertasan I am not sure what other code you would need. I can tell you that all the code is basically there... If you can give me more specifics I can post whatever you want. 

What I can tell you is that photos works, I can tell you the video uploads. I can tell you the manual route works fully but using the registermediaconversion does not work

**Comment by ams-ryanolson** [comment]
Poke? Anyone have any further help on this?
\

**Comment by mertasan** [comment]
The conversions are queued. Are you using this command? (I'm asking to be sure.)

```
php artisan queue:listen
```

**Comment by ams-ryanolson** [comment]
I thought that but I also have ->nonQueued(); set so that should not be it... but testing now just to be sure

**Comment by ams-ryanolson** [comment]
Same thing - does not create any conversions.

**Comment by ams-ryanolson** [comment]
user model:
`public function registerAllMediaConversions(): void
    {
        $this
            ->addMediaConversion('video_thumb')
            ->extractVideoFrameAtSecond(2)
            ->performOnCollections('stories')
            ->nonQueued();

        $this
            ->addMediaConversion('preview')
            ->nonQueued();

        $this
            ->addMediaConversion('thumb_square')
            ->nonQueued();
        
        $this
            ->addMediaConversion('full')
            ->nonQueued();
    }`
    
    Controller:
    `public function store(StoreStoryRequest $request)
    {
        $model = Auth::user();
        $input = $request->all();

        //upload request to media library
        $media = $model->addMediaFromUrl('https://cdn-rkm.nyc3.digitaloceanspaces.com/' . $input['key'])
        ->withResponsiveImages()
        ->toMediaCollectionOnCloudDisk('stories');

        //create story
        $story = Story::create([
            'model_id' => auth()->user()->id,
            'model_type' => 'App\Models\User',
            'media_id' => $media->id,
            'sponsored' => false,
            'views' => 0,
        ]);

        session()->flash('flash.banner', 'Story Created!');
        session()->flash('flash.bannerStyle', 'success');

        return Redirect::route('dashboard');

    }`

**Comment by ams-ryanolson** [comment]
Bump

**Comment by patinthehat** [comment]
@ams-ryanolson Following up on this - would it be possible for you to provide a sample project/repo that demonstrates the issue occurring to allow me to determine what's happening here? Thanks!

**Comment by ams-ryanolson** [comment]
> @ams-ryanolson Following up on this - would it be possible for you to provide a sample project/repo that demonstrates the issue occurring to allow me to determine what's happening here? Thanks!

Unfortunately I chose to remove Media Library from my project as a number of people on discord and other platforms stated this was a known issue and support was lacking. I even purchased a pro license and still no support was given.

**Comment by patinthehat** [comment]
I'm closing this issue as not enough information/sample project/tests were provided.  Please open a new issue if you feel this was in error.  Thank you!
