### ISSUE TITLE
SQL error on long file names

### ISSUE THREAD

**Issue by ariaieboy** [spatie/laravel-medialibrary#3077]
I have a file with a long name and when I want to upload this file using this library it throws SQL error that the value is too large for this column :
```SQL
SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(125) (SQL: insert into "media" ("name", "file_name", "disk", "conversions_disk", "collection_name", "mime_type", "size", "custom_properties", "generated_conversions", "responsive_images", "manipulations", "model_id", "model_type", "uuid", "order_column", "updated_at", "created_at") values (31-317703_apple-logo-png-transparent-svg-vector-freebie-supply, 3aWQsEbIGqbUR3xNKYsqdZc9xAdL3V-metaMzEtMzE3NzAzX2FwcGxlLWxvZ28tcG5nLXRyYW5zcGFyZW50LXN2Zy12ZWN0b3ItZnJlZWJpZS1zdXBwbHkucG5n-.png, minio, minio, logo, image/jpeg, 15391, [], [], [], [], 25, App\Models\Manufacturer, 769c3904-41c3-462f-8262-6d71e18a2eec, 1, 2022-11-01 18:11:18, 2022-11-01 18:11:18) returning "id")
```
default file name generator must generate a name with a maximum of 125 characters length

**Comment by erikn69** [comment]
Change that on migration as you need

**Comment by ariaieboy** [comment]
> Change that on migration as you need

what if someone else uploads a file with a bigger name?

**Comment by erikn69** [comment]
https://github.com/spatie/laravel-medialibrary/blob/ff4a546bafc0ecb4c779055fa1e5850c3b8b2bfe/LICENSE.md?plain=1#L15-L16

**Comment by erikn69** [comment]
> must generate a name with a maximum of 125 characters 

If you look this package is not adding any limit, your implementation has the limit

**Comment by patinthehat** [comment]
@ariaieboy I believe this can be resolved by customizing the migration for your particular use case, and don't feel that this is a bug in the code itself. Feel free to open a new issue with sample tests that demonstrate a bug if you feel that this is in error. Thanks!
