### ISSUE TITLE
Regenerating responsive images

### ISSUE THREAD

**Issue by skulllair** [spatie/laravel-medialibrary#3086]
I'm trying to regenerate responsive images but i'm encountering the following problem:

It seems that the regenerate command only regenerates responsive images that already contain responsive images.
This means my old images don't get the responsive variants and based on the documentation of regeneration I would expect this to work.

When you dive into the code there is a simple check that prevents this from working which is:
```
if (! count($media->responsive_images)) {
    return $this;
}
```

The responsive_images array is always empty when the initial image didn't have responsive images. I'm just not sure if this is intended behaviour but based on the general description of the regeneration command in the docs I would say it isn't.

If this IS intended then this issue could be closed.

Thanks in advance.

**Comment by freekmurze** [comment]
I think it is intended because we don't assume the original would ever change.
