### ISSUE TITLE
In Laravel 5.1 uploaded file stores with temporary php name instead of original name

### ISSUE THREAD

**Issue by alexglue** [spatie/laravel-medialibrary#31]
```
		if($request->hasFile('file')){
			$model->addMedia($request->file('file'));
		}
```

```
//vendor/spatie/laravel-medialibrary/src/HasMediaTrait.php:53
$media->name = pathinfo($file, PATHINFO_FILENAME);
```

So i've got "phpCYQ7ed" (temporary php filename) instead of original uploaded file name.
Or maybe i should to store uploaded file separately *before* attach it to my model?
Don't u think it'll be better to integrate upload file moving-renaming in your package also?

**Comment by freekmurze** [comment]
You should get the client original name. Here's [https://github.com/spatie/laravel-medialibrary/issues/25#issuecomment-122830899](an example).

In a next version of the package I'll make this easier.

**Comment by ziming** [comment]
Hi @alexglue 

The way I currently handle it is this

```
// I can't find a rename method on UploadedFile class hence I used it's move method to move to the 
// same directory it is uploaded then I add to the model.
$file = $file->move('.', $file->getClientOriginalName());
$object->addMedia($file);
```

Hope it helps for the moment!

**Comment by freekmurze** [comment]
You could also rename the media after adding the file:
```php
$media = $model->addMedia($request->file('file'));
$media->name = $file->getClientOriginalName();
$media->save();
```

**Comment by ziming** [comment]
Hi @freekmurze from my own attempt earlier doing that changes the name at the database row, but not the actual file name of the document.

**Comment by freekmurze** [comment]
@ziming that's true... 

I'll add method for renaming the file soon...

**Comment by ziming** [comment]
That got me stuck for a pretty long hah. Thank you.

**Comment by freekmurze** [comment]
New in version 2.2.3: when renaming file_name on a media object, the underlying file will be renamed as well.
```php
$mediaObject->file_name = 'newFileName.jpg'
$mediaObject->save(); // This will also rename the file on the filesystem.
```

**Comment by freekmurze** [comment]
Fyi, working on allowing uploads to be passed directly to the `addMedia`-function: https://github.com/spatie/laravel-medialibrary/commit/c43e5774c46689734e4e419952ba430047c61bb5

Still have to test it probably, ...
