### ISSUE TITLE
CustomPathGenerator $media relationships don't eager load

### ISSUE THREAD

**Issue by ignacio-dev** [spatie/laravel-medialibrary#3103]
When creating a CustomPathGenerator, and getting paths like so:
```
public function getPath(Media $media): string
{
    return $media->model->dirRelativePath() . '/';
}
```

I end up with too many queries.

If I try to eager load that by using ```MyModel::with('media.model')``` I get:

```
Call to a member function dirRelativePath() on null
```

**Comment by patinthehat** [comment]
@ignacio-dev Could you provide some more context/sample code and possibly a failing unit test that demonstrates the issue? Thanks!

**Comment by erikn69** [comment]
> I end up with too many queries.

of course you do, you are seraching on db model relation each time that you call `getPath`
try to use static methods and that method doesn't call to db

**Comment by patinthehat** [comment]
I'm closing this issue as it appears to be stale and does not present as a bug with the library itself.  Please open a new issue if this was done in error. Thank you!
