### ISSUE TITLE
Avoiding duplicates

### ISSUE THREAD

**Issue by loranger** [spatie/laravel-medialibrary#311]
Hello !

I'd like to know if there's a simple way to avoid duplicate files.
I was thinking about a `hash_file` call on media adding.

If you won't consider this feature, could you lead me to the best way to extend laravel-medialibrary in order to implement it in my app ?

Best

**Comment by freekmurze** [comment]
I think you should do this in your own application.

Before adding a file, just [retrieve all the current associated media](https://docs.spatie.be/laravel-medialibrary/v4/basic-usage/retrieving-media) and verify if any of their hashes don't not match the hash of the file you're trying to add.

**Comment by loranger** [comment]
All right, thanks for the tip !
