### ISSUE TITLE
Moving media with GCS disk results in zero-byte files

### ISSUE THREAD

**Issue by boboldehampsink** [spatie/laravel-medialibrary#3110]
Hi,

When moving media with media-library and gcs adapter, the moved files are zero-bytes.

**Comment by patinthehat** [comment]
Hi @boboldehampsink, can you provide sample code that demonstrates that this is a bug within the library itself? Thanks!

**Comment by boboldehampsink** [comment]
Fixed it by just updating the media's model id with config setting `move_media_on_update` set to `true`.
