### ISSUE TITLE
Downloading large multiple files using MediaStream is not working

### ISSUE THREAD

**Issue by ahamed-kashif** [spatie/laravel-medialibrary#3126]
Downloading multiple small files in a zip as mentioned in the documentation is working good. But when I try to download large files as zipped it creates a corrupted zip

**Comment by parallels999** [comment]
Php ini, apache/nginx problem, it is not an issue from this package

**Comment by masitings** [comment]
Is there any way to solve this ?

**Comment by websitevirtuoso** [comment]
change php.init to increase time and memory limits. Better options place file zipped  to storage and download from storage not using php

**Comment by ahamed-kashif** [comment]
> change php.init to increase time and memory limits. Better options place file zipped to storage and download from storage not using php

it works. sorry for late response
