### ISSUE TITLE
No id atribute after upgrade to v. 10

### ISSUE THREAD

**Issue by beard7** [spatie/laravel-medialibrary#3127]
After upgrading to version 10, the collection of media objects no longer includes the database id.

Is there a way to get this included again? I won't bore you with the details, but I need the database id to retrieve media objects in certain scenarios.

**Comment by parallels999** [comment]
This is not an issue
Feel free to overwrite/customize eveything that you need on your implementation

**Comment by andrezanna** [comment]
@beard7 can you please explain what you did? I have the same issue.
Thanks

**Comment by beard7** [comment]
Sure. It's pretty simple.

Rather than something like: `return $record->getMedia(); `
Use:
````
$attachments = $record->getMedia();

return $attachments->toArray();
````
