### ISSUE TITLE
addFromMediaLibraryRequest() does not return instance of model

### ISSUE THREAD

**Issue by visbits** [spatie/laravel-medialibrary#3132]
Hi,  I am using MediaLibrary pro V10 and found that using addFromMediaLibraryRequest() returns null instead of the model instance of the media.

`$test = $this->category->addFromMediaLibraryRequest($this->thumbnail)->toMediaCollection('thumbnail');
dump($test);`
Returns null but the functions works correctly and the media becomes available in getMedia().

**Comment by dambridge** [comment]
Necro bump. I have this same issue  and need to get the id in order to update the media table after upload...
