### ISSUE TITLE
Custom name for withResponsiveImages on addMediaCollection

### ISSUE THREAD

**Issue by ProjectAsphaleia** [spatie/laravel-medialibrary#3148]
Hi,

I'm not sure if this is a bug, but whenever I try to add responsive images like
```php
public function registerMediaCollections(Media $media = null): void
{
    $this->addMediaCollection('banner')
        ->withResponsiveImages()
        ->singleFile();
}
```
And upload an image it will make a bunch of images like
`/storage/app/public/{id}/responsive-images/{name}___media_library_original_{width}_{height}.{extension}`.

Now I would like to change `___media_library_original_` to something else. I saw that it does work with `conversionName`.

So when you do
```php
public function registerMediaCollections(Media $media = null): void
{
    $this->addMediaCollection('banner')
        ->singleFile();

    $this->addMediaConversion('responsive')
        ->withResponsiveImages();
}
```
It will generate another `conversions` folder with a single conversion file.
But also in `/responsive-images` it will generate both the `responsive` **and** `media_library_original` files.
So you'll have duplicated files.

It it supposed to work like this ? Shouldn't it only generate the 
`/storage/app/public/{id}/responsive-images/{name}___responsive_{width}_{height}.{extension}`.
and not generate the 
`/storage/app/public/{id}/responsive-images/{name}___media_library_original_{width}_{height}.{extension}`.
anymore ?

Or what's the correct way to achieve this.

**Comment by freekmurze** [comment]
I'd accept a PR (including tests) that fixes this.
