### ISSUE TITLE
withResponsiveImages() unexpected behaviour

### ISSUE THREAD

**Issue by stuartcusackie** [spatie/laravel-medialibrary#3159]
I am having trouble with the ->withResponsiveImages() function.

If I call this function in my conversions, e.g.:
```
  public function registerMediaConversions(Media $media = null): void
  {
    $this
       ->addMediaConversion('full')
       ->format('jpg')
       ->withResponsiveImages()
       ->nonQueued();
    }
```
Then the image.blade partial is outputted. It should be outputting responsiveImageWithPlaceholder.blade

If I call this function when adding images to models, e.g.:
```
$object->addMedia(resource_path('/intro-bg.png'))
  ->withResponsiveImages()
  ->toMediaCollection();
```
Then the responsiveImageWithPlaceholder.blade partial is outtputted correctly, however, all images are in PNG format, even though my conversions define jpgs.

I am using Vue so I am converting my images to html like so:
```
$object->getFirstMedia()->toHtml());
```

Maybe I'm missing something?

**Comment by stuartcusackie** [comment]
Nevermind, I figured something out. The syntax is a little strange but this seems to work:
```
$object->getFirstMedia()('full')->toHtml()
```

**Comment by faizananwerali** [comment]
In my case

```php
Project::find(1)->getFirstMedia()('responsive')->toHtml()
```

Project Model
```php
class Project extends Model implements HasMedia
{
    use HasFactory;
    use InteractsWithMedia;
    use SoftDeletes;

    // ...

    public function registerMediaConversions(?Media $media = null): void
    {
        $this->addMediaConversion('responsive')
            ->format('webp')
            ->withResponsiveImages()
            ->nonQueued();
    }
}

```

Thanks to this conversation, otherwise it was very difficult to figure it out from the documentation.

This should be included in the documentation as well.
