### ISSUE TITLE
[Question] Replace media item in blog post?

### ISSUE THREAD

**Issue by giorgoskorakas** [spatie/laravel-medialibrary#317]
I would like to update a media item in a blog post (replaced with another one by the user).
 
I try to remove a media item from media library and add a new one with the same id. I would like to do so to retain the media order inside post. 

So i delete the previous media item [ $mediaItem->delete(); ] and then i need to upload with the previous item's id the new one (upload in the same directory as the old one).

Is this procedure possible?

Thank you in advance

**Comment by freekmurze** [comment]
Under normal circumstances you shouldn't care about the `id` of a  `Media` item. If you want to replace an item and insert a new in it's place you can do this:

1. Before deleting it keep the `order_column` value in a variable.
2. Delete the item
3. Upload a new item
4. Set the `order_column` of the new `Media` object to the one from step 1.

**Comment by giorgoskorakas** [comment]
Thank you for the reply and support!
This is a great package!
