### ISSUE TITLE
Call to undefined method Spatie\MediaLibrary\MediaCollections\Models\Media::getOriginalUrlAttribute()

### ISSUE THREAD

**Issue by joostvanhoof** [spatie/laravel-medialibrary#3173]
I'm on `10.7.10` en Laravel `9.48.0`. Recently I've been receiving the following error:

`Call to undefined method Spatie\MediaLibrary\MediaCollections\Models\Media::getOriginalUrlAttribute()`

It looks like this only happens when passing media to a blade component, because this works fine:

```php
$post = Post::findOrFail(1);

$post->getFirstMediaUrl('photo', 'large');
```

But with the same model, this throws the error:

```php
<x-header backgroundImage="{{ $post->getFirstMediaUrl('photo', 'large') }}">
```

**Comment by afariasfermin** [comment]
I ran into the same issue after updating de package from version `10.7.9` to `10.7.10`, recently try to downgrade to the previous version but the error persist.

**Comment by Kaishiyoku** [comment]
The change came from here I think: https://github.com/spatie/laravel-medialibrary/commit/7e9c1d29b223a10aa10c95d2fe4d0ea1796df6ba

**Comment by afariasfermin** [comment]
> @afariasfermin also happened to me after upgrading I think. In the `10.7.10` changes [I can't see the method being removed](https://github.com/spatie/laravel-medialibrary/compare/10.7.10...main), so not sure where this comes from.

@joostvanhoof Something that works momentarily for me is using a custom model and then just reimplementing the old-style functions in the model, just these two functions and it works perfectly

```php
public function getOriginalUrlAttribute()
{
    return $this->getUrl();
}

public function getPreviewUrlAttribute()
{
    return $this->hasGeneratedConversion('preview') ? $this->getUrl('preview') : '';
}
```

**Comment by stephenjude** [comment]
Wake up to the same issue. @afariasfermin thanks for the workaround snippets.

**Comment by afariasfermin** [comment]
> Wake up to the same issue. @afariasfermin thanks for the workaround snippets.
> 
> UPDATE: The methods are there but with the new Laravel attribute syntax. Running `composer update` on my Laravel 9 project fixed it.

For me updating livewire to `v2.11.2` fixed the problem. and the workaround with the custom model is not necessary.
