### ISSUE TITLE
Call to undefined function Spatie\\ImageOptimizer\\Optimizers\\escapeshellarg()

### ISSUE THREAD

**Issue by AbdullahKaram-Dev** [spatie/laravel-medialibrary#3178]
![image](https://user-images.githubusercontent.com/61882285/216694788-558a7eee-6947-49cf-ba4c-8ab79140a772.png)
why i faced error
i uploaded my website on shared host

**Comment by timvandijck** [comment]
@AbdullahKaram-Dev most of the time this is because your host has disabled shell related features like the `escapeshellarg()` function.
I would advice to contact your hosting partner for this.
