### ISSUE TITLE
preservingOriginal() not working as expected when using S3

### ISSUE THREAD

**Issue by helloiamlukas** [spatie/laravel-medialibrary#319]
Hey!

When I'm using S3 only, the  `preservingOriginal()` method does not work. The original file will be preserved even when I'm not using the method.

I guess the problem is within the `toCollectionOnDisk` function, as `unlink()` won't work with S3:

`
      if (! $this->preserveOriginal) {
            unlink($this->pathToFile);
        }
`

Is this on purpose or will this be fixed?

Thanks :-)

**Comment by freekmurze** [comment]
Could you add a failing test to prove that this does not work properly?
