### ISSUE TITLE
Losing images when using custom media path generator

### ISSUE THREAD

**Issue by benjam-es** [spatie/laravel-medialibrary#3190]
Using a custom path generator, I have implemented a storage structure to match a structure I was already using.

So my media is saved (in s3) as 

```[BUCKET]/media/2023/02/new-red-car.jpg```

and conversions

```[BUCKET]/media/2023/02/c/new-red-car-large.jpg```
```[BUCKET]/media/2023/02/c/new-red-car-medium.jpg```
```[BUCKET]/media/2023/02/c/new-red-car-small.jpg```

The problem here is that, due to the way the media delete observer works, it uses getPath() and getConversionPath() etc and simply removes those base folders.

The expectation would be that the ```removeAllFiles``` functionality would remove the image only, and its conversions only. 

In reality, the ```media/2023/02/``` folder is being deleted in its entirety - meaning it just wipes a month worth of other media unrelated to the item that was deleted.

**Comment by fredsal** [comment]
When you use custom path generator, you should also anticipate the customization of other methods, the library cannot predict how you are going to create custom paths

PRs are welcome, feel free to make one to fix that

**Comment by benjam-es** [comment]
I am in the middle of a pull request to the v9 branch, but that seems to have 17 failing tests. Are those straight forward to remedy?

**Comment by fredsal** [comment]
@benjam-es  because v9 is already without support, the PR must be for v10

**Comment by elrosi** [comment]
Hi, I am working on a project where there is a problem with lost attachments.

I am creating content of an comment field that can either be in form of text or as an attachment.
The content (text or attachments) can be incrementally added or attached to a saved "draft" and when the content is created the user just publishes it.
Attachments that are as a group in comments have their defined collection_name e.g. comment-15487

For saving files I use the defined directory structure: "1/2023/3/11" (Company ID / Year / Month / Day)

Function to create the directory structure:
```
function createMediaPathDirectory(int $company_id, Carbon $date): string
{
    return $company_id . DIRECTORY_SEPARATOR . $date->format('Y') . DIRECTORY_SEPARATOR . $date->format('m') . DIRECTORY_SEPARATOR . $date->format('d') . DIRECTORY_SEPARATOR;
}
```

Media storage and access work well and as expected.

However, a problem occurs when the user decides to remove one of the uploaded attachments from the draft.

The methods used to remove the attachment $media->delete(); $comment->deleteMedia($media->id); is called Observer \Spatie\MediaLibrary\MediaCollections\Models\Observers\MediaObserver::deleted which implements the method \Spatie\MediaLibrary\MediaCollections\Filesystem::removeAllFiles($media)

Deletes the entire last directory (Day), creates a new, empty directory in the root with the comment ID

If there are multiple attachments loaded during the day, this is a big problem. 

Is it possible to use Medialibrary to remove just one attachment or all attachments with the same collection_name, without $media->delete(); removing the whole directory?

Thank you for the info.

**Comment by elrosi** [comment]
If my solution would help anyone:

I created an extension of a media model
I created a SoftDelete migration and index on deleted_at comulns  
I used SoftDelete on my own Media model
I created a custom observer override as an extension of Spatie\MediaLibrary\MediaCollections\Models\Observers\MediaObserver
In the model to custom_property I have a parameter "path_directory" where I store my own directory structure.

```
/**
 * Override for MediaObserver::deleted()
 * @See \Spatie\MediaLibrary\MediaCollections\Models\Observers\MediaObserver::deleted()
 */
class MediaObserver extends BaseMediaObserver
{
    public function deleted(Media $media)
    {
        if (in_array(SoftDeletes::class, class_uses_recursive($media))) {
            if (! $media->isForceDeleting()) {
                return;
            }
        }

        $filesystem = app(Filesystem::class);

        $filesystem->removeFile($media, $media->getCustomProperty('path_directory'));
    }
}
```


```
 /**
     * Odstráni súbor, ktoré sa používateľ rozhodol vymazať z drafru.
     * It removes the file that the user decided to delete from the comment draft.
     *
     * @param Media $media
     *
     * @return void
     */
    public function removeCommentFile(Media $media): void
    {
        $fileExist = Storage::disk('public')
            ->exists($media->getCustomProperty('path_directory') . '/' . $media->file_name);

        if ($fileExist === true) {
            $deleteFile = Storage::disk('public')
                ->delete($media->getCustomProperty('path_directory') . '/' . $media->file_name);
            if ($deleteFile === true) {
                $media->forceDelete();
            }
        }
    }

```

**Comment by fredsal** [comment]
use markdown correctly for readability: ` ```php `

**Comment by benjam-es** [comment]
I have prepared a pull request to add the required functionality, whilst preserving existing functionality.

https://github.com/spatie/laravel-medialibrary/pull/3252/commits/dddcd224cd120d4e1183844e03e759c14198039f is the first commit of the pull request, adding the failing test.

The PR has notes on the rest of the solution

**Comment by freekmurze** [comment]
We'll continue this in #3252
