### ISSUE TITLE
Global reusable images library

### ISSUE THREAD

**Issue by vedmant** [spatie/laravel-medialibrary#32]
Hi, it looks like a great library, but it would be great to be able to reuse the same images in different models. So I suppose it needs many-to-many relations and but in this case it will be one single options set for images conversions for whole library... Maybe it's possible to make it as an option, something like global library. This way it will be able to create Wordpress like media library (which is I'm searching for Laravel).

**Comment by freekmurze** [comment]
Hi, what you described isn't the use case I had in mind while creating the package. As I have no need for this in my projects, I won't add this anytime soon.

You could however make your idea work by
-  when adding a file saving it against some kind of dummy eloquent model
- creating by creating a [many-to-many-polymorphic relation](http://laravel.com/docs/5.1/eloquent-relationships#many-to-many-polymorphic-relations) between the media table and your content tables.

If you're up to it, you could creating your own package for this specific use case.

**Comment by vedmant** [comment]
Thank you for your answer! I will try dummy model.

**Comment by themightysapien** [comment]
Late reply but may be this might help. 
https://github.com/themightysapien/wcmedialibrary
This is my reusable framework agnostic media library package with a ready to use api 

Dummy Model Approach with api for the cilent library modal
https://github.com/themightysapien/laravelmedialibrary
