### ISSUE TITLE
getMedia doesn't find media added beforehand

### ISSUE THREAD

**Issue by Floppy012** [spatie/laravel-medialibrary#3202]
When adding media and then directly after retrieving it using `getMedia` no media is found.

**Example:**

```php
$model->addMediaFromBase64($b64)
    ->withCustomProperties(['example' => true])
    ->toMediaCollection();

$model->getMedia()->count(); // 0
$model->getMedia(filters: ['example' => true])->count(); // 0
$model->media()->count(); // 1

// Re-fetching the model from database works
Model::first()->getMedia()->count(); // 1
```

**Comment by AtlasApollo** [comment]
Thank you @Floppy012 . I am experiencing a similar situation and your suggestion to re-fetch the model has helped!

**Comment by francoism90** [comment]
I don't know if you're using this in a job/queue/notification/, but for this reason I always use afterCommit. You can also set this to default in the config files of Laravel.
