### ISSUE TITLE
Conversion doesn't work

### ISSUE THREAD

**Issue by pyaesone17** [spatie/laravel-medialibrary#321]
I use laravel 5.3 and media-library 4.8. I can attach image to model but conversion doesn't generate.

This is the Model

```php
namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Presenters\PresentableTrait;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;

class Product extends Model implements HasMediaConversions
{
	use PresentableTrait, HasMediaTrait;

    protected $fillable = [ 
    	'name', 'price', 'description', 'quantity'
    ];

    protected $presenter = 'App\Presenters\ProductPresenter';

    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
             ->setManipulations(['w' => 368, 'h' => 232])
             ->performOnCollections('images');
        
        $this->addMediaConversion('big')
            ->setManipulations(['w' => 500, 'h' => 500]);
    }

}
```

This is implementation

<pre>      
$pathToImage  = $request->photo->store('images');
$product->addMedia(storage_path("app/".$pathToImage))->toCollection('images');
</pre>

**Comment by nicolasbeauvais** [comment]
You can directly pass the file to media library without saving it first:

```php
$product->addMedia($request->file('images'))->toCollection('images');
```

But this will not resolve your conversion issue.
Are you using a queue to perform the conversion ? If it's the case try again in sync mode it's easier to debug.

Have you tried the regenerate command `php artisan medialibrary:regenerate` ? Does it create the conversions ? 

Which kind of driver are you using to store the file ?

**Comment by pyaesone17** [comment]
php artisan medialibrary:regenerate

This doesn't regenerate conversion.

Driver : local
Queue : doesn't use.

Btw performConversions is automatic right ? I don't have to use explicit on product model ?

**Comment by nicolasbeauvais** [comment]
Yes if you use the `HasMediaConversions` trait on your model everything will be automatically performed if you define conversions.

What are the type of file you are trying to attach to your model ?

You can verify the type with an instance of your media like:

```php
$product->getFirstMedia()->type;
```

Only file with `image`,  `svg`,  `pdf` or  `video` type can have a conversion. The type is determined using the file extension or mime type.

**Comment by pyaesone17** [comment]
Yes I only attach image on my model . My image file type is jpeg, jpg .

**Comment by nicolasbeauvais** [comment]
Everything looks ok, what does your public/media directory looks like ?

Just the files like:
```
/media
  /1
    hello.jpg
  /2
    avatar.jpeg
```

or is there an empty conversions directory or something else ?

**Comment by nicolasbeauvais** [comment]
Maybe you didn't set up a proper queue worker ?

**Comment by johnhjugroup** [comment]
Change QUEUE_CONNECTION to sync

**Comment by hesammoosapour** [comment]
> I can confirm that using nonQueue can resolve this issue. I don't know what is wrong with my queue.
> 
> Yes this issue is not related with media library. It is just some config cache problem.

Yes the queue connection should be set to sync , unless in my instance I need to set it to database & configure supervisor on my ubuntu server . Thanks.

**Comment by askerakbar** [comment]
I'm too having the same issue.  it works only on 'nonQueued' conversions.
