### ISSUE TITLE
`post-s3` disregarding `TemporaryUpload::$disk`

### ISSUE THREAD

**Issue by JapSeyz** [spatie/laravel-medialibrary#3215]
The `post-s3` endpoint is pulling out the diskname from `$diskName = config('media-library.disk_name');` when deciding where to store the `TemporaryUpload`, disregarding the `public static ?string $disk = null;` attribute on the `TemporaryUpload` model.

```php
protected static function getDiskName(): string
{
    return static::$disk ?? config('media-library.disk_name');
}
```

`$temporaryUploadModelClass::getDiskName()` should be used instead.

*Use-case:*
Wanting to store the temporary previews in a separate locations with an auto-cleaning lifecycle rule in S3.

*Expected Behaviour*
Setting `TemporaryUpload::$disk = 'previews'` would make mediaLibrary use this disk for the previews

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.
