### ISSUE TITLE
HTTP 500 error when uploading (large) file

### ISSUE THREAD

**Issue by knnnrd** [spatie/laravel-medialibrary#322]
Hi, I'm trying to use a media conversion to resize the uploaded images. 

When I upload small files (around 300kB), everything works. The images are stored correctly and a conversion shows up in the media public folder. However when I try to upload a 5MB image, I get a http 500 error. 

ProjectController.php:
`$project->addMedia($request->file('cover_image'))->toCollection('cover_images');`

Project.php:
`public function registerMediaConversions() {
$this->addMediaConversion('cover_image')
        ->setManipulations(['w' => 1920, 'h' => 1080])
        ->performOnCollections('cover_images');
}`

And this is in my server config:
nginx: 
`client_max_body_size 200M;`

php:
`upload_max_filesize = 200M
post_max_size = 220M
`

If I comment out the media conversion and try to upload the 5MB file, everything works as normal.

Thanks in advance

**Comment by nicolasbeauvais** [comment]
Have you also changed the medialibrary config ?
https://github.com/spatie/laravel-medialibrary/blob/master/config/laravel-medialibrary.php#L15

**Comment by knnnrd** [comment]
Yes I have.
`'max_file_size' => 1024 * 1024 * 100,`

**Comment by freekmurze** [comment]
Have you increaded the default values for `upload_max_filesize` and `post_max_size` in your `php.ini`?

**Comment by nicolasbeauvais** [comment]
Also there can be several php.ini files (like differents one for running php in the cli and under nginx)

You can use the `locate` command to find them on linux:

```bash
$ locate php.ini

/etc/php/7.0/cli/php.ini
/etc/php/7.0/fpm/php.ini
```

**Comment by freekmurze** [comment]
Or use `php --ini` 😄

**Comment by knnnrd** [comment]
This is a screenshot of what my `phpinfo()` outputs. These values should be sufficient?
![image](https://cloud.githubusercontent.com/assets/5852381/18329034/043672b2-7552-11e6-9294-f4f047ce1fb6.png)

**Comment by knnnrd** [comment]
Solved it, I had to increase this in my php.ini to something bigger.
`memory_limit=128M`
