### ISSUE TITLE
Using storage_path() and public_path() in docs

### ISSUE THREAD

**Issue by Numline1** [spatie/laravel-medialibrary#323]
Hi. I was just curious about the usage of storage_path and public_path methods in laravel-medialibrary docs on website, within documentation (both 3 and 4).

It's specified in the last step of the installation, when adding a disk into disks array in filesystems.php, this should be used:

`'root'   => public_path().'/media',`

However, Laravel (at least 5.2 and 5.3) do support this:

`'root'   => public_path('media'),`

which seems slightly cleaner and leaner to me, unless there's a specific reason to use your version (both seem to return the exact same output). It's not really an issue, nor is it causing any problems, it was just bothering me on OCD level :). Thanks!

**Comment by freekmurze** [comment]
The second option is slightly cleaner yes. I'd accept PRs on the docs that change this. 

(There's an edit button on every page of the docs to easily send in a PR)
