### ISSUE TITLE
Missing Method Definitions in HasMedia Interface

### ISSUE THREAD

**Issue by sixpeteunder** [spatie/laravel-medialibrary#3230]
Hey there!

First of all, great library! I have just noticed a mismatch between the methods available via the `HasMedia` interface, and those in `IntereactsWithMedia`:

### InteractsWithMedia
![InteractsWithMedia](https://user-images.githubusercontent.com/26766955/229308306-107685aa-bb82-4ef3-b4bf-36bf3a707a24.png)

### HasMedia
![HasMedia](https://user-images.githubusercontent.com/26766955/229308280-1cecdb3d-b118-45be-9e98-04bd87d7d014.png)

This makes it very hard to write code like below, without having static analysis tools complain.

```php
function add(Model&HasMedia $model, string $path):void
{
    $model->addMediaFromDisk($path);
}
```

**Comment by freekmurze** [comment]
Feel free to PR non-breaking improvements.
