### ISSUE TITLE
Strange behaviour of LocalUrlGenerator (v3)

### ISSUE THREAD

**Issue by ionut-tanasa** [spatie/laravel-medialibrary#324]
Hi,
I'm using a Capistrano style deployment strategy where I have a shared folder. The media folder is symlinked to the shared directory after each deploy.

When I try calling `getUrl` I throws `UrlCouldNotBeDetermined('The storage path is not part of the public path')`.

Debugging a bit I saw that `$this->getStoragePath()` returns `/home/deploy/dash/backend/staging/shared/public/media/attachments` but `public_path()` returns `/home/deploy/dash/backend/staging/releases/20160908095809/public` so when you check if `!string($this->getStoragePath())->startsWith(public_path())` it returns `true`.

In the `filesystems.php` I have configured a new local disk like this:

```php
'attachments'  => [
            'driver' => 'local',
            'root'   => public_path() . '/media/attachments',
        ],
```

And conversions like this: 

```php
    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumbnail')->setManipulations([
            'w' => 200,
            'h' => 200
        ])->performOnCollections('attachments');

        $this->addMediaConversion('large')->setManipulations(['w' => 1000])->performOnCollections('attachments');
    }
```

The version I'm using is `3.18.0` since it's a legacy app and I'm stuck with PHP 5.6.

What am I doing wrong here?

**Comment by ionut-tanasa** [comment]
Worked around it using a custom UrlGenerator.

**Comment by LKDevelopment** [comment]
@freekmurze i have suddenly the same issue with Version 4.8.3 and Laravel 5.3.6.

**Comment by ionut-tanasa** [comment]
Re-opening just to clarify :) 

My solution was to add a custom UrlGenerator and kinda hard code the piece of path based on the deployment one. Not very happy about it, but hey I needed it fast.

**Comment by LKDevelopment** [comment]
I doesnt debug this right now but it seems to be an issue with an Update on the filesystems component of laravel
