### ISSUE TITLE
Can't install the package in fresh Laravel project

### ISSUE THREAD

**Issue by timoransky** [spatie/laravel-medialibrary#3244]
Hi,

there seems to be an issue with the composer dependencies.
I created a new Laravel project with Sail and when I try to require this package a get the following error:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15653065/232737243-790feddb-b674-4612-b213-a1f16aeb46e6.png">

Apparently `maennchen/zipstream-php` requires `psr/http-message ^1.0` but that package is locked on 2.0 in Laravel. Is this resolvable on my side, your side, or their side? 😅

Thanks for any help!

**Comment by angeljqv** [comment]
`composer require "spatie/laravel-medialibrary" -W `

**Comment by timoransky** [comment]
Yes, I know this is a workaround, but is it recommended way?

**Comment by vesper8** [comment]
As of today the package remains uninstalable on Laravel 8 without the `--with-all-dependencies` flag.

**Comment by angeljqv** [comment]
I'm using laravel 8.x without problems, just
`composer require "spatie/laravel-medialibrary" -W`

**Comment by vesper8** [comment]
Yes that's what the `-W` flag is, it's the same as `--with-all-dependencies`

It indeed works with this workaround. But the fix that was merged 2 weeks ago does not make it installable on Laravel 8 without using the `-W` workaround
