### ISSUE TITLE
Class "Spatie\MailcoachEditor\Models\Upload" not found when running regenerate

### ISSUE THREAD

**Issue by joostvanhoof** [spatie/laravel-medialibrary#3279]
When I run `media-library:regenerate --only-missing` I get:

```
In ConversionCollection.php line 56:
Class "Spatie\MailcoachEditor\Models\Upload" not found
```

PHP: `8.1.13`
Laravel: `9.52.7`
MediaLibrary: `10.9.3`

**Comment by Nielsvanpach** [comment]
Fixed in release [10.9.4](https://github.com/spatie/laravel-medialibrary/releases/tag/10.9.4)
