### ISSUE TITLE
fclose() is missing in DefaultDownloader.php

### ISSUE THREAD

**Issue by NickSB** [spatie/laravel-medialibrary#3280]
hello,

We have found a rare bug.

In src/Downloaders/DefaultDownloader.php line 17 fopen() is used, but never a fclose(). According to PHP documentation you should always use a fclose.

We used this library in a project to import over 10'000 files with addMediaFromUrl().

Without fclose() the target server was overwhelmed, because it had hundreds of open requests active at the same time.

After we added fclose($stream) after file_put_contents(), the large import was no longer a problem.

The problem only occurs with bulk import.

Greetings
Nick

**Comment by Nielsvanpach** [comment]
Fixed in release [10.9.4](https://github.com/spatie/laravel-medialibrary/releases/tag/10.9.4)
