### ISSUE TITLE
Directory deleted after upload file s3

### ISSUE THREAD

**Issue by LucaMino** [spatie/laravel-medialibrary#3285]
When I try to upload a file from s3 directory to another s3 directory using custom path. I see that the new directory has been deleted after it has been generated all the images.

This's a snippet from my code using laravel media library v. 10 and php v. 8.1. 

`$category->addMediaFromDisk($category_path, 's3')->preservingOriginal()->toMediaCollection('image');`
                    
Thank you

**Comment by elmudometal** [comment]
i think this is related to this #3252
