### ISSUE TITLE
Again PDF to Image

### ISSUE THREAD

**Issue by a-wenzel** [spatie/laravel-medialibrary#330]
Hey guys,

i got the same issue again [Issue301](https://github.com/spatie/laravel-medialibrary/issues/301) - conversions of jpegs work but again not pdf to image.
!
[image](https://cloud.githubusercontent.com/assets/7287128/18468857/18d1865a-79a6-11e6-93e4-5b0f788bc986.png)

i tried it on 5.2 and 5.3

Thanks

**Comment by nicolasbeauvais** [comment]
The `4.8.3` version that has been created to fix this bug (#301) is the last release of the package.

Which version are you using ?

**Comment by a-wenzel** [comment]
Hey @nicolasbeauvais 

i use the latest version (4.8.3)

`
protected function convertPdfToImage(string $pdfFile) : string
    {
        $imageFile = pathinfo($pdfFile, PATHINFO_DIRNAME).'/'.pathinfo($pdfFile, PATHINFO_FILENAME).'.jpg';

        (new Pdf($pdfFile))->saveImage($imageFile);

        return $imageFile;
    }
`

**Comment by nicolasbeauvais** [comment]
Can you print the result of this method ? It return the converted file path:

```php
protected function convertPdfToImage(string $pdfFile) : string
{
    $imageFile = pathinfo($pdfFile, PATHINFO_DIRNAME).'/'.pathinfo($pdfFile, PATHINFO_FILENAME).'.jpg';

    (new Pdf($pdfFile))->saveImage($imageFile);

    dd($imageFile);
    return $imageFile;
}
```

If the file path looks correct verify that you have the correct permission on the directory.

**Comment by nicolasbeauvais** [comment]
The correct path for performing conversion should be like `storage/medialibrary/temp/*`

**Comment by a-wenzel** [comment]
Silly question but how can i fire the dd($imageFile)? If i upload any PDF i didnt get any dd output.

btw. the permissions couldnt be wrong when jpegs still gets conversions right?

**Comment by nicolasbeauvais** [comment]
The process for converting jpeg and (pdf/svg/video) are differents,

to convert a pdf we first extract an image representation of the pdf file using the `convertPdfToImage` method (that we don't need for a jpeg file which is already an image file) and after we perform the conversion on that extracted file.

I can see two reason for you not seeing the  `dd` output, either you are using a queue to process the conversion so the dump will be async and you will not see it, or medialibrary fail to recognize your file as a PDF, if the library does not recognize the file type, no conversions are performed.

**Comment by a-wenzel** [comment]
mhm... i tried svg now same as pdf... so which permission could be wrong? the funny thing.. on my live system it works! Only in my homestead local not...

**Comment by a-wenzel** [comment]
@nicolasbeauvais im so sorry... that was 100% my fault... i got a new PC and forgot to install imagick in my VM... rly sorry for that!
