### ISSUE TITLE
UploadedFile mime type is ignored and wrong mime type used

### ISSUE THREAD

**Issue by aprokopenko** [spatie/laravel-medialibrary#3310]
I found very weird behavior, which affect my application in a very bad way.

I have upload of the certificate files. (.pem, .crt, .cer). During the upload $_FILES array and UploadedFile objects has correct mime type inside (`application/x-x509-ca-cert`). However, when I save this to DB I get `text/plain`. After that all work with this file happen as "text/plain" and I can't add validation for the the extension or mime type, because they are set as "text/plain" and "txt" once the model is saved.
(I have a dropzone, and then on form submit I validate the file format by the Media model entry).

This happen, because in FileAdder mime type is defined by the **temporary uploaded path** (e.g. `/tmp/phph9AXhL`), which doesn't have even an extension (because that's how PHP save temporary $_FILES objects). And this make it to define it as "text/plain", instead of just taking this info from UploadedFile object:
https://github.com/spatie/laravel-medialibrary/blob/10.10.1/src/MediaCollections/FileAdder.php#L324

Could you explain the reason it's done like this? I can make a Pull Request if you suggest what is the best way to workaround this? 

My suggestion would be is to modify setFile() method and set additional class property $this->mimeType when $file is object and this info can be taken from this object. And then use $this->mimeType and File::mimeType() as fallback only.
https://github.com/spatie/laravel-medialibrary/blob/10.10.1/src/MediaCollections/FileAdder.php#L104

**Comment by aprokopenko** [comment]
Same thing happen when you "move()" media. It creates a temporary file, and then take mime type from it.

**Comment by freekmurze** [comment]
> My suggestion would be is to modify setFile() method and set additional class property $this->mimeType when $file is object and this info can be taken from this object. And then use $this->mimeType and File::mimeType() as fallback only.

Send a non-breaking PR to do just that.
