### ISSUE TITLE
Timeout after update to 10.10.2

### ISSUE THREAD

**Issue by labomatik** [spatie/laravel-medialibrary#3323]
After updating our code base to laravel-medialibrary v 10.10.2 we encountered timeout on our system (leading to 502 Bad Gateway), after narrowing down the problem we identified this commit:
https://github.com/spatie/laravel-medialibrary/pull/3319/commits/7cf8e7b440ac3c14e3f46558ea3f1785e53291f1

After commenting on the changes in line 553 the issue was resolved.

It seems again linked to serialization.

**Comment by freekmurze** [comment]
I'll tag a release in a few moments where this problem will be fixed. My apologies for the inconvenience.
