### ISSUE TITLE
Connection timeout after upgrading to new version

### ISSUE THREAD

**Issue by socieboy** [spatie/laravel-medialibrary#3324]
Not sure how this change impacted my app, but i notice that after this change 

https://github.com/spatie/laravel-medialibrary/commit/8a00a55ebbf6afc8c1f01c09bb3ee91f67a7f567

My app started taking so much time to load causing a timeout error. I had to lock the version of the package to 10.10.1 to keep the app working.

**Comment by keatliang2005** [comment]
I encounter the same issue too. as describe in https://github.com/spatie/laravel-medialibrary/pull/3319#issuecomment-1649172869

so far 2 possible workaround 

1. downgrade to 10.10.1
2. override `loadMedia()` method which is not pretty

**Comment by freekmurze** [comment]
I'll tag a release in a few moments where this problem will be fixed. My apologies for the inconvenience.
