### ISSUE TITLE
remove Intervention/image as dependencies

### ISSUE THREAD

**Issue by ariaieboy** [spatie/laravel-medialibrary#3338]
Right now, this package uses https://github.com/Intervention/image.
That package has not been updated for a year and has some issues. 

One of the issues I encountered is this missing peace of code https://github.com/Intervention/image/pull/1216/files that prevents using the GD driver to decode AVIF files. 

There is more than 347 open issue and 37 Open PR. 

I think it's a good idea to port the code to spatie/image or another package and stop using that library.

**Comment by freekmurze** [comment]
You're right, I've removed it.

**Comment by rcerljenko** [comment]
It didn't actually do anything because it's still required by `league/glide` package which, in turn, is required by the `spatie/image`...

**Comment by freekmurze** [comment]
Changing this now is a lot of work. I'd accept a PR that implements the necessary changes in spatie/image, so we can leave league/glide behind. But yeah, it's a lot of work.

**Comment by ariaieboy** [comment]
Someone needs to talk to https://github.com/Intervention organization and ask them to maintain the project or transfer it to someone else so the package gets updated.
Maintaining an open-source project is not easy and cheap, but this package is trendy, downloaded more than 2 million times a month, and deserves more resources.
