### ISSUE TITLE
jsonSerialize must be compatible with illuminate

### ISSUE THREAD

**Issue by Madlyaza** [spatie/laravel-medialibrary#3346]
When using laravel medialibrary 10.11.x we are getting this error but only on the server not on local dev environment. 

Symfony\Component\ErrorHandler\Error\FatalError: Declaration of Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection::jsonSerialize() must be compatible with Illuminate\Support\Collection::jsonSerialize(): array in file /var/www/vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Collections/MediaCollection.php on line 51 #0 {main}

**Comment by parallels999** [comment]
Fixed on https://github.com/spatie/laravel-medialibrary/pull/2756
