### ISSUE TITLE
Media library pro  2.7.3 - Error on 

### ISSUE THREAD

**Issue by OpJePl44tsm4n** [spatie/laravel-medialibrary#3375]
Sorry, don't know where to post issues for Pro, don't have acces to the repo. 

I updated to laravel 10 and livewire 3, got an error when rendering the uploads element. 

```
An alias (uploadErroredTrait) was defined for method uploadErrored(), but this method does not exist
vendor/spatie/laravel-medialibrary-pro/src/Http/Livewire/LivewireUploaderComponent.php : 12
```

suggested fix change function name from 'uploadErrored' to '_uploadErrored': 
```
use WithFileUploads {
        _uploadErrored as protected uploadErroredTrait;
 }
```

**Comment by kasirye** [comment]
Same problem:  

An alias (uploadErroredTrait) was defined for method uploadErrored(), but this method does not exist

 laravel 10 and livewire 3

**Comment by V3ct0rek** [comment]
I got the same problem, is there any way to solve it or we need to wait for some fix?

**Comment by OpJePl44tsm4n** [comment]
They just announced a release of pro today for laravel 10 and livewire 3 😁

**Comment by freekmurze** [comment]
Meanwhile a Livewire 3 compatible release is available.
