### ISSUE TITLE
moves_media_on_update doesn't work on S3.

### ISSUE THREAD

**Issue by hailwood** [spatie/laravel-medialibrary#3386]
As mentioned in [this comment](https://github.com/spatie/laravel-medialibrary/pull/2219#issuecomment-748297161) on #2219 there's an issue when enabling the `moves_media_on_update` option when using S3 as your backend.

It attempts to move the entire containing "directory", which S3 doesn't allow due to there being no real concept of a directory.

We need to either consider why we're trying to move the entire directory instead of just the source media file and just move the source file if that's all that's required.. or if it's intentional then we need to look at moving the files within the directory one by one.

**Comment by freekmurze** [comment]
If there's a way to move an entire directory at once, we should do that. 

But I don't think that's possible with Flysystem, so I believe the way to go is to move individual files. 

I'm open for a PR around this 👍
