### ISSUE TITLE
Spatie Media Library Pro Component Returning Invalid UUID When Saving

### ISSUE THREAD

**Issue by FireOpsPhil** [spatie/laravel-medialibrary#3412]
I have a Laravel project where I extensively use Spatie Media Library Pro.  But I have recently come into an odd issue that I cannot see to figure out what is wrong.

A have a model called “Preplans”.  It has the Spatie Media Library component on both the create and edit page for the model.  I first noticed the issue when I tried to add an image to the model from the edit page when no previous image existed.    The issue I saw was that is just completely skipped over adding the image with no error message.  

So then I created a new record and attached an image.  It uploaded fine to project.  It appears in the “media” table as expected.

But then I went to edit the record.  The edit page loads as expected, populating all the form fields correctly. It also shows the previously uploaded image within the Spatie Media Library component embeeded in the edit page.  When I try to save the edits without modifying the image at all,  all of the form fields get saved, but when it comes time to process the image, it throws and exception error that says”**invalid uuid”.** Nothing more.  The Laravel logs records the error as:

```
invalid uuid {"userId":1,"exception":"[object] (Exception(code: 0): invalid uuid at /Users/philiphayes/Library/CloudStorage/Dropbox/Projects/fireops/vendor/spatie/laravel-medialibrary-pro/src/Dto/PendingMediaItem.php:41)
```

So clearly I have an issue with the component on the edit page.  I have the exact same set up in other areas of the project that work fine with the same edit component (but using different keys).

Here is what my edit component looks like on the edit blade page:

```
<x-media-library-collection
                                name="image"
                                :model="$user"
                                collection="profile"
                                max-items="20"
                                rules="mimes:png,jpeg,jpg"
                           
                                />
```

This is what my method looks like in the controller:

```
public function update(Request $request, Preplan $preplan)
    {
        
        $formFields = $request->validate([
            'addr_number' => ['required'],
            'addr_street'  => ['required'],
            ....
            'occ_warn'  => ['nullable'],
            'tags'  => ['nullable'],
            'pub_date'  => ['nullable', 'date']
            
        ]);
      

        if (!empty($request->pub_date)) {
            $formFields['pub_date'] = Carbon::parse($request->post_date)->format('Y-m-d H:i');
        } else {
            $formFields['pub_date'] = null;
        }
       
        $preplan->update($formFields);

        $preplan->syncFromMediaLibraryRequest($request->images)
        ->toMediaCollection('building_picts');
      
    
        return redirect()->route('preplans.index')->with('message', 'The Preplan updated successfully!');;
    }
```

The model is set up like all the other places:

```
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;

class Preplan extends Model implements HasMedia

use InteractsWithMedia;

...

public function registerMediaCollections(): void
    {
        $this
            ->addMediaCollection('building_picts');
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')
            ->width(368)
            ->height(232)
            ->sharpen(10);

        $this->addMediaConversion('preview')
            ->crop('crop-center', 400, 400); // Trim or crop the image to the center for specified width and height.

    }
....
```

The UUID that is stored in the database looks fine.  You can see the UUID in this screenshot of a sample image that was uploaded

https://app.screencast.com/VmzvrokcTlWcS

When I dd the request in the controlled, the UUID appears just as it does in the database.

I am really stumped on what is going on.  I almost feel like something got corrupted somewhere as I do not see a programming error.  Like I said, I use the exact same code in many places across the project.

Thanks in advance,

**Comment by FireOpsPhil** [comment]
I will have to dig through my notes. I don't remember offhand. I'll get back to you.

**Comment by AllCdnBoy** [comment]
yeah, I get that too.  I have always assumed that it was maybe just clicking upload too fast?  It always happens to my staff and never me, so I haven't been able to reproduce it

**Comment by AVAPEAK** [comment]
Came across this same issue, uploading any media would return "invalid uuid".

I found that it was caused by trying to save the media twice to different collections, which I assume is causing it to remove the UUID on the second sync, producing the error.

---

We originally had a single image upload to the "images" collection:
```
if(isset($col['media'])) {
    $contentColumn->syncFromMediaLibraryRequest($col['media'])->toMediaCollection('images');
}
```
Then moved on to having different media to be displayed for Mobile / Desktop, so changed the code to:
```
if(isset($col['images_all'])) {
    $contentColumn->syncFromMediaLibraryRequest($col['images_all'])->toMediaCollection('images');
}
if(isset($col['images_desktop'])) {
    $contentColumn->syncFromMediaLibraryRequest($col['images_desktop'])->toMediaCollection('desktop');
}
if(isset($col['images_mobile'])) {
    $contentColumn->syncFromMediaLibraryRequest($col['images_mobile'])->toMediaCollection('mobile');
}
```
However some columns were still using the the old "media / images" setup, so we added the original line back in with the new:
```
if(isset($col['images_all'])) {
    $contentColumn->syncFromMediaLibraryRequest($col['images_all'])->toMediaCollection('images');
}
if(isset($col['images_desktop'])) {
    $contentColumn->syncFromMediaLibraryRequest($col['images_desktop'])->toMediaCollection('desktop');
}
if(isset($col['images_mobile'])) {
    $contentColumn->syncFromMediaLibraryRequest($col['images_mobile'])->toMediaCollection('mobile');
}
if(isset($col['media'])) {
    $contentColumn->syncFromMediaLibraryRequest($col['media'])->toMediaCollection('images');
}
```
This is what caused the UUID error - It was originally saving the media from the images_all, images_desktop, images_mobile collections and then still trying to save the normal images collection ($col['media'] was still being set)

I split the $col['media'] sync into an if statement for this particular column type and it now works.
