### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by benjam-es** [spatie/laravel-medialibrary#3417]
In this file: 

``https://github.com/spatie/laravel-medialibrary/blob/main/tests/Feature/FileAdder/IntegrationTest.php``

it appears to be running the test against a live URL.

``https://orbit.brightbox.com/v1/acc-jqzwj/Marquis-Leisure/reviews/images/000/000/898/original/Antar%C3%A8sThumb.jpg``

which is broken

**Comment by freekmurze** [comment]
Fixed on `main`.
