### ISSUE TITLE
Before adding media to it, you should first save the App\Model

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-medialibrary#343]
Like the title states, I am trying to upload a media item without a model, I know this is not the way to go but sometimes I just want to add media so I can use these for example in a long content blog post when its not created yet.

My code:

```
    public function addMedia(Request $request)
    {
        $page = new Project;

        $file = $page->addMedia($request->file('file'))->toCollection('project');

        return [
            'url' => $file->getUrl()
        ];
    }
```

Error:
```
FileCannotBeAdded in FileCannotBeAdded.php line 44:
Before adding media to it, you should first save the App\Models\Project-model
```

I know this is new since the latest updates, because I do the *exact* same thing in a laravel 5.2 project, and this just works fine. (Although you have to modify the migration aswel):

`$table->morphs('model');` to -> 

```
$table->integer('model_id')->nullable();
$table->string('model_type')->nullable();
```

**Comment by sebastiandedeyne** [comment]
Hmm I don't really agree that this is the way to go. If the model would be nullable, you'd end up with a lot of useless media files that need to get cleaned up manually.

In our projects we handle this issue the other way around, by adding a 'draft' status to the project, so we're always dealing with an existing model.

**Comment by Cannonb4ll** [comment]
Yes, like I said I am not sure if this is the way to go, but I solved this in my other project using a MediaController which shows all the media and is filterable (on nulled model types and such).

So your suggestion is whenever a user wants to create a new model, you create a 'draft' model in the create method and this way you bind the images?

**Comment by sebastiandedeyne** [comment]
Yeah, and we do a cleanup of draft models older than a certain amount of time with a scheduled command.

The main advantage of using draft models instead of allowing media that isn't attached to a model is that draft models work for any relationship you want to attach to the model, so you don't have to modify any other code.

**Comment by dvkhang** [comment]
- dasddad

dsadadasd

- dasdad[ ] dasdasdas

- [ das] as

- [dsdsada]
