### ISSUE TITLE
Customizing exception messages

### ISSUE THREAD

**Issue by sudomabider** [spatie/laravel-medialibrary#345]
Hey thanks for the great package!

I'm dealing with a foreign language here. It'd be really helpful to let the users know what exactly goes wrong. Can we allow overriding the exception messages somewhere? These are currently hardcoded in `FileCannotBeAdded`

__Edit:__ Just in case this gets confusing for others, `FileCannotBeAdded` currently can be thrown in 7 different cases each with a different error message.

**Comment by nicolasbeauvais** [comment]
Maybe you can use the built-in [Laravel Exception Handler](https://laravel.com/docs/5.3/errors#the-exception-handler) to override the error message.

Or use the [Service container](https://laravel.com/docs/5.3/container#binding-basics) to swap the exception with your own implementation.

**Comment by sudomabider** [comment]
@nicolasbeauvais thanks for the reply.

I did briefly think about using Laravel's owner handler. I don't see how it can be done without doing string/regex matches to check the type of error though, since they're all the same exception only with a different error message. I can catch it...but then it gets quite ugly.

`FileCannotBeAdded` is called statically from `FileAdder`. Not sure how it's possible to swap out that. Best I can do is use my own implementation for `FileAdder` which _is_ resolved via the container. But even then it has kind of the same problem. Would have to copy and paste 3 methods to override the exception messages because again...a try catch doesn't tell you which error it is. It's probably what I'll end up doing though unless there's a better way.

**Comment by nicolasbeauvais** [comment]
Not ideal but it can be a temporary solution:

```php
/**
* Render an exception into an HTTP response.
*/
public function render($request, Exception $e)
{
    if ($e instanceof FileCannotBeAdded) {
        // Get your other locale text
        $otherLocale = trans('errors/filecannotbeadded.' . $e->getTrace()[0]['function']);
    }
}
```

`$e->getTrace()[0]['function']` will give you which method of the `FileCannotBeAdded` class is called, so you can have a lang file like this:

```php
return [
    'unknownType' => 'other language traduction',
    'fileIsTooBig' => 'other language traduction',
    'fileDoesNotExist' => 'other language traduction',
    'unreachableUrl' => 'other language traduction',
    ...
];
```

**Comment by sudomabider** [comment]
@nicolasbeauvais haha that's so hacky and brilliant at the same time. I'll keep the trick in mind :)
