### ISSUE TITLE
[11.0.0] Saving svg in mediacollection with conversions throws exception (while it created .jpg conversions in <11.0.0)

### ISSUE THREAD

**Issue by yinx** [spatie/laravel-medialibrary#3458]
After upgrading to 11.0.0 we noticed that uploading svg's now throws an error when trying to create a conversion.
This behaviour is different from previous versions where instead a .jpg conversions would be created from the .svg.

I've looked into the source and it seems this has to do with the changes made to the spatie/image package in the GdDriver's `save` function on line 127 where an error is thrown when the extension doesn't match jpg, jpeg, png, gif or webp.

A possible fix for this could be to just add 'svg' to the switch statement, but I'm not knowledgeable enough about the inner workings of the package to make such a change comfortably, this is why I opted to report the issue here.

Thanks for taking a look at this.

**Comment by freekmurze** [comment]
We'll try to get to this soon, but if you want it fast, we're open for a PR.
