### ISSUE TITLE
[11.x] Incorrect PDF conversion results when used with GD driver

### ISSUE THREAD

**Issue by kduma** [spatie/laravel-medialibrary#3475]
Continuation of #3465.

With following configuration in [User.php](https://github.com/kduma-archive/test-laravel-medialibrary-failing-pdf/blob/b11b6afd2844de11a85c3682774a098245133099/app/Models/User.php#L20-L26) model:
```php
public function registerMediaConversions(Media $media = null): void
{
    $this->addMediaConversion('preview')
        ->fit(Fit::Crop, 300, 300)
        ->format('png')
        ->nonQueued();
}
```

Given the following test case: [ExampleTest.php](https://github.com/kduma-archive/test-laravel-medialibrary-failing-pdf/blob/3f91954f91721a77ed6321bcd84d53ac881d4aed/tests/Feature/ExampleTest.php#L17-L30)
```php
$user = \App\Models\User::factory()
    ->create();

$user
    ->addMedia(resource_path('dummy.pdf'))
    ->preservingOriginal()
    ->toMediaCollection();

$path = $user->getFirstMediaPath(conversionName: 'preview');

[$width, $height] = getimagesize($path);

$this->assertEquals(300, $width, 'The width of the conversion is not 300px.');
$this->assertEquals(300, $height, 'The height of the conversion is not 300px.');
```

The generated conversion is incorrect. Here are results from failed assertions:
```
1) The width of the conversion is not 300px.
Failed asserting that 1190 matches expected 300.
Expected :300
Actual   :1190

2) The height of the conversion is not 300px.
Failed asserting that 1684 matches expected 300.
Expected :300
Actual   :1684
```

Repository with test app: [kduma-archive/test-laravel-medialibrary-failing-pdf](https://github.com/kduma-archive/test-laravel-medialibrary-failing-pdf)

**Comment by freekmurze** [comment]
Let me know when #3476 can be reviewed.

Thanks for you work on this.

**Comment by kduma** [comment]
> Let me know when #3476 can be reviewed.
> 
> Thanks for you work on this.

@freekmurze Looks that [spatie/image#221](https://github.com/spatie/image/pull/221) PR fixes this.
