### ISSUE TITLE
repo About links to old version of docs

### ISSUE THREAD

**Issue by drbyte** [spatie/laravel-medialibrary#3486]
Hi Freek,

The link in this repo's "About" section is pointing to v10 of the docs, instead of the current v11:

![Screen Shot 2023-12-26 at 6 43 09 PM](https://github.com/spatie/laravel-medialibrary/assets/404472/41ab9b8b-8d2f-4644-a95c-34c627680f28)

**Comment by freekmurze** [comment]
Thanks for reporting, fixed 👍
