### ISSUE TITLE
S3 temporary file upload driver only supports single file uploads. Remove the [multiple] HTML attribute from your input tag.

### ISSUE THREAD

**Issue by truthytech** [spatie/laravel-medialibrary#3493]
PHP 8.2.9
Media Library 11.0.3
Media Library Pro 4.0.0 (Livewire 3 component)

I am using Cloudflare R2, an S3-compatible disk.

I removed the multiple attribute as instructed and could upload a single file, which was indeed uploaded to Cloudflare.
However, when editing a product for example, I would like to upload a second image, which throws the "S3 temporary file upload driver only supports single file uploads. Remove the [multiple] HTML attribute from your input tag." error.

Does that mean that you can only ever upload a single image? I would assume that you could upload one at a time.
How would you be able to upload multiple images to R2 (an S3-compatible disk) using the Livewire 3 component?

**Comment by timvandijck** [comment]
> Unfortunately because we use the Livewire upload mechanisms for our Livewire component, we are bound to the limitation they have at the moment.

https://github.com/livewire/livewire/discussions/4569
