### ISSUE TITLE
Livewire 3 Max validation not working

### ISSUE THREAD

**Issue by QualityCodeSA** [spatie/laravel-medialibrary#3495]
Ad per doc I apply the 'images' => 'required|max:1', validation and I upload mutiple image and save form to validation working fine. After I upload one image and save it. Edit form in click on delete icon to remove existing image and upload new image then after save it to two image upload one existing and one new image. 

https://spatie.be/docs/laravel-medialibrary/v11/handling-uploads-with-media-library-pro/handling-uploads-with-livewire-3#content-validating-the-collection

**Comment by truthytech** [comment]
https://github.com/spatie/laravel-medialibrary/issues/3494 might have sorted this out
