### ISSUE TITLE
Quality for webp not working

### ISSUE THREAD

**Issue by projct1** [spatie/laravel-medialibrary#3498]
```php
public function registerMediaCollections(): void
{
    $this
        ->addMediaConversion('')
        ->format('webp')
        ->quality(20);
}
```
Trying set quality 20/100/800/etc, but file size and visual quality image are not changing :"(

**Comment by projct1** [comment]
By the way, just checked, for jpg too.

**Comment by timvandijck** [comment]
This will be fixed in an upcoming spatie/image release later this week.
