### ISSUE TITLE
Error with abstract method

### ISSUE THREAD

**Issue by VictorOtavio** [spatie/laravel-medialibrary#35]
I implemented the interface and trait to Laravel default User model and receive the following fatal error: 
Class App\Models\User contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Spatie\MediaLibrary\HasMedia::registerMediaConversions).

**Comment by brunogaspar** [comment]
https://github.com/spatie/laravel-medialibrary#avoiding-an-empty-registration-function

**Comment by VictorOtavio** [comment]
This solved my issue. Thanks.
