### ISSUE TITLE
Broken link in UPGRADING,md, no instructions available for how to update conversions to new syntax.

### ISSUE THREAD

**Issue by SlyDave** [spatie/laravel-medialibrary#3560]
From UPGRADING.md:

> Image v3 is now used. Make sure to update your image conversions to the new syntax. See [the image docs](https://spatie.be/docs/image/v3) for more info.

The link returns a 404.

There is no UPGRADING.md in https://github.com/spatie/image 

What is the new syntax?, how does one migrate from image v2 to image v3?

**Comment by SlyDave** [comment]
Found upgrade instructions under docs/ folder - https://github.com/spatie/image/blob/main/docs/upgrading.md

Link still broken, but at least I know how what to do :)

**Comment by freekmurze** [comment]
We'll fix this soon.
