### ISSUE TITLE
php 8.3.4 + laravel-medialibrary 11.4.5:  opcache+jit error: Only arrays and Traversables can be unpacked

### ISSUE THREAD

**Issue by izica** [spatie/laravel-medialibrary#3568]
After turning on opcache+jit, after some time an error occurs:
`/var/www/backend/vendor/spatie/laravel-medialibrary/src/InteractsWithMedia.php:607`
`Only arrays and Traversables can be unpacked`
```php
        $preparedMediaConversions = collect($this->mediaConversions)
            ->each(fn (Conversion $conversion) => $conversion->performOnCollections($mediaCollection->name))
            ->values()
            ->toArray();

->     $this->mediaConversions = [...$actualMediaConversions, ...$preparedMediaConversions];
    });
    $this->registerMediaConversions($media);
}
```

this only happens after some time(5+ mins of requests), when opcache+jit is enabled
in logs 
$actualMediaConversions === false (only after opcache+jit)

Code and settings:
```
zend_extension=opcache.so
opcache.enable=1
opcache.enable_cli=1
opcache.jit_buffer_size=100M
opcache.jit=1235
```

```php
class Compilation extends BaseCompilation implements HasMedia
{
    use InteractsWithMedia;

    const IMAGE = 'image';

    protected $hidden = [
        self::CREATED_AT,
        self::UPDATED_AT,
        'pivot'
    ];

    protected $fillable = [
        self::NAME,
        self::SLUG,
        self::IMAGE,
        self::AT_HEADER,
    ];

    protected $with = [
        'media'
    ];

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection(self::IMAGE)
            ->singleFile()
            ->useFallbackUrl(
                \Storage::disk(config('disks.assets'))->url('images/dummy.png')
            )
            ->registerMediaConversions(function () {
                $this->addMediaConversion('resized')
                    ->width(400)
                    ->height(400);
            });
    }
}

```

**Comment by izica** [comment]
```php
            $this->mediaConversions = [
                ...(is_array($actualMediaConversions) ? $actualMediaConversions : []),
                ...(is_array($preparedMediaConversions) ? $preparedMediaConversions : []),
            ];
 ``` 
Sometimes when opcache+jit is enabled, somehow `$actualMediaConversions` or `$preparedMediaConversions` are `false`, not array.
I inherited this trait and overridden method with a quick fix.
Perhaps this is happening because I am using methods `getRegisteredMediaCollections` and `getMediaCollection` in custom attributes, and this registers the collections on every call `$this->registerMediaCollections();`

**Comment by timvandijck** [comment]
Looks hard to reproduce: if anyone is also experiencing this let us know, I'm wondering how many users it's impacting.

I would be happy to accept a PR if something can be improved on our side.

**Comment by sethphillips** [comment]
Im running into this while adding
`->withManipulations([
                    'avatar' => [
                        'manualCrop' => "custom props here",
                    ],
                ])`
during the adding of media to a single file collection with a registered media conversion

**Comment by jamieconnor** [comment]
Actually, I'm having this error when I try to apply manipulations to Media on S3 whether it is one media item or multiple that I am trying to apply the manipulations to.
Spatie Media Library 11.11.0
PHP 8.2 and 8.3
`$photo->manipulations = [
    '*' => ['orientation' => 90],
];
$photo->save();`

It looks like it is a happening with spreading the $parameters?
`public function apply(ImageDriver $image): void

    {

        foreach ($this->manipulations as $manipulationName => $parameters) {

            $parameters = $this->transformParameters($manipulationName, $parameters);

            $image->$manipulationName(...$parameters);

        }

    }`

**Comment by aotearoait** [comment]
I am having the same issue using with the filament form addon. When I save i get the Only arrays and traversable can be unpacked, but it still uploads and saves the image.

` Section::make('Asset Images')
                // ->visible(fn($record, $livewire) => isset($record->id) && $record instanceof Asset && !$livewire instanceof EditJob)
                ->schema(fn($record) => $record instanceof Asset ? [
                    SpatieMediaLibraryFileUpload::make('asset_media')
                        ->acceptedFileTypes(['image/jpeg', 'image/png', 'image/gif', 'image/webp'])
                        ->maxSize(25000)
                        ->image()
                        ->openable()
                        ->maxFiles(10)
                        ->placeholder('Add Asset Images by Drag and Drop or Tap Here')
                        ->collection('asset_images')
                        ->multiple()
                        ->deletable(fn() => auth()->check() && auth()->user()->isStaff())
                        ->disk('s3')
                        ->manipulations([
                            'thumb' => ['orientation' => '90'],
                        ])
                        ->conversion('thumb')
                        ->panelLayout('grid')
                ] : [])
                ->columns(3)`

`public function registerMediaConversions(Media|null $media = null): void
    {
        $this
            ->addMediaConversion('preview')
            ->fit(Fit::Contain, 700, 700)
            ->nonQueued();

        $this
            ->addMediaConversion('thumbnail')
            ->fit(Fit::Contain, 300, 300)
            ->nonQueued();
    }`

**Comment by jamieconnor** [comment]
Right, sorry, did you figure it out?
The documentation is a bit wrong since Enums have started to be used for the transformations.

If your registerMediaConversions is on the Model then that should work they way you have it, but the top part has the transformations in the wrong format

`->manipulations([ 'thumb' => ['orientation' => '90'], ])`
should be
`->manipulations([ 'thumb' => ['orientation' => ['orientation' => '90']], ])`

The reason is the Enum needs to be named to go into the manipulations column. I created a pull request #3678 with some updates but it doesn't look like it's been merged.
