### ISSUE TITLE
Upload and create media model instance at the same time

### ISSUE THREAD

**Issue by vhinmanansala** [spatie/laravel-medialibrary#358]
Upon reading the documentation. It seems to me a model instance should already be existing before you can associate it to any image. 

`$newsItem = News::find(1);
$newsItem->addMedia($pathToFile)
         ->toMediaLibrary();`

Currently, I have a media model I've created and I'm trying to upload an image and create an instance of media model but get stuck on it:

`$media = new Media();`
`$media->addMediaFromUrl($url)->toMediaLibrary();`

**Comment by freekmurze** [comment]
In normal circumstances you should have to manually create an instance of `Media`.

You must first instanciate and save a model of your own, eg `BlogPost`.

```php
$blogPost = new Blogpost();
$blogPost->save();

// or you could have done BlogPost::create();

$blogPost
   ->addMedia($pathToFile) 
   ->toMediaLibrary();
```
