### ISSUE TITLE
Error when using withManipulations in combination with enumerations

### ISSUE THREAD

**Issue by tkempf** [spatie/laravel-medialibrary#3582]
When adding media with medialibrary v11 using withManipulations, the BackedEnum BorderType gets transformed to its scalar string value before calling the manipulation itself. 
This leads to the following type error:
 Spatie\Image\Image::border(): Argument #2 ($type) must be of type Spatie\Image\Enums\BorderType, string given

The code used is as follows:
`
    $this->addMedia($params->favicon->file)
        ->preservingOriginal()
        ->withManipulations([
            'bgrectangle' => [
                'background' => ['color'=>$favIconbgcolor],
                'border' =>  ['width' => $bordersize,'type' => BorderType::Expand, 'color'=>$bordercolor]
            ]
        ])
        ->toMediaCollection('favicon');
`

**Comment by freekmurze** [comment]
It's accept a PR that fixes this.

**Comment by tkempf** [comment]
Ok, the problem occurs on FileAdder.php line 331 during
    $media->manipulations = $this->manipulations;
the manipulation get cast to an array as requested in Models/Media.php on Line 74
    protected $casts = [
        'manipulations' => 'array',
        'custom_properties' => 'array',
        'generated_conversions' => 'array',
        'responsive_images' => 'array',
    ];

As for now, neither do i know the internals of media-libray nor, how you could change that cast to leave the enums alone, i don't feel capable of fixing it the right way ...
For my purpose i just need a border, so i made it work for me now by recreating the Enum in Conversions/Manipulations 53

    public function apply(ImageDriver $image): void
    {
        foreach ($this->manipulations as $manipulationName => $parameters) {
            switch($manipulationName){
                case 'border':
                    $parameters['type'] = BorderType::from($parameters['type']);
                    break;
            }
            $image->$manipulationName(...$parameters);
        }
    }

pls. don't get me wrong, it's not that i'm not willing to provide a PR, but this is no code, i would dare to offer as such!
Alas perhaps someone who has a better knwoledge of media-libary or functionality of custom casts in laravel can use this as entrance point to fix this error.
