### ISSUE TITLE
Changing file_name doesn't sync file on disk

### ISSUE THREAD

**Issue by michele-grifa** [spatie/laravel-medialibrary#3587]
I want to edit the file_name of a media, but after save, the file on the filesystem, doesn't sync and have the old name.

```php
$media = Media::find($id);
$media->file_name = $name;
$media->name = $name;
$media->save();
```

Laravel Version: 9.52.16
Spatie Version: 10.15.0

**Comment by timvandijck** [comment]
This is expected behaviour. In your code sample you are retrieving the Eloquent model and updating it in the database, no file is touched when doing it like this.

If you want to update the file on disk you will need to do this yourself.
