### ISSUE TITLE
"The storage path is not part of the public path"

### ISSUE THREAD

**Issue by adumskis** [spatie/laravel-medialibrary#360]
Hello,

I found that madialibrary can't be fully used with envoyer.io. On server all user uploaded files are saved in public/upload, but public/upload is symlink to parent storage folder. So I get error:
"The storage path is not part of the public path"

Upload path (symlink location):
/var/www/html/project/releases/20160928072515/public/upload

Real upload path:
/var/www/html/project/storage/app/public/upload

Problem is realpath() on return in LocalUrlGenerator.php:

```
protected function getStoragePath()
{
        $diskRootPath = $this->config->get('filesystems.disks.'.$this->media->disk.'.root');

        return realpath($diskRootPath);
}
```

**Comment by freekmurze** [comment]
You could create your own UrlGenerator by extending the provided `LocalUrlGenerator` and overriding the `getStoragePath` function.

Don't forget to specify your that custom UrlGenerator in the config.

More info: https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/generating-custom-urls#generating-custom-urls
