### ISSUE TITLE
issue with singlefile()

### ISSUE THREAD

**Issue by satis-m** [spatie/laravel-medialibrary#3616]
i am registering my model for single file like this

public function registerMediaCollections(): void
{
$this->addMediaCollection('blog-main-pictures')
->acceptsMimeTypes(['image/jpeg', 'image/svg+xml', 'image/png', 'image/webp'])
->singleFile();
}
when I update the picture it does not remove old one and adds new image.
I found out that it keeps adding more image to collection instead,
(NOTE: I am not using the any queue and I migrated from V 9 )

![image](https://github.com/spatie/laravel-medialibrary/assets/9709981/9fc33dee-c893-493e-9d0e-b8a3c845a00c)

**Comment by satis-m** [comment]
sorry there was issue from my end , extreamly sorry

**Comment by AmineZCS** [comment]
@satis-m can you tell me how did you solve that ? I'm facing the same issue but only when updating multiple media collections for the same model
