### ISSUE TITLE
Feature request: add media in place or use symbolic link.

### ISSUE THREAD

**Issue by anchepiece** [spatie/laravel-medialibrary#362]
Just looking through the library and I was wondering if there is a clean way to addMedia to a model without actually moving/copying the file itself.

I could see it working like this: 
```
    // HasMediaTrait
    public function linkMedia($file)
    {
        return $this->addMedia($file)->symbolicOriginal();
    }
```
```
    // FileAdder
    protected $symbolicOriginal = false;
    public function symbolicOriginal()
    {
        $this->symbolicOriginal = true;
        return $this;
    }
    public function toCollectionOnDisk(string $collectionName = 'default', string $diskName = '')
    {
        //...snip
        if ($this->symbolicOriginal != true) {
            $this->filesystem->add($this->pathToFile, $media, $this->fileName);
        }
        //...
    }
```
```
    // in FileSystem, this is what gets jumped over.
    public function add(string $file, Media $media, string $targetFileName = '')
    {
        $this->copyToMediaLibrary($file, $media, false, $targetFileName);

        event(new MediaHasBeenAdded($media));

        app(FileManipulator::class)->createDerivedFiles($media);
    }
```
It would need to be tied into the FileSystem class to skip the file manipulations while still allowing events to fire and the creation of derived files.

**Comment by freekmurze** [comment]
Hi,

because I think the majority of users of this package (myself included) do not need this functionality, I'd probably not implement this functionality.  I don't want to add complexity to the package caused by less common use cases. I hope you understand this.

If you need this, fork the package and make your modifications there.

**Comment by anchepiece** [comment]
Agreed. It certainly would cause complications and possibly have unintended effects.
