### ISSUE TITLE
Call to undefined method App\SpatieUrlGenerator::getPath()

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#365]
I'm receiving the following error when adding a video using Media Library 4.8 and Laravel 5.3.17

```
local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: 
Call to undefined method App\SpatieUrlGenerator::getPath() 
in /Users/tim/Sites/myapp.com/vendor/spatie/laravel-medialibrary/src/Media.php:86
```

The media is added and persisted in the db; on the surface everything seems to work okay, but that error is filling my logs up and I don't know how to fix it. Oh, and the error is exiting my method, so I can't delete the local file after moving it to a cloud server.

Here's the code I'm using
```
$hash = str_random(16);
$filename = $hash.'.'.$request->file('file')->getClientOriginalExtension();
$file = request()->file('file')->storeAs('uploads', $filename);

$post->addMedia(storage_path('app/uploads/'.$filename))
        ->withCustomProperties(['visability' => 'video'])
        ->preservingOriginal()
        ->toCollection('video');
```

**Comment by nicolasbeauvais** [comment]
I cannot replicate the bug using the `4.8.0` version of the package.

We changed a big part of the code that handles video, can you try with the latest `4.9.2` version ? If you can't for some reason please give me the complete version you are using so I can try to replicate the error.

In the meantime, I saw some improvements that can be made to your code (If I understood your sample correctly), you can let Medialibrary handle the upload of the file to your machine or to a cloud server, this will slim a part of your code as you will not have to store then erase the file by yourself.

This will look like this ([this link can also help you to send the file on the required cloud storage](https://docs.spatie.be/laravel-medialibrary/v3/advanced-usage/working-with-multiple-filesystems):

```php
$post->addMedia($request->file('file'))
         ->usingFileName(str_random(16).'.'.$request->file('file')->getClientOriginalExtension())
         ->toCollection('video');
```

**Comment by timgavin** [comment]
Thanks for that example, it worked perfectly.

I upgraded to the latest Media Library and am still having the problem. I *think* the issue I'm having is that I'm using the media library for images (works well - no error messages), which are stored locally, and for videos, which are not stored locally. So, inside `config/laravel-medialibrary.php` I'm calling custom classes to generate my URLs and paths.

```
/*
 * When urls to files get generated this class will be called. Leave empty
 * if your files are stored locally above the site root or on s3.
 */
'custom_url_generator_class' => App\SpatieUrlGenerator::class,

/*
 * The class that contains the strategy for determining a media file's path.
 */
'custom_path_generator_class' => App\SpatiePathGenerator::class,
```

The docblock says to leave `custom_url_generator_class` blank if not storing locally. Could this be the problem?

**Comment by nicolasbeauvais** [comment]
I never used a custom URL/Path generator with medialibrary, maybe @freekmurze can have more insight on this ?

**Comment by freekmurze** [comment]
When looking at [this piece of code](https://github.com/spatie/laravel-medialibrary/blob/master/src/Media.php#L86) it seems that an `UrlGenerator` should have a `getPath` method.

This is obviously something that is not coded well. I'll have to put in some thought on how to fix this well without breaking changes.

The quickest solution for should be to just at that `getPath` method an return the full path to the file.

**Comment by timgavin** [comment]
@freekmurze I don't understand what you mean by this: "The quickest solution for should be to just at that getPath method an return the full path to the file."

**Comment by freekmurze** [comment]
@timgavin corrected all the typos. I meant: "The quickest solution for your problem is to just add that `getPath` method yourself. It should return the full path to the file."

**Comment by timgavin** [comment]
Yep, works. No error messages. Thanks. :)

```
public function getPath()
{
    return $this->getPathRelativeToRoot();
}
```
