### ISSUE TITLE
Memory exhausted options

### ISSUE THREAD

**Issue by patrickomeara** [spatie/laravel-medialibrary#3669]
I have around 700_000 media rows and whenever I run the regenerate command it just hits the memory limit straight away.

I have written my own regenerate command that uses a lazy collection that works well, however I assume others are hitting memory limits as well.

I would like to propose a solution:
* Allow MediaRepository to be swapped out via config
* Ship a LazyMediaRepository that user can opt-in to

Does anyone at Spatie or any users have any feedback, objections or other ideas before I start hacking on this?

**Comment by freekmurze** [comment]
Handled with #3670
