### ISSUE TITLE
Horizon - some conversions instantly mark as completed

### ISSUE THREAD

**Issue by chrispage1** [spatie/laravel-medialibrary#3677]
Hi,

I'm running into a bit of an issue where some conversions seem to be instantly marked as completed without the generations actually being made.

There is also no error reporting as to what the problem might be, simply the job is completed.

I'm using Laravel Horizon to run the jobs. Has anyone experienced this issue before or know what might cause an early completion without an error log?

Chris.

**Comment by royduin** [comment]
For reference: https://github.com/spatie/laravel-medialibrary/issues/3672 which was converted to a discussion: https://github.com/spatie/laravel-medialibrary/discussions/3674

**Comment by chrispage1** [comment]
Closing as this has been resolved with #3687
