### ISSUE TITLE
Uploads to wrong directory

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#368]
@nicolasbeauvais I thought I'd open this up to ask a question about the code you posted in [#365](https://github.com/spatie/laravel-medialibrary/issues/365).

```
$post->addMedia($request->file('file'))
     ->usingFileName(str_random(16).'.'.$request->file('file')->getClientOriginalExtension())
     ->toCollection('video');
```

I've been having too many issues with the Media Library when trying to upload, and it could be because I just don't understand it well enough.

I want to add the video to the medial library, unfortunately, every time I do the video is uploaded into the `media` directory instead of the `uploads` directory.

#### config/laravel-medialibrary.php
```
'defaultFilesystem' => 'media'
```

#### config.filesystem.php
```
'media' => [
    'driver' => 'local',
    'root' => storage_path('app/media'),
],

'video' => [
    'driver' => 'local',
    'root' => storage_path('app/uploads'),
],
```

No matter what I do, the file is uploaded into `media` instead of `uploads`. I need it to go into `uploads` so that I can keep track of it.

Or is there any way to just add the info to the `media` table without having the pass the file? Some way of manually adding the filename, collection name, etc?

**Comment by nicolasbeauvais** [comment]
Collections and media disks are two different things.

medialibrary collections are used like "categories" of files and are abstracted of the disks where they are stored.

For example, I have a User entity, my users can have one avatar and a photo gallery of their last holidays. I want all files stored on the default media disk.

```php
// Add the user avatar
$user->addMedia($request->file('avatar'))->toCollection('avatar');

// Add the user gallery images
foreach ($request->file('galery_files') as $key => $file) {
    $user->addMedia($file)->toCollection('gallery');
}
```

Now the media attached to my user are separated in 2 different collections so I can easily query my user avatar or only the media in its gallery or both.

Medialibrary use a default disk to store all the files, but you can pass the second parameter to `toCollection` to store a specific file on a different disk, let's say I want my avatar in the uploads directory but not my galleries I just have to do:

```php
// Will store the file with the avatar collection but on the video disk.
$user->addMedia($request->file('avatar'))->toCollection('avatar', 'video');
```

**Comment by timgavin** [comment]
Thank you fro the explanation - it's clearer now.

What's confusing to me though is that I only want to add the item to the collection, but leaving off the second parameter means that Media Library will actually move the file to the default disk. I don't want that, I **only** want to add the file to the collection - not manipulate or move it.

See, the problem that I have is that I need to SFTP the file to my server and in order to do that I (believe) I need to use the SFTP package included in FlySystem, as I haven't been able to SFTP with the default Laravel FileSystem. I haven't been able to successfully upload a file using Media Library and FlySystem either, so I have to do it in two steps: upload with FlySystem, then add to collection using Media Library.

```
$hash = str_random(16);
$filename = $hash.'.'.$request->file('file')->getClientOriginalExtension();

$contents = fopen(request()->file('file'), 'r+');
Flysystem::connection('sftp')->put($hash.'/'.$filename, $contents);

$post->addMedia($request->file('file'))
    ->usingFileName($filename)
    ->toCollection('video', 'video');
```

This isn't desirable, but it's the only thing I can get to work so far.

Isn't there a way to just add the file to the collection without moving it? Or, better yet, is there a way to SFTP the file to my Forge server using Media Library?

**Comment by nicolasbeauvais** [comment]
So you have 2 servers provisioned by Forge, one with the laravel code and one where files must be stored ? is that correct ?

Because once your project on production on your server, when a user upload a file, if you use the default medialibrary configuration the file will be stored on the forge server where the code is hosted.

**Comment by timgavin** [comment]
I have two Forge servers: one for the app and one for encoding video. I upload the file through the app and then send it to the encoding server to be encoded, then stored using DigitalOcean block storage.

**Comment by nicolasbeauvais** [comment]
I never used a different filesystem than the default one or S3 so I don't really know how to help you on this one :/

**Comment by timgavin** [comment]
I'm using LaravelCollectives SSH package and it's working well. Thanks. :)
