### ISSUE TITLE
Palette image not supported by webp

### ISSUE THREAD

**Issue by nezocks** [spatie/laravel-medialibrary#3706]
Converting from PNG to WebP with a "big" conversion doesn't work on the API part, but it seems to work fine on the web. Here is the conversion code:
`$this->addMediaConversion('big')
    ->performOnCollections('images')
    ->format('webp');`

Here's the error code:
`imagewebp(): Palette image not supported by webp {"exception":"[object] (ErrorException(code: 0): imagewebp(): Palette image not supported by webp at /home/forge/{domain}/vendor/spatie/image/src/Drivers/Gd/GdDriver.php:166)`

**Comment by GhostvOne** [comment]
Same here, with this image 
![image psd](https://github.com/user-attachments/assets/30e94ae4-641e-433e-93c7-c299cc77c7bf)

**Comment by timvandijck** [comment]
Hey guys, thank you for the input, the issue should be fixed in the latest verstion of the spatie/image package (which this package depends on):

https://github.com/spatie/image/releases/tag/3.7.4
