### ISSUE TITLE
Storing file path without file on disk

### ISSUE THREAD

**Issue by azcoppen** [spatie/laravel-medialibrary#372]
Trying this bad boy out, as it looks really handy. I store the file path of an image or doc, and then link to it more flexibly without Storage(). When i use addMedia($pathToFile), an exception is caused when the file doesn't exist on disk. 

Is it possible to bypass this and just add the file path without a disk/exists check?

**Comment by nicolasbeauvais** [comment]
Medialibrary is not meant to work with unexisting files.

But I think something like this could work:

```php
$media = new \Spatie\MediaLibrary\Media();

$media->model_id = $model->id;
$media->model_type = get_class($model);
$media->name = 'name';
$media->file_name = 'file name';
$media->save();
```

But I would not recommend using something like this.

**Comment by azcoppen** [comment]
Thanks for clarifying. I'm having to work with legacy code that has a pre-existing database and tonnes of folders that needs to be imported onto Azure. Future file uploads will be handled that way, but i've had to do as you suggested for historical data. Thanks for a great package!
