### ISSUE TITLE
Check for file's existence

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#374]
I'm adding media and not using a queue.

1. A user creates a post and adds an image.
2. The controller redirects to the user's feed.
3. The post is visible but the image is not (shows broken image icon), because the conversions haven't finished.

What's the best way to check if the file exists and to use a fallback?

Is there a method in the Media Library that will check this? Or do I need to use something like `file_exists(storage_path('/path/to/file.jpg'))`?

Sorry for the questions, but the spatie.be site is down right now so I can't check the docs.

**Comment by nicolasbeauvais** [comment]
I do not remember any functionality in medialibrary to check for this, on a production website where file are converted using a queue I have a small javascript code that checks for the image existence and put a loading icon while the image is not converted yet.

**Comment by timgavin** [comment]
OK, thanks.

For anybody else who might need this, I've created a simple function to check if a conversion exists, and if not to show the full-size upload

```
function getImage($image, $size) {
    if(file_exists(storage_path('app/media/'.$image->getPath($size)))) {
        return $image->getUrl($size);
    }

    return $image->getUrl();
}
```

use like

```
<img src="{{ getImage($image, 'md') }}" alt="">
```
