### ISSUE TITLE
Imagemagick?

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#375]
How can I change the Glide driver to user imagemagick?

**Comment by nicolasbeauvais** [comment]
Medialibrary uses https://github.com/spatie/laravel-glide as a dependency to interact with glide. To change the glide driver follow the `laravel-glide` readme instruction:

1. add the `Spatie\Glide\GlideServiceProvider::class` provider in your app.php
2. execute the `PHP artisan vendor:publish --provider="Spatie\Glide\GlideServiceProvider"` command to get the glide config file and change GD to Imagick

**Comment by timgavin** [comment]
Works perfectly. Thanks!

**Comment by taliptako** [comment]
Why cant we set this from media library config ?
There is a image_driver config which we can set gd or imagick but its not working.GD working always..
