### ISSUE TITLE
Is there any way to push to collection image data.

### ISSUE THREAD

**Issue by nejtr0n** [spatie/laravel-medialibrary#376]
I have collection of "HasMedia" objects. (over 1k).
It makes 1k DB requests when I'm walking through it.
Is there any way to push media data to collection before getting it (Some lazy loading).
I want to retriew it throug Media model request and push it to collection manually.

**Comment by freekmurze** [comment]
I'm not sure that I understand what you want to do. Could you post some code that you're using with some comments explaining your issue?

**Comment by nejtr0n** [comment]
I will try to explain.
```
$products =  $this->section->products($this->city)
            ->orderBy('products.sort', 'asc')
            ->get();
```
This will return 1k object of Product eloquent models with HasMedia trait.
Now im trying to walk throug it template and show image. 
And everu model make request to get image from db.

Instead of it I'm getting all images in one go:
```
$sub = $this->section->products($this->city)->select('products.id');
$images = Media::where('collection_name', 'products')
            ->where('model_type', ProductModel::class)
            ->join(DB::raw('('.$sub->toSql().') as products'), 'products.id', '=', 'media.model_id')
            ->addBinding($sub->getBindings(), 'join')
            ->orderBy('model_id', 'asc');
```
It is single query and It is faster.
And now i need to push image to collection in HasMedia object, but there is no such method =(
Do you know any way to solve my problem?
(May be it should be some decorator before taking images from DB in HasMedia trait).

**Comment by freekmurze** [comment]
What do you mean with "I need to push image to collection in HasMedia object"? Can you post some code that you would expect to work?

**Comment by nicolasbeauvais** [comment]
You can easily eager load media using `with`:

```php
 $this->section->products($this->city)->with('media')
            ->orderBy('products.sort', 'asc')
            ->get();
```

**Comment by nejtr0n** [comment]
Hm... it was so simple. Thank you!
