### ISSUE TITLE
Return vallues on deleteMedia

### ISSUE THREAD

**Issue by vool** [spatie/laravel-medialibrary#379]
hello,

Just wondering if there should be return values for success/failure on deleteMedia (and similar calls).

if you think it is a good idea I can have a look into it.

Keith

**Comment by freekmurze** [comment]
I don't think a return value for `deleteMedia` is necessary. If it fails it'll throw an exception which is the right behaviour in my book. 

In which other calls would you add a return value?

**Comment by vool** [comment]
Hi Freek, 
Yes that make sense.
Thanks
