### ISSUE TITLE
Can you upgrade Glide to 0.3.*

### ISSUE THREAD

**Issue by cve** [spatie/laravel-medialibrary#38]
Hi,

the new Glide has a fit called fill, which I need, can you upgrade a composer.json to require new Glide?

**Comment by freekmurze** [comment]
This package requires version 2.2.4 of `spatie/laravel-glide`. That package required version 0.3.* of Glide. So I think you should already could use fill.

**Comment by cve** [comment]
You are right, thanks :) and sorry for that stupid mistake :)

**Comment by freekmurze** [comment]
No problem! Have fun using the package.

**Comment by cve** [comment]
Unfortunately there is no fill mode in 0.3.5 version of Glide, but I see it in master... What we can do with it?

**Comment by freekmurze** [comment]
If you see functionality in master-branch that isn't available in latest released version, than probably the maintainer is still working on the code. You'll have to wait for the stable release (or use dev-master packages in your project, which I personally don't recommend)

**Comment by cve** [comment]
It will be nice if in medialibrary we could define custom conversions with intervention, is there any plan to do so?

**Comment by freekmurze** [comment]
Could you give an example of what your want to accomplish? 

Could a [medialibrary conversion](https://github.com/spatie/laravel-medialibrary#defining-conversions) help you?

**Comment by cve** [comment]
We want to have ability to resize the image to exact width and height but without croping, this functionality is implemented in http://glide.thephpleague.com/1.0/api/size/#fit-fit with fill fit mode in Glide, but its very simple to implement in pure Intervention library with:

````
$newImage = $imageManager->canvas(100, 100);
$resized = $image->resize(100, 100); <--- this is resized with ratio, so not always 100 x 100
$result = $newImage->insert($resized, 'center'); <--- place optimal rezied image on the canvas which always has 100, 100
````

 But with medialibrary or glide there is no posibility to define this custom manipulation

**Comment by freekmurze** [comment]
The [Glide documentation](http://glide.thephpleague.com/1.0/) states that 1.0 in still being developed. Once it gets released, I'll make sure to update my package. Meanwhile, you could perform your resize before adding the image to the medialibrary.

**Comment by cve** [comment]
Ok, I can resize the image before adding to medialibrary, but how to reference it later with getUrl('conversion') and getFirstMediaUrl('conversion') ?

**Comment by freekmurze** [comment]
A possible strategy is to put those files in their own collection:
```php
$yourModel->setMedia($pathToPreConvertedImage)->toCollection('thumbs');
```

**Comment by apt-develop** [comment]
Hi, is Glide going to be upgraded to make sure of fill? Thanks.

**Comment by freekmurze** [comment]
I'm planning on releasing a new major version of the medialibrary that'll make use of Glide 1.0 in the coming months
