### ISSUE TITLE
Make S3 connection testable

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-medialibrary#381]
@nicolasbeauvais 

I've setup an S3 bucket and added it's credentials to travis:

![screen shot 2016-10-22 at 14 36 07](https://cloud.githubusercontent.com/assets/483853/19619350/475e883c-9865-11e6-8265-40624aaeb748.jpg)

With those credentials you can only read write to the bucket specified in `S3_BUCKET_NAME`.

If I understand Travis' documentation on the subject correctly the variables will only be available when running tests on commits and merges originating from our own repo. So if somebody else sends a PR the variable isn't available during the tests of that PR (and that's a good thing, because otherwise you could just echo out the variable and see it in the travis log).

Let me know when you're ready with the S3 test, so I can test this out. If it works correctly I will investigate how your PRs can get access to these variables. Maybe I'll just add you as a collaborator on this repo.

**Comment by nicolasbeauvais** [comment]
What is the region of the bucket ? `eu-west-1` ?

**Comment by nicolasbeauvais** [comment]
To perform the tests I need `flysystem-aws-s3-v3` which require `flysystem-aws-s3-v3` which require `guzzlehttp/guzzle  ^5.3 || ^6.0.1` but `scrutinizer/ocular` already require `guzzlehttp/guzzle 3`, and there is no more recent version of `scrutinizer/ocular`  :/

I saw on https://scrutinizer-ci.com/g/spatie/laravel-medialibrary/ that the code coverage is not enabled, but there is this line in travis.yml:

```yaml
after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
```

Some light on this ?

**Comment by freekmurze** [comment]
I've added `S3_BUCKET_REGION` with the right region value.

You may just remove `scrutinizer/ocular`. I believe it isn't needed anymore.

**Comment by freekmurze** [comment]
I've added you as a collaborator on this repo. I hope in this way your PRs will have access to the travis environment variables as well.

Because you're now a collaborator (you're the first one ever on any of our public repo's, congrats 😄 ) you can now approve PRs and tag releases as well. Unless it's a simple bugfix could you always consult me or @sebastiandedeyne  before merging changes or tagging releases?

**Comment by nicolasbeauvais** [comment]
test doesn't pass  :/ `ErrorException: file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known`

any clue on this ? Is it because Travis can't read the file on S3 ? or maybe S3 need a specific header on the request like at least a user agent or something ?

I'm really happy about being a collaborator on the repo :heart: And sure I will probably start by just using my new rights to help you with issues, will see later for managing PR, tag etc.. if that's ok :)

**Comment by freekmurze** [comment]
I've pushed a fix for the S3 test. It's running now. Fingers crossed! 😬

**Comment by freekmurze** [comment]
It seems to work 🎉 

But maybe we should try to make the files uniquely named per run. Travis runs the testsuite multiple times at the same time (php 7.0, 71, ...). Right now I think we're getting lucky that those test are not performed at exactly the right time.

**Comment by nicolasbeauvais** [comment]
That and also only delete file created by this instance test suite to avoid that the php 7.0 test delete the media being tested in the 7.1 test, I add this to my todo list

**Comment by arubacao** [comment]
You could alternatively use https://minio.io/ or https://github.com/scality/S3 or any other S3 compatible services with Travis.
