### ISSUE TITLE
Delete row but leave media

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#383]
I tried using `$this->post->deletePreservingMedia()` but received this error

```
Symfony\Component\Debug\Exception\FatalThrowableError  app/Video.php:225
Type error: Argument 1 passed to App\Post::Spatie\MediaLibrary\HasMedia\{closure}() 
must be an instance of Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia, instance of App\Post given
```

Here's my Post model

```
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasMediaTrait;
...
```

I've used `$this->post->clearMediaCollection()` and do not receive an error - although it doesn't delete the row. My media is on another disk on another server that Media Library can't touch, so I only need to delete the row on my `media` table.

Is there a better way?

**Comment by nicolasbeauvais** [comment]
How did you used deletePreservingMedia() ? as documented in the code this method will delete your Post model but leave associated media row in the database.

If you want to delete a media only from the database a simple use of the laravel query builder will bypass any restriction of the media model:
```php
DB::table('media')->where('id', $media->id)->delete()
```

**Comment by freekmurze** [comment]
@timgavin could you post the entire debug trace so we can see where the error is originating exactly?

**Comment by timgavin** [comment]
@freekmurze Unfortunately I can't. I couldn't wait and had to develop another means of doing this.

**Comment by peerrabe** [comment]
It seems you don't implement required interface `HasMedia` as the error message said.
`class Post extends Model implements HasMedia`
should work?
