### ISSUE TITLE
Custom file name or extension

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#385]
I already have a system set up to encode videos, so I 'm not using Media Library for generating video thumbnails. However, I do want to use it for displaying the thumbnail and a preview video.

I am using Media Library for handling all of my `post` images, so I have conversions set up for them already: `sm`, `md`, `lg`.

In my database `media` table the filename is `foobar.mp4`.

I want to display an image thumbnail with a link to a **preview** video, which would be named `md.mp4`. I could use the conversions for this but keep running into the problem of my link looking for a `md.jpg` instead of a `md.mp4`

```
<a href="{{ $image->getUrl('md') }}">
    <img src="{{ $image->getUrl('sm') }}" class="img-responsive center-block" alt="">
</a>
```

Is there any way to pass a custom file name or, suffix or extension to the `getUrl()` method? Or any other method I should use to accomplish this?

**Comment by nicolasbeauvais** [comment]
Media conversions can only be images.

But you can easily customize the `getUrl()` method by [creating your own media model](https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/using-your-own-model)
and overiding the `getUrl()` method.
