### ISSUE TITLE
[feature] add method to only delete file et not entire folder if another file exists

### ISSUE THREAD

**Issue by jaoued** [spatie/laravel-medialibrary#388]
Hi,

I recently discovered that when i delete media, the entire folder is deleted (even if another file exists). 

Can you add method to only delete file et not entire folder if another file exists?

Thanks in advance.

Regards.

**Comment by freekmurze** [comment]
This package assumes that it has full control over the directory where all the media is residing.

If you're manually putting in the files then I suggest your use [this method](https://docs.spatie.be/laravel-medialibrary/v3/api/adding-files#preserveoriginal) to preserve all the files. Of course you should write your own logic to only remove the files created by the medialibrary and leaving your manually added files untouched.

**Comment by jaoued** [comment]
Actually, i use two methods for this :

`$media->addMedia('url')->toCollection('CollectionName');`

And to delete a media, i use `delete()` method (but this removes entire folder).

To delete juste one file and not the folder, witch method can i use ?

Thanks.

**Comment by ittikorns** [comment]
+1 on this after called delete() it delete the entire folder instead of one single image
