### ISSUE TITLE
Unexpected behavior due to PHP7 Return type "Trap"

### ISSUE THREAD

**Issue by arubacao** [spatie/laravel-medialibrary#389]
Hi,  
I'm currently writing some unittests and have noticed an unexpected behavior due to PHP7 return type declarations.

Take for example this method in `HasMediaTrait.php`:  
```
    /*
     * Get the url of the image for the given conversionName
     * for first media for the given collectionName.
     * If no profile is given, return the source's url.
     */
    public function getFirstMediaUrl(string $collectionName = 'default', string $conversionName = '') : string
    {
        $media = $this->getFirstMedia($collectionName);

        if (! $media) {
            return false;
        }

        return $media->getUrl($conversionName);
    }
```

### Some things that i've noticed:

1. Return type `string`

2. When nothing is found it (tries to) return `false`

3. No PHPDocs, even though you mostly use them

While I was writing my unittests I used `$this->assertNull($model->getFirstMediaUrl())` since that's the usual behavior for normal eloquent models and because of `return false;`.
Eventually the test fails, because it doesn't get `null` but `""`.

I don't know if that was your desired behavior, but i feel like this causes a lot of confusion.

### Solution:

1. Remove return type `string`

2. Change `return false;` into `return "";`

Cheers,
Chris

**Comment by freekmurze** [comment]
You're right that `return false` is not the correct type. However, the `string` return type will convert it to an empty string, so strictly speaking this isn't a bug.

But I understand this can lead to confusion, so I've tagged a new version `4.9.5` where an empty string is returned in the code.
