### ISSUE TITLE
How can I update a madia if a original file was changed?

### ISSUE THREAD

**Issue by cve** [spatie/laravel-medialibrary#39]
Hi,

suppose we have a media in products. All original photos are stored on external FTP and we have a cronjob which should update product media only if it was changed. How can we do it?

**Comment by freekmurze** [comment]
Detecting changes inside the directory is not the responsability of this package. 

To solve your problem you could build a script that compares the contents of your ftp against the file_name in the media table. If a change is detected you can update the media object with the new file name:

```php
$media->file_name = $newFileName
$media->save() //image conversions run again for that media object
```
