### ISSUE TITLE
Conversions folders delete problem

### ISSUE THREAD

**Issue by taliptako** [spatie/laravel-medialibrary#390]
My conversions folder owner and group is root and this cause deleting problem.When i'm trying to delete media its i'm getting permission denied error.I dont have this problem in storage folders or media folders only in media conversions folder.

**Comment by freekmurze** [comment]
It seems that this problem is caused by your specific setup.  I'm guessing it must have some to do with how the permissions on your system are set up.

Feel free to submit a failing test if you feel the package is doing something wrong.

**Comment by taliptako** [comment]
Actually all files and folders owned by my user excepts storage  they are owned by www-data and also group and i still didnt find any solution and what cause to this problem.On the resize process php-gd extension is using by this library maybe its because of this extension bug or something idk
I have Ubuntu 16.04.1 with default LEMP stack and all packages are up-to date and i only used to official ubuntu repositories

**Comment by adiachenko** [comment]
Stumbled upon this problem today when running conversions in Horizon from inside a docker container. This is caused by queue workers being run by incorrect user. The solution for me was as follows:

```
docker-compose exec --user www-data php php artisan horizon
```
