### ISSUE TITLE
Problem: ->getFirstMediaUrl() file SVG collection

### ISSUE THREAD

**Issue by Clem01** [spatie/laravel-medialibrary#391]
Hello,

I have a problem with the SVG files and with its collection.

When a SVG file was uploded, the collection (thumb) wasn't created.
And when i use the method getFirstMediaUrl, the url returned is: {{path}}/c/thumb.jpg

Thank you for your help.

In my model:

```
    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
             ->setManipulations(['w' => 300, 'h' => 300])
             ->performOnCollections('*');
    }
```

In my controller:
`$url = $user->getFirstMediaUrl('signature', 'thumb');`

**Comment by nicolasbeauvais** [comment]
Did you installed Imagick ? https://github.com/spatie/laravel-medialibrary/blob/master/README.md#requirements

Also which version of medialibrary are you using ? SVG conversion support has been implemented recently.

**Comment by Clem01** [comment]
Sorry but i just saw your response now.
The answer is no. I didn't activate it before but now it is activated.

Now it works but, when i see the path generated for the thumb, it shows : c/thumb.jpg but the original file is a SVG.

For me the logic is: when the function "getFirstMediaUrl" is called, it returns to the original file path when it is a SVG. (maybe with a supplementary argument)

**Comment by nicolasbeauvais** [comment]
Converted files are always `.jpg` or `.png` as Glide (the library used to perform the conversion) only know theses two formats. So to perform a conversion on an SVG file medialibrary first convert the SVG file to a jpg file then perform the thumb conversion.

`getFirstMediaUrl()` should indeed return your file in it's original format (svg) unless you are passing a conversion name argument like `getFirstMediaUrl('default', 'thumb')`.

**Comment by Clem01** [comment]
Ok, thanks for your reply and explication. I will work with the original file for SVG and thumb for the other formats.

**Comment by yaroslawww** [comment]
Yes you can override method. Something like this:
```
class Media extends \Spatie\MediaLibrary\MediaCollections\Models\Media
{
    public function getUrl(string $conversionName = ''): string
    {
        if (in_array($this->mime_type, [
            'image/svg',
            // ...
        ])) {
            $conversionName = '';
        }

        return parent::getUrl($conversionName);
    }
}
```
