### ISSUE TITLE
Delete single item

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#393]
My Post can have multiple photos;  I want to delete one. I've looked through the docs and can't find an example. Would this be the best way? Seems clunky...

```
public function destroy(Post $post, $photoId)
{
    $mediaItem = $post->getMedia();

    foreach($mediaItem as $item) {
        if($item->id == $photoId) {
            $item->delete();
        }
    }
}
```

**Comment by freekmurze** [comment]
There's [a `deleteMedia` function](https://github.com/spatie/laravel-medialibrary/blob/f0ce5e73e7a75c5194822a9f7451578641c44ce0/src/HasMedia/HasMediaTrait.php#L261).

In our projects we handle this case a bit differently. We get a response back with mediaIds that should be kept. We pass those ids to [the `updateMedia` function](https://github.com/spatie/laravel-medialibrary/blob/f0ce5e73e7a75c5194822a9f7451578641c44ce0/src/HasMedia/HasMediaTrait.php#L186).

**Comment by amosmos** [comment]
@freekmurze Not completely related to medialibarary but can you give more details\share how you build the UI for the user to delete images from an item, when eventually the code only send the ID's of the media to keep? Just curious...

**Comment by nicolasbeauvais** [comment]
@amosmos something like that ?

**Comment by nicolasbeauvais** [comment]
@amosmos something like that?

```php
$user = User::find(1);
$user->media->each(function (Media $media) use ($keep_id) {
    if ($media->id != $keep_id) {
        $media->delete();
    }
});
```

**Comment by amosmos** [comment]
@nicolasbeauvais  I believe that on the server side it is cleaner to use updateMedia...

But I was wondering about the front end UX and how it is implemented. How is it implemented so that the request returns an array of images to keep.

**Comment by freekmurze** [comment]
@amosmos We use the [`updateMedia` function](https://github.com/spatie/laravel-medialibrary/blob/6c1efe705770c6682cc884c485b1594a10857cf5/src/HasMedia/HasMediaTrait.php#L186). Our front end will send the media ids of all the media that should remain. The back end will delete all media items of model that are not being passed through.

**Comment by amosmos** [comment]
Yeah, I get that :-) I'm asking about how you implemented the front end to behave like that (to return the images that should be kept). As I said, I know it is less related to medialibrary, but still very interesting :-)

**Comment by amosmos** [comment]
Do you have a delete button next to each image? And if so, clicking it doesn't make a request? You have some javascript going on that removed the image from the DOM? And then a "Save" button that triggers JS that forms an array of ID's of the images that were left in the DOM?

**Comment by freekmurze** [comment]
> Do you have a delete button next to each image?

Yes

> And if so, clicking it doesn't make a request?

No, clicking it will just remove that media item for the hidden json field that holds the id's of all the media associated with the model we're displaying.

**Comment by amosmos** [comment]
That's such a nice way to do it, saving a refresh every time and allowing the user to change and save all data at once - but how do you handle adding images in such way? Let me know whenever I'm asking too much :-)

**Comment by freekmurze** [comment]
We have a drag and drop interface where users can drop their files.
Uploaded files get processed immediately.

https://github.com/spatie/blender/blob/b24a995/app/Http/Controllers/Back/Api/MediaLibraryController.php#L17-L40

We do put a draft custom property on those media and remove that property
when a user saves the entire form





Freek Van der Herten
Samberstraat 69 D
2060 Antwerpen
T:  +32 3 292 56 79
M: +32 495 84 27 91
https://spatie.be

**Comment by amosmos** [comment]
This is just amazing. I am trying to understand how to use Blender, it's still a bit too intimidating for me.. But will get there one day
