### ISSUE TITLE
Conversions other than images 

### ISSUE THREAD

**Issue by vool** [spatie/laravel-medialibrary#394]
Hello,
I am looking to convert/compress audio and video content, is this possible ?
ie using ffmpg to re-encode and save out reduced quality audio or video files ?

Thanks in advance

**Comment by nicolasbeauvais** [comment]
Medialibrary use [Glide](https://github.com/thephpleague/glide) to perform a conversion, glide can only convert images files. Medialibrary  has a feature called [Image generator](https://docs.spatie.be/laravel-medialibrary/v4/converting-other-file-types/using-image-generators) that can convert SVG, pdf, and video to images to use them in Glide.

Currently, the only way for you to compress a video file will be to compress it before sending it to medialibrary.

**Comment by vool** [comment]
Thanks for that info Nicolas,

I am looking to allow upload  of images, audio and video, associate these with a model and generate preview (compressed) versions of the files, this all works fine with images but the audio/video are an issue. 
I can compress these before sending it to medialibrary as you suggest but is there a way for me to associate the original version as well as the compressed version with the model ? 
ie if a user upload a image this can have many conversions eg org, thumbnail etc. is similar associations possible  with non image files or should I look at an alternative package

Thanks

Keith

**Comment by nicolasbeauvais** [comment]
I do not see any simple way of doing that with medialibrary for now.

You can create your own Path and Url generator with some custom logic to retrieve your video / audio conversions, but there is no feature to let you upload your own conversions, so that's a lot of code to implement on your side.
