### ISSUE TITLE
Dimensions via url (like glide)

### ISSUE THREAD

**Issue by sandervanhooft** [spatie/laravel-medialibrary#403]
Hi @freekmurze et al,

Any idea how I could use this package while also reaping the benefits of Glide's url parameters?

I.e. converting an image on the fly, passing the dimensions in the url?

Kind regards,

Sander van Hooft

**Comment by freekmurze** [comment]
That behaviour is not support. We only use Glide to make use of the easy passing of modifications via an array. The whole "on the fly" part of Glide is not used.

**Comment by sandervanhooft** [comment]
I understand, but does the media library expose a function to get the file storage path, which in turn perhaps could be used for this "on the fly conversion" method?

If so, do you see any reason why this would be cumbersome to implement?

**Comment by freekmurze** [comment]
Media items to have a `getPath` method.

On the fly conversion would take a lot of logic to implement and imho this doesn't fit into the general idea behind the medialibrary. If you need on the fly conversions, just use Glide instead of this package. It'll work fine.
