### ISSUE TITLE
get conversions for a specific collection

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#404]
Any way I can get the conversions by collection for an object?

**Comment by nicolasbeauvais** [comment]
Something like:

```php
$model->getMedia('collectionName')->each(function(Media $media) {
    return $media->getUrl('conversionName');
});
```

will return a Laravel Collection containing all URLs for the conversion `conversionName` of all file from the `collectionName` collection.

Is that what you were looking for ? :)

**Comment by kickthemooon** [comment]
I am looking for:
```
$newsItem->getMediaConversions() as $conversion
```
But only for a collection, not all conversions for the model :)

**Comment by kickthemooon** [comment]
I would also love to know where this method is located: 
```
getMediaConversions()
```
Because I can't seem to able to find it even though I'm using it successfully.
This is my composer.json medialibrary part:
```
"spatie/laravel-medialibrary": "^4.9"
```

**Comment by nicolasbeauvais** [comment]
Hope I'm not too late,

I indeed did not understand your first question, to get the media conversions of an object manually I would do something like:

```php
$model = Model::find(1);

// Write all conversion in the model's mediaConversions attribute
$model->registerMediaConversions();

// This is the exact same line used in the library to find the conversions to perform on a specific media
$conversions = $model->mediaConversions->filter(function ($conversion) {
    return $conversion->shouldBePerformedOn('collection_name_to_return');
});
```

I don't know about the `getMediaConversions()`, is it shown somewhere in the documentation?

**Comment by kickthemooon** [comment]
This what I'm using:
```
@foreach($settings->getMediaConversions() as $conversion)
    {{ str_replace('_', ' ', $conversion->getName()) }}

    @foreach($conversion->getManipulations() as $manipulation) 
    {{ $manipulation['w'] }}x{{ $manipulation['h'] }} 
    @endforeach
    
@endforeach
```
I have no idea where that method is located at :D

But it works as expected. $model->mediaConversions looks also interesting. I will consider it in the future.

Thanks.
