### ISSUE TITLE
Probably a change to increase performance for disks with s3 drivers

### ISSUE THREAD

**Issue by arubacao** [spatie/laravel-medialibrary#405]
According to the [directory structure](https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/using-a-custom-directory-structure) _"files will be stored inside a **directory** that uses the id of its Media-object as a name."_

I've noticed that the media-library could save up to 50% HTTP calls to S3 (and I guess `rackspace` would also work) when associating a new file to a model.

During the upload of a file the method `getMediaDirectory` gets called which in turn [makes a call to create a directory](https://github.com/spatie/laravel-medialibrary/blob/master/src/Filesystem.php#L131).
This is redundant for s3 because you can upload the file to a non-existing folder and s3 takes care of it.
Supposedly, it's also bad practice to treat object storages like POSIX - but I didn't research that (However, I guess that this would be a tweak for [league/flysystem-aws-s3-v3](https://github.com/thephpleague/flysystem-aws-s3-v3) ). 

Just a hacky snipplet to illustrate my point:
```
    /*
     * Return the directory where all files of the given media are stored.
     */
    public function getMediaDirectory(Media $media, bool $conversion = false) : string
    {
        $pathGenerator = PathGeneratorFactory::create();

        $directory = $conversion ?
            $pathGenerator->getPathForConversions($media) :
            $pathGenerator->getPath($media);

        if(config("filesystems.disks.{$media->disk}.driver") !== 's3') {
            $this->filesystem->disk($media->disk)->makeDirectory($directory);
        }

        return $directory;
    }
```

I'm pretty sure that there is a much better solution to incorporate the idea, but I wanted to hear your thoughts on this first.

Cheers

**Comment by arubacao** [comment]
The [`copyToMediaLibrary`](https://github.com/spatie/laravel-medialibrary/blob/master/src/Filesystem.php#L48) method could also be a good place for this.

**Comment by freekmurze** [comment]
I'd accept a PR to improves S3 performance. `copyToMediaLibrary` seems like a good spot indeed.

**Comment by arubacao** [comment]
PR was merged, so I'm going to close this here.
