### ISSUE TITLE
Add custom headers on runtime

### ISSUE THREAD

**Issue by arubacao** [spatie/laravel-medialibrary#406]
Hi,

I'd like to add custom headers depending on file, collection and disks.
In the [config file one can add the custom headers](https://github.com/spatie/laravel-medialibrary/blob/master/config/laravel-medialibrary.php#L56), however they get [appended every time](https://github.com/spatie/laravel-medialibrary/blob/master/src/Filesystem.php#L75-L77).

Simple example were adding custom headers on runtime could be relevant:

- one S3 bucket
- one collection `profile_images` --> should be **publicly** available 
- one collection `private_images` --> should be **private**

One could edit the [config value during runtime](https://laravel.com/docs/5.3/configuration#accessing-configuration-values), but in my opinion that's not an elegant way.

Cheers

**Comment by freekmurze** [comment]
Hi, thanks for that PR. On first sight it looks good, I'll review it later this week.
