### ISSUE TITLE
Video image generator not creating thumbnail for 3gp video.

### ISSUE THREAD

**Issue by ergonomicus** [spatie/laravel-medialibrary#408]
Like stated in title, thumbnails are not generated for 3gp videos and I don't see any errors in my log file. I'm using S3 for storage, and everything works nice with mp4 videos.

**Comment by nicolasbeauvais** [comment]
Hello @ergonomicus,

Only `webm`, `mov ` or `mp4` file are converted. 

This restriction is written on the following lines:
https://github.com/spatie/laravel-medialibrary/blob/master/src/ImageGenerators/FileTypes/Video.php#L36-L44

under the hood medialibrary use FFmpeg to make the conversion, the 3gp format should be compatible https://ffmpeg.org/general.html#File-Formats

You could make a small PR to add this file format, you just have to modify the lines I mentioned above to add the file format and MIME and it should work :)

**Comment by ergonomicus** [comment]
@nicolasbeauvais Thank you for links, didn't know that. Yes, I have tested ffmpeg in console, and everything works fine, I just thought that it was supported by medialibrary.
I don't know how to make PR, I will just stick it in my code somewhere...

Thanks a lot!
