### ISSUE TITLE
Registering the custom generator

### ISSUE THREAD

**Issue by ergonomicus** [spatie/laravel-medialibrary#410]
It is said in the docs that we can override the 'getImageGenerators()' function, but that function is never called. That function is defined in Media class, not in HasMedia trait.

So, is there a way to apply custom generator to single model?

**Comment by freekmurze** [comment]
You could override `getImageGenerators` in your own `Media` model and put a check on the model id there.

But honestly, I'd keep all the generators the same for all media.
