### ISSUE TITLE
[ADVICE] Redis Caching

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#413]
So I am starting to implement Redis in my app.
I am new to redis. My app uses Spatie Media Library.

The scenario:
1. Article.php has many Element.php
2. Element.php has one Gallery.php
3. Gallery.php is using SpatieMediaLibrary to attach media to it.

On the front-end i am doing this:
```
@foreach($article->elements as $element)
    //This part will access the database directly
    @foreach($element->getMedia()->first() as $image)
         //displaying single image
    @endforeach
@endforeach
```
and...
```
@foreach($article->elements as $element)
    //This part will access the database directly
    @foreach($element->gallery->getMedia() as $image)
         //displaying gallery images
    @endforeach
@endforeach
```

Article elements caching is fine, now I'm not sure how to cache the..

 - $element->getMedia()->first()
and
  - $element->gallery->getMedia() 

part with redis so I do not call the database every time.

Any suggestions ideas? Thanks.

**Comment by freekmurze** [comment]
Hi, 

questions on how to leverage Redis to speed up your app are a bit out of scope for this issue tracker. 

A possible implementation is to use Redis to cache the an array representation of a media object.
