### ISSUE TITLE
Resolve what exception method was called

### ISSUE THREAD

**Issue by a-komarev** [spatie/laravel-medialibrary#416]
I've found that when you are using static methods in Exception classes for each situation there is harder to catch what is the exact reason of the exceptional situation:

```php
catch (FileCannotBeAdded $e) {
    switch ($e->getTrace()[0]['function']) {
        case 'unknownType':
            // Do something
            break;
        case 'fileIsTooBig':
            // Do something else
           break;
    }
}
```

In earlier versions I've used `catch (FileTooBig $e)`. Is there any other ways to catch what method exactly was called in Exception in current version or going through the stack trace the only way to do it?

**Comment by freekmurze** [comment]
Currently, there is no easier way to catch that specific exception. `FileTooBig` is probably an exception that warrants it's own type. Unfortunately changing the behaviour now is a breaking change.

I'll keep this in my when creating a new major version of the package.

**Comment by freekmurze** [comment]
You'll be happy to know that in the as of yet unreleased version  `v5` each function in `FileCannotBeAdded` was refactored to it's own exception.
