### ISSUE TITLE
Problem installing package with Laravel 5.3

### ISSUE THREAD

**Issue by smakman** [spatie/laravel-medialibrary#422]
I can't seem to install this package with Laravel 5.3 running on PHP7.

Running `composer require spatie/laravel-medialibrary` results in:

> Problem 1
    - Installation request for spatie/laravel-medialibrary ^3.18 -> satisfiable by spatie/laravel-medialibrary[3.18.0].
    - Conclusion: remove laravel/framework v5.3.24
    - Conclusion: don't install laravel/framework v5.3.24
    - spatie/laravel-medialibrary 3.18.0 requires illuminate/support ~5.1.16|~5.2.0 -> satisfiable by illuminate/support[v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].

My composer.json file looks as followed:

```json
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "laravel/cashier": "~7.0",
        "laravel/spark": "*@dev"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*",
        "laravel/homestead": "^3.0"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "repositories": [
        {
            "type": "path",
            "url": "./spark"
        }
    ]
}
```

I also tried removing all vendor files and run `composer install` before running `composer require spatie/laravel-medialibrary` but that results in the same error.

**Comment by freekmurze** [comment]
Are you sure you're running PHP 7 on the command line? Run `php -v` to make sure.

If you are in fact running PHP 7, try installing the package in a fresh copy of Laravel. Maybe there's some other dependency in your project that gets in the way of medialibrary being installed.

**Comment by scottjo** [comment]
Hi, I have a similar issue. I am stuck on PHP 5, so trying to install version 3.18.0 of medialibrary. In my composer.json - 
>"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "laravelcollective/html": "^5.2.0",
        "laracasts/flash": "^2.0",
        "kyslik/column-sortable": "~5.0",
        "garygreen/pretty-routes": "^0.0.5",
        "spatie/laravel-medialibrary": "3.18.0"
    },

And running composer update I get 

> Problem 1
    - Conclusion: don't install laravel/framework v5.3.28
    - Conclusion: don't install laravel/framework v5.3.27
    - Conclusion: remove laravel/framework v5.3.26
    - Conclusion: don't install laravel/framework v5.3.26
    - Conclusion: don't install laravel/framework v5.3.25
    - Conclusion: don't install laravel/framework v5.3.24
    - Conclusion: don't install laravel/framework v5.3.23
    - Conclusion: don't install laravel/framework v5.3.22
    - Conclusion: don't install laravel/framework v5.3.21
    - Conclusion: don't install laravel/framework v5.3.20
    - Conclusion: don't install laravel/framework v5.3.19
    - Conclusion: don't install laravel/framework v5.3.18
    - Conclusion: don't install laravel/framework v5.3.17
    - Conclusion: don't install laravel/framework v5.3.16
    - Conclusion: don't install laravel/framework v5.3.15
    - Conclusion: don't install laravel/framework v5.3.14
    - Conclusion: don't install laravel/framework v5.3.13
    - Conclusion: don't install laravel/framework v5.3.12
    - Conclusion: don't install laravel/framework v5.3.11
    - Conclusion: don't install laravel/framework v5.3.10
    - Conclusion: don't install laravel/framework v5.3.9
    - Conclusion: don't install laravel/framework v5.3.8
    - Conclusion: don't install laravel/framework v5.3.7
    - Conclusion: don't install laravel/framework v5.3.6
    - Conclusion: don't install laravel/framework v5.3.5
    - Conclusion: don't install laravel/framework v5.3.4
    - Conclusion: don't install laravel/framework v5.3.3
    - Installation request for spatie/laravel-medialibrary 3.18.0 -> satisfiable by spatie/laravel-medialibrary[3.18.0].
    - Conclusion: don't install laravel/framework v5.3.2
    - Conclusion: don't install laravel/framework v5.3.1
    - spatie/laravel-medialibrary 3.18.0 requires illuminate/console ~5.1.16|~5.2.0 -> satisfiable by illuminate/console[v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - don't install illuminate/console v5.1.16|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.1.20|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.1.22|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.1.25|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.1.28|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.1.30|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.1.31|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.1.41|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.0|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.19|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.21|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.24|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.25|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.26|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.27|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.28|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.31|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.32|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.37|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.43|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.45|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.6|don't install laravel/framework v5.3.0
    - don't install illuminate/console v5.2.7|don't install laravel/framework v5.3.0
    - Installation request for laravel/framework 5.3.* -> satisfiable by laravel/framework[v5.3.0, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.3, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9].

**Comment by smakman** [comment]
Thanks @freekmurze. My virtualbox was running on PHP7 but my local machine was running on PHP5.6. After updating to PHP7 with `curl -s http://php-osx.liip.ch/install.sh | bash -s 7.0` I could install the package without any problems.
