### ISSUE TITLE
QueryException  Field 'model_id' doesn't have a default value

### ISSUE THREAD

**Issue by netwrkx** [spatie/laravel-medialibrary#425]
SQLSTATE[HY000]: General error: 1364 Field 'model_id' doesn't have a default value (SQL: insert into `media` (`updated_at`, `created_at`) values (2016-12-24 21:47:12, 2016-12-24 21:47:12))

Controller
```
        $mediafile = new Media();
	$mediafile->save();
        $file = $mediafile->addMedia($request->file('photo'))->toMediaLibrary();
```
Model
```
class Media extends Model implements HasMedia
{
    use HasMediaTrait;
	
protected $fillable = ['model_type', 'model_id', 'collection_name', 'name', 'file_name', 'disk', 'size', 'manipulations', 'custom_properties'];
}

```
help!!!

**Comment by freekmurze** [comment]
You shouldn't manually create `Media` models. The package will do this under the hood. Media should always be associated with another model.

Here's an example: 

```php
(BlogPost::first)->addMedia($pathToFile)->toMediaLibrary();
```

**Comment by cotein** [comment]
Please, explicity what is $pathToFile.
Example, please!

**Comment by freekmurze** [comment]
It' just a path to a file. eg `/home/forge/my-site.com/images/my-image.jpg`.
