### ISSUE TITLE
delete() and deleteMedia() both delete entire folder instead of single media

### ISSUE THREAD

**Issue by ittikorns** [spatie/laravel-medialibrary#426]
Hi,

I have this folder structure setup

/uploads/story/story_id/filename.jpg

This is how I add media to the library

`$story->addMedia($pathToFile)->preservingOriginal()>toMediaLibrary();`

and I try to delete by query it (after added two files to the library)

```
$media = $story->getMedia();
$media[0]->delete();
```

The results is the whole story_id folder is being deleted but only one record were deleted from the media table in the database.

**Comment by freekmurze** [comment]
When using your own directory structure you should take care that every media should have it's own unique directory.

This is [mentioned in the docs](https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/using-a-custom-directory-structure):
> There aren't any restrictions on how the directories can be named. When a Media-object gets deleted the package will delete its entire associated directory. So make sure that every media gets its own unique directory.
