### ISSUE TITLE
resize image right before adding it to the library

### ISSUE THREAD

**Issue by amosmos** [spatie/laravel-medialibrary#428]
is it possible...?

**Comment by nicolasbeauvais** [comment]
Hello @amosmos,

medialibrary integrate https://github.com/thephpleague/glide which can help you achieve this in an elegant way, this is described in the [difining conversions](https://docs.spatie.be/laravel-medialibrary/v4/converting-images/defining-conversions) part of the documentation.

If for any reason you need to resize the image by yourself:

```php

$file = request()->file('my_file');

// Perform the image resize and store the file with the correct size somewhere

$model->addMedia($pathToCorrectFile)->toMediaLibrary();
```

**Comment by amosmos** [comment]
Yes, I thought there must be a way to use the conversions api also directly on images before adding.

But I didn't think it through and just installed the intervention image package - you think it's a mistake because it's unnecessary when glide is already installed?

**Comment by nicolasbeauvais** [comment]
Medialibrary integrates glides features in a convenient API (images conversions), unless there is a feature in Intervention that you can't use with glide or medialibrary I would stay with glide wich will make you will save a lot of time.
