### ISSUE TITLE
getMedia return empty array

### ISSUE THREAD

**Issue by netwrkx** [spatie/laravel-medialibrary#429]
```
public function addMedia(StoreMediaRequest $request, News $news)
    {
		$photo = $request->file('photo');
		
		$news->save();
		$news->clearMediaCollection('images'); //doesn't clear images collection
                $file = $news->addMedia($photo)
		                  ->usingFileName(time(). $photo->getClientOriginalName())
				  ->toCollection('images');
		
		

        return [
            'url' => $file->getUrl(),
			'$mediaItems' => $news->getMedia('images'),
        ];		
        
    }
```

```
    public function medialibrary(News $news)
    {
		$mediaItems = $news->getMedia();		
		return $mediaItems //returns empty array;

    }
```

i'm trying to pull all images in images collection in order to display in a gallery mode but $news->getMedia() always return empty array...

Help!!

**Comment by freekmurze** [comment]
Does this fix your problem?

```php
return $news->getMedia('images');
```

**Comment by freekmurze** [comment]
Have you added media to the `images` collection for that `$news`?

Does your `Media` table contain any rows?

**Comment by netwrkx** [comment]
```
              $file = $news->addMedia($photo)
		                  ->usingFileName(time(). $photo->getClientOriginalName())
				  ->toCollection('images');
```

![models](https://cloud.githubusercontent.com/assets/5035044/21542799/7e1693e6-cdb8-11e6-8992-f07d452642d4.PNG)

`	return $news->getMedia('images');`

**Comment by freekmurze** [comment]
Try this.


```php
$news->addMedia($photo)
		                  ->usingFileName(time(). $photo->getClientOriginalName())
				  ->toCollection('images');

$news = $news->fresh():
$media = $news->getMedia('images');
```

**Comment by netwrkx** [comment]
FatalThrowableError in MediaDirController.php line 22:
Call to a member function getMedia() on null

```
    public function medialibrary(News $news)
    {
		$news = $news->fresh();
		$media = $news->getMedia('images'); //LINE 22
		return $media;	
    }
```

```
public function addMedia(StoreMediaRequest $request, News $news)
    {		
		$photo = $request->file('photo');
		$news->save();

                $file = $news->addMedia($photo)
   		                    ->usingFileName(time(). $photo->getClientOriginalName())
				    ->toCollection('images');
		
        return [
                        'url' => $file->getUrl(),
			'$mediaItems' => $news->getMedia('images'),
        ];			
    }
```

**Comment by freekmurze** [comment]
Is the `$news` being passed through a valid `News` object?

**Comment by netwrkx** [comment]
I don't understand what you mean by being passed through a valid News object

**Comment by freekmurze** [comment]
Ok, I think the problems you are reporting are not caused by this package, but simply by how you've built up your controller.

To validate that the package is working correctly do this:

```php
$news = App\Models\Owna\News::first();
$media = $news->getMedia('images');
```

`$media` should now hold the images of the first news item.

**Comment by netwrkx** [comment]
$news = News::first(); only to pull the first data
```
$news = News::first(); or $news = \App\Models\Owna\News::first(); // works
$media = $news->getMedia('images');
return $media;
```
when i try $news = **News::all(); or $news = \App\Models\Owna\News::all();** to pull all item, i get the following error
**BadMethodCallException in Macroable.php line 74:
Method getMedia does not exist.**

**Comment by freekmurze** [comment]
`News::all()` returns a `Collection`. `getMedia` only exists on models that use the `HasMedia` trait.

If you want to get all images for all newsItems I suggest this solution:

```php
News::all()->map(function($news) {
   return $news->getMedia('images');
})->flatten();
```

If you want to know more about Eloquent I highly suggest your read through the entire docs on the subject: https://laravel.com/docs/5.3/eloquent

If you want to know more about Collections read through those docs as well: https://laravel.com/docs/5.3/eloquent-collections#available-methods

**Comment by elshobokshy** [comment]
`$news->getMedia('images')` does work, but why? Why `$news->getMedia()` isn't?

**Comment by Amansamitola** [comment]
i ran into the same problem 

still not got solution

**Comment by topk36** [comment]
I got the same problem. The reason is that in the image request, the request is not escaped.
``SELECT * FROM `media` WHERE `model_type` = 'App\Models\AdProduct'`` must be 
``SELECT * FROM `media` WHERE `model_type` = 'App\\Models\\AdProduct'``

**Comment by Sunny-Ojo** [comment]
> Does this fix your problem?
> 
> ```
> return $news->getMedia('images');
> ```

you are awesome man,
