### ISSUE TITLE
The method clearMediaCollection() to remove all associated media doesn't work

### ISSUE THREAD

**Issue by zvermafia** [spatie/laravel-medialibrary#431]
But if I do like this `$post->getMedia()->first()->delete();` it works fine for the first item of the media collection. But it isn't comfortable to use!

homestead: 1.0.1
php: 7.0
laravel: 5.3.28
spatie/laravel-medialibrary: 4.10.2

**Comment by freekmurze** [comment]
Could you provide a snippet of code that is not working for you.

When using the default collection you need to pass `default` as a parameter

```php
->clearMediaCollection('default');
```
