### ISSUE TITLE
How rename thumbs

### ISSUE THREAD

**Issue by lucassmacedo** [spatie/laravel-medialibrary#432]
Hello! I'm trying to rename the thumbs to improve SEO. And I did not find how to do it ..
All thumbs has the same name..

      $this->addMediaConversion('thumb')
           ->setManipulations(['w' => 200]);

      $this->addMediaConversion('adminThumb')
           ->setManipulations(['w' => 400]);

      $this->addMediaConversion('big')
           ->setManipulations(['w' => 600]);

**Comment by freekmurze** [comment]
Currently there is no way to rename the filenames of the converted images themselves.  You can however [change the name of the directories they are stored in](https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/using-a-custom-directory-structure).

When working on a next major version, I'll revisit this issue to see if we can support custom names for converted images.
