### ISSUE TITLE
Conversions doesn't work.

### ISSUE THREAD

**Issue by jcornil** [spatie/laravel-medialibrary#44]
I think the path to the Conversions interface is wrong and HasMediaTrait doesn't have registerMediaConversions implementation method.

In doc,
...
use Spatie\MediaLibrary\HasMediaConversions;

class News extends Model implements HasMediaConversions
{
    use HasMediaTrait;
   ...
}

**Comment by freekmurze** [comment]
These are the right use statements:
```php
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
```
I've corrected it in the docs.

**Comment by jcornil** [comment]
What about the implementation of registerMediaConversions?

I got this error.

Class Model contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions::registerMediaConversions)

**Comment by freekmurze** [comment]
When using the `hasMediaConversions`-interface you must implement the `registerMediaConversions`-function. See the example in the docs.

**Comment by jcornil** [comment]
Oh...sorry, my fault.
Thanks for super fast response...:)

**Comment by freekmurze** [comment]
Np, have fun using the package.
