### ISSUE TITLE
Using storage to upload images with auth middleware

### ISSUE THREAD

**Issue by yusufyilmaz** [spatie/laravel-medialibrary#440]
Hi,

I have started to use medialibrary. Thanks for that. As I now saw that @freekmurze on Twitter to post questions here :)

I am using medialibrary to upload my images on local storage. I have implemented some custom url generator class. However, I want to use my images with controller in order to hide from public access with auth middleware. Is there any best practice to work through this process? What way would you implement to use an id for the different conversions of image on rout parameter?

**Comment by freekmurze** [comment]
Hi,

this package does nothing regarding authorization. You should handle everything regarding authorization in your own app.

**Comment by yusufyilmaz** [comment]
Thanks for the reply @freekmurze . I have asked my question in wrong way I suppose. 

I have been using laravel own auth middleware. I have a route for the image viewer under auth middleware. This part is not related to the medialib package. My question is that on my route, I have been using image ids `get('image/{image-id}')` 

when I use your package I could not decide what to do on image id since there are different conversions of the image.  Have you seen any implementation with non-public images to show with auth middleware with different conversions?

**Comment by freekmurze** [comment]
> when I use your package I could not decide what to do on image id since there are different conversions of the image. 

Still do not get what you're trying to do. Do you want to hide the image id? Do you want to show different conversions depending on a user is logged in or not?
