### ISSUE TITLE
Why does the add function in Filesystem.php try to createDerivedFiles?

### ISSUE THREAD

**Issue by smitbit** [spatie/laravel-medialibrary#441]
I'm new to this package and was curious about something that was causing me an issue. Perhaps it will help others that may have the same issue. 

In this bit of code:

```
    public function add($file, Media $media, $targetFileName = '')
    {
        $this->copyToMediaLibrary($file, $media, false, $targetFileName);

        $this->events->fire(new MediaHasBeenAdded($media));

        //app(FileManipulator::class)->createDerivedFiles($media);

    }
```

Why is it assumed I want to created derived files? Is it something wrong I have in config or installation? The issue was that when uploading pdfs into my app I kept getting a file not found error because it was trying to create and image of the pdf. 

I'm not sure why it couldn't find the file because it was there, but I wasn't needing to convert the pdf to an image anyway. I was just wanting to upload and encrypt the pdf.  Commenting out this line seems to have fixed the issue and just uploads the pdf.  Perhaps the encryption kept ghostscript from being able to read the file?

Thanks!

**Comment by nicolasbeauvais** [comment]
I tried and didn't get any errors, have you defined conversions on your model that might be configured to trigger the pdf conversion?

The createDerivedFiles should maybe be renamed, it initializes the media conversion and checks if any defined conversion need to be performed on the media, if not, no conversion should be triggered.

To see if any conversion is defined for your pdf file you can add a `dd($conversions);` at this line:
https://github.com/spatie/laravel-medialibrary/blob/master/src/FileManipulator.php#L43

**Comment by smitbit** [comment]
Okay, so it shouldn't try to convert unless something is telling it to. I'll look around at this more. Thanks for the help!
