### ISSUE TITLE
It is posible to use the cloud filesystem driver directly?

### ISSUE THREAD

**Issue by DojoGeekRA** [spatie/laravel-medialibrary#442]
I was wondering, it is posible to use the cloud driver defined in `config/filesystems.php`as the target disk?

It will be great to work with the `cloud` abstraction and leave to it define the disk behind it

Thanks!

**Comment by freekmurze** [comment]
Not sure what you mean or try to accomplish, but the package will can you use configured disk to store it's files. https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/working-with-multiple-filesystems

**Comment by DojoGeekRA** [comment]
I have been using a pattern where i define the cloud filesystem driver in `config/filesystem.php` as:

```
  'cloud' => env('CLOUD_DRIVER', 's3'),
```

That way if i'm in development environment, i can set `CLOUD_DRIVER` as `local` disk and this way avoid the upload of files to `s3` disk anywhere in my code

```
Illuminate\...\Filesystem\Cloud::put(...) // <- the file goes to local disk on development environment
```

I was wondering if i could tell the library to use the `cloud` driver (which is a disk really) instead of use a disk directly and this way continue using disks based on the environment.

And actually i make this works with the following line, but again, i was wondering if there was a cleaner way to do it

```
$this->model
     ->addMedia($file)
     ->toCollectionOnDisk($this->collection, config('filesystems.cloud'));
```

Even if that is not posible, i'm amazed with the quality of the project, you guys did an amazing work, congratulations!

**Comment by freekmurze** [comment]
Thank you for kind works, I'm glad you like the package.

Currently using the cloud driver is not possible. But I'll make sure this'll work in the next major version of the package.

**Comment by freekmurze** [comment]
This has been added in the as of yet unreleased `v5`. In that version you can use `toCollectionOnCloudDisk($collectionName)`

`v5` will be released closely after L5.4 will be officialy available.

**Comment by DojoGeekRA** [comment]
Wow, thank you very much @freekmurze :metal:
