### ISSUE TITLE
Why fopen in Filesystem.php require "write" permission?

### ISSUE THREAD

**Issue by ethaizone** [spatie/laravel-medialibrary#443]
https://github.com/spatie/laravel-medialibrary/blob/master/src/Filesystem.php#L61

I use `addMedia()` to add original file from samba and it trigger error "Permission denied". I mount it as folder and have permission as 755 so I think it must be something bad in code then I look at them.

I don't know why in `fopen()` in Filesystem.php need "r+".  It needs to read file only. Can we change it to "r"?

**Comment by freekmurze** [comment]
We'll discuss this further at #444
