### ISSUE TITLE
Question: Any way to preserve or specifiy folder structure?

### ISSUE THREAD

**Issue by canvural** [spatie/laravel-medialibrary#45]
Hello,

Right now the folder structure is the path we specifiy in `media` drive plus the `id` of media object plus the  filename. Ex: `/public/images/1/test.jpg`

I want to modify the folder structure because i want to organize the folder. Now everything is inside one folder. For example i want to have path like: `/public/images/reports/daily/1.jpg` 

`/public/images` part comes from the filesystem config file. We have to specifiy `reports/daily` part, maybe with `toFolder` method. Or with `preserveFolderStructure` we can keep the original structure.

We can discuss this and i can make a PR if you think this is a good idea.

**Comment by freekmurze** [comment]
Hi,

thanks for your proposal. Here are my thoughts on it.

The package was designed to make users don't care about where an how files are stored. The current folder structure with every media having its own directory has lots of benefits:
- different media objects can store files with the same file name
- conversions are stored closely to the original file
- when a media gets deleted the cleanup is very easy: we just have to delete the folder belonging to the media
- there's no way a user can overwrite the conversion folder
- by not allowing any exceptions, the code to maintain this organization is very slim and clean

Unless you can suggest a good alternative while preserving these benefits, I'm not inclined to add support for other directory structures.

**Comment by canvural** [comment]
I found a way to do it, if i'm not missing something.

In `getMediaDirectory` at `Filesystem` class we are assuming directory is the id of the media object.

We just need a new `nullable` property on `Media` model. This will be the additional path. Like: "reports/daily". And in the `getMediaDirectory` method we check if this new property is NULL. If it is we fallback to `id`. If it is not we will use it for the directory.

This way we don't need to change anything else.

This should work. Am i missing something?

**Comment by freekmurze** [comment]
That's a nice idea, but I'm still a bit skeptical. When a media object gets deleted we simply delete it's directory. If custom directories are allow there should be precautions that two media objects do not use the same custom directory. A media object should also not be allowed to store it's contents inside the directory of another media object. 

If you want to go through with this idea, feel free to submit a PR. Be sure to add tests. If the changes are elegant enough, I'll merge it (but I'm making no guaranties). If you have further question or want my opinion on something, let me know.

**Comment by canvural** [comment]
For that issue, we can use the `id` as a default directory. Just like how it is now.

But if user gives a custom directory we can "prepend" it to the `id`. So it will become "custom/directory/{id}". That way it will be unique. And it will be organised how the user wants it.

But for now, just i need this feature. I can make my own forked version and use it. But enough people requests it i can make a PR.

**Comment by freekmurze** [comment]
Ok, let me know when you have finished your work. I'm curious how you're going to tackle this.
Have fun coding it up!

**Comment by canvural** [comment]
I'm using my forked version on my project. It's working good.

I just didn't write any tests. 

But, i don't want to force you to merge this just because i wanted it. If you want i can make the PR or in an seperate issue we can ask another users if they want this kind of feature.

**Comment by freekmurze** [comment]
I've taken a look at your changes: https://github.com/canvural/laravel-medialibrary/commit/bbf0ea2a8bccb471fa9cf6e3a14ced53453ba2bc

Nice work!

To prove these changes work you should write automated tests. :smile: 

I don't see precautions to prevent the deleting of files if the directory of one media item is inside the directory of another.

**Comment by canvural** [comment]
I have a lot of to do :smile: 

First of all i commited the wrong file to my fork. `$this->setAdditionalPath = $path;` :sob: 

- Need to write tests.
- Need to change the url generators.
- Find a way to update the migration file. Publishing again didn't work.
- About deleting. I don't see how that can be an issue. A media item will have its own path.
For example; `some/directory/1` and `/some/directory/subdirectory/2`. We can delete the media with id of 2 without touching the other one. Unless some one specifies `/some/directory/1` as the directory of `2`. But maybe we can prevent this by rejecting any numbers in the `additional_path`.

**Comment by vedmant** [comment]
I'm for this feature as well! 

Also it may be greate to split it into subfolders to make not more than 10000 subfolders in one folder. What I mean is something like
      $dir = floor($id / 10000);
      $path = $path.'/'.$dir;
so the actual path will be like "media/0/120/filename.jpg" and if id is between 10000 and 19999 it will be "media/1/12000/filename.jpg".

The reason is that some filesystems slow down significantly where there are a lot of items in one folder, for example ext2 has performance issues after 10000 files in one folder.

**Comment by jcornil** [comment]
How about making folders based on the creation date.

like this...

media/2015/8/14/1/file.jpg
media/2015/8/14/2/file.jpg
media/2015/8/15/3/file.jpg
media/2015/8/15/4/file.jpg

**Comment by canvural** [comment]
@jcornil You will be able to do that with this feature.

**Comment by canvural** [comment]
@freekmurze I added tests, updated url generators.

Only thing to do is update the migration file. How can we do this? Re-publishing the vendor files doesn't seem to overwrite migration file.

We are adding a new column to database. Everyone installed this package before have to add it too. How can we do this? Or is this counts as a `breaking change`?

**Comment by vedmant** [comment]
It would be great to have some callback for model that generates any needed save path. In this case it may not need any change to database. Something like public function getMediaSavePath($media, $collection) for hasMedia interface and trait. So this callback will be used for saving file, getting url and path, removing file.

**Comment by canvural** [comment]
@vedmant With that approach you can save it to only one place. Or you have to change the value in that callback, everytime you want to save it to different place.

**Comment by vedmant** [comment]
@canvural Why in one place, this callback will return any path you need, if you need for example to save some exact model with some exact collection you can just return this: `return 'my_model_folder/'.$collection.'/'.$media->id;` or use date folder like `return 'my_model_folder/'.date('Y-m').'/'.$media->id;`, so on, I suppose this package have to check if folder exists and create it.

**Comment by canvural** [comment]
@vedmant Hmm, i guess that would work too. I misunderstood you the first time.

I will try to implement it tonight. :+1:

**Comment by canvural** [comment]
@vedmant I did some work on this. You can see it here https://github.com/canvural/laravel-medialibrary/commit/ff7b0e74bb153c5761994ec7cae9c04110964916

But there is one problem. I added a property to the `Media` model to store the directory. When the model sent to the queue for conversions that property is being lost. I think there is an issue about serialization in the queue system. I opened an issue in the framework repo.

Apart from that issue, how does it look?

**Comment by canvural** [comment]
@vedmant I did some work on that. You can take a look at https://github.com/canvural/laravel-medialibrary/commit/7f3b2302003d6b8062aa8ba17fd505cb497027cc

It needs tests. But i can't figure out how to write it correctly. Take a look and let me know what do you think.

**Comment by vedmant** [comment]
Sorry, I don't have time now to dive into the code, from what I see it will be good to pass to getDirectory() media model item, also I think it doesn't need to cache directory, you can call function each time directory have to be got. Also it looks like you have to edit only one function: `public function getMediaDirectory(Media $media)public function getMediaDirectory(Media $media)` in `src/Filesystem.php` all other functions use it, just instead of `$directory = $media->id;` type `$directory = $media->model->getMediaDirectory($media);` and I think that's all is needed, also in hasMediaTrait add function that returns $media->id by default.

**Comment by freekmurze** [comment]
In the coming weeks I'll be reviewing this pull request that add this feature: https://github.com/spatie/laravel-medialibrary/pull/50

**Comment by freekmurze** [comment]
I have decided not to put this feature in for now. I'll keep it in mind when working on a next major version.

**Comment by NarekYeghishyan** [comment]
When I uploaded the file, the URL is https://rafkanian.am/storage/app/models/product/2023/11/92/392/7c8650d066c9eacf65d019cb061f5f9e.png. However, when December started, the URL automatically changed from '/2023/11/' to '/2023/12/', and now the images don't show. Can you please explain why?
