### ISSUE TITLE
Using a filesystem disk that is on another server

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#450]
So the default disk is media:
```
'media' => [
            'driver' => 'local',
            'root'   => public_path().'/media',
        ]
```

I wanted to ask if it is possible to use a "disk" that is actually located on another server and domain?

to "convert" this:
```
mydomain.com/media/someimage.jpg
```
to
```
files.somedomain.com/media/someimage.jpg
```

I hope you can understand my question.

**Comment by nicolasbeauvais** [comment]
Laravel filesystem support local / s3 / Rackspace or FTP disks:
https://laravel.com/docs/5.3/filesystem#configuration

you could also probably use Rsync to create a virtual directory that points to your "file" server.

If you choose FTP or Rackspace you will have to generate a custom URL for the media, which is pretty straight forward:
https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/generating-custom-urls

**Comment by kickthemooon** [comment]
ok, ill try to configure the ftp driver.
thanks.
