### ISSUE TITLE
FTP disk, fwrite() expects parameter 2 to be string, resource given

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#453]
I am trying to store files externally via a ftp disk.
I managed to get through to this error:
```
ErrorException in Ftp.php line 204:
fwrite() expects parameter 2 to be string, resource given
```
Not sure what is passing the resource...

**Comment by freekmurze** [comment]
Could you try setting this up in a vanilla Laravel app, so we're sure there's nothing specific to your project is failing?

**Comment by Butochnikov** [comment]
same problem (laravel-medialibrary v4)

**Comment by freekmurze** [comment]
New versions of `v4` and `v5` have been tagged containing a fix for this problem.
