### ISSUE TITLE
Sugestion: add config:clear to installation instructions

### ISSUE THREAD

**Issue by graciano** [spatie/laravel-medialibrary#459]
So, I was installing and I ran:
`php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="migrations"`

It gave me a message like "nothing to publish under tag migrations".
So I went with `php artisan config:clear` before running the publish command and everything went fine.
I think other users and begginers could have some trouble with this.

**Comment by nicolasbeauvais** [comment]
You are not supposed to cache your configuration (or routes) in your development environment, as explained in the laravel documentation: (https://laravel.com/docs/5.3/configuration#configuration-caching)
>You should typically run the php artisan config:cache command as part of your production deployment routine. The command should not be run during local development as configuration options will frequently need to be changed during the course of your application's development.
