### ISSUE TITLE
Manipulation methods not being applied correctly when chained

### ISSUE THREAD

**Issue by cwhite92** [spatie/laravel-medialibrary#46]
Image manipulations don't seem to get correctly applied when convenience methods are chained together. For example, I defined some image manipulations to one of my Eloquent models:

    public function registerMediaConversions()
    {
        $this->addMediaConversion('small')
            ->setWidth(75)->setHeight(75)->setFit('crop')->setFormat('jpg');

        $this->addMediaConversion('medium')
            ->setWidth(150)->setHeight(150)->setFit('crop')->setFormat('jpg');

        $this->addMediaConversion('large')
            ->setWidth(300)->setHeight(300)->setFit('crop')->setFormat('jpg');

        $this->addMediaConversion('full')
            ->setFormat('jpg');
    }

After adding an image via the `addMedia()` method, I noticed that the package was not obeying the `setWidth()` and `setFit()` constraints. [This is the image I was testing with](https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=350&h=150).

What I would expect is for the `small` conversion's image to be 75x75 and cropped to fit inside those dimensions. What actually gets saved is a 176x75 image: http://i.imgur.com/qWxS58Y.jpg 

The good news is that the `setManipulations()` method doesn't have this problem. If I change the `small` conversion's code to this:

    $this->addMediaConversion('small')
        ->setManipulations(['w' => 75, 'h' => 75, 'fit' => 'crop', 'format' => 'jpg']);

Then the image gets correctly cropped to 75x75: http://i.imgur.com/ANr0O9U.jpg

This seems like a bug to me as from looking at the `Spatie\MediaLibrary\Conversion\Conversion` class it seems like the `setX()` methods should be able to be chained together.

P.S. Thank you for the package, it's making my life much easier :+1:

**Comment by freekmurze** [comment]
Thanks for the kind words.

This bug has been fixed in the newly tagged version 3.1.4.

**Comment by cwhite92** [comment]
Wow, that was quick. Thank you!

**Comment by JavierMartinz** [comment]
I think it's not totally fixed, you can't do something like: `$fooModel->addMedia('5MB.bin')->toCollection('mycollection')->withCustomProperties(['foo' => 1, 'bar' => 2])->toMediaLibrary());`

It returns:

`Call to undefined method Illuminate\Database\Query\Builder::withCustomProperties()`
