### ISSUE TITLE
Can't convert svg files

### ISSUE THREAD

**Issue by nicolasbeauvais** [spatie/laravel-medialibrary#463]
Got this error:
```
unable to open image `/tmp/magick-2507NcianG97GQbt': No such file or directory @ error/blob.c/OpenBlob/2712
```

**Fixed by installing imagemagick**:
```
sudo apt-get install imagemagick
```

Got a hard time fixing this one as `php-imagick` was installed and working. So I posted the solution for future readers ;)

**Comment by freekmurze** [comment]
Thanks!
