### ISSUE TITLE
More unified API for v5

### ISSUE THREAD

**Issue by nicolasbeauvais** [spatie/laravel-medialibrary#464]
#### Problem

In Media.php the `getPath` method is used to return the mime type of a file:
```php
public function getMimeAttribute() : string
{
  return File::getMimetype($this->getPath());
}
```

But when using amazon S3 the getPath method doesn't exist on the UrlGenerator which can result in some error on a production server that uses the s3 driver while it will work fine on local development and a local file driver.

#### Proposed solution

1. Throw a clear Exception when using `getPath` with the s3 driver instead of calling the non-existing method for easier debugging.

2. Store the file mime type in the media table, either in a new column or in the `custom_properties` column as an optional feature.

OR

2. Make a head request to the file on s3 to get the mime type (slower)

I will gladly make the PR myself if the proposed change is accepted :)

**Comment by freekmurze** [comment]
Lets go for

> Store the file mime type in the media table, either in a new column or in the custom_properties column as an optional feature.

I'd accept a PR on the v5 branch. Creating a new column for this sounds fine to me.  Also make a note of this change in the `CHANGELOG.md` on that branch.

**Comment by freekmurze** [comment]
@vanbrabantf Fancy sending a PR for this on the `v5` branch?

**Comment by freekmurze** [comment]
I'll take care of this myself.

**Comment by freekmurze** [comment]
Done!
