### ISSUE TITLE
Deprecate duplicated methods for v5

### ISSUE THREAD

**Issue by nicolasbeauvais** [spatie/laravel-medialibrary#465]
### Problem

In `FileAdder.php` there is 4 time the same method with different names:

```php
public function toMediaLibrary(string $collectionName = 'default', string $diskName = '');

public function toMediaLibraryOnDisk(string $collectionName = 'default', string $diskName = '')

public function toCollection(string $collectionName = 'default', string $diskName = '');

public function toCollectionOnDisk(string $collectionName = 'default', string $diskName = '');
```

Which can bring some confusion for beginners as they will see several implementations in examples / documentation / forums.

### Proposed solution

Deprecate or remove 3 of the methods to slim the API.

What do you think of this change ?

**Comment by freekmurze** [comment]
Sounds good, what do you think about keeping only `toMediaLibrary`?

**Comment by freekmurze** [comment]
@vanbrabantf Fancy sending a PR for this on the `v5` branch?

**Comment by nicolasbeauvais** [comment]
I like `toMediaLibrary`, it explain well what it does and it's remind of the package name which is great for the brand image :smile:

**Comment by freekmurze** [comment]
Done!
