### ISSUE TITLE
Rename config file

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-medialibrary#467]
We've decided to drop `laravel-` in the name of the config file for all our packages.

I'd accept a PR targeting the `v5` branch that renames the config file from `laravel-medialibrary.php` to `medialibrary.php`.

Please update the tests as well.

**Comment by LKDevelopment** [comment]
I'll make it, just one moment :)

**Comment by freekmurze** [comment]
Thank @LKDevelopment 👍
