### ISSUE TITLE
Link to Documentation is broken

### ISSUE THREAD

**Issue by Naoray** [spatie/laravel-medialibrary#479]
The suggested Link to the documentation [https://docs.spatie.be/laravel-medialibrary/v4/introduction](https://docs.spatie.be/laravel-medialibrary/v4/introduction) does not work. Is there another documenation except the v3?

Btw. Thanks for this awesome package! Keep up the good work.

**Comment by freekmurze** [comment]
Hi,

thanks for the kind words!

I accidentally broken the v4 docs earlier today. Meanwhile fixed my error, docs are back up.
