### ISSUE TITLE
Don't create "conversions" directory when there are no conversions

### ISSUE THREAD

**Issue by vedmant** [spatie/laravel-medialibrary#48]
Hi, I think it will be better not to create "conversions" directory when there are no conversions for model, in some cases it creates many empty directories. For example when it's not images uploaded, but documents or videos, or even images but with no conversions. Also `makeDirectory($directory.'/conversions');` (or check if it exists) can be moved to `performConversions` function and launched only if there are any conversions.

Thanks!

**Comment by freekmurze** [comment]
Fixed in v3.1.5
