### ISSUE TITLE
medialibrary does not honor $primaryKey

### ISSUE THREAD

**Issue by simplethemes** [spatie/laravel-medialibrary#482]
On a model that uses HasMediaTrait, the following is not honored:
`protected $primaryKey = 'listing_id';`

Is this something easily resolved?

**Comment by freekmurze** [comment]
The trait does nothing special regarding the naming of primary keys.  If it's not working, it has something to do with your specific model. Reopen if your further investigation leads to something our package is doing wrong.

**Comment by simplethemes** [comment]
Thanks for the reply. What I'm saying is the model_id always inherits the id column instead of the primary key defined on the model. This is probably an edge case scenario, but in this instance I have a primary key as a 25 character CHAR field (I'm syncing data over a RETS API).

Should I bypass `$table->morphs('model');` and define the relationship manually?
