### ISSUE TITLE
Generalizing Conversions, extending medialibrary

### ISSUE THREAD

**Issue by Jasper9041** [spatie/laravel-medialibrary#489]
Hi @freekmurze,

I have been following up with the stuff you are implementing in v5 and I am liking it a lot. I was wondering if we could make medialibrary a little more extensible for advanced users that would like to do more than just image conversions.

To explain why I would like this kind of functionality: I am working on a project that involves the conversion of images and video. We use an external encoding service for converting the video and we use Medialibrary for the file handling, image conversions and also to define the video conversions (to let the service know what to do and when to do it).
Currently I am running a forked version of v3 that ahs been modified to accomodate these features. Like you would expect, this is not a very good solution in the long term.. updating to newer versions of medialibrary is not going to be easy. I would be great if the package had a way to extend its functionality easily. I seem to remember issues asking for similar features before so I'm sure some people would love it.

I would propose something along these lines:
- Make a dedicated class for ImageConversion and move all image-specific logic into this class
- Make the conversion class extend an interface that defines all necessary methods
- Move the basic Conversion functionality like shouldBePerformedOn() to a common BaseConversion class
- Enable the user to define any sort of conversion in their own code and give them the possibility to inject that conversion into the registerMediaConversions() method of the hasMedia trait, while keeping the functionality of the package simple for the normal users, that don't need any special behaviour.

Do you have any interest in pursuing this kind of functionality? I would love to help build it.

**Comment by freekmurze** [comment]
In v4 of the package custom image generators were introduced. Is that what you are looking for?

**Comment by Jasper9041** [comment]
Sadly I don't think image generators are what I'm looking for. 

I like the way image generators can be used to take a screenshot of a video, so that the library can use that screenshot to generate all sorts of converted images. The package allows the user to create a custom image generator implementation.

I am looking for somehting similar: 
Let's say i have a 1080p .mp4 and I want to create a  720p .webm version.
It would be great I would be able to create a custom VideoConversion class that handles all the converting logic. This class could then be injected into the medialibrary, just like you would inject a custom image generator.

It would enable a user to create their own implementation of a "conversion":

```
class VideoConversion extends BaseConversion implements ConversionInterface
{
    //video conversion implemantation created by user
}
```
The user would than use laravel medialibrary and specify a custom conversion like this
```
class Post extends Model implements HasMedia
{
    use HasMediaTrait;

    public function registerMediaConversions()
    {
        $videoConversion = new VideoConversion(['format' => 'webm', 'size' => '720p']); // custom user-defined conversion
        $this->addMediaConversion($conversion);

        $normalConversion = new ImageConversion(['w' => 368, 'h' => 232]); //normal image conversion that is built in to the package
        $this->addMediaConversion($normalConversion);
    }
}
```

It's proving a little difficult to explain all this, I hope this helps you understand what I'm talking about. 😄

**Comment by freekmurze** [comment]
Thanks for that example, that made it more clear what you want to add.

Probably I wouldn't accept a PR that adds this to the package. Reasons:
- adding support for multiple kinds of conversions will undoubtedly add a good amount of complexity to the package
- Generally speaking I only want to maintain code I use myself, unless the changes are very simple. I don't need support for custom conversions myself
- Though I haven't performed a survey 😄 , I think most users of this package don't need this.

You could opt to perform the required conversions of your video before adding video files to the medialibrary. In that way you could just use the latest and greatest version of the package.

If that doesn't work for you, then you'll have to create and maintain your own fork.

**Comment by Jasper9041** [comment]
OK. Thank you for your time and your hard work. 😃 

I'll probably end up extending the media model and add custom behavior to convert the video there.

**Comment by AlejandroAkbal** [comment]
Hey @Jasper9041

Did you manage to get a solution?
