### ISSUE TITLE
add softDelete to media model

### ISSUE THREAD

**Issue by pamo85** [spatie/laravel-medialibrary#49]
I use soft delete for my models.
Now, when I delete items, they get soft deleted but media gets hard deleted. 
So any chance to get a soft delete option in a future version?

**Comment by freekmurze** [comment]
Because I don't need this myself, it's not high on my priority list. If you need this feel free to submit a PR.

**Comment by nicolasbeauvais** [comment]
For future readers you can simply override the delete method in the model using soft delete:

```php
public function delete()
{
    return parent::delete();
}
```

The laravel-medialibrary delete method will not be called and will leave all medias untouched.

**Comment by freekmurze** [comment]
Thanks for posting your solution!

**Comment by vesper8** [comment]
@nicolasbeauvais 

did the behaviour change? I just tried your solution and it did not prevent my media db rows from being deleted even though I added the code you posted to my App\User model.

After softDeleting the user both the images as well as the db row were removed

Do you have another workaround that works with latest version by any chance?
