### ISSUE TITLE
Retrieving a single image from collection

### ISSUE THREAD

**Issue by rawcreative** [spatie/laravel-medialibrary#5]
I may just be overlooking something but there doesn't appear to be a simple way to retrieve a single image from a collection, given it's ID (or other identifier), is this the case?

My use case: I have a Product model which has two 'collections', one is a collection containing a single primary product image, and the other contains multiple images used in a gallery/slideshow on the product page. Along with the product details, we have 'Features' section that contains a title, text and image in a carousel format (both for single products and pulling from multiple). Currently the user enters the title, text and selects an image from the collection to use for each 'slide' in the carousel (in which the image ID is stored as the selected img). The problem is, there isn't a simple way to retrieve this image given the ID AND have access to the defined profiles. I thought a simple solution would be querying the media relation with a where clause to match the ID, but since the profiles are hydrated by the repository using a private method there doesn't appear to be a way to grab just a single media object. 

Granted we could grab the whole collection and filter it for the id, but it seems a little heavy handed to have to do then when in some cases we only need a single image.

**Comment by freekmurze** [comment]
The `getMedia`-method has second, yet undocumented, parameter with which you can filter the results.

You can use it in this way:

```$images = $subject->getMedia('images, ['id' => $mediaId]```

Keep in mind that when filtering on id the result is a collection with one or zero elements. If you need a more convenient way to get a media object from a collection by it's id feel free to submit a pull request.

I'll probably add some better filtering methods (use a callable instead of an array) in a future version of the package.

**Comment by ajitbohra** [comment]
@freekmurze can you provide more details on the second parameter  ['id' => $mediaId] is it custom property ?

**Comment by freekmurze** [comment]
Yep, that for filtering on custom properties. Here is [the code that does the actual filtering](https://github.com/spatie/laravel-medialibrary/blob/3.7.0/src/MediaRepository.php#L140-L156).

**Comment by mattboban** [comment]
This solution seams to only filter by custom_properties, Is there an easy way to retrieve by media ID or would you be open to a pull request?

**Comment by freekmurze** [comment]
I'd accept a good PR that adds a function to retrieve a specific media item to the package.

**Comment by bryanrscott** [comment]
Im not sure it is a good PR but
https://github.com/spatie/laravel-medialibrary/pull/419
