### ISSUE TITLE
502 Bad Gateway status - Yet files upload and eloquent works

### ISSUE THREAD

**Issue by olimorris** [spatie/laravel-medialibrary#51]
I'm getting a bizarre 502 status code, using Homestead v0.2.7, when I use the following code:
```
public function store(Request $request, $slug)
    {
        $job = Job::where('slug', $slug)->where('user_id', Auth::id())->first();

        $job->addMedia($request->file('file'))->toCollection('images');
    }
```
The files are uploaded to the path I specify in 'laravel-medialibrary.php', they work on a local disk and an S3 disk, and the entries appear in the database. So seemingly works perfectly...yet throws a 502!

I should add that it works fine when I use Laravel's traditional
```$request->file('photo')->move($destinationPath, $fileName);```

**Comment by freekmurze** [comment]
Can you an error message or trace in your logs?

**Comment by olimorris** [comment]
Problem solved. May be a useful reference as I was using your package alongside the ```Laracasts Bulk File Uploads``` tutorial.

Exploring the error log on my Homestead VM I was seeing the following error:
```upstream sent too big header while reading response header from upstream```

In order to correct this I ran the following command to access my vhost file:
```sudo nano /etc/nginx/sites-available/YOURSITENAME.dev```
and then I applied the following within the ```location ~ .php$ {``` section of the file:
```
fastcgi_buffer_size 128k;
fastcgi_buffers 4 256k;
fastcgi_busy_buffers_size 256k;
```
I then ran ```sudo service nginx restart``` and hey presto. it all works

**Comment by freekmurze** [comment]
Nice! Thanks for letting me know the solution.
