### ISSUE TITLE
dropzone.js ParallelUploads cause errors

### ISSUE THREAD

**Issue by Meersie** [spatie/laravel-medialibrary#517]
If you set parallelUploads > 1 some files return errors because the temp directory in storage/medialibrary does not exist.

"ErrorException in GlideConversion.php line 71:
rename(/var/tmp//3f234c33a35788f80acd52e0894ad3ff/97e1abcecb9a388fc748cc2c0144def3,/Users/sindo/Sites/amplifier_v3/storage/medialibrary/temp/Zfj8Hf8TnmHlBH17thumb.jpg): No such file or directory"

Uploading 1 file at a time is ok.

**Comment by Meersie** [comment]
Followup: 

If you comment out $temporaryDirectory->delete(); in laravel-medialibrary/src/FileManipulator.php the uploads work fine.

**Comment by freekmurze** [comment]
We greatly improved how temporary files are handled in `v5` of the package. Could you upgrade to that version?

**Comment by Meersie** [comment]
Problem is indeed fixed. Thanks!
