### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by BertKUL** [spatie/laravel-medialibrary#52]
Please update the documentation in the section 'Basic usage'. I could not get my conversions to work because I used HasMedia instead of HasMediaConversions

```php
namespace App\Models;

use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

class News extends Model implements HasMedia
{
	use HasMediaTrait;
   ...
}
```

It should be this:

```php
namespace App\Models;

use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;

class News extends Model implements HasMediaConversions
{
	use HasMediaTrait;
   ...
}
```

**Comment by freekmurze** [comment]
In the [defining conversions section](https://github.com/spatie/laravel-medialibrary#defining-conversions) of the readme it is mentioned that you should specify the `hasMediaConversions`-interface.
