### ISSUE TITLE
Upgrade Guide planned?

### ISSUE THREAD

**Issue by Naoray** [spatie/laravel-medialibrary#520]
Hey there,

I was just wondering if you've planned on creating a small upgrade guide. I know there are just a few changes to make when upgrading from e.g. v.4 to v.5, still I forgot to add a migration for the `mime_type` column.

Keep up the good work!

**Comment by freekmurze** [comment]
You'll find a limited upgrade guide here: https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md
