### ISSUE TITLE
Postgres?

### ISSUE THREAD

**Issue by patrickguevara** [spatie/laravel-medialibrary#521]
Docs say that because this package uses `json` column types, it's only compatible with MySQL 5.7+. 

Looking at the Laravel Schema Grammars, Postgres makes the distinction between `json` and `jsonb` as column types whereas MySQL uses the `json` column type for both `json()` and `jsonb()` functions from migration files. This is because MySQL stores JSON internally as BSON where Postgres allows both JSON and BSON.

Is it safe to assume that publishing the migrations file and making the following change...

```
$table->json('manipulations');
$table->json('custom_properties');
```

```
$table->jsonb('manipulations');
$table->jsonb('custom_properties');
```

... can make this package compatible with Postgres?

If so, is it worth making a note of this and/or creating a separate migrations file to publish if you use Postgres?

**Comment by freekmurze** [comment]
I don't use postgres, so I haven't needed or tried compatibility with postgres.

I'm not 100 % sure if your changes will work. To get an indication wether the package works with `jsonb` fields, you could try running the testsuite on a postgres db. You can change the db configuration in `TestCase.php` and run the tests with `vendor/bin/phpunit run`.

If it all works for you, I'd accept a PR that adds a note in the readme.

**Comment by patrickguevara** [comment]
Looks like it works with Postgres using either `json` or `jsonb`. This is of course, without the S3 tests.

One note, however, is the assumptions made about column data types and query results order for a Sqlite database. **Because of this, I had to modify the tests in order for them to pass when connected to a Postgres database instance**. 

For instance, `HasMediaTrait/GetMediaTest.php` asserts that `it_will_return_preloaded_media_sorting_on_order_column`. This assumes that `order_column` value returned from the database will be wrapped in single quotes. This is true for Sqlite but not true for Postgres where it comes out as an integer (as PHP understands it). This makes the test fail when using Postgres. I fixed it with a `->map()` that typecasts the results to an `int`. 

In the `HasMedia/UpdateMediaTest.php` the assertion for `it_removes_a_media_item_if_its_not_in_the_update_array` fails because the wrong media item was removed in the test setup. This is based on the assumption that the insert order is preserved when fetching. This is true for a Sqlite database, but not for Postgres. I modified the test setup to use the `scopeOrdered` trait for ensure that we're removing the intended item.

In the same test class, the `it_reorders_media_items` assertion also fails based on the same assumption of fetch order. I added a `sortBy()` to make sure that when `array_reverse` is issued in the setup phase, it performs the correct reversal and the update goes through as intended.

**The tests still pass for both Sqlite and Postgres after these modifications.**

Another note, in `TestCase.php` I added a couple lines to check for database tables and drop them if they exist. This is necessary for Postgres because the tables (and their rows) persist between tests. 

I'm going to submit a PR for your review so you can see the changes I made, but I'm satisfied with Postgres compatibility so far.

**Comment by freekmurze** [comment]
Thank you for your work in making sure the package works on Sqlite and Postgresql. Great to hear the package works for both these db's.

See comment on the PR why I rejected that one.

**Comment by patrickguevara** [comment]
Yep! I wouldn't make a change to the docs, either. Yes, it technically _can_ support a postgres database but I don't think it's worth including the caveat or increasing your overhead. 

Thanks again for a great package!
