### ISSUE TITLE
Which branch or release for Laravel 5.3?

### ISSUE THREAD

**Issue by phpguru** [spatie/laravel-medialibrary#523]
Our application is written for Laravel 5.3. I'd like to use (or at least test) your library but it's not clear what I should use in composer.json.

**Comment by nicolasbeauvais** [comment]
Version 4.x.x of laravel-medialibrary should work just fine :)

**Comment by davidvd** [comment]
You need to run L5.3 with php7 for this to work. Doesn't work with L5.3 php5.

**Comment by freekmurze** [comment]
There's currently no version that supports Laravel 5.3 and PHP 5. 

The easiest solution it to just upgrade your PHP installation. 

Alternatively you could fork this package and replace all usage of PHP 7 syntax to equivalent PHP 5 code.
