### ISSUE TITLE
Importing multiple files is not working (Only strings, FileObjects and UploadedFileObjects can be imported)

### ISSUE THREAD

**Issue by kplaricos** [spatie/laravel-medialibrary#524]
I have  an array of UploadedFile on the $request object. The library is not checking if the given variable is contains an array of uploads !

dd($request) preview 

array:2 [▼
  "_token" => "5SgZNvUAM6ysrr0AmN9cwcJt5Q8Fi54fH8tac9GT"
  "images" => array:2 [▼
    0 => UploadedFile {#243 ▼
      -test: false
      -originalName: "1327599927.png"
      -mimeType: "image/png"
      -size: 93025
      -error: 0
      path: "C:\wamp64\tmp"
      filename: "phpA18A.tmp"
      basename: "phpA18A.tmp"
      pathname: "C:\wamp64\tmp\phpA18A.tmp"
      extension: "tmp"
      realPath: "C:\wamp64\tmp\phpA18A.tmp"
      aTime: 2017-02-16 13:36:28
      mTime: 2017-02-16 13:36:28
      cTime: 2017-02-16 13:36:28
      inode: 0
      size: 93025
      perms: 0100666
      owner: 0
      group: 0
      type: "file"
      writable: true
      readable: true
      executable: false
      file: true
      dir: false
      link: false
      linkTarget: "C:\wamp64\tmp\phpA18A.tmp"
    }
    1 => UploadedFile {#245 ▼
      -test: false
      -originalName: "creative-sound-blaster-x-fi-surround-5-1-pro.jpg"
      -mimeType: "image/jpeg"
      -size: 26278
      -error: 0
      path: "C:\wamp64\tmp"
      filename: "phpA18B.tmp"
      basename: "phpA18B.tmp"
      pathname: "C:\wamp64\tmp\phpA18B.tmp"
      extension: "tmp"
      realPath: "C:\wamp64\tmp\phpA18B.tmp"
      aTime: 2017-02-16 13:36:28
      mTime: 2017-02-16 13:36:28
      cTime: 2017-02-16 13:36:28
      inode: 0
      size: 26278
      perms: 0100666
      owner: 0
      group: 0
      type: "file"
      writable: true
      readable: true
      executable: false
      file: true
      dir: false
      link: false
      linkTarget: "C:\wamp64\tmp\phpA18B.tmp"
    }
  ]
]

[laravel.log.txt](https://github.com/spatie/laravel-medialibrary/files/780247/laravel.log.txt)

**Comment by nicolasbeauvais** [comment]
I do not think there is any method to add multiple files at once to medialibrary, but you can easily loop on the files:

```php
foreach ($request->file('files', []) as $key => $file) {
    $user->addMedia($file)->toMediaLibrary();
}
```

Hope this answer your question :)

**Comment by freekmurze** [comment]
I'd accept a fully test PR that adds support for this to the package.

**Comment by freekmurze** [comment]
`createMultipleFromRequest` and `createAllFromRequest` have been added on `FileAdder` by @AlexVanderbist in `v5.5.0`

We'll add those to the documentation soon.
