### ISSUE TITLE
Support: how would you handle different image fields?

### ISSUE THREAD

**Issue by FreshFlesh** [spatie/laravel-medialibrary#53]
Hi,

I have one question when associating medias, how would you handle different image fields?

Let's says my News object needs one "main image", one or many "inline images" and one "facebook image".

Would you use different collections, even if some collection would only have one image, or should i create some table columns containing the media ID?

Thanks for your help!

**Comment by freekmurze** [comment]
No prob!

I'd put them in different collections. I wouldn't really mind that there is only one image in it.

**Comment by FreshFlesh** [comment]
Thanks!
