### ISSUE TITLE
Image name conversions x SEO 

### ISSUE THREAD

**Issue by ednonunes** [spatie/laravel-medialibrary#531]
Hello,

First off all is an amazing library, congrats!
Im wondering how can I get some resized image with the original name, for SEO friendly.
For example, if we have the 'thumb' conversion, the 
`$this->getFirstMediaUrl('users', 'thumb'); `
returns "thumb.jpg".
Is there any way to return the original name?
If not, I would suggest to create folders by dimensions, eg: {id}/conversions/thumb/original-name.jpg

I new to Laravel packages, so im not confident to send a contribution for now.

Sorry for my english mistakes (im from Brazil)

Thanks for advance!

**Comment by freekmurze** [comment]
Out of the box this behaviour is not supported, but you could use a custom [`PathGenerator`](https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/using-a-custom-directory-structure) to modify the path names used by the package.
