### ISSUE TITLE
Please update the package to support laravel 5.4

### ISSUE THREAD

**Issue by AchoArnold** [spatie/laravel-medialibrary#533]

**Comment by nicolasbeauvais** [comment]
You can use the version 5.x of this package to get laravel 5.4 support

**Comment by AchoArnold** [comment]
Perhaps this should be added to the documentation because when I do 

```bash
 composer require spatie/laravel-medialibrary
```

I get 

```bash
Using version ^3.18 for spatie/laravel-medialibrary
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

And this fails.

**Comment by freekmurze** [comment]
Yea, the released on the `v3` have much too open version requirements. Unfortunately there's no way to fix this properly outside of removing those releases (which is a nuclear option).

I'll update the docs soon.
