### ISSUE TITLE
Conversions that rely on a custom media attribute do not work

### ISSUE THREAD

**Issue by Rias500** [spatie/laravel-medialibrary#535]
I have a model with the following media conversion:

```php
    public function registerMediaConversions()
    {
        $focus_x = $this->hasMedia() ? $this->getFirstMedia()->getCustomProperty('focus_x', 50) : 50;
        $focus_y = $this->hasMedia() ? $this->getFirstMedia()->getCustomProperty('focus_y', 50) : 50;
        $this->addMediaConversion('banner')
            ->focalCrop(1440, 400, $focus_x, $focus_y);
    }
```

It relies on the focus point coordinates to do its focal crop but when regenerating the media it does not load the model but just creates a new instance as seen [here](https://github.com/spatie/laravel-medialibrary/blob/master/src/Conversion/ConversionCollection.php#L77)

It prevents a query but this query is sometimes necessary, unless there's a better way to solve my problem of setting focal points.

**Comment by freekmurze** [comment]
@sebastiandedeyne and I have discussed the problem. We think we have found a good solution for this. I'll code it up in the coming days and let you know when the fix is released.

**Comment by Rias500** [comment]
Great! I've solved it temporarily by adding the conversion to the media manipulations

**Comment by freekmurze** [comment]
This was added in `v5.3.0`: https://docs.spatie.be/laravel-medialibrary/v5/converting-images/defining-conversions#using-model-properties-in-a-conversion

**Comment by ceesvanegmond** [comment]
@riasvdv Any chance of sharing this plugin? 👍
