### ISSUE TITLE
Always return all media for given Model possible?

### ISSUE THREAD

**Issue by jorenvh1** [spatie/laravel-medialibrary#541]
Is it possible to always return a model with all of its media? I can't just use the Model::getMedia(); function because of relationships. 
This is my setup:
Customer::with('projects')->all();
I want to return all customers with all of their projects. A project has 0, 1 or more media items linked to it. How can I make sure I return all customers, with all of their project (including all their media)?

**Comment by freekmurze** [comment]
Try this:

```php
Customer::with(['projects', 'projects.media'])->all();
```
