### ISSUE TITLE
Set a number of max tries or allow change the class to perform conversions

### ISSUE THREAD

**Issue by Mirdrack** [spatie/laravel-medialibrary#542]
Hello: 
Thanks for this project, this is an amazing package.
Right know I'm having an issue when I upload a non image file, related with this issue https://github.com/spatie/laravel-medialibrary/issues/534

The way to solve this problem is using queues and let fail the job but the problem is that PerformConversions class doesn't have a max tries member.
It would be great if you can specify a number for the max tries before send the job to the failed jobs table or allow specify in the configuration file a custom job class, this will be useful when you need to set an specify behavior.

Thanks.

**Comment by nicolasbeauvais** [comment]
Hello @Mirdrack,

If your app isn't supposed to receive image files shouldn't you just validate the file before handling it to medialibray?

Using something like Laravel native image validation should do the work https://laravel.com/docs/5.4/validation#rule-image

**Comment by Mirdrack** [comment]
I'm creating a file manager for an specific entity(Client) this should be able to receive all kind of files(media) and relate the items to the main entity
When I upload an image there is no problem, the problem comes when I try to upload another kind of files like a txt, the package tries to generate a thumb for an txt file
My question was if there is a way to generate a thumb only for specific type of files

**Comment by nicolasbeauvais** [comment]
Only file type recognized by the library should be converted (listed here: https://github.com/spatie/laravel-medialibrary/tree/master/src/ImageGenerators/FileTypes), if the file doesn't pass the check of one of those 4 types it should'nt be converted :thinking: 

Could you share  the media conversion you defined ? Have you tried with a different txt file ? Which `ImageGenerators` try to convert the file ?

**Comment by freekmurze** [comment]
Closing this for now. If there problem persist, please reopen and include some code or a file (or PR a failing test) that helps us to recreate the problem.
