### ISSUE TITLE
setting created_at before folder creation

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#560]
So i have around 130k (migrated from and older version of the app) articles to which i would like to attach their corresponding images (via an url). The articles have a created_at range of a few years.

I would like to set the media objects created_at equal to the created_at value of the article objects its being attached to before the folder is created so to avoid having 130K images in one folder.

I am using the custom path generator like /2017/9/15/384/someimage.jpg.

```
$object->addMediaFromUrl($url)->toMediaLibrary();
```

I wanted to ask for an idea on how to set the created_at field equal to the article created_at field that isnt too complicated (slow) :)

**Comment by freekmurze** [comment]
In the loop where you're importing all the media you could fake the current time. Carbon has a method for that.

```php
Carbon::setTestNow('2017', '1','1');
```

**Comment by vesper8** [comment]
would be nice to add a "usingDate" instead of this rather hacky proposal
