### ISSUE TITLE
Watermark [v5]

### ISSUE THREAD

**Issue by Butochnikov** [spatie/laravel-medialibrary#561]
Please add support of a watermark for version 5.

**Comment by freekmurze** [comment]
We'll add in this next couple of weeks to the underlying `image` package.

See https://github.com/spatie/image/issues/9

**Comment by freekmurze** [comment]
The underlying `spatie/image` package now has support for watermarks.

https://docs.spatie.be/image/v1/image-manipulations/watermarks

**Comment by Butochnikov** [comment]
Thanks 👍
