### ISSUE TITLE
php artisan migrate error 

### ISSUE THREAD

**Issue by AEK-BKF** [spatie/laravel-medialibrary#563]
Hi,
Using L5.4, I'm trying to install the package but I can't migrate the table, an error says :

 

> [Illuminate\Database\QueryException]                                                                    
>   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check th  
>   e manual that corresponds to your MariaDB server version for the right syntax to use near 'json not nu  
>   ll, `custom_properties` json not null, `order_column` int unsigned nu' at line 1 (SQL: create table `m  
>   edia` (`id` int unsigned not null auto_increment primary key, `model_id` int unsigned not null, `model  
>   _type` varchar(191) not null, `collection_name` varchar(191) not null, `name` varchar(191) not null, `  
>   file_name` varchar(191) not null, `mime_type` varchar(191) null, `disk` varchar(191) not null, `size`   
>   int unsigned not null, `manipulations` json not null, `custom_properties` json not null, `order_column  
>   ` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set u  
>   tf8mb4 collate utf8mb4_unicode_ci)   

> [PDOException]                                                                                          
>   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check th  
>   e manual that corresponds to your MariaDB server version for the right syntax to use near 'json not nu  
>   ll, `custom_properties` json not null, `order_column` int unsigned nu' at line 1              

Please where's the mistake ?

**Comment by h3ndro** [comment]
i confirm that this error is exist when i try to `php artisan migrate`

**Comment by freekmurze** [comment]
Are you using MySQL 5.7 ((mentioned in the docs)[https://docs.spatie.be/laravel-medialibrary/v5/requirements]).

I've not tested it but you could try to replace `json` by `text` in the migrations and see if that works.

**Comment by AEK-BKF** [comment]
Thanks @freekmurze  for answer,
It works now, but will there any mistake when we change json type to text ?

**Comment by freekmurze** [comment]
I'm thinking there won't be any errors, but haven't tested it myself.

**Comment by AEK-BKF** [comment]
Thanks a lot :) :+1:

**Comment by h3ndro** [comment]
@freekmurze , nope, im using mariadb 10.1.9 bundled in laragon, :)

**Comment by vesper8** [comment]
I'm using Server version: 10.2.5-MariaDB Homebrew and was also getting this problem. I thought MariaDB 10.2.x supported json types.. guess not!

Changed to text type instead.. hope it doesn't break anything

**Comment by mikewink** [comment]
@vesper8 MariaDB does not have dedicated json or jsonb data types yet. It comes with a hand full of json related functions though. Find out more about the current state as of posting this comment here: https://mariadb.com/resources/blog/json-mariadb-102

**Comment by thsdeveloper** [comment]
Mudei os meus campos de json para text:
`  $table->text('manipulations');
            $table->text('custom_properties');`
Funciona normal!

**Comment by j0131n** [comment]
As per mariadb version 10.1.32 and lower it seems like mariadb does not support json data type I am still unsure if it is available in version 10.2.7+.

but here's a simple workaround to get through this.

change json data type into text and then run your migration again.

![image](https://user-images.githubusercontent.com/27993070/41234757-9f0ea360-6dbf-11e8-8222-14a52246a87a.png)

**Comment by newsapkota** [comment]
Thanks, it's save my time :+1:

**Comment by Dreanad** [comment]
Hi, same problem here with 
Server version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1

**Comment by yashdhol** [comment]
![image](https://user-images.githubusercontent.com/29609639/54714594-4efe7080-4b77-11e9-844b-57c0df0d8f96.png)

Thanks :)

**Comment by ddreamz18** [comment]
@freekmurze 
Thanks it's working fine.

**Comment by vicsystems55** [comment]
it worked for me too

**Comment by manager-wiseTech** [comment]
> Are you using MySQL 5.7? That requirement is mentioned [in the docs](https://docs.spatie.be/laravel-medialibrary/v5/requirements)
> 
> I've not tested it but you could try to replace `json` by `text` in the migrations and see if that works.

Thanks for your answer.

**Comment by nausixkiz** [comment]
Thank @j0131n 
But we should use ```longText``` instead of ``text`` as MariaDB recommended
