### ISSUE TITLE
Availability delay

### ISSUE THREAD

**Issue by loranger** [spatie/laravel-medialibrary#566]
Hello,

I use medialibrary v5 and I like it, but I'd like to understand something weird:

Inside my controller, (right) after associating files, it seems they are not immediately available

```php
foreach ($request->input('new_picture') as $picture) {
        $post->addMedia($picture)
            ->withCustomProperties(['comment' => $request->input('new_picture_comment')])
            ->preservingOriginal()
            ->toMediaLibrary('upload');
}

dump($post->getMedia('upload')->count());
```

always return `0`

Even a request later (the page where the user is redirected), it seems the medias are not ready yet.

Concerning the conversions, I could understand the job queue may not be always ready, but regarding the associations, I cannot figure out why this is happening.

Could you please help me to understand ?
Thanks

**Comment by freekmurze** [comment]
Like many functions that work on relations the effect of adding a media relation to a model is not immediately visible on the model on which it is performed.

If you get a fresh copy of the model you should see the changes.

```php
...

$post = $post->fresh();
$post->getMedia('upload')->count();
```

Does this work for you?

**Comment by loranger** [comment]
It definitely does, thanks Freek.

I haven't notice anything related while playing with Laravel models and relations
Was I lucky, or are the uploaded file size and the bit manipulations responsible of this delay ?
