### ISSUE TITLE
[L5.1] Eager loading relationship and calling getMedia()

### ISSUE THREAD

**Issue by olimorris** [spatie/laravel-medialibrary#57]
Firstly, a wonderful, wonderful package. Saved me many hours and I find the quality of code in any Spatie package to be top notch!

I'm using the package in a project where a user can post jobs. The user can of course attach lots of images to jobs using your package.

When I come to display all of a users jobs to them, I do so with a thumbnail of their first image, first by calling a method from my controller to my repository, then sending the data to a view:

```php
// Controller
public function __construct(User $user)
{
    $this->user = $user;
}

public function jobs($username)
{
    $jobs = $this->user->jobs($username);

   return view('user.jobs', compact('jobs'));
}
```
```php
// Repository
public function __construct(User $user)
{
    $this->user = $user;
}

public function jobs($username)
{
    $user = $this->user->where('username', $username)->first();

    $jobs = $user->jobs;

    return $jobs;
}
```

```php
// View
@foreach($jobs->chunk(3) as $jobSet)
<div class="row jobs-content-box">
    @foreach ($jobSet as $job)
    <img src="{{ $job->getMedia()[0]->getURL() }}" />
    @endforeach
</div>
@endforeach
```

This works fine however I am left with rather a lot of queries when I investigate using Laravel's Debugbar.

My question is, is there a way to eager load the ```getMedia()``` method rather than having so many queries?

**Comment by freekmurze** [comment]
Thanks for the kind words. I'm glad you like the spatie-packages :)

The media table or the relationship with the model isn't anything special.  So I think the [nested eager loading](http://laravel.com/docs/5.1/eloquent-relationships#eager-loading) could help avoiding the extra queries.

Try changing:
```php
$user = $this->user->where('username', $username)->first();
```
to 
```php
$user = $this->user->with(['jobs', 'jobs.media'])->where('username', $username)->first();
```

Let me know if that works for you.

**Comment by olimorris** [comment]
What a plonker I am...I was use 'jobs.getMedia' - doh!

Works perfectly and down to a respectable number of queries now. Thanks
