### ISSUE TITLE
Format media conversions v5

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#574]
I changed this:
```
$this->addMediaConversion('main_header_logo')
        ->setManipulations(['w' => 515, 'h' => 80, 'fit' => 'crop', 'fm' => 'png'])
        ->performOnCollections('main_header_logo')
        ->nonQueued();
```
to this:
```
$this->addMediaConversion('main_header_logo')
        ->fit('crop', 515, 80)
        ->format(Image::FORMAT_PNG)
        ->performOnCollections('main_header_logo');
```

Getting error:
```
Undefined class constant 'FORMAT_PNG'
```

So I am not sure which model to use intervention/image or spatie/image and I actually both don't seem to work. I took the format(Image::FORMAT_PNG) from the spatie/image documentation but I am probably doing something wrong.

**Comment by freekmurze** [comment]
`Image::FORMAT_PNG` should be `Spatie\Image\Manipulations::FORMAT_PNG`. Please send a PR to the docs to correct this.
