### ISSUE TITLE
Rename `toMediaLibrary`

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-medialibrary#575]
`toMedialibrary` doesn't feel that good when you pass it a collection.

```php
$this->user->addMediaFromRequest('file')->toMediaLibrary('avatar');
```

We should add a method `toMediaLibraryCollection`  and mark `toMediaLibrary` as deprecated.

**Comment by fetzi** [comment]
@freekmurze  I'll send a PR

**Comment by freekmurze** [comment]
@fetzi cool. Also rename all usages of `toMediaLibrary` to `toMediaLibraryCollection` in the tests.
And add one new simple test for `toMediaLibrary`.

If you want to continue being awesome, also send a PR to [our docs](https://docs.spatie.be/laravel-medialibrary).

**Comment by rodymol123** [comment]
Wouldn't ```toMediaCollection``` be a more sensible name? Would go in hand with the ```clearMediaCollection``` I've seen in another issue.

**Comment by freekmurze** [comment]
Yup, I like `toMediaCollection`. I'll merge the changes from #577  and perform that rename myself.

**Comment by fetzi** [comment]
@freekmurze i can do the rename tomorrow if you  want me to?

**Comment by freekmurze** [comment]
It's already done and tagged 😄
