### ISSUE TITLE
Add a method to clear a collection except certain media

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-medialibrary#576]
If a collection needs to be overwritten by one or more `Media` instances, you wouldn't want to clear the collection before adding the media, because if the add would fail, the collection would be empty.

It would be nicer to add one or more media, then clear the collection of all items except the new ones.

Example:

```php
$avatar = $user->addMediaFromRequest('file')->toMediaLibrary('avatar');
$user->clearMediaCollection('avatar', [$avatar]);
```

Don't think we can change the signature because that would be breaking, gonna need a new method for this.

**Comment by AlexVanderbist** [comment]
Maybe something like `clearMediaCollectionExcept()` or `clearMediaCollectionPreserving()`?

Is the change considered breaking if the `$excluded` argument would be optional and null by default?

**Comment by sebastiandedeyne** [comment]
Yeah PHP doesn't seem to complain about that. https://3v4l.org/VZAog

If we'd go for a different method, `clearMediaCollectionExcept` sounds better since we already use the term `preserving` for "don't delete the files".

**Comment by freekmurze** [comment]
I'd go for a different method instead of tacking on extra arguments. `clearMediaCollectionExcept` sounds fine to me. 👍

**Comment by AlexVanderbist** [comment]
Should the `CollectionHasBeenCleared` event still be fired if the collection was only partly cleared?

**Comment by AlexVanderbist** [comment]
Also; doesn't the `removeMediaItemsNotPresentInArray` method do exactly what the issue describes?

**Comment by sebastiandedeyne** [comment]
> Should the CollectionHasBeenCleared event still be fired if the collection was only partly cleared?

My gut feeling says no /cc @freekmurze 

> Also; doesn't the removeMediaItemsNotPresentInArray method do exactly what the issue describes?

This method is protected and tailored for `updateMedia`, which updates media based on a raw array, not an array of media items.

Sounds like `clearMediaCollectionExcept` is the way to go!

**Comment by freekmurze** [comment]
> Should the CollectionHasBeenCleared event still be fired if the collection was only partly cleared?

Indeed no
