### ISSUE TITLE
Call to undefined method Spatie\MediaLibrary\FileAdder\FileAdder::toCollection() 

### ISSUE THREAD

**Issue by alexeightsix** [spatie/laravel-medialibrary#582]
I'm getting this error, couldn't find anything online

Laravel 5.4
"spatie/laravel-medialibrary": "^5.0.0",

Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Spatie\MediaLibrary\FileAdder\FileAdder::toCollection() 
in /home/vagrant/physiotec/loader/app/Http/Controllers/DocumentController.php:34

Code:

$input = $request->all();
    	$input["exercise_id"] = $exercise_id;

    	$validator = Validator::make($input, [
    		'uploads' => 'file|required',
    		'exercise_id' => 'required|exists:exercises,id'
    	]);

    	if ($validator->fails()) {
            return response($validator->errors()->first(), 404);
        }

        try {

        	$exercise = Exercise::findOrFail($exercise_id);
        	$exercise->addMedia($request->file('uploads'))->toCollection("documents");
       	} catch (Exception $e) {
       		return response($e->getMessage());
       	}

Model:

<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

class Exercise extends Model implements HasMedia
{
     use HasMediaTrait;
}

**Comment by alexeightsix** [comment]
i was referencing the v4 documentation, i'm assuming the method was removed from v5

**Comment by alexeightsix** [comment]
hmm, not sure if i'm doing something wrong or the method is no longer available in v5?

**Comment by freekmurze** [comment]
I've you're using the latest version (which was tagged only minutes ago) there is a function called `toMediaCollection` that does what you need.
