### ISSUE TITLE
Conversions throw ErrorException after file-upload but regenerating works fine

### ISSUE THREAD

**Issue by JasonSuave** [spatie/laravel-medialibrary#588]
I keep running into this exception. It seems to only happen when I've uploaded the file and the conversions are being generated. (The file is there in the media directory, but the conversions subdirectory is missing)

``` php
ErrorException in GlideConversion.php line 98:
rename(/var/tmp//9OzZdWuNKaXwXm92thumbnail.jpg/efa8862bf439cd32ecbb95ae0f08b357,/Volumes/UserSpace/Users/jonas/Sources/senioren-club-aalst/storage/medialibrary/temp/kBer9TJ3Cqf6XlNRvEvzV1lVItBf7z4A/9OzZdWuNKaXwXm92thumbnail.jpg): 
Operation not permitted
```

Here's the code in my controller

``` php
$activity->addMedia($request->file('attachment'))
                 ->toMediaLibrary('information');
```

If I run `php artisan medialibrary:regenerate` the conversions show up fine. 
I also have a console command which does the same thing, except for the file-upload, this also works without issues. The file is added to the library and conversions generate perfectly.

Don't think it is related to #517 as commenting out `$temporaryDirectory->delete();` does not fix the problem.

I was on the `dev-master` and tried downgrading to `5.6.0` to no avail.
And fresh out of ideas 😭

**Comment by JasonSuave** [comment]
My current workaround looks like this 
```php
try {
    /** @var Media $media */
    $activity->addMedia($request->file('attachment'))
        ->toMediaLibrary('information');
} catch (\ErrorException $error) {
    Log::error($error->getMessage());
    $media = $activity->getMedia('information')->last();
    \Artisan::call('medialibrary:regenerate', ['--ids' => $media->id]);
}
```
It ain't pretty but it gets the job done for now. 🙈

**Comment by JasonSuave** [comment]
Okay, after some serious Google Fu I found the underlying issue and managed to resolve it.
The problem is caused by the fact that `rename` can only work "normally" on the same drive (cf. [PHP Bug](https://bugs.php.net/bug.php?id=50676)).

As I have my macOS Users folder symlinked to another volume, the system's temporary directory and my source code are on different drives.

The solution is to change Valet's php.ini and set the temporary directory to a folder on the same drive. (That or move your source code to the other drive)
In my case it now looks like this.
```
sys_temp_dir = "/Volumes/UserSpace/var/tmp"
```
Restart Valet and everything should work as expected.

**Comment by freekmurze** [comment]
Thanks for letting us know your solution 👍

**Comment by freekmurze** [comment]
The latest version of `spatie/image` uses `copy` and `unlink` instead of `rename` (thanks for the PR @spyrosk)

**Comment by spyrosk** [comment]
No problem! Thank you for the quick turnaround @freekmurze!
