### ISSUE TITLE
[v5] Storing media specific manipulations - Manual Crop

### ISSUE THREAD

**Issue by Krato** [spatie/laravel-medialibrary#590]
Hi.

I'm trying to store custom manipulation. But no way to get it. This is the code I'm trying:

```php
$imageToModify->manipulations = [
    'thumb' => [
        'crop' => [
            $value['imageWidth'],
            $value['imageHeight'],
            $value['imageLeft'],
            $value['imageTop'],
        ],
    ],
];
```

And this is not working. Throwing this error: 

> Type error: Argument 2 passed to Spatie\Image\ManipulationSequence::addManipulation() must be of the type string, array given, called in /Applications/MAMP/htdocs/templyappbuilder/vendor/spatie/image/src/ManipulationSequence.php on line 52

I'm doing something wrong? How can I do a manual crop?

I know that I can do it from `registerMediaConversions` using `manualCrop` method. But I don't want to do it with all items. I want to crop images depending some properties.

-----------------

Ok, I get it! You need to send the manipulations as string instead an array.

```php
$manipulations = [
    'resized' => [
        'manualCrop' => $value['imageWidth'].', '.$value['imageHeight'].', '.$value['imageLeft'].', '.$value['imageTop'],
    ],
];
```

You can close the issue.

Thanks so much for this package 👍

**Comment by AlexVanderbist** [comment]
Hi @Krato 

You're looking for the following: 
```php
$imageToModify->manipulations = [
    'thumb' => [
        'manualCrop' => "{$value['imageWidth']},{$value['imageHeight']},{$value['imageLeft']},{$value['imageTop']}"
        ],
    ],
];
```

The docs aren't really clear on this but some investigating pointed this out: for the media specific conversions the value of the manipulations for a conversion is always a string. In this case a comma separated list of the necessary arguments (as seen here: https://github.com/spatie/image/blob/master/src/Manipulations.php#L146).

Good luck!

**Comment by Krato** [comment]
Sure. Thanks for the suggestions.

But it's working without the brackets also.

Regards!
