### ISSUE TITLE
getUrl('conversion') and getPath('conversion') return a jpg when using keepOriginalImageFormat()

### ISSUE THREAD

**Issue by langeuh** [spatie/laravel-medialibrary#591]
model
```php
    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
            ->fit(Manipulations::FIT_CROP, 150, 150)
            ->keepOriginalImageFormat();
    }
``` 

When uploading a png conversions are made and result in  png's but the path and url methods are wrong for conversions

`$media->getUrl(); //  returns .../public/media/1/test.png` OK 
`$media->getUrl('thumb'); //  returns .../public/media/1/conversions/thumb.jpg` KO

I looked into it but can't seem to find where it goes wrong

**Comment by AlexVanderbist** [comment]
Looks like I've missed some things when adding `keepOriginalImageFormat`, thanks for pointing this out!
