### ISSUE TITLE
How to store media file to custom public directory?

### ISSUE THREAD

**Issue by muhghazaliakbar** [spatie/laravel-medialibrary#596]
Hi i have laravel directory structure like this:
```
-> /app (all application files)
-> /public_html (all public assets)
```

i already config the public directory in `/public_html/index.php`;

here the filesystem config:
```
'media' => [
    'driver' => 'local',
    'root'   => public_path('media'),
],
```

then i try to upload some image, and does not stored in `/public_html/media` but the package create new one `public/media` directory inside `/app` directory and store the media file there.

**Comment by nicolasbeauvais** [comment]
Hello @muhghazaliakbar,

this is because laravel public_path method is hard coded to always return the `public` directory:
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Application.php#L374-L382

an easy solution would be to use `app_path` instead:
```php
'media' => [
    'driver' => 'local',
    'root'   => app_path('public_html/media'),
],
```
