### ISSUE TITLE
addMediaFromBase64() with optional filename?

### ISSUE THREAD

**Issue by stroebjo** [spatie/laravel-medialibrary#599]
I use an Vue.js form with an image upload (I just put the image into an text field in base64). When I save the Model to the database I use the `addMediaFromBase64()` method to save the image, by doing this it gets a [random filename](https://github.com/spatie/laravel-medialibrary/blob/4f7b437302069e89d9dfa340ee3c10b6d4bfba8e/src/HasMedia/HasMediaTrait.php#L150). 

Would it be possible to add an additional (optional) parameter to pass down the desired filename directly?

**Comment by freekmurze** [comment]
You can use `usingFileName` to set a custom file name.

```php
$yourModel
   ->addMediaFromBase64($base64Date)
   ->usingFileName($yourFileName)
   ->toMediaCollection();
```

**Comment by stroebjo** [comment]
Ah makes sense. Thanks for the hint!
