### ISSUE TITLE
Profile names with _

### ISSUE THREAD

**Issue by rawcreative** [spatie/laravel-medialibrary#6]
It should be noted in the docs that any profile names containing an underscore will not work correctly. We   spent a fair bit of time trying to track down why profile images were being created but not being returned when queried, e.g. we have profiles of 'grid', 'grid_sm', 'grid_lg', and only 'grid' would return an image. We  thought it was in issue with our app  until we looked into the LocalFileSystem class to see the profile names were being parsed by exploding the filenames via underscore.

**Comment by freekmurze** [comment]
I'm sorry that you lost a bit of time. I've made a note of this in the docs. 

I'll make necessary changes to allow underscores in de profilename in a future version of the package.
