### ISSUE TITLE
Any Alternative to usingFileName in Version3

### ISSUE THREAD

**Issue by netwrkx** [spatie/laravel-medialibrary#600]
I just had to degrade from V5 to V3 due to server reasons but i get this error while using V3 
"Call to undefined method Spatie\MediaLibrary\FileAdder\FileAdder::usingFileName()"   
Any fix/alternative to usingFIleName()

Here is my code 
```
        if($request->hasFile('image')){
            $file = $pages->addMedia($data['image'])
                          ->usingFileName(time(). $data['image']->getClientOriginalName())
                          ->toMediaLibrary('Pages', 'pages-fileSystem');
                          
            $pages->save();              
        }
```

**Comment by freekmurze** [comment]
Could you try `setFileName`? 

There are many many differences between `v5` and `v3`. If you encounter more problems please go through the docs on `v3`.

https://docs.spatie.be/laravel-medialibrary/v3/

**Comment by netwrkx** [comment]
i finally used V3.16... Problem solved. thanks
