### ISSUE TITLE
Class 'Spatie\Glide\GlideServiceProvider' not found

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#603]
I upgraded to L 5.4
I upgraded to Media Library 5.0.0 and followed upgrade instructions in UPGRADE.md, though I'm unclear on bullet #3: `media conversions are now handled by spatie/image. Convert all manipulations on your conversion to manipulations supported by spatie/image.`

Now I'm receiving the error `Class 'Spatie\Glide\GlideServiceProvider' not found`

Not sure what to do about this.

**Comment by freekmurze** [comment]
You may remove the `Spatie\Glide\GlideServiceProvider`. Go through all your defined conversions as well. Here are the docs on how you define conversions in `v5`: https://docs.spatie.be/laravel-medialibrary/v5/converting-images/defining-conversions
