### ISSUE TITLE
getMedia() issue

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#605]
In L 5.3 I was able to use `$post->getMedia()` and it worked perfectly. Now it returns null.

So now I have to do `$post->getMedia('public')`, which worries me a little because I have more collection names than just "public." I also have "private" that will only show to people who are authorized to see them; they would be able to see both public *and* private collections...

Is this the way it's intended now? Do I *have* to have to supply a collection name?

**Comment by freekmurze** [comment]
If, in `v5` of the package,  you do not provide a parameter to `getMedia` all media in the collection named `default` will be returned.

**Comment by timgavin** [comment]
This change actually breaks my app, which I've spent a *very* long time building.

If I get 'public' images, then I can't see the `private ones`, and vice versa. Do I need to rebuild how I'm doing things and add everything to a 'default' collection (which I currently don't have) and set the visibility via the `custom_properties`?

What's the point of having collection names if you can no longer use them?

**Comment by freekmurze** [comment]
You can use collection names. What was changed in `v5` that if you do not provide a collection name to the `getMedia` function only items from the collection named `default` will be returned.

**Comment by timgavin** [comment]
Right, so when I *didn't* provide a collection name I would receive *all* images from the `public` *and* `private` collections for each post, and then I would filter them based on a custom property, like so...

```
$array = $post->getMedia();

foreach($array as $image) {
    if(canView($post, $access)) {
        if($image->getCustomProperty('visability') == 'private') {
            // show private image
        }
    } else {
        if($image->getCustomProperty('visability') == 'public') {
            // show public image
        }
    }
}
```

Now that I have to specify a collection name, I only get the images from that specified collection, not from both, which breaks my app.

Can there be a preference that allows the old behavior? Or do I need to reconfigure my app and only use a `default` collection?

**Comment by freekmurze** [comment]
You can get all media for a model by using the `media` property.

```php
$allMedia = $yourModel->media;
```

It'll return a `Illuminate\Support\Collection` which you can filter to your heart's content.

**Comment by timgavin** [comment]
still doesn't make a difference. in fact, it won't even do conversions anymore on new images.

**Comment by timgavin** [comment]
Found the problem: I needed to convert all of my manipulations to the new format supported by `spatie/image`.

I know that's specified plain as day in the upgrade guide, but for some reason it just didn't click with me. :P
