### ISSUE TITLE
Correct approach to save model and process array of images with queue's

### ISSUE THREAD

**Issue by jasperjorna** [spatie/laravel-medialibrary#606]
My VehicleController gets a POST request with an XML that contains vehicle information, including an array of images that it needs to save. When the Vehicle model is created and saved, I'm looping through the array of images to process (resize, generate thumbs, etc.) and save (attach to model) them. Media Library uses the queue for this.

The problem I'm having is the order in which things are executed. Because both the images event and the model's Scout event are queued, they are not aware of each other. This results in my model not having the images attached before Scout sends the model to Algolia.

My current approach was to use Scout's `withoutSyncingToSearch` function to prevent the save() method from indexing the model to Algolia. This seems to solve part of the problem by being able to index the model to Algolia when I want to. However, I'm struggling to figure out how to determine that all images are processed and everything is ready to be synced to Algolia. The images are queued with a loop, so how do I determine when the whole collection is done?

```php
Vehicle::withoutSyncingToSearch(function () use ($vehicle, $content) {
    $vehicle->save();

    $files = $content['images'];

    $media = collect($files)
        ->map(function ($file) use ($vehicle) {
            return $vehicle
                ->addMediaFromUrl($file)
                ->toMediaLibrary('vehicles');
        });
});

// When the above queued events have finished
// publish the vehicle and make it searchable
$vehicle->published = true;
$vehicle->save();
```

**Comment by freekmurze** [comment]
In an ideal world the medialibrary would fire off an event after all jobs that convert images for a model have been completed. Unfortunately it's not that easy to detect when all jobs have been completed.

There's a discussion going on at Laravel internals to make it easier to detect when certain jobs have been completed. It's a sort of `promise.all` for queued jobs. I'm hoping this feature will make it into Laravel 5.5. In that case the medialibrary will immediately implement a `AllConversionHaveBeenCompleted`-event.

Right now the easiest way to index your model after conversion have been completed is to just dispatch a job that does the indexing [with a delay of a couple of minutes](https://laravel.com/docs/5.4/queues#delayed-dispatching). I know, it's a bit crappy, hopefully we can improve things in Laravel 5.5

**Comment by sebastiaanluca** [comment]
I have a similar situation where a user is redirected to a page containing the (converted) media they just uploaded. Since it's queued and the conversion is still pending, they see missing/broken images.

In addition to the `ConversionHasBeenCompleted` event being dispatched in `FileManipulator` per conversion, wouldn't it be trivial to add the `AllConversionHaveBeenCompleted` just at the end of the `performConversions` method or am I missing something? I see no queued jobs in that flow other than the `PerformConversions` which encapsulates all.

Currently trying to set the expected number of conversions on a media model using custom properties and reducing it when `ConversionHasBeenCompleted` until it reaches 0, but it feels too cumbersome just to know when the media is ready to be used.

**Comment by freekmurze** [comment]
Feel free to PR any events that you'd like added.

In our projects where we expect the result to be immediately there (such as avatars of users) we use `nonQueued` on the conversion. This will make sure the converted image is created is the request itself.

**Comment by sebastiaanluca** [comment]
No problem, I'll try to schedule some time to submit a PR when I'm refactoring our image handling.

**Comment by sebastiaanluca** [comment]
Was going to implement this today, doesn't seem necessary anymore 😅 A lucky "side-effect" of switching to responsive images (for all our images) is that it defaults to the original, already uploaded and available, image. When the queue has converted the responsive images, it uses those instead. So win-win here.

Great package, cool new features. Cheers to the team!
