### ISSUE TITLE
Updating image/file for existing media records

### ISSUE THREAD

**Issue by unstoppablecarl** [spatie/laravel-medialibrary#609]
There is no simple way to update the image of an existing media record. 
The package appears to be written with the intent to never update the image of an existing media record. I'm not sure why this is the case, maybe there is a good reason for this I am missing. 

Use Case:

An app with blog posts that have zero or more attached media records. The blog post editing ui has a list view of each media record attached displaying the file/image, title, and description of each media record (title and description are stored in `media.custom_properties`). 

A user is editing a post with multiple images attached with titles and descriptions. There is a media record that they wish to update the image of but want to keep the title and description they have already written for it. 

Building this list view using a front-end that makes changes via an async api becomes unusually difficult. You have a collection of media records on the front end using `media.id` as the unique identifier of each list item. It is easy to update all the data of an existing media record *except* the image/file. Abstracting the updating of an existing media item by creating a new one to replace it complicates syncing the data changes with the front end as the id of the media item has changed.

I'm very surprised no one has mentioned this case before.
After digging into the code I realize adding this would take some work. I would be happy to make a PR. Would the Spatie group be open to discussing how best implement this?

**Comment by unstoppablecarl** [comment]
This is a reduced case of my current solution for updating the file of an existing media item.

I have not yet tackled triggering regeneration of the media records conversions.

```php
use Spatie\MediaLibrary\Helpers\File;

Route::post('media/{media}/update-file', function (Request $request, Media $media) {

    $newFile = $request->file('new_file');

    $fileName    = $newFile->getClientOriginalName();
    $fileName    = sanitizeFileName($fileName);
    $path        = $newFile->path();
    $currentPath = $media->getPath();
    $fileSystem  = app(\Spatie\MediaLibrary\Filesystem\Filesystem::class);

    $media->name      = pathinfo($fileName, PATHINFO_FILENAME);
    $media->file_name = $fileName;
    $media->mime_type = File::getMimetype($path);
    $media->size      = filesize($path);

    // remove the current files for this media item
    $fileSystem->removeFiles($media);

    // overwrite current file but keep old name
    $fileSystem->copyToMediaLibrary($path, $media, false, $currentPath);

    // when this model is saved, the file will be renamed appropriately to $fileName via $media->file_name
    $media->save();

    return $media;
});

function sanitizeFileName(string $fileName): string {
    return str_replace(['#', '/', '\\'], '-', $fileName);
}
```

**Comment by freekmurze** [comment]
Thank you for this code, but we're probably not going to add this feature to the package. If you want to replace a media item, just delete the old one and create a new one (with the newer files) and set its properties to the same values as the old media item.

**Comment by unstoppablecarl** [comment]
Is there a reason why? I thought I provided a reasonable case.

**Comment by Punksolid** [comment]
I also think that  ->replace($name = 'logo') would be useful

**Comment by ConstantMath** [comment]
Hello Freek, I think it could be very useful to be able update a record since you want to include a media manager in your cms where you can update some infos, upload new file, etc. 
(like in Wordpress to use a famous example ;)

**Comment by Akhibemudu** [comment]
@unstoppablecarl  @canvural Please is there a way I can upload new image[s] to an existing model? In my situation, I created a Property form that accepts multiple property images which work well, but the problem is when trying to update that Property Model to accepts more image whenever the user clicks on update form, I get the same error as above.
Here is it for update function.
`  foreach ($request->file('property_photos', []) as $key => $file) {
            $property->addMedia($file)
                ->preservingOriginal()
                ->toMediaCollection('property_image');
        }`
**For this update, I want to add more images to the existing image in the Property Model without having to delete previous uploaded image**

**Comment by unstoppablecarl** [comment]
There is not a reasonable way to do it with this package. You have to delete and create.

**Comment by danpalmieri** [comment]
I set the collection that was Single file to multiple files and I'm getting the latest one. Of course as a prune job scheduled to cleanup the old files every week.

**Comment by masitings** [comment]
```
$gallery = $event->getMedia('gallery_photo');
            $arr = [];
            foreach ($gallery as $key => $value) {
                if ($value->uuid === $request->id) {
                    $value->setCustomProperty('featured', true);
                } else {
                    $value->setCustomProperty('featured', false);
                }
                $value->save();
            }
```
You can try something like this you will match the id with the request id that you want to update.

**Comment by diazsasak** [comment]
for me i can replace the image by using this

`
Storage::disk('public')->delete($media->id.'/'.$media->file_name);
$this->photo->storeAs(strval($media->id), $name, 'public')
`

**Comment by MuhammadUsman678** [comment]
> 
**Refactor Code**
```
$media = $this->mymodel->getFirstMedia(); 
Storage::disk($media->disk)->delete($media->id.'/'.$media->file_name);
$this->photo->storeAs(strval($media->id), $media->file_name, $media->disk)
```

**Comment by masitings** [comment]
> > 
> 
> **Refactor Code**
> 
> ```
> 
> $media = $this->mymodel->getFirstMedia(); 
> 
> Storage::disk($media->disk)->delete($media->id.'/'.$media->file_name);
> 
> $this->photo->storeAs(strval($media->id), $media->file_name, $media->disk)
> 
> ```
> 
> 

I think this is more likely to delete the first media.

**Comment by hesammoosapour** [comment]
So the method updateMedia doesn't actually upload a new photo? @freekmurze

**Comment by popbosupport** [comment]
To anyone looking to extend Media with a replace function, note that this doesn't bring over any pivot values or Custom Attributes

```
use Spatie\MediaLibrary\MediaCollections\Models\Media as BaseMedia;

class Media extends BaseMedia
{
    ...
    public function replace($image_url): self
    {
        self::forceDelete();
        return $this->model->addMediaFromUrl($image_url)->toMediaCollection($this->collection_name, $this->disk);
    }
}
```

don't forget to modify config/media-library.php
`'media_model' => App\Models\Media::class,`

**Comment by mauricekindermann** [comment]
If you're using local storage and you don't want to regenerate the media ID everytime you update a file, this works

Add the trait

```php
class Media extends BaseMedia
{
    use HasFactory;
    use Concerns\CanReplaceMediaFile;
```


```php
<?php

namespace App\Models\Concerns;

use Spatie\MediaLibrary\Support\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;

trait CanReplaceMediaFile
{
    /**
     * Replace the current file while preserving the media record.
     */
    public function replace($newFile): self
    {
        // Replace the physical file
        $originalPath = $this->getPath();
        
        if ($newFile instanceof UploadedFile) {
            copy($newFile->getPathname(), $originalPath);
        } else {
            copy($newFile, $originalPath);
        }
        
        // Update metadata
        $this->update([
            'size' => filesize($originalPath),
            'mime_type' => File::getMimeType($originalPath),
            'generated_conversions' => [], // Clear so conversions regenerate
        ]);
        
        // Regenerate conversions
        \Artisan::call('media-library:regenerate', ['--ids' => $this->id]);
        
        return $this;
    }
    
}
```

Then you can use it for editing media. You may need to enable this config for livewire:

```
'version_urls' => true,
```
