### ISSUE TITLE
How to upload multiple file?

### ISSUE THREAD

**Issue by muhghazaliakbar** [spatie/laravel-medialibrary#610]
Hi, i want to upload multiple files using: `<input type="file" multiple>`

how this package handle that?

**Comment by freekmurze** [comment]
This is covered in the docs: https://docs.spatie.be/laravel-medialibrary/v5/api/adding-files#addmultiplemediafromrequest

**Comment by muhghazaliakbar** [comment]
Ah i didn't check the API docs. Thank you!
