### ISSUE TITLE
Use ProgressBar in medialibrary:regenerate

### ISSUE THREAD

**Issue by Anahkiasen** [spatie/laravel-medialibrary#611]
Currently when you launch it, if you have many models with media, you never know how long it's gonna take. Would be nice if instead of printing one line per media the package showed a ProgressBar instance

**Comment by freekmurze** [comment]
Great idea, I'd accept a PR that adds this to the package.

**Comment by markvaneijk** [comment]
PR: https://github.com/spatie/laravel-medialibrary/pull/612

**Comment by freekmurze** [comment]
Closing this, we'll handle this further in the #612
