### ISSUE TITLE
Getting a media item based on custom property and Bulk Manipulations and Updates

### ISSUE THREAD

**Issue by abishekrsrikaanth** [spatie/laravel-medialibrary#613]
Thank you for this awesome package. I have 2 questions in regards to this package

**Media By Custom Property**
Is it possible to `filter` or `find` a media item based on the custom property defined? 
For example: I currently use this on a custom CMS tool to store all the images belonging to a particular page. Assuming I have 20 different images on this tool and I want to retrieve the image for each region on the page. I store the region `id`'s as the custom property for each media item. So if I wanted to retrieve all the media items belonging to a specific id, how would i go about doing this?

**Bulk Manipulations**
Is is possible to perform the same manipulations on all the media items belonging to a NewsItem without having to repeat it per item? 
For example: 
- **Scenario 1:** I have a news item that is being posted with 10 images and I wanted to watermark all the 10 images before they are stored on S3.
- **Scenario 2:** I have 25 news items that are already on the database. My watermark file changes and I want to update all the media items across news items. How would I do this?

**Updates**
Is replacing the Item with the same file name the only option to update the media item?

**Comment by freekmurze** [comment]
**Media by custom prop**

`getMedia` returns a collection. You can perform any of the collection methods (such as `filter`)  in it.

The docs show how tho get a custom property: https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/adding-custom-properties
You can use that to filter the collection.

**Bulk**
Just add your 10 images seperately to the medialibrary. Here are the docs on defining conversions. Watermarking is supported

If you change one of your conversion (eg changing the watermark file) you should regenerate the derived files. Here are the docs on that: https://docs.spatie.be/laravel-medialibrary/v5/converting-images/regenerating-images

**Updates**
A `media` model is just an Eloquent model. You can use it to update any property you'd like. If you change the file name, the name of the file on disk will be changed as well. Replacing the files themselves isn't possible. Just delete the old media, add a new one, copy over properties manually.
