### ISSUE TITLE
[L5.4] getMedia() doesn't work (Escaping FQCN?)

### ISSUE THREAD

**Issue by 2PR3CISE** [spatie/laravel-medialibrary#614]
Hi!

If I call the `getMedia()` method to get any associated files, I always get an empty collection, but the DB has the correct data. I guess it is because of the escaping inside the `model_type` attribute.

To recreate this issue, install a fresh L5.4 copy (I also used a fresh homestead environment) and add this package (+ adding ServiceProvider and modifying e.g. `App\User` class to implement `HasMedia` and use the `HasMediaTrait` trait).
After calling `php artisan make:auth` and register a dummy user, create the following routes:

```php
Route::get('/add', function() {
    $user = \App\User::first();
    $user->addMediaFromUrl('http://www.beat102103.com/wp-content/uploads/2016/10/meh-cat_featured.png')->toMediaCollection('foo');
});

Route::get('/show', function() {
    $user = \App\User::first();
    dump($user->toArray());
    dump($user->getMedia());
});
```

The `media` table was updated after visiting `/add`: 

```
id: 1
model_id: 1
model_type: App\User
collection_name: foo
name: meh-cat_featured
file_name: meh-cat_featured.png
mime_type: image/png
disk: media
size: 503691
manipulations: []
custom_properties: []
order_column: 1
```

I guess it is because of the `model_type`, because the query, which eventually runs, is:
```sql
select * from 'media'
where 'media'.'model_id' = '1'
and 'media'.'model_id' is not null
and 'media'.'model_type' = 'App\User'
```

If I directly run this query, I don't get any results either, but I if run
```sql
select * from 'media'
where 'media'.'model_id' = '1'
and 'media'.'model_id' is not null
and 'media'.'model_type' = 'App\\\User' -- (note the multiple backslashes)
```
I get a result...

Do you have any advice for me?

Thank you very much!

Kind regards

**Comment by freekmurze** [comment]
`getMedia` only returns media in the collection named `default`.

To get media from the `foo` collection use `$model->getMedia('foo');`
