### ISSUE TITLE
Fixing documentation

### ISSUE THREAD

**Issue by tmaly1980** [spatie/laravel-medialibrary#615]
On https://docs.spatie.be/laravel-medialibrary/v5/converting-images/defining-conversions,

the documentation refers to: 

```
public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
              ->width(368)
              ->height(232)
              ->sharpen(10);
    }
```

Unfortunately, width(), height() and sharpen() are not defined in Spatie\MediaLibrary\Conversion\Conversion.php , there is however a setWidth() and setHeight() (but no setSharpen()). I'm guessing the documentation is outdated, but I don't know what else has changed to confidently update the documentation myself.

**Comment by freekmurze** [comment]
It seems like you are using `v4` in your project. The documentation you are linking to is on `v5`.
