### ISSUE TITLE
v3 issue with calling thumb url

### ISSUE THREAD

**Issue by Jafo232** [spatie/laravel-medialibrary#616]
I can't figure this out..  

Here is what I have in my model:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class FeedData extends Model implements HasMediaConversions
{
    use HasMediaTrait;

    //
    protected $table = 'feed_data';

    protected $guarded = ['id'];

    protected $casts = [
        'url' => 'string',
        'title'=> 'string',
        'description' => 'string',
        'uniqueid' => 'string',
        'feed_id' => 'integer'
    ];


    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
        ->setManipulations(['w' => config('laravel-medialibrary.thumb_width'), 'h' => config('laravel-medialibrary.thumb_height'), 'fm' => 'jpg'])
        ->performOnCollections('*')->nonQueued();

        $this->addMediaConversion('story_public')
            ->setManipulations(['fm' => 'jpg'])
            ->performOnCollections('story_images')->nonQueued();

    }

}
```

And when I call an image:

`echo " hey " . $img->getUrl();`

That works as expected, however this:

`echo " hey " . $img->getUrl('thumb');`

Throws the following error:

> ErrorException in ConversionCollection.php line 41: Argument 2 passed to Spatie\MediaLibrary\Conversion\ConversionCollection::Spatie\MediaLibrary\Conversion\{closure}() must be an instance of Spatie\MediaLibrary\Conversion\Conversion, integer given

I have regenerated images without any issue.  Any ideas?

**Comment by Jafo232** [comment]
Anyone?

**Comment by sebastiandedeyne** [comment]
What version of this package are you using?

**Comment by Jafo232** [comment]
V3.

**Comment by sebastiandedeyne** [comment]
I assume you're using Laravel 5.3, which isn't compatible with this package at that version. Is upgrading to laravel-medialibrary v4 an option?

**Comment by Jafo232** [comment]
I am using Laravel Framework 5.4.19.  We cannot run in a PHP7 environment as of yet with this project.  Is PHP7 a requirement in V4?

**Comment by sebastiandedeyne** [comment]
PHP7 is required for v4. We don't support v3 anymore since it's already two major versions old. It was never built with Laravel 5.3 in mind so I can't say what will and won't work. I'd recommend forking this repository or copying it into your project if you're stuck with a combination of PHP5 and Laravel 5.3+.

The issue at hand is that keys and values have been swapped in the closures of some collection methods. Here's the line that breaks in your sample:

https://github.com/spatie/laravel-medialibrary/blob/v3/src/Conversion/ConversionCollection.php#L41

**Comment by Jafo232** [comment]
Ok thank you so much for your help! :)

**Comment by mtarlac** [comment]
Maybe you can try something like this:

`<img src="{{ url('') }}/uploads/{{ $img->id }}/conversions/thumb.{{ substr(strrchr($img->file_name, '.'), 1) }}" alt="{{ $img->name }}">`
