### ISSUE TITLE
Load migrations and config dynamically, instead of copying

### ISSUE THREAD

**Issue by torkiljohnsen** [spatie/laravel-medialibrary#620]
Less steps to go through in the installer if you use `loadMigrationsFrom()` and `mergeConfigFrom()`.

https://laravel.com/docs/5.4/packages#migrations
https://laravel.com/docs/5.4/packages#configuration

**Comment by sebastiandedeyne** [comment]
We're already using `mergeConfigFrom` here. https://github.com/spatie/laravel-medialibrary/blob/master/src/MediaLibraryServiceProvider.php#L39

As for `loadMigrationsFrom`, we're not using it deliberately because users wouldn't be able to publish and edit the migration file.

**Comment by MannikJ** [comment]
@sebastiandedeyne @torkiljohnsen 
Why not adding a config attribute to activate and deactivate migration auto-loading as well as leaving the option of publishing and changing the migration file manually?
