### ISSUE TITLE
Default setup throws UrlCannotBeDetermined exception

### ISSUE THREAD

**Issue by sandervanhooft** [spatie/laravel-medialibrary#621]
Testing with default setup throws a UrlCannotBeDetermined exception. Any clue as to why this is happening?

```
Spatie\MediaLibrary\Exceptions\UrlCannotBeDetermined: Storagepath `` is not part of public path `/Users/Sander/Desktop/devstreet/chroniql2/public`
```

Filesystems config:
```
...
'media' => [
            'driver' => 'local',
            'root'   => public_path('media'),
            // 'url' => env('APP_URL').'/storage/media', <== if I add this I get no exception
        ],
...
```

Handling upload in controller:
```
...
$file = $animation->addMediaFromRequest('thumbnail')->toMediaCollection();
dd($file->getUrl());
...
```

Edit: I've ran `php artisan storage:link`. I am using Laravel 5.4.19 and Medialibrary 5.10.0.

**Comment by sebastiandedeyne** [comment]
Is `media` under `disks` in your config? What's the result when you run `config('filesystems.disks.media.root')`?

**Comment by sandervanhooft** [comment]
@sebastiandedeyne Thanks for responding! I've just tested again with the default settings, and I get no errors now. My best guess is that the errors were caused by a lingering config cache.

Issue can be closed for now.

**Comment by mi600** [comment]
In my case, the folder did not exist in `public/`. After creating the folder, the exception disappeared
