### ISSUE TITLE
Allow to use a different "public" directory

### ISSUE THREAD

**Issue by Xety** [spatie/laravel-medialibrary#624]
Hello,
For my Unit Tests, i want to use a custom directory to store the images. But i actually can't because it return an `UrlCannotBeDetermined` execption :
```
Storagepath `root/tests/storage/media` is not part of public path `root/public`
```
That means, to fix it, i must use `root/public/tests/storage/media` which make no sense for me.

I think you should allow to use a custom "root" directory and not constraint people to use the `public` directory.
Related code : https://github.com/spatie/laravel-medialibrary/blob/master/src/UrlGenerator/LocalUrlGenerator.php#L41-L43

Except that, you did an awesome work. Keep it up. :+1:

**Comment by freekmurze** [comment]
Hi,

if you want to use another url generator you can [create your own custom one](https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/generating-custom-urls) and set that one as in the `custom_url_generator_class` key of the `medialibrary.php` config file.

**Comment by Xety** [comment]
Oh sorry i didn't saw that before. My bad. Thanks for the fast reply.
