### ISSUE TITLE
Wrong error/exception for non-existing model

### ISSUE THREAD

**Issue by bbashy** [spatie/laravel-medialibrary#626]
Why do I get this error when I try to save media to an non-existing model (store method).

I was trying to work out what the hell was going on then realised I was trying to save the media before the model.

Is this a bug with the exception for model? It shouldn't get to the copy part if the model doesn't exist yet?

```
ErrorException in /Users/ben/Sites/project-folder/vendor/spatie/laravel-medialibrary/src/Filesystem/DefaultFilesystem.php line 45:

fopen(/private/var/tmp/phpd4DWf5): failed to open stream: No such file or directory
```

**Comment by freekmurze** [comment]
In general is't best to safe a model before adding media to it. That being said we recently added some improvements for adding media to a model that hasn't been saved yet. Behind the scenes the media will be added behind the screens after the model get saved.

Explicitly saving a media instance without a related model is asking for trouble, just don't do it 😄 

If without these pointers you can't fix your problem, could you please post some code for me to look at (or submit a failing test)?

**Comment by bbashy** [comment]
Yeah I know, forgot I wasn't working on the edit area :P

I fixed it by calling the addMedia() after saving the related model but my main question was around the error I received. Shouldn't there be a model related error?

*Confused me a little and thought my PHP was broken where it couldn't find the upload path*

**Comment by freekmurze** [comment]
Glad you could fixes the problem quick.

The error could indeed be a bit better. I'd accept a fully tested PR that improves this.
