### ISSUE TITLE
Uploads multiple images at onces.

### ISSUE THREAD

**Issue by xilwal** [spatie/laravel-medialibrary#629]
How to upload multiple files ?

**Comment by canvural** [comment]
You have methods like `addMultipleMediaFromRequest` or `addAllMediaFromRequest`. You can check those.

**Comment by xilwal** [comment]
RequestDoesNotHaveFile in RequestDoesNotHaveFile.php line 12:
The current request does not have a file in a key named `/tmp/phpZVbJ0F`.
Please help me out.

**Comment by sebastiandedeyne** [comment]
Could you share a snippet of the code you're working with?

**Comment by freekmurze** [comment]
Are you sure the request has the files you expect? Can you get the file(s) off the request manually? What code are you using to add the files?

Here's the relevant documentation of the methods @canvural mentioned: https://docs.spatie.be/laravel-medialibrary/v5/api/adding-files#addmultiplemediafromrequest

Here's a test where you can see those methods in action: https://github.com/spatie/laravel-medialibrary/blob/851441ffd1532083d8460b9446058dbee501853f/tests/FileAdder/IntegrationTest.php#L220

**Comment by xilwal** [comment]
**view:**
```
{{Form::open(array('route'=>'postmeta.store', 'method'=>'POST', 'enctype'=>'multipart/form-data' ))}}
{{Form::file('images[]', ['multiple' => 'multiple'])}}
{{Form::submit('Upload')}}
{{Form::close()}}
```
**method**
//dd($request->all());
        $post = Post::find(24);
        //$files = $request->file('images');

        $post->addMultipleMediaFromRequest($request->file('images'))->toMediaCollection('images');
        return back()->with('success', 'Uploades Successfully');
``

**Comment by freekmurze** [comment]
Which error are you getting?

**Comment by xilwal** [comment]
Error:
RequestDoesNotHaveFile in RequestDoesNotHaveFile.php line 12:
The current request does not have a file in a key named `/tmp/php3EPUCp`

**Comment by freekmurze** [comment]
`addMultipleMediaFromRequest` expects an array of key names in the `files` part of your request [like shown in the relevant test](https://github.com/spatie/laravel-medialibrary/blob/851441ffd1532083d8460b9446058dbee501853f/tests/FileAdder/IntegrationTest.php#L186).

**Comment by xilwal** [comment]
This can be a solution or not, Sir? Its work.
foreach($files as $file)
        {
        $post->addMedia($file)->toMediaCollection('images');
        }

**Comment by freekmurze** [comment]
While checking the code I noticed that `createMultipleFromRequest` currently does not work with files that are uploaded as an array (when you form element uses brackets).

I'd accept a PR that would add support for this.

The quick solution for you would be to manually loop through your upload files and add them to the medialibrary manually using `addMedia` and `toMediaCollection`.

**Comment by Vishnja** [comment]
Still doesn't seem to work
