### ISSUE TITLE
Fix PDF tests

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-medialibrary#631]
Something changed over at Travis that make all tests that touch PDFs fail. This should be fixed.

**Comment by BePsvPT** [comment]
After some searching, I found that ImageMagick may require Ghostscript to convert pdf to image.

References: [1](http://imagemagick.sourceforge.net/http/www/windows.html), [2](https://secure.php.net/manual/en/imagick.construct.php#113801), [3](https://stackoverflow.com/questions/9227014/convert-pdf-to-jpeg-with-php-and-imagemagick#comment29454734_12407686)

**Comment by freekmurze** [comment]
Yea, I think that Ghostscript was available on Travis by default, but that they changes it. Need to research on how to re-enabled it.
