### ISSUE TITLE
Softdelete record but not media

### ISSUE THREAD

**Issue by baqirfarooq** [spatie/laravel-medialibrary#632]
Currently i just try to restore record but media permanent delete!

**Comment by freekmurze** [comment]
Currently this package doesn't directly support soft deletes. If the code is simple and well tested I might accept a PR that adds support for them.

Maybe the

**Comment by vesper8** [comment]
I am also really hurting to find a workaround to prevent deletion of media rows (and the media itself) when a model is softDeleted. I know you have added logic to preserve the media itself. But I want to be able to restore the media entirely. Anyone got a workaround?
