### ISSUE TITLE
Only saving converted images

### ISSUE THREAD

**Issue by jorenvh1** [spatie/laravel-medialibrary#633]
Hey there

I'm trying to resize my images after uploading them and before saving them with medialibrary. 
I want know I can use the registerMediaConversions() method but this will still save the original image.

I don't need to keep the original image but just the resized one, how can i accomplish this? :)

**Comment by freekmurze** [comment]
Currently these is no support for storing only the conversions. If you need this manually convert the image before adding it to the medialibrary.

**Comment by jorenvh1** [comment]
Thanks for the quick response.

If I use GlideImage to convert my image before saving, I'd be saving a .tmp file.
Is there any way to rename the file before saving it?
`$img_path = $avatar->getPathName();
        $avatar_img = GlideImage::create($avatar)
                        ->modify(['w'=> 75])
                        ->save($path);

        $child->addMedia($path)
        ->withCustomProperties(['url_id' => $avatar_url_id])
        ->toMediaLibrary('avatar');`

$avatar is a temp file because it's being uploaded, so in this case I'm saving the correct image but with the temp name and .tmp extension

**Comment by freekmurze** [comment]
All your problem regarding this problem would be solved if you use our image package

https://docs.spatie.be/image/v1/introduction

Under the hood it uses Glide. We built an easy to use class on top of it.

**Comment by jorenvh1** [comment]
How would I go about using this in Laravel?

**Comment by freekmurze** [comment]
There's nothing Laravel specific in the package. Just follow the examples mentioned [in the docs](https://docs.spatie.be/image/v1/introduction)
