### ISSUE TITLE
Conditionally choosing resizing method

### ISSUE THREAD

**Issue by dror3go** [spatie/laravel-medialibrary#636]
Hi,

I'm trying to find a way to define a conversion method depending on the size of the image: If the image's dimensions are bigger than X/Y, I need to crop it. If it's smaller than X/Y - I need to leave it as is.
How can I achieve that?

Thanks

**Comment by freekmurze** [comment]
I'm thinking you're looking for  [`FIT_CONTAIN`](https://docs.spatie.be/image/v1/image-manipulations/resizing-images#fit).

Here's an example [image conversion definition](https://docs.spatie.be/laravel-medialibrary/v5/converting-images/defining-conversions):

```php
 public function registerMediaConversions()
    {
        $this->addMediaConversion('yourMediaConversion')->fit();
    }
```
