### ISSUE TITLE
Possible to copy instead of move the file?

### ISSUE THREAD

**Issue by jorenvh1** [spatie/laravel-medialibrary#637]
Hey

Is it possible to keep the original file instead of moving the file when adding it as media to a model?

I thought preservingOriginal() did this exact thing but apparently not?

**Comment by sebastiandedeyne** [comment]
It should, what does your code look like?

**Comment by jorenvh1** [comment]
Nevermind, I don't know what happened but now it works. Probably made a small mistake, but it works, thanks!
