### ISSUE TITLE
Question, possible bug?

### ISSUE THREAD

**Issue by williamoliveira** [spatie/laravel-medialibrary#639]
Shouldn't [this](https://github.com/spatie/laravel-medialibrary/blob/master/src/FileAdder/FileAdder.php#L277) be [here](https://github.com/spatie/laravel-medialibrary/blob/master/src/FileAdder/FileAdder.php#L364) ?

By the time the file is processed it would already be deleted, wouldn't it?

**Comment by freekmurze** [comment]
The current code seems ok to me.

`processMediaItem` will not delete the file.

**Comment by williamoliveira** [comment]
But in a case where the subject model [is not saved yet](https://github.com/spatie/laravel-medialibrary/blob/master/src/FileAdder/FileAdder.php#L335) and `preserveOriginal` is `false`, `processMediaItem` will be called on a [later time](https://github.com/spatie/laravel-medialibrary/blob/master/src/FileAdder/FileAdder.php#L340), the original file will be [already deleted](https://github.com/spatie/laravel-medialibrary/blob/master/src/FileAdder/FileAdder.php#L278) and it will crash

**Comment by freekmurze** [comment]
You're right. I've fixed this in the newly tagged version `5.11.1`
