### ISSUE TITLE
Images not being converted

### ISSUE THREAD

**Issue by dees040** [spatie/laravel-medialibrary#643]
I'm using Laravel 5.4.21 with medialibrary 5.11.1. I'm trying to convert some of my images, but it seems like none of the images are being converted. The following code is for updating a user it's profile picture in an API.

The user model:
```php
public function registerMediaConversions()
{
    $this->addMediaConversion('140')
        ->width(140)
        ->height(140)
        ->nonQueued();

    $this->addMediaConversion('210')
        ->width(210)
        ->height(210)
        ->nonQueued();
}
```

The file is send as binary, then converted to base64.
```php
currentUser()
    ->clearMediaCollection()
    ->addMediaFromBase64(base64_encode($request->getContent()))
    ->toMediaCollection();
```
The media folder:
![image](https://cloud.githubusercontent.com/assets/5390555/26520472/79015838-42d3-11e7-9578-3b4c8887ec3c.png)

Now when viewing the image via the API I see a perfectly fine image. But there are no conversions found for that image.

I couldn't find a solutions. Any tips?

**Comment by freekmurze** [comment]
Does your model implement `HasMediaConversions` and does it use `HasMediaTrait`?

**Comment by dees040** [comment]
It totally missed out on the `HasMediaConversions` interface. It all works now, thanks!
