### ISSUE TITLE
Using Own Model

### ISSUE THREAD

**Issue by dror3go** [spatie/laravel-medialibrary#644]
Hi,

I need to store  app-related fields for each of my media items (such as the date when the picture/video was taken, etc.), and have relationships for the media items (such as "has many people").

The docs on using own model doesn't seem to explain this too much. Should I add columns to the `media` table?
How would I create new media items, since I seem to have issues calling the `save()` method (_Field 'model_id' doesn't have a default value_, since I'm not assigning the package's fields when creating a new model)?

**Comment by canvural** [comment]
I think the custom properties is the thing you are looking for. You can read more [here](https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/adding-custom-properties).

**Comment by dror3go** [comment]
I don't think that custom properties suits my needs, cause I'll want to filter results by using these extra columns.
If you take my example for the media's date it was taken (let's call it `taken_at` column) - I need to index this column and to be able to query with stuff like SQL's BETWEEN, etc.

**Comment by IlCallo** [comment]
I think you shall add columns to the migration.
Set them as nullable or with a default value, then save the model using the library with
`$media = $user->addMedia($file)->toMediaCollection($collection)`
and update the returned instance fields you need
`$media->taken_at = $currentDate;`
`$media->save();`

**Comment by IlCallo** [comment]
On this regard, I don't know if it can be fixed in some way, but all method of the library which returns a Media model have 
`@return \Spatie\MediaLibrary\Media`
in their PHPDocs and this can create problems in the IDEs autocomplete feature if a custom model is used.

**Comment by freekmurze** [comment]
It's true that IDE's won't be able to automatically give hints for the right type. But it's better than nothing. 

If you really want type hinting you could add a phpdoc line inside your function

```php
/* @var $varName Type_Name */
```
