### ISSUE TITLE
addMediaFromUrl mime check

### ISSUE THREAD

**Issue by IlCallo** [spatie/laravel-medialibrary#645]
Hi all,
while working with the library I thought about the following use case.

- an user is asked to insert an image or an url to an image;
- he insert an url to a file which has an extensions of an image (jpg, png, other) but is in fact a script or something malevolent;
- we use addMediaFromUrl to save the media;
- the user have succesfully injected a script on our storage disk and we don't even know.

Do you think this can be considered a security bug?
Is it possible to add a parameter to the addMediaFromUrl to specify which mime types are accepted or something similar?
With normal files is easy because Laravel 5 validation understand the mime type from the content (in this library it's taken from the extension, I think it should be changed) and can be filtered, but from a remote URL we cannot check the mime type before saving the media with addMediaFromUrl.

Thoughts?

**Comment by IlCallo** [comment]
Same concern about the addMediaFromBase64 method

**Comment by freekmurze** [comment]
Thanks for reporting this. The problem can by mitigated by adding a second parameter to `addMediaFromUrl` and `addMediaFromBase64`  to pass mimetypes.

I'll take care of it soon, but if you have the time I'd accept a fully tested PR with no breaking changes.

**Comment by bhulsman** [comment]
I'll give it a try!
