### ISSUE TITLE
The current request does not have a file in a key named X

### ISSUE THREAD

**Issue by Oussama-Tn** [spatie/laravel-medialibrary#646]
Hey! Thanks for all the great packages!

The isssue i found:

> RequestDoesNotHaveFile in RequestDoesNotHaveFile.php line 12:
The current request does not have a file in a key named `/tmp/php5iH3fq`

My Routes:

```
Route::get('/medialibrary', function(){
	return view('test.medialibrary.index');
});

Route::post('/medialibrary', function(Illuminate\Http\Request $request){
  	$user = App\User::find(1);
        $user->addMediaFromRequest($request->my_file)
                 ->toMediaCollection('media');

})->name('test.medialibrary.action');
```

My view : 

```
<form action="{{ route('test.medialibrary.action') }}" enctype="multipart/form-data" method="post" class="form-create">

    <input type="hidden" name="_token" value="{{ csrf_token() }}">

    <div class="form-group">
      <label>{{trans('og.filename')}} *</label>
      <input type="file" class="form-control" name="my_file" required>
    </div>

    <button type="submit" class="btn btn-primary">{{trans('og.button.create')}}</button>

</form>
```
 
Thanks

**Comment by bhulsman** [comment]
See the documentation; https://laravel.com/docs/5.4/requests#files

> You may access uploaded files from a Illuminate\Http\Request instance using the file method or using dynamic properties. The file method returns an instance of the  Illuminate\Http\UploadedFile class, which extends the PHP SplFileInfo class and provides a variety of methods for interacting with the file.

You should use `$request->file('my_file')` instead of `$request->my_file`.

**Comment by freekmurze** [comment]
Thanks for answering this one @bhulsman

**Comment by Oussama-Tn** [comment]
Thanks! :+1:

**Comment by kikoseijo** [comment]
Came up here, in my case was the size of the file was exceeding PHP restrictions.
Happy coding!

**Comment by vwasteels** [comment]
@kikoseijo thanks a lot for this !

**Comment by jordyparks** [comment]
> Came up here, in my case was the size of the file was exceeding PHP restrictions.
> Happy coding!

THIS COMMENT SAVED MY LIFE 👍

**Comment by boryn** [comment]
> Came up here, in my case was the size of the file was exceeding PHP restrictions.
> Happy coding!

For me it was the same problem, you can read the exact error with `$request->files->get('image')->getErrorMessage();`
where I got `The file ... exceeds your upload_max_filesize ini directive (limit is 2048 KiB)`

**Comment by beregsys** [comment]
> > Came up here, in my case was the size of the file was exceeding PHP restrictions.
> > Happy coding!
> 
> For me it was the same problem, you can read the exact error with `$request->files->get('image')->getErrorMessage();`
> where I got `The file ... exceeds your upload_max_filesize ini directive (limit is 2048 KiB)`

Thank you very much, when i made dd($request->files->get('image')->getErrorMessage()) on this I got message that i have change upload_max_size in php.ini.
