### ISSUE TITLE
ClearMediaCollection() to Queue?

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#650]
Is it possible to put `clearMediaCollection()` into a queue?

This is what I'm currently doing, and it can be slow if there are a lot of media items to delete. I'd rather give the user instant feedback and then delete the collection behind the scene. I was about ready to create a new Event but thought I'd check here first.

```
public function destroy(Post $post, Request $request)
{
    if (Gate::denies('destroy', $post)) {
        abort(403);
    }

    $post->clearMediaCollection();

    $post->delete();

    if ($request->ajax()) {
        return response()->json([
            'type' => 'success'
        ]);
    }

    return redirect('/home');
}
```

**Comment by freekmurze** [comment]
I think it 'd be overkill to add a dedicated method for this to the package. I think it's best to queue the clearing of a mediacollection in your application.
