### ISSUE TITLE
Docs Issue

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#651]
Searching the docs at `https://docs.spatie.be/laravel-medialibrary/v5/introduction` puts me into results for v3.

Reproduce

Go to the URL and search for `width`. You will end up in the v3 documentation.

**Comment by freekmurze** [comment]
I'll pass this along to the nice folks at Algolia who provided this search for us.

**Comment by freekmurze** [comment]
This has been fixed.
