### ISSUE TITLE
Problem when media directory is linked

### ISSUE THREAD

**Issue by vfsoraki** [spatie/laravel-medialibrary#653]
I have deployed an app, where `public/media` directory was linked to somewhere outside `public` directory. Web server happily serves files, but the library throws an exception, telling me media folder is not inside public directory.

I dug issue a bit, and I think issue is related to [this line](https://github.com/spatie/laravel-medialibrary/blob/master/src/UrlGenerator/LocalUrlGenerator.php#L41)

        if (! starts_with($this->getStoragePath(), public_path())) {
            throw UrlCannotBeDetermined::mediaNotPubliclyAvailable($this->getStoragePath(), public_path());
        }

Maybe it should be specified in documentation too?

PS. I'm using v3 of library, but I saw the latest code and it seems it would throw the same exception.

**Comment by freekmurze** [comment]
The default `LocalUrlGenerator` expects that you store media somewhere within the public path. If in your app media is handled differently you can [write your own url generator](https://docs.spatie.be/laravel-medialibrary/v3/advanced-usage/generating-custom-urls).
