### ISSUE TITLE
MediaPathGenerator on delete

### ISSUE THREAD

**Issue by Krato** [spatie/laravel-medialibrary#655]
Hello, I have a custom path generator but I'm having problems when a model is deleted.

This is my MediaPathGenerator.php file:

```
<?php

namespace App\Helpers;

use Spatie\MediaLibrary\Media;
use Spatie\MediaLibrary\PathGenerator\PathGenerator;

class MediaPathGenerator implements PathGenerator
{
    /*
     * Get the path for the given media, relative to the root storage path.
     */
    /**
     * @param Media $media
     * @return mixed
     */
    public function getPath(Media $media): string
    {
        $model = $media->model()->withTrashed()->first();

        return $media->collection_name.'/'.$model->mediaId.'/'.$media->id.'/';
    }
    /*
     * Get the path for conversions of the given media, relative to the root storage path.
     * @return string
     */
    /**
     * @param Media $media
     * @return mixed
     */
    public function getPathForConversions(Media $media): string
    {
        $model = $media->model()->withTrashed()->first();

        return $media->collection_name.'/'.$model->mediaId.'/'.$media->id.'/c/';
    }
}
```
Is working fine when a media is generated. But when I delete a media, model is empty so it throws an error.

~~There is some way to get the model?~~

Ok, I get it using that:

```
if (!$model) {
	$model = app($media->model_type);
	$model->id = $media->model_id;
}
```

But i think that should be better way to do it yes?

Thanks

**Comment by freekmurze** [comment]
> when I delete a media, model is empty

I don't understand this part. Could you give a code example?

**Comment by GriPower** [comment]
clearMediaCollection don`t delete files if custom_path_generator_class used

**Comment by Krato** [comment]
> I don't understand this part. Could you give a code example?

Is on the question. I will tell you. I generate custom paths for each media including a model mutator and a media collection.

For example, thi is the path for collection `properties` and Model id 6.

So using this Custom Path Generator, the vars will be:

```
$media->collection_name = 256956ab-b067-54b3-8873-f6ef0fadce64 // The uuid for word 'properties'
$model->mediaId =a6c4fc8f-6950-51de-a9ae-2c519c465071 // Mutator giving a uuid for the model
$media->id = 38 // The media ID

So the final path will be:
media/256956ab-b067-54b3-8873-f6ef0fadce64/a6c4fc8f-6950-51de-a9ae-2c519c465071/38
```

This is working fine. But I have the error when deleting a model, because `$media->model` is nothing. Any way to get the `$media->model` when deleting a model?

Jajaja, hope you understand.

Regards!

**Comment by freekmurze** [comment]
By default if you delete a `model` it's attached `media` will be deleted as well. And this should work even if you use a custom path generator. If you're still having troubles with this could you PR a failing test for me to fix?
