### ISSUE TITLE
duplicate and attach a media to an item

### ISSUE THREAD

**Issue by Rostom22** [spatie/laravel-medialibrary#657]
Hi, i'm using this package for attached files in a private messaging system, now i'm trying to add forward feature to the system but i don't know how to attach media of the forwarded message to the new message ? (i'm sending the ids of the media to my controller) thanks for any help.

**Comment by freekmurze** [comment]
Hi, 

this whole package is been set up around a one to many relation between a model and media. If you need a many to many relation take a look at the [laravel-mediable](https://www.plankdesign.com/en/journal/introducing-laravel-mediable) package.
