### ISSUE TITLE
Custom headers for conversions

### ISSUE THREAD

**Issue by williamoliveira** [spatie/laravel-medialibrary#659]
I noticed that `$fileAdder->addCustomHeaders()` only adds headers for the original file, is there a way to add custom headers for conversions as well? 

My goal is to add `['visibility' => 'public']` to make s3 files publicly accessible, but currently its only working for the original files

**Comment by freekmurze** [comment]
Currently this is not possible. You could solve this by setting the right permission via a policy on S3 itself. If this can be solved in a simple non breaking way, I'd accept a fully tested PR that adds this to the package.
