### ISSUE TITLE
Eager loading media with nested select

### ISSUE THREAD

**Issue by g33kcentric** [spatie/laravel-medialibrary#66]
Hello! 

I have a feeling this is a Laravel specific question, rather than an issue with this package so I apologise if this isn't the proper forum for this question. 

I have a custom eloquent query: 

    return $this->with(['user' => function($query) {
            $query->select('id', 'username');
        }])->paginate(15, ['slug', 'name', 'image', 'created_at', 'user_id']);

this works fine, however when i try to also load media in the 'with' array, i get get an empty collection, i know this has something to do with the last select array, as if i take user_id out, i get an empty user item. 

But because media is a polymorphic relationship, there is no field i can reference on my model for media. 

I could just remove all the specific field selects, but I have a thing with not wanting to use SELECT * statements! 

Thank you :)

**Comment by freekmurze** [comment]
Hi,

I can't see the immediate cause or solution, but suspect the problem isn't releated to this package.

Try asking your question on of these excellent places:
- [laracasts forum](https://laracasts.com/discuss)
- [larachat](http://larachat.co/)
- [laravel.io forums](http://laravel.io/forum)
