### ISSUE TITLE
Class App\Handlers\Commands\Spatie\MediaLibrary\Jobs\PerformConversionsHandler does not exist

### ISSUE THREAD

**Issue by nasirkhan** [spatie/laravel-medialibrary#661]
I was trying to use the `laravel-medialibray` with my Laravel (5.1) application. I installed v4 of the package and handling the upload, attach, delete an image is ok. 
While i configured the model for conversions it gaves the following error.

`
Class App\Handlers\Commands\Spatie\MediaLibrary\Jobs\PerformConversionsHandler does not exist
`

Here is the Model i am using, 

```
namespace App;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;

class Organizer extends BaseModel implements HasMediaConversions
{
    use HasMediaTrait;

    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
             ->setManipulations(['w' => 200, 'h' => 300])
             ->performOnCollections('*');
    }

More code ...
```

currently i reverted the conversion code, need assistance to resolve this issue.

**Comment by canvural** [comment]
Sounds like a missing import or missing `\` Double check  the imports.

**Comment by nasirkhan** [comment]
@canvural thanks for your response. 
i did not fully understand your feedback. As i mentioned above. if i implement `HasMedia` it works perfectly. But when i changed to `HasMediaConversions` and add the method `registerMediaConversions` it starts to show the error.

**Comment by freekmurze** [comment]
We don't support `v4` anymore. Is it possible to upgrade your application so `v5` can be used?

**Comment by nasirkhan** [comment]
@freekmurze thanks for informing that you discontinued the support. I will really appropriate if you please add this notice on the introduction page of v4. I did not find such notice in any place of the v4 doc.  Otherwise i would not use this package. 

My application is developed based on Laravel 5.1. As this is the only long time support version till now and did not ended the support as yours, we do not have any plan to upgrade the version now. But after the L5.5 release we believe we would do so. 

I thought the Spatie team was more responsible and dependable.

**Comment by freekmurze** [comment]
> I thought the Spatie team was more responsible and dependable.

We've never made it a secret that we like developing with the latest versions of the stuff and think that sticking to LTS releases is a very bad idea.

If you are disappointed in our decision to not support an older version of Laravel, please consider that we do all of this work in our spare time. It's kinda strange that you think we should work for free on stuff that we don't need ourselves anymore.

When using open source always keep in mind that you should either know your requirements enough so you can fix bugs yourself or that it should be easy to switch to another package.
