### ISSUE TITLE
How can set a default image for file types that is not image?

### ISSUE THREAD

**Issue by codeitlikemiley** [spatie/laravel-medialibrary#662]
Let say im using a .doc , 

i want to use an image with of microsoft word pic 

that is already in my images...

Can someone guide me on this?

Also if you can share your own method, of how to accomplish this...

thanks

**Comment by freekmurze** [comment]
I don't really understand your question. 

Maybe this is what you need?

https://docs.spatie.be/laravel-medialibrary/v5/converting-other-file-types/creating-a-custom-image-generator

**Comment by Childplan** [comment]
I think this is the same as a question that I have - which is:

If the file uploaded is not an image (.jpg / .png) and is another file type such as a MS Word file (.doc / .docx) or PDF then is there an easy way to display the default icon for that file type.  For most non image doc types it makes more sense to display an icon than a thumbnail of the document itself.

Many thanks

**Comment by freekmurze** [comment]
You can just use the `mime_type` (or maybe just the extension of the original file) saved in a `Media` object to decide in your view which icon should be displayed.

If you need to generate something specific (eg a thumbnail of the contents). You can use the aforementioned custom image generator.
