### ISSUE TITLE
Undefined method toMediaCollection?

### ISSUE THREAD

**Issue by Wolrab1** [spatie/laravel-medialibrary#664]
Hi guys,

Edit: I can use toMediaLibrary() however in the documentation it says use toMediaCollection();

Fresh install of this media library and I am getting the following error when trying to attach a image to a product.

```
        $product = Product::FindOrFail(1);

        $url = 'Path to image on the web';
        $product
           ->addMediaFromUrl($url)
           ->toMediaCollection();
```

> Call to undefined method Spatie\MediaLibrary\FileAdder\FileAdder::toMediaCollection() 

I can confirm in my Product model I have the following defined.

```
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

class Product extends Model implements HasMedia
{
    //use Searchable;
    use HasMediaTrait;
```

I'm using Laravel 5.4 and "spatie/laravel-medialibrary": "5.0.0",

**Comment by freekmurze** [comment]
The Truth (aka [the source code(https://github.com/spatie/laravel-medialibrary/blob/master/src/FileAdder/FileAdder.php#L249)) says that `toMediaCollection`is the right method name. Are you sure you're using `v5`?

**Comment by sebeq** [comment]
Hello,

I am working one the same setup (Laravel 5.4) and "spatie/laravel-medialibrary": "5.0.0" and having the same issue.

Method toMediaCollection() cannot be found, however, toMediaLibrary() works.

@Wolrab1: Are the conversions working well for you? Not sure if connected with function name, but when defining:

`
public function registerMediaConversions()
    {
        $this->addMediaConversion("box")
            ->crop(Manipulations::CROP_CENTER, 382, 189)
            ->performOnCollections("images", "gallery");

        $this->addMediaConversion("thumb")
            ->crop(Manipulations::CROP_CENTER, 100, 100)
            ->performOnCollections('images', 'gallery');

        $this->addMediaConversion('small')
            ->width(300)
            ->height(200)
            ->performOnCollections('images', 'gallery');

        $this->addMediaConversion('medium')
            ->width(1024)
            ->height(768)
            ->performOnCollections('images', 'gallery');

        $this->addMediaConversion('large')
            ->width(1920)
            ->height(1080)
            ->performOnCollections('images', 'gallery');
    }
`
I can get only original picture and first defined conversion. 
When using `$model->getFirstMediaUrl("gallery")` I'm able to get source file, but `$model->getFirstMediaUrl("gallery", "thumb")` (or any other - small, medium, large) always return "box".

When changing order e.g. "large" conversion set as first one - function will always return "large".

Files are created properly and exists on a filesystem.

**Comment by freekmurze** [comment]
You shouldn't pass collection names such as `images`, `gallery` to `getFirstMediaUrl`, but rather conversion names such as (in your case) `thumb`, `small`, `medium` and `large`.

**Comment by sebeq** [comment]
Of course you are right, but still not working. I've got other example:

```
@foreach($content->getMedia('gallery') as $row)
                    <a class="colorbox" rel="gallery" href="{{ $row->getUrl('large') }}"><img src="{{ $row->getUrl('thumb') }}" alt="grid"></a>
@endforeach
```

If I understand correctly - `HREF` should link to `large` conversion and `img` should show `thumb` .. but both show `box` converted file (defined as the first of conversions). Files are available on the drive (generated correctly).

**Comment by freekmurze** [comment]
Our tests (included in the package) indicate that this should be working as indented. 

Try installing the package in a vanilla Laravel app, define one conversion and try to get en url of that. If that works, try adding another conversion.

**Comment by sebeq** [comment]
For both issues solution is to update source by hand. Composer update, removal, reinstall did not help. But simple file update solve both issues.
