### ISSUE TITLE
Artisan medialibrary:clean orphan file not working when using custom path

### ISSUE THREAD

**Issue by muswanto** [spatie/laravel-medialibrary#665]
Hai, thank u for usefull package. :100: 
I've an issue when using custom path and custom id. Delete orphan file is not working. This's my configuration:

- Using guid as id for media database record
- Using custom path {year}{month}/{guid} (ex : 20170501/11e73a8029ef95bc976b3389a49dd6ec)

Everything is working well exept clean up command. I want to clean all orphan file but not working, i see in command code, it's not check if using custom path. Thank you very much for your help... :+1:

**Comment by freekmurze** [comment]
Currently cleaning orphaned files only works if you're not using custom paths. 

If you need this to work for custom paths, I'd accept a fully tested, backwards compatible PR.

**Comment by freekmurze** [comment]
Conversation contiunes in #677
