### ISSUE TITLE
Own sortable trait versus sortable package functionality

### ISSUE THREAD

**Issue by emielmolenaar** [spatie/laravel-medialibrary#667]
Is there a reason this package uses it's own sortable stuff instead of just adopting your https://github.com/spatie/eloquent-sortable package?

The https://github.com/spatie/eloquent-sortable package facilitates a `buildSortQuery` method which can be overridden, which can be very useful :smiley:

**Comment by sebastiandedeyne** [comment]
It's been a while, but I think we opted to not use the sortable package because it would give issues when we want to bump a major version, and people (like us) are using both packages in their apps.

**Comment by emielmolenaar** [comment]
All right, OK. I am looking for a nice clean way to fill up `order_column` with a value per model. Ended up overriding `getHighestOrderNumber` and modifying the query there. It works OK for now, but something like a `buildSortQuery` method which can be overriden is a bit of a cleaner and more future proof way I guess.

Thanks!
