### ISSUE TITLE
InvalidConversion There is no conversion named `thumb`

### ISSUE THREAD

**Issue by rezaple** [spatie/laravel-medialibrary#669]
Wheh i try this code, its working
`$user= Auth::user();
        return $user->getMedia('images')->first()->getUrl();`

but when i change to
`$user= Auth::user();
        return $user->getMedia('images')->first()->getUrl('thumb');`

it's getting error

here is my model look likes
`    

    use HasRoles;

    use LogsActivity;

    use HasMediaTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getDescriptionForEvent(string $eventName): string
    {
        return "This model has been {$eventName}";
    }

    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
             ->setManipulations(['w' => 368, 'h' => 232])
             ->performOnCollections('images');
    }
`

**Comment by freekmurze** [comment]
Did you implement the `HasMediaConversions` trait [mentioned in the docs](https://docs.spatie.be/laravel-medialibrary/v5/converting-images/defining-conversions)
