### ISSUE TITLE
Trait delete method conflict

### ISSUE THREAD

**Issue by a-komarev** [spatie/laravel-medialibrary#67]
>Trait method delete has not been applied, because there are collisions with other trait methods

Conflicting with `EntityTrait` in https://cartalyst.com/manual/attributes/1.0 package.

**Comment by freekmurze** [comment]
Could you describe the problem with a bit more detail?

**Comment by a-komarev** [comment]
`EntityTrait` from Cartalyst Attribute package got `public function delete()` method already.

If you want to use both of the traits in one model there is an error that delete method already exists in other trait.

Renaming delete method in your package trait wouldn't work because in case of model delete it will be just skipped then. Is there a way to attach it as event?

**Comment by freekmurze** [comment]
This package does not have a `delete()`-method in it's trait and already listens to a delete event. It seems to me this problem must be solved at Cartalyst's end.

**Comment by a-komarev** [comment]
This method is raising a conflict: https://github.com/spatie/laravel-medialibrary/blob/master/src/HasMedia/HasMediaTrait.php#L249

**Comment by freekmurze** [comment]
My bad, forgot that we had that. Like stated in the comments, we still have to figured out why the model event isn't working properly. As soon as we have figured that out we can drop the `delete`-method.

**Comment by freekmurze** [comment]
Will fix in a future major version.

**Comment by hugofabricio** [comment]
@freekmurze When will be fixed?

**Comment by freekmurze** [comment]
You can solve this in your application by listening to eloquent delete events and checking if the deleted model implements the `hasMediaConversions`-interface.

It won't be fixed in v3, but I'll try to make it better in the next major version which 'll be released somewhere this year.

**Comment by hugofabricio** [comment]
Thank you.

**Comment by a-komarev** [comment]
@hugofabricio @freekmurze I've shared my solution #182. Maybe you'll find it helpful.

**Comment by freekmurze** [comment]
I've decided not to pull in that solution. I'll solve this problem in the next major version of the package. 

If you are having problems with the `EntityTrait` from Cartalyst be sure to take a look at the code in #182.

**Comment by freekmurze** [comment]
This issue is fixed in v3.16.1
