### ISSUE TITLE
Need help adding variables to Conversions

### ISSUE THREAD

**Issue by DigicreateJens** [spatie/laravel-medialibrary#670]
Hi,

I'm currently testing out your package for a future project of mine, but I need help with something. Namely: adding variables to conversions. When saving a media file, I currently also add `custom_properties` to the media in question. Among other properties, I also add `focalX` and `focalY` to these properties to be used in the `focalCrop` conversion.

But how do I access these properties from my model or from the `registerMediaConversions` method?

Thanks in advance!

**Comment by freekmurze** [comment]
Great that you're trying out medialibrary. I hope you like it.

You can access variables of a model from inside `registerMediaConversion`. The way you can achieve media specific conversions is by using the `manipulations` property on a `Media` model.

More info here: https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/storing-media-specific-manipulations

Does that answer your question?

**Comment by DigicreateJens** [comment]
I do indeed like the package, thanks!

So I cannot use the _custom_properties_ of a `Media` model in `registerMediaConversions`? It's not 100% clear how this would work with the `focalX` and `focalY` properties I'm trying to add to the model.

**Comment by DigicreateJens** [comment]
Basically what I'm trying to make is a focus-crop plugin where the user can set a point on an image before it's uploaded. This point is then saved in the `custom_properties` of the uploaded media as `focalX` and `focalY`. But now I want to use these `custom_properties` when using the `focalCrop` function in the `registerMediaConversions` function.

So in a perfect world I would be able to add the following code to my own Models' _registerMediaConversions_ method:

`
$this->addMediaConversion('thumb')->focalCrop(400, 60, $media->getCustomProperty('focalX'), $media->getCustomProperty('focalY'));
`

Any tips on how I could achieve something like this?

**Comment by DigicreateJens** [comment]
@freekmurze I have created a [Pull Request](https://github.com/spatie/laravel-medialibrary/pull/672) as I have found a way to do what I described above. If I did anything wrong in the PR, please let me know as this is the first time I'm doing something like this to an _official_ repository.

**Comment by freekmurze** [comment]
Closing this. Conversion continues in #672
