### ISSUE TITLE
Request: Store main image and converted images sizes (in px) in media table

### ISSUE THREAD

**Issue by vedmant** [spatie/laravel-medialibrary#671]
I see that images sizes (in pixels) are not stored in media table, I think this is important for many cases. In my case I need sizes for lazy loading placeholder cause images aspect ratio is variable. Reading sizes from the disk every time will be much less efficient.

**Comment by freekmurze** [comment]
Couldn't you introduce some caching layer in your app where you would only read an image once and cache it's dimension?

An alternative to adding your own caching storage, would be to use a media's custom properties to store the dimensions. More info on custom properties here: https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/adding-custom-properties

**Comment by vedmant** [comment]
Thanks, yeah I can utilize MediaHasBeenAdded and ConversionHasBeenCompleted events and add dimensions to custom properties, but I was thinking that it's something that good to have out of the box, most of media files have dimensions, all images and videos.

**Comment by freekmurze** [comment]
I'll revisit this issue when creating a new major release next year.
