### ISSUE TITLE
Silly noob question about adding multiple files

### ISSUE THREAD

**Issue by HelgeSverre** [spatie/laravel-medialibrary#673]
I'e looked around in the API and the documentation but has not found a good example that deals with the scenario where I have 1 file input in my form that accepts multiple files, and I want all of these files to be added to my model.

I have written this mess right here and it works as I expect, however, is there a cleaner or better way to do this?

```php
<?php

collect($model->addMultipleMediaFromRequest(["images"])
    ->first())
    ->each(function ($adder) {
        $adder->toMediaLibrary();
    });
```

i collect the result from addMultipleMediaFromRequest because it returns an array (with only 1 item...) and need to loop through each fileAdder objects within that item.

The ideal syntax would be something like this:

```php
<?php

$model->addMultipleMediaFromRequest("images")
    ->each(function ($adder) {
        $adder->toMediaLibrary();
    });


// Even better
$model
    ->addMultipleMediaFromRequest("images")
    ->allToMediaLibrary();
```

Any tips on this would be great, I really like this package, but I think the documentation and DevUX for common issues like this should be easier to use/find and get going quickly.

**Comment by sebastiandedeyne** [comment]
There was a bug regarding adding multiple media, it should be fixed in version 5.12.1.

This syntax should do the trick:

```php
$model->addMultipleMediaFromRequest(["images"])
    ->each(function ($fileAdder) {
        $fileAdder->toMediaCollection();
    });
```

I think you could use `Collection`'s higher order methods too...

```php
$model->addMultipleMediaFromRequest(["images"])->each->toMediaCollection();
```
