### ISSUE TITLE
Max File Size by mime type

### ISSUE THREAD

**Issue by abishekrsrikaanth** [spatie/laravel-medialibrary#674]
Am not sure if this has been asked or requested before, but could you consider an enhancement to add Max File Size by mime types? This might help in cases where one would like to upload a video of upto 25mb but limit images to just 10mb.

**Comment by freekmurze** [comment]
Thanks for your suggestion, but I'm thinking that there's only a small minority of users that need this functionality. The ones who do can easily add this check in their own projects.

**Comment by elshobokshy** [comment]
Up
