### ISSUE TITLE
Specify folder for S3 storage

### ISSUE THREAD

**Issue by wsray** [spatie/laravel-medialibrary#675]
Is it possible to specify a path for S3 storage?

This problem manifests when using a multi-environment setup. I have 4 environments, local, dev, stage and production ... all using a single bucket. When the DB ids for a media object clash they overwrite each other.

Perhaps I'm approaching this incorrectly, any advice is appreciated.

**Comment by bobinrinder** [comment]
Check out this part of the documentation:
[https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/using-a-custom-directory-structure#using-a-custom-directory-structure](https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/using-a-custom-directory-structure#using-a-custom-directory-structure)

I assume you could just add a config var with a folder path to those functions, then you can you change that config var for each environment.

**Comment by wsray** [comment]
This is perfect and much netter than I hoped for. I've implemented and it's working as expected. Thanks for helping me with this. I'll be sure to RTFM next time :)

I owe you guys a few postcards.

**Comment by mindmergedesign** [comment]
@wsray would you mind sharing how you implemented this? I am not really sure where to add the config file containing the functions.

**Comment by wsray** [comment]
@mindmergedesign of course, info below.

In my app I have a namespace `App\Helpers` within this namespace I created a class called `EnvironmentPathGenerator` the contents of this class are at the end of this comment, but it's really simple and basically just prepends the env to the file path.

In order to make use of the custom path generator class, I then needed to update the file `config/medialibrary.php` and point the configuration variable `custom_path_generator_class` at my custom path generator class.

My configuration change within `config/medialibrary.php` is as follows -

`'custom_path_generator_class' => App\Helpers\EnvironmentPathGenerator::class,`

```
namespace App\Helpers;

use Spatie\MediaLibrary\Media;
use Spatie\MediaLibrary\PathGenerator\PathGenerator;

class EnvironmentPathGenerator implements PathGenerator
{
    protected $path;

    public function __construct()
    {
        $this->path = app()->env . '/';
    }

    public function getPath(Media $media) : string
    {
        return $this->path . $media->id . '/';
    }

    public function getPathForConversions(Media $media) : string
    {
        return $this->getPath($media) . 'conversions/';
    }
}
```

**Comment by mindmergedesign** [comment]
@wsray Thank you so much! I'll give it a try later today.

**Comment by mindmergedesign** [comment]
@wsray it worked perfectly, Thanks again!

**Comment by Pixelworlds** [comment]
Its good to note that the import has changed from `use Spatie\MediaLibrary\Media;` to `use Spatie\MediaLibrary\Models\Media;`

**Comment by connecteev** [comment]
Updated for medialibrary v7:

```
<?php

namespace App\Helpers;

use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\PathGenerator\PathGenerator;

// Customize the path where the image gets stored (on the local filesystem, on S3, etc)
class EnvironmentPathGenerator implements PathGenerator
{
    protected $path;

    public function __construct()
    {
        $this->path = app()->env . "/user-images/";
    }

    public function getPath(Media $media): string
    {
        return $this->path . $media->id . "/";
    }

    public function getPathForConversions(Media $media): string
    {
        return $this->getPath($media) . "conversions/";
    }

    public function getPathForResponsiveImages(Media $media): string
    {
        return $this->getPath($media) . "responsive/";
    }
}


```
