### ISSUE TITLE
getMedia returns all collections with any param

### ISSUE THREAD

**Issue by gsabater** [spatie/laravel-medialibrary#676]
Hello there,

I'm just having an issue with getMedia.
I'm just querying the media attached to a specific model element, and i want to get the images in a single collection:
```
$media = Post::find(1);
$media->getMedia('medialib');
```
This code returns me the exact same number of results than `$media->getMedia('images');`
as you can see in this screenshot, i'm gettign mixed collections in results.

![mixed](https://user-images.githubusercontent.com/8863225/28184099-4f47cc20-6812-11e7-8d2c-4afdba2943a2.PNG)

Using spatie/laravel-medialibrary 5.12

**Comment by freekmurze** [comment]
Could you PR a failing test that demonstrates the bug?

**Comment by gsabater** [comment]
@freekmurze I'm sorry but i don't actually know how to do tests.

**Comment by freekmurze** [comment]
Testing is not that difficult. It's just basically writing some code that does the same as in a normal application.

This package includes this test that proves that the `getMedia` function is working properly when a collection name is passed through it: https://github.com/spatie/laravel-medialibrary/blob/master/tests/HasMediaTrait/GetMediaTest.php#L64-L71

**Comment by gsabater** [comment]
@freekmurze Now i don't have time to perform the tests.
I will close the issue and i will repoen it again when i have them done.

Thanks
