### ISSUE TITLE
Defining Media Conversions by mime type

### ISSUE THREAD

**Issue by abishekrsrikaanth** [spatie/laravel-medialibrary#678]
On the model when the `registerMediaConversions` is used to define conversion for each file that is attached, is it possible to run media conversions based on the mime type? 

I have a model that can have both video and images as a media. I want to watermark either, but the code for watermarking a video is different from watermarking an image file. Would it be possible to check for the `mime` type within the `registerMediaConversions` function and run conversions accordingly?

On the same note, is it also possible to define a file system per conversion that is defined on `registerMediaConversions`. I use S3 as my Filesystem and I want the original file to go to a secured bucket and the thumbnail to go to another bucket. I have to disks setup on my config, but not sure how to separate them based on the conversion

**Comment by freekmurze** [comment]
I believe you can achieve the watermarking by using custom image generators: https://docs.spatie.be/laravel-medialibrary/v5/converting-other-file-types/creating-a-custom-image-generator.

File systems per conversion are not supported. I'd accept a PR that adds that to the package if the code is not too complex, non-breaking and well tested.
