### ISSUE TITLE
Watermarking a Video

### ISSUE THREAD

**Issue by abishekrsrikaanth** [spatie/laravel-medialibrary#679]
Does this library support watermarking a video? When I try to use the watermark code on a video, it creates a thumbnail of the video and watermarks the thumbnail.

```
$this->addMediaConversion('video_watermark')
            ->watermark(public_path('/assets/admin/img/test_watermark.png'))
            ->watermarkPosition(Manipulations::POSITION_CENTER)
            ->performOnCollections('library_item_video');
```

Is there anything in addition to this that I need to do?

**Comment by freekmurze** [comment]
This package cannot watermark a video, only images.

If you want to watermark a video you must do that yourself before adding the video to the medialibrary.
