### ISSUE TITLE
Ability to upload temporary images

### ISSUE THREAD

**Issue by a-komarev** [spatie/laravel-medialibrary#68]
Proposal for a new feature. Use case:

1. User coming to website as guest and proceeding to registration.
2. On registration he uploading his photo. Then he reloading page or if it's multi-step form - changing step.
3. Because image could be attached only after successful model creation there could be an option to store upload temporary in `temp` folder.
4. Place name of temp file in session.
5. After registration have an ability to retrieve temporary filename, persist it and attach to model.

**Comment by freekmurze** [comment]
The behaviour you're describing lies beyond the scope of this package. Your application should handle this. Here's how a do it in my projects (simplified version):

1. Add a field temp to the model.
2. When adding a new entity already persist it with the temp value of 1
3. Now you model can already have media
4. When succesfully having stored the entity for the first time set it's temp flag to false.

I've got a daily job running that cleans up the temp records.

There are multiple ways to do it, this is only how I do it. See if that fits your project.

**Comment by a-komarev** [comment]
Thank you for the idea. I think it's a pretty good solution.

**Comment by a-komarev** [comment]
@freekmurze Excuse me that bumping up this issue again. But is there a way to upload media without attaching it to model with your package? Because in use case described by you 2nd point requires it.

**Comment by freekmurze** [comment]
Media is always attached to a model. But you can mark uploaded media as tempory as wel by [using a custom property](http://medialibrary.spatie.be/v3/advanced-usage/adding-custom-properties/).

**Comment by a-komarev** [comment]
So, in this case there is only way to add an hidden model which will hold all temporary records then. Because media could be uploaded before model is created.

I know that's not a great behaviour, but customer want exactly this flow. Media uploaded > Model created.

**Comment by freekmurze** [comment]
Yeah, it's a bit of a hassle. So I always created a model first, mark it as temporary. If the user finishes the flow, remove the temporary flag for the model/media.

**Comment by a-komarev** [comment]
Thanks again, Freek.

Now I'm clearly see that I will need draft status not only for articles, pages and other common models which has it, but for users too.

**Comment by freekmurze** [comment]
Np!

In my projects almost every table has a draft (aka temp) field with a default value of 1. All models have a draftable trait which sets the temp field to false when a record is updated for the first time.

**Comment by a-komarev** [comment]
I thought about using `status` field for states `draft`, `unapproved`, `approved` and etc... why do you think separate field is better?

**Comment by sonuku** [comment]
Hmm,
Could you just upload, store reference to a temp file in session array/volatile state, then move/attach the file later using an ORM event?
All you’d need to do was track a form unique id against your temp files, then hook into Laravel’s saving event.

Seems like more of an application workflow requirement than this libraries responsibility?

**Comment by a-komarev** [comment]
@sonuku Yes, Freek said it in his first reply, I'm just trying to find the best way to do it. Right now I'm doing exactly what you've described. Saving file temporary and then move it from temporary directory to media library after model creation.
