### ISSUE TITLE
Media Conversions collection specific

### ISSUE THREAD

**Issue by bobinrinder** [spatie/laravel-medialibrary#681]
Hello,

I ran into an issue that was a little unexpected for me:
The media conversions are not collection specific, which I find a little unfortunate. 
I have multiple collections on a model for different kinds of images and I thought I am consistent and stick with the same naming conventions for the conversions (large, regular, small, thumb) for each collection, so the front-end developer does not have to figure out the naming of the conversion every time.

Looks like this:
     
        $this->addMediaConversion('large')`
            ->width(1920)
            ->height(1080)
            ->performOnCollections('project-images-full-hd');

        $this->addMediaConversion('regular')
            ->width(960)
            ->height(540)
            ->performOnCollections('project-images-full-hd');

        $this->addMediaConversion('large')
            ->width(1440)
            ->height(1080)
            ->performOnCollections('project-images-4-by-3');

        $this->addMediaConversion('regular')
            ->width(720)
            ->height(540)
            ->performOnCollections('project-images-4-by-3');

Sadly this is not possible so far (from what I can see)!?

Another (even better solution) would be, if the conversion width and height manipulations accept a percentage. Then I could define the 4 responsive conversions once (75%, 50%, 25%) and it would not even need to be collection specific.

Maybe like this:

        $this->addMediaConversion('large')`
            ->widthByPercentage(75)
            ->heightByPercentage(75);

        $this->addMediaConversion('regular')
            ->widthByPercentage(50)
            ->heightByPercentage(50);

Any thoughts or ideas to that issue? :)

Thanks,
Robin

**Comment by freekmurze** [comment]
> The media conversions are not collection specific

They are collection specific. 

```
    $this->addMediaConversion('large')`
        ->width(1920)
        ->height(1080)
        ->performOnCollections('project-images-full-hd');
```

This will conversion will only be performed on the `project-images-full-hd` collection. If want it on all collections, leave off `->performOnCollections('project-images-full-hd')`.

Your second question regarding:

```
 $this->addMediaConversion('large')`
        ->widthByPercentage(75)
        ->heightByPercentage(75);
```

The underlying image package does not support percentages. You can make calculations of the desired with and height in your own project and then use media specific conversions: https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/storing-media-specific-manipulations

**Comment by bobinrinder** [comment]
Thanks for your reply.
By collection specific I meant that the name of the conversion can exist once in each collection. I ran into trouble as I had a conversion with the name `large` three times on the same model but differently configured for each collection (as I tried to demonstrate with the code above). Which means I cannot give the same name to multiple conversions in the same model, although each conversion is aiming at a different collection.

**Comment by freekmurze** [comment]
Ok, I think we're on the same page now.

What you could do to make your designers happy is to define your conversions like this:

```php
    $this->addMediaConversion('large-project-images-full-hd')
        ->width(1920)
        ->height(1080)
        ->performOnCollections('project-images-full-hd');
```

You could use [a custom Media model](https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/using-your-own-model) and start override methods such as `getMediaUrl` like this:

```php
// in your custom media model that extends the media model shipped by this package
    public function getUrl(string $conversionName = ''): string
    {
        return parent::getUrl("{$conversionName}-{$this->collection_name}");
    }
```

**Comment by bobinrinder** [comment]
That seems like a neat solution, I will give that a try! :)
Thank you very much! 👍
