### ISSUE TITLE
PHP memory exhausted when uploading big images

### ISSUE THREAD

**Issue by yinx** [spatie/laravel-medialibrary#682]
When uploading a big image( 3mb+, 2000x6000, ...) PHP runs out of memory.
I have already increased the memory limit but I can't keep increasing it.

I also tried putting the conversions on a queue but then the queue displays the exact same error and  even quits the queueworker, it doesn't even try again.

It seems that the moment any conversion is added, the memory usage skyrockets, even with only one conversion.

Is there any way to deal with this? At least so it doesn't give a 500 error on upload.
I could use the queue, then it doesn't throw a 500 error but then no conversions will ever be added since the queue worker stops the moment it gets that memory error.

**Comment by freekmurze** [comment]
For unpacking a big image PHP just needs a lot of memory. There's no way around that. 

Here's a calculator that show how much memory you need: http://www.dotsamazing.com/en/labs/phpmemorylimit
