### ISSUE TITLE
Exception in Media:php

### ISSUE THREAD

**Issue by giorgiomen** [spatie/laravel-medialibrary#684]
Hi,
thank you for all your amazing packages.
I've installed your package in a fresh laravel project and found this error in laravel.log
local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Default value for parameters with a class type hint can only be NULL' in /home/giorgio/myproject/vendor/spatie/laravel-medialibrary/src/Media.php:49

Can you help me solve this?

Thank you

**Comment by freekmurze** [comment]
Could you PR a failing test for me to look at?

**Comment by giorgiomen** [comment]
Solved. The problem was php 5.6. Using php7, it works fine.

Thank you
