### ISSUE TITLE
Problem with symbolic links storage paths with LocalUrlGenerator

### ISSUE THREAD

**Issue by williamoliveira** [spatie/laravel-medialibrary#686]
As this line uses `realpath`:
https://github.com/spatie/laravel-medialibrary/blob/master/src/UrlGenerator/LocalUrlGenerator.php#L63
we cannot use symliked paths outside /public
is there a reason to why `realpath` is used here?

an example of an error I am having:
```
Next ErrorException: Storagepath `/home/user/app/shared/public/media` is not part of public path `/home/user/app/releases/22/public` in /home/user/app/releases/22/vendor/spatie/laravel-medialibrary/src/Exceptions/UrlCannotBeDetermined.php:11
```
my symlink looks like this: `/home/user/app/releases/22/public/media -> /home/user/app/shared/public/media`

**Comment by freekmurze** [comment]
Modifying this behaviour now would be a breaking chance. I'll re-evaluate the use of `realpath` when creating a new major version of the package next year.

In the meantime you can create a custom url generator that works for you: https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/generating-custom-urls
