### ISSUE TITLE
Question: Curious about the migration creation

### ISSUE THREAD

**Issue by Naoray** [spatie/laravel-medialibrary#690]
Hey there,

I asked myself if [this line](https://github.com/spatie/laravel-medialibrary/blob/master/src/MediaLibraryServiceProvider.php#L23) in the `MedialibraryServiceProvider` actually makes a difference, cause when I publish the migration more than once `class_exists()` still results to `false` and creates another migration file in the `database/migration/` dir.

Could someone please explain to me why it is used or what it is supposed to do? I can't make sense out of it.

**Comment by freekmurze** [comment]
If you dump your autoloader after you publish the migration the `class_exists` will return `true` and that line will prevent the migration from being published twice.
