### ISSUE TITLE
Fatal error HasMediaTrait->deleteMedia

### ISSUE THREAD

**Issue by StApostol** [spatie/laravel-medialibrary#691]
The example: I try to delete media not related to the model.
This code (https://github.com/spatie/laravel-medialibrary/blob/master/src/HasMedia/HasMediaTrait.php#L376) return null.
So this row https://github.com/spatie/laravel-medialibrary/blob/master/src/HasMedia/HasMediaTrait.php#L379 return the fatal error because $media are not declared as Spatie\MediaLibrary\Media

**Comment by freekmurze** [comment]
Do not try to delete media via that function that is not related to the model.

You could delete media directly instead

```php
$media->delete();
```

**Comment by StApostol** [comment]
I understand that you need to use a different method, but do not use it correctly
MediaCannotBeDeleted :: doesNotBelongToModel which throws out a fatal error

**Comment by freekmurze** [comment]
Got it, I'll take a look at this soon.
