### ISSUE TITLE
Greedy download 

### ISSUE THREAD

**Issue by AzAzzAzzz** [spatie/laravel-medialibrary#705]
Hi! How to implement a greedy download in medialibrary?

**Comment by freekmurze** [comment]
What is a greedy download?

**Comment by AzAzzAzzz** [comment]
I'm sorry, I meant Eager Loading... How to avoid multiple database requests?
In the controller, I get the data this way

`return view('blog.index', ['posts', Blog::where('active', 1)->paginate(5)]);`

Output in view

`@foreach($posts as $post)
    <div class="">
        <h3 class="">{{ $post->name }}</h3>
        <img src="{{ $post->getFirstMediaUrl('images') }}">        
		...
	</div>		
@endforeach`

All works, but it turns out a lot of queries to the database, please tell me how to avoid this

**Comment by sebastiandedeyne** [comment]
You could add a `with` call to your query.

```
Blog::with('media')->where('active', 1)->paginate(5)
```

**Comment by AzAzzAzzz** [comment]
Thanks already understood, earlier to make such it did not turn out, because I in the table did changes which are not necessary)

**Comment by AzAzzAzzz** [comment]
Thanks to the author for the cool package
