### ISSUE TITLE
Call to undefined method Spatie\MediaLibrary\UrlGenerator\S3UrlGenerator::getPath()

### ISSUE THREAD

**Issue by dimitribocquet** [spatie/laravel-medialibrary#708]
I recently installed this package and I'm trying to use with S3.

For my first upload, I'm doing that : 
```
$media = $user->addMedia($request->file('profile_picture'))->toMediaCollection();

\Log::debug($media);
\Log::debug($media->getUrl());
\Log::debug($media->getPath());
```

The file is correctly uploaded to S3, I have a row in my DB, and `getUrl()` works. Great.
But `getPath()` throws me this error :
`Call to undefined method Spatie\MediaLibrary\UrlGenerator\S3UrlGenerator::getPath() in /Users/dimitri/Sites/laravel/vendor/spatie/laravel-medialibrary/src/Media.php:95`

I have this issue in 5.13.2.

BTW, `getUrl()` gives me the public url for S3, how can I have the url for private files? Is there a way to know if a file is public or private?

Thanks!

**Comment by s1rc** [comment]
Running into the same issue as @dimitribocquet.

Same version and same exact symptoms.

**Comment by freekmurze** [comment]
I don't remember anymore why I removed `getPath` so I added it back now. Run `composer update` to pull that change in.

**Comment by jonathandey** [comment]
I'm running version 4.13.5 and I'm still running in to this problem. Any idea what could be wrong?

**Comment by freekmurze** [comment]
We don't support `v4` anymore. Is it possible for you to upgrade to `v6`?

**Comment by jonathandey** [comment]
Don't think I can. I'm using OctoberCMS on Laravel 5.1. To the best of my knowledge this is a small fix. I have my own fork but I'd rather be using the official version. You can see my fix here: https://github.com/jonathandey/laravel-medialibrary/commit/8a0d1bbde150794477e5c922e4bc7708daadf60b

**Comment by freekmurze** [comment]
Use your own fork, `v4` won't be maintained anymore so your fork will probably contain the latest version of `v4` for a long time.

**Comment by jonathandey** [comment]
Ok. Thanks for your help.
