### ISSUE TITLE
Issue in version 3 

### ISSUE THREAD

**Issue by diptesh-p-crest** [spatie/laravel-medialibrary#709]
In version 3 there is file 
\spatie\laravel-medialibrary\src\HasMedia\HasMediaTrait.php

in this file there is function called removeMediaItemsNotPresentInArray.. 
protected function removeMediaItemsNotPresentInArray(array $newMediaArray, $collectionName = 'default')
    {
        $this->getMedia($collectionName, [])
            ->filter(function ($currentMediaItem) use ($newMediaArray) {
                return !in_array($currentMediaItem->id, collect($newMediaArray)->lists('id')->toArray());
            })
            ->map(function ($media) {
                $media->delete();
            });
    }

NEED TO CHANGE THE 

> lists

 function as it is been deprecated CHANGE it to 

> Pluck

**Comment by Yentel** [comment]
This has been fixed in v4 already :-)

**Comment by diptesh-p-crest** [comment]
Actually issue is my laravel is installed at 5.6.14 PHP version.. 
and not able to update the version 4 of medialibrary as it requires PHP 7
-- I have tried many ways to update to php 7 but not got success ..
-- So Is it possible to change in version 3 function directly so whenever anybody download version 3 it should work with Laravel 5.4 and PHP 5.16..

If possible please do .. anyway I have fixed the issue by overriding function in MODEL class. 

Thank You,
Diptesh Patel

**Comment by freekmurze** [comment]
For us PHP 5 is dead for quite some time now and we are not going to invest anymore time in old releases.

Please fork the code and fix it there.
