### ISSUE TITLE
Initial conversion

### ISSUE THREAD

**Issue by vedmant** [spatie/laravel-medialibrary#71]
Hi, I wanted to ask, is there any way to convert original file on uploading, for example I can accept files up to 2048px, but for this type of images maximum size can be 800px, so saving all original files will be real waste of disk space.

**Comment by freekmurze** [comment]
Hi,

currently there is no way to perform an initial conversion. In our projects we got plenty of diskspace and storing a big image isn't really a problem. In the public section of our sites we never show the original image, but use a profile name something like `bigImage` which is max 2000x2000.

I think that resizing the original image before adding it to the medialibrary is a responsability of the application. However, it would be a nice to have for this package. So if you would submit a PR (with tests) that adds this functionality to the package, I'd likely merge it.
