### ISSUE TITLE
Return into deleteMedia function

### ISSUE THREAD

**Issue by judantus** [spatie/laravel-medialibrary#73]
Am I wrong, or in this line itshould be included a return?
https://github.com/spatie/laravel-medialibrary/blob/3.5.0/src/HasMedia/HasMediaTrait.php#L224

**Comment by freekmurze** [comment]
I don't think returning a value is necessary. What should it return according to you? Do you have a specific use case in mind?

**Comment by judantus** [comment]
This is my code:
        $model= $this->model;
        try{
            $item= $model::findOrFail($id);
            $item->deleteMedia($request->id_media);
            return \Response::json(array(
                'success'=> 200,
                'request' => $request->id_media
            ));
        }
        catch(\Exception $exc)
        {
            return \Response::json(array(
                'error'=> $exc->getCode(), 
                'message'=>$exc->getMessage()
            ));
        }

In ajax call if the '$request->id_media' is null it does not catch the exception. 
Thanks.

**Comment by freekmurze** [comment]
In your case you could do:
```php
$media = Media::findOrFail($request->id_media);
$media->delete();
```
