### ISSUE TITLE
Class [..\Filesystem] is not instantiable

### ISSUE THREAD

**Issue by vladvisinescu** [spatie/laravel-medialibrary#730]
Hi all,

When running this code:

```php
foreach ($request->file('images') as $key => $path) {
    $jurnal->addMedia($path)->toMediaCollection();
}
```

...I get this message:

> Target [Spatie\MediaLibrary\Filesystem\Filesystem] is not instantiable while building [Spatie\MediaLibrary\FileAdder\FileAdder].

This hasn\`t happened to me before. I`ve used the docs for installing, as always.

Maybe I\`m forgetting/missing something? Can somebody help? 

Thanks! :)

P.S.: I`m using PHP v7.1.8 and Laravel 5.4 on Forge.

**Comment by sebastiandedeyne** [comment]
Hmm is the service provider registered correctly?

Maybe add a `dd` here and see if it passes throught. This is the line that ensures that the `Filesystem` can be instantiated.

https://github.com/spatie/laravel-medialibrary/blob/a3cdd12c96677bdfad3df1d1125bbfeb0f3f6863/src/MediaLibraryServiceProvider.php#L51

**Comment by vladvisinescu** [comment]
You`re were right. Thanks!
