### ISSUE TITLE
laravel55 branch: HasMediaConversions interface expects a Media parameter

### ISSUE THREAD

**Issue by manogi** [spatie/laravel-medialibrary#734]
Hi there,
I am using the laravel55 branch - when I add the `registerMediaConversions` in my model, it throws an exception on uploading:

> Declaration of App\Image::registerMediaConversions() must be compatible with Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions::registerMediaConversions(?Spatie\MediaLibrary\Media $media = NULL)

When I remove the parameter `Media $media = null`  from the `registerMediaConversions` method inside the `HasMediaConversions` interface everything seems to work fine. Is that parameter added in there for a reason? Or should I write a PR removing that parameter?

Thanks for your time, 
Sebastian

**Comment by a-komarev** [comment]
@manogi I suppose you followed documentation and have in your model code:

```php
public function registerMediaConversions()
{
   // Your code
}
```

But interface is changed in laravel55 branch and it doesn't reflected in documentation because this branch is under development.

Try to update method declaration to this one:
```php
public function registerMediaConversions(Media $media = null)
{
    // Your code
}
```

**Comment by manogi** [comment]
@a-komarev Thank you very much. Yes, that helps. I should probably not post issues concerning development branch. I did use this because I started a project on laravel 5.5 and needed to use the laravel55 version of medialibrary, though.
