### ISSUE TITLE
Updating to specific folder within disk

### ISSUE THREAD

**Issue by seandelaney** [spatie/laravel-medialibrary#737]
How can I specify or set the folder I want to upload to within a disk.

By default, all files are uploaded to the root of a disk.

**Comment by freekmurze** [comment]
Just set the `root` property of the disk to the path you want your files to be stored.

**Comment by seandelaney** [comment]
I'm a bit confused, sorry. I might not have asked the correct question either...

My disk is called `uploads` like:

```
'uploads' => [
	'driver' => 'local',
	'root' => public_path('uploads'),
],
```

I want to upload a file X to `/uploads/carbs` but let's say I then want to upload my next file to `/uploads/proteins`.

The upload path can change if that makes sense.

When I call `$asset->addMedia($file)->toMediaCollection($this->mediaCollection);`, the file gets uploaded to `/uploads` but I'd like to set the path to `/uploads/carbs` or `/uploads/some_folder`.

Do I still need to update the `public_path()` value each time?

**Comment by freekmurze** [comment]
No, that medialibrary works best if you let it to take care of all the paths in the root directory of your app. If you do want to change the directory structure that medialibrary will use, take a look at this piece of documentation: https://docs.spatie.be/laravel-medialibrary/v6/advanced-usage/using-a-custom-directory-structure

**Comment by seandelaney** [comment]
Yeah, I've also setup a custom directory structure.

I've got:

```
/**
 * Get the path for the given media, relative to the root storage path.
 */
public function getPath(Media $media) : string
{
	// Set path to root level 
	return '';
}
	
/*
 * Get the path for conversions of the given media, relative to the root storage path.
 * @return string
 */
public function getPathForConversions(Media $media) : string
{
	// Sets asset conversions in a folder called "conversions/model_id"
	return 'conversions/'.$media->model->id.'/';
}
```

I didn't want:

```
/uploads/1/
/uploads/1/conversions
/uploads/2/
/uploads/2/conversions
...
/uploads/n/
/uploads/n/conversions
```

I changed this because I'm also using https://github.com/DirectoryLister/DirectoryLister as my File Manager UI and wanted all my file uploads to be saved in the root and a single folder "conversions" as a subfolder holding all my conversions in sub-sub folders based on `model_id`. It actually works very well.

I added a Create Folders button to the File Manager UI that I'm trying to build, allowing the client to create a sub folder. This is why I asked how do I set the path to allow a user to upload a file to a specific folder within the `uploads` folder.

Make better sense?

**Comment by freekmurze** [comment]
This is not possible with the medialibrary.

From the docs: 
> When a Media-object gets deleted the package will delete its entire associated directory. To avoid tears or worse, make sure that every media gets stored its own unique directory.

**Comment by yatinPatel13490** [comment]
Thanks for quick reply and guidance.....+1

**Comment by oyepez003** [comment]
https://github.com/spatie/laravel-medialibrary/issues/1053

**Comment by Tofandel** [comment]
For anyone coming to this issue for a quick way to be able to set the folder at upload time

Here is a custom generator
```php
<?php

namespace App;

use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Spatie\MediaLibrary\Support\PathGenerator\DefaultPathGenerator;

class MediaPathGenerator extends DefaultPathGenerator
{

    /*
     * Get a unique base path for the given media.
     */
    protected function getBasePath(Media $media): string
    {
        $path = config('media-library.prefix', '');

        if ($path !== '') {
            $path .= '/';
        }

        if ($folder = $media->getCustomProperty('folder')) {
            $path .= $folder . '/';
        }

        return $path . $media->getKey();
    }
}
```

Register it in the config

```php
    /*
     * The class that contains the strategy for determining a media file's path.
     */
    'path_generator' => \App\Models\Overrides\MediaPathGenerator::class,
```

And add folder to the custom properties when uploading

```php
        $this->addMedia($file)
            ->withCustomProperties(['folder' => 'carbs'])
            ->usingFileName(Str::random(40) . '.jpg')         
```
