### ISSUE TITLE
duplicated migration file

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-medialibrary#739]
because of this line
https://github.com/spatie/laravel-medialibrary/blob/0491a18d95be3b8ef3e2e351cd14720d7484070a/src/MediaLibraryServiceProvider.php#L25

can we use only one data instead of re-generating new one on each publish ?

**Comment by freekmurze** [comment]
That class check should prevent the migration from being published again (after you’ve dumped the autoloader)

**Comment by ctf0** [comment]
sadly this is not the current behavior, cuz laravel dump the autoload after each package installation automatically.

**Comment by chrisbjr** [comment]
Hi @freekmurze unfortunately this issue still holds true. Video shown here:

https://www.dropbox.com/s/epe9yn73vh4er4d/laravel-medialibrary-issue.mov?dl=1

I'll be creating a pull request to resolve this.

**Comment by jantoniomartin** [comment]
Hi @freekmurze. I'm having this issue when publishing laravel-medialibrary as a dependency of [craftable](https://github.com/BRACKETS-by-TRIAD/craftable) into an existing project.

In this project, I was already using laravel-medialibrary. When installing craftable, a new create_media_table is generated, with a different timestamp, and that breaks the migrations (and thus the craftable setup).

I've seen that @chrisbjr's PR was not accepted. Is there any other way to solve this?
