### ISSUE TITLE
performConversion on bmp

### ISSUE THREAD

**Issue by Kolovious** [spatie/laravel-medialibrary#740]
Hi Spatie, i'm amazed with the design of the package. I need to ask you if is there a  way to add the ability to performConversions on bmp files. i read somewhere but i cannot find it right now.

Thanks , when on production will send you a postcard! ;)

**Comment by freekmurze** [comment]
Under the hood the medialibrary uses [our image package](https://docs.spatie.be/image). On it's turn it leverages gd and imagick. I believe they those libraries do support `bmp`s.

**Comment by Kolovious** [comment]
hmmm, will check again, none of my bmp's are handled.

**Comment by Kolovious** [comment]
In https://github.com/spatie/laravel-medialibrary/blob/master/src/ImageGenerators/FileTypes/Image.php#L23 are defined the image extensions.
How i should overwrite this value?

**Comment by ottosmops** [comment]
I think you can add extensions via your ImageGenerator (supportedExtensions() and supportedMimeTypes()):
https://docs.spatie.be/laravel-medialibrary/v4/converting-other-file-types/creating-a-custom-image-generator

**Comment by Kolovious** [comment]
Aha! that was the link! 
i don't know why i was getting the other posted by me. Will post the snippet here.

**Comment by ottosmops** [comment]
That would be great, because I am on the same type of thing trying to make a tif ImageGenerator. But I miss something. It does not work:

```php
// Media.php
class Media extends BaseMedia  {

    /**
    * Collection of all ImageGenerator drivers.
    */
    public function getImageGenerators() : Collection
    {   
        \Log::debug(__METHOD__);
        return collect(config('medialibrary.image_generators'))->push(\App\ImageGenerators\Tiff::class );
    }
```
Whereas the Model registerMediaConversions() method is found, the getImageGenerators() method is not called when I add Tiffs or use the regenerate command.

```php
// Tiff.php
class Tiff extends BaseGenerator 
{
   /**
    * This function should return a path to an image representation of the given file.
    */
    public function convert(string $file, Conversion $conversion = null) : string
    {
        \Log::debug(__METHOD__);
        $imageFile = pathinfo($file, PATHINFO_DIRNAME).'/'.pathinfo($file, PATHINFO_FILENAME).'.jpg';

        Image::make($fullname)->widen(1200)->save($imageFile);

        return $imageFile;
    }
...
 public function supportedExtensions() : Collection
    {
        return collect(['tif', 'tiff']);
    }

    public function supportedMimeTypes() : Collection
    {
        return collect('image/tiff');
    }
```
Also the convert method is not used.

I declared the Media model and the ImageGenarator in the config file:

```php 
// medialibrary.php
  /*
   * The class name of the media model to be used.
   */
     'media_model' => App\Models\Media::class ,
...
  'image_generators' => [
		Spatie\MediaLibrary\ImageGenerators\FileTypes\Image::class ,
		App\ImageGenerators\Tiff::class ,
		Spatie\MediaLibrary\ImageGenerators\FileTypes\Pdf::class ,
		Spatie\MediaLibrary\ImageGenerators\FileTypes\Svg::class ,
		Spatie\MediaLibrary\ImageGenerators\FileTypes\Video::class ,
	],
```

**Comment by ottosmops** [comment]
A better solution would be, if the bmp or tiff could be recognized/handled as an image, I guess?
