### ISSUE TITLE
Dynamically assigning extractVideoFrameAtSecond when adding media

### ISSUE THREAD

**Issue by abishekrsrikaanth** [spatie/laravel-medialibrary#742]
My requirement is to be able to extract the thumbnail from the video at a specific second and I see there is a function `extractVideoFrameAtSecond` that can be defined on the `registerMediaConversions`. Is there a way define this when adding the media? or is it possible to alter the time to extract on the `registerMediaConversions` method?

**Comment by freekmurze** [comment]
You could opt to add [a custom property]
(https://docs.spatie.be/laravel-medialibrary/v6/advanced-usage/adding-custom-properties) to your Media instance containing your specific seconds to take the tumbnail.

In the latest version of the medialibrary, an instance of `Media` is being passed to `registerMediaConversions`. You could read the custom property there to pass to the `extractVideoFrameAtSecond` function.

**Comment by abishekrsrikaanth** [comment]
The new version requires an upgrade to Laravel 5.5, could you add the parameter to the package that support Laravel 5.4? I really don't see a point to spend more hours upgrading to Laravel 5.5 and testing it to be able to use a new parameter on the `registerMediaConversions` function.

**Comment by freekmurze** [comment]
>  could you add the parameter to the package that support Laravel 5.4?

No, that would be a breaking change. You always have the option to fork the package and make the modification in your own copy.

**Comment by Cannonb4ll** [comment]
@freekmurze Could you give an example on how to set a the `extractVideoFrameAtSecond` dynamically through the `$media` property?

**Comment by martindrapeau** [comment]
@Cannonb4ll I know this is old however here is code sample. Oh and it allows using a float instead of an integer for seconds.
```
public function registerMediaConversions(Media $media = null)
{
    $conversion = $this->addMediaConversion('thumb')
        ->width(560)
        ->height(315)
        ->extractVideoFrameAtSecond(2)
        ->performOnCollections('videos')
        ->nonQueued();
    // Force a float value. We cannot use method extractVideoFrameAtSecond since
    // it only takes an int. Workaround is to use reflection.
    if (isset($media)) {
        $thumb_at = $media->getCustomProperty('thumb_at');
        if ($thumb_at != null) {
            $o = new \ReflectionObject($conversion);
            $r = $o->getProperty('extractVideoFrameAtSecond');
            $r->setAccessible(true);
            $r->setValue($o, $thumb_at);
        }
    }
...
```
