### ISSUE TITLE
need to set folder in disk

### ISSUE THREAD

**Issue by yatinPatel13490** [spatie/laravel-medialibrary#743]
Hi,

I need to create the new folder into my disk and then need to store all related images into that.

Should it possible?

I am using **laravel5.4** and here is the disk path:
'users' => [
            'driver' => 'local',
            'root' => public_path('uploads'),
        ],

currently when I upload images from from it put the images into folder on "uploads" directory. but I need to put images folder into this location "uploads/users"

I tried with : 
$user = User::find($id);
$user->addMediaFromRequest('image')->toMediaCollection('test', 'uploads/users'); //But it gives me error of no such disk error

please guide me.

**Comment by freekmurze** [comment]
see #737
