### ISSUE TITLE
Make compatible with mariaDB or mysql < 5.7.8

### ISSUE THREAD

**Issue by cesargb** [spatie/laravel-medialibrary#744]
Hi!

this package is very usefull, but i have the problem with requeriment in database. Sometimes is not possible run the service with mysql 5.7.8 or higher.

The fields `manipulations`and `custom_properties ` requires JSON DATATYPE.

Would it be possible to make it compatible with earlier versions of mysql or mariadb? Perhaps, a item in config file with the option to select this DATETYPE ... of this changes and mutators of this fields.

If you do not discard this change, I can try a PR

Thanks for your time.

**Comment by freekmurze** [comment]
On all my projects I can use just the required mysql version, so I'm not going to invest any time in making the package compatible with things that don't support the json datatype.

If you need that, it's probably best to fork the package and make the necessary modifications in your own fork.

**Comment by bbdangar** [comment]
@cesargb Hey, I just changed field type json to text and it works for me.
