### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by microscan5ep** [spatie/laravel-medialibrary#746]
$ composer require spatie/laravel-activitylog
Using version ^2.0 for spatie/laravel-activitylog
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-activitylog ^2.0 -> satisfiable by spatie/laravel-activitylog[2.0.0].
    - Conclusion: remove laravel/framework v5.4.33
    - Conclusion: don't install laravel/framework v5.4.33
    - spatie/laravel-activitylog 2.0.0 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[v5.5.0, v5.5.2].
    - don't install illuminate/database v5.5.0|don't install laravel/framework v5.4.33
    - don't install illuminate/database v5.5.2|don't install laravel/framework v5.4.33
    - Installation request for laravel/framework (locked at v5.4.33, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.33].

Installation failed, reverting ./composer.json to its original content.

PHP is v7.1.0
OS is Centos 7.3.1611

Any ideas please?

Thanks

**Comment by freekmurze** [comment]
You should have opened this issue at the laravel-activitylog repo.

v2 of activitylog is only installable in Laravel 5.5.

Try installing v1 of the package.
