### ISSUE TITLE
Sharing media

### ISSUE THREAD

**Issue by CupOfTea696** [spatie/laravel-medialibrary#748]
I was wondering if it was possible to share media between models? To re-use an image now, it seems that the only possibility is to have one or more duplicates stored.

**Comment by freekmurze** [comment]
Nope, that's not possible right now. I tried to make the medialibrary as easy as possible and that's why I opted for a 1-to-n relation between media and model. If you need n-to-n you could opt to use [laravel-mediable](https://murze.be/2016/08/introducing-laravel-mediable/).
