### ISSUE TITLE
Add and use user_id column in media table?

### ISSUE THREAD

**Issue by dambridge** [spatie/laravel-medialibrary#75]
I'm thinking this is possible through the custom model capabilities, but I confess I'm not sure to go about that exactly. For instance, where would I pass an additional value when uploading a file toMediaLibrary()?

**Comment by freekmurze** [comment]
If you just want to add a custom property to an uploaded media file it's best to use [custom properties](http://medialibrary.spatie.be/v3/advanced-usage/adding-custom-properties/).

If you really want to use your own model, the documentation provides [some starting points on how to do that](http://medialibrary.spatie.be/v3/advanced-usage/using-your-own-model/).

**Comment by dbpolito** [comment]
FYI, in case someone else needs it, i did this using my own model with this:

````
<?php

namespace App;

use Spatie\MediaLibrary\Media as BaseMedia;

class Media extends BaseMedia
{
    /**
     * Boot events
     * @return void
     */
    public static function boot()
    {
        parent::boot();

        static::creating(function ($media) {
            if ($user = auth()->getUser()) {
                $media->user_id = $user->id;
            }
        });
    }

    /**
     * User relationship (one-to-one)
     * @return App\User
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}
````

You also have to create a migration to add column `user_Id`.

**Comment by dambridge** [comment]
Ah, great idea @dbpolito !

**Comment by dambridge** [comment]
I guess now my challenge is figuring out how to do something like
`` getMedia($request->collection)->with('user') ``

**Comment by dambridge** [comment]
Never mind, sorted, and thanks again for that. Sorry to necro-bump this issue!

**Comment by freekmurze** [comment]
![](http://cdn4.teehunter.com/wp-content/uploads/2013/12/zombie-t-shirts.jpg)

**Comment by naumanahmed19** [comment]
@freekmurze can you please update docs for this the solution @dbpolito suggested seems not working for "^5.0.0"

**Comment by freekmurze** [comment]
https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/using-your-own-model

**Comment by farbodakvan** [comment]
> FYI, in case someone else needs it, i did this using my own model with this:
> 
> ```
> <?php
> 
> namespace App;
> 
> use Spatie\MediaLibrary\Media as BaseMedia;
> 
> class Media extends BaseMedia
> {
>     /**
>      * Boot events
>      * @return void
>      */
>     public static function boot()
>     {
>         parent::boot();
> 
>         static::creating(function ($media) {
>             if ($user = auth()->getUser()) {
>                 $media->user_id = $user->id;
>             }
>         });
>     }
> 
>     /**
>      * User relationship (one-to-one)
>      * @return App\User
>      */
>     public function user()
>     {
>         return $this->belongsTo('App\User');
>     }
> }
> ```
> 
> You also have to create a migration to add column `user_id`.

Thank you for the very good way
There is a change for Laravel 9, I said to share

    public static function boot()
    {
        parent::boot();

        static::creating(function ($media) {
            if ($user = Auth::user()) {
                $media->user_id = $user->id;
            }
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

**Comment by LiamKarlMitchell** [comment]
For Laravel 9, I wanted to store authenticated user against the Media, but also customize the searching of existing media using [Advanced Nova Media Library](https://github.com/ebess/advanced-nova-media-library/blob/master/src/Http/Controllers/MediaController.php)

Additionally A user should only be able to remove the media if they are Admin or Authenticated as the owner, but thats an implementation detail so I'll leave it out here. But to quote from this [question](https://github.com/spatie/laravel-medialibrary/issues/919)

> This package doesn't handle anything regarding permissions, that's something you should handle yourself in your app.

To go further on that I may need to make a Policy or [Gate](https://reecemay.me/articles/using_model_morph_names_for_gates/)? for Media.

Model
```
sail artisan make:model Media
```

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Spatie\MediaLibrary\MediaCollections\Models\Media as BaseMedia;

class Media extends BaseMedia
{
    /**
     * All the relationships to be touched.
     *
     * @var array
     */
    protected $touches = ['model'];

    /**
     * Boot events
     * @return void
     */
    public static function boot()
    {
        parent::boot();

        static::creating(function ($media) {
            $user = auth()->getUser();
            if ($user) {
                $media->user_id = $user->id;
            }
        });
    }

    /**
     * User that uploaded the image.
     *
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
```


Migration:
```
sail artisan make:migration add_user_to_media_table
```

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('media', function (Blueprint $table) {
            $table->foreignId('user_id')->index()->nullable()->constrained()->comment('The user that owns this record');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('media', function (Blueprint $table) {
            $table->dropConstrainedForeignId('user_id');
        });
    }
};
```

Extending Advanced Nova Media Library Media Controller to query existing media based on User that uploaded the media.

Make a controller as needed.

App\Http\Controllers\AdvancedNovaMediaLibrary\MediaController.php

```php
<?php

namespace App\Http\Controllers\AdvancedNovaMediaLibrary;

use App\Http\Controllers\Controller;
use Ebess\AdvancedNovaMediaLibrary\Http\Requests\MediaRequest;
use Ebess\AdvancedNovaMediaLibrary\Http\Resources\MediaResource;
use Exception;

class MediaController extends Controller
{
    public function index(MediaRequest $request)
    {
        if (!config('nova-media-library.enable-existing-media')) {
            throw new Exception('You need to enable the `existing media` feature via config.');
        }

        $hideCollections = config('nova-media-library.hide-media-collections', []);
        $mediaClass = config('media-library.media_model');
        $mediaClassIsSearchable = method_exists($mediaClass, 'search');

        $searchText = $request->input('search_text') ?: null;
        $perPage = $request->input('per_page') ?: 15;

        $query = null;

        if ($searchText && $mediaClassIsSearchable) {
            $query = $mediaClass::search($searchText);
        } else {
            $query = $mediaClass::query();

            if ($searchText) {
                $query->where(function ($query) use ($searchText) {
                    $query->where('name', 'LIKE', '%' . $searchText . '%');
                    $query->orWhere('file_name', 'LIKE', '%' . $searchText . '%');
                });
            }

            $query->latest();
        }

        if (!empty($hideCollections)) {
            if (!is_array($hideCollections)) {
                $hideCollections = [ $hideCollections ];
            }

            $query->whereNotIn('collection_name', $hideCollections);
        }

        // Custom code: Filter by uploaded user.
        $user = $request->getUser();
        if ($user) {
            $query->whereUser($user);
        }
        // End of custom code.

        $results = $query->paginate($perPage);

        return MediaResource::collection($results);
    }
}
```

Make a route accordingly to your controller.

api.php
```php
Route::get('/media', [AdvancedNovaMediaLibrary\MediaController::class, 'index']);
```

And update the model in config/media-library.php to point to your custom one.
```php
    /*
     * The fully qualified class name of the media model.
     */
    'media_model' => Media::class
```

**Comment by RejownAhmed** [comment]
> FYI, in case someone else needs it, i did this using my own model with this:
> 
> ```
> <?php
> 
> namespace App;
> 
> use Spatie\MediaLibrary\Media as BaseMedia;
> 
> class Media extends BaseMedia
> {
>     /**
>      * Boot events
>      * @return void
>      */
>     public static function boot()
>     {
>         parent::boot();
> 
>         static::creating(function ($media) {
>             if ($user = auth()->getUser()) {
>                 $media->user_id = $user->id;
>             }
>         });
>     }
> 
>     /**
>      * User relationship (one-to-one)
>      * @return App\User
>      */
>     public function user()
>     {
>         return $this->belongsTo('App\User');
>     }
> }
> ```
> 
> You also have to create a migration to add column `user_id`.

Inside a Laravel queued job this configuration won't work. So it'd be better to use custom properties, I believe
