### ISSUE TITLE
Use "FilesystemAdapter::getUrl()" instead of manually configuring S3 URL

### ISSUE THREAD

**Issue by hohl** [spatie/laravel-medialibrary#750]
Why does this library try to build their own URLs when there is a `getUrl()` method provided by Laravel (which does exactly that)? This not only causes redundant code, but also configuring the same stuff twice (no need for `s3.domain` in `config/medialibrary.php`).

**Comment by freekmurze** [comment]
Because when using a custom path using a `PathGenerator` `FilesystemAdapter::getUrl()` will produce wrong results.
