### ISSUE TITLE
Does media to the disk get added using queue or sync when queue is enabled?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [spatie/laravel-medialibrary#751]
After the file is uploaded from the client to the server and when the `addMedia` function is called, does the media get added to the designated disk (example; `s3`) using the queue or does it happen synchronously? I see the transformations happen using the queue when queue is enabled but don't think storing the file uses the queue currently

**Comment by freekmurze** [comment]
It happens synchornously.
