### ISSUE TITLE
Provide Collection Scopes

### ISSUE THREAD

**Issue by MannikJ** [spatie/laravel-medialibrary#752]
Hi!

Are there convenience query functions (scopes) to retrieve 
(1) all media in a collection
(2) all media in a collection belonging to a specific model class
and so on?

As you see I want to query media from a global point of view instead of via a model instance 
I know you can do `$modelInstance->getMedia('collection');` etc.

I would want to write something like 
`Media::collection('collection')->model(MyModel::class)->get();` 
or even 
`MyModel::getMedia('collection');`

I am only asking because I don't want to start implementing my own stuff when I just missed something that's already there. Or maybe I just don't understand the concept of the media collections :D

Edit:
What underlies this question is that I don't like that there is no real connection between the model class and the collection name from the application point of view, although all necessary information is already in the database. 
I don't want to create collections with names like 'user-images' and 'item-images', because that would only add duplicate information and also make it more complicated to retrieve _all images regardless of it's model type_ for example.

Best regards,
Jannik

**Comment by ottosmops** [comment]
If I got you right, then it would be possible to do that with a queryScope. https://laravel.com/docs/5.5/eloquent#query-scopes

```php 
public function scopeCollection($query, $collection)
    {
        return $query->where('collection', $collection);
    }
```
Not tested.

**Comment by freekmurze** [comment]
A query scope seems a nice way to go about this.
