### ISSUE TITLE
Permissions in different user/groups

### ISSUE THREAD

**Issue by bertalanimre** [spatie/laravel-medialibrary#753]
Hey Dev. Team,

I wish to use your medialibrary, but ran into a small issue about permissions.
On my server, because of security reasons, I store my laravel projects with web:nginx permissions. However, when a file is being uploaded, it get's the nginx:nginx permissions. I assume it is because the user running NginX is actually nginx. It is the same user that is running the PHP-FPM. The web user is just a restricted user, who is able to do my git pull-s and some php artisan commands. 

What do you suggest besides using a watcher to modify the permissions on every file create event? 

Cheers in advance!

Bert

**Comment by AlexVanderbist** [comment]
Hi Bert, I'm no expert on permissions but I'd suggest running PHP and NGINX as the `web` user as well just to avoid the issue altogether.

**Comment by bertalanimre** [comment]
I've done it today. NginX is running by user `web` and so does php-fpm. Every service is restarted, BUT...
When the images are being uploaded, the permissions on the project.com/public/media library still switches from `web:nginx` to `nginx:nginx`. I have downloaded and set up a watcher to change the permissions back to `web:nginx` when a file is being created in `public/media` BUT after the modification, the permissions are set again back to `nginx:nginx`, So when I upload a file the following happens if I've manually set `web:nginx` on `public/media`:
 - File being uploaded into public/media/XX/
 - Permissions are changed on public/media from web:nginx to nginx:nginx by medialibrary
 - Permissions are changed on public/media from nginx:nginx to web:nginx by watcher
 - Permissions are changed back again on public/media from web:nginx to nginx:nginx by medialibrary

How do you think this is possible if everything is being run by user `web` ?

**Comment by bertalanimre** [comment]
I take it back, even if I stop watcher, the permissions are still changing in this order.

**Comment by bertalanimre** [comment]
Localhost issue.Problem solved. I don't wanna talk about it.....

**Comment by AlexVanderbist** [comment]
Alright, glad you got it solved!
