### ISSUE TITLE
Getting extension to rename files

### ISSUE THREAD

**Issue by jerauf** [spatie/laravel-medialibrary#754]
I want to rename files with a hash instead of the original name. When I tried to rename a file on upload, it removed the extension and just changed the entire name.

In order to do this properly, I need to get the extension. It doesn't seem to be in the docs.

What do I call to get it?

**Comment by freekmurze** [comment]
You can get the extension of any file with `pathinfo($path, PATHINFO_EXTENSION)`

**Comment by Emmanuel-Oduro** [comment]
Hi, is there a way to rename the file for upload?
