### ISSUE TITLE
Can't upload images bigger than 1500px max

### ISSUE THREAD

**Issue by jerauf** [spatie/laravel-medialibrary#757]
Some of my images are pretty large. My server restricts file size but not file dimensions.

I changed this setting in the config file:

    'max_file_size' => 5000 * 5000 * 5000,

It seems to be only bytes and therefore file size but I changed it anyway.

Where is the px dimension setting?

**Comment by freekmurze** [comment]
There is no setting to limit the max px.

**Comment by jerauf** [comment]
There must be something. I can do it with Intevention/Image. I can't do it with this package. It's not a server setting.

**Comment by freekmurze** [comment]
Can you do the conversion using our image package (which get used under the hood) directly?

https://docs.spatie.be/image

**Comment by jerauf** [comment]
I'm willing to try. When I require, there is an error:

`[InvalidArgumentException]                                                                                                               
  Could not find package require at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
`

**Comment by freekmurze** [comment]
What is your php version and what is the composer command you’re running?

Did you try install it in an empty directory?

**Comment by jerauf** [comment]
Hi - PHP version is 7. And I installed it in the directory with my Laravel app.

**Comment by jerauf** [comment]
Did I install it wrong?

**Comment by AlexVanderbist** [comment]
Hi,

If you're looking to prevent large images from being uploaded you can use the `dimensions` validation rule: https://laravel.com/docs/5.5/validation#dimensions

For example:
```php
public function upload() {
    $this->validate(request(), [
        'image' => 'dimensions:max_width=1500,max_height=1500',
    ]);

    // Continue adding the file to medialibrary
}
```

**Comment by jerauf** [comment]
No. The opposite. I need to convert larger files.

The files are uploading. The conversion is throwing the error.

**Comment by AlexVanderbist** [comment]
What error is being thrown exactly?

**Comment by jerauf** [comment]
It's a 500 error.

**Comment by jerauf** [comment]
The problem is that the php.ini file I was editing is not the one that the server was loading. I was able to make that change and now it's working.

What was happening is that for an image larger than 1500px, the memory settings were too low to handle resizing it.

**Comment by tylerwiegand** [comment]
@jerauf and whoever else runs into this issue, I had it recently. Memory limits can be increased, but imo the proper way to handle this issue is actually to not use the "sync" queue driver in your .env file. Install a queue manager, like Redis
```
composer require predis/predis
brew install redis
```
Then just have a queue working running, or run one on demand
```
php artisan queue:work
php artisan queue:work --once
```

Cheers!

**Comment by Kyawzino** [comment]
how to upload image width is more than 4000 pixels
