### ISSUE TITLE
Updating a Media object

### ISSUE THREAD

**Issue by MannikJ** [spatie/laravel-medialibrary#762]
Hi,

here is another question from me (hopefully not too stupid ;)).
I am looking for an easy way to update a media model with a new file and the other attributes (size) etc. as well. I know that Media is just a normal model and can be updated manually, but I want to have it consistent and use the mechanisms that are already implemented within the package to set the properties like size for example.
I would like it to perform basically the same as `$model->addMedia($path)->toMediaCollection($collection, $disk);` does, but with updating an existing media model instead of saving it under a new one with a new id.
This is for automatically regenerated files that are also managed by the media library, but cannot be conversions since they are no images.
I hope someone can give a hint how to do that or suggest a completely different way if this is rubbish anyway.

Best regards,
Jannik

**Comment by freekmurze** [comment]
> I would like it to perform basically the same as $model->addMedia($path)->toMediaCollection($collection, $disk); does, but with updating an existing media model instead of saving it under a new one with a new id.

That currently is not possible. You could opt to use [your own media model](https://docs.spatie.be/laravel-medialibrary/v6/advanced-usage/using-your-own-model). You can then add a method `replaceMedia` or something similar to it that:
- remember the id of the media you want to change the file of
- deletes that media instance
- creates a new media instance with a new file
- change the id of the new media to the old media id

**Comment by MannikJ** [comment]
This would create a hole in the id range, because of the new media object the auto-increment steps forward, no matter if the id is actually used or not, correct?
Not that this would technically matter unless you're going against 4 billion media items in you application ;) It's just not very beautiful...

**Comment by freekmurze** [comment]
> This would create a hole in the id range

Yup, but like you said, it's not really a problem unless you're Ebay or something of that scale.

**Comment by dlaynes** [comment]
Hi, I just stumbled upon this thread, and the quickest solution is to delete the previous object.

Also, old databases do not support JSON fields, so using the default BIGTEXT is fine, I guess, for regular websites.

**Comment by MannikJ** [comment]
No this does not work if I get you correct. Obviously one media record can only reference one file out of the box. 
But what you could possibly do is to add the HasMedia trait to a custom Media model so you can assign media to media like you assign media to users.

**Comment by Akhibemudu** [comment]
@MannikJ  well after updating media-library to 7.6.0, I was able to add more media to existing media without having to delete the existing media.
