### ISSUE TITLE
Why am I getting nothing to publish fro tab [migrations] ?

### ISSUE THREAD

**Issue by apurva2342** [spatie/laravel-medialibrary#77]
When I run 

php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="migrations"

I'm getting nothing to publish fro tab [migrations]

**Comment by freekmurze** [comment]
Did you register the service provider?

```php
// config/app.php
'providers' => [
    ...
    Spatie\MediaLibrary\MediaLibraryServiceProvider::class,
];
```

**Comment by apurva2342** [comment]
Thanks for quick reply. Yes I did. But on double checking. I tried restarting my CLI and now it works.

**Comment by aapiro** [comment]
How you do to restart your CLI?

**Comment by arisdwisuryono** [comment]
just open a new terminal, and it worked... thanks @apurva2342
