### ISSUE TITLE
Add `getTemporaryUrl` in `UrlGenerator` interface

### ISSUE THREAD

**Issue by AlexVanderbist** [spatie/laravel-medialibrary#771]
Version 6.1.0 accidentally introduced a `getTemporaryUrl` method on the `UrlGenerator` interface. This method was removed in 6.1.1 but should be added to the interface again in the next major release.

```php
    /**
     * Get the temporary url for the profile of a media item.
     *
     * @param \DateTimeInterface $expiration
     * @param array              $options
     *
     * @return string
     */
    public function getTemporaryUrl(DateTimeInterface $expiration, array $options = []): string;
```

**Comment by freekmurze** [comment]
Closing for now, but the label will make me take a look at this issue again, when creating a new major version.

**Comment by freekmurze** [comment]
This method has been re-added on the `v7` branch.
