### ISSUE TITLE
Custom Url Generator Class not recognized. 

### ISSUE THREAD

**Issue by michaelasears** [spatie/laravel-medialibrary#772]
The error that is thrown is "AzureUrlGenerator doesn't exist".  

I have installed the flysystem with the azure driver.  

This was working before the switch to Laravel 5.5. 

It seems that the config is not actually recognizing that I have a custom url generator class in place: 
_'custom_url_generator_class' => SundaySim\UrlGenerator\MyUrlGenerator::class,_

My class:

namespace SundaySim\UrlGenerator;
use Spatie\MediaLibrary\UrlGenerator\BaseUrlGenerator;

class MyUrlGenerator extends BaseUrlGenerator
{ ... }

**Comment by freekmurze** [comment]
Try clearing the config with `php artisan clear:config`
