### ISSUE TITLE
When i upgrade v5 to v6 conversions has some issues

### ISSUE THREAD

**Issue by pyaesone17** [spatie/laravel-medialibrary#774]
{
    "message": "The process has been signaled with signal \"6\".",
    "exception": "Symfony\\Component\\Process\\Exception\\RuntimeException",
    "file": "/Users/veve/Sites/newchallenges/vendor/symfony/process/Process.php",
    "line": 431,
    "trace": [
        {
            "file": "/Users/veve/Sites/newchallenges/vendor/symfony/process/Process.php",
            "line": 216,
            "function": "wait",
            "class": "Symfony\\Component\\Process\\Process",
            "type": "->"
        },
        {
            "file": "/Users/veve/Sites/newchallenges/vendor/spatie/image-optimizer/src/OptimizerChain.php",
            "line": 101,
            "function": "run",
            "class": "Symfony\\Component\\Process\\Process",
            "type": "->"
        },

But uploading image without conversions is fine.

**Comment by pyaesone17** [comment]
1. chaining nonOptimized work it.
I think the problem is something in optimizing image.

**Comment by freekmurze** [comment]
`The process has been signaled with signal "6` signifies that some of the optimization tools are installed, but that they are missing some dependencies. It could be anything really. Try reinstalling them from scratch.

Workaround is indeed to disable optimizing images by chaining `nonOptimized` to the profile.
