### ISSUE TITLE
Package saving media to wrong directory

### ISSUE THREAD

**Issue by lordraz0r** [spatie/laravel-medialibrary#776]
Hi, so I noted something peculiar with the package. Even if I set my config like this:
`'media' => [
            'driver' => 'local',
            'root'   => public_path('media'),
        ],`

it instead saves to the public path. So I end up with a structure like this.

public/1
public/2

instead of public/media/1

**Comment by brendt** [comment]
Hi @lordraz0r 

By default, the media library will use the `public` disk. Configuring a dedicated media disk in `config/filesystems.php` is the first step, which you did.

Did you also configure this disk to be used as default by the media library? This can be done in `config/medialibrary.php` as follows.

```php
return [
    'default_filesystem' => 'media'
];
```

If you don't want to use this disk as default, you can also pass a second parameter when calling the `toMediaCollection()` method on a `HasMedia` model, eg.

```php
$model
    ->addMedia("{$sourceDirectory}/{$file}")
    ->toMediaCollection($collectionName, 'media');
```

**Comment by lordraz0r** [comment]
I did configure it to use the media disk yeah. What I find very strange is when uploading say for instance from the site it seems to work fine but when the origin file exists on the server it seems to be doing this.

**Comment by lordraz0r** [comment]
This code is my implementation where it happens.

`$path = public_path() . '/tmp/users/' . $user->id . '/';

            if (!\File::exists($path)) {
                \File::makeDirectory($path, $mode = 0777, true, true);
            }

            $manager = new ImageManager();
            $new_image = $manager->make($file)->fit(300, 300)->save($path . $file->getClientOriginalName());

            $user->addMedia($new_image->basePath())->toMediaCollection('avatar');`

**Comment by brendt** [comment]
Hi @lordraz0r 

Based on your example, I've made a test setup on my local environment. I've set the `media` disk as default in `config/medialibrary.php`. For me this setup works as expected. 

Do you by any chance have config caching enabled on your environment? This might cause config changes not to happen instantly.

Can you try `php artisan cache:clear`?

If this doesn't work, could you share both your `config/filesystems.php` and `config/medialibrary.php` files?

**Comment by lordraz0r** [comment]
I infact did try that again now just to make sure and somehow it is still
doing it. 'defaultFilesystem' => 'media',is also set.

**Comment by lordraz0r** [comment]
medialibrary.php

`<?php

return [

    /*
     * The filesystems on which to store added files and derived images by default. Choose
     * one or more of the filesystems you configured in app/config/filesystems.php
     */
    'defaultFilesystem' => 'media',

    /*
     * The maximum file size of an item in bytes. Adding a file
     * that is larger will result in an exception.
     */
    'max_file_size' => 1024 * 1024 * 10,

    /*
     * This queue will be used to generate derived images.
     * Leave empty to use the default queue.
     */
    'queue_name' => '',

    /*
     * The class name of the media model to be used.
     */
    'media_model' => App\Models\MediaFile::class,

    /*
     * The engine that will perform the image conversions.
     * Should be either `gd` or `imagick`
     */
    'image_driver' => 'gd',

    /*
     * When urls to files get generated this class will be called. Leave empty
     * if your files are stored locally above the site root or on s3.
     */
    'custom_url_generator_class' => null,

    /*
     * The class that contains the strategy for determining a media file's path.
     */
    'custom_path_generator_class' => null,

    's3' => [
        /*
         * The domain that should be prepended when generating urls.
         */
        'domain' => 'https://xxxxxxx.s3.amazonaws.com',
    ],

    'remote' => [
        /*
         * Any extra headers that should be included when uploading media to
         * a remote disk. Even though supported headers may vary between
         * different drivers, a sensible default has been provided.
         *
         * Supported by S3: CacheControl, Expires, StorageClass,
         * ServerSideEncryption, Metadata, ACL, ContentEncoding
         */
        'extra_headers' => [
            'CacheControl' => 'max-age=604800',
        ],
    ],

    /*
     * These generators will be used to created conversion of media files.
     */
    'image_generators' => [
        Spatie\MediaLibrary\ImageGenerators\FileTypes\Image::class,
        Spatie\MediaLibrary\ImageGenerators\FileTypes\Pdf::class,
        Spatie\MediaLibrary\ImageGenerators\FileTypes\Svg::class,
        Spatie\MediaLibrary\ImageGenerators\FileTypes\Video::class,
    ],

    /*
     * FFMPEG & FFProbe binaries path, only used if you try to generate video
     * thumbnails and have installed the php-ffmpeg/php-ffmpeg composer
     * dependency.
     */
    'ffmpeg_binaries' => '/usr/bin/ffmpeg',
    'ffprobe_binaries' => '/usr/bin/ffprobe',
];
`

and filesystems.php

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default filesystem disk that should be used
    | by the framework. A "local" driver, as well as a variety of cloud
    | based drivers are available for your choosing. Just store away!
    |
    | Supported: "local", "ftp", "s3", "rackspace"
    |
    */

    'default' => 'local',

    /*
    |--------------------------------------------------------------------------
    | Default Cloud Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Many applications store files both locally and in the cloud. For this
    | reason, you may specify a default "cloud" driver here. This driver
    | will be bound as the Cloud disk implementation in the container.
    |
    */

    'cloud' => 's3',

    /*
    |--------------------------------------------------------------------------
    | Filesystem Disks
    |--------------------------------------------------------------------------
    |
    | Here you may configure as many filesystem "disks" as you wish, and you
    | may even configure multiple disks of the same driver. Defaults have
    | been setup for each driver as an example of the required options.
    |
    */

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => public_path(),
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => 'your-key',
            'secret' => 'your-secret',
            'region' => 'your-region',
            'bucket' => 'your-bucket',



        ],
        'media' => [
            'driver' => 'local',
            'root'   => public_path('media'),
        ],
    ]
];
`

**Comment by brendt** [comment]
Hi @lordraz0r 

The default filesystem parameter is not correct in your `config/medialibrary.php`, it should be the following.

```
[
    // ...

    'default_filesystem' => 'media',
]
```

Instead of `defaultFilesystem`

**Comment by lordraz0r** [comment]
Haha thanks a lot. I was probably being an idiot.
