### ISSUE TITLE
Delete Temp Files

### ISSUE THREAD

**Issue by matthewscalf** [spatie/laravel-medialibrary#777]
When adding media from a url you do not delete the tmp file. I just ran an import on a project for 40k images and it worked splendidly, except it filled the disk because the temp files were never removed.

**Comment by AlexVanderbist** [comment]
You're right! I'll look into it.

**Comment by BrentRobert** [comment]
I can't reproduce this bug.
When using the following code it deletes the tmp files:

```
$user = User::find(1);
$user->addMediaFromUrl('http://ichef.bbci.co.uk/images/ic/640x360/p04nfr07.jpg')->toMediaCollection('images');
```

When using the following, it doesn't (as it should)
```
$user = User::find(1);
$user->addMediaFromUrl('http://ichef.bbci.co.uk/images/ic/640x360/p04nfr07.jpg')->preservingOriginal()->toMediaCollection('images');

```

**Comment by matthewscalf** [comment]
You are totally right. I did not notice I had the preservingOriginal set at the end of the chain :sob: I guess that is what happens when you work too late. Thanks!
