### ISSUE TITLE
using your own media model

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-medialibrary#779]
I'm trying to get this to work with a Mongodb model and running into some weird problems.. regardless of that I am trying to use a different Media model than the default one

The configuration file allows you to set your own model. So I changed it to a model in my own namespace and am running into this issue now:

```
Type error: Argument 1 passed to Spatie\MediaLibrary\MediaRepository::__construct() must be an instance of Spatie\MediaLibrary\Media, instance of App\Models\Media given
```

below is the line in MediaRepository that causes this problem. I guess since the constructor has Media $model in it and no actual namespace for the Media model since it's in the same folder.. it just expects the model to be of that same class... how to work around this?

```
    /** @param \Spatie\MediaLibrary\Media $model */
    public function __construct(Media $model)
    {
        $this->model = $model;
    }
```

**Comment by freekmurze** [comment]
You can solve this by letting your model extend `Spatie\MediaLibrary\Media`. Reopen this issue if that doesn't solve your problem.
