### ISSUE TITLE
[help wanted]Create zip to downloads from multiple files

### ISSUE THREAD

**Issue by elamotte** [spatie/laravel-medialibrary#786]
Hi,
First of all thanks for this package, makes it really handy to manage files related to a model!

I am actually storing mutliple files around a model (let's say an Article) I want to be able to offer my end user the possibility to download all the related files from the article as a ZIP.

Actually I'm able to get back all my files attached to my article (from S3) thanks to your package, but I have to zip them directly on my server I'm affraid that the operation could be a bit heavy on final prod server...

Any input to the best way to do this properly?

**Comment by freekmurze** [comment]
Zipping files is out of scope of this package. 

You could do everything regarding zipping in queued jobs and mail the use a link when a zip operation is complete.
