### ISSUE TITLE
Revert to default if no file was found

### ISSUE THREAD

**Issue by RaoulDijksman** [spatie/laravel-medialibrary#79]
Hi, i would first of all like to thank you for this great package!

I have a situation where i would like to return a default file if the user does not have a file yet. I do not know if this is in the scope of your package, if not would you mind suggesting the best way of handling this? I like non of the possible solutions i thought of.

I am curious for your thoughts on the matter.

Thank you.

**Comment by canvural** [comment]
Just assign a default media when the user registers. And if they update it, they can use their own media.

**Comment by RaoulDijksman** [comment]
Why didn't i think of that? Thank you! I was really over thinking this.
But the addMedia() function would create a new file for every user which is not really necessary. 
Creating a media model without making a copy of the file wouldn't be possible becuase the remove function, which would remove the default file, would be called once the user uploads his own file.
Am i over thinking this again? 

Thanks again, you saved me some wierd and complicated constructions.

**Comment by sebastiandedeyne** [comment]
I'd say this is application logic and doesn't belong in the package. Maybe add a specific function for the operation to your model? E.g.:

```
public function avatar()
{
    return $this->hasMedia('foo') ? $this->getFirstMedia('foo')->getUrl() : 'somedefaulturl';
}
```
