### ISSUE TITLE
how to add/delete/replace custom property?

### ISSUE THREAD

**Issue by paulprok** [spatie/laravel-medialibrary#793]
for example now custom properties are `[]`
`$media_id->custom_properties= [ 'prop1' =>  'value1' ];`
it 'ok, now is `{"a": "b"}`

but how to make that: 
`{"prop1": "value1", "prop2": "value2"}`

in way I could get all properties, make with new temp object all I want and then save it
so how to get all properties?
I see only method `getCustomProperty('propname')`

thanx

**Comment by freekmurze** [comment]
I've added a few more examples to the relevant page in the documentation.

https://docs.spatie.be/laravel-medialibrary/v6/advanced-usage/using-custom-properties

**Comment by paulprok** [comment]
Great, thanks!

**Comment by roncarino** [comment]
Hi @freekmurze,

so you can use "withCustomProperties($array)" just when you are adding an image but not on update...correct?
So if I have something like this:

```
foreach ($slider->getMedia('images') as $key => $media) {
            $custom_properties = ['title' => 'title example', 'description' => 'desc example'];
            $media->withCustomProperties($custom_properties);
            $media->save();
        }
```
"withCustomProperties" will throw "Call to undefined method"

Should I just do something like this instead?

```
$media->setCustomProperty('title', 'title example');
$media->setCustomProperty('description', 'desc example');
```
