### ISSUE TITLE
Store media in 2 different tables

### ISSUE THREAD

**Issue by bobinrinder** [spatie/laravel-medialibrary#795]
Hi,
I would like to store some media from certain models in the regular `media` table and some in a separate table (let's say `media_public`) as we would have to synchronize them to other servers.

Any neat idea on how to do that?

I tried around but haven't found an elegant way yet... :-/

Cheers,
Robin

**Comment by freekmurze** [comment]
Storing media in two different tables is not supported. I guess the easiest way is to fork this package and try to adapt it manually to your needs.
