### ISSUE TITLE
Allow direct attribute assignment

### ISSUE THREAD

**Issue by Propaganistas** [spatie/laravel-medialibrary#8]
Hi

Just a suggestion to take Eloquent integration one step further: how about supporting attribute assignment instead of calling the trait methods?

Instead of doing:
```
$newsItem->addMedia($pathToFile, $collectionName);
```
let's do for example:
```php
$newsItem->collectionName($uploadedFile1); // inserts a single file, replaces if exists
$newsItem->collectionName(); // remove all files
$newsItem->collectionName([$uploadedFile2]); // add additional file to existing set
$newsItem->collectionName([$uploadedFile1, $uploadedFile2]); // add multiple files to existing set
// (this is just a quick visualization of how this could look like; more reasoning needs to be done, e.g. handling of empty array etc.)
```

This would certainly allow for cleaner controller methods since mass assignment will be possible.
For example [Stapler](https://github.com/CodeSleeve/stapler/blob/master/src/ORM/EloquentTrait.php) has implemented this behavior.

**Comment by freekmurze** [comment]
Those calls look really nice. I'll look into this soon.

**Comment by freekmurze** [comment]
I decided against adding this functionality as it would require to use a magic method. In the newly tagged version 2.0.0 there is a new short syntax to get a media collection.
