### ISSUE TITLE
Media library flow and implementation?

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#80]
So now I want to add profile pics for users and while I am doing that I want to solve the whole or a big part of the media question for my app and future apps.

While thinking and researching I found spatie laravel media library, which, from first glance, doesnt look bad at all with the glide thing and attaching media to models capabilities.

So now I have to come up with the flow and implementation.

Lets take profile pictures as an example. I am using dropzone. Now I want the user to drag his picture, send it to 

UserController@profilePic 

and i want to save the photo under 

public/media/avatars/ {current-year} / {current-month} / {current-date-and-time-string}-filename.jpg

AVATARs would be spesific to user profile pics, if id implement articles id want media to be stored

public/media/articles/ {current-year} / {current-month} / {current-date-and-time-string}-filename.jpg

after its uploaded I want to attach that picture to the user with the media library ( not sure if i need to create a db field for the name of the file? or is the media library handling this?)

And not i want to be able to use that users profile pic throughout my app...?

What do you think, is this flow ok?

So anyway, what do you suggest as a basic flow for uploading images, attaching them to models and in the end retrieving them?

Hope i am not bothering too much, thanks in advance.

If my question is not clear enough, just ask so i can formulate it better maybe...

**Comment by freekmurze** [comment]
Well, apart from the proposed directory structure, everything you described can be handled by the medialibrary.

You could pass your upload request to the media library like this:

```php
$user->addMedia($request->file('image'))->toCollection('avatars');
```

And you can retrieve an url to the image with this piece of code:

```php
$user->getCollection('avatars')->first()->getUrl('thumb');
```

I'm assuming that you [prepared your model](http://medialibrary.spatie.be/v3/basic-usage/preparing-your-model/) and [set up a conversion](http://medialibrary.spatie.be/v3/converting-images/defining-conversions/) named "thumb".

You really shouldn't worry about directory structure, the medialibrary handles this behind the scenes for you.

**Comment by kickthemooon** [comment]
Ok, great for the start.
now i want to have 3 conversions for profile pics, is this the right way?
```
class User extends Model implements HasMediaConversions
{
    use HasMediaTrait;

    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
             ->setManipulations(['w' => 368, 'h' => 232])
             ->performOnCollections('avatars');

        $this->addMediaConversion('medium')
            ->setManipulations(['w' => 600, 'h' => 400])
            ->performOnCollections('avatars');

        $this->addMediaConversion('large')
             ->setManipulations(['w' => 1000, 'h' => 700])
             ->performOnCollections('avatars');
    }
}
```
next, does the library also handle the names of files? does it make the names unique?

**Comment by kickthemooon** [comment]
and unfortunately, im also not sure how I set up a route for this? I want to send the post request to for example: UsersController@postProfilePic
do i need to pass any paramaters?

**Comment by freekmurze** [comment]
Files will be uploaded in seperate directories. No need to make the file names unique. Creating routes / controllers isn't a responsability of this package. If you want to know how to do that, checkout out [this awesome lesson on Laracasts](https://laracasts.com/series/build-project-flyer-with-me/episodes/11).

**Comment by kickthemooon** [comment]
thanks Freek, thanks a lot. I hope i didnt bother too much, i hope your package will be very useful to me for some time.

you didnt answer me if i can make multiple conversions for an example user profile pic.

like three sizes?

**Comment by freekmurze** [comment]
Np! Have fun using the package. If you have a question about it, don't hesitate to open another issue.
