### ISSUE TITLE
load ALL media & collections

### ISSUE THREAD

**Issue by angryalf** [spatie/laravel-medialibrary#803]
Hi!

1) is any way to load all media (insteed $model->load('media'), like getMedia() but from all collections ) ?

2) is any way to  get all collections (with or without media) ?

**Comment by paulprok** [comment]
$model->media
$model->media->keyBy('collection_name')

maybe

**Comment by freekmurze** [comment]
This indeed seems like the way to go:

```
$model->media->keyBy('collection_name')
```
