### ISSUE TITLE
Only regenerate missing conversions

### ISSUE THREAD

**Issue by AlexVanderbist** [spatie/laravel-medialibrary#809]
When running `medialibrary:regenerate` all conversions will be regenerated. This is preferred when the conversions have been updated but sometimes you just want to generate missing conversions.

Proposing a `--only-missing` flag or maybe even a `medialibrary:generate-missing` command which generates only the missing conversion files.

**Comment by freekmurze** [comment]
Makes sense, I'd accept a PR for that. Might be a good first issue for someone.

**Comment by vesper8** [comment]
this would be great!

side note.. can you currently pass a or many conversion names to this command? say you just added a new conversion and only want to generate that one.. is that currently possible?

**Comment by davidianbonner** [comment]
Hopefully this does what you're looking for.

```php
artisan medialibrary:regenerate --only-missing
```

**Comment by vesper8** [comment]
This is useful but since you're deep in it I think it would have been nice to also have a --only flag where you can pass a conversion name so it runs it (or re-runs it) whether the file is missing or not.

Your use-case is good when adding a NEW conversion that you want to run and don't want to re-run all others.

However what if you make a modification to a conversion? Then you have the same problem and the --only-missing won't address it. There could be a --only-changed but that would be very difficult or impossible to implement

So being able to specify only the name of the new/changed conversion and only run that one would be a very useful option

Thoughts?

**Comment by freekmurze** [comment]
I'd accept a PR that adds an `only` option has well. It should accept the names of one or more conversions. Only those conversions will be run (regardless of if the file already exists).

**Comment by davidianbonner** [comment]
I'll create a separate branch for an `only` option and have a look. Shouldn't be a problem to implement I don't think.

An `only-changed` option would be nice, needs a bit of thought as to how to implement it with little overhead.

**Comment by freekmurze** [comment]
Thanks @davidianbonner, much appreciated!

**Comment by davidianbonner** [comment]
No worries @freekmurze.

@vesper8 the `only-missing` option can be used along with `only` which accepts an one or multiple conversion names.

**Comment by vesper8** [comment]
I was in a rush to get this working.. not sure if this code can help you @davidianbonner at all but I'm using it to regenerate only specific conversions

I also noticed some seemingly dead bodies `$erroredMediaIds` and `{--ids=*}`

The Conversion class has some methods to filter out conversions but none of them allow to filter by name

```
            $this->arguments["conversion"] = "yourConversionName"

            $mediaFiles = $submission->getMedia('submissions');

            $this->errorMessages = [];

            $mediaFiles->each(function (Media $media) {
                try {
                    $this->createDerivedFilesCustom($media);
                } catch (Exception $exception) {
                    $this->errorMessages[$media->id] = $exception->getMessage();
                }
            });

    public function createDerivedFilesCustom(Media $media)
    {
        $profileCollection = ConversionCollection::createForMedia($media);

        $conversions = $profileCollection->getConversions($media->collection_name);

        for ($i = 0; $i < count($conversions); $i++) {
            if($conversions[$i]->getName() != $this->arguments["conversion"]) {
                unset($conversions[$i]);
            }
        }

        $this->fileManipulator->performConversions(
            $conversions,
            $media
        );
    }
```

**Comment by davidianbonner** [comment]
Thanks @vesper8. Submitted a PR just before this that implements only the specified conversions.

https://github.com/davidianbonner/laravel-medialibrary/blob/f5fc5e3cb794eeafdb367c22624e7bc3599b9c63/src/FileManipulator.php#L30

**Comment by freekmurze** [comment]
We'll handle this further in #811
