### ISSUE TITLE
undefined method getCollection()

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#81]
So I am trying to retrieve an image like this:
```
$avatarthumb = $user->getCollection('avatars')->first()->getUrl('thumb');
```
and i get an error like this: 
```
Call to undefined method Illuminate\Database\Query\Builder::getCollection()
```
help? 

I managed the uploading of pictures. The folder structure i get is like this:

![medialibraryfolderstructure](https://cloud.githubusercontent.com/assets/7913974/10754324/1fabfecc-7c97-11e5-9de1-e44c102fa9cd.jpg)

So this is ok and scaleable to lets say 100k + images?

**Comment by freekmurze** [comment]
Ah, I gave you an example with the old syntax. Sorry about that

You should use `getMedia` instead of `getCollection`.

The largest library I have is a few thousand files. If you run into problem when using 100k+ images, let me know.
