### ISSUE TITLE
Call to undefined method Spatie\MediaLibrary\FileAdder\FileAdder::preservinOriginal()

### ISSUE THREAD

**Issue by RudySIMPLON** [spatie/laravel-medialibrary#813]
hello !

I have this errors  =
 Call to undefined method Spatie\MediaLibrary\FileAdder\FileAdder::preservinOriginal()

laravel version : 5.1 and medialibrary :^4.0.0

My route =  Route::get('test',function (){
    Test::create()
        ->addMedia(storage_path('demo/laraconeu.jpg'))
        ->preservinOriginal()
        ->toMediaCollection();
});

**Comment by freekmurze** [comment]
Seem you have a typo there. Method name is probably `preservin**g**Original`

**Comment by RudySIMPLON** [comment]
I corrected,  but i have the same error.

**Comment by RudySIMPLON** [comment]
thank's it work !!
