### ISSUE TITLE
Laravel Charts Install

### ISSUE THREAD

**Issue by Amaarys** [spatie/laravel-medialibrary#818]
Hello,

I try to install charts on my laravel project. But i have some issues.

> c:\wamp\www\my-site\aspro.dev>composer`
require consoletvs/charts:5.*
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
Problem1
    - Conclusion: don't install laravel/framework v5.2.6
    - elibyy/laravel-tcpdf v0.0.1 requires illuminate/support 5.0.x -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - elibyy/laravel-tcpdf v0.0.2 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - elibyy/laravel-tcpdf v0.0.3 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - elibyy/laravel-tcpdf v0.0.4 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - elibyy/laravel-tcpdf v0.0.5 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - elibyy/laravel-tcpdf v0.0.6 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.1.41|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.2.6
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.2.6
    - Installation request for laravel/framework (locked at v5.2.6, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.6].
    - Installation request for elibyy/laravel-tcpdf 0.* -> satisfiable by elibyy/laravel-tcpdf[v0.0.1, v0.0.2, v0.0.3, v0.0.4, v0.0.5, v0.0.6].

> Installation failed, reverting ./composer.json to its original content.

I Really need a help.

**Comment by freekmurze** [comment]
This issue does not concern the medialibrary, but seems to be something specific to your project.

**Comment by Amaarys** [comment]
I want to install consoletvs/charts on my Laravel project. When try it, These issues was generated.

How can I do  to install consoletvs/charts?

**Comment by driesvints** [comment]
@Amaarys try here: https://github.com/ConsoleTVs/Charts
