### ISSUE TITLE
getMedia() always returns an empty collection

### ISSUE THREAD

**Issue by adriaanvermeire** [spatie/laravel-medialibrary#819]
I just started using this package to speed up image-upload processing for a project i've been making, but after I associate the image with the model, I can't get it back via getMedia(). On both models I've tested it on, it always gives back an empty collection. 

Am I missing some set up?

**Comment by freekmurze** [comment]
What is the output of `$yourModel->media`?

Are there any records in the `Media` table?

**Comment by adriaanvermeire** [comment]
The records are being added to the `Media` table and the output of `$myModel->media` gives back the correct data. Using `$myModel->getMedia()` still results in an empty collection.

**Comment by adriaanvermeire** [comment]
Also is there any way to limit the amount of files associated with a model intance? 
Say you can only have one avatar for a user. If the user then changes his avatar, the older picture gets deleted.

**Comment by freekmurze** [comment]
What is the value of `collection_name` in the Media table. Try passing that value to `getMedia()`.

> Say you can only have one avatar for a user. If the user then changes his avatar, the older picture gets deleted.
 
No, this is something you should handle in your own application.

**Comment by adriaanvermeire** [comment]
Thanks! That worked!
