### ISSUE TITLE
Different disks for different models

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#82]
Can i define different disks for different models?

**Comment by freekmurze** [comment]
The package can use multiple disks, but your application logic should determine which file should go to which disk.

**Comment by kickthemooon** [comment]
is this ok?
```
'disks' => [

        'local' => [
            'driver' => 'local',
            'root'   => storage_path('app'),
        ],

        'media' => [
            'driver' => 'local',
            'root'   => public_path().'/media',
        ],

        'profilesmedia' => [
            'driver' => 'local',
            'root'   => public_path().'/profilesmedia',
        ],
```

**Comment by freekmurze** [comment]
seems good

**Comment by kickthemooon** [comment]
can I specify a disk here somewhere?
```
$user->addMedia($request->file('file'))->toCollection('avatars');
```

**Comment by freekmurze** [comment]
The [documentation](http://medialibrary.spatie.be/) mentions on how to do this.

**Comment by vladvisinescu** [comment]
Following this issue, I can`t store images to a subfolder of "media" using the toMediaLibraryOnDisk() method.
What am I missing ?

**Comment by freekmurze** [comment]
The idea behind the medialibrary is that you don't have to manage the media folder. You can specify were the media folder should reside by configuring a filesystem in `app/config/filesystems.php` and let the package use that filesystem.
