### ISSUE TITLE
I'd like to be able to delete the original upload, leaving the conversions

### ISSUE THREAD

**Issue by snapey** [spatie/laravel-medialibrary#821]
Is this possible? I store two sizes suitable to display on the site, but I don't need to keep the user's 4000 pixel original.

I know I could get the path and unlink the file but not sure what implications this would have.  I don't plan to allow conversions to be regenerated.

**Comment by freekmurze** [comment]
The package doesn't do this for you, but you can manually delete the original file with 

```php
unlink($media->getPath());
```

**Comment by ctf0** [comment]
@snapey have u found an automated way for doing that ?

**Comment by vagafonov** [comment]
If using s3 or local
Illuminate\Support\Facades\Storage\Storage::disk($media->disk)->delete($media->getPath());
