### ISSUE TITLE
Need Temp URL for getFirstMediaURL

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#823]
Is there a way to do `$post->getFirstMediaUrl('posters')` with temporary URLs on S3?

**Comment by freekmurze** [comment]
Currently there's no method for that but I'd accept a PR that adds `getFirstTemporyUrl` to the package. Internally it should call  `getTemporaryUrl`.

**Comment by lalitvj** [comment]
Hey Freek,

Added getTemporaryUrl.
Check out with my first pull request for Spatie. Need feedbacks

**Comment by freekmurze** [comment]
It was a perfect PR, thanks!

**Comment by timgavin** [comment]
Just updated Media Library to test and receive `Call to undefined method Spatie\MediaLibrary\Media::getFirstTemporyUrl()` error. Do I need to pull in the dev version?

Also, the method name is misspelled. Currently it's `getFirstTemporyUrl` and it should be `getFirstTemporaryUrl` :)

**Comment by freekmurze** [comment]
I've fixed the spelling of the method. It's available in v6.6.1
