### ISSUE TITLE
Disable ffmpeg For Video Conversions

### ISSUE THREAD

**Issue by s1rc** [spatie/laravel-medialibrary#824]
I've registered some media conversions for a data model (small, medium, large). Since laravel-medialibrary only handles conversions for images I'm using AWS ElasticTranscoder to generate my video conversions and video thumbnails.

I've already setup my custom path generator to change the extensions on video conversions from .jpg to .mp4, however when the media is added to the models mediaCollection ffmpeg is still called for the thumbnail.

Is there a way to disable calling ffmpeg for video conversions (so I don't have to catch the `ExecutableNotFoundException`), or better yet register media conversions that do not perform any action if the media type is video?

As a side note, I think because I'm not using ffmpeg and catching the `ExecutableNotFoundException`, the file get's put into storage properly, however the temporary file in `/storage/medialibrary/temp/` is not deleted.

**Comment by freekmurze** [comment]
You can remove `Spatie\MediaLibrary\ImageGenerators\FileTypes\Video::class`  from the `image_generators` in the config file.
