### ISSUE TITLE
FileDoesNotExist

### ISSUE THREAD

**Issue by codeitlikemiley** [spatie/laravel-medialibrary#832]
Hi Im windows user, im having hard time with the path ,  causing error  FileDoesNotExist

the usual windows path uses backslash instead of slash..

when i store a new file

```php
$path = $request->file->store('public');
//  $path =  public/uploads/3BuH2sf1kcOLESGfY9r7DPIVTG34U3hYT5G0DJzk.jpeg
```

the path is in the format  with slash...

but when i do use storage_path()

i get this
```
C:\Users\myuser\sites\www\laravel\storage\public
```

so when we combine now storage_path and the $path

```
C:\Users\myuser\sites\www\laravel\storage\public/uploads/3BuH2sf1kcOLESGfY9r7DPIVTG34U3hYT5G0DJzk.jpeg
```

cause the  

```
$order->addMedia(storage_path($path))
```

to have an error of FileDoesNotExist

Anyhelp i can go around with it in development?  Since im using windows , help would be much appreciated

**Comment by AlexVanderbist** [comment]
Hi, 

I haven't used Windows for a while so I'm not sure what the expected separator would be for a relative path like the one in your first code example. Afaik a forward slash should always work, even on Windows.

Something strange I noticed when looking into this is that the [`storage_path` helper](https://github.com/laravel/framework/blob/9c9b86c692529c82f44c635ef363b4d709bc2f39/src/Illuminate/Foundation/helpers.php#L837-L848) uses the `DIRECTORY_SEPARATOR` constant but Laravel's [`FilesystemAdapter`](https://github.com/illuminate/filesystem/blob/346d406bd81d10c1ed5c281711f68e681d5e4592/FilesystemAdapter.php#L160-L176) doesn't... 

Maybe someone with some more Windows experience can shed some light on this?

**Comment by introwit** [comment]
@codeitlikemiley you can directly do `$order-> addMediaFromRequest('file')`
