### ISSUE TITLE
Position image

### ISSUE THREAD

**Issue by hugofabricio** [spatie/laravel-medialibrary#833]
Hi, its possible on Manipulation FIT_FILL, define position of image, left or right, per example, but the image in example only position in center.

https://docs.spatie.be/images/image/example-background.png

How to set x-offset and y-offset?

**Comment by freekmurze** [comment]
Under the hood this package leverages Glide. If they can do the manipulation you want, our package can do it. If not, changes are our package can't do it.

Take a look at their docs for some examples: http://glide.thephpleague.com/
