### ISSUE TITLE
Conditional Manipulations

### ISSUE THREAD

**Issue by sidis405** [spatie/laravel-medialibrary#837]
Laravel: 5.4
Medialibrary: 4.9
Php: 7.1

Hi all.

I have the following question for anyone that has an idea that for the life of me i can't seem to find a way.

I have the following manipulation set up that per se works just fine as expected and it's great 👍 

```
 $this->addMediaConversion('public')
             ->setManipulations([
                'fit'=> 'crop',
                'w' => 1600,
                'h' => 1016
                ]);
```

The matter that i'm having is domain specific.
The images coming through can be horizontally or vertically oriented.

Now when the image is horizontal this gives a fine output. The image is brought to the correct dimensions and then it's cropped. Cool.
The issue arises when the image is vertical. The manipulation works again as expected and clearly a portion (middle portion) of the image is kept and the rest is cropped.

Now the question is this.

When the image is vertical, in fact i would like to perform the following manipulation:

```
 $this->addMediaConversion('public')
             ->setManipulations([
                'fit'=> 'fill',
                'w' => 1600,
                'h' => 1016,
                ]);
```

How can i conditionally set this up if when i define the conversions i have no way to access the media instance that i am manipulating?

If anyone has a suggestion i'd greatly appreciate.

Thanks in advance

**Comment by sebastiandedeyne** [comment]
The current model gets passed to the `registerMediaConversions` method.

```
public function registerMediaConversion(Media $media)
{
    if ($media->something) {
        // ...
    }
}
```

You can do whatever you want there then.

**Comment by sidis405** [comment]
Thanks for the reply, but the model implementing HasMediaConversions has to abide to the interface that currently on 4.9 is

```
<?php
namespace Spatie\MediaLibrary\HasMedia\Interfaces;

interface HasMediaConversions extends HasMedia
{
    /**
     * Register the conversions that should be performed.
     *
     * @return array
     */
    public function registerMediaConversions();
}
```

so media does not get currently passed unfortunately.
:/

**Comment by sebastiandedeyne** [comment]
Oh sorry, missed the version number. I'm afraid that isn't supported yet in older versions of the library :/

If diskspace isn't an issue, I'd recommend generating two separate conversions...

**Comment by sidis405** [comment]
No worries man. Seems like this is available on v6 so i updated Laravel to 5.5 and updated medialibrary to v6.

So i got a way to do what i needed.

On a related note. The only way i could think of to get the dimensions of the retrieved media was to do it with Intervention\Image since it's already installed for Glide. 

Does Medialibrary provide an api to fetch dimensions of resulting media?

**Comment by sebastiandedeyne** [comment]
Hmm I don't think so. Might be nice to have though, what do you think @freekmurze? (or is it already possible?)

**Comment by sidis405** [comment]
I did find something that allowed me to use the media props as object properties, but I was getting different values compared to intervention\image which as giving working value sets.

As soon as I get to the office I'll post back with a reference to the docs regarding what I meant.
