### ISSUE TITLE
Advice needed: How to deal with alt text for images?

### ISSUE THREAD

**Issue by addorange** [spatie/laravel-medialibrary#840]
Hi,

thanks for the amazing package. I may have a silly question around it’s use: How would you attach and retrieve alt text for the uploaded images? By using custom properties or is another option the way to go?

**Comment by timgavin** [comment]
I use custom properties for all sorts of things; I think they would be perfect for alt tags.

```
<img alt="{{ $media->getCustomProperty('alt') }}" src="{{ $media->getFirstMediaUrl('images', 'thumb') }}">
```

**Comment by freekmurze** [comment]
Here are the docs on custom properties: https://docs.spatie.be/laravel-medialibrary/v6/advanced-usage/using-custom-properties

**Comment by addorange** [comment]
Thanks for the advice :-).
