### ISSUE TITLE
Question: Where is the file uploaded?

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#841]
To clarify: when uploading to S3, does the file go straight to S3, or to the app's server and then S3?

I'm allowing videos to be uploaded, which will then be - if needed - re-encoded on a separate server. Using Media Library, will the videos be uploaded to the app server, so that I then have to transfer them to the encoding server? Or will they go straight to the encoding server if it's defined in `filesystem.php`?

The encoding server is a DigitalOcean droplet, so the only way to access it is via SFTP.

**Comment by freekmurze** [comment]
The package really doesn't concern itself with the upload. You should manage the upload to the server. And from there on you can use the methods this package provides such as:

```php
$yourModel->addMedia($yourFile)->toMediaCollection($collectionName, $diskName);
```
