### ISSUE TITLE
[Question] - Adding single image into different collections.

### ISSUE THREAD

**Issue by xenonthong** [spatie/laravel-medialibrary#845]
Is there any way I can add an image uploaded by user and add them to multiple collections?

I only intend to keep one copy of the original image in my s3 bucket. What i'm currently doing is as such

```
$model->addMedia($image)
    ->preservingOriginal()
    ->toMediaCollection('collection-1');

// Removing preservingOriginal() will cause File `/private/var/tmp/php7zWmZ7` does not exist
$listing->addMedia($image)
     ->toMediaCollection('collection-2');
````

Doing the above stores 2 copy of the original image

**Comment by AlexVanderbist** [comment]
Hi, there's currently no way to do this. You can however add your own pivot model that supports adding one `Media` to many models. Check out this issue that has some more info on that: https://github.com/spatie/laravel-medialibrary/issues/205
