### ISSUE TITLE
Switching from local storage to S3?

### ISSUE THREAD

**Issue by jpmurray** [spatie/laravel-medialibrary#849]
Hello,

Just looking for inputs. I have v4 on `laravel-medialibrary` on a site where we would like to start using S3 rather than the local storage. We curently have a bit more than a year worth of images on local storage, so I'm wondering...

Is there any easy way to just transfer them to S3? Would it be as easy as switching the driver in `laravel-medialibrary` and uploading the files using the same structure of folder on S3?

**Comment by jpmurray** [comment]
Well, apart from changing the `disk` field in the database too... Yes, that's how easy it is!

Closing! 👍

**Comment by sawirricardo** [comment]
Hi @jpmurray, I'm wondering if you know how the migration process steps looked like? I also have a production app with local storage and thinking to start moving to s3.
