### ISSUE TITLE
Deleting collection of models won't delete associated media

### ISSUE THREAD

**Issue by jelgervisser** [spatie/laravel-medialibrary#852]
Hi,
I'm not sure if this is a bug; have searched the docs but can't find any info on it. In the following situation the Medialibrary **will not delete** associated media:

`News::where('status', 0)->delete();`

All news models with status 0 are deleted, but associated media are still present. Medialibrary only deletes associated media if I directly delete a model, like so:

`foreach($news as $newsItem){
    $newsItem->delete();
}`

Is this default behavior of the Medialibrary or am I missing something?

regards, Jlgr

**Comment by freekmurze** [comment]
This is a limitation of Laravel itself. 

Medialibrary leverages model events to detect when stuff gets deleted. In case you use a query to delete stuff Laravel will not fire off Model events (because the models are not retrieved, but directly deleted in the db).

**Comment by jelgervisser** [comment]
Ok, thanks for answering.
