### ISSUE TITLE
Apply custom path generation for specific files

### ISSUE THREAD

**Issue by Mirdrack** [spatie/laravel-medialibrary#859]
Hello!

Im using a custom media generator class to save my files 
{modelValue}/{modelId}/{name}
but now I have remove the **modelId** but not for all files

Is there a way to apply specific media generator classes only for some files?

Let me know if you need more information
Thanks in advance

**Comment by AlexVanderbist** [comment]
I assume by "media generator" you mean a custom path generator? 

If that's the case: there's no way to assign a specific path generator to a specific model. You can however implement this in your custom path generator. For example something like this (untested):
```php
class CustomPathGenerator extends BasePathGenerator implements PathGenerator
{
    public function getPath(Media $media): string
    {
        if ($media->model_type === ModelWithCustomPath::class) {
            return 'custom/path/logic/here';
        }

        return parent::getBasePath($media).'/';
    }

    public function getPathForConversions(Media $media): string
    {
        // same as `getPath`
    }
}
```

Hopefully this is what you're after.
