### ISSUE TITLE
image path issue

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#86]
so upload and storing the image works ok:
```
public function avatarUpload(Request $request, $slug)
    {
        $user = User::findBySlug($slug);

        $user->clearMediaCollection('avatars');

        $user->addMedia($request->file('file'))->toCollectionOnDisk('avatars', 'avatars');

        return 'Working on it';
    }
```
now i am retrieving the image like this:
```
$thumbprofileimg = $user->getMedia('avatars')->first()->getUrl('medium');
```
this gives me a path like this:
```
\media\avatars/30/conversions/medium.jpg 
```

it works in chrome but not in firefox. the image could not be loaded.

These are my disks:
```
        'media' => [
            'driver' => 'local',
            'root'   => public_path().'/media',
        ],

        'avatars' => [
            'driver' => 'local',
            'root'   => public_path().'/media/avatars',
        ],
```

**Comment by freekmurze** [comment]
I can't see anything wrong except that `\media\avatars/30/conversions/medium.jpg` is not a valid url.

**Comment by kickthemooon** [comment]
of course it is not a valid url but that is what I get from:
```
$user->getMedia('avatars')->first()->getUrl('medium');
```
and this is my disk:
```
'avatars' => [
            'driver' => 'local',
            'root'   => public_path().'/media/avatars',
        ],
```

**Comment by freekmurze** [comment]
Could you look up what these functions return

```
$this->getStoragePath()
public_path()
$this->getBaseMediaDirectory()
$this->getPathRelativeToRoot()
```
in
https://github.com/spatie/laravel-medialibrary/blob/3.7.0/src/UrlGenerator/LocalUrlGenerator.php#L18-L22

**Comment by freekmurze** [comment]
Could you look up what these functions return

```php
$this->getStoragePath()
public_path()
$this->getBaseMediaDirectory()
$this->getPathRelativeToRoot()
```
in
https://github.com/spatie/laravel-medialibrary/blob/3.7.0/src/UrlGenerator/LocalUrlGenerator.php#L18-L22

**Comment by kickthemooon** [comment]
how would i look that up? not sure :(

**Comment by freekmurze** [comment]
You can do this quick and dirty by adding some echo statements that that
function.

I'm pretty sure something in hour configuration is not right and getting
the output of those functions might ging us a clue

On Sunday, 1 November 2015, kickthemooon <notifications@github.com> wrote:

> how would i look that up? not sure :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spatie/laravel-medialibrary/issues/86#issuecomment-152860827>
> .
>


-- 
Freek Van der Herten
https://spatie.be
+32 495 84 27 91

**Comment by kickthemooon** [comment]
i tried adding it like this but not working:
```
echo $this->getBaseMediaDirectory().'/'.$this->getPathRelativeToRoot();
```
hmm

**Comment by kickthemooon** [comment]
i did dd like this:
```
public function getUrl()
    {
        if (!string($this->getStoragePath())->startsWith(public_path())) {
            throw new UrlCouldNotBeDetermined('The storage path is not part of the public path');
        }

        dd($this->getBaseMediaDirectory().'/'.$this->getPathRelativeToRoot());

        return $this->getBaseMediaDirectory().'/'.$this->getPathRelativeToRoot();
    }
```
the out put is of course the same invalid url:
"\media\avatars/46/conversions/medium.jpg"

**Comment by kickthemooon** [comment]
now i did dd just on:
```
dd($this->getBaseMediaDirectory());
```
the out put is:
```
Str {#271 ▼
  #string: "\media\avatars"
}
```

**Comment by freekmurze** [comment]
What is the output of `getStoragePath` in that file?

**Comment by kickthemooon** [comment]
"C:\wamp\www\larasilos\public\media\avatars"

**Comment by kickthemooon** [comment]
this is the functions:
```
protected function getStoragePath()
    {
        $diskRootPath = $this->config->get('filesystems.disks.'.$this->media->disk.'.root');

        return realpath($diskRootPath);
    }
```
and in my case it returns this:
"C:\wamp\www\larasilos\public\media\avatars"

**Comment by kickthemooon** [comment]
any ideas?

**Comment by freekmurze** [comment]
I think you might have discovered a bug in the package when working in Windows. The directory delimiter is different from the one used on linux-like hosts.  I'll investigate this further and add a solution soon.

**Comment by kickthemooon** [comment]
I hope it'll be fixed soon :)

**Comment by kickthemooon** [comment]
i managed to get it working, but it is probably a dirty way:
```
public function getUrl()
    {
        if (!string($this->getStoragePath())->startsWith(public_path())) {
            throw new UrlCouldNotBeDetermined('The storage path is not part of the public path');
        }

        return str_replace('\\','/',$this->getBaseMediaDirectory()).'/'.$this->getPathRelativeToRoot();
    }
```

**Comment by freekmurze** [comment]
It's a bit dirty yes, but if I don't find a better way to fix this, that code 'll probably end up in the package.

**Comment by freekmurze** [comment]
This is fixed in v3.7.1 of the package.

**Comment by kickthemooon** [comment]
return $this->makeCompatibleForNonUnixHosts($url); 
nice :)

**Comment by chisumo2016** [comment]
I am using window OS  .

[41;1m Spatie\MediaLibrary\Exceptions\FileCannotBeAdded\UnreachableUrl [49;22m : [33mUrl `C:\laragon\www\Real-Estate-Application\public\images/locations/birmingham.jpg` cannot be
reached[39m

  at [32mC:\laragon\www\Real-Estate-Application\vendor\spatie\laravel-medialibrary\src\Exceptions\FileCannotBeAdded\UnreachableUrl.php[39m:[32m11[39m
     7| class UnreachableUrl extends FileCannotBeAdded
     8| {
     9|     public static function create(string $url)
    10|     {
  > 11|         return new static("Url `{$url}` cannot be reached");
    12|     }
    13| }


$locationObject->addMediaFromUrl(public_path('images/locations/' . $slug . '.jpg' ))
            ->toMediaCollection('photo');
