### ISSUE TITLE
I could not figure out how to safe dynamic generated PDFs (Question)

### ISSUE THREAD

**Issue by maximaexchen** [spatie/laravel-medialibrary#860]
Hi. 

I try to store dynamic generated PDFs with laravel-dompdf.

```
$pdf = PDF::loadView('account.pdf', compact('procedure' ));

 $procedure
            ->addMedia($pdf)
            ->toMediaCollection('procedure');
```
So I get the Error.
"Only strings, FileObjects and UploadedFileObjects can be imported"

So this way it does not work. ;-)

Could I some how directly save it to a storage path (custom PathGenerator) with the associated collection_name?
If yes how should I do that? 
Or do I need to a "temp-folder".

Any help appreciated

**Comment by AlexVanderbist** [comment]
Hi @maximaexchen 

>Could I some how directly save it to a storage path (custom PathGenerator) with the associated collection_name?

There's currently no way to save to the media's conversion path directly. That means you're right about having to save your pdf to a temp folder first.

Something like this:

```php
$pdf = PDF::loadView('account.pdf', compact('procedure' ));
$pdfPath = storage_path("temp_procedure_pdfs/{$procedure->id}.pdf");
$pdf->save($pdfPath);

 $procedure
            ->addMedia($pdfPath)
            ->toMediaCollection('procedure');
```
