### ISSUE TITLE
How to keep the quality of converted images?

### ISSUE THREAD

**Issue by faustuzas** [spatie/laravel-medialibrary#861]
Hello,

when I convert image's width and height image's quality drops ridiculously. I can even see the pixels. How to keep it higher?

Thank you

**Comment by freekmurze** [comment]
Normally that shouldn't happen. Could you provide the code you're using?

**Comment by faustuzas** [comment]
I have it like this


`public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('resized')
            ->height(50)
            ->width(50)
            ->nonQueued();
    }`

**Comment by freekmurze** [comment]
What happens if you set the height and width to higher values?

**Comment by faustuzas** [comment]
The quality still is bad.

Here is the original:
![logo_baltas](https://user-images.githubusercontent.com/33425982/33273053-ce39a3bc-d394-11e7-8d3e-627b48aba4c8.png)

Converted:
![resized](https://user-images.githubusercontent.com/33425982/33273072-db86a204-d394-11e7-87c7-986a4905fd9a.jpg)

**Comment by gerciljunio** [comment]
the topic is closed, but I saw that the previous user left you unanswered and as I am with the same problem, I decided to comment!

I [have an image](https://s3.amazonaws.com/toaberto/media_dev/b53b3a3d6ab90ce0268229151c9bde11/c/small.jpg), 260x260px, with the following conversion:

```
$this->addMediaConversion('large')
 ->width(1000)
 ->height(1000)
 ->optimize()
 ->nonQueued();
```

the image converted to 1000x1000px [is this](https://s3.amazonaws.com/toaberto/media_dev/b53b3a3d6ab90ce0268229151c9bde11/c/large.jpg)

and also has a conversion to 600px

```
$this->addMediaConversion('medium')
 ->width(600)
 ->height(600)
 ->optimize()
 ->nonQueued();
```

the image converted to 600x600px [is this](https://s3.amazonaws.com/toaberto/media_dev/b53b3a3d6ab90ce0268229151c9bde11/c/medium.jpg)

is this the expected outcome, or should the package improve quality?
thanks!
