### ISSUE TITLE
quietly dies without logging an error when handling conversions on large images

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-medialibrary#862]
I've noticed something with this package. And I've noticed the same thing is happening with your laravel-glide package

When trying to do a conversion on an image that's larger than 4mb, whether with laravel-medialibrary or laravel-glide, the operation fails but no error is logged

In the case of laravel-glide, an error 500 is the only indication

In the case of this package, I was trying to run "pa medialibrary:regenerate" from the command line and when it got to the first image that was 4mb >, it just crashed, again no error in the logs and no error in the command line

I temporarily added these lines to the RegenerateCommand
```
        ini_set("max_execution_time", 9999);
        ini_set("memory_limit", "2048M");
```

and I was then able to run the regeneration with success

I don't know if it's possible, but I think this error should be better handled and caught

**Comment by freekmurze** [comment]
This error is caused by running out of memory. The package can't really do anything about that.

You could try to register your own error handling function in `register_shutdown_function`. And handle the situation.
