### ISSUE TITLE
is there a simple way to convert an existing library to a new custom media path?

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-medialibrary#865]
On one of the first projects I tested laravel-medialibrary on, I initially just used the default media path but now I would like to make use of a custom media path.

The thing is there are already thousands of uploading images.

I can build a custom converter but that sounds like a big headache and I figured maybe there's an easier way.

The current path is the default so 

/storageFolder/media_id/image.jpg
/storageFolder/media_id/conversions/thumb.jpg

And the new custom media path will be

/storageFolder/md5(model_id)/md5(media_id)/image.jpg
/storageFolder/md5(model_id)/md5(media_id)/thumb.jpg

```
class CustomMediaPath implements PathGenerator
{
    /*
    * Get the path for the given media, relative to the root storage path.
    */
    public function getPath(Media $media): string
    {
        $profile = Profile::find($media->model_id);

        $fileFolder = md5($media->id);
        $path = "{$profile->id}/{$fileFolder}/";
        return $path;
    }

    /*
     * Get the path for conversions of the given media, relative to the root storage path.
     * @return string
     */
    public function getPathForConversions(Media $media): string
    {
        $profile = Profile::find($media->model_id);

        $fileFolder = md5($media->id);
        $path = "{$profile->id}/{$fileFolder}/";
        return $path;

    }
```

Is there a simple way to do this that isn't scary and annoying? :)

**Comment by freekmurze** [comment]
The package has no support for converting entire media libraries to new paths. You need the create your own bash / php / whatever script for that.
