### ISSUE TITLE
Is there an easy way to get images from storage directory?

### ISSUE THREAD

**Issue by faustuzas** [spatie/laravel-medialibrary#866]
Hello,

I want to store my images in storage directory. How can I easily retrieve them in my blades?

Filesystem: 
`        'media' => [
            'driver' => 'local',
            'root' => storage_path('media')
        ]`

Saving image:

`public function updateAvatar(Request $request){

        $this->validate($request, [
            'avatar' => 'required|image|max:1000'
        ]);

        $user = Auth::user();

        $file = $request->file('avatar');

        $fileName = $file->getClientOriginalName();

        $file->move(storage_path(), $fileName);

        if($user->hasMedia('avatars')){
            $user->clearMediaCollection('avatars');
        }

        $user->addMedia(storage_path() . '/' . $fileName)->toMediaCollection('avatars');

        return redirect()->route('auth.change_password');
    }`

I tried like that: 
`<img src="{{ Auth::user()->hasMedia('avatars') ? Auth::user()->getFirstMediaPathl('avatars', 'resized') : '/images/avatar_placeholder.jpg'}}">`

**Comment by freekmurze** [comment]
Looks good, apart from the typo `getFirstMediaPathl` should be `getFirstMediaPath`

Did you specify a `resized` media conversion on your model? Does your model implement `HasMediaConversions`?

**Comment by AlexVanderbist** [comment]
Hi! 

The easy "Laravel way" of doing this is via the [public disk](https://laravel.com/docs/5.5/filesystem#the-public-disk).

Retrieving media in your blade views then becomes as easy as `$user->getFirstMediaUrl('avatars', 'resized')` (like you said).

**Comment by freekmurze** [comment]
Ah indeed, `getFirstMediaPath` should be `getFirstMediaUrl`. `getFirstMediaPath` will return the full path on disk, `getFirstMediaUrl` only the relative part to the configured disk.

**Comment by faustuzas** [comment]
So I did 
`php artisan storage:link `
and now refering to image as 

> Auth::user()->getFirstMediaUrl('avatars', 'resized')`, but I get this error
> ...\ap_avatar\storage\app\public` is not part of public path ...\ap_avatar\public 

Filesystem: 
`        'media' => [
            'driver' => 'local',
            'root'   => storage_path('app\public'),
        ],`
