### ISSUE TITLE
Retrieve/Updating specific image from collection

### ISSUE THREAD

**Issue by ajitbohra** [spatie/laravel-medialibrary#87]
- Custom properties can be added to images/Files
- Is it possible to get specific file from collection
- Is it possible to update specific image

For e.g. 
- Having collection artworks  
- We can get the complete collection and loop though it to get all details
- Now if we need to update caption of any specific image how can we do that ?

**Comment by kickthemooon** [comment]
http://medialibrary.spatie.be/v3/basic-usage/retrieving-media/

maybe that can help you, hopefully.

**Comment by ajitbohra** [comment]
@kickthemooon thanks for the reply have checked the document but it returns collection. Need at access and update specific image have provided the e.g. above for more details

**Comment by freekmurze** [comment]
The collection holds Media objects which are regular Eloquent models. You can use those to update properties.

To get a specific media object you either have to loop a collection or manually query the media table.

**Comment by ajitbohra** [comment]
- How can we update image name for particular image in collection
- loop it would be array based how can we know which image unless we add custom property to filter
- manually query media table ?

**Comment by freekmurze** [comment]
1. 
```php
$media = Media::find($idOfMedia)->name = 'new name';
$media->save();
```
2. You could use the a custom property or id.
3. Just use regular eloquent methods on the Media class.

**Comment by ajitbohra** [comment]
@freekmurze thanks for the example it gives more clarity :)

Last doubt where can we find media Id ? i guess getMedia() will return the collection which will hold the id and other details ?

Sorry for being naive. Have just started playing around with the package :)

**Comment by freekmurze** [comment]
Np, the id i'm referring to is the regular id of the eloquent model.

```php
Media::first()->id;
```

**Comment by ajitbohra** [comment]
@freekmurze thanks for the prompt reply and solution. Will use the above details and reply back with few example based on our implementation so that others can ref.

**Comment by freekmurze** [comment]
Reopen this if you want to continue the conversation.

**Comment by danilogkir** [comment]
well, when i try the solution that @freekmurze gave i'm getitng:
```
SQLSTATE[HY093]: Invalid parameter number (SQL: select * from `media` where `media`.`id` in (6, App\Company, 5, icons, avatar, avatar.png, image/png, public, 20204, 6, 2018-09-09 03:35:27, 2018-09-09 03:35:27, ?, ?, ?))
