### ISSUE TITLE
$media->getURL() returns http://localhost/storage...

### ISSUE THREAD

**Issue by jozeflambrecht** [spatie/laravel-medialibrary#870]
I can upload my media files (the are stored in the `public/storage/..` folder without problems.
When I want to display my images using `<img src="{{ $media->getURL() }}">`, I get this error in my console:
`GET http://localhost/storage/1/conversions/thumb.jpg net::ERR_CONNECTION_REFUSED`

Both my app.php and .env files have the correct app URL `phplaravel-xxxx-xxxx.cloudwaysapps.com`

Helper functions as `public_path()`, `asset()` or `storage_path()` work fine on my server.

Laravel 5.5.x
Laravel-medialibrary: lastest version, default settings

**Comment by jozeflambrecht** [comment]
running `php artisan config:clear` fixed my issue

**Comment by crossRT** [comment]
Hi @jozeflambrecht ,
May I know how do you allow public to access images in your `storage` folder?
Write a new route to do the job?

**Comment by crossRT** [comment]
I found this,
https://stackoverflow.com/questions/30191330/laravel-5-how-to-access-image-uploaded-in-storage-within-view

Hope it's a proper way to do this?

**Comment by jozeflambrecht** [comment]
Sorry for the late answer, but it is the proper way to do this. (more info: https://laravel.com/docs/5.6/filesystem#configuration)
