### ISSUE TITLE
How to maintain default image orientatation?

### ISSUE THREAD

**Issue by faustuzas** [spatie/laravel-medialibrary#871]
When I'm uploading a picture which height is smaller than width, it gets rotated. How to main original orientation?

**Comment by freekmurze** [comment]
Code you share some code for us to look at?

**Comment by faustuzas** [comment]
Here it is: 
![screenshot_3](https://user-images.githubusercontent.com/33425982/33807347-068910ce-ddde-11e7-8199-156a9a2f0695.png)

**Comment by freekmurze** [comment]
Are you sure the problem is caused by the medialibrary? Does the problem occur when you store the file without the medialibrary? Could this problem be caused by the exif orientation flag in your image?

**Comment by HenkVanMaanen** [comment]
@faustuzas How did you solve the problem?

**Comment by faustuzas** [comment]
@HenkVanMaanen I didn't :(
