### ISSUE TITLE
getMediaConversionNames doesn't take collection into account

### ISSUE THREAD

**Issue by adiachenko** [spatie/laravel-medialibrary#872]
Sometimes, it is fairly useful to list conversions for particular image. 

For example, we have a RESTful API that returns versions available with each image. Clients can then proceed to decide which version to use based on either viewport size, context or whatever: 

```json
{
  "data": {
    "id": 6,
    "file_name": "example.jpg",
    "mime_type": "image/jpeg",
    "size": 222242,
    "href": "http://marketing-url.com",
    "versions": {
      "thumbnail": "https://example.com/storage/media/6/conversions/thumbnail.jpg",
      "large": "https://example.com/storage/media/6/conversions/large.jpg",
      "original": "https://example.com/storage/media/6/example.jpg"
    }
  }
}
```

Medialibrary already does have they way to do this natively (credits to @unstoppablecarl for bringing up the idea in #185). However, the *existing implementation does not take into account whether the conversion is actually performed on collection this media is stored in*.

We do have a working fix, but it relies on Medialibrary internals (rather than well-documented, public API) to work, which kinda stinks. 

Would you kindly welcome a PR for this? The fix should be fairly trivial as we only need to add `shouldBePerformedOn` check against the media this conversion is created for. Here is what we currently do in our code:

```
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\Resource;
use Spatie\MediaLibrary\Conversion\Conversion;
use Spatie\MediaLibrary\Conversion\ConversionCollection;

class MediaResource extends Resource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->resource->id,
            'file_name' => $this->resource->file_name,
            'mime_type' => $this->resource->mime_type,
            'size' => $this->resource->size,
            'href' => $this->resource->href,
            'versions' => $this->getVersions(),
        ];
    }

    /**
     * @return mixed
     */
    protected function getVersions()
    {
        $conversions = ConversionCollection::createForMedia($this->resource);

        $versions = $conversions->reduce(function ($carry, Conversion $conversion) {
            if ($conversion->shouldBePerformedOn($this->resource->collection_name)) {
                $name = $conversion->getName();
                $carry[$name] = $this->resource->getFullUrl($name);
            }

            return $carry;
        }, []);

        return array_merge($versions, [
            'original' => $this->resource->getFullUrl()
        ]);
    }
}

```

**Comment by adiachenko** [comment]
By the way, I've just read in [your tweet](https://twitter.com/freekmurze/status/939161592725409796) that responsive images support is coming in v7. I am not very familiar with the concept, but could you please comment whether it would be possible to utilize this functionality in RESTful API providing we take care of the markup on the client?

**Comment by freekmurze** [comment]
> Would you kindly welcome a PR for this?

 I suspect not many people need this feature, so I'm thinking the way you do it now, is the way to go.

> Does that mean there would be a better (or maybe easier) way to do it providing we take care of the markup on the client?

I'm not sure I understand your question correctly but the package will take care of the markup and you'll be able to easily customise that markup.
