### ISSUE TITLE
default_filesystem is not working?

### ISSUE THREAD

**Issue by liran-co** [spatie/laravel-medialibrary#873]
I have my default_filesystem set to s3 but for some reason the package is still uploading to public

**Comment by freekmurze** [comment]
Try running

php artisan config:clear

**Comment by liran-co** [comment]
I've already tried this several times. Any other possible causes?

**Comment by freekmurze** [comment]
Does running `config('medialibrary')` in an artisan tinker session return the correct values?

**Comment by liran-co** [comment]
Turns out I didn't change defaultFileSystem to default_filesystem when upgrading to v6 :/
