### ISSUE TITLE
SoftDelete on Media items

### ISSUE THREAD

**Issue by brendt** [spatie/laravel-medialibrary#876]
As discussed in https://github.com/spatie/laravel-medialibrary/pull/838 , soft deleting a media item itself will also remove the file. 

@Airidas10 was willing to write up some tests for this.

We'll be moving this conversation here instead of in the closed PR thread.

**Comment by brendt** [comment]
@Airidas10 You mentioned a failing test because the `deleted_at` column is missing; feel free to add it in the migration file. We will also provide an entry in UPGRADING.md for people who are already using the media library, they will have to manually add a conversion.

**Comment by Airidas10** [comment]
@brendt Added that column, created a new custom model in the test case and submitted the tests, which pass with the new changes in MediaObserver, but fail with the old ones.
Please take a look, https://github.com/spatie/laravel-medialibrary/pull/879

**Comment by brendt** [comment]
I'll also be closing this issue as Freek already answered in https://github.com/spatie/laravel-medialibrary/pull/879
