### ISSUE TITLE
Feature for v7: toMediaCollection third parameter for atomic dir structure

### ISSUE THREAD

**Issue by abkrim** [spatie/laravel-medialibrary#877]
On my opinion, there a a problem with intensive use, such database with 90 Million media for example.

Modern filesystems such ext4, btrfs, etc, has not problem (theorical) with large number or dirs on structure.

But if you working on real life with millions of dirs  on one dir, get problems with HFS on max, ext4, and other. 

System it's slowly .

I think is better atomic structure such:

/path/media/
     /name_of_collection/

Or beeter if possible split dirs using MD5 techniques.

For example in my case, I can split media onto collections (250)... 100 millions o media, they are now a maximum of 1 million of dirs...

It's only idea.

Best regards.

**Comment by freekmurze** [comment]
You can already use a custom `PathGenerator` to achieve this. Or you can use different disks.
