### ISSUE TITLE
Allow custom properties (when uploading to S3)

### ISSUE THREAD

**Issue by kallepa** [spatie/laravel-medialibrary#88]
Hi,

I would like to send custom properties when uploading files to S3. For example Content-Type. Something like this:

http://georgebohnisch.com/s3-set-contenttype-request-headers-laravel-filesystem-cloud-storage/

When uploading images the Content-Type was application/octet-stream and your were not able to view the uploaded images in browser.

**Comment by freekmurze** [comment]
This has been added to v3.7.2
