### ISSUE TITLE
GetUrl second in collection is fail

### ISSUE THREAD

**Issue by cona88** [spatie/laravel-medialibrary#880]
Hi,
I have the problem,
I am using For function to add image to collection, after that I get url url($post_trans->getMedia()[1]. It is failed
` foreach ($tags as $tag) {
            $imageLink = $tag->getAttribute('src');
            if (@getimagesize($imageLink)) {
                try {
                    $post_trans->addMediaFromUrl($imageLink)->toMediaCollection($imageLang);
                    $contents = str_replace($imageLink, url($post_trans->getMedia($imageLang)[$i]->getUrl()), $contents);
                    $i++;
                } catch (\Exception $ex) {
                    continue;
                }

            }
        }`

$contents = str_replace($imageLink, url($post_trans->getMedia($imageLang)[0]->getUrl()) -> It's OK
$contents = str_replace($imageLink, url($post_trans->getMedia($imageLang)[1]->getUrl()) -> It's failed
can somebody help me?
Thank in advance.

**Comment by freekmurze** [comment]
What does `$post_trans->getMedia()` return?
