### ISSUE TITLE
[v6][Support] Unable to Probe error when testing video upload using PHPUnit 

### ISSUE THREAD

**Issue by ludo237** [spatie/laravel-medialibrary#881]
## Server specifications

- PHP `v7.1.11`
- Node `v8.9.1`
- Laravel `v5.5.27`
- PHPUnit `v6.5.5`
- OS: `Debian GNU/Linux 8.9 (jessie)` as 🐳 Docker container
- Dependencies ✔️ all installed

## Preface

Hello everyone

I'm facing an issue when I try to write a feature test, HTTP test in *laravel language*,  for the `VideoController` that I've created.

## Problem

The current method involved in the `VideoControllerTest` is the following:

```php

    /** @test */
    public function it_is_possible_to_upload_a_new_video()
    {
        Storage::fake("tmp");
        
        $response = $this->post("users/{$this->user->uuid}/upload", [
            "video" => UploadedFile::fake()->create("myvideo.mp4"),
        ]);
        $response->assertStatus(Response::HTTP_OK)
            ->assertJsonStructure([
                "message",
                "view",
                "video",
            ]);
        
        $video = $response->getOriginalContent()["video"];
        Storage::disk("videos")->assertExists("{$video->uuid}/myvideo.mp4");
        Storage::disk("videos")->assertExists("{$video->uuid}/c");
        Storage::disk("videos")->assertExists("{$video->uuid}/c/thumbnail.jpg");
    }
```

Then I try to run this test I get the following stack trace:

```
1) Tests\Feature\VideoControllerTest::it_is_possible_to_upload_a_new_video
FFMpeg\Exception\RuntimeException: Unable to probe /app/storage/tmp/y6gZN4HBAPAVjNwcT5WBmKw8iaPd2o2e/XEjraASlaZqawcJb.mp4

/app/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php:263
/app/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php:206
/app/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php:92
/app/vendor/spatie/laravel-medialibrary/src/ImageGenerators/FileTypes/Video.php:22
/app/vendor/spatie/laravel-medialibrary/src/FileManipulator.php:82
/app/vendor/laravel/framework/src/Illuminate/Support/Collection.php:337
/app/vendor/spatie/laravel-medialibrary/src/FileManipulator.php:95
/app/vendor/spatie/laravel-medialibrary/src/Jobs/PerformConversions.php:32
```

The fun side of this is that either browser tests and manual upload from the browser itself are working great so it's a test related problem🤔 but what can it be? Maybe something related to the way Storage fake creates the file?

## Additional resources

This is the current PHPUnit environment configuration

```xml
  <php>
        <env name="APP_ENV" value="testing"/>
        <env name="APP_DEBUG" value="true"/>
        <env name="APP_URL" value="http://localhost/"/>
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
        <env name="CACHE_DRIVER" value="file"/>
        <env name="SESSION_DRIVER" value="file"/>
        <env name="SESSION_CONNECTION" value="sqlite"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="MAIL_DRIVER" value="log"/>
        <env name="MAIL_PRETEND" value="true"/>
    </php>
```

**Comment by freekmurze** [comment]
Are these paths correct? https://github.com/spatie/laravel-medialibrary/blob/ac8b8df1d2266260a20dc181b528050e09b1c9b4/config/medialibrary.php#L114-L115

**Comment by ludo237** [comment]
@freekmurze yes

**Comment by freekmurze** [comment]
I've tested it on my local installation and on a server and this is all working as expection.

Pretty sure the problem is caused by something specific to your server. 

If you find out what the problem is, please report back here.

**Comment by ludo237** [comment]
![explorer_2018-01-03_10-50-14](https://user-images.githubusercontent.com/921500/34515807-30ca6cc2-f074-11e7-9f72-93bec02874d6.png)

It seems that the problem is caused bye the fact that `UploadedFile::fake()->create("myvideo.mp4"),` creates a 0 byte file by default. The problem persists even if I try to specify the kilobytes 😖 am I missing something ❓

**Comment by ludo237** [comment]
@freekmurze can you please paste the test example that you've created?

**Comment by ludo237** [comment]
## Update

The above exception is not complete, this is the second message buried inside the stack trace

Just a reminder, `ffprobe` is in the correct path!

```
Caused by
Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffprobe failed to execute command '/usr/bin/ffprobe' '/app/storage/tmp/CjgVnZrr0KZ9EKQRjiIXDoUfoClJLF4s/eGnL6HhxKfazU7Sf.mp4' '-show_streams' '-print_format' 'json'

/app/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100
/app/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:72
/app/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php:209
/app/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php:137
/app/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php:261
/app/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php:206
/app/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php:92
/app/vendor/spatie/laravel-medialibrary/src/ImageGenerators/FileTypes/Video.php:22
```

**Comment by allaniftrue** [comment]
@ludo237 How did you manage to resolve this issue?

**Comment by ludo237** [comment]
Hi @allaniftrue we ditched this library long time ago when we shifted to a dedicated micro service to handle upload/conversion on Azure so I don't have any solution for this error.

**Comment by allaniftrue** [comment]
@ludo237 thanks for the quick response.
