### ISSUE TITLE
Chaining fit methods in Media Conversion

### ISSUE THREAD

**Issue by nathan6137** [spatie/laravel-medialibrary#882]
I have the following code in my model:

```
$this->addMediaConversion('big')
    ->fit('fill', 1000, 1000)
    ->nonQueued();
```

I have run into the same issue as  @dryror ( [here](https://github.com/spatie/image/issues/33) )

Is it possible to somehow chain the conversions to first do  `->fit('contain', 1000, 1000)` & than `->fit('fill', 1000, 1000)` on the same image? 

Or alternatively to pass some sort of flag to fill method to allow upsizing?

**Comment by freekmurze** [comment]
You can use the `apply` method to execute some image operations before executing the next ones.

You'll find more info on this in the docs of the image package: https://docs.spatie.be/image/v1/usage/advanced-manipulations

**Comment by nathan6137** [comment]
@freekmurze Thank you so much!!!
