### ISSUE TITLE
Updating already existing image for 

### ISSUE THREAD

**Issue by Quadriphobs1** [spatie/laravel-medialibrary#883]
I am a little bit confused, I can add the media but how do I update the already existing one, let's assume I have a post with id 1, and I have already set the featured image of the post, how can i update the featured image, if I wish to update the existing with the new image. I have read through the documentation I can seem to see any class to update existing image, or maybe I didn't notice but I do hope I can get to solve that here

**Comment by freekmurze** [comment]
There isn't a method to update a media. Just simply deleted the old media and add a new file to the medialibrary.

**Comment by Quadriphobs1** [comment]
I would have simply do that but in this case is till do want to keep the old image in the collection
