### ISSUE TITLE
Code cleaning & fixing style?

### ISSUE THREAD

**Issue by Omranic** [spatie/laravel-medialibrary#886]
I’m willing to send you PR with code style fixes & some cleaning around, plus adding missing docblocks, I like making code tidy and more beautiful. Is that’s something you’re willing to merge?

**Comment by freekmurze** [comment]
>  Is that’s something you’re willing to merge

That the depends on the things you want to clean up. Do you have some examples?

Before releasing my team will do some code reviews and I will go through it myself too to hopefully fix inconsistencies.

**Comment by Omranic** [comment]
Will wait until final release then, thanks.
