### ISSUE TITLE
Directory id being used for every file?

### ISSUE THREAD

**Issue by dambridge** [spatie/laravel-medialibrary#89]
This seems odd. For every file I attach to a given model, the package is putting it into a separate directory of its own, named for that file's id. So I've uploaded 5 files to a model, and now have 5 separate directories on S3 called 1,2,3,4,5, each with a file in it. Is this expected behaviour?

**Comment by freekmurze** [comment]
Yep, that's expected behaviour. Doing it like this will make sure that you can upload files with the same name. If you would use the image conversions you'd see that the conversions of an image also will get stored into that directory.

**Comment by dambridge** [comment]
Understood, thanks for the quick reply!

**Comment by freekmurze** [comment]
Np, have fun using the package!
