### ISSUE TITLE
How to get image width/heigh from conversion?

### ISSUE THREAD

**Issue by eminos** [spatie/laravel-medialibrary#893]
I'm using the javascript image viewer PhotoSwipe which needs the image width and height attributes to function properly. How do I get those from a conversion/file?
I have looked through both the manual and the code and couldn't find anything regarding this.

**Comment by freekmurze** [comment]
You can get the width and height of an image through our `image` package.

Here's an example from the tests of that package.

https://github.com/spatie/image/blob/d868b79d451046877c225af92a40114734eb4e5a/tests/ImageTest.php#L64-L70
