### ISSUE TITLE
Special characters and delete the file name space

### ISSUE THREAD

**Issue by widlturk** [spatie/laravel-medialibrary#9]
MediaLibraryRepository.php 

```php
private function createMediaForFile($file, $collectionName, $addAsTemporary)
    {
        $pathParts = pathinfo($file);
        $media = new Media();
        $media->name = $pathParts['filename'];
```

  $media->name = str_slug($pathParts['filename']);

It can be an insertion

**Comment by freekmurze** [comment]
This would break backwards compatibility. What problem are you trying to solve?

**Comment by widlturk** [comment]
sample 

ĞÜ Şİşiçğü filename.jpg => sisicgu-filename.jpg

I think more readable files have names
<img src ="ĞÜ Şİşiçğü filename.jpg"> 
instead
<img src="sisicgu-filename.jpg">

**Comment by freekmurze** [comment]
I can image that some people would like the original name of the file in the db. If you want to use a slug as a name, I think it's perfectly fine how you do it now.
