### ISSUE TITLE
Mass insert/upload without a form

### ISSUE THREAD

**Issue by jerauf** [spatie/laravel-medialibrary#904]
I use Intervention Image on my site and want to switch to medialibrary. I've got 1000+ images so it's not exactly feasible to manually upload each image through the web.

I've got a table with all of the file names, so those could be simply be inserted into the media table. But what about the file structure and the model_type, collection_name, mime_type and size? Is there a way for medialibrary to take care of that automatically?

**Comment by freekmurze** [comment]
You don't have to manually upload the images. Just write a script or command to import the images with code.

```php
foreach($images as $image) {
   $yourModel->addMedia($image)->toMediaCollection();
}
```

Check out the docs to learn all the methods the medialibrary provides:

https://docs.spatie.be/laravel-medialibrary/v7/introduction

**Comment by jerauf** [comment]
I did this. But something went wrong. So I deleted everything from the database and the copied files. It seems like it won't re-add the same image twice. How do I fix that?
