### ISSUE TITLE
default_filesystem does not take action.

### ISSUE THREAD

**Issue by shiroamada** [spatie/laravel-medialibrary#905]
Laravel: 5.5.32
Laravel-MediaLibrary: 6.6.7
PHP: 7.1.11
macOS: 10.12.6

I have created a new array inside `filesystem.php`

```
'media' => [
            'driver' => 'local',
            'root' => public_path('media'),
            'url' => env('APP_URL') . '/media',
        ],
```
and inside `medialibrary.php` I also changed to
```
'default_filesystem' => 'media',
```

But I still get 

Storagepath `/Users/shiro/Sites/laravel-media/storage/app/public` is not part of public path `/Users/shiro/Sites/laravel-media/public` (View: /Users/shiro/Sites/laravel-media/resources/views/show.blade.php)

What I can do is change
`filesystem.php`

```
'public' => [
            'driver' => 'local',
            //'root' => storage_path('app/public'), //comment the original
            'root' => public_path(),
            'visibility' => 'public',
        ],
```
then it only does not throw the error. Sometimes I missed that default_filesystem does not take any action?

As I look into vendor code
```
protected function getBaseMediaDirectoryUrl(): string
    {
        //$this->media->disk <- this one refer to 'public' instead of 'media' <- the media disk should take default_filesystem setting right?
        if ($diskUrl = $this->config->get("filesystems.disks.{$this->media->disk}.url")) {
            return str_replace(url('/'), '', $diskUrl);
        }


        if (! starts_with($this->getStoragePath(), public_path())) {
            throw UrlCannotBeDetermined::mediaNotPubliclyAvailable($this->getStoragePath(), public_path());
        }

        return $this->getBaseMediaDirectory();
    }
```

**Comment by freekmurze** [comment]
Run `php artisan cache:clear` and try again.

**Comment by shiroamada** [comment]
OK. I didn't have any config cache.
However, I manage to find out the issue.
It is due to in the view I have 2 media.
1st one I save in public media, and the 2nd one I changed it to media filesystem. Somehow. I remove all the data and do it again, there is no more error.

Sorry for the inconvenience.
