### ISSUE TITLE
Get collection of nearly uploaded Images

### ISSUE THREAD

**Issue by altercode** [spatie/laravel-medialibrary#907]
Hi,

Is there a possibility to get the list of nearly uploaded files to media collection?

`$category->addMultipleMediaFromRequest(["images"])
            ->each(function ($fileAdder) {
                $fileAdder->toMediaCollection("images");
            });`

`$category->getMedia('images')` 

will return all files from images collection.

**Comment by freekmurze** [comment]
That `>each(function ($fileAdder) { ` isn't possible, if it involves not too much code, I'd accept a PR that adds that (please include tests).

**Comment by hakimihamdan88** [comment]
@altercode any hacks?

**Comment by altercode** [comment]
Hi @hakimihamdan88 

I finnaly did something like this:


        $addedFiles = [];

        $filesAdded = $mediable->addMultipleMediaFromRequest(['file']);

        foreach ($filesAdded as $fa) {
            $addedFiles[] = $fa->toMediaCollection('images');
        }

        return json_encode($addedFiles);
