### ISSUE TITLE
Responding with media: URLGenerator doesn't exist

### ISSUE THREAD

**Issue by jozeflambrecht** [spatie/laravel-medialibrary#908]
When I use this code:

```
use Spatie\MediaLibrary\Media;

class DownloadMediaController
{
   public function show(Media $mediaItem)
   {
      return $mediaItem;
   }
}
```

I get the following error:

> Class Spatie\MediaLibrary\UrlGenerator\UrlGenerator doesn't exist

Default filesystem: 'public'
```
    'disks' => [

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'visibility' => 'public',
        ],
```

Using Spark 5.x and Laravel 5.5.x and `public/storage` directory is linked to my `storage/app/public` using a symbolic link.

**Comment by eduduardo** [comment]
The "Class Spatie\MediaLibrary\UrlGenerator\UrlGenerator" is an interface and it cannot be used as the generator itself.

Maybe you can set the config file to:
```
'custom_url_generator_class' => \Spatie\MediaLibrary\UrlGenerator\LocalUrlGenerator::class,
````

**Comment by josegus** [comment]
It works for me, I'm using a custom media model and adding the 'custom_url_generator_class' solve it
