### ISSUE TITLE
migration publishing does not work

### ISSUE THREAD

**Issue by alexglue** [spatie/laravel-medialibrary#91]
```
php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="migrations"
```
returns 
```
Nothing to publish for tag [migrations].
```
but config publishing works properly.

**Comment by freekmurze** [comment]
Did you install the service provider before trying to publish the migration?

Also: the migration only gets published if there is not already a class named `CreateMediaTable`.

**Comment by alexglue** [comment]
@freekmurze your're right! my fault, an old migration with the same name was already installed earlier; thanx!
