### ISSUE TITLE
Feature request: filter on getFirstMediaURL()

### ISSUE THREAD

**Issue by jozeflambrecht** [spatie/laravel-medialibrary#911]
I am loving this package, thanks people from Spatie!

What would be the best/cleanest way to retrieve the URL of the featured image (image with custom property ['featured' => 1]?

I think it would be nice to have a filter for the getFirstMediaURL() function.

This is what I tried to do: `$post->getFirstMediaURL('images', ['featured' => 1])` with _featured_ a custom property. The error I get is:

`Argument 2 passed to App\School::getFirstMediaUrl() must be of the type string, array given`

I tried the same with `$post->getMedia('images', ['featured' => 1])->first()->getURL('thumb')`, but this does not work neither.

Thanks!

**Comment by freekmurze** [comment]
I'd accept a fully tested non breaking pr that add support for passing a callable to `App\School::getFirstMediaUrl()`. If a callable is passed, the first media for which the callable returns `true` will be returned.

**Comment by DivineOmega** [comment]
Hope this does the trick. :)

**Comment by freekmurze** [comment]
We'll handle this further in #912
