### ISSUE TITLE
[Question] Tracking disk usage per user

### ISSUE THREAD

**Issue by elamotte** [spatie/laravel-medialibrary#915]
Hi,
I want to put a limit to disk-usage per user (dependings of their plan).

I don't want to recalculate the disk used by the user every times (ex: retreiving all his posts with all associated media to calculate total filessizes).
So I want to add a collumn in my user model that I will use as an accumulator.

I want to increment this value at each new file added and decrease it at each file deleted.

I saw in the docs that you have **Consuming events** which looks to suit my needs at least in part:
I have **MediaHasBeenAdded** but I don't have the same for when a MediaHasBeenDeleted. There is only for **CollectionHasBeenCleared**, how can I track a single file delete?

Is there a better approach to do this?

Thanks!

**Comment by freekmurze** [comment]
If you use a [model observers](https://laravel.com/docs/5.5/eloquent#events) on the `Media` class you'll be able to listen for any event your heart desires.

**Comment by elamotte** [comment]
Perfect. Thanks for the tip!
