### ISSUE TITLE
Getting last inserted ID

### ISSUE THREAD

**Issue by jerauf** [spatie/laravel-medialibrary#916]
I want to reference the ID of the last inserted media. How would I do that?

**Comment by freekmurze** [comment]
```php
Media::latest()->first()->id;
```

**Comment by jerauf** [comment]
Well, yes. But is there a way without needing to do another query?

**Comment by freekmurze** [comment]
You'll always need to do at least one query to get this info.

**Comment by ludo237** [comment]
@jerauf you should eager loading the media ids of a related model

`Model::with("mediaIds")->first()`

Where `mediaIds` is a custom relationship inside `Model`

```
public function mediaIds()
{
    return $this->media()->lists("id");
}
```
