### ISSUE TITLE
how to use both S3 and local storage (S3 as a mirror)

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-medialibrary#917]
I'm currently using local storage for hosting a few thousand images. I would like to have every image mirrored on S3 and ideally I would like for this to be automatic.

In essence I would like laravel-medialibrary to write to both local storage and s3, but only read from one

Is there a way to configure this package to do this without running additional scripts or crons to keep the two disks in sync ?

**Comment by freekmurze** [comment]
No, this package will only store a given media on one disk. 

> In essence I would like laravel-medialibrary to write to both local storage and s3, but only read from one

You'll need to take care of this yourself.
