### ISSUE TITLE
Generate URLs via Storage::disk()->url() unless overriden

### ISSUE THREAD

**Issue by leewillis77** [spatie/laravel-medialibrary#918]
Currently the package has built in URL generators for local filesystems, and for S3. Anything other storage disk requires a Custom URL Generator to be written (E.g. https://github.com/leewillis77/medialibrary-gcs-url-generator). This seems overkill since the URL can be generated via `Storage::disk()->url()` (See https://github.com/leewillis77/medialibrary-gcs-url-generator/blob/master/src/MedialibraryGcsUrlGenerator.php#L17 for an example)

Is there a reason that the package doesn't implement the following logic:

- Check for custom_url_generator set in config and use that if valid
- Generate a slug based on storage type, e.g. gcs-url-generator and try and resolve that through the  service container, using that if valid
- Generate a class name based on storage type and look for an in-package class to handle it (as per current logic)
- Fallback to a generator that just uses `Storage::disk()->url()`

That would seem to be as flexible (if not more) than the [current solution](https://github.com/spatie/laravel-medialibrary/blob/master/src/UrlGenerator/UrlGeneratorFactory.php#L14) while also working out-of-the-box in many more cases.

**Comment by freekmurze** [comment]
Thanks for the good suggestions, I'll try to improve on this in `v7`. If you already have a good view on how this could be implement easily, I'd highly appreciate a PR to the `v7` branch. If you do, please make sure all tests pass.

**Comment by freekmurze** [comment]
A simplified way of generating URLs have been implemented on the `v8` branch.

https://github.com/spatie/laravel-medialibrary/blob/0fa2f72a42a0fa524446842a72a544568b967d76/src/UrlGenerator/DefaultUrlGenerator.php#L8

**Comment by leewillis77** [comment]
Thanks. I think that meets my needs.
