### ISSUE TITLE
How could i change original non-safety filename while addMedia() ?

### ISSUE THREAD

**Issue by alexglue** [spatie/laravel-medialibrary#92]
The file will be stored with original file name. It's critically bad practice.
How could i change it to md5() etc? 
Could you implement this or tell me how could i do this if it's possible?

```
$user->addMedia($request->file('image'))->toCollection('images');
```

**Comment by freekmurze** [comment]
This can be done with [`usingFileName`](https://github.com/spatie/laravel-medialibrary/blob/3.7.1/src/FileAdder/FileAdder.php#L162-L172).

```php
$user->addMedia($request->file('image'))->usingFileName($yourCustomFileName)->toCollection('images');
```

**Comment by alexglue** [comment]
@freekmurze so, in case of user's avatar upload i should do this:
```
			$filename = md5($request->file('image')->getClientOriginalName()) . '.' . $request->file('image')->getClientOriginalExtension();
			$user->clearMediaCollection('avatar');
			$user->addMedia($request->file('image'))->setFileName($filename)->toCollection('avatar');
```

This looks strange ) I've some feature request for you:
Could you just append callback/event or user-defined function to rename files by default?
Also, it will be nice to set "single-file" mode in model media settings, or add replaceMedia() or something like that.

**Comment by freekmurze** [comment]
These seem like things that are specific to your application. You could make it readable by adding some helper methods to your own application.

**Comment by nguyentranchung** [comment]
how can I change file name with setFileName() and keep extension file?

**Comment by ctf0** [comment]
@nguyentranchung after some work here is the work around
1. create new trait that inherit the original trait
2. in the new trait add
```php
public function addHashedMedia($file)
    {
        $name = Str::uuid();

        return $this->addMedia($file)
            ->setFileName($name)
            ->usingFileName($name . '.' . pathinfo($file, PATHINFO_EXTENSION));
    }
```
3. use the new method instead of `addMedia`

now you have the best of 2 worlds, the original which save he file as it was uploaded, and another to save it with hash name.

**Comment by dakira** [comment]
@ctf0 Actually Laravel has this built in. You can get a hashed version off the file itself. I always want the files saved hashed (keeping the original name), so I use this trait:

```php
<?php

namespace App;

use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

trait HasHashedMediaTrait
{
    use HasMediaTrait {
        HasMediaTrait::addMedia as parentAddMedia;
    }

    public function addMedia($file)
    {
        return $this->parentAddMedia($file)
            ->usingFileName($file->hashName());
    }
}

```

Now I just use HasHashedMediaTrait instead of the original trait.

**Comment by ctf0** [comment]
@dakira hashing the file based on content means the file have to be loaded into memory first, while using something generic like uuid is faster and does the same job

**Comment by dakira** [comment]
@ctf0 `hashName` does no hashing of the file, it just generates a name and adds the extension.

```php
public function hashName($path = null)
{
    if ($path) {
        $path = rtrim($path, '/').'/';
    }

    $hash = $this->hashName ?: $this->hashName = Str::random(40);

    if ($extension = $this->guessExtension()) {
        $extension = '.'.$extension;
    }

    return $path.$hash.$extension;
}
```

**Comment by ctf0** [comment]
oh, i must have confused it with something else, thanx for the headsup

**Comment by janisii** [comment]
For those who need safe filename for `<input type="file" name="uploads[]" multiple="multiple" />`, I used this approach.

```
<?php
        //...
        $uploads = request()->allFiles()['uploads'];

        $model->addMultipleMediaFromRequest(['uploads'])->each(
            function ($fileAdder, $idx) use ($uploads) {
                $fileAdder->preservingOriginal()
                    ->usingFileName($uploads[$idx]->hashName())
                    ->toMediaCollection();
                $idx++;
            }
        );
        //...
```

**Comment by burzum** [comment]
Is there any way to change this in a single place and not having to go through all the add* methods?

What I would like to get done is that the filename becomes <hash>.<extension> and the original filename is preserved in the database. By the way, why is the "name" field missing the file extension?

**Comment by abdelrahman-varit** [comment]
> ```
> 
>     public function addMedia($file)
>     {
>         return $this->parentAddMedia($file)
>             ->usingFileName($file->hashName());
>     }
> ```

when I used this:

```
trait Mediable
{
    use InteractsWithMedia {
        InteractsWithMedia::addMedia as parentAddMedia;
    }

    public function addMedia($file)
    {
        return $this->parentAddMedia($file)
            ->usingFileName($file->hashName());
    }
}
```

I get 

> Whoops\Run::handleError("Declaration of App\Models\Category::addMedia($file) must be compatible with Spatie\MediaLibrary\Has
Media::addMedia($file): Spatie\MediaLibrary\MediaCollections\FileAdder",

**Comment by dakira** [comment]
@abdelrahman-varit It's what the error message says. The method declaration must be the same as the original (i.e. same parameters and return type). In other words, the method signatures must match.

**Comment by mibu31** [comment]
@abdelrahman-varit `public function addMedia($file): FileAdder`

**Comment by FatihAraz** [comment]
what about temporary uploads in the pro version?
I am using S3 to save my files and temporary uploads and i need a way before the file is uploaded to s3.

**Comment by laratutodotcom** [comment]
How to get file extension from path in Laravel 9? https://laratuto.com/how-to-get-file-extension-from-path-in-laravel/**

you use Laravel Function  right ?/

```
$_EXTENSTION = $request->file->extension(); 

dd($_EXTENSTION);
```
