### ISSUE TITLE
using a dynamically registered disk

### ISSUE THREAD

**Issue by clarkwinkelmann** [spatie/laravel-medialibrary#920]
Hello,

I'm trying to use this package with https://github.com/hyn/multi-tenant and as such I'd like to use the `tenant` disk, which is created dynamically in a service provider and has no key in configuration files (It's registered directly via `Illuminate\Filesystem\FilesystemManager::set` in https://github.com/hyn/multi-tenant/blob/4b28eb4994a91d1612166a3fe0d42ba1f58009ce/src/Listeners/Filesystem/ActivatesDisk.php#L60)

Medialibrary complains that this disk doesn't exist, but this is because it's checking directly against the configuration in

https://github.com/spatie/laravel-medialibrary/blob/0dda07ad3ed6eebd945f846f7fc7c24fc1766cbd/src/FileAdder/FileAdder.php#L303

Using Storage::disk('tenancy') does return the disk.

I was thinking about submitting a PR but I discovered there's not really any way to query the list of existing disks without actually resolving it, which I guess you don't want to do inside `FileAdder::determineDiskName`...

I think I can hack my way around this by creating a dummy filesystem in the configuration file with the `tenant` name, but still, it would be nice for this package to ask the filesystem manager about the existing disks.

I also noticed Laravel contracts don't include any way to add or query disks on the Factory so I guess it's hard to justify adding this here...

**Comment by freekmurze** [comment]
I'm not sure how to solve this, but maybe it's an option to dynamically set a path and an url generator somewhere after you've determined which tenant your serving?

**Comment by clarkwinkelmann** [comment]
@freekmurze yes I've registered a custom PathGenerator and UrlGenerator, no problem on that side, extensibility is great !

I've found that the following bare minimum is required in `config/filesystem.php` in order to use medialibrary a virtual disk:

```php
    'disks' => [
        // The tenancy disk is created dynamically by hyn/multi-tenant but spatie/laravel-medialibrary
        // requires any disk to be declared in the config file. This dummy entry fixes the issue.
        // Used in Spatie\MediaLibrary\FileAdder\FileAdder::determineDiskName
        // @see https://github.com/spatie/laravel-medialibrary/issues/920
        'tenant' => [
            // Used in Spatie\MediaLibrary\Media::getDiskDriverName
            'driver' => 'local',
        ],
    ],
```

I guess there's not really any other solution than adding this dummy entry. Given hyn/multi-tenant registers its `tenant` disk very early I didn't found any case where Laravel would try to load it from that dummy configuration instead.

**Comment by freekmurze** [comment]
👍
