### ISSUE TITLE
Broken video image generator.

### ISSUE THREAD

**Issue by tvercruysse** [spatie/laravel-medialibrary#921]
Since the release of laravel 5.6 which depends on symfony ~4.0 the video image generator is broken.
The crulpit seems to be alchemy/binary-driver on which php-ffmpeg depends.

Due to the slow release cycle of said package (last update 01/17) there are a couple of solutions.

Possible solutions: 
 - Find alternative for php-fmpeg
 - Override the binarydriver package with a [fork](https://github.com/PHP-FFMpeg/BinaryDriver).
 - Wait until PR gets merged ( which could be a while )

**Comment by freekmurze** [comment]
I'm hoping the PR will get merged soon.
