### ISSUE TITLE
Not working in multi tenant DB

### ISSUE THREAD

**Issue by ajaybairagi** [spatie/laravel-medialibrary#924]
Hello,

I use multi tenant DB, below code I use . I want to pass current DB connection.

$emailAuditMedia = $emailAudit->where('id', '=', $id)->first();
$emailAuditMedia->addMedia($file)->toMediaCollection();

How to pass current DB connection.

**Comment by freekmurze** [comment]
In the docs you can learn how to use your own model: https://docs.spatie.be/laravel-medialibrary/v6/advanced-usage/using-your-own-model

In your custom model you can set the `connection` property to the name of the connection this model should use

```
  protected $connection = 'mysql2';
```

**Comment by ajaybairagi** [comment]
Thanks to your reply
It is working with extends BaseMedia and put static connection  but I want to pass dynamic database connection 
Have any option to pass  Tenant database name in
$emailAuditMedia->addMedia($file)->toMediaCollection();
or have other code
or have any option to pass variable in  __construct($connection)

**Comment by ajaybairagi** [comment]
I have extend Media Modal and solved problem

namespace App\Models;
use Spatie\MediaLibrary\Media as BaseMedia;

class CustomMedia extends BaseMedia {
    public $connection;
    function __construct($connection = null) {
        if (!empty($connection)) {
            $this->connection = $connection;
        } else {
            $conn = app('db')->getConnections();
            reset($conn);
            $this->connection = key($conn);
        }
    }
    protected $table = 'media';
}

**Comment by elreco** [comment]
Hello @ajaybairagi 

That doesn't work anymore I guess
