### ISSUE TITLE
pathinfo failed to set valid Media.name with UTF-8 chars

### ISSUE THREAD

**Issue by alexglue** [spatie/laravel-medialibrary#93]
vendor/spatie/laravel-medialibrary/src/FileAdder/FileAdder.php:115
```
$this->mediaName = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
```

so, mediaName is a source for the media.name column, but it failed with russian filename etc (and other utf-8), and loose original file name. "Заранее назвал Мой супер крутой файл_2.png" turns into " назвал Мой супер крутой файл_2.png" etc.

The solution is to use mb_pathinfo variant (non-native) or just get $file->getClientOriginalName() for this field. Why do you get pathinfo only in this case?

**Comment by freekmurze** [comment]
I did not know that pathinfo did not work with special characters. I'll fix this soon.
