### ISSUE TITLE
Why am I forced to install Imagick?

### ISSUE THREAD

**Issue by bbashy** [spatie/laravel-medialibrary#935]
```
- spatie/pdf-to-image 1.6.0 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
- spatie/laravel-medialibrary 6.6.9 requires spatie/pdf-to-image ^1.2 -> satisfiable by spatie/pdf-to-image[1.6.0].
```

README says "For the creation of thumbnails of svg's or pdf's you should also install Imagick." but I'm not doing any of that.

**Comment by freekmurze** [comment]
Thanks for reporting this.

`spatie/pdf-to-image` should go in the suggested packages in `composer.json` to solve this. Unfortunately doing this is a breaking change. I'll do this in the upcoming `v7` of the package.

Meanwhile you can install the package by adding it to `composer.json` and then running 

```
composer install --ignore-platform-reqs
```

Please let me know if you have any better ideas on how to solve this without breaking BC.

**Comment by cviebrock** [comment]
I think you forgot to do this for v7.  `spatie/pdf-to-image` is still listed as a requirement, not a suggestion. ☹️

**Comment by freekmurze** [comment]
Damn, forgot about this one. Tempted to move it to the suggestions right now, but I'm afraid this breaking change would cause a lot of havoc in production systems of current users of v7.

**Comment by cviebrock** [comment]
Maybe re-open this so you don't forget for v8? ;)

**Comment by freekmurze** [comment]
I promise I'll take a look at this in v8. 🙏

**Comment by freekmurze** [comment]
The dependency has been moved to the suggestions on the `v8` branch 👍 

https://github.com/spatie/laravel-medialibrary/commit/eb5091da6cb239a2f0adb10310a1e9471664e304
