### ISSUE TITLE
Animated GIF Error

### ISSUE THREAD

**Issue by nessimabadi** [spatie/laravel-medialibrary#948]
Hey @freekmurze,

When uploading an animated GIF, the conversions makes it a static one.
I've tried adding keepOriginalImageFormat() but still got the same problem.

I don't know if I have an error or I'm missing something.

Code
```PHP
/**
*
* @param Media|null $media
*/
public function registerMediaConversions(Media $media = null)
{
    $this->addMediaConversion('optimized')->optimize()->keepOriginalImageFormat()->apply();
}
```

**Comment by brendt** [comment]
Did a lot of digging into this issue; turns out that Intervention (the image library used by `thephpleague/glide`) doesn't support animated GIFs: https://github.com/Intervention/image/issues/176

Reading from the comments it seems that there support will come in V3, but there no release date set. 

Long story short: you're able to save animated GIFs in the media library, but you're not able to perform optimisations on them.

**Comment by nessimabadi** [comment]
Thanks for the help.
Now lets wait for intervention/image V3

**Comment by brendt** [comment]
I'm going to close this issue for now, but we'll come back to it when there's a V3 release of intervention.

**Comment by freekmurze** [comment]
v3 still hasn't dropped...

**Comment by gasner** [comment]
Is there anything new about this issue?
still not working :(

**Comment by bdahlinger** [comment]
still not dropped :/

**Comment by AlejandroAkbal** [comment]
Intervention/Image V3 is in alpha state, looking forward to this 😢

**Comment by msonowal** [comment]
> Did a lot of digging into this issue; turns out that Intervention (the image library used by `thephpleague/glide`) doesn't support animated GIFs: [Intervention/image#176](https://github.com/Intervention/image/issues/176)
> 
> Reading from the comments it seems that there support will come in V3, but there no release date set.
> 
> Long story short: you're able to save animated GIFs in the media library, but you're not able to perform optimisations on them. You could eg. add a check on the extension before applying conversions.
> 
> ```
> public function registerMediaConversions(Media $media = null)
> {
>     if ($media && $media->getExtensionAttribute() === Manipulations::FORMAT_GIF) {
>         return;
>     }
>     
>     $this
>         ->addMediaConversion('optimized')
>         ->optimize()
>         ->keepOriginalImageFormat()
>         ->apply();
> }
> ```
> 
> You would have to manually check in eg. view files whether the conversion exists, or you'll get a `Spatie\MediaLibrary\Exceptions\InvalidConversion` error.

the new updated syntax for latest version would be

```php
 public function registerMediaConversions(Media $media = null)
 {
     if ($media && $media->extension === Manipulations::FORMAT_GIF) {
         return;
     }
     
     $this
         ->addMediaConversion('optimized')
         ->optimize()
         ->keepOriginalImageFormat()
         ->apply();
 }
 ```

**Comment by Ramdeep-zentral** [comment]
Quick Solution for this issue:-

In Views, we can add @if condition.

    $gifMIMETypes = ['image/gif'];
    $imageMIMETypes = ['image/bmp', 'image/jpeg', 'image/png', 'image/jpg'];

   @foreach ($project->getMedia('hero_image') as $image)
    @if (in_array($image->mime_type, $imageMIMETypes))
    {{ $image('preview') }}
    @endif
    @if (in_array($image->mime_type, $gifMIMETypes))
    <img src="{{ asset($image->getUrl()) }}" alt="">
    @endif
    @endforeach

I hope this will help.

**Comment by paulrrogers** [comment]
Intervention Image v3 is out, v2 has reached the end-of-life; and League Glide now uses v3 too. Please reopen.
