### ISSUE TITLE
Getting Issue related to permission in  Spatie\MediaLibrary\Jobs\PerformConversions 

### ISSUE THREAD

**Issue by avanisolanki** [spatie/laravel-medialibrary#952]
Hello, I am using laravel media library to manage media upload and conversation. When I upload any image It's getting loaded as the queue to convert media is getting failed with below error.

ErrorException: mkdir(): Permission denied in /var/www/html/xevo/vendor/league/flysystem/src/Adapter/Local.php:367Stack trace:#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mkdir(): Permis...', '/var/www/html/z...', 367, Array)#1 /var/www/html/xevo/vendor/league/flysystem/src/Adapter/Local.php(367): mkdir('/var/www/html/z...', 493, true)#2 /var/www/html/xevo/vendor/league/flysystem/src/Filesystem.php(262): League\Flysystem\Adapter\Local->createDir('13/conversions', Object(League\Flysystem\Config))#3 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(593): League\Flysystem\Filesystem->createDir('13/conversions')#4 /var/www/html/xevo/vendor/spatie/laravel-medialibrary/src/Filesystem/DefaultFilesystem.php(152): Illuminate\Filesystem\FilesystemAdapter->makeDirectory('13/conversions/')#5 /var/www/html/xevo/vendor/spatie/laravel-medialibrary/src/Filesystem/DefaultFilesystem.php(42): Spatie\MediaLibrary\Filesystem\DefaultFilesystem->getMediaDirectory(Object(Spatie\MediaLibrary\Media), true)#6 /var/www/html/xevo/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(92): Spatie\MediaLibrary\Filesystem\DefaultFilesystem->copyToMediaLibrary('/var/www/html/z...', Object(Spatie\MediaLibrary\Media), true)#7 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Support/Collection.php(337): Spatie\MediaLibrary\FileManipulator->Spatie\MediaLibrary{closure}(Object(Spatie\MediaLibrary\Conversion\Conversion), 0)#8 /var/www/html/xevo/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(95): Illuminate\Support\Collection->each(Object(Closure))#9 /var/www/html/xevo/vendor/spatie/laravel-medialibrary/src/Jobs/PerformConversions.php(32): Spatie\MediaLibrary\FileManipulator->performConversions(Object(Spatie\MediaLibrary\Conversion\ConversionCollection), Object(Spatie\MediaLibrary\Media))#10 [internal function]: Spatie\MediaLibrary\Jobs\PerformConversions->handle()#11 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)#12 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container{closure}()#13 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))#14 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)#15 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)#16 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus{closure}(Object(Spatie\MediaLibrary\Jobs\PerformConversions))#17 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Spatie\MediaLibrary\Jobs\PerformConversions))#18 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))#19 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Spatie\MediaLibrary\Jobs\PerformConversions), false)#20 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)#21 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()#22 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))#23 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))#24 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'media', Object(Illuminate\Queue\WorkerOptions))#25 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'media')#26 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()#27 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)#28 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container{closure}()#29 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))#30 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)#31 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)#32 /var/www/html/xevo/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))#33 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))#34 /var/www/html/xevo/vendor/symfony/console/Application.php(938): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#35 /var/www/html/xevo/vendor/symfony/console/Application.php(240): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#36 /var/www/html/xevo/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#37 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#38 /var/www/html/xevo/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#39 /var/www/html/xevo/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#40 {main}

Moreover the same is working in local environment but not working in staging environment.
In staging it's getting failed
![selection_002](https://user-images.githubusercontent.com/37375055/37460434-3af0f88a-2871-11e8-9315-54389fec5c16.png)

Can anyone please help?

**Comment by freekmurze** [comment]
Probably your issue is not related to this package, but to permission blues on your staging env.

**Comment by avanisolanki** [comment]
I followed the steps written here http://laravel-recipes.com/recipes/25/creating-an-apache-virtualhost to run laravel app using virtual host.

I changed user in envvars file with my system user. So It is working properly!

**Comment by bump909** [comment]
add this to 'disks' array in config/filesystems.php:

'media' => [
            'driver' => 'local',
            'root' => public_path('media'),
            'url' => env('APP_URL').'/media',
            'permissions' => [
                'file' => [
                    'public' => 0774,
                    'private' => 0600,
                ],
                'dir' => [
                    'public' => 0775,
                    'private' => 0700,
                ],
            ],
        ],
