### ISSUE TITLE
Adding url in filesystems, omits the app_url

### ISSUE THREAD

**Issue by JonasLod** [spatie/laravel-medialibrary#954]
So weird one. Normally I would add my env(APP_URL) in the transformer just before the $media->getUrl(). I recently found that you can add this at the filesystems config. Like this:

```
   'media' => [
            'driver' => 'local',
            'root'   => public_path('/media'),
            'url' => env('APP_URL') ."/media", //THIS
        ],
```
Locally everything was working fine but when I pushed to server, it would omit everything before /media. So I would get: "/media/1/..." instead of "https://....com/media/1/..".  I am working with a https url.
Things I tested: 
- Change app_url to http version => works
- Change to env('APP_URL', "test") => doesn't do a thing
- Add something to the APP_URL like '....com/banana' => this actually does: "banana/media/..." but does not add the url itself, so it clearly gets cut somewhere
- Put strtoupper around env('APP_URL') => This makes it work, no kidding!
- Try strtolower => nope, it gets cut.

Is this a setting I am overlooking somewhere? Currently I have it working with strtoupper as http is not done in our environment. I never had this problem before when I would add the path through the transformer so I'm guessing it has something to do with this package or the filesystem in general.

**Comment by freekmurze** [comment]
Could it be the case that you just have to run `php artisan config:clear` on your server?

**Comment by JonasLod** [comment]
Nope that was not the case. Isn't an explanation for the partly cut either..

**Comment by noahjahn** [comment]
I'm having the same issue that @jonlod described.

The following works:  
```
        'media' => [
            'driver' => 'local',
            'root'   => public_path().'/uploads',
            'url'    => strtoupper(env('APP_URL')).'/uploads',
        ],
```

But the following doesn't:  
```
        'media' => [
            'driver' => 'local',
            'root'   => public_path().'/uploads',
            'url'    => env('APP_URL').'/uploads',
        ],
```
Here's the error:  
`GET https://uploads/170/aaron-vroma.jpg net::ERR_NAME_NOT_RESOLVED`

**Comment by jonlod** [comment]
I haven't found a solution either so I just stopped using that part of the config. I have been using this static helper function to get the media urls now. Also easier if you're working with multiple disks.
`   public static function retrieveMediaUrl(Media $media){
        if($media->disk == "s3")
            return $media->getFullUrl();
        else
            return env('APP_URL') . $media->getUrl();
    }`
