### ISSUE TITLE
unable to install on latest laravel?

### ISSUE THREAD

**Issue by snipiba** [spatie/laravel-medialibrary#955]
Problem 1
    - Conclusion: remove laravel/framework v5.6.12
    - Conclusion: don't install illuminate/pipeline v5.5.39
    - Conclusion: don't install illuminate/pipeline v5.5.37
    - Conclusion: don't install illuminate/pipeline v5.5.36
    - Conclusion: don't install illuminate/pipeline v5.5.35
    - Conclusion: don't install illuminate/pipeline v5.5.34
    - Conclusion: don't install illuminate/pipeline v5.5.33
    - Conclusion: don't install illuminate/pipeline v5.5.28
    - Conclusion: don't install illuminate/pipeline v5.5.17
    - Conclusion: don't install illuminate/pipeline v5.5.16
    - Installation request for spatie/laravel-medialibrary 6.0.0 -> satisfiable by spatie/laravel-medialibrary[6.0.0].
    - Conclusion: don't install illuminate/pipeline v5.5.2
    - don't install illuminate/pipeline 5.5.x-dev|don't install laravel/framework v5.6.12
    - don't install illuminate/pipeline 5.5.x-dev|don't install laravel/framework v5.6.12
    - spatie/laravel-medialibrary 6.0.0 requires illuminate/pipeline ~5.5.0 -> satisfiable by illuminate/pipeline[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - Conclusion: don't install illuminate/pipeline v5.5.0
    - Installation request for laravel/framework (locked at v5.6.12, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.12].

**Comment by freekmurze** [comment]
The 6.0.0 is not compatible with Laravel 5.6.  The last point release is. Please install the package by running `php artisan require spatie/laravel-medialibrary`. Make sure the package is not in your `composer.json` before running this command.

**Comment by snipiba** [comment]
are u sure with php artisan require command? not composer require? ;)
