### ISSUE TITLE
v.7 Conversion FileName Being Appended to Path

### ISSUE THREAD

**Issue by s1rc** [spatie/laravel-medialibrary#960]
Upgraded from v.6 to v.7 for Laravel 5.6 and noticed that the conversion convention is not being followed.

https://docs.spatie.be/laravel-medialibrary/v7/advanced-usage/using-a-custom-directory-structure shows: 

```
media
---
1
------ file.jpg
------ conversions
--------- small.jpg
--------- medium.jpg
--------- big.jpg
---
```

Using the default PathGenerator, I see errors looking for the conversion at:
`81/conversions/filename-large.jpg`

Using my custom PathGenerator, I see errors looking for the conversion at:
`Team/80/conversions/filename-large.jpg`

So unfortunately none of these files exists, since they are just named:
`Team/80/conversions/large.jpg`

**Comment by s1rc** [comment]
Edit: I read UPGRADING.md and see this is normal behaviour.

Is there any way in my custom path generator to remove the filename from the conversion path?

I have about 12,000 media objects with are video and use AWS Elastic Transcoder to generated multiple file sizes. I can change newly added conversions to the new path format, however the existing files it'd be nice to not have to go through and rename.

**Comment by freekmurze** [comment]
Our intern is currently working at a tool to accomplish this. Keep on eye on this repo: https://github.com/spatie/laravel-medialibrary-v6-to-v7-filesystem-upgrade
