### ISSUE TITLE
Publishing views with Artisan command does not work

### ISSUE THREAD

**Issue by clarkewing** [spatie/laravel-medialibrary#964]
Nothing happens when issuing the `php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="views"` command.

After looking through the source code, this seems to be due to the views not being listed for publishing in the Service Provider.

Currently just copying and pasting the views as a workaround.

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. I've fixed this in the latest version.
