### ISSUE TITLE
Will Laravel 5.5 LTS continue to be supported?

### ISSUE THREAD

**Issue by mcni** [spatie/laravel-medialibrary#966]
It appears from the composer.json that Laravel 5.5 is still currently supported, but the documentation Indicates that it is for 5.6 and above. I'm just curious if you will continue to support Laravel 5.5 LTS throughout it's support cycle.

**Comment by freekmurze** [comment]
I've fixed the docs so it now displays the right required version which is L5.5

> I'm just curious if you will continue to support Laravel 5.5 LTS throughout it's support cycle.

As soon there's a compelling reason in a future Laravel version, we'll drop L5.5 support.
