### ISSUE TITLE
How to use laravel-medialibrary without storing the images?

### ISSUE THREAD

**Issue by skalero01** [spatie/laravel-medialibrary#968]
Hi, i want to use laravel media library but without storing the images, i mean, use the models and databases but getting the original url

**For example:**
Add the url of the image on the model
```
$url = 'http://medialibrary.spatie.be/assets/images/mountain.jpg';
$newsItem
   ->addMediaFromUrl($url)
   ->toMediaCollection();
```

And when getting the media get the full url 

```
$url = $newsItem->getFirstMediaUrl(); 
// $url returns 'http://medialibrary.spatie.be/assets/images/mountain.jpg'
```

And maybe add a feature for adding a media conversion url to the media (for example thumb)
```
$url = 'http://medialibrary.spatie.be/assets/images/mountain.jpg';
$url_thumb = 'http://medialibrary.spatie.be/assets/images/mountain_thumb.jpg';
$newsItem
   ->addMediaFromUrl($url)
   ->addMediaFromUrl($url_thumb, 'thumb')
   ->toMediaCollection();
$url = $newsItem->getFirstMediaUrl('default', 'thumb'); 
// $url returns 'http://medialibrary.spatie.be/assets/images/mountain_thumb.jpg'
```

Is there a way to use laravel-medialibrary like this?

If there isnt exist, i'd like to help to do it, but i want to read your opinions.

Regards

**Comment by freekmurze** [comment]
This functionality isn't provided by the medialib. I don't see it coming to the package because presumed low usage does not warrant the extra complexity this change will bring.
