### ISSUE TITLE
getMedia() retrieves null

### ISSUE THREAD

**Issue by eichgi** [spatie/laravel-medialibrary#978]
I've been able to add and delete media but I cannot retrieve media with these methods:
getMedia() or getFirstMedia() (shows null). 

I already setup the interface and the trait over the model, images are storing in the folder. Any suggestion or do I need to do something else?

Laravel 5.6
MySQL 5.7
Laravel Medialibrary 7.0.0

**Comment by YoshiMannaert** [comment]
I'm having the same issue.

I've set up everything according to the docs and I'm able to store images and add conversions,
just retrieving the media doesn't seem to work.

Also using:
Laravel 5.6
MySQL 5.7
Laravel Medialibrary 7.0.0

**Comment by AEK-BKF** [comment]
Me too !
I confirm this issue with :
L 5.6 ,  Mysql 5.7 , Latest version of package !

**Comment by AEK-BKF** [comment]
The mistake is when we use :
` 'default_filesystem' => 'public';` 
But it works fine if we change it to :
` 'default_filesystem' => 'media';`
And of course don't forget to set :
```
 'media' => [
            'driver' => 'local',
            'root'   => public_path().'/media',
        ],
```

**Comment by eichgi** [comment]
@AEK-BKF I had tried already what you suggest and still not working

**Comment by AEK-BKF** [comment]
set your code and the error message please

**Comment by eichgi** [comment]
When I dump `dd($user->getMedia());` I got a null collection, but the reference and the media is stored.

**Comment by AEK-BKF** [comment]
Ok, try this when you store files :

`$user->addMediaFromRequest('myfile')->preservingOriginal()->toMediaCollection('myfiles');`

and when you retrieve your file, try this :
```
$myfiles = $user->getMedia('myfiles');
dd($myfiles[0]->getUrl());
```

**Comment by eichgi** [comment]
Debugging with your suggestions it works out, the "error" of retrieving null collection is because no parameter was passed, it works even if you do not define a media collection 
`getMedia("")`

So if you define no parameter it returns nothing, which is weird because is what the docs shows. Anyway thanks!

**Comment by brendt** [comment]
@eichgi looking in the media table in the database, what `collection_name` are media items saved to by default?

**Comment by eichgi** [comment]
Using public disk and defining no media it got saved as default on field collection_name.
`$user->addMediaFromRequest('avatar')->toMediaCollection();`

And now I can retrieve a collection with:
`dd($user->getMedia());`

After debugging and testing it seems we didn't realize the matter of defining collections and how to relate them. Right now they are working as expected.
