### ISSUE TITLE
Add docs on extending HasMediaTrait

### ISSUE THREAD

**Issue by robjbrain** [spatie/laravel-medialibrary#979]
Not sure if i'm just ignorant but I just spent ages trying to figure out how to extend the HasMediaTrait because you can't just do

```php
use Spatie\MediaLibrary\HasMedia\HasMediaTrait as BaseTrait;

trait HasMediaTrait extends BaseTrait
{

}
```

Eventually figured it's as simple as:

```php
use Spatie\MediaLibrary\HasMedia\HasMediaTrait as BaseTrait;

trait HasMediaTrait
{
    use BaseTrait;
}
```

Perhaps it's not worth putting in the docs because it's just php but it took me a while, so I figured it was worth suggesting to put it into the docs, after all you've put in a section on extending the Media model.

If you agree it could be added to the docs i'll submit a PR.

If not then at the very least someone will find this when they Google "extend HasMediaTrait"

:)

**Comment by freekmurze** [comment]
Let's leave it in this issue for now.
