### ISSUE TITLE
addMediaFromUrl & registerMediaConversions

### ISSUE THREAD

**Issue by ato10** [spatie/laravel-medialibrary#98]
It does not seem to work, conversion is not created

**Comment by freekmurze** [comment]
Do conversions in general work in your app?

**Comment by ato10** [comment]
```
$item->addMedia(...)->preservingOriginal()->toCollection('images');
```
works great
```
$item->addMediaFromUrl(...)->toCollection('images');
```
doesn't work using the same conversion definition
```
    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
             ->setManipulations(['w' => 78, 'h' => 78])
             ->performOnCollections('images');
    }
```

**Comment by freekmurze** [comment]
Is the image from the url being added to the medialibrary? What is it's
extension?

On Saturday, 7 November 2015, ato10 <notifications@github.com> wrote:

> $item->addMedia(...)->preservingOriginal()->toCollection('images');
>
> works great
>
> $item->addMediaFromUrl(...)->toCollection('images');
>
> doesn't work using the same conversion definition
>
>     public function registerMediaConversions()
>     {
>         $this->addMediaConversion('thumb')
>              ->setManipulations(['w' => 78, 'h' => 78])
>              ->performOnCollections('images');
>     }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spatie/laravel-medialibrary/issues/98#issuecomment-154744340>
> .
>


-- 
Freek Van der Herten
https://spatie.be
+32 495 84 27 91

**Comment by ato10** [comment]
OK sorry, my bad.
The problem is on .gif files extension.
Can I force another extension on downloaded images?
Thanks in advance

**Comment by ato10** [comment]
never mind, I found it.
Thanks for great work
