### ISSUE TITLE
base64 difference with Android

### ISSUE THREAD

**Issue by gauravmak** [spatie/laravel-medialibrary#980]
We are receiving base64 encoded string for the avatar of the user from Android app. While uploading the image, execution stops at https://github.com/spatie/laravel-medialibrary/blob/aecc201e7b43b9548556187e9aa15b42edf9dee1/src/HasMedia/HasMediaTrait.php#L170

Anyone knows if there is any difference in how Android and PHP encode/decode base64? How do we solve this?

PS - Is base64 the best way to deal with avatars from the mobile app?

**Comment by brendt** [comment]
Yes, base64 encoded uploads are a good way to handle API uploads.

Regarding the exception: I think you'll have to do some more debugging. What kind of base64 string is created on the client? Can you manually decode it in a standalone PHP script with the same result? What's the difference between the uploaded bas64 string and the decoded/encoded version which causes the exception? See: https://github.com/spatie/laravel-medialibrary/blob/aecc201e7b43b9548556187e9aa15b42edf9dee1/src/HasMedia/HasMediaTrait.php#L169

**Comment by gauravmak** [comment]
We found that using the [NO_WRAP](https://developer.android.com/reference/android/util/Base64.html#NO_WRAP) constant on the Android side created a base64 encoded string which worked properly. Thanks.
