### ISSUE TITLE
Parse error: syntax error, unexpected '=' (HasMedia/HasMediaTrait.php) line 159

### ISSUE THREAD

**Issue by roarkmccolgan** [spatie/laravel-medialibrary#985]
Hi,

I'm getting a strange error:
```
Parse error: syntax error, unexpected '=' (View: ... layouts/app.blade.php) (View: ... layouts/app.blade.php)
```
However error seems to be in HasMedia/HasMediaTrait.php line 159

Running Laravel 5.5 php7.1 via valet MBP

I've installed media library v7.0.5 added the interface and trait to my model:
```
namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\HasMedia;

class Category extends Model implements HasMedia
{
	use HasMediaTrait;
	... // rest of the model stuff
```

But fails with this error.

Any ideas?

Thanks!
Roark

**Comment by freekmurze** [comment]
I'm thinking this will be a problem caused by your specific project. Could you install the project in a vanilla Laravel app?

**Comment by roarkmccolgan** [comment]
I think you're right,
I'll close for now and post solution if I find it.

Thanks!

**Comment by hugofabricio** [comment]
@roarkmccolgan solved? I have the same problem.

**Comment by roarkmccolgan** [comment]
Hi @hugo i n bet found the source of the issue but re-publishing the config
file fixed my issue. It was as if the plugin never recognized the one from
source control

Hope that helps!

**Comment by roarkmccolgan** [comment]
I meant to say ‘I never found the source of the issue...’
