### ISSUE TITLE
vendor:publish views does not actually publish the views for responsive images

### ISSUE THREAD

**Issue by beartas** [spatie/laravel-medialibrary#989]
https://docs.spatie.be/laravel-medialibrary/v7/responsive-images/customizing-the-rendered-html
```
php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="views"
```
Looks like...
```
$this->publishes([
       __DIR__.'/../resources/views' => resource_path('views/vendor/medialibrary'),
    ], 'views');
```
may be missing from MediaLibraryServiceProvider@boot method

**Comment by clarkewing** [comment]
Duplicate of #964

**Comment by beartas** [comment]
[#964](url) is closed although the fix hasn't made it into the master branch

**Comment by freekmurze** [comment]
Forgot to push it, the fix is in the latest version now.

**Comment by beartas** [comment]
Merci beaucoup
