### ISSUE TITLE
Amazon S3 Integration Issue

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-medialibrary#99]
I followed the [ Media Library docs](http://medialibrary.spatie.be/) to the letter and was able to put a file locally using

```
$post->addMedia($pathToFile)
->preservingOriginal()
->toMediaLibrary();
```

I was amazed at how easy it was! However, when using the S3 example:

```
$post->addMedia($pathToFile)->toCollectionOnDisk('images', 's3');
```

I received the following error:
```
FatalErrorException in FilesystemManager.php line 166:
Class 'League\Flysystem\AwsS3v3\AwsS3Adapter' not found
```

The documentation doesn't say anything about using the Flysystem S3 component - is it actually required? Or am I doing something wrong? Regardless, I installed it and am still receiving the error.

**Comment by freekmurze** [comment]
This package uses Laravel's built in Cloud Filesystem. To use S3 you'll have to require `league/flysystem-aws-s3-v3`. It's mentioned in the [Laravel docs](http://laravel.com/docs/master/filesystem).

For clarity I'll mention this optional requirement in our docs.
