### ISSUE TITLE
V7 How to customize the responsive images file type?

### ISSUE THREAD

**Issue by zhi8617** [spatie/laravel-medialibrary#994]
Code like this ...  
```
 public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('images')
            ->format(Manipulations::FORMAT_JPG)
            ->withResponsiveImages();   
    }
```
“Conversions” files Has been successfully converted ,but Responsive images did not. 
I look at documents and issues, I still no idea.

Thank all for making this.

**Comment by brendt** [comment]
Hi @zhi8617 

Thanks for the question! At Spatie don't really have use cases for this. If you'd really want to save an image and its responsive variations in another format via the medialibrary, you could manually format the image before saving it as a media item.

If you're really interested in adding this feature, we might accept a PR if it could be done in a non-breaking way, so feel free to take the initiative.

At this point though, we're not going to invest time in this feature.
